# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> 는 일본에서 개발되는 웹 브라우저이에요. Firefox를 기반으로 <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>에서 더 나은 웹을 만들기 위해 만들어지고 있어요. 도움을 주고 싶으신가요? <label data-l10n-name="helpus-donateLink">기부를 고려해 주세요!</label>
icon-creator = 아이콘 제작자 : <label data-l10n-name="browser-logo-twitter">@CutterKnife_ 님</label> 와 <label data-l10n-name="brand-logo-twitter">@mwxdxx 님</label>
contributors = <label data-l10n-name="about-contributor">기여자 및 개발자 목록</label>도 확인 부탁드려요!
#################################################################### about:preferences ####################################################################

pane-design-title = 디자인
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = 변경 사항을 적용하려면 재시작해 주세요.
tab-width = 탭의 최소 너비
preferences-tabs-newtab-position = 새 탭 위치
open-new-tab-use-default = 
    .label = 기본 위치에서 새 탭 열기
open-new-tab-at-the-end = 
    .label = 탭 표시줄 끝에서 새 탭 열기
open-new-tab-next-to-current = 
    .label = 현재 탭 옆에 새 탭 열기
multirow-tabs-limit = 
    .label = 여러줄 탭에 줄 갯수 제한 사용
multirow-tabs-newtab = 
    .label = 탭의 맨 아래 줄 끝에 '새 탭 열기' 버튼을 배치하기
multirow-tabs-value = 여러줄 탭이 활성화됐을 때 줄 갯수
enable-tab-sleep = 
    .label = 탭 슬립 사용
tab-sleep-timeout-minutes-value = 탭이 (분) 동안 비활성화된 후 슬립 모드로 전환됩니다.
tab-sleep-settings-button = 설정...
tab-sleep-settings-dialog-title = 
    .title = 탭 슬립 설정
tab-sleep-settings-dialog-excludehosts-label = 제외할 호스트
tab-sleep-settings-dialog-excludehosts-label-2 = 한 줄에 호스트 하나를 입력합니다.
tab-sleep-tab-context-menu-excludetab = 탭을 슬립으로 전환하지 않기
enable-tab-scroll-change = 
    .label = 마우스로 스크롤하여 탭 전환
enable-tab-scroll-reverse = 
    .label = 탭 전환 스크롤을 반대로
enable-tab-scroll-wrap = 
    .label = 스크롤을 루프시키기
enable-double-click-block = 
    .label = 더블 클릭으로 탭 닫기
enable-show-pinned-tabs-title = 
    .label = 핀 꼽힌 탭의 제목 표시
tabbar-preference = 탭 바
tab-normal-mode = 
    .label = 기본
hide-horizontality-tabs = 
    .label = 가로 탭 바에서 탭 숨기기
verticalTab-setting = 
    .label = 세로 탭 바에 맞게 브라우저 최적화하기
move-tabbar-position = 
    .label = 도구 모음 아래에 탭 바 표시
tabbar-on-bottom = 
    .label = 창 하단에 탭 바 표시
tabbar-favicon-color = 
    .label = 탭 바의 배경 색을 웹 페이지에 맞추기
tabbar-style-preference = 탭 바 스타일
horizontal-tabbar = 
    .label = 가로 탭
tabbar-style-description = 이 설정을 완전히 적용하려면 { -brand-short-name } 을 재시작해야 해요.
multirow-tabbar = 
    .label = 여러줄 탭
vertical-tabbar = 
    .label = 세로 탭 바(실험적)
native-vertical-tab-show-right = 
    .label = 창 오른쪽에 세로 탭 바 표시하기
native-vertical-tab-show-padding = 
    .label = 탭 바 상단에 드래그용 여백 추가하기
hover-vertical-tab = 
    .label = 세로 탭 바 접기
floorp-show-vertical-tab-newtab-button = 
    .label = 세로 탭 바에 '새 탭 열기' 버튼 표시
floorp-show-vertical-tab-scrollbar = 
    .label = 세로 탭 바에서 스크롤바를 표시하기
TST = 트리 스타일 탭
about-TST = 트리 스타일 탭은 { -brand-short-name } 10 에서 내장되어 있던 수직 탭을 위한 애드온이에요. 이 애드온을 설치하면 { -brand-short-name } 고유의 설정을 사용하실 수 있어요.
treestyletab-Settings = 
    .label = 트리 스타일 탭 접기
sidebar-reverse-position-toolbar = 반대편에 사이드바 표시하기
bookmarks-bar-settings = 북마크 도구 모음(한 번에 하나의 옵션만 사용할 수 있음)
bookmarks-focus-mode = 
    .label = 네비게이션 바 위로 마우스를 가져가지 않는 한 북마크 도구 모음 숨기기
bookmarks-bottom-mode = 
    .label = { -brand-short-name } 하단에 북마크 툴바를 표시합니다.
navbar-settings = 네비게이션 바
show-nav-bar-bottom = 
    .label = { -brand-short-name } 하단에 도구모음 표시(실험적)
material-effect = 
    .label = Mica For Everyone으로 브라우저 디자인 수정 허용
disable-extension-check-compatibility-option = 
    .label = 확장 기능과의 브라우저 호환성을 검사하지 않기
other-preference = 기타 설정
enable-userscript = 
    .label = 레거시 구성 요소 사용하기
about-userscript = 이 기능을 활성화하면 예상치 못한 버그나 치명적인 오류가 발생할 수 있어요.
search-positon-top = 
    .label = 페이지 상단에 찾기 표시줄을 표시하기
allow-auto-restart = 
    .label = 재시작이 필요한 설정이 변경되면 자동으로 재시작하기
disable-fullscreen-notification = 
    .label = 전체 화면으로 전환할 때 알림을 표시하지 않기

## Browser Theme

system-color-settings = 몇몇 테마는 라이트 모드와 다크 모드를 모두 갖추고 있어요 - 어떤 모드를 사용할 지 선택해 주세요.
preferences-theme-appearance-header = 테마 모드
system-theme-dark = 
    .label = 다크
system-theme-light = 
    .label = 라이트
system-theme-auto = 
    .label = 시스템 테마를 따르기

## User interface preferences

ui-preference = 브라우저 모양
preferences-browser-appearance-description = { -brand-short-name }에서 사용할 기본 제공 외부 디자인을 선택해주세요. 일부 디자인은 사용자 설정과 호환되지 않을 수 있어요.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (지원 중단됨)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (지원 중단됨)
floorp-gnomeUI = 
    .label = GNOME Theme (지원 중단됨)

## Download Manager

download-notification-preferences = 다운로드 알림
start-always-notify = 
    .label = 다운로드 시작 시에만 알림
finish-always-notify = 
    .label = 다운로드가 완료된 경우에만 알림
always-notify = 
    .label = 다운로드 시작 시점과 다운로드 완료 시점에 알림
do-not-notify = 
    .label = 다운로드 알림 비활성화

## Sidebar

profiles-button-label = 프로파일 관리
floorp-help-button-label = { -brand-short-name } Support
appmenuitem-reboot = 
    .label = 재시작

## UserAgent

userAgent-preference = 사용자 에이전트
default-useragent-mode = 
    .label = Firefox 사용자 에이전트 사용(기본값)
windows-chrome-useragent-mode = 
    .label = Windows의 Chrome 사용자 에이전트 사용
macOS-chrome-useragent-mode = 
    .label = macOS의 Chrome 사용자 에이전트 사용
linux-chrome-useragent-mode = 
    .label = Linux의 Chrome 사용자 에이전트 사용
mobile-chrome-useragent-mode = 
    .label = iOS의 Chrome 사용자 에이전트 사용
use-custom-useragent-mode = 
    .label = 사용자 지정 사용자 에이전트 사용

## DMR UI

download-mgr-UI = 
    .label = SimpleUI 다운로드 관리자 활성화
downloading-red-color = 
    .label = 다운로드할 때 빨간색 다운로드 아이콘을 사용하세요.
sidebar-preferences = 사이드바
bsb-preferences = 브라우저 관리자 사이드바 설정
view-sidebar2-right = 
    .label = 오른쪽에 브라우저 관리자 사이드바를 표시하기
enable-sidebar2 = 
    .label = 브라우저 관리자 사이드바 활성화
visible-bms = 
    .label = 브라우저 관리자 사이드바 표시하기
hide-bms-to-unload-panel = 
    .label = 패널을 숨길 때 패널 언로드
enable-addons-in-sidebar2-with-experimental = 
    .label = 브라우저 관리자 사이드바에서 확장 프로그램 활성화(실험적)
enable-addons-in-sidebar2 = 
    .label = 브라우저 관리자 사이드바에서 확장 프로그램의 콘텐츠 스크립트 활성화
sidebar2-enable-addons-desc = 광고 차단 확장 프로그램 및 기타 확장 프로그램이 사이드바에서 작동하게 되어요. 하지만 모든 확장 프로그램이 작동하는 것은 아니에요.
custom-URL-option = 웹 패널 URL 설정
set-custom-URL-button = 
    .label = 사용자 지정 URL 설정...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = 브라우저 관리자 사이드바
bsb-context = 다음 컨테이너를 사용하기
bsb-userAgent-label = 
    .label = 이 웹 패널에서 모바일 사용자 에이전트 사용
bsb-width = 너비(0으로 설정하면 전역 값이 사용됨)
bsb-page = 열 페이지
bsb-add = 브라우저 관리자 사이드바에 웹 패널 추가
bsb-setting = 웹 패널 설정
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = 웹사이트
sidebar2-pref-delete = 
    .label = 삭제
sidebar2-pref-setting = 
    .label = 설정
sidebar2-global-width = 글로벌 웹 패널 너비
use-icon-provider-option = 아이콘 제공 서비스
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (중국에서 사용 가능)
use-icon-provider-option-hatena = 
    .label = Hatena (중국에서 사용 가능)
memory-and-performance = 메모리 및 성능
min-memory = 
    .label = 최소 메모리 사용량(낮은 성능)
balance-memory = 
    .label = 메모리 사용량과 성능의 균형
max-memory = 
    .label = 최고 성능(높은 메모리 사용량)
delete-border-and-roundup-option = 
    .label = 페이지 모서리 둥글게 처리

## DualTheme

dualtheme-enable = 
    .label = 듀얼 테마 사용
newtab-background = { -brand-short-name } 홈 배경
newtab-background-random-image = 
    .label = Unsplash의 무작위 이미지
newtab-background-gradation = 
    .label = 그라데이션
newtab-background-not-background = 
    .label = 배경 비활성화
newtab-background-selected-image = 
    .label = 사용자 지정 폴더...
newtab-background-selected-one-image = 
    .label = 커스텀 이미지...
newtab-background-folder = 이 폴더의 이미지를 사용합니다:
newtab-background-image = 사용할 이미지:
newtab-choose-image = 이미지를 선택:
newtab-background-folder-reload = 
    .label = 이미지 다시 로드
newtab-background-folder-default = 
    .label = 기본값 복원
newtab-background-folder-open = 
    .label = 폴더 열기
newtab-background-folder-choose = 이미지 폴더 선택...
newtab-background-image-choose = 이미지를 선택:
newtab-background-extensions = 다음 파일 확장자(","로 구분)의 이미지 사용
disable-blur-on-newtab = 
    .label = { -brand-short-name } 홈의 흐림 효과 끄기
disable-releasenote-on-newtab = 
    .label = { -brand-short-name } 홈의 릴리스 노트 및 지원 URL 표시 끄기
disable-imagecredit-on-newtab = 
    .label = { -brand-short-name } 홈에서 이미지 크레딧(Unsplash) 끄기

## Lepton Preferences

about-lepton = Lepton으로 { -brand-short-name } 커스터마이즈
lepton-preference-button = 
    .label = Lepton 설정...
    .accesskey = L
lepton-header = Lepton 설정
lepton-preference = Lepton 설정
photon-mode = 
    .label = Photon 디자인 사용
lepton-mode = 
    .label = Lepton 디자인 사용
protonfix-mode = 
    .label = 조정된 Proton 디자인 사용
autohide-preference = 브라우저 요소 자동 숨기기
floorp-lepton-enable-tab-autohide = 
    .label = 탭 자동 숨기기
floorp-lepton-enable-navbar-autohide = 
    .label = 도구 모음 자동 숨기기
floorp-lepton-enable-sidebar-autohide = 
    .label = 사이드바 자동 숨기기
floorp-lepton-enable-urlbar-autohide = 
    .label = 주소 표시줄 자동 숨기기
floorp-lepton-enable-back-button-autohide = 
    .label = 자동으로 뒤로 숨기기 버튼
floorp-lepton-enable-forward-button-autohide = 
    .label = 앞으로 가기 버튼 자동 숨기기
floorp-lepton-enable-page-action-button-autohide = 
    .label = 주소 표시줄의 버튼 자동 숨기기
floorp-lepton-enable-toolbar-overlap = 
    .label = 웹사이트 콘텐츠 위에 툴바 표시
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = "가로" 콘텐츠를 표시할 때 툴바 자동 숨기기
hide-preference = 브라우저 요소 관리
floorp-lepton-enable-tab_icon-hide = 
    .label = 탭 아이콘 숨기기
floorp-lepton-enable-tabbar-hide = 
    .label = 탭 표시줄 숨기기
floorp-lepton-enable-navbar-hide = 
    .label = 도구 모음 숨기기
floorp-lepton-enable-sidebar_header-hide = 
    .label = 사이드바 헤더 숨기기
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = 주소 표시줄 아이콘 숨기기
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = 책갈피 막대 아이콘 숨기기
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = 북마크 바 레이블 숨기기
floorp-lepton-enable-disabled_menu-hide = 
    .label = 비활성화된 컨텍스트 메뉴 항목 숨기기
floorp-lepton-disable-userChrome-icon = 
    .label = Lepton의 컨텍스트 메뉴 및 패널 메뉴 아이콘 비활성화하기
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Lepton의 컨텍스트 메뉴 아이콘 활성화하기
positon-preferences = 위치 조정
floorp-lepton-enable-centered-tab = 
    .label = 탭의 중앙 레이블
floorp-lepton-enable-centered-urlbar = 
    .label = 주소 표시줄의 중앙 텍스트
floorp-lepton-enable-centered-bookmarkbar = 
    .label = 중앙 북마크 모음 항목
urlbar-preferences = 주소 표시줄
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = 주소 표시줄 아이콘을 왼쪽으로 이동
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = 입력할 때 '이동' 버튼을 표시하기
floorp-lepton-enable-always-show-page_action = 
    .label = 주소 표시줄에 항상 페이지 작업 표시
tabbar-preferences = 탭 바
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = 제목 표시줄의 탭 바
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = 탭 표시줄과 도구 모음 결합
lepton-sidebar-preferences = 사이드바
floorp-lepton-enable-overlap-sidebar = 
    .label = 웹사이트 콘텐츠 위에 사이드바 표시
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } 홈(기본값)
floorp-home-prefs-content-header = { -brand-short-name } 홈 콘텐츠
floorp-home-prefs-content-description = { -brand-short-name } 홈페이지에서 보고 싶은 콘텐츠를 선택합니다.

## Notes

floorp-notes = { -brand-short-name } 참고
restore-from-backup = 백업에서 노트 복원
enable-notes-sync = 
    .label = { -brand-short-name } 노트 동기화 활성화
about-notes-backup-tips = { -brand-short-name } Notes는 다른 기기와 노트를 동기화하기 위해 Firefox Sync를 사용합니다. 만약 당신의 노트를 잃었다면, 백업으로부터 복원할 수 있습니다. 백업은 { -brand-short-name }를 시작할때 생성됩니다.
notes-sync-description = 이렇게 하면 동기화 중 노트 덮어쓰기로 인해 콘텐츠가 손실되는 문제를 해결할 수 있습니다.
backuped-time = 백업 위치
notes-backup-option = 백업 설정
backup-option-button = 백업 설정...
restore-from-backup-prompt-title = { -brand-short-name } Notes 복원 서비스
restore-from-this-backup = 노트를 이 백업 상태로 복원하시겠습니까?
restore-button = 복원

## user.js

header-userjs = user.js
userjs-customize = user.js로 { -brand-short-name } 커스터마이즈
about-userjs-customize = user.js는 { -brand-short-name } 를 커스터마이즈할 수 있는 설정 파일입니다. user.js 파일은 인터넷에서 다운로드되며 현재 user.js 파일을 덮어씁니다. 계속하기 전에 현재 user.js 파일을 백업하세요. { -brand-short-name }을 재시작하면 user.js 설정이 자동으로 적용됩니다.
userjs-label = user.js 목록
userjs-prompt = 이 user.js 를 적용하시겠어요?
apply-userjs-attention = 새 user.js를 적용하면 현재 user.js 파일을 덮어쓰게 됩니다.
apply-userjs-attention2 = 계속하기 전에 현재 user.js 파일을 백업하세요.
userjs-button = user.js 설정...
userjs-select-option = { -brand-short-name } 에서 사용되는 user.js를 관리하여 성능과 개인정보 보호를 개선하세요.
apply-userjs-button = 적용하기

## userjs Options

default-userjs-label = { -brand-short-name } Default
about-default-userjs = 원격 측정 비활성화. 다양한 커스텀이 활성화된 균형 잡힌 { -brand-short-name } 설정이예요.
Securefox-label = Yokoffing Securefox
about-Securefox = 기본적으로 HTTPS. 사이트 격리를 통한 완벽한 쿠키 보호. 향상된 상태 및 네트워크 파티셔닝. 기타 다양한 개선 사항.
default-label = Yokoffing Default
about-default = 필요한 것은 모두. 깨질 일이 없습니다. 이것이 당신의 user.js입니다.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Firefox의 브라우징 속도를 대폭 향상시킵니다. Chrome을 압도하세요!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = 새 탭 페이지를 깔끔하게 정리합니다. Pocket을 제거. 컴팩트 모드를 옵션으로 부활. 웹 페이지 알림, 팝업 및 기타 성가신 알림을 정지.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Edge와 같은 부드러운 스크롤을 최애의 브라우저에서.
select-workspace = 워크스페이스 선택
workspace-select-icon = 워크스페이스 아이콘 선택
    .label = 워크스페이스 아이콘 선택
workspace-select-container = 컨테이너 탭 선택
    .label = 컨테이너 탭 선택
workspace-customize = 
    .title = 워크스페이스 커스터마이즈
floorp-no-workspace-container = 
    .label = 컨테이너 없음
workspace-icon-article = 
    .label = 기사
workspace-icon-book = 
    .label = 책
workspace-icon-briefcase = 
    .label = 직장
workspace-icon-cart = 
    .label = 쇼핑
workspace-icon-chat = 
    .label = 잡담
workspace-icon-chill = 
    .label = 사생활
workspace-icon-circle = 
    .label = 서클
workspace-icon-compass = 
    .label = 나침반
workspace-icon-code = 
    .label = 코드
workspace-icon-dollar = 
    .label = 은행
workspace-icon-fence = 
    .label = 울타리
workspace-icon-fingerprint = 
    .label = 개인
workspace-icon-food = 
    .label = 음식
workspace-icon-fruit = 
    .label = 과일
workspace-icon-game = 
    .label = 게임
workspace-icon-gear = 
    .label = 기어
workspace-icon-gift = 
    .label = 선물
workspace-icon-key = 
    .label = 열쇠
workspace-icon-lightning = 
    .label = 번개
workspace-icon-network = 
    .label = 인터넷
workspace-icon-notes = 
    .label = 메모
workspace-icon-paint = 
    .label = 페인트
workspace-icon-photo = 
    .label = 사진
workspace-icon-pin = 
    .label = 핀
workspace-icon-pet = 
    .label = 반려동물
workspace-icon-question = 
    .label = 질문
workspace-icon-smartphone = 
    .label = 스마트폰
workspace-icon-star = 
    .label = 스타
workspace-icon-tree = 
    .label = 나무
workspace-icon-vacation = 
    .label = 휴가
workspace-icon-love = 
    .label = 하트
workspace-icon-moon = 
    .label = 달
workspace-icon-music = 
    .label = 음악
workspace-icon-user = 
    .label = 사용자
# Custom Keyboard Shortcuts
floorp-CSK-title = 커스텀 키보드 단축키
floorp-CSK-description = { -brand-short-name }의 키보드 단축키를 커스터마이즈하세요. { -brand-short-name }는 80개 이상의 커스터마이즈 가능한 키보드 단축키를 제공합니다! 중복된 키보드 단축키는 작동하지 않습니다. 변경된 설정을 적용하시려면 { -brand-short-name }를 재시작해 주세요.
disable-fx-actions = 
    .label = Mozilla Firefox의 키보드 단축키 비활성화하기
customize-Action = 
    .label = 바로 가기 추가
remove-Action = 
    .label = 바로 가기 제거
CSK-reset-title = 커스텀 키보드 단축키 초기화
CSK-reset-description = 커스텀 키보드 단축키를 { -brand-short-name }의 기본값으로 설정합니다.
CSK-reset-label = 커스텀 키보드 단축키 초기화
CSK-reset-button = 기본값 복원
CSK-manage-title = 키보드 단축키 관리
CSK-remove-shortcutkey = 사용자 지정 키보드 단축키를 제거하시겠습니까?
CSK-remove-shortcutkey-description = 이 키보드 단축키를 제거하시겠습니까?
CSK-restore-default = 기본값 복원?
CSK-restore-default-description = { -brand-short-name }의 기본 단축키를 복원하시겠어요? 현재 설정된 단축키는 잃게 되어요.
CSK-reboot-browser-label = { -brand-short-name } 을 재시작하여 다음 설정을 적용합니다.
CSK-reboot-browser-button = { -brand-short-name }를 재시작하기
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = 현재 키보드 단축키: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = 현재 키보드 단축키: { $key }.
CSK-keyborad-shortcut-is-changed = (적용되지 않음)
floorp-custom-actions-tab-action = 탭 액션
floorp-custom-actions-page-action = 페이지 액션
floorp-custom-actions-visible-action = 표시방법 액션
floorp-custom-actions-search-action = 검색 액션
floorp-custom-actions-tools-action = 도구 액션
floorp-custom-actions-bookmark-action = 북마크 액션
floorp-custom-actions-open-page-action = 페이지 열기 액션
floorp-custom-actions-history-action = 기록 액션
floorp-custom-actions-pip-action = 화면 속 화면 액션
floorp-custom-actions-downloads-action = 다운로드 액션
floorp-custom-actions-sidebar-action = 사이드바 액션
floorp-custom-actions-bms-action = 브라우저 관리자 사이드바 액션
floorp-custom-actions-split-view-action = 분할 뷰 액션
floorp-custom-actions-workspaces-action = 워크스페이스 액션
floorp-custom-actions-custom-action = 커스텀 액션(실험적)

## Mouse Gestures

mouse-gesture = 마우스 제스처
mouse-gesture-description = { -brand-short-name }에서 마우스 제스처를 사용하려면 Gesturefy가 설치되어 있어야 합니다.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy는 브라우저에 마우스 제스처를 추가하는 확장 기능입니다. 만약 { -brand-short-name }가 이 확장 기능을 감지한다면, { -brand-short-name }에서만 사용할 수 있는 제스처를 추가할 거예요. 또, 이 애드온은 새로운 탭에서도 작동해요!
# Translate
TWS = 웹 페이지 번역
about-TWS = Google 또는 Yandex를 사용하여 페이지를 실시간으로 번역하세요. 선택한 텍스트 또는 전체 페이지를 번역할 수도 있습니다.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = 개인정보 보호 허브
block-more-tracker = 더 많은 광고 및 트래커 차단
block-tracker = 이 섹션에서는 광고 및 트래커를 차단하도록 설계된 확장 프로그램들을 소개합니다.
view-at-AMO = addons.mozilla.org에서 이 애드온 보기
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin은 광고, 광범위한 추적기 및 추가 위험 사이트를 차단합니다.
Facebook-Container = Facebook Container
about-Facebook-Container = Facebook이 웹에서 사용자를 추적하지 못하도록 차단하세요. Facebook 컨테이너 확장 프로그램을 사용하면 웹 활동을 제어하고 Facebook으로부터 격리할 수 있습니다.

## Fingerprinting

fingerprint-header = 지문 및 IP 주소 유출 방지
block-fingerprint = 지문 인식은 브라우저와 운영 체제의 고유한 기능에 의존하는 추적 메커니즘입니다. 이 섹션에는 기본 차단을 넘어 이 보호 기능을 더욱 강화하는 설정이 포함되어 있습니다.
enable-firefox-fingerprint-protections = 지문에 대한 강력한 보호 기능 사용
about-firefox-fingerprint-protection = Firefox에서 보호 기능을 활성화하면 강제 라이트 모드, 일부 API 비활성화 등이 포함됩니다. 일부 사이트가 손상될 수 있습니다.
fingerprint-Protection = 
    .label = 지문 인식 방지 보호
html5-canvas-prompt-settings = 
    .label = HTML5 이미지 데이터에 대한 액세스 확인 프롬프트 자동 거부
canvas-prompt = 수동으로 허용하지 않는 한 웹 사이트에서 캔버스 읽기 프롬프트를 사용하지 못하도록 합니다.
disable-webgl = 
    .label = WebGL 비활성화
about-webgl = WebGL은 그래픽을 렌더링하는 데 사용되는 자바스크립트 API로, GPU를 식별하는 데 사용될 수 있습니다.
Canvas-Blocker = 캔버스 차단기
about-CB = 이 애드온은 핑거프린팅 기법에 사용되는 데이터를 스푸핑합니다.
WebRTC-connection = WebRTC는 실시간 통화를 제공하는 표준입니다. 이 설정을 비활성화하면 Discord 등을 사용할 수 없게 됩니다.
WebRTC = 
    .label = WebRTC 연결 활성화
################################################################### browser ###############################################################

rest-mode = 휴식 중...
rest-mode-description = { -brand-short-name }가 현재 일시 중단되었어요. 계속하시려면 Enter 또는 확인을 눌러주세요.
Sidebar2 = 
    .label = 브라우저 관리자 사이드바
    .tooltiptext = 사이드바 표시 전환
sidebar2-mute-and-unmute = 
    .label = 이 패널 음소거/음소거 해제
sidebar2-unload-panel = 
    .label = 이 패널 언로드
sidebar2-change-ua-panel = 
    .label = 모바일 사용자 에이전트 전환
sidebar2-delete-panel = 
    .label = 이 패널 삭제
sidebar2-change-zoom-level = 
    .label = 확대 정도 바꾸기
sidebar2-zoom-in = 
    .label = 확대
sidebar2-zoom-out = 
    .label = 축소
sidebar2-reset-zoom = 
    .label = 확대 초기화
sidebar2-close-button = 
    .tooltiptext = 사이드바 닫기
sidebar-back-button = 
    .tooltiptext = 뒤로
sidebar-forward-button = 
    .tooltiptext = 앞으로
sidebar-reload-button = 
    .tooltiptext = 다시 로드
sidebar-go-index-button = 
    .tooltiptext = 홈으로 이동
sidebar-muteAndUnmute-button = 
    .tooltiptext = 사이드바 음소거/음소거 해제
sidebar2-browser-manager-sidebar = 브라우저 관리자
show-browser-manager-sidebar = 
    .tooltiptext = { sidebar2-browser-manager-sidebar } 사이드바 표시
sidebar2-bookmark-sidebar = 북마크
show-bookmark-sidebar = 
    .tooltiptext = { sidebar2-bookmark-sidebar } 사이드바 표시
sidebar2-history-sidebar = 역사
show-history-sidebar = 
    .tooltiptext = { sidebar2-history-sidebar } 사이드바 표시
sidebar2-download-sidebar = 다운로드
show-download-sidebar = 
    .tooltiptext = { sidebar2-download-sidebar } 사이드바 표시
sidebar2-notes-sidebar = 참고
show-notes-sidebar = 
    .tooltiptext = { sidebar2-notes-sidebar } 사이드바 표시
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = 애드온 및 테마
sidebar2-hide-sidebar-button = 
    .tooltiptext = 브라우저 관리자 사이드바 숨기기
sidebar-passwords-button = 
    .tooltiptext = 비밀번호
sidebar-preferences-button = 
    .tooltiptext = 설정
sidebar-keepWidth-button = 
    .tooltiptext = 이 패널에서 현재 너비를 계속 사용합니다.
sidebar2-keep-width-for-global = 
    .label = 현재 웹 패널 폭을 모든 웹 패널에 적용하기
bsb-context-add = 
    .label = 웹 패널에 페이지 추가...
bsb-context-link-add = 
    .label = 웹 패널에 링크 추가...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = 프로필 디렉토리 열기
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = 브라우저 CSS 파일 다시 빌드
    .accesskey = R
make-browsercss-file = 
    .label = 브라우저 CSS 파일 생성
    .accesskey = M
open-css-folder = 
    .label = CSS 폴더 열기
    .accesskey = O
edit-userChromeCss-editor = 
    .label = userChrome.css 파일 편집
edit-userContentCss-editor = 
    .label = userContent.css 파일 편집
not-found-editor-path = CSS 파일 편집기를 찾을 수 없습니다.
set-pref-description = 사용하려는 CSS 파일 편집기의 파일 위치를 입력합니다:
rebuild-complete = 재구축이 완료되었습니다.
please-enter-filename = 파일 이름을 입력하세요.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = 닫힌 탭 다시 열기
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = 하위 테마로 사용
dual-theme-disable-addon-button = 하위 테마 비활성화
dual-theme-enabled-heading = 하위 테마로 사용
##################################################################### toolbar ###############################################################

status-bar = 
    .label = 상태 표시줄
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] 트리 스타일 탭 패널 열기
gf-floorp-open-tree-style-tab-description = 트리 스타일 탭을 사이드바에서 열어요.
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] 북마크 패널 열기
gf-floorp-open-bookmarks-sidebar-description = 사이드바에서 북마크 패널 열기
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] 기록 패널 열기
gf-floorp-open-history-sidebar-description = 기록을 북마크 패널에서 열어요
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] 동기화된 탭 패널을 열기
gf-floorp-open-synctabs-sidebar-description = 동기화된 탭을 사이드바에서 열어요
gf-floorp-close-sidebar-name = [{ -brand-short-name }] 사이드 바 닫기
gf-floorp-close-sidebar-description = 사이드바 닫기
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] BMS 열기
gf-floorp-open-browser-manager-sidebar-description = 웹 패널이 로드된 경우, 브라우저 관리자 사이드바를 열어요.
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] BMS 닫기
gf-floorp-close-browser-manager-sidebar-description = 브라우저 관리자 사이드바 닫기
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] BMS 표시 전환
gf-floorp-show-browser-manager-sidebar-description = 브라우저 관리자 사이드바 토글
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] 상태 표시줄 숨기기
gf-floorp-hide-statusbar-description = 상태 표시줄 숨기기
gf-floorp-show-statusbar-name = [{ -brand-short-name }] 상태 표시줄 전환
gf-floorp-show-statusbar-description = 상태 표시줄 표시 또는 숨기기
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] 선택한 애드온 사이드바 열기
gf-floorp-open-extension-sidebar-description = 사이드 바에서 선택한 애드온 열기
gf-floorp-open-extension-sidebar-settings-addons-id = 사이드바 애드온
gf-floorp-open-extension-sidebar-settings-addons-id-description = 사이드바의 애드온 열기 확장
gf-floorp-open-extension-sidebar-settings-list-default = 부가 기능을 선택하세요.
gf-floorp-open-extension-sidebar-settings-list-unknwon = 알 수 없는 애드온
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = 새로운 업데이트를 찾았어요!
update-portable-notification-found-message = 업데이트 다운로드 중...
update-portable-notification-ready-title = 업데이트 준비 완료!
update-portable-notification-ready-message = { -brand-short-name }는 다음에 실행될 때 업데이트됩니다.
update-portable-notification-success-title = 업데이트에 성공했습니다!
update-portable-notification-success-message = 업데이트 성공! { -brand-short-name }의 새로운 버전을 즐겨주세요!
update-portable-notification-failed-title = 업데이트하지 못했습니다.
update-portable-notification-failed-redirector-message = 업데이트하지 못했습니다. 브라우저를 다시 시작하면 이 문제가 해결될 수 있습니다.
update-portable-notification-failed-prepare-message = 업데이트를 준비하지 못했습니다.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Portable 업데이트
floorp-update-application-auto-enabled-option = 
    .label = { -brand-short-name } Portable에 대한 업데이트를 자동으로 확인합니다. (권장)
##################################################################### Open link in external ###############################################################
openInExternal-title = 외부 브라우저에서 열기
open-link-in-external-enabled-option = 
    .label = '외부 브라우저에서 열기' 기능 사용
open-link-in-external-select-browser-option = 열 브라우저 선택
open-link-in-external-select-browser-option-default = 
    .label = 기본 브라우저
open-link-in-external-tab-context-menu = 외부 브라우저에서 열기
open-link-in-external-tab-dialog-title-error = 오류가 발생했습니다:
open-link-in-external-tab-dialog-message-default-browser-not-found = 기본 브라우저를 찾을 수 없거나 구성되지 않았습니다.
open-link-in-external-tab-dialog-message-selected-browser-not-found = 선택한 브라우저가 존재하지 않습니다.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = 신규
memo-title-input-placeholder = 여기에 제목을 입력하세요.
memo-input-placeholder = 여기에 메모를 작성하거나 붙여넣기
delete-memo = 삭제
save-memo = 저장
memo-welcome-title = 환영합니다!
memo-first-tip = { -brand-short-name } Notes에 오신 것을 환영합니다! 사용방법을 설명할게요!
memo-second-tip = { -brand-short-name } Notes는 여러 장치에서 동기화되는 메모 기능이예요. 동기화 하기 위해서는 Mozilla 계정으로 { -brand-short-name } 에 로그인해야 해요.
memo-third-tip = { -brand-short-name } Notes 는 { -brand-short-name } 에 저장되어, Firefox Sync를 사용하여 여러 장치에 동기화되어요. Firefox Sync는 동기화하는 내용을 Mozilla 계정의 비밀번호로 암호화하기에 누구에게도 내용이 알려질 걱정이 없어요.
memo-import-data-tip = Firefox 동기화는 백업 서비스가 아닙니다. 백업을 생성하는 것이 좋습니다.
memo-new-title = 새 노트
chage-view-mode = 보기/편집 모드 전환
readonly-mode = 오프라인(읽기 전용)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = 애블레이즈 지원
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = 다운로드 지우기
    .accesskey = D
    .tooltiptext = 다운로드 지우기
floorp-show-all-downloads = 
    .label = 모든 다운로드 표시
    .accesskey = S
    .tooltiptext = 모든 다운로드 표시
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = 새로운 워크스페이스 만들기
    .tooltiptext = 새로운 워크스페이스 만들기
workspaces-manage-workspaces-button = 
    .label = 워크스페이스 관리...
    .tooltiptext = 워크스페이스 관리
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = 워크스페이스 이름 바꾸기
    .accesskey = R
delete-this-workspace = 
    .label = 워크스페이스 삭제
    .accesskey = D
manage-this-workspaces = 
    .label = 워크스페이스 관리...
    .accesskey = M
workspace-new-default-name = 새로운 워크스페이스
workspace-default-name = 기본
move-tab-another-workspace = 
    .label = 다른 워크스페이스로 이동
rename-workspace-prompt-title = 워크스페이스 이름 바꾸기
rename-workspace-prompt-text = 워크스페이스 이름을 입력하세요. 대부분의 문자와 기호를 사용할 수 있어요.
workspaces-toolbar-button = 워크스페이스
    .label = 워크스페이스
    .tooltiptext = 워크스페이스 선택...

## Preferences

enable-workspaces = 
    .label = 워크스페이스 사용하기
    .tooltiptext = 워크스페이스 사용하기
workspace-notice = 워크스페이스는 툴바에 버튼이 놓여져 있지 않다면 이 설정이 활성화되어있어도 작동하지 않아요. 완전히 워크스페이스를 비활성화하고 싶으실 때 이 설정을 이용해 주세요.
enable-workspaces-with-experimental = 
    .label = 워크스페이스를 사용하기 (실험적)
    .tooltiptext = 워크스페이스를 사용하기 (실험적)
workspace-warning = 워크스페이스는 탭 그룹 애드온과 같이 사용할 수 없습니다. 만약 탭 그룹 애드온을 사용하고 싶으시다면, 워크스페이스를 비활성화하고, { -brand-short-name } 를 재시작해 주세요.
category-workspaces = 
    .label = 워크스페이스
    .tooltiptext = 워크스페이스
pane-workspaces-title = 워크스페이스
floorp-workspaces-title = { -brand-short-name } 워크스페이스
floorp-workspace-settings-button = 워크스페이스 설정...
floorp-preferences-label = Preferences
floorp-extensions-label = Extensions
floorp-private-label = Private
change-to-close-workspace-popup-option = 
    .label = 워크스페이스를 선택하면 워크스페이스 닫기 팝업이 나타납니다.
manage-workspace-on-bms-option = 
    .label = 브라우저 관리자 사이드바에서 워크스페이스 관리하기
show-workspace-name-option = 
    .label = 탭 바의 워크스페이스 버튼에 워크스페이스 이름 표시
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = 공유 모드
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Firefox 계정에 로그인
welcome-to-floorp = { -brand-short-name }에 오신 것을 환영합니다!
welcome-describe-floorp = { -brand-short-name } 은 다양한 환경을 지원하고 Firefox에 기반하는 유연한 브라우저에요.
welcome-start-setup = 준비됐나요?
welcome-skip-to-start-browsing = 브라우징 시작으로 건너뛰기
welcome-select-preferences-template = 템플릿 선택하기
welcome-minimum-template = 기본
welcome-enable-basic-features = 기본적인 기능과 설정으로 심플한 경험을.
welcome-medium-template = 기본값
welcome-enable-some-features = 더 좋은 경험을 위해 추가 기능과 설정을 사용
welcome-maximum-template = 고급
welcome-enable-most-of-features = 고급 기능과 설정을 사용합니다. Geek한 분에게 추천해요!
welcome-go-next-setup = 다음
welcome-select-browser-design = 브라우저 디자인 선택
welcome-describe-browser-design = { -brand-short-name } 의 다양한 서드파티 디자인을 골라보세요! 사용하시는 OS에 딱 맞는 디자인도 환경설정에서 만나보실 수 있어요.
welcome-design-lepton-name = Lepton Original 디자인
welcome-design-photon-name = Lepton Photon 디자인
welcome-design-ProtonFix-name = Lepton ProtonFix 디자인
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial 디자인
welcome-design-firefox-proton-name = Firefox Proton 디자인
welcome-import-data = 브라우저 데이터 가져오기
welcome-import-data-description = 순식간에 설정! 이전 브라우저에서 북마크나 비밀번호같은 것들을 가져올 수 있어요! Firefox 사용자는 Firefox Sync에서 동기화할 수 있어요.
welcome-import-data-button = 데이터 가져오기...
welcome-import-data-skip = 가져오기 건너뛰기
welcome-select-button = 선택
welcome-finish-setup = 설정 완료!
welcome-finish-setup-description = 모든 준비가 끝났어요! 세로 탭 및 워크스페이스와 같은 기능은 { -brand-short-name } 의 설정에서 찾아볼 수 있어요. { -brand-short-name } 를 즐기세요!
welcomet-finish-setup = 웹 브라우징 시작
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = 키보드 단축키
    .tooltiptext = 키보드 단축키
category-CSK-title = 키보드 단축키
shortcutkey-customize = 
    .title = 키보드 단축키
select-shortcutkeyAction = 트리거할 작업을 선택합니다.
shortcutkey-customize-key-list-placeholder = 키보드 단축키가 여기에 표시됩니다.
shortcut-key-label = 키보드 단축키
start-input-button-listen = 기록 시작
end-input-button-listen = 기록 종료
shortcut-key-description = "기록 시작"을 클릭하고 단축키로서 사용할 키를 입력하세요. 여러개의 키를 사용할 수도 있어요. 다른 액션과 중복하지 않도록 해주세요.
floorp-custom-actions-open-new-tab = 새 탭 열기
    .label = 새 탭 열기
floorp-custom-actions-close-tab = 현재 탭 닫기
    .label = 현재 탭 닫기
floorp-custom-actions-open-new-window = 새 창 열기
    .label = 새 창 열기
floorp-custom-actions-open-new-private-window = 새 비공개 창 열기
    .label = 새 비공개 창 열기
floorp-custom-actions-close-window = 현재 창 닫기
    .label = 현재 창 닫기
floorp-custom-actions-restore-last-session = 마지막 세션 복원
    .label = 마지막 세션 복원
floorp-custom-actions-restore-last-window = 마지막 창 복원
    .label = 마지막 창 복원
floorp-custom-actions-show-next-tab = 다음 탭 표시
    .label = 다음 탭 표시
floorp-custom-actions-show-previous-tab = 이전 탭 표시
    .label = 이전 탭 표시
floorp-custom-actions-show-all-tabs-panel = 모든 탭 표시 패널
    .label = 탭 목록 표시
floorp-custom-actions-send-with-mail = 메일로 보내기
    .label = 이메일을 통해 보내기
floorp-custom-actions-save-page = 페이지 저장
    .label = 페이지 저장
floorp-custom-actions-print-page = 인쇄 페이지
    .label = 인쇄 페이지
floorp-custom-actions-mute-current-tab = 현재 음소거/음소거 해제 탭 전환
    .label = 현재 음소거/음소거 해제 탭 전환
floorp-custom-actions-toggle-bookmark-toolbar = 북마크 도구 모음의 표시를 전환하기
    .label = 북마크 도구 모음 토글
floorp-custom-actions-show-source-of-page = 페이지 소스 표시
    .label = 페이지 소스 열기
floorp-custom-actions-show-page-info = 페이지 정보 표시
    .label = 페이지 정보 열기
floorp-custom-actions-zoom-in = 확대
    .label = 확대
floorp-custom-actions-zoom-out = 축소
    .label = 축소
floorp-custom-actions-reset-zoom = 줌 초기화
    .label = 줌 초기화
floorp-custom-actions-back = 뒤로
    .label = 뒤로
floorp-custom-actions-forward = 앞으로
    .label = 앞으로
floorp-custom-actions-reload = 다시 로드
    .label = 다시 로드
floorp-custom-actions-stop = 중지
    .label = 중지
floorp-custom-actions-force-reload = 강제 재로드
    .label = 강제 재로드
floorp-custom-actions-search-in-this-page = 이 페이지에서 검색
    .label = 페이지에서 찾기
floorp-custom-actions-show-next-search-result = 이 페이지 결과에서 다음 검색어 표시
    .label = 다음 '페이지에서 찾기' 결과
floorp-custom-actions-show-previous-search-result = 이 페이지 결과에서 이전 검색어 표시
    .label = 이전 '페이지에서 찾기' 결과
floorp-custom-actions-search-the-web = 웹 검색
    .label = 웹 검색
floorp-custom-actions-open-migration-wizard = 마이그레이션 마법사 열기
    .label = 마이그레이션 마법사 열기
floorp-custom-actions-quit-from-application = 애플리케이션에서 종료
    .label = 종료 { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = 툴바 커스터마이징
    .label = 사용자 지정 열기 { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = 오프라인 모드로 전환
    .label = 오프라인 모드로 전환
floorp-custom-actions-open-screen-capture = 화면 캡처 도구 열기
    .label = 스크린샷 찍기
floorp-custom-actions-show-pip = 사진에 사진 표시
    .label = 화면 속 화면 표시
floorp-custom-actions-bookmark-this-page = 이 페이지 북마크하기
    .label = 이 페이지 북마크하기
floorp-custom-actions-open-bookmarks-sidebar = 북마크 사이드바 열기
    .label = 북마크 사이드바 열기
floorp-custom-actions-open-bookmark-add-tool = 북마크 추가 도구 열기
    .label = 북마크 추가
floorp-custom-actions-open-bookmark-add-toolbar = '새 북마크 추가' 팝업 창 열기
    .label = 북마크에 추가 도구 모음
floorp-custom-actions-open-bookmarks-manager = 북마크 관리자 열기
    .label = 북마크 관리자 열기
floorp-custom-actions-show-bookmark-toolbar = 북마크 도구 모음 토글
    .label = 북마크 도구 모음 토글
floorp-custom-actions-open-general-preferences = 일반 환경설정 열기
    .label = 일반 환경설정 열기
floorp-custom-actions-open-privacy-preferences = 개인 정보 기본 설정 열기
    .label = 개인 정보 기본 설정 열기
floorp-custom-actions-open-workspaces-preferences = 작업 공간 환경설정 열기
    .label = 작업 공간 환경설정 열기
floorp-custom-actions-open-containers-preferences = 컨테이너 환경설정 열기
    .label = 컨테이너 환경설정 열기
floorp-custom-actions-open-search-preferences = 검색 환경설정 열기
    .label = 검색 환경설정 열기
floorp-custom-actions-open-sync-preferences = 동기화 환경설정 열기
    .label = 동기화 환경설정 열기
floorp-custom-actions-open-task-manager = 작업 관리자 열기
    .label = { -brand-short-name }의 작업 관리자를 엽니다.
floorp-custom-actions-open-home-page = { -brand-short-name }의 홈 페이지를 엽니다.
    .label = { -brand-short-name }의 홈페이지를 엽니다.
floorp-custom-actions-open-addons-manager = 애드온 및 테마 열기
    .label = 애드온 및 테마 열기
floorp-custom-actions-forget-history = 역사 잊기
    .label = 역사 잊기
floorp-custom-actions-quick-forget-history = 빠른 기록 삭제
    .label = 빠른 기록 삭제
floorp-custom-actions-clear-recent-history = 최근 기록 지우기
    .label = 최근 기록 지우기
floorp-custom-actions-search-history = 검색 기록
    .label = 검색 기록
floorp-custom-actions-manage-history = 기록 관리
    .label = 기록 관리
floorp-custom-actions-open-downloads = 다운로드 열기
    .label = 다운로드 열기
floorp-custom-actions-show-bsm = 브라우저 관리자 사이드바 표시
    .label = 브라우저 관리자 사이드바 표시
floorp-custom-actions-show-bookmark-sidebar = 북마크 사이드바 표시
    .label = 북마크 사이드바 표시
floorp-custom-actions-show-history-sidebar = 기록 사이드바 표시
    .label = 기록 사이드바 표시
floorp-custom-actions-show-synced-tabs-sidebar = 동기화된 탭 사이드바 표시
    .label = 동기화된 탭 사이드바 표시
floorp-custom-actions-reverse-sidebar = 반대쪽 사이드바 위치
    .label = 반대쪽 사이드바 위치
floorp-custom-actions-hide-sidebar = 사이드바 숨기기
    .label = 사이드바 숨기기
floorp-custom-actions-show-sidebar = 사이드바 토글
    .label = 사이드바 토글
floorp-custom-actions-toggle-sidebar = 사이드바 표시 전환하기
    .label = 사이드바 표시 전환하기
floorp-custom-actions-open-previous-workspace = 이전 작업 공간 열기
    .label = 이전 작업 공간 열기
floorp-custom-actions-open-next-workspace = 다음 작업 공간 열기
    .label = 다음 작업 공간 열기
floorp-custom-actions-show-panel-1 = 패널 토글 1
    .label = 패널 토글 1
floorp-custom-actions-show-panel-2 = 패널 토글 2
    .label = 패널 토글 2
floorp-custom-actions-show-panel-3 = 패널 토글 3
    .label = 패널 토글 3
floorp-custom-actions-show-panel-4 = 패널 토글 4
    .label = 패널 토글 4
floorp-custom-actions-show-panel-5 = 패널 토글 5
    .label = 패널 토글 5
floorp-custom-actions-show-panel-6 = 패널 토글 6
    .label = 패널 토글 6
floorp-custom-actions-show-panel-7 = 패널 토글 7
    .label = 패널 토글 7
floorp-custom-actions-show-panel-8 = 패널 토글 8
    .label = 패널 토글 8
floorp-custom-actions-show-panel-9 = 패널 토글 9
    .label = 패널 토글 9
floorp-custom-actions-show-panel-10 = 패널 토글 10
    .label = 패널 토글 10
floorp-custom-actions-open-split-view-on-left = 현재 탭을 분할 뷰로 왼쪽에 열기
    .label = 현재 탭을 분할 뷰로 왼쪽에 열기
floorp-custom-actions-open-split-view-on-right = 현재 탭을 분할 뷰로 오른쪽에 열기
    .label = 현재 탭을 분할 뷰로 오른쪽에 열기
floorp-custom-actions-close-split-view = 분할 뷰 닫기
    .label = 분할 뷰 닫기
floorp-custom-actions-custom-action-1 = 사용자 지정 작업 1
    .label = 사용자 지정 작업 1
floorp-custom-actions-custom-action-2 = 사용자 지정 작업 2
    .label = 사용자 지정 작업 2
floorp-custom-actions-custom-action-3 = 사용자 지정 작업 3
    .label = 사용자 지정 작업 3
floorp-custom-actions-custom-action-4 = 사용자 지정 작업 4
    .label = 사용자 지정 작업 4
floorp-custom-actions-custom-action-5 = 사용자 지정 작업 5
    .label = 사용자 지정 작업 5
floorp-custom-actions-rest-mode = 휴식 모드 사용하기
    .label = 휴식 모드 사용하기
floorp-custom-actions-hide-user-interface = 유저 인터페이스를 전환하기
    .label = 유저 인터페이스를 전환하기
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = 시작
    .tooltiptext = 이 프로필로 { -brand-short-name } 실행
floorp-profiles-in-use = 이 프로필이 사용 중입니다.
floorp-profiles-title = 프로필
floorp-profile-manager = 프로필 관리자
floorp-profiles-create = 프로필 만들기
floorp-profile = 프로필
    .label = 프로필 관리자
    .tooltiptext = 프로필 관리자 열기
fxa-not-signed-in = 로그인하지 않음
###################################################################### Private Container ##############################################################
floorp-private-container-name = 사생활
floorp-toggle-private-container = 
    .label = 사생활 컨테이너/컨테이너 없음으로 다시 열기
    .accesskey = P
open-in_private-container = 
    .label = 사생활 컨테이너로 새 탭에서 열기
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = 분할 뷰에서 열기
splitview-show-on-right = 
    .label = 오른쪽에 표시하기
splitview-show-on-left = 
    .label = 왼쪽에 표시하기
splitview-close-split-tab = 
    .label = 분할 탭을 닫기
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = QR코드를 스캔하세요.
qrcode-generate-page-action = 
    .tooltiptext = QR코드로 웹 사이트를 공유
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = 통합 확장 기능 버튼
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = 앱 설치
    .tooltiptext = 이 사이트를 앱으로 설치하기
ssb-page-action-title = 앱 설치
ssb-app-open-button = 
    .label = 앱으로 열기
ssb-app-install-button = 
    .label = 설치
ssb-app-cancel-button = 
    .label = 취소
floorp-open-manage-ssb-page = 
    .label = 설치된 웹 앱을 관리하기
appmenuitem-webapps = 
    .label = 웹 앱
appmenu-open-installed-apps-subheader = 설치된 웹 앱 열기
appmenuitem-install-current-page = 
    .label = 이 사이트를 앱으로서 설치하기
appmenuitem-open-current-page = 
    .label = 이 사이트를 설치한 앱으로 열기
appmenuitem-contextmenu-open-app = 
    .label = 이 앱을 열기
appmenuitem-contextmenu-uninstall-app = 
    .label = 이 앱을 삭제하기

## Preferences

category-ssb = 
    .label = 웹 앱
    .tooltiptext = 웹 앱
category-ssb-title = 웹 앱
floorp-ssb-title = 웹 앱
floorp-ssb-description = 웹 앱은 앱으로서 설치할 수 있는 웹사이트이에요. { -brand-short-name } 의 메뉴 패널 또는 Windows 시작 메뉴에서 실행할 수 있어요.
ssb-preferences = 웹 앱 설정
floorp-enable-ssb = 
    .label = 웹 앱 사용하기
floorp-enable-ssb-with-experimental = 
    .label = 웹 앱 사용하기 (실험적)
floorp-enable-ssb-description = 이 기능은 Mac과 Linux에서 실험 단계이에요. Windows에서는 이 기능을 활성화하는 것이 좋아요.
floorp-disable-toolbars = 
    .label = 웹 앱의 툴바를 사용하지 않기
floorp-disable-toolbars-description = 웹 앱 창에서 모든 확장 프로그램 아이콘과 도구 모음을 숨깁니다.
ssb-installed-list-title = 설치된 웹 앱
ssb-uninstall-title = 웹 앱을 삭제하기
ssb-uninstall-message = { -brand-short-name } 에서 이 웹 앱을 삭제하시겠어요?
ssb-uninstall-button = 
    .label = 삭제
ssb-uninstall-cancel = 취소
######################################################################### Download Notification ###############################################################
floorp-started-download = 다운로드 시작
floorp-finished-download = 다운로드 완료
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } 는 최신 상태이에요!
floorp-notificationContent-latest = 최신 버전의 { -brand-short-name } 를 사용하고 있습니다.
floorp-notificationTitle = 새로운 버전의 { -brand-short-name } 가 있어요!
floorp-notificationContent = 최신 버전을 다운로드하려면 클릭하세요.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = 위 탭을 모두 닫기
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = 아래 탭을 모두 닫기
    .accesskey = E
