# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> er en af de indenlandske browsere udviklet i Japan. Den er baseret på Firefox og opererer fortsat under <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, for at forbedre internettet. Vil du hjælpe? <label data-l10n-name="helpus-donateLink">Donér</label>
icon-creator = Ikonskaber <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> og <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = En liste over <label data-l10n-name="about-contributor">bidragsydere og udviklere</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Design
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Genstart er påkrævet for at anvende ændringer
tab-width = Minimumsbredde på faner
preferences-tabs-newtab-position = Ny faneposition
open-new-tab-use-default = 
    .label = Åbn nye faner på standardposition
open-new-tab-at-the-end = 
    .label = Åbn nye faner for enden af Fanebjælken
open-new-tab-next-to-current = 
    .label = Åbn nye faner ved siden af den aktuelle fane
multirow-tabs-limit = 
    .label = Aktivér rækkegrænse for flerrækkede faner
multirow-tabs-newtab = 
    .label = Placer knappen "Åbn en ny fane" sidst i den nederste række faner
multirow-tabs-value = Antal rækker, når flerrækkede faner er aktiveret
enable-tab-sleep = 
    .label = Aktivér Dvaletilstand for Faner
tab-sleep-timeout-minutes-value = Faner går i dvale efter inaktivitet i (minutter)
tab-sleep-settings-button = Indstillinger...
tab-sleep-settings-dialog-title = 
    .title = Indstillinger For Sovende Faneblade
tab-sleep-settings-dialog-excludehosts-label = Ekskluder værter
tab-sleep-settings-dialog-excludehosts-label-2 = Indtast én vært pr. linje.
tab-sleep-tab-context-menu-excludetab = Hold fane åben
enable-tab-scroll-change = 
    .label = Skift faner ved at rulle med musen
enable-tab-scroll-reverse = 
    .label = Omvendt retning af rullefaner
enable-tab-scroll-wrap = 
    .label = Ombryd rulning faner i kanten
enable-double-click-block = 
    .label = Luk faner med dobbeltklik
enable-show-pinned-tabs-title = 
    .label = Vis titlen på fastgjorte faner
tabbar-preference = Fanebjælke
tab-normal-mode = 
    .label = Standard
hide-horizontality-tabs = 
    .label = Skjul faner på Vandret Fanebjælke
verticalTab-setting = 
    .label = Optimer browser til Lodret Fanebjælke
move-tabbar-position = 
    .label = Vis Fanebjælke under Værktøjslinjen
tabbar-on-bottom = 
    .label = Vis Fanebjælke nederst i vinduet
tabbar-favicon-color = 
    .label = Farv Fanebjælken med den aktuelle hjemmesides favicon-farve
tabbar-style-preference = Fanebjælkestil
horizontal-tabbar = 
    .label = Vandret Fanebjælke
tabbar-style-description = Genstart af { -brand-short-name } kræves for at anvende denne indstilling helt.
multirow-tabbar = 
    .label = Flerrækket Fanebjælke
vertical-tabbar = 
    .label = Lodret Fanebjælke (eksperimentel)
native-vertical-tab-show-right = 
    .label = Vis Lodret Fanebjælke i højre side af vinduet
native-vertical-tab-show-padding = 
    .label = Aktivér padding i toppen
hover-vertical-tab = 
    .label = Skjul Lodret Fanebjælke
floorp-show-vertical-tab-newtab-button = 
    .label = Vis knappen "Åbn en ny fane" i Lodret Fanebjælke
floorp-show-vertical-tab-scrollbar = 
    .label = Vis scrollbar på Lodret Fanebjælke
TST = Faneblad For Træstil
about-TST = Tree Style Tab er en populær tilføjelse, der lader dig vise faner i en trælignende struktur. Denne tilføjelse er allerede præintegreret i { -brand-short-name }. Installer tilføjelsen for at aktivere { -brand-short-name }'s Tree Style Tab.
treestyletab-Settings = 
    .label = Sammenfold Tree Style Tab
sidebar-reverse-position-toolbar = Vis Sidebjælker på den anden side
bookmarks-bar-settings = Bogmærkeværktøjslinje (kun én mulighed kan bruges ad gangen)
bookmarks-focus-mode = 
    .label = Skjul Bogmærkeværktøjslinjen, medmindre du holder musen over navigationslinjen
bookmarks-bottom-mode = 
    .label = Vis Bogmærkeværktøjslinjen i bunden af { -brand-short-name }
navbar-settings = Navigationslinje
show-nav-bar-bottom = 
    .label = Vis Værktøjslinjen i bunden af { -brand-short-name } (eksperimentel)
material-effect = 
    .label = Tillad Mica For Everyone at ændre browserens design
disable-extension-check-compatibility-option = 
    .label = Kontrollér ikke for kompatibilitet med tilføjelser
other-preference = Andre Præferencer
enable-userscript = 
    .label = Aktivér ældre komponenter
about-userscript = Aktivering af denne funktion kan forårsage uventede eller alvorlige fejl.
search-positon-top = 
    .label = Vis Søgelinjen øverst på siden
allow-auto-restart = 
    .label = Genstart automatisk, når indstillinger, der kræver en genstart, ændres
disable-fullscreen-notification = 
    .label = Vis ikke en meddelelse, når du går ind i fuld skærm

## Browser Theme

system-color-settings = Nogle temaer har både lyse og mørke tilstande — vælg, hvilken tilstand du vil bruge i disse temaer.
preferences-theme-appearance-header = Tematilstand
system-theme-dark = 
    .label = Mørk
system-theme-light = 
    .label = Lys
system-theme-auto = 
    .label = Følg mit systems udseende

## User interface preferences

ui-preference = Browserens udseende
preferences-browser-appearance-description = Vælg et indbygget tredjepartsdesign til brug i { -brand-short-name }. Nogle designs er muligvis ikke kompatible med din konfiguration.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon • Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (forældet)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (forældet)
floorp-gnomeUI = 
    .label = GNOME-tema (forældet)

## Download Manager

download-notification-preferences = Hent Notifikationer
start-always-notify = 
    .label = Underret kun, når overførsler startes
finish-always-notify = 
    .label = Advisér kun når en download er færdig
always-notify = 
    .label = Giv besked, når du starter downloads og når en download er færdig
do-not-notify = 
    .label = Deaktiver download notifikationer

## Sidebar

profiles-button-label = Administrer Profiler
floorp-help-button-label = { -brand-short-name } Support
appmenuitem-reboot = 
    .label = Genstart

## UserAgent

userAgent-preference = User Agent
default-useragent-mode = 
    .label = Brug Firefox User Agent (Standard)
windows-chrome-useragent-mode = 
    .label = Spoof Chrome på Windows
macOS-chrome-useragent-mode = 
    .label = Spoof Chrome på macOS
linux-chrome-useragent-mode = 
    .label = Spoof Chrome på Linux
mobile-chrome-useragent-mode = 
    .label = Spoof Chrome på iOS
use-custom-useragent-mode = 
    .label = Brug Brugerdefineret Brugeragent

## DMR UI

download-mgr-UI = 
    .label = Aktiver SimpleUI Download Manager
downloading-red-color = 
    .label = Brug ikonet med røde downloads, når du henter
sidebar-preferences = Sidebar
bsb-preferences = Indstillinger For Browserhåndteringsidebjælke
view-sidebar2-right = 
    .label = Vis Browser Manager Sidebjælken til højre
enable-sidebar2 = 
    .label = Aktiver browserhåndterings sidebjælken
visible-bms = 
    .label = Vis sidebjælken til browserhåndtering
hide-bms-to-unload-panel = 
    .label = Fjern panel ved skjulning af panel
enable-addons-in-sidebar2-with-experimental = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar (experimental)
enable-addons-in-sidebar2 = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar
sidebar2-enable-addons-desc = Hvis denne indstilling er aktiveret, vil annonceblokerende udvidelser og andre udvidelser fungere i sidepanelet. Det er dog ikke alle udvidelser, der virker.
custom-URL-option = Angiv Webpanel URL'er
set-custom-URL-button = 
    .label = Sæt Brugerdefinerede URL'er...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Browser Manager Sidebjælke
bsb-context = Use the following Container
bsb-userAgent-label = 
    .label = Brug mobilbruger agent i dette webpanel
bsb-width = Bredde (hvis sat til 0, vil den globale værdi blive anvendt)
bsb-page = Side der skal åbnes
bsb-add = Tilføj webpanel i browserhåndterings sidebjælke
bsb-setting = Web Panel Indstillinger
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Hjemmeside
sidebar2-pref-delete = 
    .label = Slet
sidebar2-pref-setting = 
    .label = Indstillinger
sidebar2-global-width = Globale webpaneler bredde
use-icon-provider-option = Use Icon Provider
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = AndeDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (tilgængelig i Kina)
use-icon-provider-option-hatena = 
    .label = Hatena (fås i Kina)
memory-and-performance = Hukommelse og ydeevne
min-memory = 
    .label = Mindste hukommelsesforbrug (lav ydeevne)
balance-memory = 
    .label = Balance hukommelse forbrug og ydeevne
max-memory = 
    .label = Bedste Ydeevne (højt hukommelsesforbrug)
delete-border-and-roundup-option = 
    .label = Rund hjørnerne af siderne

## DualTheme

dualtheme-enable = 
    .label = Aktiver Dobbelt Tema
newtab-background = { -brand-short-name } Hjem Baggrund
newtab-background-random-image = 
    .label = Tilfældige billeder fra Unsplash
newtab-background-gradation = 
    .label = Overgang
newtab-background-not-background = 
    .label = Deaktivér baggrund
newtab-background-selected-image = 
    .label = Brugerdefineret mappe...
newtab-background-selected-one-image = 
    .label = Tilpasset billede...
newtab-background-folder = Brug billeder fra denne mappe:
newtab-background-image = Brug billede:
newtab-choose-image = Vælg billede...
newtab-background-folder-reload = 
    .label = Reload images
newtab-background-folder-default = 
    .label = Gendan Standarder
newtab-background-folder-open = 
    .label = Åbn mappe
newtab-background-folder-choose = Vælg billedmappe...
newtab-background-image-choose = Vælg billede...
newtab-background-extensions = Brug billeder med disse filendelser (adskilt af ",")
disable-blur-on-newtab = 
    .label = Deaktivér sløringseffekt i { -brand-short-name } Hjem
disable-releasenote-on-newtab = 
    .label = Deaktivér Udgivelsesnoter og Supportlinks i { -brand-short-name } Hjem
disable-imagecredit-on-newtab = 
    .label = Deaktivér billedkreditering (Unsplash) i { -brand-short-name } Hjem

## Lepton Preferences

about-lepton = Tilpas { -brand-short-name } med Lepton
lepton-preference-button = 
    .label = Lepton Indstillinger...
    .accesskey = L
lepton-header = Lepton Indstillinger
lepton-preference = Lepton Indstillinger
photon-mode = 
    .label = Brug Photon design
lepton-mode = 
    .label = Brug Lepton design
protonfix-mode = 
    .label = Brug tweaked Proton design
autohide-preference = Skjul automatisk browserelementer
floorp-lepton-enable-tab-autohide = 
    .label = Skjul automatisk faneblade
floorp-lepton-enable-navbar-autohide = 
    .label = Skjul Automatisk Værktøjslinje
floorp-lepton-enable-sidebar-autohide = 
    .label = Skjul Sidebjælke Automatisk
floorp-lepton-enable-urlbar-autohide = 
    .label = Skjul Automatisk Adresselinje
floorp-lepton-enable-back-button-autohide = 
    .label = Skjul automatisk tilbage-knap
floorp-lepton-enable-forward-button-autohide = 
    .label = Skjul automatisk fremad knap
floorp-lepton-enable-page-action-button-autohide = 
    .label = Skjul automatisk knapper på adressebjælken
floorp-lepton-enable-toolbar-overlap = 
    .label = Vis værktøjslinje over hjemmesidens indhold
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Skjul automatisk værktøjslinjen ved visning af "ltr" indhold
hide-preference = Håndtér browserelementer
floorp-lepton-enable-tab_icon-hide = 
    .label = Skjul faneikoner
floorp-lepton-enable-tabbar-hide = 
    .label = Skjul Fanebladslinje
floorp-lepton-enable-navbar-hide = 
    .label = Skjul Værktøjslinje
floorp-lepton-enable-sidebar_header-hide = 
    .label = Skjul Sidebjælkeoverskrifter
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Skjul ikoner i adresselinje
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Skjul ikoner i bogmærkelinjen
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Skjul Bogmærker Bar etiketter
floorp-lepton-enable-disabled_menu-hide = 
    .label = Skjul deaktiverede kontekstmenupunkter
floorp-lepton-disable-userChrome-icon = 
    .label = Deaktivér Leptons kontekstmenu og panelmenuikoner
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Aktivér Leptons kontekstmenuikoner
positon-preferences = Justering af position
floorp-lepton-enable-centered-tab = 
    .label = Centrér etiketter i faneblade
floorp-lepton-enable-centered-urlbar = 
    .label = Centrér tekst i adressebjælken
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Centrér bogmærkelinje elementer
urlbar-preferences = Adressebjælke
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Flyt Adressebjælke-ikoner til venstre side
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Vis en "Gå"-knap, når du skriver
floorp-lepton-enable-always-show-page_action = 
    .label = Vis altid sidehandlinger i adressebjælken
tabbar-preferences = Fanebladslinje
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Fanebjælke i Titellinjen
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Kombiner fanebladslinje og værktøjslinje
lepton-sidebar-preferences = Sidebar
floorp-lepton-enable-overlap-sidebar = 
    .label = Vis sidepanel over hjemmesidens indhold
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Hjem (Standard)
floorp-home-prefs-content-header = { -brand-short-name } Hjem Indhold
floorp-home-prefs-content-description = Vælg det indhold, du ønsker at se på { -brand-short-name } Hjemmeside.

## Notes

floorp-notes = { -brand-short-name } Noter
restore-from-backup = Gendan noter fra sikkerhedskopi
enable-notes-sync = 
    .label = Aktiver { -brand-short-name } Noter Synkronisering
about-notes-backup-tips = { -brand-short-name } Noter bruger Firefox Sync til at synkronisere dine noter med andre enheder. Hvis du mister dine noter, kan du gendanne dem fra en sikkerhedskopi. En sikkerhedskopi oprettes, når du starter { -brand-short-name }.
notes-sync-description = Dette kan løse problemet med at miste indhold på grund af overskrive noter under synkronisering.
backuped-time = Sikkerhedskopieret på
notes-backup-option = Sikkerhedskopiér Indstillinger
backup-option-button = Sikkerhedskopiér Indstillinger...
restore-from-backup-prompt-title = { -brand-short-name } Notes Restore Service
restore-from-this-backup = Gendan noter tilbage til den tilstand, de var i denne backup?
restore-button = Gendan

## user.js

header-userjs = user.js
userjs-customize = Tilpas { -brand-short-name } med user.js
about-userjs-customize = user.js er en konfigurationsfil, der giver dig mulighed for at tilpasse { -brand-short-name }. user.js-filer downloades fra internettet og overskrive din nuværende bruger. s file. Please back up your current user.js file before continuing. user.js configurations will be applied automatically after restarting { -brand-short-name }.
userjs-label = user.js liste
userjs-prompt = Anvend denne user.js?
apply-userjs-attention = Anvendelse af en ny user.js vil overskrive din nuværende user.js-fil.
apply-userjs-attention2 = Sikkerhedskopier venligst din aktuelle user.js-fil, før du fortsætter.
userjs-button = user.js Indstillinger...
userjs-select-option = Administrer user.js som i øjeblikket anvendes i { -brand-short-name } for at forbedre ydeevne og privatliv.
apply-userjs-button = Anvend

## userjs Options

default-userjs-label = { -brand-short-name } Standard
about-default-userjs = Telemetri deaktiveret. Velafbalanceret { -brand-short-name } med forskellige tilpasninger aktiveret.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS-by-Default. Total Cookie Beskyttelse med isolation af webstedet. Forbedret tilstand og netværkspartitionering. Forskellige andre forbedringer.
default-label = Yokoffing Default
about-default = Alt det væsentlige. Ingen af bruddet. Dette er din user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Øge Firefox char@@0 rsquo; s browsing hastighed. Giv Chrome et løb for sine penge!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Unclutter den nye fane side. Fjern Pocket. Gendan kompakt tilstand som en mulighed. Stop webside meddelelser, pop-ups, og andre irritationer.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Få kant-lignende glat rulning på din foretrukne browser - eller vælg noget mere din stil.
select-workspace = Vælg Arbejdsområde
workspace-select-icon = Vælg Arbejdsområde-ikon
    .label = Vælg Arbejdsområde-ikon
workspace-select-container = Vælg Container Faneblad
    .label = Vælg Container Faneblad
workspace-customize = 
    .title = Tilpas Arbejdsrum
floorp-no-workspace-container = 
    .label = Ingen Beholder
workspace-icon-article = 
    .label = Artikel
workspace-icon-book = 
    .label = Bog
workspace-icon-briefcase = 
    .label = Job
workspace-icon-cart = 
    .label = Shopping
workspace-icon-chat = 
    .label = Chat
workspace-icon-chill = 
    .label = Privat
workspace-icon-circle = 
    .label = Cirkel
workspace-icon-compass = 
    .label = Kompas
workspace-icon-code = 
    .label = Kode
workspace-icon-dollar = 
    .label = Bank
workspace-icon-fence = 
    .label = Hegn
workspace-icon-fingerprint = 
    .label = Personlig
workspace-icon-food = 
    .label = Mad
workspace-icon-fruit = 
    .label = Frugt
workspace-icon-game = 
    .label = Spil
workspace-icon-gear = 
    .label = Redskab
workspace-icon-gift = 
    .label = Gave
workspace-icon-key = 
    .label = Nøgle
workspace-icon-lightning = 
    .label = Lyn
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Noter
workspace-icon-paint = 
    .label = Maling
workspace-icon-photo = 
    .label = Foto
workspace-icon-pin = 
    .label = Nål
workspace-icon-pet = 
    .label = Kæledyr
workspace-icon-question = 
    .label = Spørgsmål
workspace-icon-smartphone = 
    .label = Smart Telefon
workspace-icon-star = 
    .label = Stjerne
workspace-icon-tree = 
    .label = Træ
workspace-icon-vacation = 
    .label = Ferie
workspace-icon-love = 
    .label = Kærlighed
workspace-icon-moon = 
    .label = Måne
workspace-icon-music = 
    .label = Musik
workspace-icon-user = 
    .label = Bruger
# Custom Keyboard Shortcuts
floorp-CSK-title = Brugerdefinerede tastaturgenveje
floorp-CSK-description = Tilpas { -brand-short-name }'s tastaturgenveje. { -brand-short-name } har mere end 80 tastaturgenveje, der kan tilpasses! Duplikerede tastaturgenveje virker ikke. Genstart { -brand-short-name } for at anvende disse indstillinger.
disable-fx-actions = 
    .label = Deaktivér genveje til Mozilla Firefox
customize-Action = 
    .label = Tilføj genvej
remove-Action = 
    .label = Fjern genvej
CSK-reset-title = Nulstil brugerdefinerede tastaturgenveje
CSK-reset-description = Nulstil brugerdefinerede tastaturgenveje til { -brand-short-name }'s standardindstillinger.
CSK-reset-label = Nulstil brugerdefinerede tastaturgenveje
CSK-reset-button = Gendan Standarder
CSK-manage-title = Håndtér tastaturgenveje
CSK-remove-shortcutkey = Fjern brugerdefineret tastaturgenvej?
CSK-remove-shortcutkey-description = Er du sikker på, at du vil fjerne denne tastaturgenvej?
CSK-restore-default = Gendan Standard?
CSK-restore-default-description = Gendan { -brand-short-name }'s standardtastaturgenveje? Dine nuværende genveje går tabt.
CSK-reboot-browser-label = Genstart { -brand-short-name } for at anvende disse indstillinger
CSK-reboot-browser-button = Genstart { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Nuværende tastaturgenvej: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Nuværende tastaturgenvej: { $key }.
CSK-keyborad-shortcut-is-changed = (Ikke Anvendt)
floorp-custom-actions-tab-action = Fane Handlinger
floorp-custom-actions-page-action = Side Handlinger
floorp-custom-actions-visible-action = Synlige Handlinger
floorp-custom-actions-search-action = Søg Handlinger
floorp-custom-actions-tools-action = Værktøjer Handlinger
floorp-custom-actions-bookmark-action = Bogmærke Handlinger
floorp-custom-actions-open-page-action = Åbn Sidehandlinger
floorp-custom-actions-history-action = Historik Handlinger
floorp-custom-actions-pip-action = Picture-in-Picture Handlinger
floorp-custom-actions-downloads-action = Download Handlinger
floorp-custom-actions-sidebar-action = Sidebar Handlinger
floorp-custom-actions-bms-action = Browser Manager Sidebar Handlinger
floorp-custom-actions-split-view-action = Split View Actions
floorp-custom-actions-workspaces-action = Workspaces Actions
floorp-custom-actions-custom-action = Brugerdefinerede Handlinger (Eksperimentel)

## Mouse Gestures

mouse-gesture = Mus Fagter
mouse-gesture-description = Gesturefy skal være installeret for at bruge musebevægelser med { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy er en tilføjelse, der føjer musebevægelser til din browser. Hvis { -brand-short-name } registrerer installationen af denne tilføjelse, føjer den bevægelseskommandoer til Gesturefy, som kun er tilgængelige i { -brand-short-name }. Denne tilføjelse opretter også nye faner!
# Translate
TWS = Translate Web Page
about-TWS = Oversæt din side i realtid ved hjælp af Google eller Yandex. Du kan også oversætte den valgte tekst eller hele siden.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Privatliv Hub
block-more-tracker = Blokér flere Annoncer og Trackers
block-tracker = Dette afsnit indeholder et sæt af udvidelser, der er designet til at blokere annoncer og trackere
view-at-AMO = Se denne tilføjelse i addons.mozilla.org
uBlock-Origin = uBlock Oprindelse
about-uboori = uBlock Origin blokerer annoncer, omfattende trackere, og yderligere farlige steder.
Facebook-Container = Facebook Container
about-Facebook-Container = Forhindre Facebook i at spore dig rundt på nettet. Facebook Container udvidelse hjælper dig med at tage kontrol og isolere din webaktivitet fra Facebook.

## Fingerprinting

fingerprint-header = Modstå lækager fra fingeraftryk og IP adresse
block-fingerprint = Fingerprint er en sporingsmekanisme, der er afhængig af de unikke funktioner i din browser og operativsystem. Dette afsnit indeholder indstillinger for yderligere at forbedre denne beskyttelse ud over standard blokering.
enable-firefox-fingerprint-protections = Aktiver stærk beskyttelse mod fingeraftryk
about-firefox-fingerprint-protection = Aktivering af beskyttelse af Firefox omfatter tvungen lystilstand, deaktivering af nogle API'er, osv. Nogle websteder kan være brudt.
fingerprint-Protection = 
    .label = Beskyttelse mod fingeraftryk
html5-canvas-prompt-settings = 
    .label = Afvis automatisk adgangsbekræftelsesprompter til HTML5-billeddata
canvas-prompt = Forhindrer hjemmesider i at bruge canvas- reading prompt medmindre det er tilladt manuelt.
disable-webgl = 
    .label = Deaktivér WebGL
about-webgl = WebGL er en Javascript API, der bruges til at gengive grafik, som kan bruges til at identificere GPU.
Canvas-Blocker = Lærred Blocker
about-CB = Denne add-on spoofs data, der anvendes af fingeraftryk teknikker.
WebRTC-connection = WebRTC er en standard, der giver realtidsopkald. Hvis du deaktiverer denne indstilling, vil du ikke kunne bruge Discord, osv.
WebRTC = 
    .label = Aktiver WebRTC Forbindelse
################################################################### browser ###############################################################

rest-mode = Tager en pause...
rest-mode-description = { -brand-short-name } is currently suspended. Press ENTER or OK to continue.
Sidebar2 = 
    .label = Browser Manager Sidebjælke
    .tooltiptext = Skift synlighed for sidepanel
sidebar2-mute-and-unmute = 
    .label = Mute/Unmute dette panel
sidebar2-unload-panel = 
    .label = Fjern dette panel
sidebar2-change-ua-panel = 
    .label = Slå Mobilbruger Agent Til/Fra
sidebar2-delete-panel = 
    .label = Slet dette panel
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom Ind
sidebar2-zoom-out = 
    .label = Zoom Ud
sidebar2-reset-zoom = 
    .label = Nulstil Zoom
sidebar2-close-button = 
    .tooltiptext = Luk Sidebjælke
sidebar-back-button = 
    .tooltiptext = Tilbage
sidebar-forward-button = 
    .tooltiptext = Fremad
sidebar-reload-button = 
    .tooltiptext = Reload
sidebar-go-index-button = 
    .tooltiptext = Gå Hjem
sidebar-muteAndUnmute-button = 
    .tooltiptext = Mute/Unmute sidebar
sidebar2-browser-manager-sidebar = Browser Manager
show-browser-manager-sidebar = 
    .tooltiptext = Show { sidebar2-browser-manager-sidebar } Sidebar
sidebar2-bookmark-sidebar = Bogmærker
show-bookmark-sidebar = 
    .tooltiptext = Show { sidebar2-bookmark-sidebar } Sidebar
sidebar2-history-sidebar = Historik
show-history-sidebar = 
    .tooltiptext = Show { sidebar2-history-sidebar } Sidebar
sidebar2-download-sidebar = Downloads
show-download-sidebar = 
    .tooltiptext = Show { sidebar2-download-sidebar } Sidebar
sidebar2-notes-sidebar = Noter
show-notes-sidebar = 
    .tooltiptext = Show { sidebar2-notes-sidebar } Sidebar
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Tilføjelser og temaer
sidebar2-hide-sidebar-button = 
    .tooltiptext = Hide Browser Manager Sidebar
sidebar-passwords-button = 
    .tooltiptext = Adgangskoder
sidebar-preferences-button = 
    .tooltiptext = Indstillinger
sidebar-keepWidth-button = 
    .tooltiptext = Bliv ved med at bruge den aktuelle bredde på dette panel
sidebar2-keep-width-for-global = 
    .label = Anvend denne bredde på alle paneler uden en brugerdefineret bredde
bsb-context-add = 
    .label = Tilføj side til webpanel...
bsb-context-link-add = 
    .label = Tilføj link til webpanel...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Åbn Profilmappe
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Genopbyg browser CSS-filer
    .accesskey = R
make-browsercss-file = 
    .label = Opret browser CSS-fil
    .accesskey = Læ
open-css-folder = 
    .label = Åbn CSS-mappe
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Rediger userChrome.css fil
edit-userContentCss-editor = 
    .label = Rediger userContent.css fil
not-found-editor-path = Kunne ikke finde en CSS fil editor
set-pref-description = Indtast filplaceringen for den CSS fil editor du vil bruge:
rebuild-complete = Genopbygningen er gennemført.
please-enter-filename = Indtast venligst et filnavn.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Genåbn lukket fane
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Aktiver som et undertema
dual-theme-disable-addon-button = Deaktivér undertema
dual-theme-enabled-heading = Aktiveret som et undertema
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Status Bjælke
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Open Tree Style Tab Panel
gf-floorp-open-tree-style-tab-description = Open Tree Style Tab Panel on the Sidebar
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Open Bookmarks Panel
gf-floorp-open-bookmarks-sidebar-description = Open Bookmarks Panel on the Sidebar
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Open History Panel
gf-floorp-open-history-sidebar-description = Open History Panel on the Sidebar
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Open Synced Tabs Panel
gf-floorp-open-synctabs-sidebar-description = Open Synced Tabs Panel on the Sidebar
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Close Sidebar
gf-floorp-close-sidebar-description = Luk Sidebjælke
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Open BMS
gf-floorp-open-browser-manager-sidebar-description = Open Browser Manager Sidebar if the Web Panel of Browser Manager Sidebar is loaded
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Close BMS
gf-floorp-close-browser-manager-sidebar-description = Luk Browserhåndtering Sidebjælke
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Toggle BMS
gf-floorp-show-browser-manager-sidebar-description = Skift Browserhåndterings Sidebjælke
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Skjul Statuslinje
gf-floorp-hide-statusbar-description = Skjul Statuslinje
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Slå Statuslinje Til/Fra
gf-floorp-show-statusbar-description = Vis eller skjul statuslinje
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Open selected add-on Sidebar
gf-floorp-open-extension-sidebar-description = Open selected add-on on the Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id = Tilføjelse af sidebjælke
gf-floorp-open-extension-sidebar-settings-addons-id-description = Udvidelsen af tilføjelsen åben for sidebar
gf-floorp-open-extension-sidebar-settings-list-default = Vælg venligst tilføjelse
gf-floorp-open-extension-sidebar-settings-list-unknwon = Ukendt tilføjelse
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Opdateringer fundet!
update-portable-notification-found-message = Downloader opdateringer...
update-portable-notification-ready-title = Klar til at opdatere!
update-portable-notification-ready-message = { -brand-short-name } opdateres ved den næste opstart.
update-portable-notification-success-title = Opdatering lykkedes!
update-portable-notification-success-message = Opdatering fuldført! Håber, du nyder den nye version af { -brand-short-name }!
update-portable-notification-failed-title = Opdatering mislykkedes.
update-portable-notification-failed-redirector-message = Opdatering mislykkedes. Genstart af din browser kan løse dette problem.
update-portable-notification-failed-prepare-message = Kunne ikke forberede opdateringen.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Portabel Opdatering
floorp-update-application-auto-enabled-option = 
    .label = Tjek automatisk for opdateringer til { -brand-short-name } bærbar. (anbefales)
##################################################################### Open link in external ###############################################################
openInExternal-title = Åbn i ekstern browser
open-link-in-external-enabled-option = 
    .label = Aktiver funktionen "Åbn i ekstern browser"
open-link-in-external-select-browser-option = Vælg hvilken browser der vil blive åbnet
open-link-in-external-select-browser-option-default = 
    .label = Standard browser
open-link-in-external-tab-context-menu = Åbn i ekstern browser
open-link-in-external-tab-dialog-title-error = Der opstod en fejl:
open-link-in-external-tab-dialog-message-default-browser-not-found = Standardbrowseren blev ikke fundet eller er ikke konfigureret.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Den valgte browser findes ikke.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Ny
memo-title-input-placeholder = Skriv en titel her
memo-input-placeholder = Skriv eller indsæt et notat her
delete-memo = Slet
save-memo = Gem
memo-welcome-title = Velkommen!
memo-first-tip = Velkommen til { -brand-short-name } Noter! Her er nogle instruktioner om, hvordan du bruger det!
memo-second-tip = { -brand-short-name } Noter er en notesblok, der lader dig gemme flere noter, som synkroniseres på tværs af enheder. For at aktivere synkronisering skal du logge ind på { -brand-short-name } med din Firefox-konto.
memo-third-tip = { -brand-short-name } Noter gemmes i dine { -brand-short-name }-indstillinger og synkroniseres på tværs af enheder ved hjælp af Firefox Sync. Firefox Sync krypterer indholdet af synkroniseringen med adgangskoden til din Firefox-konto, så ingen andre end du kender indholdet.
memo-import-data-tip = Firefox Sync er ikke en backup-tjeneste. Vi anbefaler, at du opretter sikkerhedskopier.
memo-new-title = Ny Note
chage-view-mode = Skift Vis/Rediger Tilstand
readonly-mode = Offline (kun Læs)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Ablaze Support
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Ryd Downloads
    .accesskey = D
    .tooltiptext = Ryd Downloads
floorp-show-all-downloads = 
    .label = Vis alle downloads
    .accesskey = S
    .tooltiptext = Vis alle downloads
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Opret nyt Arbejdsområde...
    .tooltiptext = Opret et nyt Arbejdsområde
workspaces-manage-workspaces-button = 
    .label = Administrér Arbejdsområder...
    .tooltiptext = Administrér dine Arbejdsområder
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Omdøb Arbejdsområde
    .accesskey = R
delete-this-workspace = 
    .label = Slet Arbejdsområde
    .accesskey = D
manage-this-workspaces = 
    .label = Administrér Arbejdsområder...
    .accesskey = M
workspace-new-default-name = Nyt Arbejdsområde
workspace-default-name = Standard
move-tab-another-workspace = 
    .label = Flyt til et andet arbejdsområde
rename-workspace-prompt-title = Omdøb Arbejdsområde
rename-workspace-prompt-text = Enter Workspace Name. Most characters and symbols can be used.
workspaces-toolbar-button = Arbejdsområder
    .label = Arbejdsområder
    .tooltiptext = Vælg et Arbejdsområde...

## Preferences

enable-workspaces = 
    .label = Aktivér Arbejdsområder
    .tooltiptext = Aktivér Arbejdsområder
workspace-notice = Arbejdsområder fungerer ikke med denne indstilling aktiveret, medmindre knappen for arbejdsområder er placeret på værktøjslinjen. Brug denne indstilling, hvis du vil deaktivere Arbejdsområder helt.
enable-workspaces-with-experimental = 
    .label = Aktivér Arbejdsområder (Eksperimentel)
    .tooltiptext = Aktivér Arbejdsområder (Eksperimentel)
workspace-warning = Workspaces cannot be used with Tab Group add-ons. If you want to use Tab Group add-ons, please disable Workspaces and restart { -brand-short-name }.
category-workspaces = 
    .label = Arbejdsområder
    .tooltiptext = Arbejdsområder
pane-workspaces-title = Arbejdsområder
floorp-workspaces-title = { -brand-short-name } Arbejdsrum
floorp-workspace-settings-button = Indstillinger For Arbejdsrum...
floorp-preferences-label = Preferences
floorp-extensions-label = Extensions
floorp-private-label = Private
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = Administrer arbejdsområde på Browser Manager Sidebar
show-workspace-name-option = 
    .label = Vis arbejdsrumsnavn på fanebladslinjens arbejdsområde-knap
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Del Tilstand
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Log ind på din Firefox-konto
welcome-to-floorp = Velkommen til { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } er en funktionsrig, fleksibel browser, der understøtter forskellige miljøer og er baseret på Firefox.
welcome-start-setup = Klar til at springe ud i det?
welcome-skip-to-start-browsing = Skip to Start Browsing
welcome-select-preferences-template = Vælg en skabelon
welcome-minimum-template = Grundlæggende
welcome-enable-basic-features = Aktivér basisfunktioner og -indstillinger for en enkel oplevelse.
welcome-medium-template = Standard
welcome-enable-some-features = Aktivér yderligere funktioner og indstillinger for en bedre oplevelse.
welcome-maximum-template = Avanceret
welcome-enable-most-of-features = Aktivér avancerede funktioner og indstillinger. Anbefales til erfarne brugere.
welcome-go-next-setup = Næste
welcome-select-browser-design = Vælg et browserdesign
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Lepton Oprindeligt Design
welcome-design-photon-name = Lepton Photon Design
welcome-design-ProtonFix-name = Lepton ProtonFix Design
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Firefox Proton Design
welcome-import-data = Importér Dine Browserdata
welcome-import-data-description = Hurtig opsætning! Importér dine bogmærker, adgangskoder og mere fra din gamle browser. Firefox-brugere kan importere data fra Firefox Sync.
welcome-import-data-button = Importér Data...
welcome-import-data-skip = Overspring Import
welcome-select-button = Vælg
welcome-finish-setup = Opsætning Fuldført!
welcome-finish-setup-description = Så er du klar! Andre funktioner som Lodrette Faner og Arbejdsområder kan findes i { -brand-short-name }'s Indstillinger. God fornøjelse med { -brand-short-name }!
welcomet-finish-setup = Begynd at gennemse internettet
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Tastaturgenveje
    .tooltiptext = Tastaturgenveje
category-CSK-title = Tastaturgenveje
shortcutkey-customize = 
    .title = Tastaturgenveje
select-shortcutkeyAction = Vælg en handling der skal udløses
shortcutkey-customize-key-list-placeholder = Din tastaturgenvej vises her
shortcut-key-label = Keyboard Shortcut
start-input-button-listen = Start Listening
end-input-button-listen = Stop Listening
shortcut-key-description = Click "Start Listening" and enter your new keyboard shortcut for this action. Multiple keys can be used; however, keyboard shortcuts will not work if already assigned to other actions.
floorp-custom-actions-open-new-tab = Åbn en ny fane
    .label = Åbn en ny fane
floorp-custom-actions-close-tab = Luk det aktuelle faneblad
    .label = Luk det aktuelle faneblad
floorp-custom-actions-open-new-window = Åbn et nyt vindue
    .label = Åbn et nyt vindue
floorp-custom-actions-open-new-private-window = Åbn et nyt privat vindue
    .label = Åbn et nyt privat vindue
floorp-custom-actions-close-window = Luk det aktuelle vindue
    .label = Luk det aktuelle vindue
floorp-custom-actions-restore-last-session = Gendan den sidste session
    .label = Gendan den sidste session
floorp-custom-actions-restore-last-window = Gendan det sidste vindue
    .label = Gendan det sidste vindue
floorp-custom-actions-show-next-tab = Vis næste fane
    .label = Vis næste fane
floorp-custom-actions-show-previous-tab = Vis forrige faneblad
    .label = Vis forrige faneblad
floorp-custom-actions-show-all-tabs-panel = Vis alle faner panel
    .label = Vis listen over faneblade
floorp-custom-actions-send-with-mail = Send med mail
    .label = Send via e-mail
floorp-custom-actions-save-page = Gem side
    .label = Gem side
floorp-custom-actions-print-page = Print page
    .label = Print page
floorp-custom-actions-mute-current-tab = Slå til/fra for aktuel fane
    .label = Slå til/fra for aktuel fane
floorp-custom-actions-toggle-bookmark-toolbar = Toggle bookmark toolbar
    .label = Slå Bogmærkelinje Til/Fra
floorp-custom-actions-show-source-of-page = Vis kilde til side
    .label = Åbn Sidekilde
floorp-custom-actions-show-page-info = Vis sideoplysninger
    .label = Åbn Sideinfo
floorp-custom-actions-zoom-in = Zoom ind
    .label = Zoom ind
floorp-custom-actions-zoom-out = Zoom ud
    .label = Zoom ud
floorp-custom-actions-reset-zoom = Reset zoom
    .label = Reset zoom
floorp-custom-actions-back = Tilbage
    .label = Tilbage
floorp-custom-actions-forward = Fremad
    .label = Fremad
floorp-custom-actions-reload = Reload
    .label = Reload
floorp-custom-actions-stop = Stop
    .label = Stop
floorp-custom-actions-force-reload = Gennemtving genindlæsning
    .label = Gennemtving genindlæsning
floorp-custom-actions-search-in-this-page = Søg på denne side
    .label = Find på siden
floorp-custom-actions-show-next-search-result = Vis næste søgeord i dette sideresultat
    .label = Næste "Find i side" resultat
floorp-custom-actions-show-previous-search-result = Vis tidligere søgeord i dette sideresultat
    .label = Forrige "Find i side" resultat
floorp-custom-actions-search-the-web = Søg på nettet
    .label = Søg på nettet
floorp-custom-actions-open-migration-wizard = Åbn migrationsguide
    .label = Åbn migrationsguide
floorp-custom-actions-quit-from-application = Afslut fra applikationen
    .label = Afslut { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Customize Toolbar
    .label = Åbn Tilpas { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Enter offline mode
    .label = Indtast offline tilstand
floorp-custom-actions-open-screen-capture = Åbn værktøj til skærmoptagelse
    .label = Tag et skærmbillede
floorp-custom-actions-show-pip = Vis billede i billede
    .label = Vis Billede-i-billede
floorp-custom-actions-bookmark-this-page = Bogmærk denne side
    .label = Bogmærk denne side
floorp-custom-actions-open-bookmarks-sidebar = Åbn bogmærker sidepanel
    .label = Åbn bogmærker sidepanel
floorp-custom-actions-open-bookmark-add-tool = Åbn værktøjet til at tilføje bogmærke
    .label = Tilføj Bogmærke
floorp-custom-actions-open-bookmark-add-toolbar = Open "Add a new bookmark" pop-up window
    .label = Føj til bogmærkeværktøjslinje
floorp-custom-actions-open-bookmarks-manager = Åbn bogmærke- håndtering
    .label = Åbn Bogmærker Manager
floorp-custom-actions-show-bookmark-toolbar = Skift bogmærkeværktøjslinje
    .label = Slå Bogmærkelinje Til/Fra
floorp-custom-actions-open-general-preferences = Åbn generelle præferencer
    .label = Åbn Generelle Præferencer
floorp-custom-actions-open-privacy-preferences = Åbn privatlivsindstillinger
    .label = Åbn Privatlivsindstillinger
floorp-custom-actions-open-workspaces-preferences = Open Workspaces preferences
    .label = Åbn Indstillinger For Arbejdsrum
floorp-custom-actions-open-containers-preferences = Åbn container-præferencer
    .label = Åbn Containers Præferencer
floorp-custom-actions-open-search-preferences = Åbn søgeindstillinger
    .label = Åbn Søgeindstillinger
floorp-custom-actions-open-sync-preferences = Åbn synkroniseringsindstillinger
    .label = Åbn Synkroniseringsindstillinger
floorp-custom-actions-open-task-manager = Åbn opgavehåndtering
    .label = Åbn { -brand-short-name }'s Opgavestyring
floorp-custom-actions-open-home-page = Åbn { -brand-short-name }'s startside
    .label = Åbn { -brand-short-name }'s hjemmeside
floorp-custom-actions-open-addons-manager = Open add-ons and themes
    .label = Åbn tilføjelser og temaer
floorp-custom-actions-forget-history = Glem historik
    .label = Glem historik
floorp-custom-actions-quick-forget-history = Hurtig glemte historik
    .label = Hurtig glemte historik
floorp-custom-actions-clear-recent-history = Ryd seneste historik
    .label = Ryd seneste historik
floorp-custom-actions-search-history = Søg i historik
    .label = Søg i historik
floorp-custom-actions-manage-history = Administrer historik
    .label = Administrer historik
floorp-custom-actions-open-downloads = Åbn downloads
    .label = Åbn Downloads
floorp-custom-actions-show-bms = Toggle browser manager sidebar
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = Vis bogmærke sidebjælke
    .label = Vis Bogmærker Sidebjælke
floorp-custom-actions-show-history-sidebar = Show history sidebar
    .label = Show History Sidebar
floorp-custom-actions-show-synced-tabs-sidebar = Show synced tabs sidebar
    .label = Show Synced Tabs Sidebar
floorp-custom-actions-reverse-sidebar = Omvendt sidepanel position
    .label = Omvendt sidepanel position
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = Slå sidepanel til/fra
    .label = Slå sidepanel til/fra
floorp-custom-actions-toggle-sidebar = Toggle sidebar
    .label = Toggle sidebar
floorp-custom-actions-open-previous-workspace = Open previous Workspace
    .label = Open previous Workspace
floorp-custom-actions-open-next-workspace = Open next Workspace
    .label = Open next Workspace
floorp-custom-actions-show-panel-1 = Skift panel 1
    .label = Skift panel 1
floorp-custom-actions-show-panel-2 = Skift panel 2
    .label = Skift panel 2
floorp-custom-actions-show-panel-3 = Skift panel 3
    .label = Skift panel 3
floorp-custom-actions-show-panel-4 = Skift panel 4
    .label = Skift panel 4
floorp-custom-actions-show-panel-5 = Skift panel 5
    .label = Skift panel 5
floorp-custom-actions-show-panel-6 = Skift panel 6
    .label = Skift panel 6
floorp-custom-actions-show-panel-7 = Skift panel 7
    .label = Skift panel 7
floorp-custom-actions-show-panel-8 = Skift panel 8
    .label = Skift panel 8
floorp-custom-actions-show-panel-9 = Skift panel 9
    .label = Skift panel 9
floorp-custom-actions-show-panel-10 = Skift panel 10
    .label = Skift panel 10
floorp-custom-actions-open-split-view-on-left = Open current tab on left in split view
    .label = Open current tab on left in split view
floorp-custom-actions-open-split-view-on-right = Open current tab on right in split view
    .label = Open current tab on right in split view
floorp-custom-actions-close-split-view = Close split view
    .label = Close split view
floorp-custom-actions-custom-action-1 = Brugerdefineret handling 1
    .label = Brugerdefineret handling 1
floorp-custom-actions-custom-action-2 = Brugerdefineret handling 2
    .label = Brugerdefineret handling 2
floorp-custom-actions-custom-action-3 = Brugerdefineret handling 3
    .label = Brugerdefineret handling 3
floorp-custom-actions-custom-action-4 = Brugerdefineret handling 4
    .label = Brugerdefineret handling 4
floorp-custom-actions-custom-action-5 = Brugerdefineret handling 5
    .label = Brugerdefineret handling 5
floorp-custom-actions-rest-mode = Enable rest mode
    .label = Enable rest mode
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
floorp-custom-actions-toggle-navigation-panel = Toggle Navigation Panel
    .label = Toggle Navigation Panel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Start
    .tooltiptext = Start { -brand-short-name } med denne profil
floorp-profiles-in-use = Denne profil er i brug.
floorp-profiles-title = Profiles
floorp-profile-manager = Profil Manager
floorp-profiles-create = Opret Profil
floorp-profile = Profil
    .label = Profil Manager
    .tooltiptext = Åbn Profil Manager
fxa-not-signed-in = Ikke logget ind
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privat
floorp-toggle-private-container = 
    .label = Genåben på privat/ingen beholder
    .accesskey = P
open-in_private-container = 
    .label = Åbn i nyt faneblad med privat beholder
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = Open in split view
splitview-show-on-right = 
    .label = Show on right
splitview-show-on-left = 
    .label = Show on left
splitview-close-split-tab = 
    .label = Close split tab
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Skan QR-kode med din telefon
qrcode-generate-page-action = 
    .tooltiptext = Del denne side med din telefon
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Knap For Samlede Udvidelser
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Install app
    .tooltiptext = Install this site as an app
ssb-page-action-title = Install app
ssb-app-open-button = 
    .label = Open In App
ssb-app-install-button = 
    .label = Install
ssb-app-cancel-button = 
    .label = Cancel
floorp-open-manage-ssb-page = 
    .label = Manage installed Web Apps
appmenuitem-webapps = 
    .label = Web Apps
appmenu-open-installed-apps-subheader = Open installed web apps
appmenuitem-install-current-page = 
    .label = Install this site as an app
appmenuitem-open-current-page = 
    .label = Open this site on installed app
appmenuitem-contextmenu-open-app = 
    .label = Open this app
appmenuitem-contextmenu-uninstall-app = 
    .label = Uninstall this app

## Preferences

category-ssb = 
    .label = Web Apps
    .tooltiptext = Web Apps
category-ssb-title = Webapps
floorp-ssb-title = Webapps
floorp-ssb-description = Web Apps are websites that can be installed as apps. They can be launched from { -brand-short-name }'s menu panel or the Windows Start menu.
ssb-preferences = Web Apps Settings
floorp-enable-ssb = 
    .label = Aktivér Webapps
floorp-enable-ssb-with-experimental = 
    .label = Aktivér Webapps (Eksperimentel)
floorp-enable-ssb-description = Denne funktion er eksperimentel på Mac og Linux. Det anbefales at aktivere den på Windows.
floorp-disable-toolbars = 
    .label = Disable toolbars on Web Apps Window
floorp-disable-toolbars-description = This setting will hide all extensions and toolbars on Web Apps Window.
ssb-installed-list-title = Installerede Webapps
ssb-uninstall-title = Afinstallér Webapp
ssb-uninstall-message = Er du sikker på, at du vil afinstallere denne Webapp fra { -brand-short-name }?
ssb-uninstall-button = 
    .label = Afinstallér
ssb-uninstall-cancel = Annullér
######################################################################### Download Notification ###############################################################
floorp-started-download = Download started
floorp-finished-download = Download finished
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } er ajourført!
floorp-notificationContent-latest = { -brand-short-name } er ajourført. Du bruger den seneste version af { -brand-short-name }.
floorp-notificationTitle = Ny version af { -brand-short-name } er tilgængelig!
floorp-notificationContent = Klik for at hente den seneste version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
