# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> er en af de indenlandske browsere udviklet i Japan. Den er baseret på Firefox og opererer fortsat under <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, for at forbedre internettet. Vil du hjælpe? <label data-l10n-name="helpus-donateLink">Donér</label>
icon-creator = Ikonskaber <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> og <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = En liste over <label data-l10n-name="about-contributor">bidragsydere og udviklere</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Design
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Genstart er påkrævet for at anvende ændringer
tab-width = Minimumsbredde på faner
tab-height = Minimumshøjde på faner
preferences-tabs-newtab-position = Position for ny fane
open-new-tab-use-default = 
    .label = Åbn nye faner på standardposition
open-new-tab-at-the-end = 
    .label = Åbn nye faner til sidst i fanelinjen
open-new-tab-next-to-current = 
    .label = Åbn nye faner ved siden af den nuværende fane
multirow-tabs-limit = 
    .label = Aktivér rækkegrænse for flerrækkede faner
multirow-tabs-newtab = 
    .label = Placer knappen "Åbn en ny fane" til sidst i den nederste række faner
multirow-tabs-value = Antal rækker, når flerrækkede faner er aktiveret
enable-tab-sleep = 
    .label = Aktivér Dvaletilstand for Faner
tab-sleep-timeout-minutes-value = Faner går i dvale efter inaktivitet i (minutter)
tab-sleep-settings-button = Indstillinger...
tab-sleep-settings-dialog-title = 
    .title = Indstillinger for Faner i Dvaletilstand
tab-sleep-settings-dialog-excludehosts-label = Ekskluder værter
tab-sleep-settings-dialog-excludehosts-label-2 = Indtast én vært pr. linje.
tab-sleep-tab-context-menu-excludetab = Hold fane åben
enable-tab-scroll-change = 
    .label = Skift faner ved at rulle med musen
enable-tab-scroll-reverse = 
    .label = Vend rulleretning for faner
enable-tab-scroll-wrap = 
    .label = Ombryd rulning faner i kanten
enable-double-click-block = 
    .label = Luk faner med dobbeltklik
enable-show-pinned-tabs-title = 
    .label = Vis titlen på fastgjorte faner
tabbar-preference = Fanelinje
tab-normal-mode = 
    .label = Standard
hide-horizontality-tabs = 
    .label = Skjul faner i vandret fanelinje
verticalTab-setting = 
    .label = Optimer browser til lodret fanelinje
move-tabbar-position = 
    .label = Vis fanelinje under værktøjslinjen
tabbar-on-bottom = 
    .label = Vis fanelinje nederst i vinduet
tabbar-favicon-color = 
    .label = Farv Fanebjælken med den aktuelle hjemmesides favicon-farve
tabbar-style-preference = Fanelinjestil
horizontal-tabbar = 
    .label = Vandret Fanelinje
tabbar-style-description = Genstart af { -brand-short-name } kræves for at anvende denne indstilling helt.
multirow-tabbar = 
    .label = Flerrækket Fanelinje
vertical-tabbar = 
    .label = Lodret Fanelinje (eksperimentel)
native-vertical-tab-show-right = 
    .label = Vis Lodret Fanelinje i højre side af vinduet
native-vertical-tab-show-padding = 
    .label = Aktivér padding i toppen
hover-vertical-tab = 
    .label = Skjul Lodret Fanelinje
floorp-show-vertical-tab-newtab-button = 
    .label = Vis knappen "Åbn en ny fane" i Lodret Fanelinje
floorp-show-vertical-tab-scrollbar = 
    .label = Vis rullebjælke i Lodret Fanelinje
TST = Tree Style Tab
about-TST = Tree Style Tab er en populær tilføjelse, der lader dig vise faner i en trælignende struktur. Den er allerede præintegreret i { -brand-short-name }. Installer tilføjelsen for at aktivere { -brand-short-name }'s Tree Style Tab.
treestyletab-Settings = 
    .label = Skjul Tree Style Tab
sidebar-reverse-position-toolbar = Vis sidepaneler på den anden side
bookmarks-bar-settings = Bogmærkelinje (kun én mulighed kan bruges ad gangen)
bookmarks-focus-mode = 
    .label = Skjul Bogmærkelinjen, medmindre musen holdes over navigationslinjen
bookmarks-bottom-mode = 
    .label = Vis Bogmærkelinjen i bunden af { -brand-short-name }
navbar-settings = Navigationslinje
show-nav-bar-bottom = 
    .label = Vis Værktøjslinjen i bunden af { -brand-short-name } (eksperimentel)
disable-extension-check-compatibility-option = 
    .label = Tjek ikke for kompatibilitet med tilføjelser (forældet)
other-preference = Andre Indstillinger
search-positon-top = 
    .label = Vis Søgelinjen øverst på siden
allow-auto-restart = 
    .label = Genstart automatisk, når indstillinger, der kræver en genstart, ændres
disable-fullscreen-notification = 
    .label = Vis ikke en meddelelse, når du går ind i fuld skærm

## Browser Theme

system-color-settings = Nogle temaer har både lyse og mørke tilstande — vælg den, du ønsker at bruge.
preferences-theme-appearance-header = Tematilstand
system-theme-dark = 
    .label = Mørk
system-theme-light = 
    .label = Lys
system-theme-auto = 
    .label = Følg systemets udseende

## User interface preferences

ui-preference = Browserudseende
preferences-browser-appearance-description = Vælg et indbygget tredjepartsdesign til brug i { -brand-short-name }. Nogle designs er muligvis ikke kompatible med din konfiguration.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon • Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (forældet)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (Ny)

## Download Manager

download-notification-preferences = Downloadmeddelelser
start-always-notify = 
    .label = Underret kun, når en download startes
finish-always-notify = 
    .label = Underret kun, når en download er færdig
always-notify = 
    .label = Underret, når en download startes og er færdig
do-not-notify = 
    .label = Deaktivér downloadmeddelelser

## Sidebar

profiles-button-label = Administrer Profiler
floorp-help-button-label = { -brand-short-name } Support
appmenuitem-reboot = 
    .label = Genstart

## DMR UI

download-mgr-UI = 
    .label = Aktivér SimpleUI Download Manager
downloading-red-color = 
    .label = Brug det røde downloads-ikon, når du henter
sidebar-preferences = Sidepanel
bsb-preferences = Indstillinger for Browserhåndteringssidepanel
view-sidebar2-right = 
    .label = Vis Browserhåndteringssidepanelet til højre
enable-sidebar2 = 
    .label = Aktivér Browserhåndteringssidepanel
visible-bms = 
    .label = Vis sidepanelet for browserhåndtering
hide-bms-to-unload-panel = 
    .label = Fjern panel, når panel skjules
enable-addons-in-sidebar2-with-experimental = 
    .label = Aktivér indholdsscripts til udvidelser i Browserhåndteringssidepanel (eksperimentel)
enable-addons-in-sidebar2 = 
    .label = Aktivér indholdsscripts til udvidelser i Browserhåndteringssidepanel
sidebar2-enable-addons-desc = Hvis denne indstilling er aktiveret, fungerer annonceblokerende udvidelser og andre udvidelser i sidepanelet. Dog virker alle udvidelser ikke.
custom-URL-option = Angiv Webpanel URL'er
set-custom-URL-button = 
    .label = Angiv brugerdefinerede URL'er...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Browser Manager Sidebjælke
bsb-context = Brug følgende Beholder
bsb-userAgent-label = 
    .label = Brug Mobil Brugeragent i dette Webpanel
bsb-width = Bredde (hvis sat til 0, bruges den globale værdi)
bsb-page = Side at åbne
bsb-add = Tilføj Webpanel i Browserhåndteringssidepanel
bsb-setting = Webpanel Indstillinger
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Hjemmeside
sidebar2-pref-delete = 
    .label = Slet
sidebar2-pref-setting = 
    .label = Indstillinger
sidebar2-global-width = Bredde på Globale Webpaneler
use-icon-provider-option = Brug Ikonudbyder
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (tilgængelig i Kina)
use-icon-provider-option-hatena = 
    .label = Hatena (tilgængelig i Kina)
memory-and-performance = Hukommelse og Ydeevne
min-memory = 
    .label = Minimum hukommelsesforbrug (lav ydeevne)
balance-memory = 
    .label = Balancér hukommelsesforbrug og ydeevne
max-memory = 
    .label = Bedste ydeevne (højt hukommelsesforbrug)
delete-border-and-roundup-option = 
    .label = Afrund hjørnerne af sider

## DualTheme

dualtheme-enable = 
    .label = Aktivér dobbelt tema (forældet)
floorp-enable-dualtheme-description = Dobbelt Tema-funktionen kan give problemer med udvidelser. Brug venligst med omhu.
newtab-background = { -brand-short-name } Hjem-baggrund
newtab-background-random-image = 
    .label = Tilfældige billeder fra Unsplash
newtab-background-gradation = 
    .label = Gradient
newtab-background-not-background = 
    .label = Deaktivér baggrund
newtab-background-selected-image = 
    .label = Brugerdefineret mappe...
newtab-background-selected-one-image = 
    .label = Brugerdefineret billede...
newtab-background-folder = Brug billeder fra denne mappe:
newtab-background-image = Brug billede:
newtab-choose-image = Vælg billede...
newtab-background-folder-reload = 
    .label = Genindlæs billeder
newtab-background-folder-default = 
    .label = Gendan Standard
newtab-background-folder-open = 
    .label = Åbn mappe
newtab-background-folder-choose = Vælg billedmappe...
newtab-background-image-choose = Vælg billede...
newtab-background-extensions = Brug billeder med disse filtyper (adskilt af ",")
disable-blur-on-newtab = 
    .label = Deaktivér sløringseffekt i { -brand-short-name } Hjem
disable-releasenote-on-newtab = 
    .label = Deaktivér Udgivelsesnoter og Supportlinks i { -brand-short-name } Hjem
disable-imagecredit-on-newtab = 
    .label = Deaktivér billedkreditering (Unsplash) i { -brand-short-name } Hjem

## Lepton Preferences

about-lepton = Tilpas { -brand-short-name } med Lepton
lepton-preference-button = 
    .label = Lepton-indstillinger...
    .accesskey = L
lepton-header = Lepton-indstillinger
lepton-preference = Lepton-indstillinger
photon-mode = 
    .label = Brug Photon-design
lepton-mode = 
    .label = Brug Lepton-design
protonfix-mode = 
    .label = Brug justeret Proton-design
autohide-preference = Skjul automatisk browserelementer
floorp-lepton-enable-tab-autohide = 
    .label = Skjul automatisk faner
floorp-lepton-enable-navbar-autohide = 
    .label = Skjul automatisk værktøjslinje
floorp-lepton-enable-sidebar-autohide = 
    .label = Skjul automatisk sidepanel
floorp-lepton-enable-urlbar-autohide = 
    .label = Skjul automatisk adresselinje
floorp-lepton-enable-back-button-autohide = 
    .label = Skjul automatisk tilbage-knap
floorp-lepton-enable-forward-button-autohide = 
    .label = Skjul automatisk fremad-knap
floorp-lepton-enable-page-action-button-autohide = 
    .label = Skjul automatisk knapper i adresselinjen
floorp-lepton-enable-toolbar-overlap = 
    .label = Vis værktøjslinje over sideindhold
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Skjul automatisk værktøjslinje ved visning af "ltr"-indhold
hide-preference = Administrer browserelementer
floorp-lepton-enable-tab_icon-hide = 
    .label = Skjul faneikoner
floorp-lepton-enable-tabbar-hide = 
    .label = Skjul fanelinje
floorp-lepton-enable-navbar-hide = 
    .label = Skjul værktøjslinje
floorp-lepton-enable-sidebar_header-hide = 
    .label = Skjul overskrifter i sidepanel
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Skjul ikoner i adresselinje
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Skjul ikoner i bogmærkelinje
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Skjul etiketter i bogmærkelinje
floorp-lepton-enable-disabled_menu-hide = 
    .label = Skjul deaktiverede elementer i kontekstmenu
floorp-lepton-disable-userChrome-icon = 
    .label = Deaktivér Lepton's ikoner i kontekst- og panelmenu
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Aktivér Lepton's ikoner i kontekstmenu
positon-preferences = Justering af position
floorp-lepton-enable-centered-tab = 
    .label = Centrer etiketter i faner
floorp-lepton-enable-centered-urlbar = 
    .label = Centrer tekst i adresselinjen
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Centrer elementer i bogmærkelinje
urlbar-preferences = Adresselinje
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Flyt ikoner i adresselinje til venstre
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Vis en "Gå"-knap, når du skriver
floorp-lepton-enable-always-show-page_action = 
    .label = Vis altid sidehandlinger i adresselinjen
tabbar-preferences = Fanelinje
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Fanelinje i titellinjen
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Kombiner fanelinje og værktøjslinje
lepton-sidebar-preferences = Sidepanel
floorp-lepton-enable-overlap-sidebar = 
    .label = Vis sidepanel over sideindhold
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Hjem (Standard)
floorp-home-prefs-content-header = { -brand-short-name } Hjem Indhold
floorp-home-prefs-content-description = Vælg det indhold, du ønsker at se på { -brand-short-name } Startside.

## Notes

floorp-notes = { -brand-short-name } Noter
restore-from-backup = Gendan Noter fra sikkerhedskopi
enable-notes-sync = 
    .label = Aktivér { -brand-short-name } Noter Synkronisering
about-notes-backup-tips = { -brand-short-name } Noter bruger Firefox Sync til at synkronisere dine noter med andre enheder. Hvis du mister dine noter, kan du gendanne dem fra en sikkerhedskopi. En sikkerhedskopi oprettes, når du starter { -brand-short-name }.
notes-sync-description = Dette kan løse problemet med at miste indhold grundet overskrivning af noter under synkronisering.
backuped-time = Sikkerhedskopieret på
notes-backup-option = Sikkerhedskopiér Indstillinger
backup-option-button = Sikkerhedskopiér Indstillinger...
restore-from-backup-prompt-title = { -brand-short-name } Noter Gendannelsestjeneste
restore-from-this-backup = Gendan noter tilbage til den tilstand, de var i denne backup?
restore-button = Gendan

## user.js

header-userjs = user.js
userjs-customize = Tilpas { -brand-short-name } med user.js
about-userjs-customize = user.js er en konfigurationsfil, der lader dig tilpasse { -brand-short-name }. user.js-filer hentes fra internettet og overskriver din nuværende user.js-fil. Sørg for at sikkerhedskopiere din nuværende user.js-fil, før du fortsætter. user.js-konfigurationer anvendes automatisk efter genstart af { -brand-short-name }.
userjs-label = user.js-liste
userjs-prompt = Anvend denne user.js?
apply-userjs-attention = Anvendelse af en ny user.js overskriver din nuværende user.js-fil.
apply-userjs-attention2 = Sikkerhedskopiér venligst din nuværende user.js-fil, før du fortsætter.
userjs-button = user.js Indstillinger...
userjs-select-option = Administrer den user.js, der i øjeblikket bruges i { -brand-short-name } for at forbedre ydeevne og privatliv.
apply-userjs-button = Anvend

## userjs Options

default-userjs-label = { -brand-short-name } Standard
about-default-userjs = Telemetri deaktiveret. Velafbalanceret { -brand-short-name } med forskellige tilpasninger aktiveret.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS som standard. Total cookiebeskyttelse med webstedsisolering. Forbedret tilstands- og netværksdeling. Mange andre forbedringer.
default-label = Yokoffing Default
about-default = Alt det vigtigste. Intet der går i stykker. Dette er din user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Øg Firefox' browserhastighed enormt. Giv Chrome kamp til stregen!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Fjern rod på den nye faneside. Fjern Pocket. Gendan kompakt tilstand som en mulighed. Stop webside-meddelelser, pop-ups og andre forstyrrelser.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Få Edge-lignende glat scrolling i din yndlingsbrowser — eller vælg noget, der er mere din stil.
select-workspace = Vælg Arbejdsområde
workspace-select-icon = Vælg Arbejdsområde-ikon
    .label = Vælg Arbejdsområde-ikon
workspace-select-container = Vælg Container Faneblad
    .label = Vælg Container Faneblad
workspace-customize = 
    .title = Tilpas Arbejdsområde
floorp-no-workspace-container = 
    .label = Ingen Beholder
workspace-icon-article = 
    .label = Artikel
workspace-icon-book = 
    .label = Bog
workspace-icon-briefcase = 
    .label = Job
workspace-icon-cart = 
    .label = Shopping
workspace-icon-chat = 
    .label = Chat
workspace-icon-chill = 
    .label = Privat
workspace-icon-circle = 
    .label = Cirkel
workspace-icon-compass = 
    .label = Kompas
workspace-icon-code = 
    .label = Kode
workspace-icon-dollar = 
    .label = Bank
workspace-icon-fence = 
    .label = Hegn
workspace-icon-fingerprint = 
    .label = Personlig
workspace-icon-food = 
    .label = Mad
workspace-icon-fruit = 
    .label = Frugt
workspace-icon-game = 
    .label = Spil
workspace-icon-gear = 
    .label = Redskab
workspace-icon-gift = 
    .label = Gave
workspace-icon-key = 
    .label = Nøgle
workspace-icon-lightning = 
    .label = Lyn
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Noter
workspace-icon-paint = 
    .label = Maling
workspace-icon-photo = 
    .label = Foto
workspace-icon-pin = 
    .label = Nål
workspace-icon-pet = 
    .label = Kæledyr
workspace-icon-question = 
    .label = Spørgsmål
workspace-icon-smartphone = 
    .label = Smartphone
workspace-icon-star = 
    .label = Stjerne
workspace-icon-tree = 
    .label = Træ
workspace-icon-vacation = 
    .label = Ferie
workspace-icon-love = 
    .label = Kærlighed
workspace-icon-moon = 
    .label = Måne
workspace-icon-music = 
    .label = Musik
workspace-icon-user = 
    .label = Bruger
# Custom Keyboard Shortcuts
floorp-CSK-title = Brugerdefinerede tastaturgenveje
floorp-CSK-description = Tilpas { -brand-short-name }'s tastaturgenveje. { -brand-short-name } har mere end 80 tastaturgenveje, der kan tilpasses! Duplikerede tastaturgenveje virker ikke. Genstart { -brand-short-name } for at anvende indstillingerne.
disable-fx-actions = 
    .label = Deaktivér Mozilla Firefox' tastaturgenveje
floorp-CSK-error = Den indtastede tastebinding er allerede i brug. Prøv venligst en anden.
customize-Action = 
    .label = Tilføj genvej
remove-Action = 
    .label = Fjern genvej
CSK-reset-title = Nulstil brugerdefinerede tastaturgenveje
CSK-reset-description = Nulstil brugerdefinerede tastaturgenveje til { -brand-short-name }'s standardindstillinger.
CSK-reset-label = Nulstil brugerdefinerede tastaturgenveje
CSK-reset-button = Gendan Standard
CSK-manage-title = Administrer tastaturgenveje
CSK-remove-shortcutkey = Fjern brugerdefineret tastaturgenvej?
CSK-remove-shortcutkey-description = Er du sikker på, at du vil fjerne denne tastaturgenvej?
CSK-restore-default = Gendan Standard?
CSK-restore-default-description = Gendan { -brand-short-name }'s standardtastaturgenveje? Dine nuværende genveje går tabt.
CSK-reboot-browser-label = Genstart { -brand-short-name } for at anvende indstillingerne
CSK-reboot-browser-button = Genstart { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Nuværende tastaturgenvej: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Nuværende tastaturgenvej: { $key }.
CSK-keyborad-shortcut-is-changed = (Ikke Anvendt)
floorp-custom-actions-tab-action = Fanehandlinger
floorp-custom-actions-page-action = Sidehandlinger
floorp-custom-actions-visible-action = Synlighedshandlinger
floorp-custom-actions-search-action = Søgehandlinger
floorp-custom-actions-tools-action = Værktøjshandlinger
floorp-custom-actions-bookmark-action = Bogmærkehandlinger
floorp-custom-actions-open-page-action = Åbn Sidehandlinger
floorp-custom-actions-history-action = Historikhandlinger
floorp-custom-actions-pip-action = Billede-i-Billede Handlinger
floorp-custom-actions-downloads-action = Overførselshandlinger
floorp-custom-actions-sidebar-action = Handlinger for Sidepanel
floorp-custom-actions-bms-action = Handlinger for Browserhåndteringssidepanel
floorp-custom-actions-split-view-action = Handlinger for Delt Visning
floorp-custom-actions-workspaces-action = Handlinger for Arbejdsområder
floorp-custom-actions-custom-action = Brugerdefinerede Handlinger (Eksperimentel)

## Mouse Gestures

mouse-gesture = Musebevægelser
mouse-gesture-description = Gesturefy skal være installeret for at bruge musebevægelser med { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy er en tilføjelse, der føjer musebevægelser til din browser. Hvis { -brand-short-name } registrerer installationen af den, føjer den bevægelseskommandoer til Gesturefy, som kun er tilgængelige i { -brand-short-name }. Denne tilføjelse kan også oprette nye faner!
# Translate
TWS = Translate Web Pages
about-TWS = Oversæt din side i realtid med Google eller Yandex. Du kan også oversætte markeret tekst eller hele siden.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Privatlivshub
block-more-tracker = Bloker flere annoncer og trackere
block-tracker = Dette afsnit indeholder et sæt udvidelser designet til at blokere annoncer og trackere
view-at-AMO = Se denne tilføjelse i addons.mozilla.org
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin blokerer annoncer, omfattende trackere og flere farlige sider.
Facebook-Container = Facebook Container
about-Facebook-Container = Forhindr Facebook i at spore dig på nettet. Facebook Container-udvidelsen hjælper dig med at tage kontrol og isolere din webaktivitet fra Facebook.

## Fingerprinting

fingerprint-header = Modstå fingeraftryk og lækage af IP-adresser
block-fingerprint = Fingeraftryk er en sporingsmekanisme baseret på de unikke funktioner i din browser og dit operativsystem. Dette afsnit indeholder indstillinger til yderligere forbedring af denne beskyttelse udover standardblokeringen.
enable-firefox-fingerprint-protections = 
    .label = Aktivér kraftig beskyttelse mod fingeraftryk
about-firefox-fingerprint-protection = Aktivering af Firefox' beskyttelse omfatter bl.a. tvungen lys tilstand og deaktivering af nogle API'er. Nogle sider kan blive ødelagt.
fingerprint-Protection = 
    .label = Beskyttelse mod fingeraftryk
html5-canvas-prompt-settings = 
    .label = Afvis automatisk adgangsbekræftelsesprompter til HTML5-billeddata
canvas-prompt = Forhindrer hjemmesider i at bruge canvas- reading prompt medmindre det er tilladt manuelt.
disable-webgl = 
    .label = Deaktivér WebGL
about-webgl = WebGL er en Javascript-API til at gengive grafik, som kan bruges til at identificere GPU'en.
Canvas-Blocker = Canvas Blocker
about-CB = Denne tilføjelse forfalsker data brugt af fingeraftryksteknikker.
WebRTC-connection = WebRTC er en standard, der muliggør realtidsopkald. Deaktiverer du denne indstilling, kan du ikke bruge Discord osv.
WebRTC = 
    .label = Aktivér WebRTC-forbindelse
################################################################### browser ###############################################################

rest-mode = Tager en pause...
rest-mode-description = { -brand-short-name } er i øjeblikket suspenderet. Tryk på ENTER eller OK for at fortsætte.
Sidebar2 = 
    .label = Browser Manager Sidebjælke
    .tooltiptext = Ændr sidepanelets synlighed
sidebar2-mute-and-unmute = 
    .label = Slå lyden fra/til for dette panel
sidebar2-unload-panel = 
    .label = Fjern dette panel
sidebar2-change-ua-panel = 
    .label = Slå mobilbrugeragent til/fra
sidebar2-delete-panel = 
    .label = Slet dette panel
sidebar2-change-zoom-level = 
    .label = Skift zoomniveau
sidebar2-zoom-in = 
    .label = Zoom ind
sidebar2-zoom-out = 
    .label = Zoom ud
sidebar2-reset-zoom = 
    .label = Nulstil zoom
sidebar2-close-button = 
    .tooltiptext = Luk sidepanel
sidebar-back-button = 
    .tooltiptext = Tilbage
sidebar-forward-button = 
    .tooltiptext = Fremad
sidebar-reload-button = 
    .tooltiptext = Genindlæs
sidebar-go-index-button = 
    .tooltiptext = Gå Hjem
sidebar-muteAndUnmute-button = 
    .tooltiptext = Slå lyden til/fra i sidepanel
sidebar2-browser-manager-sidebar = Browser Manager
show-browser-manager-sidebar = 
    .tooltiptext = Vis Sidepanel for { sidebar2-browser-manager-sidebar }
sidebar2-bookmark-sidebar = Bogmærker
show-bookmark-sidebar = 
    .tooltiptext = Vis Sidepanel for { sidebar2-bookmark-sidebar }
sidebar2-history-sidebar = Historik
show-history-sidebar = 
    .tooltiptext = Vis Sidepanel for { sidebar2-history-sidebar }
sidebar2-download-sidebar = Downloads
show-download-sidebar = 
    .tooltiptext = Vis Sidepanel for { sidebar2-download-sidebar }
sidebar2-notes-sidebar = Noter
show-notes-sidebar = 
    .tooltiptext = Vis Sidepanel for { sidebar2-notes-sidebar }
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Tilføjelser og temaer
sidebar2-hide-sidebar-button = 
    .tooltiptext = Skjul Browserhåndteringssidepanel
sidebar-passwords-button = 
    .tooltiptext = Adgangskoder
sidebar-preferences-button = 
    .tooltiptext = Indstillinger
sidebar-keepWidth-button = 
    .tooltiptext = Behold den nuværende bredde på dette panel
sidebar2-keep-width-for-global = 
    .label = Anvend denne bredde på alle paneler uden tilpasset bredde
bsb-context-add = 
    .label = Føj side til Webpanel...
bsb-context-link-add = 
    .label = Føj link til Webpanel...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Åbn Profilmappe
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Genopbyg browser CSS-filer
    .accesskey = R
make-browsercss-file = 
    .label = Opret browser CSS-fil
    .accesskey = M
open-css-folder = 
    .label = Åbn CSS-mappe
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Rediger userChrome.css-fil
edit-userContentCss-editor = 
    .label = Rediger userContent.css-fil
not-found-editor-path = Kunne ikke finde en CSS-fileditor
set-pref-description = Indtast filplaceringen for den CSS-fileditor, du vil bruge:
rebuild-complete = Genopbygningen er fuldført.
please-enter-filename = Indtast venligst et filnavn.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Genåbn lukket fane
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Aktivér som et undertema
dual-theme-disable-addon-button = Deaktivér undertema
dual-theme-enabled-heading = Aktiveret som et undertema
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Statuslinje
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Åbn Tree Style Tab-panel
gf-floorp-open-tree-style-tab-description = Åbn Tree Style Tab-panel i sidepanelet
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Åbn Bogmærkepanel
gf-floorp-open-bookmarks-sidebar-description = Åbn bogmærkepanel i sidepanelet
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Åbn Historikpanel
gf-floorp-open-history-sidebar-description = Åbn historikpanel i sidepanelet
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Åbn Panel med Synkroniserede Faner
gf-floorp-open-synctabs-sidebar-description = Åbn panel med synkroniserede faner i sidepanelet
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Luk Sidepanel
gf-floorp-close-sidebar-description = Luk sidepanel
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Åbn BHS
gf-floorp-open-browser-manager-sidebar-description = Åbn Browserhåndteringssidepanel, hvis Webpanelet til det er indlæst
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Luk BHS
gf-floorp-close-browser-manager-sidebar-description = Luk sidepanel for browserhåndtering
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Vis/Skjul BHS
gf-floorp-show-browser-manager-sidebar-description = Vis/skjul sidepanel for browserhåndtering
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Skjul Statuslinje
gf-floorp-hide-statusbar-description = Skjul statuslinje
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Vis/Skjul Statuslinje
gf-floorp-show-statusbar-description = Vis eller skjul statuslinje
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Åbn den valgte tilføjelse i sidepanel
gf-floorp-open-extension-sidebar-description = Åbn den valgte tilføjelse i sidepanelet
gf-floorp-open-extension-sidebar-settings-addons-id = Tilføjelse af sidebjælke
gf-floorp-open-extension-sidebar-settings-addons-id-description = Udvidelsen af tilføjelsen åben for sidebar
gf-floorp-open-extension-sidebar-settings-list-default = Vælg venligst tilføjelse
gf-floorp-open-extension-sidebar-settings-list-unknwon = Ukendt tilføjelse
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Opdateringer fundet!
update-portable-notification-found-message = Henter opdateringer...
update-portable-notification-ready-title = Klar til at opdatere!
update-portable-notification-ready-message = { -brand-short-name } opdateres ved den næste opstart.
update-portable-notification-success-title = Opdatering lykkedes!
update-portable-notification-success-message = Opdatering lykkedes! Håber, du nyder den nye version af { -brand-short-name }!
update-portable-notification-failed-title = Opdatering mislykkedes.
update-portable-notification-failed-redirector-message = Opdatering mislykkedes. Genstart af browseren løser muligvis problemet.
update-portable-notification-failed-prepare-message = Kunne ikke forberede opdateringen.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Portable Opdatering
floorp-update-application-auto-enabled-option = 
    .label = Søg automatisk efter opdateringer til { -brand-short-name } portable. (Anbefales)
##################################################################### Open link in external ###############################################################
openInExternal-title = Åbn i ekstern browser
open-link-in-external-enabled-option = 
    .label = Aktivér funktionen "Åbn i ekstern browser"
open-link-in-external-select-browser-option = Vælg den browser, der åbnes
open-link-in-external-select-browser-option-default = 
    .label = Standardbrowser
open-link-in-external-tab-context-menu = Åbn i ekstern browser
open-link-in-external-tab-dialog-title-error = Der opstod en fejl:
open-link-in-external-tab-dialog-message-default-browser-not-found = Standardbrowseren blev ikke fundet eller er ikke konfigureret.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Den valgte browser findes ikke.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Ny
memo-title-input-placeholder = Skriv en titel her
memo-input-placeholder = Skriv eller indsæt et notat her
delete-memo = Slet
save-memo = Gem
memo-welcome-title = Velkommen!
memo-first-tip = Velkommen til { -brand-short-name } Noter! Her er nogle instruktioner om, hvordan du bruger det!
memo-second-tip = { -brand-short-name } Noter er en notesblok, hvor du kan gemme flere noter, som synkroniseres på tværs af enheder. For at aktivere synkronisering skal du logge ind på { -brand-short-name } med din Firefox-konto.
memo-third-tip = { -brand-short-name } Noter gemmes i dine { -brand-short-name }-indstillinger og synkroniseres på tværs af enheder med Firefox Sync. Firefox Sync krypterer indholdet med adgangskoden til din Firefox-konto, så ingen andre end dig kender indholdet.
memo-import-data-tip = Firefox Sync er ikke en backup-tjeneste. Vi anbefaler, at du opretter sikkerhedskopier.
memo-new-title = Ny Note
chage-view-mode = Skift Vis/Rediger Tilstand
readonly-mode = Offline (Skrivebeskyttet)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Ablaze Support
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Ryd Overførsler
    .accesskey = D
    .tooltiptext = Ryd Overførsler
floorp-show-all-downloads = 
    .label = Vis alle overførsler
    .accesskey = S
    .tooltiptext = Vis alle overførsler
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Opret nyt Arbejdsområde...
    .tooltiptext = Opret et nyt Arbejdsområde
workspaces-manage-workspaces-button = 
    .label = Administrer Arbejdsområder...
    .tooltiptext = Administrer dine Arbejdsområder
reorder-this-workspace-to-up = 
    .label = Flyt dette Arbejdsområde op
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Flyt dette Arbejdsområde ned
    .accesskey = A
rename-this-workspace = 
    .label = Omdøb Arbejdsområde
    .accesskey = R
delete-this-workspace = 
    .label = Slet Arbejdsområde
    .accesskey = D
manage-this-workspaces = 
    .label = Administrer Arbejdsområder...
    .accesskey = M
workspace-new-default-name = Nyt Arbejdsområde
workspace-default-name = Standard
move-tab-another-workspace = 
    .label = Flyt til et andet Arbejdsområde
rename-workspace-prompt-title = Omdøb Arbejdsområde
rename-workspace-prompt-text = Indtast Arbejdsområdets navn. De fleste tegn og symboler kan bruges.
workspaces-toolbar-button = Arbejdsområder
    .label = Arbejdsområder
    .tooltiptext = Vælg et Arbejdsområde...

## Preferences

enable-workspaces = 
    .label = Aktivér Arbejdsområder
    .tooltiptext = Aktivér Arbejdsområder
workspace-notice = Arbejdsområder virker ikke med denne indstilling aktiveret, medmindre arbejdsområdeknappen er placeret på værktøjslinjen. Brug denne indstilling, hvis du vil deaktivere Arbejdsområder helt.
enable-workspaces-with-experimental = 
    .label = Aktivér Arbejdsområder (Eksperimentel)
    .tooltiptext = Aktivér Arbejdsområder (Eksperimentel)
workspace-warning = Arbejdsområder kan ikke bruges med Fanegruppe-tilføjelser. Vil du bruge disse tilføjelser, skal du deaktivere Arbejdsområder og genstarte { -brand-short-name }.
category-workspaces = 
    .label = Arbejdsområder
    .tooltiptext = Arbejdsområder
pane-workspaces-title = Arbejdsområder
floorp-workspaces-title = { -brand-short-name } Arbejdsområder
floorp-workspace-settings-button = Indstillinger for Arbejdsområde...
floorp-preferences-label = Præferencer
floorp-extensions-label = Udvidelser
floorp-private-label = Privat
change-to-close-workspace-popup-option = 
    .label = Luk pop op-vinduet Arbejdsområder, når du vælger et Arbejdsområde
manage-workspace-on-bms-option = 
    .label = Administrer arbejdsområde på Browser Manager Sidebar
show-workspace-name-option = 
    .label = Vis arbejdsområdets navn på fanelinjens arbejdsområdeknap
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Delingstilstand
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Log ind på din Firefox-konto
welcome-to-floorp = Velkommen til { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } er en funktionsrig, fleksibel browser, der understøtter forskellige miljøer og er baseret på Firefox.
welcome-start-setup = Klar til at begynde?
welcome-skip-to-start-browsing = Spring Over for at Starte Browsing
welcome-select-preferences-template = Vælg en skabelon
welcome-minimum-template = Grundlæggende
welcome-enable-basic-features = Aktivér basisfunktioner og -indstillinger for en enkel oplevelse.
welcome-medium-template = Standard
welcome-enable-some-features = Aktivér yderligere funktioner og indstillinger for en bedre oplevelse.
welcome-maximum-template = Avanceret
welcome-enable-most-of-features = Aktivér avancerede funktioner og indstillinger. Anbefales til erfarne brugere.
welcome-go-next-setup = Næste
welcome-select-browser-design = Vælg et Browserdesign
welcome-describe-browser-design = Du kan vælge et af de vidunderlige tredjepartsdesigns for { -brand-short-name }. OS-specifikke designs er også tilgængelige i Indstillinger.
welcome-design-lepton-name = Lepton Original Design
welcome-design-photon-name = Lepton Photon Design
welcome-design-ProtonFix-name = Lepton ProtonFix Design
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Firefox Proton Design
welcome-import-data = Importér Dine Browserdata
welcome-import-data-description = Hurtig opsætning! Importér dine bogmærker, adgangskoder og mere fra din gamle browser. Firefox-brugere kan importere data fra Firefox Sync.
welcome-import-data-button = Importér Data...
welcome-import-data-skip = Spring Import Over
welcome-select-button = Vælg
welcome-finish-setup = Opsætning Fuldført!
welcome-finish-setup-description = Så er du klar! Andre funktioner som Lodrette Faner og Arbejdsområder kan findes i { -brand-short-name }'s Indstillinger. God fornøjelse med { -brand-short-name }!
welcomet-finish-setup = Begynd at surfe på nettet
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Tastaturgenveje
    .tooltiptext = Tastaturgenveje
category-CSK-title = Tastaturgenveje
shortcutkey-customize = 
    .title = Tastaturgenveje
select-shortcutkeyAction = Vælg en handling at udløse
shortcutkey-customize-key-list-placeholder = Din tastaturgenvej vises her
shortcut-key-label = Tastaturgenvej
start-input-button-listen = Start med at lytte
end-input-button-listen = Stop med at lytte
shortcut-key-description = Klik på "Start med at lytte", og indtast din nye tastaturgenvej til denne handling. Flere taster kan bruges, men tastaturgenveje virker ikke, hvis de allerede er tildelt andre handlinger.
floorp-custom-actions-open-new-tab = Åbn en ny fane
    .label = Åbn en ny fane
floorp-custom-actions-close-tab = Luk den nuværende fane
    .label = Luk den nuværende fane
floorp-custom-actions-open-new-window = Åbn et nyt vindue
    .label = Åbn et nyt vindue
floorp-custom-actions-open-new-private-window = Åbn et nyt privat vindue
    .label = Åbn et nyt privat vindue
floorp-custom-actions-close-window = Luk det nuværende vindue
    .label = Luk det nuværende vindue
floorp-custom-actions-restore-last-session = Gendan den sidste session
    .label = Gendan den sidste session
floorp-custom-actions-restore-last-window = Gendan det sidste vindue
    .label = Gendan det sidste vindue
floorp-custom-actions-show-next-tab = Vis den næste fane
    .label = Vis den næste fane
floorp-custom-actions-show-previous-tab = Vis den forrige fane
    .label = Vis den forrige fane
floorp-custom-actions-show-all-tabs-panel = Vis alle faner panel
    .label = Vis listen over faner
floorp-custom-actions-send-with-mail = Send med mail
    .label = Send via e-mail
floorp-custom-actions-save-page = Gem side
    .label = Gem side
floorp-custom-actions-print-page = Udskriv side
    .label = Udskriv side
floorp-custom-actions-mute-current-tab = Slå lyd til/fra for nuværende fane
    .label = Slå lyd til/fra for nuværende fane
floorp-custom-actions-toggle-bookmark-toolbar = Vis/skjul bogmærkelinje
    .label = Vis/skjul bogmærkelinje
floorp-custom-actions-show-source-of-page = Vis sidens kilde
    .label = Åbn Sidekilde
floorp-custom-actions-show-page-info = Vis sideinfo
    .label = Åbn Sideinfo
floorp-custom-actions-zoom-in = Zoom ind
    .label = Zoom ind
floorp-custom-actions-zoom-out = Zoom ud
    .label = Zoom ud
floorp-custom-actions-reset-zoom = Nulstil zoom
    .label = Nulstil zoom
floorp-custom-actions-back = Tilbage
    .label = Tilbage
floorp-custom-actions-forward = Fremad
    .label = Fremad
floorp-custom-actions-reload = Genindlæs
    .label = Genindlæs
floorp-custom-actions-stop = Stop
    .label = Stop
floorp-custom-actions-force-reload = Tving genindlæsning
    .label = Tving genindlæsning
floorp-custom-actions-search-in-this-page = Søg på denne side
    .label = Find på siden
floorp-custom-actions-show-next-search-result = Vis næste søgeord i dette sideresultat
    .label = Næste "Find på siden"-resultat
floorp-custom-actions-show-previous-search-result = Vis forrige søgeord i dette sideresultat
    .label = Forrige "Find på siden"-resultat
floorp-custom-actions-search-the-web = Søg på nettet
    .label = Søg på nettet
floorp-custom-actions-open-migration-wizard = Åbn migrationsguide
    .label = Åbn migrationsguide
floorp-custom-actions-quit-from-application = Afslut fra applikation
    .label = Afslut { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Tilpas Værktøjslinje
    .label = Åbn Tilpas { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Gå i offline-tilstand
    .label = Gå i offline-tilstand
floorp-custom-actions-open-screen-capture = Åbn værktøj til skærmoptagelse
    .label = Tag et skærmbillede
floorp-custom-actions-show-pip = Vis billede-i-billede
    .label = Vis Billede-i-billede
floorp-custom-actions-bookmark-this-page = Bogmærk denne side
    .label = Bogmærk denne side
floorp-custom-actions-open-bookmarks-sidebar = Åbn sidepanel for bogmærker
    .label = Åbn sidepanel for bogmærker
floorp-custom-actions-open-bookmark-add-tool = Åbn værktøjet til at tilføje bogmærke
    .label = Tilføj Bogmærke
floorp-custom-actions-open-bookmark-add-toolbar = Åbn pop op-vinduet "Tilføj nyt bogmærke"
    .label = Føj til bogmærkeværktøjslinje
floorp-custom-actions-open-bookmarks-manager = Åbn bogmærke- håndtering
    .label = Åbn Bogmærker Manager
floorp-custom-actions-show-bookmark-toolbar = Vis/skjul bogmærkelinje
    .label = Vis/skjul bogmærkelinje
floorp-custom-actions-open-general-preferences = Åbn generelle indstillinger
    .label = Åbn Generelle Indstillinger
floorp-custom-actions-open-privacy-preferences = Åbn privatlivsindstillinger
    .label = Åbn Privatlivsindstillinger
floorp-custom-actions-open-workspaces-preferences = Åbn Indstillinger for Arbejdsområder
    .label = Åbn Indstillinger for Arbejdsområder
floorp-custom-actions-open-containers-preferences = Åbn indstillinger for beholdere
    .label = Åbn Indstillinger for Beholdere
floorp-custom-actions-open-search-preferences = Åbn søgeindstillinger
    .label = Åbn Søgeindstillinger
floorp-custom-actions-open-sync-preferences = Åbn synkroniseringsindstillinger
    .label = Åbn Synkroniseringsindstillinger
floorp-custom-actions-open-task-manager = Åbn opgavehåndtering
    .label = Åbn { -brand-short-name }'s Opgavehåndtering
floorp-custom-actions-open-home-page = Åbn { -brand-short-name }'s startside
    .label = Åbn { -brand-short-name }'s startside
floorp-custom-actions-open-addons-manager = Åbn tilføjelser og temaer
    .label = Åbn tilføjelser og temaer
floorp-custom-actions-forget-history = Glem historik
    .label = Glem historik
floorp-custom-actions-quick-forget-history = Hurtig-glem historik
    .label = Hurtig-glem historik
floorp-custom-actions-clear-recent-history = Ryd seneste historik
    .label = Ryd seneste historik
floorp-custom-actions-search-history = Søg i historik
    .label = Søg i historik
floorp-custom-actions-manage-history = Administrer historik
    .label = Administrer historik
floorp-custom-actions-open-downloads = Åbn overførsler
    .label = Åbn Overførsler
floorp-custom-actions-show-bms = Vis/skjul Browserhåndteringssidepanel
    .label = Vis/skjul Browserhåndteringssidepanel
floorp-custom-actions-show-current-panel = Vis/skjul nuværende panel
    .label = Vis/skjul nuværende panel
floorp-custom-actions-show-bookmark-sidebar = Vis sidepanel for bogmærker
    .label = Vis sidepanel for bogmærker
floorp-custom-actions-show-history-sidebar = Vis sidepanel for historik
    .label = Vis sidepanel for historik
floorp-custom-actions-show-synced-tabs-sidebar = Vis synkroniserede faner i sidepanel
    .label = Vis synkroniserede faner i sidepanel
floorp-custom-actions-reverse-sidebar = Omvendt sidebjælkeposition
    .label = Omvendt sidebjælkeposition
floorp-custom-actions-hide-sidebar = Skjul sidepanel
    .label = Skjul sidepanel
floorp-custom-actions-show-sidebar = Vis/skjul sidepanel
    .label = Vis/skjul sidepanel
floorp-custom-actions-toggle-sidebar = Vis/skjul sidepanel
    .label = Vis/skjul sidepanel
floorp-custom-actions-open-previous-workspace = Åbn forrige arbejdsområde
    .label = Åbn forrige arbejdsområde
floorp-custom-actions-open-next-workspace = Åbn næste arbejdsområde
    .label = Åbn næste arbejdsområde
floorp-custom-actions-show-panel-1 = Skift panel 1
    .label = Skift panel 1
floorp-custom-actions-show-panel-2 = Skift panel 2
    .label = Skift panel 2
floorp-custom-actions-show-panel-3 = Skift panel 3
    .label = Skift panel 3
floorp-custom-actions-show-panel-4 = Skift panel 4
    .label = Skift panel 4
floorp-custom-actions-show-panel-5 = Skift panel 5
    .label = Skift panel 5
floorp-custom-actions-show-panel-6 = Skift panel 6
    .label = Skift panel 6
floorp-custom-actions-show-panel-7 = Skift panel 7
    .label = Skift panel 7
floorp-custom-actions-show-panel-8 = Skift panel 8
    .label = Skift panel 8
floorp-custom-actions-show-panel-9 = Skift panel 9
    .label = Skift panel 9
floorp-custom-actions-show-panel-10 = Skift panel 10
    .label = Skift panel 10
floorp-custom-actions-open-split-view-on-left = Åbn nuværende fane til venstre i delt visning
    .label = Åbn nuværende fane til venstre i delt visning
floorp-custom-actions-open-split-view-on-right = Åbn nuværende fane til højre i delt visning
    .label = Åbn nuværende fane til højre i delt visning
floorp-custom-actions-close-split-view = Luk delt visning
    .label = Luk delt visning
floorp-custom-actions-custom-action-1 = Brugerdefineret handling 1
    .label = Brugerdefineret handling 1
floorp-custom-actions-custom-action-2 = Brugerdefineret handling 2
    .label = Brugerdefineret handling 2
floorp-custom-actions-custom-action-3 = Brugerdefineret handling 3
    .label = Brugerdefineret handling 3
floorp-custom-actions-custom-action-4 = Brugerdefineret handling 4
    .label = Brugerdefineret handling 4
floorp-custom-actions-custom-action-5 = Brugerdefineret handling 5
    .label = Brugerdefineret handling 5
floorp-custom-actions-rest-mode = Aktivér hviletilstand
    .label = Aktivér hviletilstand
floorp-custom-actions-hide-user-interface = Vis/skjul brugergrænseflade
    .label = Vis/skjul brugergrænseflade
floorp-custom-actions-toggle-navigation-panel = Vis/skjul navigationspanel
    .label = Vis/skjul navigationspanel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Start
    .tooltiptext = Start { -brand-short-name } med denne profil
floorp-profiles-in-use = Denne profil er i brug.
floorp-profiles-title = Profiler
floorp-profile-manager = Profiladministrator
floorp-profiles-create = Opret Profil
floorp-profile = Profil
    .label = Profiladministrator
    .tooltiptext = Åbn Profiladministrator
fxa-not-signed-in = Ikke logget ind
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privat
floorp-toggle-private-container = 
    .label = Genåbn i Privat/Ingen Beholder
    .accesskey = P
open-in_private-container = 
    .label = Åbn i ny fane med privat beholder
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Åbn i delt visning
floorp-split-view-fixed-menu = 
    .label = Del denne fane i en fane uden delt visning
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Fjern delt visning
split-view-title = Indstillinger for Delt Visning
split-view-position = Position
split-view-flex-type = Flex-type
split-view-position-top = Top Side
split-view-position-left = Standard
split-view-position-right = Omvendt
split-view-flex-column = Lodret
split-view-flex-row = Vandret
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Scan QR-kode med din telefon
qrcode-generate-page-action = 
    .tooltiptext = Del denne side med din telefon
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Knap til Samlede Udvidelser
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Installer app
    .tooltiptext = Installer dette websted som en app
ssb-page-action-title = Installer app
ssb-app-open-button = 
    .label = Åbn i app
ssb-app-install-button = 
    .label = Installer
ssb-app-cancel-button = 
    .label = Annuller
floorp-open-manage-ssb-page = 
    .label = Administrer installerede webapps
appmenuitem-webapps = 
    .label = Webapps
appmenu-open-installed-apps-subheader = Åbn installerede webapps
appmenuitem-install-current-page = 
    .label = Installer dette websted som en app
appmenuitem-open-current-page = 
    .label = Åbn dette websted på installeret app
appmenuitem-contextmenu-open-app = 
    .label = Åbn denne app
appmenuitem-contextmenu-uninstall-app = 
    .label = Afinstaller denne app

## Preferences

category-ssb = 
    .label = Webapps
    .tooltiptext = Webapps
category-ssb-title = Webapps
floorp-ssb-title = Webapps
floorp-ssb-description = Webapps er hjemmesider, der kan installeres som apps. De kan startes fra { -brand-short-name }'s menupanel eller Windows' Start-menu.
ssb-preferences = Indstillinger for Webapps
floorp-enable-ssb = 
    .label = Aktivér Webapps
floorp-enable-ssb-with-experimental = 
    .label = Aktivér Webapps (Eksperimentel)
floorp-enable-ssb-description = Denne funktion er eksperimentel på Mac og Linux. Det anbefales at aktivere den på Windows.
floorp-disable-toolbars = 
    .label = Deaktivér værktøjslinjer i Webapps-vindue
floorp-disable-toolbars-description = Denne indstilling skjuler alle udvidelser og værktøjslinjer i Webapps-vindue.
ssb-installed-list-title = Installerede Webapps
ssb-uninstall-title = Afinstaller Webapp
ssb-uninstall-message = Er du sikker på, at du vil afinstallere denne Webapp fra { -brand-short-name }?
ssb-uninstall-button = 
    .label = Afinstaller
ssb-uninstall-cancel = Annuller
######################################################################### Download Notification ###############################################################
floorp-started-download = Overførsel begyndt
floorp-finished-download = Overførsel fuldført
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } er opdateret!
floorp-notificationContent-latest = { -brand-short-name } er opdateret. Du bruger den seneste version af { -brand-short-name }.
floorp-notificationTitle = Ny version af { -brand-short-name } er tilgængelig!
floorp-notificationContent = Klik for at hente den seneste version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
