# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> est un navigateur développé au Japon. Il est basé sur Firefox et est développé par <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, afin d'améliorer le web. Vous souhaitez nous aider ? <label data-l10n-name="helpus-donateLink">Faites un don</label>
icon-creator = Créateurs des icônes, <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> et <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Une liste de <label data-l10n-name="about-contributor">contributeurs et développeurs</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Conception
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Un redémarrage est nécessaire pour appliquer les modifications
tab-width = Largeur minimale des onglets
preferences-tabs-newtab-position = Position du nouvel onglet
open-new-tab-use-default = 
    .label = Ouvrir de nouveaux onglets à la position par défaut
open-new-tab-at-the-end = 
    .label = Ouvrir de nouveaux onglets à la fin de la barre d'onglets
open-new-tab-next-to-current = 
    .label = Ouvrir de nouveaux onglets à côté de l'onglet actuel
multirow-tabs-limit = 
    .label = Activer la limite de lignes pour les onglets multilignes
multirow-tabs-newtab = 
    .label = Placer le bouton "Ouvrir un nouvel onglet" à la fin de la dernière rangée d'onglets
multirow-tabs-value = Nombre de lignes lorsque les onglets multilignes sont activés
enable-tab-sleep = 
    .label = Activer les onglets en veille
tab-sleep-timeout-minutes-value = Les onglets se mettent en veille après avoir été inactifs pendant (minutes)
tab-sleep-settings-button = Paramètres…
tab-sleep-settings-dialog-title = 
    .title = Paramètres des onglets en veille
tab-sleep-settings-dialog-excludehosts-label = Exclure les hôtes
tab-sleep-settings-dialog-excludehosts-label-2 = Entrez un hôte par ligne.
tab-sleep-tab-context-menu-excludetab = Garder l'onglet actif
enable-tab-scroll-change = 
    .label = Passer d'un onglet à l'autre avec la molette de la souris
enable-tab-scroll-reverse = 
    .label = Inverser le sens de navigation des onglets
enable-tab-scroll-wrap = 
    .label = Envelopper les onglets de défilement au bord
enable-double-click-block = 
    .label = Fermer les onglets avec un double-clic
enable-show-pinned-tabs-title = 
    .label = Afficher le titre des onglets épinglés
tabbar-preference = Barre d'onglets
tab-normal-mode = 
    .label = Défaut
hide-horizontality-tabs = 
    .label = Masquer les onglets dans la barre d'onglets horizontale
verticalTab-setting = 
    .label = Optimiser le navigateur pour la barre d'onglets verticale
move-tabbar-position = 
    .label = Afficher la barre d'onglets sous la barre d'outils
tabbar-on-bottom = 
    .label = Afficher la barre d'onglets en bas de la fenêtre
tabbar-favicon-color = 
    .label = Coloriser la barre d'onglets avec la couleur de la favicône du site internet actuel
tabbar-style-preference = Style de la barre d'onglets
horizontal-tabbar = 
    .label = Barre d'onglets horizontale
tabbar-style-description = Un redémarrage de { -brand-short-name } est nécessaire pour appliquer complètement ce paramètre.
multirow-tabbar = 
    .label = Barre d'onglets multi-lignes
vertical-tabbar = 
    .label = Barre d'onglets verticale (expérimentale)
native-vertical-tab-show-right = 
    .label = Afficher la barre d'onglets verticale sur le côté droit de la fenêtre
native-vertical-tab-show-padding = 
    .label = Activer un espace au sommet
hover-vertical-tab = 
    .label = Réduire la barre d'onglets verticale
floorp-show-vertical-tab-newtab-button = 
    .label = Afficher le bouton "Ouvrir un nouvel onglet" dans la barre d'onglets verticale
floorp-show-vertical-tab-scrollbar = 
    .label = Afficher la barre de défilement sur la barre d'onglets verticale
TST = Tree Style Tab
about-TST = Tree Style Tab est une extension populaire qui vous permet d'afficher des onglets dans une structure arborescente. Cette extension est déjà pré-intégrée dans { -brand-short-name }. Veuillez l'installer pour activer Tree Style Tab dans { -brand-short-name }.
treestyletab-Settings = 
    .label = Réduire Tree Style Tab
sidebar-reverse-position-toolbar = Afficher les barres latérales de l'autre côté
bookmarks-bar-settings = Barre d'outil des marque-pages (une seule option peut être utilisée à la fois)
bookmarks-focus-mode = 
    .label = Masquer la barre d'outils des marque-pages à moins que l'on ne survole la barre de navigation
bookmarks-bottom-mode = 
    .label = Afficher la barre d'outils des marque-pages au bas de { -brand-short-name }
navbar-settings = Barre de navigation
show-nav-bar-bottom = 
    .label = Afficher la barre d'outils en bas de { -brand-short-name } (expérimental)
material-effect = 
    .label = Autoriser « Mica for Everyone » pour la modification du style du navigateur (Déprécié)
disable-extension-check-compatibility-option = 
    .label = Ne pas vérifier la compatibilité avec les extensions (obsolète)
other-preference = Autres préférences
enable-userscript = 
    .label = Activer les composants hérités (obsolète)
about-userscript = L'activation de cette fonctionnalité peut provoquer des bugs inattendus ou des erreurs fatales.
search-positon-top = 
    .label = Afficher la barre de recherche en haut de la page
allow-auto-restart = 
    .label = Redémarrer automatiquement lorsque les paramètres nécessitant un redémarrage sont modifiés
disable-fullscreen-notification = 
    .label = Ne pas afficher de notification lorsque vous entrez en plein écran

## Browser Theme

system-color-settings = Certains thèmes ont un mode clair et un mode sombre — choisissez quel mode vous souhaitez que ces thèmes utilisent.
preferences-theme-appearance-header = Thèmes
system-theme-dark = 
    .label = Sombre
system-theme-light = 
    .label = Clair
system-theme-auto = 
    .label = Adapter au système

## User interface preferences

ui-preference = Apparence du navigateur
preferences-browser-appearance-description = Choisissez une apparence tierce intégrée à utiliser dans { -brand-short-name }. Certaines apparences peuvent ne pas être compatibles avec votre configuration.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (obsolète)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (obsolète)
floorp-gnomeUI = 
    .label = Thème GNOME (obsolète)

## Download Manager

download-notification-preferences = Notifications de téléchargement
start-always-notify = 
    .label = Notifier uniquement lors du démarrage d'un téléchargement
finish-always-notify = 
    .label = Notifier uniquement quand un téléchargement se termine
always-notify = 
    .label = Notifier lors du démarrage des téléchargements et quand un téléchargement se termine
do-not-notify = 
    .label = Désactiver les notifications de téléchargement

## Sidebar

profiles-button-label = Gérer les profils
floorp-help-button-label = Support de { -brand-short-name }
appmenuitem-reboot = 
    .label = Redémarrer

## UserAgent

userAgent-preference = Agent utilisateur (obsolète)
default-useragent-mode = 
    .label = Utiliser l'agent utilisateur de Firefox (par défaut)
windows-chrome-useragent-mode = 
    .label = Se faire passer pour Chrome sous Windows
macOS-chrome-useragent-mode = 
    .label = Se faire passer pour Chrome sous macOS
linux-chrome-useragent-mode = 
    .label = Se faire passer pour Chrome sous Linux
mobile-chrome-useragent-mode = 
    .label = Se faire passer pour Chrome sous iOS
use-custom-useragent-mode = 
    .label = Utiliser un agent utilisateur personnalisé

## DMR UI

download-mgr-UI = 
    .label = Activer le gestionnaire de téléchargement SimpleUI
downloading-red-color = 
    .label = Utiliser l'icône rouge de téléchargement
sidebar-preferences = Barre latérale
bsb-preferences = Paramètres de la barre latérale de gestion du navigateur
view-sidebar2-right = 
    .label = Afficher la barre latérale de gestion du navigateur à droite
enable-sidebar2 = 
    .label = Activer la barre latérale de gestion du navigateur
visible-bms = 
    .label = Afficher la barre latérale de gestion du navigateur
hide-bms-to-unload-panel = 
    .label = Décharger le panneau lors de son masquage
enable-addons-in-sidebar2-with-experimental = 
    .label = Activer les scripts de contenus des extensions dans la barre latérale de gestion du navigateur (expérimental)
enable-addons-in-sidebar2 = 
    .label = Activer les scripts de contenus des extensions dans la barre latérale de gestion du navigateur
sidebar2-enable-addons-desc = Si ce paramètre est activé, les bloqueurs de publicités et autres extensions fonctionneront dans la barre latérale. Cependant, toutes les extensions ne fonctionneront pas.
custom-URL-option = Définir les URL du panneau Web
set-custom-URL-button = 
    .label = Définir des URL personnalisées…
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Barre latérale de gestion du navigateur
bsb-context = Utiliser le conteneur suivant
bsb-userAgent-label = 
    .label = Utiliser l'agent utilisateur pour mobile dans ce panneau web
bsb-width = Largeur (si définie à 0, la valeur globale sera utilisée)
bsb-page = Page à ouvrir
bsb-add = Ajouter le panneau Web sur la barre latérale de gestionnaire de navigateur
bsb-setting = Paramètres du panneau web
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Site Web
sidebar2-pref-delete = 
    .label = Supprimer
sidebar2-pref-setting = 
    .label = Paramètres
sidebar2-global-width = Largeur globale des panneaux web
use-icon-provider-option = Utiliser le fournisseur d'icônes
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (disponible en Chine)
use-icon-provider-option-hatena = 
    .label = Hatena (disponible en Chine)
memory-and-performance = Mémoire et performances
min-memory = 
    .label = Utilisation minimale de la mémoire (faible performance)
balance-memory = 
    .label = Équilibrer l'utilisation de la mémoire et des performances
max-memory = 
    .label = Meilleures performances (utilisation élevée de la mémoire)
delete-border-and-roundup-option = 
    .label = Arrondir les angles des pages

## DualTheme

dualtheme-enable = 
    .label = Activer le double thème
newtab-background = Arrière-plan d'accueil { -brand-short-name }
newtab-background-random-image = 
    .label = Images aléatoires de Unsplash
newtab-background-gradation = 
    .label = Dégradé
newtab-background-not-background = 
    .label = Désactiver l'arrière-plan
newtab-background-selected-image = 
    .label = Dossier personnalisé…
newtab-background-selected-one-image = 
    .label = Image personnalisée…
newtab-background-folder = Utiliser les images de ce dossier :
newtab-background-image = Utiliser l'image :
newtab-choose-image = Choisir une image…
newtab-background-folder-reload = 
    .label = Recharger les images
newtab-background-folder-default = 
    .label = Restaurer les valeurs par défaut
newtab-background-folder-open = 
    .label = Ouvrir le dossier
newtab-background-folder-choose = Choisir le dossier des images…
newtab-background-image-choose = Choisir une image...
newtab-background-extensions = Utilisez des images avec ces extensions de fichier (séparées par ",")
disable-blur-on-newtab = 
    .label = Désactiver l'effet de flou dans la page d'accueil de { -brand-short-name }
disable-releasenote-on-newtab = 
    .label = Désactiver les notes de mise à jour et les liens de support sur la page d'accueil de { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Désactiver le crédit d'image (Unsplash) dans la page d'accueil de { -brand-short-name }

## Lepton Preferences

about-lepton = Personnaliser { -brand-short-name } avec Lepton
lepton-preference-button = 
    .label = Paramètres de Lepton…
    .accesskey = L
lepton-header = Paramètres de Lepton
lepton-preference = Paramètres de Lepton
photon-mode = 
    .label = Utiliser le design Photon
lepton-mode = 
    .label = Utiliser le design Lepton
protonfix-mode = 
    .label = Utiliser le design Proton ajusté
autohide-preference = Masquer automatiquement les éléments du navigateur
floorp-lepton-enable-tab-autohide = 
    .label = Masquer automatiquement les onglets
floorp-lepton-enable-navbar-autohide = 
    .label = Masquer automatiquement la barre d'outils
floorp-lepton-enable-sidebar-autohide = 
    .label = Masquer automatiquement la barre latérale
floorp-lepton-enable-urlbar-autohide = 
    .label = Masquer automatiquement la barre d'adresse
floorp-lepton-enable-back-button-autohide = 
    .label = Masquer automatiquement le bouton reculer d'une page
floorp-lepton-enable-forward-button-autohide = 
    .label = Masquer automatiquement le bouton avancer d'une page
floorp-lepton-enable-page-action-button-autohide = 
    .label = Masquer automatiquement les boutons de la barre d'adresse
floorp-lepton-enable-toolbar-overlap = 
    .label = Afficher la barre d'outils au-dessus du contenu du site web
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Masquer automatiquement la barre d'outils lors de l'affichage du contenu "ltr"
hide-preference = Gérer les éléments du navigateur
floorp-lepton-enable-tab_icon-hide = 
    .label = Masquer les icônes des onglets
floorp-lepton-enable-tabbar-hide = 
    .label = Masquer la barre d'onglets
floorp-lepton-enable-navbar-hide = 
    .label = Masquer la barre d'outils
floorp-lepton-enable-sidebar_header-hide = 
    .label = Masquer les en-têtes de la barre latérale
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Masquer les icônes de la barre d'adresse
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Masquer les icônes de la barre des marque-pages
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Masquer les libellés de la barre des marque-pages
floorp-lepton-enable-disabled_menu-hide = 
    .label = Masquer les éléments désactivés du menu contextuel
floorp-lepton-disable-userChrome-icon = 
    .label = Désactiver le menu contextuel Lepton et les icônes de menu du panneau
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Activer les icônes du menu contextuel Lepton
positon-preferences = Ajustements de position
floorp-lepton-enable-centered-tab = 
    .label = Centrer les étiquettes dans les onglets
floorp-lepton-enable-centered-urlbar = 
    .label = Centrer le texte dans la barre d'adresse
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Centrer les éléments de la barre de signets
urlbar-preferences = Barre d'adresse
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Déplacer les icônes de la barre d'adresse vers la gauche
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Lors de la saisie, afficher un bouton "Aller"
floorp-lepton-enable-always-show-page_action = 
    .label = Toujours afficher les actions de la page dans la barre d'adresse
tabbar-preferences = Barre d'onglets
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Barre d'onglets dans la barre de titre
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Combiner la barre d'onglets et la barre d'outils
lepton-sidebar-preferences = Barre latérale
floorp-lepton-enable-overlap-sidebar = 
    .label = Afficher la barre latérale sur le contenu du site web
floorp-home-mode-choice-default = 
    .label = Accueil { -brand-short-name } (par défaut)
floorp-home-prefs-content-header = Contenu de l'accueil de { -brand-short-name }
floorp-home-prefs-content-description = Choisissez le contenu que vous souhaitez voir sur la page d'accueil de { -brand-short-name }.

## Notes

floorp-notes = { -brand-short-name } Notes
restore-from-backup = Restaurer les notes depuis la sauvegarde
enable-notes-sync = 
    .label = Activer la synchronisation de { -brand-short-name } Notes
about-notes-backup-tips = { -brand-short-name } Notes utilise Firefox Sync pour synchroniser vos notes avec d'autres appareils. Si vous perdez vos notes, vous pouvez les restaurer à partir d'une sauvegarde. Une sauvegarde est créée lorsque vous lancez { -brand-short-name }.
notes-sync-description = Cela peut résoudre le problème de la perte de contenu en raison de l'écrasement des notes lors de la synchronisation.
backuped-time = Sauvegardé le
notes-backup-option = Paramètres de sauvegarde
backup-option-button = Paramètres de sauvegarde…
restore-from-backup-prompt-title = Service de restauration de { -brand-short-name } Notes
restore-from-this-backup = Restaurer les notes dans l'état où elles se trouvaient dans cette sauvegarde ?
restore-button = Restaurer

## user.js

header-userjs = user.js
userjs-customize = Personnaliser { -brand-short-name } avec user.js
about-userjs-customize = user.js est un fichier de configuration qui vous permet de personnaliser { -brand-short-name }. Les fichiers user.js sont téléchargés depuis internet et remplacent votre fichier user.js actuel. Veuillez sauvegarder votre fichier user.js actuel avant de continuer. Les configurations user.js seront appliquées automatiquement après le redémarrage de { -brand-short-name }.
userjs-label = liste user.js
userjs-prompt = Appliquer ce user.js ?
apply-userjs-attention = L'application d'un nouveau user.js écrasera votre fichier user.js actuel.
apply-userjs-attention2 = Veuillez sauvegarder votre fichier user.js actuel avant de continuer.
userjs-button = Paramètres user.js…
userjs-select-option = Gérez le fichier user.js actuellement utilisé dans { -brand-short-name } pour améliorer les performances et la confidentialité.
apply-userjs-button = Appliquer

## userjs Options

default-userjs-label = { -brand-short-name } par défaut
about-default-userjs = Télémétrie désactivée. { -brand-short-name } bien équilibré avec diverses personnalisations activées.
Securefox-label = Securefox par Yokoffing
about-Securefox = HTTPS par défaut. Protection totale contre les cookies avec isolement de site. État et partitionnement réseau améliorés. Diverses autres améliorations.
default-label = Yokoffing par défaut
about-default = Tous les éléments essentiels. Pas de panne. Voici votre user.js.
Fastfox-label = Fastfox par Yokoffing
about-Fastfox = Augmente considérablement la vitesse de navigation de Firefox. Donnez du fil à retordre à Chrome !
Peskyfox-label = Peskyfox par Yokoffing
about-Peskyfox = Désencombrement de la page des nouveaux onglets. Supprimer Pocket. Restaurer le mode compact en tant qu'option. Arrêter les notifications des pages web, les popups et autres désagréments.
Smoothfox-label = Smoothfox par Yokoffing
about-Smoothfox = Bénéficiez d'un défilement fluide de type Edge sur votre navigateur préféré — ou choisissez quelque chose de plus adapté à votre style.
select-workspace = Sélectionner un espace de travail
workspace-select-icon = Sélectionner l'icône de l'espace de travail
    .label = Sélectionner l'icône de l'espace de travail
workspace-select-container = Sélectionner l'onglet Conteneur
    .label = Sélectionner l'onglet Conteneur
workspace-customize = 
    .title = Personnaliser l'espace de travail
floorp-no-workspace-container = 
    .label = Pas de conteneur
workspace-icon-article = 
    .label = Article
workspace-icon-book = 
    .label = Livre
workspace-icon-briefcase = 
    .label = Tâche
workspace-icon-cart = 
    .label = Achats
workspace-icon-chat = 
    .label = Messagerie
workspace-icon-chill = 
    .label = Privé
workspace-icon-circle = 
    .label = Cercle
workspace-icon-compass = 
    .label = Boussole
workspace-icon-code = 
    .label = Code
workspace-icon-dollar = 
    .label = Bancaire
workspace-icon-fence = 
    .label = Barrière
workspace-icon-fingerprint = 
    .label = Personnel
workspace-icon-food = 
    .label = Nourriture
workspace-icon-fruit = 
    .label = Fruit
workspace-icon-game = 
    .label = Jeu
workspace-icon-gear = 
    .label = Équipement
workspace-icon-gift = 
    .label = Cadeau
workspace-icon-key = 
    .label = Clé
workspace-icon-lightning = 
    .label = Éclair
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notes
workspace-icon-paint = 
    .label = Peindre
workspace-icon-photo = 
    .label = Photo
workspace-icon-pin = 
    .label = Épingle
workspace-icon-pet = 
    .label = Animal de compagnie
workspace-icon-question = 
    .label = Question
workspace-icon-smartphone = 
    .label = Smartphone
workspace-icon-star = 
    .label = Étoiles
workspace-icon-tree = 
    .label = Arbre
workspace-icon-vacation = 
    .label = Vacances
workspace-icon-love = 
    .label = Amour
workspace-icon-moon = 
    .label = Lune
workspace-icon-music = 
    .label = Musique
workspace-icon-user = 
    .label = Utilisateur
# Custom Keyboard Shortcuts
floorp-CSK-title = Personnaliser les raccourcis clavier
floorp-CSK-description = Personnaliser les raccourcis clavier de { -brand-short-name }. { -brand-short-name } propose plus de 80 raccourcis personnalisables ! Les doublons ne fonctionneront pas. Redémarrez { -brand-short-name } pour appliquer ces paramètres.
disable-fx-actions = 
    .label = Désactiver les raccourcis clavier de Mozilla Firefox
customize-Action = 
    .label = Ajouter un raccourci
remove-Action = 
    .label = Supprimer le raccourci
CSK-reset-title = Réinitialiser les raccourcis clavier personnalisés
CSK-reset-description = Réinitialiser les raccourcis clavier personnalisés aux valeurs par défaut de { -brand-short-name }.
CSK-reset-label = Réinitialiser les raccourcis clavier personnalisés
CSK-reset-button = Restaurer les valeurs par défaut
CSK-manage-title = Gérer les raccourcis clavier
CSK-remove-shortcutkey = Supprimer le raccourci clavier personnalisé ?
CSK-remove-shortcutkey-description = Êtes-vous sûr de vouloir supprimer ce raccourci clavier ?
CSK-restore-default = Restaurer les valeurs par défaut ?
CSK-restore-default-description = Restaurer les raccourcis clavier de { -brand-short-name } par défaut ? Vos raccourcis clavier actuels seront perdus.
CSK-reboot-browser-label = Redémarrez { -brand-short-name } pour appliquer ces paramètres
CSK-reboot-browser-button = Redémarrer { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Raccourci clavier actuel : { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Raccourci clavier actuel : { $key }.
CSK-keyborad-shortcut-is-changed = (Non appliqué)
floorp-custom-actions-tab-action = Actions des onglets
floorp-custom-actions-page-action = Actions de la page
floorp-custom-actions-visible-action = Actions visibles
floorp-custom-actions-search-action = Actions de recherche
floorp-custom-actions-tools-action = Actions des outils
floorp-custom-actions-bookmark-action = Actions de marque-pages
floorp-custom-actions-open-page-action = Actions sur les pages ouvertes
floorp-custom-actions-history-action = Actions de l'historique
floorp-custom-actions-pip-action = Actions de Picture-in-Picture
floorp-custom-actions-downloads-action = Actions de téléchargement
floorp-custom-actions-sidebar-action = Actions de la barre latérale
floorp-custom-actions-bms-action = Actions de la barre latérale de gestion du navigateur
floorp-custom-actions-split-view-action = Actions en vue fractionnée
floorp-custom-actions-workspaces-action = Actions sur les espaces de travail
floorp-custom-actions-custom-action = Actions personnalisées (expérimental)

## Mouse Gestures

mouse-gesture = Gestes de la souris
mouse-gesture-description = Gesturefy doit être installé pour utiliser les gestes de souris avec { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy est une extension qui ajoute des gestes de souris à votre navigateur. Si { -brand-short-name } y détecte l'installation, il ajoutera à Gesturefy des commandes gestuelles qui ne sont disponibles que dans { -brand-short-name }. Cette extension crée également de nouveaux onglets !
# Translate
TWS = TWP - Translate Web Pages
about-TWS = Traduisez votre page en temps réel à l'aide de Google ou Yandex. Vous pouvez également traduire un texte sélectionné ou la page entière.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Centre de confidentialité
block-more-tracker = Bloquer plus de publicités et de mouchards
block-tracker = Cette section contient un ensemble d'extensions conçues pour bloquer les publicités et les mouchards
view-at-AMO = Voir cette extension dans addons.mozilla.org
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin bloque les publicités, les mouchards étendus et les sites dangereux supplémentaires.
Facebook-Container = Facebook Container
about-Facebook-Container = Empêcher Facebook de vous suivre sur internet. L'extension Facebook Container vous aide à prendre le contrôle et à isoler votre activité de Facebook.

## Fingerprinting

fingerprint-header = Résistance aux fuites d'empreintes et d'adresses IP
block-fingerprint = L'empreinte est un mécanisme de suivi qui repose sur les caractéristiques uniques de votre navigateur et de votre système d'exploitation. Cette section contient des paramètres permettant d'améliorer cette protection au-delà du blocage par défaut.
enable-firefox-fingerprint-protections = Activer une protection forte contre la prise d'empreintes
about-firefox-fingerprint-protection = L'activation de la protection par Firefox comprend le mode clair forcé, la désactivation de certaines API, etc. Certains sites peuvent cesser de fonctionner.
fingerprint-Protection = 
    .label = Protection contre les empreintes
html5-canvas-prompt-settings = 
    .label = Rejeter automatiquement les demandes de confirmation d'accès pour les données d'image HTML5
canvas-prompt = Empêche les sites internet d'utiliser la lecture du Canvas (composant de rendu qui peut tracer un utilisateur), à moins que cela ne soit autorisé manuellement.
disable-webgl = 
    .label = Désactiver WebGL
about-webgl = WebGL est une API Javascript utilisée pour le rendu graphique, il peut être utilisé pour identifier la carte graphique.
Canvas-Blocker = Bloqueur de toile
about-CB = Cette extension falsifie les données utilisées par les techniques d'empreintes.
WebRTC-connection = WebRTC est un standard qui permet d'effectuer des conversations en temps réel. Si vous désactivez cette option, vous ne pourrez plus utiliser Discord, etc.
WebRTC = 
    .label = Activer la connexion WebRTC
################################################################### browser ###############################################################

rest-mode = Fait une pause...
rest-mode-description = { -brand-short-name } est actuellement suspendu. Appuyez sur Entrée ou OK pour continuer.
Sidebar2 = 
    .label = Barre latérale de gestion du navigateur
    .tooltiptext = Modifier la visibilité de la barre latérale
sidebar2-mute-and-unmute = 
    .label = Activer/désactiver ce panneau
sidebar2-unload-panel = 
    .label = Décharger ce panneau
sidebar2-change-ua-panel = 
    .label = Activer/désactiver l'agent utilisateur mobile
sidebar2-delete-panel = 
    .label = Supprimer ce panneau
sidebar2-change-zoom-level = 
    .label = Modifier le niveau de zoom
sidebar2-zoom-in = 
    .label = Zoom avant
sidebar2-zoom-out = 
    .label = Zoom arrière
sidebar2-reset-zoom = 
    .label = Réinitialiser le zoom
sidebar2-close-button = 
    .tooltiptext = Fermer la barre latérale
sidebar-back-button = 
    .tooltiptext = Précédent
sidebar-forward-button = 
    .tooltiptext = Suivant
sidebar-reload-button = 
    .tooltiptext = Recharger
sidebar-go-index-button = 
    .tooltiptext = Aller à l'accueil
sidebar-muteAndUnmute-button = 
    .tooltiptext = Activer/désactiver la barre latérale
sidebar2-browser-manager-sidebar = Gestionnaire du navigateur
show-browser-manager-sidebar = 
    .tooltiptext = Afficher la barre latérale { sidebar2-browser-manager-sidebar }
sidebar2-bookmark-sidebar = Marque-pages
show-bookmark-sidebar = 
    .tooltiptext = Afficher la barre latérale { sidebar2-bookmark-sidebar }
sidebar2-history-sidebar = Historique
show-history-sidebar = 
    .tooltiptext = Afficher la barre latérale { sidebar2-history-sidebar }
sidebar2-download-sidebar = Téléchargements
show-download-sidebar = 
    .tooltiptext = Afficher la barre latérale { sidebar2-download-sidebar }
sidebar2-notes-sidebar = Notes
show-notes-sidebar = 
    .tooltiptext = Afficher la barre latérale { sidebar2-notes-sidebar }
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Extensions et thèmes
sidebar2-hide-sidebar-button = 
    .tooltiptext = Cacher la barre latérale de gestion du navigation
sidebar-passwords-button = 
    .tooltiptext = Mots de passe
sidebar-preferences-button = 
    .tooltiptext = Paramètres
sidebar-keepWidth-button = 
    .tooltiptext = Continuer à utiliser la largeur actuelle de ce panneau
sidebar2-keep-width-for-global = 
    .label = Appliquer cette largeur à tous les panneaux sans largeur personnalisée
bsb-context-add = 
    .label = Ajouter la page au panneau web…
bsb-context-link-add = 
    .label = Ajouter un lien au panneau web…
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Répertoire des profils ouverts
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Reconstruire les fichiers CSS du navigateur
    .accesskey = R
make-browsercss-file = 
    .label = Créer un fichier CSS pour le navigateur
    .accesskey = M
open-css-folder = 
    .label = Ouvrir le dossier CSS
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Modifier le fichier userChrome.css
edit-userContentCss-editor = 
    .label = Modifier le fichier userContent.css
not-found-editor-path = Impossible de trouver un éditeur de fichier CSS
set-pref-description = Saisissez l'emplacement du fichier de l'éditeur de fichiers CSS que vous souhaitez utiliser :
rebuild-complete = Reconstruction terminée.
please-enter-filename = Veuillez saisir le nom du fichier.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Rouvrir l'onglet fermé
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Activer en tant que sous-thème
dual-theme-disable-addon-button = Désactiver le sous-thème
dual-theme-enabled-heading = Activé en tant que sous-thème
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Barre d'état
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = Ouvre le panneau d'arborescence des onglets de [{ -brand-short-name }]
gf-floorp-open-tree-style-tab-description = Ouvrir le panneau des onglets en arborescent dans la barre latérale
gf-floorp-open-bookmarks-sidebar-name = Ouvrir le panneau des marque-pages de [{ -brand-short-name }]
gf-floorp-open-bookmarks-sidebar-description = Ouvrir le panneau des marque-pages sur la barre latérale
gf-floorp-open-history-sidebar-name = Ouvre le panneau d'historique de [{ -brand-short-name }]
gf-floorp-open-history-sidebar-description = Ouvrir le panneau d'historique dans la barre latérale
gf-floorp-open-synctabs-sidebar-name = Ouvre le panneau des onglets synchronisés de [{ -brand-short-name }]
gf-floorp-open-synctabs-sidebar-description = Ouvrir le panneau des onglets synchronisés dans la barre latérale
gf-floorp-close-sidebar-name = Ferme la barre latérale de [{ -brand-short-name }]
gf-floorp-close-sidebar-description = Fermer la barre latérale
gf-floorp-open-browser-manager-sidebar-name = Ouvrir la barre latérale de gestion du navigateur de [{ -brand-short-name }]
gf-floorp-open-browser-manager-sidebar-description = Ouvrir le gestionnaire du navigateur dans la barre latérale si le panneau web de la barre latérale de gestion du navigation est chargé
gf-floorp-close-browser-manager-sidebar-name = Fermer la barre latérale de gestion du navigateur de [{ -brand-short-name }]
gf-floorp-close-browser-manager-sidebar-description = Fermer la barre latérale de gestion du navigateur
gf-floorp-show-browser-manager-sidebar-name = Afficher/masquer la barre latérale de gestion du navigateur de [{ -brand-short-name }]
gf-floorp-show-browser-manager-sidebar-description = Activer/désactiver la barre latérale de gestion du navigateur
gf-floorp-hide-statusbar-name = Masquer la barre d'état de [{ -brand-short-name }]
gf-floorp-hide-statusbar-description = Masquer la barre d'état
gf-floorp-show-statusbar-name = Activer/désactiver la barre d'état de [{ -brand-short-name }]
gf-floorp-show-statusbar-description = Afficher/Masquer la barre d'état
gf-floorp-open-extension-sidebar-name = Ouvrir l'extension sélectionnée dans la barre d'état de [{ -brand-short-name }]
gf-floorp-open-extension-sidebar-description = Ouvrir l'extension sélectionnée dans la barre d'état
gf-floorp-open-extension-sidebar-settings-addons-id = Extension pour la barre latérale
gf-floorp-open-extension-sidebar-settings-addons-id-description = L'extension du module complément ouvert dans la barre latérale
gf-floorp-open-extension-sidebar-settings-list-default = Veuillez sélectionner une extension
gf-floorp-open-extension-sidebar-settings-list-unknwon = Extension inconnue
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Mises à jour disponibles !
update-portable-notification-found-message = Téléchargement des mises à jour en cours…
update-portable-notification-ready-title = Prêt à être mis à jour !
update-portable-notification-ready-message = { -brand-short-name } sera mis à jour lors du prochain lancement.
update-portable-notification-success-title = Mise à jour réussie !
update-portable-notification-success-message = Mise à jour réussie ! Nous espérons que vous apprécierez cette nouvelle version de { -brand-short-name } !
update-portable-notification-failed-title = La mise à jour a échoué.
update-portable-notification-failed-redirector-message = La mise à jour a échoué. Le redémarrage de votre navigateur peut résoudre ce problème.
update-portable-notification-failed-prepare-message = Échec de la préparation de la mise à jour.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = Mise à jour portable de { -brand-short-name }
floorp-update-application-auto-enabled-option = 
    .label = Vérifier automatiquement les mises à jour de { -brand-short-name } portable. (Recommandé)
##################################################################### Open link in external ###############################################################
openInExternal-title = Ouvrir dans un navigateur externe
open-link-in-external-enabled-option = 
    .label = Activer la fonctionnalité "Ouvrir dans un navigateur externe"
open-link-in-external-select-browser-option = Choisir le navigateur qui sera ouvert
open-link-in-external-select-browser-option-default = 
    .label = Navigateur par défaut
open-link-in-external-tab-context-menu = Ouvrir dans un navigateur externe
open-link-in-external-tab-dialog-title-error = Une erreur s'est produite :
open-link-in-external-tab-dialog-message-default-browser-not-found = Le navigateur par défaut n'a pas été trouvé ou n'est pas configuré.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Le navigateur sélectionné n'existe pas.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Nouveau
memo-title-input-placeholder = Écrire un titre ici
memo-input-placeholder = Ecrire ou coller un mémo ici
delete-memo = Supprimez
save-memo = Enregistrer
memo-welcome-title = Bienvenue !
memo-first-tip = Bienvenue sur { -brand-short-name } Notes ! Voici quelques instructions sur la façon de l'utiliser !
memo-second-tip = { -brand-short-name } Notes est un bloc-notes qui vous permet de stocker plusieurs notes qui se synchronisent entre les appareils. Pour activer la synchronisation, vous devez vous connecter à { -brand-short-name } avec votre compte Firefox.
memo-third-tip = Les notes { -brand-short-name } Notes seront enregistrées dans vos paramètres de { -brand-short-name } et synchronisées entre les appareils à l'aide de Firefox Sync. Firefox Sync chiffre le contenu de la synchronisation avec le mot de passe de votre compte Firefox, de sorte que personne d'autre que vous n'en connaisse le contenu.
memo-import-data-tip = Firefox Sync n'est pas un service de sauvegarde. Nous vous recommandons de créer des sauvegardes.
memo-new-title = Nouvelle note
chage-view-mode = Basculer entre le mode affichage et le mode édition
readonly-mode = Hors ligne (lecture seule)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Support Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Effacer les téléchargements
    .accesskey = D
    .tooltiptext = Effacer les téléchargements
floorp-show-all-downloads = 
    .label = Afficher tous les téléchargements
    .accesskey = S
    .tooltiptext = Afficher tous les téléchargements
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Créer un nouvel espace de travail…
    .tooltiptext = Créer un nouvel espace de travail
workspaces-manage-workspaces-button = 
    .label = Gérer les espaces de travail…
    .tooltiptext = Gérer vos espaces de travail
reorder-this-workspace-to-up = 
    .label = Déplacer vers le haut cet espace de travail
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Déplacer vers le bas cet espace de travail
    .accesskey = A
rename-this-workspace = 
    .label = Renommer l'espace de travail
    .accesskey = R
delete-this-workspace = 
    .label = Supprimer l’espace de travail
    .accesskey = D
manage-this-workspaces = 
    .label = Gérer les espaces de travail…
    .accesskey = M
workspace-new-default-name = Nouvel espace de travail
workspace-default-name = Défaut
move-tab-another-workspace = 
    .label = Déplacer vers un autre espace de travail
rename-workspace-prompt-title = Renommer l'espace de travail
rename-workspace-prompt-text = Saisir le nom de l'espace de travail. La plupart des caractères et des symboles peuvent être utilisés.
workspaces-toolbar-button = Espaces de travail
    .label = Espaces de travail
    .tooltiptext = Sélectionner un espace de travail…

## Preferences

enable-workspaces = 
    .label = Activer les espaces de travail
    .tooltiptext = Activer les espaces de travail
workspace-notice = Les espaces de travail ne fonctionneront pas si ce paramètre est activé, à moins que le bouton de l'espace de travail ne soit placé dans la barre d'outils. Utilisez ce paramètre si vous souhaitez désactiver complètement les espaces de travail.
enable-workspaces-with-experimental = 
    .label = Activer les espaces de travail (expérimental)
    .tooltiptext = Activer les espaces de travail (expérimental)
workspace-warning = Les espaces de travail ne peuvent pas être utilisés avec des extensions de groupes d'onglets. Si vous souhaitez utiliser ces extensions, veuillez désactiver les groupes de travail et redémarrer { -brand-short-name }.
category-workspaces = 
    .label = Espaces de travail
    .tooltiptext = Espaces de travail
pane-workspaces-title = Espaces de travail
floorp-workspaces-title = Espaces de travail { -brand-short-name }
floorp-workspace-settings-button = Paramètres de l'espace de travail…
floorp-preferences-label = Paramètres
floorp-extensions-label = Extensions
floorp-private-label = Privé
change-to-close-workspace-popup-option = 
    .label = Fermer la fenêtre contextuelle des espaces de travail lors de la sélection d'un espace de travail
manage-workspace-on-bms-option = 
    .label = Gérer l'espace de travail dans la barre latérale du navigateur
show-workspace-name-option = 
    .label = Afficher le nom de l'espace de travail dans la barre d'onglets
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Mode de partage
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Connectez-vous à votre compte Firefox
welcome-to-floorp = Bienvenue sur { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } est un navigateur flexible et très complet qui prend en charge différents environnements et qui est basé sur Firefox.
welcome-start-setup = Prêt à plonger ?
welcome-skip-to-start-browsing = Passer à la navigation
welcome-select-preferences-template = Choisir un modèle
welcome-minimum-template = Basique
welcome-enable-basic-features = Activez les fonctions et les paramètres de base pour une expérience simple.
welcome-medium-template = Par défaut
welcome-enable-some-features = Activer des fonctionnalités et des paramètres supplémentaires pour une meilleure expérience.
welcome-maximum-template = Avancé
welcome-enable-most-of-features = Activer les fonctionnalités et paramètres avancés. Recommandé pour les utilisateurs expérimentés.
welcome-go-next-setup = Suivant
welcome-select-browser-design = Sélectionner une apparence pour le navigateur
welcome-describe-browser-design = Vous pouvez choisir l'un des merveilleux thèmes tiers sur { -brand-short-name }. Des thèmes spécifiques au système d'exploitation sont également disponibles dans les préférences.
welcome-design-lepton-name = Design original Lepton
welcome-design-photon-name = Design Photon Lepton
welcome-design-ProtonFix-name = Design ProtonFix Lepton
welcome-design-floorp-fluerial-name = Fluerial Design de { -brand-short-name }
welcome-design-firefox-proton-name = Design Firefox Proton
welcome-import-data = Importer les données de votre navigateur
welcome-import-data-description = Configuration rapide ! Importez vos marque-pages, mots de passe et plus encore depuis votre ancien navigateur. Les utilisateurs de Firefox peuvent importer des données depuis Firefox Sync.
welcome-import-data-button = Importer les données…
welcome-import-data-skip = Ignorer l'importation
welcome-select-button = Sélectionner
welcome-finish-setup = Configuration terminée !
welcome-finish-setup-description = Vous êtes prêt ! D'autres fonctionnalités comme les onglets verticaux et les espaces de travail peuvent être trouvées dans les paramètres de { -brand-short-name }. Nous vous souhaitons une bonne navigation sur { -brand-short-name } !
welcomet-finish-setup = Commencer à naviguer sur internet
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Raccourcis clavier
    .tooltiptext = Raccourcis clavier
category-CSK-title = Raccourcis clavier
shortcutkey-customize = 
    .title = Raccourcis clavier
select-shortcutkeyAction = Sélectionnez une action à déclencher
shortcutkey-customize-key-list-placeholder = Votre raccourci clavier apparaîtra ici
shortcut-key-label = Raccourcis clavier
start-input-button-listen = Commencer l'assignation
end-input-button-listen = Arrêter l'assignation
shortcut-key-description = Cliquez sur "Commencer l'assignation" et saisissez votre nouveau raccourci clavier pour cette action. Plusieurs touches peuvent être utilisées ; cependant, les raccourcis clavier ne fonctionneront pas s'ils sont déjà affectés à d'autres actions.
floorp-custom-actions-open-new-tab = Ouvrir un nouvel onglet
    .label = Ouvrir un nouvel onglet
floorp-custom-actions-close-tab = Fermer l'onglet actuel
    .label = Fermer l'onglet actuel
floorp-custom-actions-open-new-window = Ouvrir une nouvelle fenêtre
    .label = Ouvrir une nouvelle fenêtre
floorp-custom-actions-open-new-private-window = Ouvrir une nouvelle fenêtre privée
    .label = Ouvrir une nouvelle fenêtre privée
floorp-custom-actions-close-window = Fermer la fenêtre actuelle
    .label = Fermer la fenêtre actuelle
floorp-custom-actions-restore-last-session = Restaurer la dernière session
    .label = Restaurer la dernière session
floorp-custom-actions-restore-last-window = Restaurer la dernière fenêtre
    .label = Restaurer la dernière fenêtre
floorp-custom-actions-show-next-tab = Afficher l'onglet suivant
    .label = Afficher l'onglet suivant
floorp-custom-actions-show-previous-tab = Afficher l'onglet précédent
    .label = Afficher l'onglet précédent
floorp-custom-actions-show-all-tabs-panel = Afficher tous les onglets
    .label = Afficher la liste des onglets
floorp-custom-actions-send-with-mail = Envoyer par mail
    .label = Envoyer par e-mail
floorp-custom-actions-save-page = Enregistrer la page
    .label = Enregistrer la page
floorp-custom-actions-print-page = Imprimer la page
    .label = Imprimer la page
floorp-custom-actions-mute-current-tab = Activer/désactiver le son de l'onglet actuel
    .label = Activer/désactiver le son de l'onglet actuel
floorp-custom-actions-toggle-bookmark-toolbar = Afficher la barre d'outils des marque-pages
    .label = Activer/désactiver la barre des marque-pages
floorp-custom-actions-show-source-of-page = Afficher la source de la page
    .label = Ouvrir la source de la page
floorp-custom-actions-show-page-info = Afficher les informations sur la page
    .label = Ouvrir les informations de la page
floorp-custom-actions-zoom-in = Zoom avant
    .label = Zoom avant
floorp-custom-actions-zoom-out = Zoom arrière
    .label = Zoom arrière
floorp-custom-actions-reset-zoom = Réinitialiser le zoom
    .label = Réinitialiser le zoom
floorp-custom-actions-back = Précédent
    .label = Précédent
floorp-custom-actions-forward = Suivant
    .label = Suivant
floorp-custom-actions-reload = Actualiser
    .label = Actualiser
floorp-custom-actions-stop = Arrêter
    .label = Arrêter
floorp-custom-actions-force-reload = Forcer le rechargement
    .label = Forcer le rechargement
floorp-custom-actions-search-in-this-page = Rechercher dans cette page
    .label = Rechercher dans la page
floorp-custom-actions-show-next-search-result = Afficher le mot recherché suivant dans le résultat de cette page
    .label = Résultat suivant "Rechercher dans la page"
floorp-custom-actions-show-previous-search-result = Afficher le mot de recherche précédent dans le résultat de cette page
    .label = Résultat de la recherche précédente dans la page
floorp-custom-actions-search-the-web = Rechercher sur internet
    .label = Rechercher sur internet
floorp-custom-actions-open-migration-wizard = Ouvrir l'assistant de migration
    .label = Ouvrir l'assistant de migration
floorp-custom-actions-quit-from-application = Quitter l'application
    .label = Quitter { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Personnaliser les barres d'outils
    .label = Ouvrir la Personnalisation { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Passer en mode hors connexion
    .label = Passer en mode hors connexion
floorp-custom-actions-open-screen-capture = Ouvrir l'outil de capture d'écran
    .label = Prendre une capture d'écran
floorp-custom-actions-show-pip = Affichage Picture-in-Picture
    .label = Affichage Picture-in-Picture
floorp-custom-actions-bookmark-this-page = Mettre cette page en favori
    .label = Mettre cette page en favori
floorp-custom-actions-open-bookmarks-sidebar = Ouvrir la barre latérale des marque-pages
    .label = Ouvrir la barre latérale des marque-pages
floorp-custom-actions-open-bookmark-add-tool = Ouvrir l'outil d'ajout des marque-pages
    .label = Activer le marque-page
floorp-custom-actions-open-bookmark-add-toolbar = Ouvrir la fenêtre contextuelle "Ajouter un nouveau marque-page"
    .label = Ajouter à la barre d'outils des marque-pages
floorp-custom-actions-open-bookmarks-manager = Ouvrir le gestionnaire des marque-pages
    .label = Ouvrir le gestionnaire des marque-pages
floorp-custom-actions-show-bookmark-toolbar = Activer/désactiver la barre d'outils des marque-pages
    .label = Activer/désactiver la barre d'outils des marque-pages
floorp-custom-actions-open-general-preferences = Ouvrir les paramètres généraux
    .label = Ouvrir les paramètres généraux
floorp-custom-actions-open-privacy-preferences = Ouvrir les paramètres de confidentialité
    .label = Ouvrir les paramètres de confidentialité
floorp-custom-actions-open-workspaces-preferences = Ouvrir les paramètre des espaces de travail
    .label = Ouvrir les paramètres des espaces de travail
floorp-custom-actions-open-containers-preferences = Ouvrir les paramètres des conteneurs
    .label = Ouvrir les paramètres des conteneurs
floorp-custom-actions-open-search-preferences = Ouvrir les paramètres de recherche
    .label = Ouvrir les paramètres de recherche
floorp-custom-actions-open-sync-preferences = Ouvrir les paramètres de synchronisation
    .label = Ouvrir les paramètres de synchronisation
floorp-custom-actions-open-task-manager = Ouvrir le gestionnaire des tâches
    .label = Ouvrez le gestionnaire des tâches de { -brand-short-name }
floorp-custom-actions-open-home-page = Ouvrir la page d'accueil de { -brand-short-name }
    .label = Ouvrir la page d'accueil de { -brand-short-name }
floorp-custom-actions-open-addons-manager = Ouvrir les extensions et les thèmes
    .label = Ouvrir les extensions et des thèmes
floorp-custom-actions-forget-history = Oublier l'historique
    .label = Oublier l'historique
floorp-custom-actions-quick-forget-history = Historique d'oubli rapide
    .label = Historique d'oubli rapide
floorp-custom-actions-clear-recent-history = Effacer l'historique récent
    .label = Effacer l'historique récent
floorp-custom-actions-search-history = Historique de la recherche
    .label = Historique de la recherche
floorp-custom-actions-manage-history = Gérer l'historique
    .label = Gérer l'historique
floorp-custom-actions-open-downloads = Ouvrir les téléchargements
    .label = Ouvrir les téléchargements
floorp-custom-actions-show-bms = Afficher la barre latérale de gestion du navigateur
    .label = Afficher la barre latérale de gestion du navigateur
floorp-custom-actions-show-current-panel = Basculer le panneau actuel
    .label = Basculer le panneau actuel
floorp-custom-actions-show-bookmark-sidebar = Afficher la barre latérale des marque-pages
    .label = Afficher la barre latérale des marque-pages
floorp-custom-actions-show-history-sidebar = Afficher la barre latérale de l'historique
    .label = Afficher la barre latérale de l'historique
floorp-custom-actions-show-synced-tabs-sidebar = Afficher la barre latérale des onglets synchronisés
    .label = Afficher la barre latérale des onglets synchronisés
floorp-custom-actions-reverse-sidebar = Inverser la position de la barre latérale
    .label = Inverser la position de la barre latérale
floorp-custom-actions-hide-sidebar = Masquer la barre latérale
    .label = Masquer la barre latérale
floorp-custom-actions-show-sidebar = Activer/désactiver la barre latérale
    .label = Activer/désactiver la barre latérale
floorp-custom-actions-toggle-sidebar = Activer/désactiver la barre latérale
    .label = Activer/désactiver la barre latérale
floorp-custom-actions-open-previous-workspace = Ouvrir le précédent espace de travail
    .label = Ouvrir le précédent espace de travail
floorp-custom-actions-open-next-workspace = Ouvrir le prochain espace de travail
    .label = Ouvrir le prochain espace de travail
floorp-custom-actions-show-panel-1 = Activer/désactiver le panneau 1
    .label = Activer/désactiver le panneau 1
floorp-custom-actions-show-panel-2 = Activer/désactiver le panneau 2
    .label = Activer/désactiver le panneau 2
floorp-custom-actions-show-panel-3 = Activer/désactiver le panneau 3
    .label = Activer/désactiver le panneau 3
floorp-custom-actions-show-panel-4 = Activer/désactiver le panneau 4
    .label = Activer/désactiver le panneau 4
floorp-custom-actions-show-panel-5 = Activer/désactiver le panneau 5
    .label = Activer/désactiver le panneau 5
floorp-custom-actions-show-panel-6 = Activer/désactiver le panneau 6
    .label = Activer/désactiver le panneau 6
floorp-custom-actions-show-panel-7 = Activer/désactiver le panneau 7
    .label = Activer/désactiver le panneau 7
floorp-custom-actions-show-panel-8 = Activer/désactiver le panneau 8
    .label = Activer/désactiver le panneau 8
floorp-custom-actions-show-panel-9 = Activer/désactiver le panneau 9
    .label = Activer/désactiver le panneau 9
floorp-custom-actions-show-panel-10 = Activer/désactiver le panneau 10
    .label = Activer/désactiver le panneau 10
floorp-custom-actions-open-split-view-on-left = Ouvrir l'onglet actuel à gauche en vue fractionnée
    .label = Ouvrir l'onglet actuel à gauche en vue fractionnée
floorp-custom-actions-open-split-view-on-right = Ouvrir l'onglet actuel à droite en vue fractionnée
    .label = Ouvrir l'onglet actuel à droite en vue fractionnée
floorp-custom-actions-close-split-view = Fermer la vue fractionnée
    .label = Fermer la vue fractionnée
floorp-custom-actions-custom-action-1 = Action personnalisée 1
    .label = Action personnalisée 1
floorp-custom-actions-custom-action-2 = Action personnalisée 2
    .label = Action personnalisée 2
floorp-custom-actions-custom-action-3 = Action personnalisée 3
    .label = Action personnalisée 3
floorp-custom-actions-custom-action-4 = Action personnalisée 4
    .label = Action personnalisée 4
floorp-custom-actions-custom-action-5 = Action personnalisée 5
    .label = Action personnalisée 5
floorp-custom-actions-rest-mode = Activer le mode repos
    .label = Activer le mode repos
floorp-custom-actions-hide-user-interface = Basculer l'interface utilisateur
    .label = Basculer l'interface utilisateur
floorp-custom-actions-toggle-navigation-panel = Activer/désactiver le panneau de navigation
    .label = Activer/désactiver le panneau de navigation
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Démarrer
    .tooltiptext = Lancer { -brand-short-name } avec ce profil
floorp-profiles-in-use = Ce profil est en cours d'utilisation.
floorp-profiles-title = Profiles
floorp-profile-manager = Gestionnaire de profil
floorp-profiles-create = Créer un profil
floorp-profile = Profil
    .label = Gestionnaire de profil
    .tooltiptext = Ouvrir le gestionnaire de profil
fxa-not-signed-in = Pas connecté
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privé
floorp-toggle-private-container = 
    .label = Réouvrir en privé/sans conteneur
    .accesskey = P
open-in_private-container = 
    .label = Ouvrir dans un nouvel onglet avec un conteneur privé
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = Ouvrir en vue fractionnée
splitview-show-on-right = 
    .label = Afficher à gauche
splitview-show-on-left = 
    .label = Afficher à droite
splitview-close-split-tab = 
    .label = Fermer l'onglet fractionné
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Scannez le QR Code avec votre téléphone
qrcode-generate-page-action = 
    .tooltiptext = Partagez cette page avec votre téléphone
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Bouton des extensions unifiées
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Installer l'application
    .tooltiptext = Installer ce site en tant qu'application
ssb-page-action-title = Installer l'application
ssb-app-open-button = 
    .label = Ouvrir dans l'application
ssb-app-install-button = 
    .label = Installer
ssb-app-cancel-button = 
    .label = Annuler
floorp-open-manage-ssb-page = 
    .label = Gérer les applications web installées
appmenuitem-webapps = 
    .label = Applications web
appmenu-open-installed-apps-subheader = Ouvrir les applications web installées
appmenuitem-install-current-page = 
    .label = Installer ce site en tant qu'application
appmenuitem-open-current-page = 
    .label = Ouvrir ce site dans l'application installée
appmenuitem-contextmenu-open-app = 
    .label = Ouvrir cette application
appmenuitem-contextmenu-uninstall-app = 
    .label = Désinstaller cette application

## Preferences

category-ssb = 
    .label = Applications web
    .tooltiptext = Applications web
category-ssb-title = Applications web
floorp-ssb-title = Applications web
floorp-ssb-description = Les applications web sont des sites internet qui peuvent être installés en tant qu'applications. Elles peuvent être lancées à partir du menu de { -brand-short-name } ou du menu Démarrer de Windows.
ssb-preferences = Paramètres des applications web
floorp-enable-ssb = 
    .label = Activer les applications web
floorp-enable-ssb-with-experimental = 
    .label = Activer les applications web (expérimental)
floorp-enable-ssb-description = Cette fonctionnalité est expérimentale sur Mac et Linux. Il est recommandé d'activer cette fonctionnalité sous Windows.
floorp-disable-toolbars = 
    .label = Désactiver les barres d'outils dans la fenêtre des applications web
floorp-disable-toolbars-description = Ce paramètre masque toutes les extensions et les barres d'outils dans la fenêtre des applications web.
ssb-installed-list-title = Applications web installées
ssb-uninstall-title = Désinstaller l'application web
ssb-uninstall-message = Êtes-vous sûr de vouloir désinstaller cette application web de { -brand-short-name } ?
ssb-uninstall-button = 
    .label = Désinstaller
ssb-uninstall-cancel = Annuler
######################################################################### Download Notification ###############################################################
floorp-started-download = Téléchargement démarré
floorp-finished-download = Téléchargement terminé
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } est à jour !
floorp-notificationContent-latest = { -brand-short-name } est à jour. Vous utilisez la dernière version de { -brand-short-name }.
floorp-notificationTitle = Une nouvelle version de { -brand-short-name } est disponible!
floorp-notificationContent = Cliquer pour télécharger la dernière version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Fermer les onglets jusqu'au début
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Fermer les onglets jusqu'à la fin
    .accesskey = E
