# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> jest przeglądarką opracowaną w Japonii. Opiera się ona na Firefox i nadal działa w ramach <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, aby ulepszyć internet. Chcesz pomóc? <label data-l10n-name="helpus-donateLink">Dokonaj darowizny</label>
icon-creator = Twórca ikon <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> i <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Lista współtwórców <label data-l10n-name="about-contributor">i programistów</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Wygląd
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Do zastosowania zmian wymagany jest restart
tab-width = Minimalna szerokość kart
preferences-tabs-newtab-position = Pozycja nowej karty
open-new-tab-use-default = 
    .label = Otwórz nowe karty w domyślnej pozycji
open-new-tab-at-the-end = 
    .label = Otwórz nowe karty na końcu paska kart
open-new-tab-next-to-current = 
    .label = Otwórz nowe karty obok bieżącej karty
multirow-tabs-limit = 
    .label = Włącz limit wierszy dla kart wielowierszowych
multirow-tabs-newtab = 
    .label = Umieść przycisk "Otwórz nową kartę" na końcu najniższego wiersza kart
multirow-tabs-value = Liczba wierszy, gdy karty z wieloma wierszami są włączone
enable-tab-sleep = 
    .label = Włącz śpiące karty
tab-sleep-timeout-minutes-value = Karty będą uśpione po nieaktywności od (minut)
tab-sleep-settings-button = Ustawienia...
tab-sleep-settings-dialog-title = 
    .title = Ustawienia śpiących kart
tab-sleep-settings-dialog-excludehosts-label = Wyklucz hosty
tab-sleep-settings-dialog-excludehosts-label-2 = Wprowadź jeden host na linię.
tab-sleep-tab-context-menu-excludetab = Nie zasypiaj karty
enable-tab-scroll-change = 
    .label = Przełącz karty przez przewijanie za pomocą myszy
enable-tab-scroll-reverse = 
    .label = Odwróć kierunek przewijania kart
enable-tab-scroll-wrap = 
    .label = Zawijaj przewijane karty na krawędzi
enable-double-click-block = 
    .label = Zamknij karty podwójnym kliknięciem
enable-show-pinned-tabs-title = 
    .label = Pokaż tytuł przypiętych kart
tabbar-preference = Pasek kart
tab-normal-mode = 
    .label = Domyślny
hide-horizontality-tabs = 
    .label = Ukryj karty na poziomym pasku kart
verticalTab-setting = 
    .label = Optymalizuj przeglądarkę dla pionowego paska kart
move-tabbar-position = 
    .label = Wyświetl pasek kart pod paskiem narzędzi
tabbar-on-bottom = 
    .label = Wyświetl pasek kart u dołu okna
tabbar-favicon-color = 
    .label = Koloruj pasek kart używając koloru ikony obecnej strony
tabbar-style-preference = Styl paska kart
horizontal-tabbar = 
    .label = Poziomy pasek kart
tabbar-style-description = Aby w pełni zastosować to ustawienie, wymagany jest restart { -brand-short-name }.
multirow-tabbar = 
    .label = Wielowierszowy pasek kart
vertical-tabbar = 
    .label = Pionowy pasek kart (eksperymentalny)
native-vertical-tab-show-right = 
    .label = Pokaż pionowy pasek kart po prawej stronie okna
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = Zwiń pionowy pasek kart
floorp-show-vertical-tab-newtab-button = 
    .label = Pokaż przycisk "Otwórz nową kartę" na pasku kart pionowych
floorp-show-vertical-tab-scrollbar = 
    .label = Pokaż pasek przewijania na pasku kart pionowych
TST = Karta stylu drzewa
about-TST = Tree Style Tab to popularne rozszerzenie umożliwiające wyświetlanie kart w strukturze drzewa. Rozszerzenie te jest już wstępnie zintegrowane z { -brand-short-name }. Zainstaluj rozszerzenie, aby aktywować Tree Style Tab { -brand-short-name }a.
treestyletab-Settings = 
    .label = Zwiń kartę stylu drzewa
sidebar-reverse-position-toolbar = Pokaż paski boczne po drugiej stronie
bookmarks-bar-settings = Pasek zakładek (tylko jedna opcja może być użyta jednocześnie)
bookmarks-focus-mode = 
    .label = Ukryj pasek zakładek bez najechania na pasek nawigacyjny
bookmarks-bottom-mode = 
    .label = Pokaż pasek zakładek u dołu { -brand-short-name }
navbar-settings = Pasek nawigacji
show-nav-bar-bottom = 
    .label = Pokaż pasek nawigacji u dołu { -brand-short-name } (eksperymentalne)
material-effect = 
    .label = Allow Mica For Everyone to modify the browser design (Deprecated)
disable-extension-check-compatibility-option = 
    .label = Do not check for compatibility with add-ons (deprecated)
other-preference = Inne preferencje
enable-userscript = 
    .label = Enable legacy components (deprecated)
about-userscript = Włączenie tej funkcji może spowodować nieoczekiwane błędy lub błędy krytyczne.
search-positon-top = 
    .label = Wyświetlanie paska wyszukiwania w górnej części strony
allow-auto-restart = 
    .label = Uruchom ponownie automatycznie, gdy ustawienia, które wymagają restartu zostaną zmienione
disable-fullscreen-notification = 
    .label = Nie pokazuj powiadomienia podczas wchodzenia na pełny ekran

## Browser Theme

system-color-settings = Niektóre szablony mają zarówno jasne, jak i ciemne tryby - wybierz tryb, w którym chcesz użyć tych motywów.
preferences-theme-appearance-header = Tryb motywu
system-theme-dark = 
    .label = Ciemny
system-theme-light = 
    .label = Jasny
system-theme-auto = 
    .label = Śledź ustawienia systemu

## User interface preferences

ui-preference = Wygląd przeglądarki
preferences-browser-appearance-description = Wybierz wbudowany projekt zewnętrznej firmy do użycia w { -brand-short-name }. Niektóre projekty mogą nie być kompatybilne z konfiguracją.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (przestarzały)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (przestarzały)
floorp-gnomeUI = 
    .label = Motyw GNOME (przestarzały)

## Download Manager

download-notification-preferences = Pobierz powiadomienia
start-always-notify = 
    .label = Powiadom tylko podczas uruchamiania pobierania
finish-always-notify = 
    .label = Powiadom tylko wtedy, gdy pobieranie zakończy się
always-notify = 
    .label = Powiadom o rozpoczęciu pobierania i zakończeniu pobierania
do-not-notify = 
    .label = Wyłącz powiadomienia o pobieraniu

## Sidebar

profiles-button-label = Zarządzaj profilami
floorp-help-button-label = Wsparcie { -brand-short-name }
appmenuitem-reboot = 
    .label = Uruchom ponownie

## UserAgent

userAgent-preference = User Agent (deprecated)
default-useragent-mode = 
    .label = Użyj Firefox User Agent (domyślnie)
windows-chrome-useragent-mode = 
    .label = User Agent Chrome w systemie Windows
macOS-chrome-useragent-mode = 
    .label = User Agent Chrome na macOS
linux-chrome-useragent-mode = 
    .label = User Agent Chrome na Linuxie
mobile-chrome-useragent-mode = 
    .label = User Agent Chrome na iOS
use-custom-useragent-mode = 
    .label = Użyj niestandardowego user agenta użytkownika

## DMR UI

download-mgr-UI = 
    .label = Włącz menedżera pobierania SimpleUI
downloading-red-color = 
    .label = Użyj czerwonej ikony pobierania podczas pobierania
sidebar-preferences = Sidebar
bsb-preferences = Ustawienia paska bocznego przeglądarki
view-sidebar2-right = 
    .label = Wyświetl pasek boczny menedżera przeglądarki po prawej
enable-sidebar2 = 
    .label = Włącz pasek boczny menedżera przeglądarki
visible-bms = 
    .label = Pokaż pasek boczny menedżera przeglądarki
hide-bms-to-unload-panel = 
    .label = Wyładuj panel podczas ukrywania panelu
enable-addons-in-sidebar2-with-experimental = 
    .label = Włącz skrypty rozszerzeń w pasku bocznym przeglądarki (eksperymentalne)
enable-addons-in-sidebar2 = 
    .label = Włącz skrypty rozszerzeń w pasku bocznym przeglądarki
sidebar2-enable-addons-desc = Jeśli to ustawienie jest włączone, blokery reklam i inne rozszerzenia będą działać w pasku bocznym. Nie wszystkie rozszerzenia będą działać.
custom-URL-option = Ustaw adresy URL panelu sieci Web
set-custom-URL-button = 
    .label = Ustaw niestandardowe URL...
    .accesskey = Pr
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Pasek boczny menedżera przeglądarek
bsb-context = Użyj następującego kontenera
bsb-userAgent-label = 
    .label = Użyj mobilnego Agenta w tym Panelu Web
bsb-width = Szerokość (jeśli jest ustawiona na 0, zostanie użyta wartość globalna)
bsb-page = Strona do otwarcia
bsb-add = Dodaj panel internetowy na pasku bocznym przeglądarki
bsb-setting = Ustawienia panelu www
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Strona internetowa
sidebar2-pref-delete = 
    .label = Usuń
sidebar2-pref-setting = 
    .label = Ustawienia
sidebar2-global-width = Szerokość globalnych Paneli Web
use-icon-provider-option = Wybierz dostawcę ikon
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (dostępny w Chinach)
use-icon-provider-option-hatena = 
    .label = Hatena (dostępna w Chinach)
memory-and-performance = Pamięć i wydajność
min-memory = 
    .label = Minimalne zużycie pamięci (niska wydajność)
balance-memory = 
    .label = Użycie i wydajność pamięci bilansowej
max-memory = 
    .label = Najlepsza wydajność (wysokie zużycie pamięci)
delete-border-and-roundup-option = 
    .label = Zaokrąglij narożniki stron

## DualTheme

dualtheme-enable = 
    .label = Włącz podwójny motyw
newtab-background = Tło domowe { -brand-short-name }
newtab-background-random-image = 
    .label = Losowe obrazy z Unsplash
newtab-background-gradation = 
    .label = Gradient
newtab-background-not-background = 
    .label = Wyłącz tło
newtab-background-selected-image = 
    .label = Folder niestandardowy...
newtab-background-selected-one-image = 
    .label = Własny obraz...
newtab-background-folder = Użyj obrazów z tego folderu:
newtab-background-image = Użyj obrazu:
newtab-choose-image = Wybierz obraz...
newtab-background-folder-reload = 
    .label = Reload images
newtab-background-folder-default = 
    .label = Przywróć domyślne
newtab-background-folder-open = 
    .label = Otwórz folder
newtab-background-folder-choose = Wybierz folder obrazów...
newtab-background-image-choose = Wybierz obraz...
newtab-background-extensions = Użyj obrazów z tymi rozszerzeniami plików (oddzielone przez ",")
disable-blur-on-newtab = 
    .label = Wyłącz efekt rozmycia na stronie startowej { -brand-short-name }
disable-releasenote-on-newtab = 
    .label = Ukryj informacje o wydaniu i linki wsparcia na stronie startowej { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Ukryj kredytowanie zdjęć (Unsplash) na stronie startowej { -brand-short-name }

## Lepton Preferences

about-lepton = Dostosuj { -brand-short-name } z Lepton
lepton-preference-button = 
    .label = Ustawienia Leptona...
    .accesskey = L
lepton-header = Ustawienia Leptona
lepton-preference = Ustawienia Leptona
photon-mode = 
    .label = Użyj wyglądu Photon
lepton-mode = 
    .label = Użyj wyglądu Lepton
protonfix-mode = 
    .label = Użyj ulepszonego interfejsu Proton
autohide-preference = Automatycznie ukryj elementy przeglądarki
floorp-lepton-enable-tab-autohide = 
    .label = Automatycznie ukryj karty
floorp-lepton-enable-navbar-autohide = 
    .label = Automatycznie ukryj pasek narzędzi
floorp-lepton-enable-sidebar-autohide = 
    .label = Automatycznie ukryj pasek boczny
floorp-lepton-enable-urlbar-autohide = 
    .label = Automatycznie ukryj pasek adresu
floorp-lepton-enable-back-button-autohide = 
    .label = Automatycznie ukryj przycisk wstecz
floorp-lepton-enable-forward-button-autohide = 
    .label = Automatycznie ukryj przycisk do przodu
floorp-lepton-enable-page-action-button-autohide = 
    .label = Automatycznie ukryj przyciski na pasku adresu
floorp-lepton-enable-toolbar-overlap = 
    .label = Pokaż pasek narzędzi nad zawartością witryny
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Automatycznie ukryj pasek narzędzi podczas wyświetlania treści "ltr"
hide-preference = Zarządzaj elementami przeglądarki
floorp-lepton-enable-tab_icon-hide = 
    .label = Ukryj ikony kart
floorp-lepton-enable-tabbar-hide = 
    .label = Ukryj pasek kart
floorp-lepton-enable-navbar-hide = 
    .label = Ukryj pasek narzędzi
floorp-lepton-enable-sidebar_header-hide = 
    .label = Ukryj nagłówki paska bocznego
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Ukryj ikony paska adresu
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Ukryj ikony paska zakładek
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Ukryj etykiety paska zakładek
floorp-lepton-enable-disabled_menu-hide = 
    .label = Ukryj wyłączone pozycje menu kontekstowego
floorp-lepton-disable-userChrome-icon = 
    .label = Wyłącz menu kontekstowe i ikony menu Lepton
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Włącz ikony menu kontekstowego Lepton
positon-preferences = Korekty pozycji
floorp-lepton-enable-centered-tab = 
    .label = Wyśrodkuj etykiety w kartach
floorp-lepton-enable-centered-urlbar = 
    .label = Wyśrodkuj tekst na pasku adresu
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Wyśrodkuj pasek zakładek
urlbar-preferences = Pasek adresu
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Przenieś ikony paska adresu z lewej strony
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Podczas wpisywania, pokaż przycisk "Przejdź"
floorp-lepton-enable-always-show-page_action = 
    .label = Zawsze pokazuj akcje strony na pasku adresu
tabbar-preferences = Pasek kart
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Pasek kart na pasku tytułu
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Połącz pasek kart i pasek narzędzi
lepton-sidebar-preferences = Pasek boczny
floorp-lepton-enable-overlap-sidebar = 
    .label = Pokaż pasek boczny nad zawartością witryny
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Strona główna (domyślnie)
floorp-home-prefs-content-header = { -brand-short-name } Zawartość Domu
floorp-home-prefs-content-description = Wybierz treść, którą chcesz zobaczyć na stronie głównej { -brand-short-name }.

## Notes

floorp-notes = Notatki { -brand-short-name }
restore-from-backup = Przywróć notatki z kopii zapasowej
enable-notes-sync = 
    .label = Włącz synchronizację notatek { -brand-short-name }
about-notes-backup-tips = Notatki { -brand-short-name } wykorzystują Firefox Sync do synchronizowania notatek z innymi urządzeniami. W przypadku utraty notatek można je przywrócić z kopii zapasowej. Kopia zapasowa tworzona jest po uruchomieniu { -brand-short-name }.
notes-sync-description = To może rozwiązać problem utraty treści z powodu nadpisywania notatek podczas synchronizacji.
backuped-time = Kopia zapasowa
notes-backup-option = Ustawienia kopii zapasowej
backup-option-button = Ustawienia kopii zapasowej...
restore-from-backup-prompt-title = { -brand-short-name } Usługa przywracania notatek
restore-from-this-backup = Przywrócić notatki do stanu, w którym były w tej kopii zapasowej?
restore-button = Przywróć

## user.js

header-userjs = user.js
userjs-customize = Dostosuj { -brand-short-name } za pomocą user.js
about-userjs-customize = user.js to plik konfiguracyjny, który pozwala na dostosowanie { -brand-short-name }. Pliki user.js są pobierane z Internetu i nadpisywane przez bieżącego użytkownika. s plik. Przed kontynuowaniem utwórz kopię zapasową bieżącego pliku user.js. Konfiguracje użytkownika zostaną zastosowane automatycznie po ponownym uruchomieniu { -brand-short-name }.
userjs-label = Lista użytkowników.js
userjs-prompt = Zastosuj tego użytkownika.j?
apply-userjs-attention = Zastosowanie nowego user.js nadpisze bieżący plik user.js.
apply-userjs-attention2 = Zanim przejdziesz dalej, wykonaj kopię zapasową bieżącego pliku user.js.
userjs-button = Ustawienia użytkownika...
userjs-select-option = Zarządzaj użytkownikiem używanym obecnie w { -brand-short-name } w celu poprawy wydajności i prywatności.
apply-userjs-button = Zastosuj

## userjs Options

default-userjs-label = { -brand-short-name } Domyślne
about-default-userjs = Telemetria wyłączona. Dobrze zbalansowany { -brand-short-name } z włączonymi różnymi dostosowaniami.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS-by-Default. Całkowita ochrona plików cookie z izolacją witryny. Zwiększony podział stanu i sieci. Różne inne ulepszenia.
default-label = Yokoffing Default
about-default = Wszystkie niezbędne elementy. Żadnych uszkodzeń. To jest twój user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Zwiększenie wydajności Floorpa!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Uporządkuj stronę nowej karty. Usuń Pocket. Przywróć tryb kompaktowy jako opcję. Zatrzymaj powiadomienia ze stron internetowych, wyskakujące okienka i inne irytującyce elementy.
Smoothfox-label = Yokoffing Smoothfx
about-Smoothfox = Uzyskaj płynne przewijanie Edge-like w swojej ulubionej przeglądarce — lub wybierz coś innego.
select-workspace = Wybierz obszar roboczy
workspace-select-icon = Wybierz ikonę obszaru roboczego
    .label = Wybierz ikonę obszaru roboczego
workspace-select-container = Wybierz kontener kart
    .label = Wybierz kontener kart
workspace-customize = 
    .title = Dostosuj obszar roboczy
floorp-no-workspace-container = 
    .label = No Container
workspace-icon-article = 
    .label = Artykuł
workspace-icon-book = 
    .label = Książka
workspace-icon-briefcase = 
    .label = Praca
workspace-icon-cart = 
    .label = Zakupy
workspace-icon-chat = 
    .label = Czat
workspace-icon-chill = 
    .label = Prywatne
workspace-icon-circle = 
    .label = Okrąg
workspace-icon-compass = 
    .label = Kompas
workspace-icon-code = 
    .label = Programowanie
workspace-icon-dollar = 
    .label = Bankowość
workspace-icon-fence = 
    .label = Ogrodzenie
workspace-icon-fingerprint = 
    .label = Osobiste
workspace-icon-food = 
    .label = Żywność
workspace-icon-fruit = 
    .label = Owoce
workspace-icon-game = 
    .label = Gra
workspace-icon-gear = 
    .label = Narzędzia połowowe
workspace-icon-gift = 
    .label = Prezent
workspace-icon-key = 
    .label = Klucz
workspace-icon-lightning = 
    .label = Piorun
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notatki
workspace-icon-paint = 
    .label = Malowanie
workspace-icon-photo = 
    .label = Zdjęcie
workspace-icon-pin = 
    .label = Pinezka
workspace-icon-pet = 
    .label = Zwierzę domowe
workspace-icon-question = 
    .label = Pytanie
workspace-icon-smartphone = 
    .label = Smartfon
workspace-icon-star = 
    .label = Gwiazdka
workspace-icon-tree = 
    .label = Drzewo
workspace-icon-vacation = 
    .label = Wakacje
workspace-icon-love = 
    .label = Miłość
workspace-icon-moon = 
    .label = Księżyc
workspace-icon-music = 
    .label = Muzyka
workspace-icon-user = 
    .label = Użytkownik
# Custom Keyboard Shortcuts
floorp-CSK-title = Niestandardowe skróty klawiszowe
floorp-CSK-description = Dostosuj skróty klawiszowe przeglądarki { -brand-short-name }. { -brand-short-name } pozwala ci ustawić ponad 80 własnych skrótów klawiszowych! Zduplikowane skróty klawiszowe nie będą działać. Uruchom ponownie { -brand-short-name }, aby zastosować te ustawienia.
disable-fx-actions = 
    .label = Wyłącz skróty klawiszowe Mozilla Firefox
customize-Action = 
    .label = Dodaj skrót
remove-Action = 
    .label = Usuń skrót
CSK-reset-title = Resetuj niestandardowe skróty klawiszowe
CSK-reset-description = Zresetuj niestandardowe skróty klawiszowe do domyślnych ustawień { -brand-short-name }.
CSK-reset-label = Resetuj niestandardowe skróty klawiszowe
CSK-reset-button = Przywróć domyślne
CSK-manage-title = Zarządzaj skrótami klawiszowymi
CSK-remove-shortcutkey = Usunąć niestandardowy skrót klawiatury?
CSK-remove-shortcutkey-description = Czy na pewno chcesz usunąć ten skrót klawiaturowy?
CSK-restore-default = Przywrócić domyślne?
CSK-restore-default-description = Przywrócić domyślne skróty klawiaturowe { -brand-short-name }? Bieżące skróty zostaną utracone.
CSK-reboot-browser-label = Uruchom ponownie { -brand-short-name } aby zastosować te ustawienia
CSK-reboot-browser-button = Uruchom ponownie { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Bieżący skrót klawiatury: { $key } i { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Bieżący skrót klawiatury: { $key }.
CSK-keyborad-shortcut-is-changed = (Nie stosowane)
floorp-custom-actions-tab-action = Akcje karty
floorp-custom-actions-page-action = Akcje strony
floorp-custom-actions-visible-action = Widoczne akcje
floorp-custom-actions-search-action = Szukaj akcji
floorp-custom-actions-tools-action = Akcje narzędzi
floorp-custom-actions-bookmark-action = Akcje zakładek
floorp-custom-actions-open-page-action = Otwórz akcje strony
floorp-custom-actions-history-action = Historia akcji
floorp-custom-actions-pip-action = Akcje obrazu w zdjęciu
floorp-custom-actions-downloads-action = Akcje pobierania
floorp-custom-actions-sidebar-action = Akcje paska bocznego
floorp-custom-actions-bms-action = Akcje panelu bocznego przeglądarki
floorp-custom-actions-split-view-action = Akcje dzielenia widoku
floorp-custom-actions-workspaces-action = Akcje przestrzeni roboczych
floorp-custom-actions-custom-action = Akcje niestandardowe (eksperymentalne)

## Mouse Gestures

mouse-gesture = Gesty myszy
mouse-gesture-description = Gesturefy musi być zainstalowane, aby używać gestów myszy z { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy to rozszerzenie, które dodaje gesty myszy do przeglądarki. Jeśli { -brand-short-name } wykryje instalację tego rozszerzenia, doda do Gesturefy polecenia gestów, które są dostępne tylko w { -brand-short-name }. Rozszerzenie te działa również w nowej karcie!
# Translate
TWS = Przetłumacz strone internetową
about-TWS = Przetłumacz swoją stronę w czasie rzeczywistym za pomocą Google lub Yandex. Możesz również przetłumaczyć wybrany tekst lub całą stronę.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Centrum Prywatności
block-more-tracker = Zablokuj więcej reklam i trackerów
block-tracker = Ta sekcja zawiera zestaw rozszerzeń przeznaczonych do blokowania reklam i trackerów
view-at-AMO = Zobacz ten dodatek w addons.mozilla.org
uBlock-Origin = Pochodzenie uBlock
about-uboori = uBlock Origin blokuje reklamy, rozległe trackery i dodatkowe niebezpieczne strony.
Facebook-Container = Kontener Facebook
about-Facebook-Container = Zablokuj Facebookowi śledzenie Cię przez Internet. Rozszerzenie kontenera na Facebooku pomaga przejąć kontrolę i izolować swoją aktywność internetową z Facebooka.

## Fingerprinting

fingerprint-header = Odporny druk linii papilarnych i adres IP
block-fingerprint = Odciski palców to mechanizm śledzenia oparty na unikalnych funkcjach przeglądarki i systemu operacyjnego. Ta sekcja zawiera ustawienia, aby dalej zwiększać tę ochronę poza domyślnym blokowaniem.
enable-firefox-fingerprint-protections = Włącz silną ochronę przed pobieraniem odcisków palców
about-firefox-fingerprint-protection = Włączenie ochrony Firefoksa obejmuje tryb wymuszonego oświetlenia, wyłączenie niektórych API itp. Niektóre strony mogą być uszkodzone.
fingerprint-Protection = 
    .label = Zabezpieczenia przed odciskiem palców
html5-canvas-prompt-settings = 
    .label = Automatycznie odrzuć powiadomienia o potwierdzeniu dostępu dla danych obrazu HTML5
canvas-prompt = Zapobiega używaniu okna do czytania płótna przez strony internetowe, chyba że jest to dozwolone ręcznie.
disable-webgl = 
    .label = Wyłącz WebGL
about-webgl = WebGL jest interfejsem API Javascript używanym do renderowania grafiki, który może być używany do identyfikacji GPU.
Canvas-Blocker = Blokowanie płótna
about-CB = Ten dodatek łupi dane wykorzystywane przez techniki pobierania odcisków palców.
WebRTC-connection = WebRTC jest standardem umożliwiającym połączenie w czasie rzeczywistym. Jeśli wyłączysz to ustawienie, nie będziesz mógł korzystać z Discorda itp.
WebRTC = 
    .label = Włącz połączenie WebRTC
################################################################### browser ###############################################################

rest-mode = Trwa przerwa...
rest-mode-description = { -brand-short-name } jest aktualnie uśpiony. Naciśnij ENTER lub OK, aby kontynuować.
Sidebar2 = 
    .label = Pasek boczny menedżera przeglądarek
    .tooltiptext = Zmień widoczność paska bocznego
sidebar2-mute-and-unmute = 
    .label = Wycisz/Wyłącz wyciszenie tego panelu
sidebar2-unload-panel = 
    .label = Rozładuj ten panel
sidebar2-change-ua-panel = 
    .label = Przełącz agenta użytkowników mobilnych
sidebar2-delete-panel = 
    .label = Usuń ten panel
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom In
sidebar2-zoom-out = 
    .label = Zoom Out
sidebar2-reset-zoom = 
    .label = Reset Zoom
sidebar2-close-button = 
    .tooltiptext = Zamknij pasek boczny
sidebar-back-button = 
    .tooltiptext = Powrót
sidebar-forward-button = 
    .tooltiptext = Przekaż
sidebar-reload-button = 
    .tooltiptext = Reload
sidebar-go-index-button = 
    .tooltiptext = Przejdź do strony głównej
sidebar-muteAndUnmute-button = 
    .tooltiptext = Mute/Unmute sidebar
sidebar2-browser-manager-sidebar = Menedżer przeglądarek
show-browser-manager-sidebar = 
    .tooltiptext = Show { sidebar2-browser-manager-sidebar } Sidebar
sidebar2-bookmark-sidebar = Zakładki
show-bookmark-sidebar = 
    .tooltiptext = Pokaż pasek boczny "{ sidebar2-bookmark-sidebar }"
sidebar2-history-sidebar = Historia
show-history-sidebar = 
    .tooltiptext = Show { sidebar2-history-sidebar } Sidebar
sidebar2-download-sidebar = Pobrania
show-download-sidebar = 
    .tooltiptext = Show { sidebar2-download-sidebar } Sidebar
sidebar2-notes-sidebar = Uwagi
show-notes-sidebar = 
    .tooltiptext = Show { sidebar2-notes-sidebar } Sidebar
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Dodatki i motywy
sidebar2-hide-sidebar-button = 
    .tooltiptext = Ukryj pasek boczny przeglądarki
sidebar-passwords-button = 
    .tooltiptext = Hasła
sidebar-preferences-button = 
    .tooltiptext = Ustawienia
sidebar-keepWidth-button = 
    .tooltiptext = Używaj bieżącej szerokości tego panelu
sidebar2-keep-width-for-global = 
    .label = Zastosuj tę szerokość do wszystkich paneli bez niestandardowej szerokości
bsb-context-add = 
    .label = Dodaj stronę do panelu WWW...
bsb-context-link-add = 
    .label = Dodaj link do panelu WWW...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Otwórz katalog profilu
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Przebuduj pliki CSS przeglądarki
    .accesskey = R
make-browsercss-file = 
    .label = Utwórz plik CSS przeglądarki
    .accesskey = Pr
open-css-folder = 
    .label = Otwórz folder CSS
    .accesskey = Pr
edit-userChromeCss-editor = 
    .label = Edytuj plik userChrome.css
edit-userContentCss-editor = 
    .label = Edytuj plik userContent.css
not-found-editor-path = Nie można znaleźć edytora plików CSS
set-pref-description = Wprowadź lokalizację pliku edytora plików CSS, którego chcesz użyć:
rebuild-complete = Odbudowa została zakończona.
please-enter-filename = Wprowadź nazwę pliku.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Otwórz ponownie zamkniętą kartę
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Włącz jako podmotyw
dual-theme-disable-addon-button = Wyłącz podmotyw
dual-theme-enabled-heading = Włączone jako podszablon
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Pasek statusu
    .accesskey = Pr
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Otwórz panel zakładek w stylu drzewa
gf-floorp-open-tree-style-tab-description = Otwórz panel Tree Style Tab na pasku bocznym
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Otwórz boczny panel zakładek
gf-floorp-open-bookmarks-sidebar-description = Otwórz panel zakładek na pasku bocznym
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Otwórz boczny panel historii
gf-floorp-open-history-sidebar-description = Otwórz panel historii na pasku bocznym
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Otwórz boczny panel zsynchronizowanych kart
gf-floorp-open-synctabs-sidebar-description = Otwórz panel zsynchronizowanych kart na pasku bocznym
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Zamknij pasek boczny
gf-floorp-close-sidebar-description = Zamknij pasek boczny
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Otwórz BMS
gf-floorp-open-browser-manager-sidebar-description = Otwórz pasek boczny przeglądarki, jeśli załadowany jest panel menedżera przeglądarki
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Zamknij BMS
gf-floorp-close-browser-manager-sidebar-description = Zamknij pasek boczny menedżera przeglądarki
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Przełącz BMS
gf-floorp-show-browser-manager-sidebar-description = Przełącz pasek boczny menedżera przeglądarki
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Ukryj pasek stanu
gf-floorp-hide-statusbar-description = Ukryj pasek stanu
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Przełącz pasek stanu
gf-floorp-show-statusbar-description = Pokaż lub ukryj pasek statusu
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Otwórz wybrane rozszerzenie na pasku bocznym
gf-floorp-open-extension-sidebar-description = Otwórz wybrane rozszerzenie na pasku bocznym
gf-floorp-open-extension-sidebar-settings-addons-id = Dodatek panelu bocznego
gf-floorp-open-extension-sidebar-settings-addons-id-description = Rozszerzenie dodatku na pasek boczny
gf-floorp-open-extension-sidebar-settings-list-default = Wybierz dodatek
gf-floorp-open-extension-sidebar-settings-list-unknwon = Nieznany dodatek
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Znaleziono aktualizacje!
update-portable-notification-found-message = Pobieranie aktualizacji...
update-portable-notification-ready-title = Gotowy do aktualizacji!
update-portable-notification-ready-message = { -brand-short-name } zostanie zaktualizowany przy następnym uruchomieniu.
update-portable-notification-success-title = Aktualizacja powiodła się!
update-portable-notification-success-message = Aktualizacja powiodła się! Mamy nadzieję, że spodoba ci się nowa wersja { -brand-short-name }!
update-portable-notification-failed-title = Aktualizacja nie powiodła się.
update-portable-notification-failed-redirector-message = Aktualizacja nie powiodła się. Ponowne uruchomienie przeglądarki może rozwiązać ten problem.
update-portable-notification-failed-prepare-message = Nie udało się przygotować aktualizacji.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = Aktualizacja przenośna { -brand-short-name }
floorp-update-application-auto-enabled-option = 
    .label = Automatycznie sprawdzaj aktualizacje dla przenośnej wersji { -brand-short-name }. (Zalecane)
##################################################################### Open link in external ###############################################################
openInExternal-title = Otwórz w zewnętrznej przeglądarce
open-link-in-external-enabled-option = 
    .label = Włącz funkcję "Otwórz w zewnętrznej przeglądarce"
open-link-in-external-select-browser-option = Wybierz jaka przeglądarka zostanie otwarta
open-link-in-external-select-browser-option-default = 
    .label = Domyślna przeglądarka
open-link-in-external-tab-context-menu = Otwórz w zewnętrznej przeglądarce
open-link-in-external-tab-dialog-title-error = Wystąpił błąd:
open-link-in-external-tab-dialog-message-default-browser-not-found = Domyślna przeglądarka nie została znaleziona lub nie została skonfigurowana.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Wybrana przeglądarka nie istnieje.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Nowa
memo-title-input-placeholder = Napisz tutaj tytuł
memo-input-placeholder = Napisz lub wklej notatkę tutaj
delete-memo = Usuń
save-memo = Zapisz
memo-welcome-title = Witaj!
memo-first-tip = Witaj w Notatkach { -brand-short-name }! Oto kilka instrukcji, jak z nich korzystać!
memo-second-tip = { -brand-short-name } Notatki umożliwiają przechowywanie wielu notatek synchronizowanych między urządzeniami. Aby włączyć synchronizację, należy zalogować się w { -brand-short-name } za pomocą konta Firefox.
memo-third-tip = Notatki { -brand-short-name } będą zapisywane w twoich ustawieniach { -brand-short-name } i synchronizowane będą między urządzeniami za pomocą Firefox Sync. Firefox Sync szyfruje zawartość synchronizacji za pomocą hasła do twojego konta Firefox, dzięki czemu nikt poza tobą nie zna ich zawartości.
memo-import-data-tip = Firefox Sync nie jest usługą tworzenia kopii zapasowych. Zalecamy utworzenie kopii zapasowych.
memo-new-title = Nowa notatka
chage-view-mode = Przełącz tryb widoku/edycji
readonly-mode = Offline (tylko do odczytu)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Wsparcie Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Wyczyść pobrania
    .accesskey = D
    .tooltiptext = Wyczyść pobrania
floorp-show-all-downloads = 
    .label = Pokaż wszystkie pobrane pliki
    .accesskey = Pr
    .tooltiptext = Pokaż wszystkie pobrane pliki
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Utwórz nową przestrzeń...
    .tooltiptext = Utwórz nową przestrzeń
workspaces-manage-workspaces-button = 
    .label = Zarządzanie przestrzeniami...
    .tooltiptext = Zarządzaj przestrzeniami
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Zmień nazwę przestrzeni
    .accesskey = R
delete-this-workspace = 
    .label = Usuń przestrzeń
    .accesskey = D
manage-this-workspaces = 
    .label = Zarządzanie przestrzeniami roboczymi...
    .accesskey = M
workspace-new-default-name = Nowa przestrzeń robocza
workspace-default-name = Domyślna
move-tab-another-workspace = 
    .label = Przenieś do innej przestrzeni roboczej
rename-workspace-prompt-title = Zmień nazwę przestrzeni
rename-workspace-prompt-text = Wprowadź nazwę przestrzeni roboczej. Możesz użyć większości znaków i symboli.
workspaces-toolbar-button = Przestrzenie robocze
    .label = Przestrzenie robocze
    .tooltiptext = Wybierz przestrzeń roboczą...

## Preferences

enable-workspaces = 
    .label = Włącz przestrzenie robocze
    .tooltiptext = Włącz przestrzenie robocze
workspace-notice = Przestrzenie robocze nie będą działać z tym ustawieniem, chyba że przycisk przestrzeni roboczych zostanie umieszczony na pasku narzędzi. Użyj tego ustawienia, jeśli chcesz całkowicie wyłączyć przestrzenie robocze.
enable-workspaces-with-experimental = 
    .label = Włącz przestrzenie robocze (Eksperymentalne)
    .tooltiptext = Włącz przestrzenie robocze (Eksperymentalne)
workspace-warning = Przestrzenie robocze nie mogą być używane z rozszerzeniami "Tab Group". Jeśli chcesz korzystać z rozszerzeń "Tab Group", wyłącz przestrzenie robocze i uruchom ponownie { -brand-short-name }.
category-workspaces = 
    .label = Przestrzenie robocze
    .tooltiptext = Przestrzenie robocze
pane-workspaces-title = Przestrzenie robocze
floorp-workspaces-title = Obszary robocze { -brand-short-name }
floorp-workspace-settings-button = Ustawienia projektu...
floorp-preferences-label = Preferences
floorp-extensions-label = Extensions
floorp-private-label = Private
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = Zarządzaj obszarem roboczym w panelu bocznym przeglądarki
show-workspace-name-option = 
    .label = Pokaż nazwę przestrzeni roboczej na przycisku w pasku kart
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Tryb udostępniania
    .accesskey = Pr
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Zaloguj się na swoje konto Firefox
welcome-to-floorp = Witaj w { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Zaczynamy?
welcome-skip-to-start-browsing = Pomiń aby rozpocząć przeglądanie
welcome-select-preferences-template = Wybierz szablon
welcome-minimum-template = Podstawowe
welcome-enable-basic-features = Włącz podstawowe funkcje i ustawienia, aby zapewnić prostą obsługę.
welcome-medium-template = Domyślny
welcome-enable-some-features = Włącz dodatkowe funkcje i ustawienia, aby uzyskać lepsze wrażenia.
welcome-maximum-template = Zaawansowane
welcome-enable-most-of-features = Włącz zaawansowane funkcje i ustawienia. Zalecane dla doświadczonych użytkowników.
welcome-go-next-setup = Następny
welcome-select-browser-design = Wybierz wygląd przeglądarki
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Oryginalny projekt Leptona
welcome-design-photon-name = Projektowanie zdjęć Leptona
welcome-design-ProtonFix-name = Lepton ProtonFix Design
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Projektowanie Proton Firefox
welcome-import-data = Importuj dane przeglądarki
welcome-import-data-description = Szybka konfiguracja! Importuj zakładki, hasła i inne dane ze starej przeglądarki. Użytkownicy Firefoksa mogą importować dane z Firefox Sync.
welcome-import-data-button = Importuj dane...
welcome-import-data-skip = Pomiń import
welcome-select-button = Wybierz
welcome-finish-setup = Konfiguracja zakończona!
welcome-finish-setup-description = Wszystko gotowe! Inne funkcje, takie jak pionowe karty i przestrzenie robocze, można znaleźć w ustawieniach { -brand-short-name }. Miłego korzystania z { -brand-short-name }!
welcomet-finish-setup = Rozpocznij przeglądanie sieci Web
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Skróty klawiszowe
    .tooltiptext = Skróty klawiszowe
category-CSK-title = Skróty klawiszowe
shortcutkey-customize = 
    .title = Skróty klawiszowe
select-shortcutkeyAction = Wybierz akcję do wyzwalania
shortcutkey-customize-key-list-placeholder = Skrót klawiaturowy pojawi się tutaj
shortcut-key-label = Skrót klawiszowy
start-input-button-listen = Zacznij słuchanie
end-input-button-listen = Zakończ słuchanie
shortcut-key-description = Kliknij "Zacznij słuchanie" i wprowadź nowy skrót klawiaturowy dla tej akcji. Można użyć wielu klawiszy, jednak skróty klawiaturowe nie będą działać, jeśli zostały już przypisane do innych działań.
floorp-custom-actions-open-new-tab = Otwórz nową kartę
    .label = Otwórz nową kartę
floorp-custom-actions-close-tab = Zamknij bieżącą kartę
    .label = Zamknij bieżącą kartę
floorp-custom-actions-open-new-window = Otwórz nowe okno
    .label = Otwórz nowe okno
floorp-custom-actions-open-new-private-window = Otwórz nowe okno prywatne
    .label = Otwórz nowe okno prywatne
floorp-custom-actions-close-window = Zamknij bieżące okno
    .label = Zamknij bieżące okno
floorp-custom-actions-restore-last-session = Przywróć ostatnią sesję
    .label = Przywróć ostatnią sesję
floorp-custom-actions-restore-last-window = Przywróć ostatnie okno
    .label = Przywróć ostatnie okno
floorp-custom-actions-show-next-tab = Pokaż następną kartę
    .label = Pokaż następną kartę
floorp-custom-actions-show-previous-tab = Pokaż poprzednią kartę
    .label = Pokaż poprzednią kartę
floorp-custom-actions-show-all-tabs-panel = Pokaż wszystkie karty
    .label = Pokaż listę kart
floorp-custom-actions-send-with-mail = Wyślij pocztą
    .label = Wyślij e-mailem
floorp-custom-actions-save-page = Zapisz stronę
    .label = Zapisz stronę
floorp-custom-actions-print-page = Print page
    .label = Print page
floorp-custom-actions-mute-current-tab = Przełącz wyciszenie/wycisz aktywną kartę
    .label = Przełącz wyciszenie/wycisz aktywną kartę
floorp-custom-actions-toggle-bookmark-toolbar = Przełącz pasek zakładek
    .label = Przełącz pasek zakładek
floorp-custom-actions-show-source-of-page = Pokaż źródło strony
    .label = Źródło otwartej strony
floorp-custom-actions-show-page-info = Pokaż informacje o stronie
    .label = Otwórz informacje o stronie
floorp-custom-actions-zoom-in = Powiększ
    .label = Powiększ
floorp-custom-actions-zoom-out = Pomniejsz
    .label = Pomniejsz
floorp-custom-actions-reset-zoom = Reset zoom
    .label = Reset zoom
floorp-custom-actions-back = Powrót
    .label = Powrót
floorp-custom-actions-forward = Przekaż
    .label = Przekaż
floorp-custom-actions-reload = Reload
    .label = Reload
floorp-custom-actions-stop = Zatrzymaj
    .label = Zatrzymaj
floorp-custom-actions-force-reload = Wymuś przeładowanie
    .label = Wymuś przeładowanie
floorp-custom-actions-search-in-this-page = Szukaj na tej stronie
    .label = Znajdź na stronie
floorp-custom-actions-show-next-search-result = Pokaż następne słowo wyszukiwania w wyniku tej strony
    .label = Następny wynik "Znajdź na stronie"
floorp-custom-actions-show-previous-search-result = Pokaż poprzednie słowo wyszukiwania w wyniku tej strony
    .label = Poprzedni wynik "Znajdź na stronie"
floorp-custom-actions-search-the-web = Szukaj w sieci
    .label = Szukaj w sieci
floorp-custom-actions-open-migration-wizard = Otwórz kreatora migracji
    .label = Otwórz kreatora migracji
floorp-custom-actions-quit-from-application = Wyjdź z aplikacji
    .label = Wyjdź z { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Dostosuj pasek narzędzi
    .label = Otwórz dostosowywanie { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Przejście do trybu offline
    .label = Wejdź do trybu offline
floorp-custom-actions-open-screen-capture = Otwórz narzędzie przechwytywania ekranu
    .label = Zrób zrzut ekranu
floorp-custom-actions-show-pip = Pokaż obraz w obrazku
    .label = Pokaż obraz w zdjęciu
floorp-custom-actions-bookmark-this-page = Dodaj zakładkę do tej strony
    .label = Dodaj zakładkę do tej strony
floorp-custom-actions-open-bookmarks-sidebar = Otwórz pasek boczny zakładek
    .label = Otwórz pasek boczny zakładek
floorp-custom-actions-open-bookmark-add-tool = Otwórz zakładkę dodawania narzędzia
    .label = Dodaj zakładkę
floorp-custom-actions-open-bookmark-add-toolbar = Otwórz wyskakujące okno "Dodaj nową zakładkę"
    .label = Dodaj do paska zakładek
floorp-custom-actions-open-bookmarks-manager = Otwórz menedżera zakładek
    .label = Otwórz Menedżera Zakładek
floorp-custom-actions-show-bookmark-toolbar = Przełącz pasek zakładek
    .label = Przełącz pasek zakładek
floorp-custom-actions-open-general-preferences = Otwórz ustawienia ogólne
    .label = Otwórz ustawienia ogólne
floorp-custom-actions-open-privacy-preferences = Otwórz ustawienia prywatności
    .label = Otwórz ustawienia prywatności
floorp-custom-actions-open-workspaces-preferences = Open Workspaces preferences
    .label = Otwórz ustawienia przestrzeni roboczej
floorp-custom-actions-open-containers-preferences = Ustawienia otwierania kontenerów
    .label = Ustawienia Otwartych kontenerów
floorp-custom-actions-open-search-preferences = Otwórz ustawienia wyszukiwania
    .label = Otwórz ustawienia wyszukiwania
floorp-custom-actions-open-sync-preferences = Otwórz ustawienia synchronizacji
    .label = Otwórz ustawienia synchronizacji
floorp-custom-actions-open-task-manager = Otwórz menedżera zadań
    .label = Otwórz Menedżera zadań { -brand-short-name }
floorp-custom-actions-open-home-page = Otwórz stronę główną { -brand-short-name }
    .label = Otwórz stronę główną { -brand-short-name }
floorp-custom-actions-open-addons-manager = Otwórz rozszerzenia i motywy
    .label = Otwórz dodatki i motywy
floorp-custom-actions-forget-history = Zapomnij historii
    .label = Zapomnij historii
floorp-custom-actions-quick-forget-history = Szybkie zapomnianie historii
    .label = Szybkie zapomnianie historii
floorp-custom-actions-clear-recent-history = Wyczyść ostatnią historię
    .label = Wyczyść ostatnią historię
floorp-custom-actions-search-history = Historia wyszukiwania
    .label = Historia wyszukiwania
floorp-custom-actions-manage-history = Zarządzaj historią
    .label = Zarządzaj historią
floorp-custom-actions-open-downloads = Otwórz pobieranie
    .label = Otwórz pobieranie
floorp-custom-actions-show-bms = Toggle browser manager sidebar
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = Pokaż pasek boczny zakładki
    .label = Pokaż pasek boczny zakładek
floorp-custom-actions-show-history-sidebar = Show history sidebar
    .label = Show History Sidebar
floorp-custom-actions-show-synced-tabs-sidebar = Pokaż pasek boczny zsynchronizowanych kart
    .label = Pokaż pasek boczny zsynchronizowanych kart
floorp-custom-actions-reverse-sidebar = Odwrócona pozycja paska bocznego
    .label = Odwrócona pozycja paska bocznego
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = Przełącz pasek boczny
    .label = Przełącz pasek boczny
floorp-custom-actions-toggle-sidebar = Przełącz pasek boczny
    .label = Przełącz pasek boczny
floorp-custom-actions-open-previous-workspace = Open previous Workspace
    .label = Open previous Workspace
floorp-custom-actions-open-next-workspace = Open next Workspace
    .label = Open next Workspace
floorp-custom-actions-show-panel-1 = Przełącz panel 1
    .label = Przełącz panel 1
floorp-custom-actions-show-panel-2 = Przełącz panel 2
    .label = Przełącz panel 2
floorp-custom-actions-show-panel-3 = Przełącz panel 3
    .label = Przełącz panel 3
floorp-custom-actions-show-panel-4 = Przełącz panel 4
    .label = Przełącz panel 4
floorp-custom-actions-show-panel-5 = Przełącz panel 5
    .label = Przełącz panel 5
floorp-custom-actions-show-panel-6 = Przełącz panel 6
    .label = Przełącz panel 6
floorp-custom-actions-show-panel-7 = Przełącz panel 7
    .label = Przełącz panel 7
floorp-custom-actions-show-panel-8 = Przełącz panel 8
    .label = Przełącz panel 8
floorp-custom-actions-show-panel-9 = Przełącz panel 9
    .label = Przełącz panel 9
floorp-custom-actions-show-panel-10 = Przełącz panel 10
    .label = Przełącz panel 10
floorp-custom-actions-open-split-view-on-left = Otwórz bieżącą kartę po lewej stronie w widoku podzielonym
    .label = Otwórz bieżącą kartę po lewej stronie w widoku podzielonym
floorp-custom-actions-open-split-view-on-right = Otwórz bieżącą kartę po prawej stronie w widoku podzielonym
    .label = Otwórz bieżącą kartę po prawej stronie w widoku podzielonym
floorp-custom-actions-close-split-view = Zamknij widok podzielony
    .label = Zamknij widok podzielony
floorp-custom-actions-custom-action-1 = Akcja niestandardowa 1
    .label = Akcja niestandardowa 1
floorp-custom-actions-custom-action-2 = Niestandardowe działanie 2
    .label = Niestandardowe działanie 2
floorp-custom-actions-custom-action-3 = Niestandardowe działanie 3
    .label = Niestandardowe działanie 3
floorp-custom-actions-custom-action-4 = Niestandardowe działanie 4
    .label = Niestandardowe działanie 4
floorp-custom-actions-custom-action-5 = Akcja niestandardowa 5
    .label = Akcja niestandardowa 5
floorp-custom-actions-rest-mode = Włącz tryb odpoczynku
    .label = Włącz tryb odpoczynku
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
floorp-custom-actions-toggle-navigation-panel = Toggle Navigation Panel
    .label = Toggle Navigation Panel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Uruchom
    .tooltiptext = Uruchom { -brand-short-name } z tym profilem
floorp-profiles-in-use = Ten profil jest w użyciu.
floorp-profiles-title = Profiles
floorp-profile-manager = Menedżer profilu
floorp-profiles-create = Utwórz profil
floorp-profile = Profil
    .label = Menedżer profilu
    .tooltiptext = Otwórz Menedżera Profili
fxa-not-signed-in = Nie zalogowano
###################################################################### Private Container ##############################################################
floorp-private-container-name = Prywatny
floorp-toggle-private-container = 
    .label = Otwórz ponownie w Prywatnym/bez kontenera
    .accesskey = P
open-in_private-container = 
    .label = Otwórz w nowej karcie z prywatnym kontenerem
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Open in Split View
floorp-split-view-close-menu = 
    .label = Close Split Tab
floorp-split-view-grid = Grid
floorp-split-view-vertical = Vertical
floorp-split-view-horizontal = Horizontal
floorp-split-view-unsplit = Unsplit
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Zeskanuj kod QR za pomocą telefonu
qrcode-generate-page-action = 
    .tooltiptext = Udostępnij tę strone na telefon
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Przycisk rozszerzeń
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Zainstaluj aplikację
    .tooltiptext = Zainstaluj tę stronę jako aplikację
ssb-page-action-title = Zainstaluj aplikację
ssb-app-open-button = 
    .label = Otwórz w aplikacji
ssb-app-install-button = 
    .label = Zainstaluj
ssb-app-cancel-button = 
    .label = Anuluj
floorp-open-manage-ssb-page = 
    .label = Zarządzaj zainstalowanymi aplikacjami
appmenuitem-webapps = 
    .label = Aplikacje internetowe
appmenu-open-installed-apps-subheader = Otwórz zainstalowane aplikacje
appmenuitem-install-current-page = 
    .label = Zainstaluj tę stronę jako aplikację
appmenuitem-open-current-page = 
    .label = Otwórz tę stronę w zainstalowanej aplikacji
appmenuitem-contextmenu-open-app = 
    .label = Otwórz tę aplikację
appmenuitem-contextmenu-uninstall-app = 
    .label = Odinstaluj tę aplikację

## Preferences

category-ssb = 
    .label = Aplikacje internetowe
    .tooltiptext = Aplikacje internetowe
category-ssb-title = Aplikacje internetowe
floorp-ssb-title = Aplikacje internetowe
floorp-ssb-description = Aplikacje internetowe to strony, które mogą być instalowane jako aplikacje. Mogą być uruchamiane z panelu menu { -brand-short-name } lub menu start Windows.
ssb-preferences = Ustawienia aplikacji internetowych
floorp-enable-ssb = 
    .label = Włącz aplikacje internetowe
floorp-enable-ssb-with-experimental = 
    .label = Włącz aplikacje internetowe (eksperymentalne)
floorp-enable-ssb-description = Ta funkcja jest eksperymentalna w systemach Mac i Linux. Zaleca się włączenie tej funkcji w systemie Windows.
floorp-disable-toolbars = 
    .label = Wyłącz paski narzędzi w oknach aplikacji internetowych
floorp-disable-toolbars-description = To ustawienie ukryje wszystkie rozszerzenia i paski narzędzi w oknach aplikacji internetowych.
ssb-installed-list-title = Zainstalowane aplikacje internetowe
ssb-uninstall-title = Odinstaluj aplikację internetową
ssb-uninstall-message = Czy na pewno chcesz odinstalować tę aplikację z { -brand-short-name }?
ssb-uninstall-button = 
    .label = Odinstaluj
ssb-uninstall-cancel = Anuluj
######################################################################### Download Notification ###############################################################
floorp-started-download = Pobieranie rozpoczęte
floorp-finished-download = Pobieranie ukończone
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } jest aktualny!
floorp-notificationContent-latest = { -brand-short-name } jest aktualny. Korzystasz z najnowszej wersji { -brand-short-name }.
floorp-notificationTitle = Dostępna jest nowa wersja { -brand-short-name }!
floorp-notificationContent = Kliknij, aby pobrać najnowszą wersję.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
