# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> is one of the domestic browsers developed in Japan. It is based on Firefox and continues to operate under <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, to improve the web. Want to help? <label data-l10n-name="helpus-donateLink">Make a donation</label>
icon-creator = Icon creator <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> and <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = A list of <label data-l10n-name="about-contributor">contributors and Developers</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Utseende
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = En omstart er nødvendig for å lagre endringer
tab-width = Minimum bredde på faner
tab-height = Minimum høyde på faner
preferences-tabs-newtab-position = Plassering av ny fane
open-new-tab-use-default = 
    .label = Åpne nye faner i standardposisjon
open-new-tab-at-the-end = 
    .label = Open new tabs at the end of the Tab Bar
open-new-tab-next-to-current = 
    .label = Open new tabs next to the current tab
multirow-tabs-limit = 
    .label = Enable row limit for multi-row tabs
multirow-tabs-newtab = 
    .label = Place the "Open a new tab" button at the end of the lowest row of tabs
multirow-tabs-value = Number of rows when multi-row tabs are enabled
enable-tab-sleep = 
    .label = Enable Sleeping Tabs
tab-sleep-timeout-minutes-value = Tabs will sleep after being inactive for (minutes)
tab-sleep-settings-button = Innstillinger...
tab-sleep-settings-dialog-title = 
    .title = Sleeping Tabs Settings
tab-sleep-settings-dialog-excludehosts-label = Ekskluder verter
tab-sleep-settings-dialog-excludehosts-label-2 = Enter one host per line.
tab-sleep-tab-context-menu-excludetab = Hold fanen våken
enable-tab-scroll-change = 
    .label = Switch tabs by scrolling with your mouse
enable-tab-scroll-reverse = 
    .label = Reverse direction of scrolling tabs
enable-tab-scroll-wrap = 
    .label = Wrap scrolling tabs at the edge
enable-double-click-block = 
    .label = Close tabs with a double click
enable-show-pinned-tabs-title = 
    .label = Show the title of pinned tabs
tabbar-preference = Tab Bar
tab-normal-mode = 
    .label = Standard
hide-horizontality-tabs = 
    .label = Hide tabs on Horizontal Tab Bar
verticalTab-setting = 
    .label = Optimise browser for Vertical Tab Bar
move-tabbar-position = 
    .label = Display Tab Bar underneath the Toolbar
tabbar-on-bottom = 
    .label = Display Tab Bar at the bottom of the window
tabbar-favicon-color = 
    .label = Color the Tab Bar using the current website's favicon color
tabbar-style-preference = Tab Bar Style
horizontal-tabbar = 
    .label = Horizontal Tab Bar
tabbar-style-description = A restart of { -brand-short-name } is required to fully apply this setting.
multirow-tabbar = 
    .label = Multi-Row Tab Bar
vertical-tabbar = 
    .label = Vertical Tab Bar (experimental)
native-vertical-tab-show-right = 
    .label = Show Vertical Tab Bar on the right side of the window
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = Collapse Vertical Tab Bar
floorp-show-vertical-tab-newtab-button = 
    .label = Show the "Open a new tab" button inside Vertical Tab Bar
floorp-show-vertical-tab-scrollbar = 
    .label = Show scrollbar on Vertical Tab Bar
TST = Tree Style Tab
about-TST = Tree Style Tab is a popular add-on that allows you to display tabs in a tree-like structure. This add-on is already pre-integrated in { -brand-short-name }. Please install the add-on to activate { -brand-short-name }'s Tree Style Tab.
treestyletab-Settings = 
    .label = Collapse Tree Style Tab
sidebar-reverse-position-toolbar = Show Sidebars on the other side
bookmarks-bar-settings = Bookmarks Toolbar (only one option can be used at a time)
bookmarks-focus-mode = 
    .label = Hide the Bookmarks Toolbar unless hovering over the navigation bar
bookmarks-bottom-mode = 
    .label = Show the Bookmarks Toolbar at the bottom of { -brand-short-name }
navbar-settings = Navigasjonsbar
show-nav-bar-bottom = 
    .label = Show the Toolbar at the bottom of { -brand-short-name } (experimental)
disable-extension-check-compatibility-option = 
    .label = Do not check for compatibility with add-ons (deprecated)
other-preference = Other Preferences
search-positon-top = 
    .label = Display the Find Bar at the top of the page
allow-auto-restart = 
    .label = Restart automatically when settings that require a restart are changed
disable-fullscreen-notification = 
    .label = Do not show a notification when entering full screen

## Browser Theme

system-color-settings = Some themes have both light and dark modes - choose which mode you'd like these themes to use.
preferences-theme-appearance-header = Tema Modus
system-theme-dark = 
    .label = Mørk
system-theme-light = 
    .label = Lys
system-theme-auto = 
    .label = Følg systemutseendet mitt

## User interface preferences

ui-preference = Utseende på nettleser
preferences-browser-appearance-description = Velg et innebygd tredjeparts design å bruke i { -brand-short-name }. Noen design er kanskje ikke kompatible med din konfigurasjon.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (foreldet)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (New)

## Download Manager

download-notification-preferences = Last ned varsler
start-always-notify = 
    .label = Varsle kun når du starter nedlastinger
finish-always-notify = 
    .label = Varsle kun når en nedlasting er ferdig
always-notify = 
    .label = Varsle ved start av nedlastinger og når en nedlasting er ferdig
do-not-notify = 
    .label = Deaktiver nedlastingsvarsler

## Sidebar

profiles-button-label = Administrer profiler
floorp-help-button-label = { -brand-short-name } brukerstøtte
appmenuitem-reboot = 
    .label = Omstart

## DMR UI

download-mgr-UI = 
    .label = Enable the SimpleUI Download Manager
downloading-red-color = 
    .label = Use the red downloads icon when downloading
sidebar-preferences = Sidebar
bsb-preferences = Browser Manager Sidebar Settings
view-sidebar2-right = 
    .label = Display the Browser Manager Sidebar on the right
enable-sidebar2 = 
    .label = Enable the Browser Manager Sidebar
visible-bms = 
    .label = Show the Browser Manager Sidebar
hide-bms-to-unload-panel = 
    .label = Unload panel when hiding panel
enable-addons-in-sidebar2-with-experimental = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar (experimental)
enable-addons-in-sidebar2 = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar
sidebar2-enable-addons-desc = If this setting is enabled, ad blocking extensions and other extensions will work in the sidebar. However, not all extensions will work.
custom-URL-option = Set Web Panel URLs
set-custom-URL-button = 
    .label = Set Custom URLs...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Browser Manager Sidebar
bsb-context = Use the following Container
bsb-userAgent-label = 
    .label = Use Mobile User Agent in this Web Panel
bsb-width = Width (if set to 0, the global value will be used)
bsb-page = Side å åpne
bsb-add = Add Web Panel on Browser Manager Sidebar
bsb-setting = Web Panel Settings
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Nettside
sidebar2-pref-delete = 
    .label = Slett
sidebar2-pref-setting = 
    .label = Innstillinger
sidebar2-global-width = Global Web Panels width
use-icon-provider-option = Use Icon Provider
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (tilgjengelig i Kina)
use-icon-provider-option-hatena = 
    .label = Hatena (tilgjengelig i Kina)
memory-and-performance = Minne og prestasjon
min-memory = 
    .label = Minimum minnebruk (lav ytelse)
balance-memory = 
    .label = Balanser minnebruk og ytelse
max-memory = 
    .label = Best Performance (high memory usage)
delete-border-and-roundup-option = 
    .label = Avrund hjørnene på sider

## DualTheme

dualtheme-enable = 
    .label = Enable Dual Theme (Deprecated)
floorp-enable-dualtheme-description = Dual Theme feature may cause problems with extensions. Please use with caution.
newtab-background = { -brand-short-name } Home Background
newtab-background-random-image = 
    .label = Random images from Unsplash
newtab-background-gradation = 
    .label = Gradient
newtab-background-not-background = 
    .label = Deaktiver bakgrunn
newtab-background-selected-image = 
    .label = Custom folder...
newtab-background-selected-one-image = 
    .label = Egendefinert bilde...
newtab-background-folder = Use images from this folder:
newtab-background-image = Bruk bilde :
newtab-choose-image = Velg bilde...
newtab-background-folder-reload = 
    .label = Last inn bilder på nytt
newtab-background-folder-default = 
    .label = Last inn standardinnstillinger
newtab-background-folder-open = 
    .label = Åpne mappe
newtab-background-folder-choose = Velg bildemappe...
newtab-background-image-choose = Velg bilde...
newtab-background-extensions = Use images with these file extensions (separated by ",")
disable-blur-on-newtab = 
    .label = Disable blur effect in { -brand-short-name } Home
disable-releasenote-on-newtab = 
    .label = Disable Release Note and Support Links in { -brand-short-name } Home
disable-imagecredit-on-newtab = 
    .label = Disable image credit (Unsplash) in { -brand-short-name } Home

## Lepton Preferences

about-lepton = Tilpass { -brand-short-name } med Lepton
lepton-preference-button = 
    .label = Innstillinger for Lepton...
    .accesskey = L
lepton-header = Innstillinger for Lepton
lepton-preference = Innstillinger for Lepton
photon-mode = 
    .label = Bruk Photon utseende
lepton-mode = 
    .label = Bruk Photon utseende
protonfix-mode = 
    .label = Use tweaked Proton design
autohide-preference = Automatically hide browser elements
floorp-lepton-enable-tab-autohide = 
    .label = Skjul faner automatisk
floorp-lepton-enable-navbar-autohide = 
    .label = Skjul verktøylinjen automatisk
floorp-lepton-enable-sidebar-autohide = 
    .label = Automatically hide Sidebar
floorp-lepton-enable-urlbar-autohide = 
    .label = Automatically hide Address Bar
floorp-lepton-enable-back-button-autohide = 
    .label = Automatically hide back button
floorp-lepton-enable-forward-button-autohide = 
    .label = Automatically hide forward button
floorp-lepton-enable-page-action-button-autohide = 
    .label = Automatically hide buttons on the Address Bar
floorp-lepton-enable-toolbar-overlap = 
    .label = Show Toolbar over website content
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Automatically hide Toolbar when displaying "ltr" content
hide-preference = Manage browser elements
floorp-lepton-enable-tab_icon-hide = 
    .label = Hide tab icons
floorp-lepton-enable-tabbar-hide = 
    .label = Hide Tab Bar
floorp-lepton-enable-navbar-hide = 
    .label = Hide Toolbar
floorp-lepton-enable-sidebar_header-hide = 
    .label = Hide Sidebar Headers
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Hide Address Bar icons
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Hide Bookmarks Bar icons
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Hide Bookmarks Bar labels
floorp-lepton-enable-disabled_menu-hide = 
    .label = Hide disabled context menu items
floorp-lepton-disable-userChrome-icon = 
    .label = Disable Lepton's context menu and panel menu icons
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Enable Lepton's context menu icons
positon-preferences = Position adjustments
floorp-lepton-enable-centered-tab = 
    .label = Sentrer etiketter på faner
floorp-lepton-enable-centered-urlbar = 
    .label = Center text in the Address Bar
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Center Bookmarks Bar items
urlbar-preferences = Adresselinje
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Move Address Bar icons to the left side
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = When typing, show a "Go" button
floorp-lepton-enable-always-show-page_action = 
    .label = Always show page actions in the Address Bar
tabbar-preferences = Tab Bar
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Tab Bar in the Title Bar
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Combine Tab Bar and Toolbar
lepton-sidebar-preferences = Sidebar
floorp-lepton-enable-overlap-sidebar = 
    .label = Show Sidebar over website content
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Hjem (standard)
floorp-home-prefs-content-header = { -brand-short-name } Home Content
floorp-home-prefs-content-description = Choose the content you want to see on the { -brand-short-name } Home Page.

## Notes

floorp-notes = { -brand-short-name } Notes
restore-from-backup = Restore Notes from backup
enable-notes-sync = 
    .label = Enable { -brand-short-name } Notes Sync
about-notes-backup-tips = { -brand-short-name } Notes uses Firefox Sync to sync your notes with other devices. If you lose your notes, you can restore them from a backup. A backup is created when you launch { -brand-short-name }.
notes-sync-description = This can solve the problem of losing content due to overwriting notes during synchronization.
backuped-time = Sikkerhetskopiert på
notes-backup-option = Innstillinger for sikkerhetskopiering
backup-option-button = Innstillinger for sikkerhetskopiering...
restore-from-backup-prompt-title = { -brand-short-name } Notes Restore Service
restore-from-this-backup = Restore Notes back to the state they were in this backup?
restore-button = Gjenopprett

## user.js

header-userjs = user.js
userjs-customize = Customize { -brand-short-name } with user.js
about-userjs-customize = user.js is a configuration file that allows you to customize { -brand-short-name }. user.js files are downloaded from the Internet and overwrite your current user.js file. Please back up your current user.js file before continuing. user.js configurations will be applied automatically after restarting { -brand-short-name }.
userjs-label = user.js list
userjs-prompt = Apply this user.js?
apply-userjs-attention = Applying a new user.js will overwrite your current user.js file.
apply-userjs-attention2 = Please back up your current user.js file before continuing.
userjs-button = user.js Settings...
userjs-select-option = Manage the user.js currently used in { -brand-short-name } to improve performance and privacy.
apply-userjs-button = Bruk

## userjs Options

default-userjs-label = { -brand-short-name } Standard
about-default-userjs = Telemetry disabled. Well balanced { -brand-short-name } with various customizations enabled.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS-by-Default. Total Cookie Protection with site isolation. Enhanced state and network partitioning. Various other enhancements.
default-label = Yokoffing Default
about-default = All the essentials. None of the breakage. This is your user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Immensely increase Firefox's browsing speed. Give Chrome a run for its money!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Unclutter the new tab page. Remove Pocket. Restore compact mode as an option. Stop webpage notifications, pop-ups, and other annoyances.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Get Edge-like smooth scrolling on your favorite browser — or choose something more your style.
select-workspace = Velg arbeidsområde
workspace-select-icon = Velg arbeidsområdets ikon
    .label = Select Workspace Icon
workspace-select-container = Select Container Tab
    .label = Select Container Tab
workspace-customize = 
    .title = Customize Workspace
floorp-no-workspace-container = 
    .label = Ingen beholder
workspace-icon-article = 
    .label = Artikkel
workspace-icon-book = 
    .label = Bok
workspace-icon-briefcase = 
    .label = Jobb
workspace-icon-cart = 
    .label = Handel
workspace-icon-chat = 
    .label = Chat
workspace-icon-chill = 
    .label = Privat
workspace-icon-circle = 
    .label = Sirkel
workspace-icon-compass = 
    .label = Kompass
workspace-icon-code = 
    .label = Kode
workspace-icon-dollar = 
    .label = Bank
workspace-icon-fence = 
    .label = Gjerde
workspace-icon-fingerprint = 
    .label = Personlig
workspace-icon-food = 
    .label = Mat
workspace-icon-fruit = 
    .label = Frukt
workspace-icon-game = 
    .label = Spill
workspace-icon-gear = 
    .label = Tannhjul
workspace-icon-gift = 
    .label = Gave
workspace-icon-key = 
    .label = Nøkkel
workspace-icon-lightning = 
    .label = Lyn
workspace-icon-network = 
    .label = Internett
workspace-icon-notes = 
    .label = Notater
workspace-icon-paint = 
    .label = Maling
workspace-icon-photo = 
    .label = Bilde
workspace-icon-pin = 
    .label = Fest
workspace-icon-pet = 
    .label = Kjæledyr
workspace-icon-question = 
    .label = Spørsmål
workspace-icon-smartphone = 
    .label = Smart telefon
workspace-icon-star = 
    .label = Stjerne
workspace-icon-tree = 
    .label = Tre
workspace-icon-vacation = 
    .label = Ferie
workspace-icon-love = 
    .label = Kjærlighet
workspace-icon-moon = 
    .label = Måne
workspace-icon-music = 
    .label = Musikk
workspace-icon-user = 
    .label = Bruker
# Custom Keyboard Shortcuts
floorp-CSK-title = Egendefinerte hurtigtaster
floorp-CSK-description = Customize { -brand-short-name }'s keyboard shortcuts. { -brand-short-name } provides more than 80 customizable keyboard shortcuts! Duplicate keyboard shortcuts will not work. Restart { -brand-short-name } to apply these settings.
disable-fx-actions = 
    .label = Deaktiver Mozilla Firefox sine tastatursnarveier
floorp-CSK-error = The keybinding you entered is already in use. Please try a different keybinding.
customize-Action = 
    .label = Ny snarvei
remove-Action = 
    .label = Fjern snarvei
CSK-reset-title = Reset custom keyboard shortcuts
CSK-reset-description = Reset custom keyboard shortcuts to { -brand-short-name }'s defaults.
CSK-reset-label = Reset custom keyboard shortcuts
CSK-reset-button = Last inn standardinnstillinger
CSK-manage-title = Manage keyboard shortcuts
CSK-remove-shortcutkey = Remove custom keyboard shortcut?
CSK-remove-shortcutkey-description = Are you sure you want to remove this keyboard shortcut?
CSK-restore-default = Last inn standardinnstillinger?
CSK-restore-default-description = Restore { -brand-short-name }'s default keyboard shortcuts? Your current shortcuts will be lost.
CSK-reboot-browser-label = Restart { -brand-short-name } to apply these settings
CSK-reboot-browser-button = Restart { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Current keyboard shortcut: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Current keyboard shortcut: { $key }.
CSK-keyborad-shortcut-is-changed = (Not Applied)
floorp-custom-actions-tab-action = Tab Actions
floorp-custom-actions-page-action = Page Actions
floorp-custom-actions-visible-action = Visible Actions
floorp-custom-actions-search-action = Søk handlinger
floorp-custom-actions-tools-action = Handlinger for verktøy
floorp-custom-actions-bookmark-action = Bokmerkehandlinger
floorp-custom-actions-open-page-action = Åpne sidehandlinger
floorp-custom-actions-history-action = History Actions
floorp-custom-actions-pip-action = Picture-in-Picture Actions
floorp-custom-actions-downloads-action = Downloads Actions
floorp-custom-actions-sidebar-action = Sidebar Actions
floorp-custom-actions-bms-action = Browser Manager Sidebar Actions
floorp-custom-actions-split-view-action = Split View Actions
floorp-custom-actions-workspaces-action = Workspaces Actions
floorp-custom-actions-custom-action = Custom Actions (Experimental)

## Mouse Gestures

mouse-gesture = Musebevegelser
mouse-gesture-description = Gesturefy must be installed to use mouse gestures with { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy is an extension that adds mouse gestures to your browser. If { -brand-short-name } detects the installation of this add-on, it will add gesture commands to Gesturefy that are only available in { -brand-short-name }. This add-on also create new tabs!
# Translate
TWS = Oversett websider
about-TWS = Translate your page in real time using Google or Yandex. You can also translate selected text or the entire page.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Privacy Hub
block-more-tracker = Block more Ads and Trackers
block-tracker = This section contains a set of extensions designed to block ads and trackers
view-at-AMO = View this addon in addons.mozilla.org
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin blocks ads, extensive trackers, and additional dangerous sites.
Facebook-Container = Facebook Container
about-Facebook-Container = Prevent Facebook from tracking you around the web. Facebook Container extension helps you take control and isolate your web activity from Facebook.

## Fingerprinting

fingerprint-header = Resist Fingerprinting & IP address leaks
block-fingerprint = Fingerprinting is a tracking mechanism that relies on the unique features of your browser and operating system. This section contains settings to further enhance this protection beyond the default blocking.
enable-firefox-fingerprint-protections = 
    .label = Enable strong protection against fingerprinting
about-firefox-fingerprint-protection = Enabling protection by Firefox includes forced light mode, disabling some APIs, etc. Some sites may be broken.
fingerprint-Protection = 
    .label = Anti-fingerprinting protections
html5-canvas-prompt-settings = 
    .label = Automatically dismiss access confirmation prompts for HTML5 image data
canvas-prompt = Prevents websites from using the canvas-reading prompt unless manually permitted.
disable-webgl = 
    .label = Deaktiver WebGL
about-webgl = WebGL is a Javascript API used to render graphics, which can be used to identify GPU.
Canvas-Blocker = Canvas Blocker
about-CB = This add-on spoofs data used by fingerprinting techniques.
WebRTC-connection = WebRTC is a standard that provides real-time calling. If you disable this setting, you will not be able to use Discord, etc.
WebRTC = 
    .label = Enable WebRTC Connection
################################################################### browser ###############################################################

rest-mode = Tar en pause...
rest-mode-description = { -brand-short-name } is currently suspended. Press ENTER or OK to continue.
Sidebar2 = 
    .label = Browser Manager Sidebar
    .tooltiptext = Change Sidebar visibility
sidebar2-mute-and-unmute = 
    .label = Mute/Unmute this Panel
sidebar2-unload-panel = 
    .label = Unload this Panel
sidebar2-change-ua-panel = 
    .label = Toggle Mobile User Agent
sidebar2-delete-panel = 
    .label = Slett dette panelet
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom inn
sidebar2-zoom-out = 
    .label = Zoom ut
sidebar2-reset-zoom = 
    .label = Nullstill zoom
sidebar2-close-button = 
    .tooltiptext = Close Sidebar
sidebar-back-button = 
    .tooltiptext = Tilbake
sidebar-forward-button = 
    .tooltiptext = Frem
sidebar-reload-button = 
    .tooltiptext = Last inn på nytt
sidebar-go-index-button = 
    .tooltiptext = Gå hjem
sidebar-muteAndUnmute-button = 
    .tooltiptext = Mute/Unmute sidebar
sidebar2-browser-manager-sidebar = Browser Manager
show-browser-manager-sidebar = 
    .tooltiptext = Show { sidebar2-browser-manager-sidebar } Sidebar
sidebar2-bookmark-sidebar = Bokmerker
show-bookmark-sidebar = 
    .tooltiptext = Show { sidebar2-bookmark-sidebar } Sidebar
sidebar2-history-sidebar = Logg
show-history-sidebar = 
    .tooltiptext = Show { sidebar2-history-sidebar } Sidebar
sidebar2-download-sidebar = Nedlastinger
show-download-sidebar = 
    .tooltiptext = Show { sidebar2-download-sidebar } Sidebar
sidebar2-notes-sidebar = Notater
show-notes-sidebar = 
    .tooltiptext = Show { sidebar2-notes-sidebar } Sidebar
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Add-ons and themes
sidebar2-hide-sidebar-button = 
    .tooltiptext = Hide Browser Manager Sidebar
sidebar-passwords-button = 
    .tooltiptext = Passord
sidebar-preferences-button = 
    .tooltiptext = Innstillinger
sidebar-keepWidth-button = 
    .tooltiptext = Keep using the current width on this Panel
sidebar2-keep-width-for-global = 
    .label = Apply this width to all panels without a custom width
bsb-context-add = 
    .label = Add page to Web Panel...
bsb-context-link-add = 
    .label = Add link to Web Panel...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Open Profile Directory
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Rebuild browser CSS files
    .accesskey = R
make-browsercss-file = 
    .label = Create browser CSS file
    .accesskey = M
open-css-folder = 
    .label = Open CSS folder
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Edit userChrome.css file
edit-userContentCss-editor = 
    .label = Edit userContent.css file
not-found-editor-path = Could not find a CSS file editor
set-pref-description = Input the file location of the CSS file editor you want to use:
rebuild-complete = Rebuild has been completed.
please-enter-filename = Vennligst skriv inn et filnavn.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Gjenåpne lukket fane
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Enable as a sub-theme
dual-theme-disable-addon-button = Disable sub-theme
dual-theme-enabled-heading = Enabled as a sub-theme
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Status Bar
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Open Tree Style Tab Panel
gf-floorp-open-tree-style-tab-description = Open Tree Style Tab Panel on the Sidebar
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Open Bookmarks Panel
gf-floorp-open-bookmarks-sidebar-description = Open Bookmarks Panel on the Sidebar
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Open History Panel
gf-floorp-open-history-sidebar-description = Open History Panel on the Sidebar
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Open Synced Tabs Panel
gf-floorp-open-synctabs-sidebar-description = Open Synced Tabs Panel on the Sidebar
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Close Sidebar
gf-floorp-close-sidebar-description = Close Sidebar
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Open BMS
gf-floorp-open-browser-manager-sidebar-description = Open Browser Manager Sidebar if the Web Panel of Browser Manager Sidebar is loaded
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Close BMS
gf-floorp-close-browser-manager-sidebar-description = Close Browser Manager Sidebar
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Toggle BMS
gf-floorp-show-browser-manager-sidebar-description = Toggle Browser Manager Sidebar
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Hide Status Bar
gf-floorp-hide-statusbar-description = Hide Status Bar
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Toggle Status Bar
gf-floorp-show-statusbar-description = Show or Hide Status Bar
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Open selected add-on Sidebar
gf-floorp-open-extension-sidebar-description = Open selected add-on on the Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id = Add-on of Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id-description = The extension of the add-on open of sidebar
gf-floorp-open-extension-sidebar-settings-list-default = Please select add-on
gf-floorp-open-extension-sidebar-settings-list-unknwon = Unknown add-on
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Oppdateringer funnet!
update-portable-notification-found-message = Downloading updates...
update-portable-notification-ready-title = Klar for oppdatering!
update-portable-notification-ready-message = { -brand-short-name } will be updated on the next launch.
update-portable-notification-success-title = Update succeeded!
update-portable-notification-success-message = Update succeeded! Hope you enjoy the new version of { -brand-short-name }!
update-portable-notification-failed-title = Oppdateringen mislyktes.
update-portable-notification-failed-redirector-message = Update failed. Restarting your browser may solve this problem.
update-portable-notification-failed-prepare-message = Kunne ikke forberede oppdateringen.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Portabel oppdatering
floorp-update-application-auto-enabled-option = 
    .label = Automatically check for updates to { -brand-short-name } portable. (Recommended)
##################################################################### Open link in external ###############################################################
openInExternal-title = Åpne i ekstern nettleser
open-link-in-external-enabled-option = 
    .label = Enable the "Open in external browser" feature
open-link-in-external-select-browser-option = Choose what browser will be opened
open-link-in-external-select-browser-option-default = 
    .label = Standard nettleser
open-link-in-external-tab-context-menu = Åpne i ekstern nettleser
open-link-in-external-tab-dialog-title-error = En feil har oppstått:
open-link-in-external-tab-dialog-message-default-browser-not-found = Default browser was not found or is not configured.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Den valgte nettleseren eksisterer ikke.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Ny
memo-title-input-placeholder = Skriv en tittel her
memo-input-placeholder = Write or paste a memo here
delete-memo = Slett
save-memo = Lagre
memo-welcome-title = Velkommen!
memo-first-tip = Welcome to { -brand-short-name } Notes! Here are some instructions on how to use it!
memo-second-tip = { -brand-short-name } Notes is a notepad that lets you store multiple notes that sync across devices. To enable synchronization, you need to sign in to { -brand-short-name } with your Firefox account.
memo-third-tip = { -brand-short-name } Notes will be saved in your { -brand-short-name } settings and synchronized across devices using Firefox Sync. Firefox Sync encrypts the contents of the sync with your Firefox account password, so no one but you know its contents.
memo-import-data-tip = Firefox Sync is not a backup service. We recommend you to create backups.
memo-new-title = Nytt notat
chage-view-mode = Toggle View/Edit Mode
readonly-mode = Frakoblet (skrivebeskyttet)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Ablaze brukerstøtte
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Tøm nedlastinger
    .accesskey = D
    .tooltiptext = Tøm nedlastinger
floorp-show-all-downloads = 
    .label = Vis alle nedlastninger
    .accesskey = S
    .tooltiptext = Vis alle nedlastninger
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Opprett nytt arbeidsområde...
    .tooltiptext = Opprett et nytt arbeidsområde
workspaces-manage-workspaces-button = 
    .label = Manage Workspaces...
    .tooltiptext = Manage your Workspaces
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Omdøp arbeidsområde
    .accesskey = R
delete-this-workspace = 
    .label = Slett arbeidsområde
    .accesskey = D
manage-this-workspaces = 
    .label = Manage Workspaces...
    .accesskey = M
workspace-new-default-name = Nytt arbeidsområde
workspace-default-name = Standard
move-tab-another-workspace = 
    .label = Move to another Workspace
rename-workspace-prompt-title = Omdøp arbeidsområde
rename-workspace-prompt-text = Enter Workspace Name. Most characters and symbols can be used.
workspaces-toolbar-button = Arbeidsområder
    .label = Arbeidsområder
    .tooltiptext = Velg et arbeidsområde...

## Preferences

enable-workspaces = 
    .label = Enable Workspaces
    .tooltiptext = Enable Workspaces
workspace-notice = Workspaces will not work with this settings enabled unless the workspaces's button is placed on the toolbar. Use this setting if you want to disable Workspaces completely.
enable-workspaces-with-experimental = 
    .label = Enable Workspaces (Experimental)
    .tooltiptext = Enable Workspaces (Experimental)
workspace-warning = Workspaces cannot be used with Tab Group add-ons. If you want to use Tab Group add-ons, please disable Workspaces and restart { -brand-short-name }.
category-workspaces = 
    .label = Arbeidsområder
    .tooltiptext = Arbeidsområder
pane-workspaces-title = Arbeidsområder
floorp-workspaces-title = { -brand-short-name } Workspaces
floorp-workspace-settings-button = Innstillinger for arbeidsområder...
floorp-preferences-label = Innstillingar
floorp-extensions-label = Utvidelser
floorp-private-label = Privat
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = Manage Workspace on Browser Manager Sidebar
show-workspace-name-option = 
    .label = Show Workspace Name on Tab Bar's Workspace Button
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Share Mode
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Logg inn på Firefox-kontoen din
welcome-to-floorp = Velkommen til { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Ready to dive in?
welcome-skip-to-start-browsing = Skip to Start Browsing
welcome-select-preferences-template = Vel ein mal
welcome-minimum-template = Enkelt
welcome-enable-basic-features = Enable basic features and settings for a simple experience.
welcome-medium-template = Standard
welcome-enable-some-features = Enable additional features and settings for a better experience.
welcome-maximum-template = Avansert
welcome-enable-most-of-features = Enable advanced features and settings. Recommended for experienced users.
welcome-go-next-setup = Neste
welcome-select-browser-design = Velg et nettleser-design
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Lepton Original Design
welcome-design-photon-name = Lepton Photon Design
welcome-design-ProtonFix-name = Lepton ProtonFix Design
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Firefox Proton design
welcome-import-data = Import Your Browser Data
welcome-import-data-description = Quick setup! Import your bookmarks, passwords, and more from your old browser. Firefox users can import data from Firefox Sync.
welcome-import-data-button = Importer data...
welcome-import-data-skip = Hopp over import
welcome-select-button = Velg
welcome-finish-setup = Konfigurering fullført!
welcome-finish-setup-description = You're all set! Other features like Vertical Tabs & Workspaces can be found in { -brand-short-name }'s Settings. Enjoy { -brand-short-name }!
welcomet-finish-setup = Start surfing på nettet
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Hurtigtaster
    .tooltiptext = Hurtigtaster
category-CSK-title = Hurtigtaster
shortcutkey-customize = 
    .title = Hurtigtaster
select-shortcutkeyAction = Velg en handling som skal utløses
shortcutkey-customize-key-list-placeholder = Your keyboard shortcut will appear here
shortcut-key-label = Keyboard Shortcut
start-input-button-listen = Begynn å lytte
end-input-button-listen = Avslutt lytting
shortcut-key-description = Click "Start Listening" and enter your new keyboard shortcut for this action. Multiple keys can be used; however, keyboard shortcuts will not work if already assigned to other actions.
floorp-custom-actions-open-new-tab = Åpne en ny fane
    .label = Åpne en ny fane
floorp-custom-actions-close-tab = Lukk nåværende fane
    .label = Lukk nåværende fane
floorp-custom-actions-open-new-window = Åpne et nytt vindu
    .label = Åpne et nytt vindu
floorp-custom-actions-open-new-private-window = Åpne et nytt privat vindu
    .label = Åpne et nytt privat vindu
floorp-custom-actions-close-window = Lukk nåværende fane
    .label = Lukk nåværende vindu
floorp-custom-actions-restore-last-session = Gjenopprett siste økt
    .label = Restore the last session
floorp-custom-actions-restore-last-window = Restore the last window
    .label = Restore the last window
floorp-custom-actions-show-next-tab = Vis neste fane
    .label = Vis neste fane
floorp-custom-actions-show-previous-tab = Vis forrige fane
    .label = Vis forrige fane
floorp-custom-actions-show-all-tabs-panel = Show all tabs panel
    .label = Show the tabs list
floorp-custom-actions-send-with-mail = Send med e-post
    .label = Send med e-post
floorp-custom-actions-save-page = Lagre siden
    .label = Lagre siden
floorp-custom-actions-print-page = Skriv ut side
    .label = Skriv ut side
floorp-custom-actions-mute-current-tab = Toggle mute/unmute current tab
    .label = Toggle mute/unmute current tab
floorp-custom-actions-toggle-bookmark-toolbar = Toggle bookmark toolbar
    .label = Toggle Bookmarks Toolbar
floorp-custom-actions-show-source-of-page = Show source of page
    .label = Open Page Source
floorp-custom-actions-show-page-info = Show page info
    .label = Open Page Info
floorp-custom-actions-zoom-in = Zoom inn
    .label = Zoom inn
floorp-custom-actions-zoom-out = Zoom ut
    .label = Zoom ut
floorp-custom-actions-reset-zoom = Nullstill zoom
    .label = Nullstill zoom
floorp-custom-actions-back = Tilbake
    .label = Tilbake
floorp-custom-actions-forward = Frem
    .label = Frem
floorp-custom-actions-reload = Last inn på nytt
    .label = Last inn på nytt
floorp-custom-actions-stop = Stopp
    .label = Stopp
floorp-custom-actions-force-reload = Tving omstart
    .label = Tving omstart
floorp-custom-actions-search-in-this-page = Søk på denne siden
    .label = Søk i side
floorp-custom-actions-show-next-search-result = Show next search word in this page result
    .label = Next "Find in page" result
floorp-custom-actions-show-previous-search-result = Show previous search word in this page result
    .label = Previous "Find in page" result
floorp-custom-actions-search-the-web = Søk på internett
    .label = Søk på internett
floorp-custom-actions-open-migration-wizard = Open migration wizard
    .label = Open migration wizard
floorp-custom-actions-quit-from-application = Avslutt applikasjonen
    .label = Avslutt { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Tilpass verktøylinjen
    .label = Åpne Tilpass { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Gå til offline-modus
    .label = Gå til offline-modus
floorp-custom-actions-open-screen-capture = Open screen capture tool
    .label = Ta et skjermbilde
floorp-custom-actions-show-pip = Vis bilde i bilde
    .label = Vis bilde-i-bilde
floorp-custom-actions-bookmark-this-page = Bokmerk denne siden
    .label = Bokmerk denne siden
floorp-custom-actions-open-bookmarks-sidebar = Open bookmarks sidebar
    .label = Open Bookmarks sidebar
floorp-custom-actions-open-bookmark-add-tool = Open bookmark add tool
    .label = Legg til bokmerke
floorp-custom-actions-open-bookmark-add-toolbar = Open "Add a new bookmark" pop-up window
    .label = Add to Bookmarks Toolbar
floorp-custom-actions-open-bookmarks-manager = Åpne bokmerkebehandling
    .label = Åpne bokmerkebehandling
floorp-custom-actions-show-bookmark-toolbar = Toggle bookmark toolbar
    .label = Toggle Bookmarks Toolbar
floorp-custom-actions-open-general-preferences = Åpne generelle innstillinger
    .label = Åpne generelle innstillinger
floorp-custom-actions-open-privacy-preferences = Åpne personverninnstillinger
    .label = Åpne personverninnstillinger
floorp-custom-actions-open-workspaces-preferences = Open Workspaces preferences
    .label = Open Workspaces Preferences
floorp-custom-actions-open-containers-preferences = Open containers preferences
    .label = Open Containers Preferences
floorp-custom-actions-open-search-preferences = Open search preferences
    .label = Open Search Preferences
floorp-custom-actions-open-sync-preferences = Open sync preferences
    .label = Open Sync Preferences
floorp-custom-actions-open-task-manager = Åpne oppgavebehandling
    .label = Open { -brand-short-name }'s Task Manager
floorp-custom-actions-open-home-page = Open { -brand-short-name }'s home page
    .label = Open { -brand-short-name }'s homepage
floorp-custom-actions-open-addons-manager = Open add-ons and themes
    .label = Open Add-ons and themes
floorp-custom-actions-forget-history = Glem historikk
    .label = Glem historikk
floorp-custom-actions-quick-forget-history = Quick forget history
    .label = Quick forget history
floorp-custom-actions-clear-recent-history = Tøm nylig historie
    .label = Tøm nylig historie
floorp-custom-actions-search-history = Søk i historikk
    .label = Søk i historikk
floorp-custom-actions-manage-history = Administrer historikk
    .label = Behandle historikk
floorp-custom-actions-open-downloads = Åpne nedlastinger
    .label = Åpne nedlastinger
floorp-custom-actions-show-bms = Toggle browser manager sidebar
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = Show bookmark sidebar
    .label = Show Bookmarks Sidebar
floorp-custom-actions-show-history-sidebar = Show history sidebar
    .label = Show History Sidebar
floorp-custom-actions-show-synced-tabs-sidebar = Show synced tabs sidebar
    .label = Show Synced Tabs Sidebar
floorp-custom-actions-reverse-sidebar = Reverse sidebar position
    .label = Reverse sidebar position
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = Toggle sidebar
    .label = Toggle sidebar
floorp-custom-actions-toggle-sidebar = Toggle sidebar
    .label = Toggle sidebar
floorp-custom-actions-open-previous-workspace = Åpne forrige arbeidsområde
    .label = Åpne forrige arbeidsområde
floorp-custom-actions-open-next-workspace = Åpne neste arbeidsområde
    .label = Åpne neste arbeidsområde
floorp-custom-actions-show-panel-1 = Toggle panel 1
    .label = Toggle panel 1
floorp-custom-actions-show-panel-2 = Toggle panel 2
    .label = Toggle panel 2
floorp-custom-actions-show-panel-3 = Toggle panel 3
    .label = Toggle panel 3
floorp-custom-actions-show-panel-4 = Skru av/på panel 4
    .label = Skru av/på panel 4
floorp-custom-actions-show-panel-5 = Skru av/på panel 5
    .label = Skru av/på panel 5
floorp-custom-actions-show-panel-6 = Skru av/på panel 6
    .label = Skru av/på panel 6
floorp-custom-actions-show-panel-7 = Skru av/på panel 7
    .label = Skru av/på panel 7
floorp-custom-actions-show-panel-8 = Skru av/på panel 8
    .label = Skru av/på panel 8
floorp-custom-actions-show-panel-9 = Skru av/på panel 9
    .label = Skru av/på panel 9
floorp-custom-actions-show-panel-10 = Skru av/på panel 10
    .label = Skru av/på panel 10
floorp-custom-actions-open-split-view-on-left = Open current tab on left in split view
    .label = Open current tab on left in split view
floorp-custom-actions-open-split-view-on-right = Open current tab on right in split view
    .label = Open current tab on right in split view
floorp-custom-actions-close-split-view = Lukk splittvisning
    .label = Lukk splittvisning
floorp-custom-actions-custom-action-1 = Egendefinert handling 1
    .label = Egendefinert handling 1
floorp-custom-actions-custom-action-2 = Egendefinert handling 2
    .label = Egendefinert handling 2
floorp-custom-actions-custom-action-3 = Egendefinert handling 3
    .label = Egendefinert handling 3
floorp-custom-actions-custom-action-4 = Egendefinert handling 4
    .label = Egendefinert handling 4
floorp-custom-actions-custom-action-5 = Egendefinert handling 5
    .label = Egendefinert handling 5
floorp-custom-actions-rest-mode = Aktiver hvilemodus
    .label = Aktiver hvilemodus
floorp-custom-actions-hide-user-interface = Veksle brukergrensesnitt
    .label = Veksle brukergrensesnitt
floorp-custom-actions-toggle-navigation-panel = Vis/skjul navigasjonspanel
    .label = Vis/skjul navigasjonspanel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Start
    .tooltiptext = Start { -brand-short-name } med denne profilen
floorp-profiles-in-use = Denne profilen er i bruk.
floorp-profiles-title = Profiler
floorp-profile-manager = Profile Manager
floorp-profiles-create = Opprett Profil
floorp-profile = Profil
    .label = Profile Manager
    .tooltiptext = Open Profile Manager
fxa-not-signed-in = Ikke pålogget
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privat
floorp-toggle-private-container = 
    .label = Reopen in Private/No Container
    .accesskey = P
open-in_private-container = 
    .label = Open in New Tab with Private Container
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Open in Split View
floorp-split-view-fixed-menu = 
    .label = Split this Tab in a Tab without Split View
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Remove Split View
split-view-title = Split View Settings
split-view-position = Plassering
split-view-flex-type = Flex Type
split-view-position-top = Top Side
split-view-position-left = Standard
split-view-position-right = Omvendt
split-view-flex-column = Vertikal
split-view-flex-row = Horizontal
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Skann QR-kode med telefonen din
qrcode-generate-page-action = 
    .tooltiptext = Share this page with your phone
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Unified Extensions Button
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Installer app
    .tooltiptext = Installer dette nettstedet som en app
ssb-page-action-title = Installer app
ssb-app-open-button = 
    .label = Åpne i App
ssb-app-install-button = 
    .label = Installer
ssb-app-cancel-button = 
    .label = Avbryt
floorp-open-manage-ssb-page = 
    .label = Manage installed Web Apps
appmenuitem-webapps = 
    .label = Web-apper
appmenu-open-installed-apps-subheader = Open installed web apps
appmenuitem-install-current-page = 
    .label = Install this site as an app
appmenuitem-open-current-page = 
    .label = Open this site on installed app
appmenuitem-contextmenu-open-app = 
    .label = Åpne denne appen
appmenuitem-contextmenu-uninstall-app = 
    .label = Avinstaller denne appen

## Preferences

category-ssb = 
    .label = Web-apper
    .tooltiptext = Web-apper
category-ssb-title = Web-apper
floorp-ssb-title = Web-apper
floorp-ssb-description = Web Apps are websites that can be installed as apps. They can be launched from { -brand-short-name }'s menu panel or the Windows Start menu.
ssb-preferences = Web Apps Settings
floorp-enable-ssb = 
    .label = Enable Web Apps
floorp-enable-ssb-with-experimental = 
    .label = Enable Web Apps (Experimental)
floorp-enable-ssb-description = This feature is experimental on Mac and Linux. It is recommended to enable this feature on Windows.
floorp-disable-toolbars = 
    .label = Disable toolbars on Web Apps Window
floorp-disable-toolbars-description = This setting will hide all extensions and toolbars on Web Apps Window.
ssb-installed-list-title = Installerte nettapplikasjoner
ssb-uninstall-title = Avinstaller Web App
ssb-uninstall-message = Are you sure you want to uninstall this Web App from { -brand-short-name }?
ssb-uninstall-button = 
    .label = Avinstaller
ssb-uninstall-cancel = Avbryt
######################################################################### Download Notification ###############################################################
floorp-started-download = Nedlasting startet
floorp-finished-download = Nedlasting fullført
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } is up to date!
floorp-notificationContent-latest = { -brand-short-name } is up to date. You are using the latest version of { -brand-short-name }.
floorp-notificationTitle = New version of { -brand-short-name } is available!
floorp-notificationContent = Click to download the latest version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = W
