# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> — это один из отечественных браузеров, разработанных в Японии. Он основан на Firefox и продолжает развиваться под руководством <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, чтобы сделать Интернет лучше. Хотите помочь? <label data-l10n-name="helpus-donateLink">Сделайте пожертвование</label>
icon-creator = Создатели иконок: <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> и <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Список <label data-l10n-name="about-contributor">контрибьюторов и разработчиков</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Дизайн
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Для применения изменений требуется перезапуск
tab-width = Минимальная ширина вкладок
preferences-tabs-newtab-position = Позиция новой вкладки
open-new-tab-use-default = 
    .label = Открывать новые вкладки по умолчанию
open-new-tab-at-the-end = 
    .label = Открывать новые вкладки в конце панели вкладок
open-new-tab-next-to-current = 
    .label = Открывать новые вкладки рядом с текущей вкладкой
multirow-tabs-limit = 
    .label = Включить ограничение строк для многострочных вкладок
multirow-tabs-newtab = 
    .label = Поместить кнопку «Открыть новую вкладку» в конце нижней строки вкладок
multirow-tabs-value = Количество строк при включённых многострочных вкладках
enable-tab-sleep = 
    .label = Включить спящие вкладки
tab-sleep-timeout-minutes-value = Вкладки перейдут в спящий режим после неактивности в течении (минуты)
tab-sleep-settings-button = Настройки...
tab-sleep-settings-dialog-title = 
    .title = Настройки спящих вкладок
tab-sleep-settings-dialog-excludehosts-label = Список исключений
tab-sleep-settings-dialog-excludehosts-label-2 = Введите одно исключение на строку.
tab-sleep-tab-context-menu-excludetab = Держать вкладки пробуждёнными
enable-tab-scroll-change = 
    .label = Переключать вкладки с помощью прокрутки
enable-tab-scroll-reverse = 
    .label = Обратное направление прокрутки вкладок
enable-tab-scroll-wrap = 
    .label = Переносить прокручивающиеся вкладки на край экрана
enable-double-click-block = 
    .label = Закрыть вкладки двойным щелчком
enable-show-pinned-tabs-title = 
    .label = Показывать название закрепленных вкладок
tabbar-preference = Панель вкладок
tab-normal-mode = 
    .label = По умолчанию
hide-horizontality-tabs = 
    .label = Скрывать вкладки на горизонтальной панели вкладок
verticalTab-setting = 
    .label = Оптимизировать браузер для вертикальной панели вкладок
move-tabbar-position = 
    .label = Отображать панель вкладок под панелью инструментов
tabbar-on-bottom = 
    .label = Отображение панели вкладок в нижней части окна
tabbar-favicon-color = 
    .label = Использовать цвет иконки сайта для цвета фона панели вкладок
tabbar-style-preference = Стиль панели вкладок
horizontal-tabbar = 
    .label = Горизонтальная панель вкладок
tabbar-style-description = Для применения этой настройки требуется перезапуск { -brand-short-name }.
multirow-tabbar = 
    .label = Многострочная панель вкладок
vertical-tabbar = 
    .label = Вертикальная панель вкладок (экспериментальная)
native-vertical-tab-show-right = 
    .label = Отображать вертикальную панель вкладок в правой части окна
native-vertical-tab-show-padding = 
    .label = Включить отступ сверху
hover-vertical-tab = 
    .label = Свернуть вертикальную панель вкладок
floorp-show-vertical-tab-newtab-button = 
    .label = Показывать кнопку "Открыть новую вкладку" на вертикальной панели вкладок
floorp-show-vertical-tab-scrollbar = 
    .label = Показывать полосу прокрутки на вертикальной панели вкладок
TST = Tree Style Tab
about-TST = Tree Style Tab - это популярное дополнение, позволяющее отображать вкладки в виде древовидной структуры. Это дополнение уже предварительно интегрировано в { -brand-short-name }. Для активации дополнения в { -brand-short-name } потребуется его установка.
treestyletab-Settings = 
    .label = Свернуть Tree Style Tab
sidebar-reverse-position-toolbar = Отображать боковые панели с противоположной стороны
bookmarks-bar-settings = Панель закладок (одновременно можно использовать только одну опцию)
bookmarks-focus-mode = 
    .label = Скрывать панель закладок при отсутствии наведения курсора на панель навигации
bookmarks-bottom-mode = 
    .label = Отображать панель закладок в нижней части { -brand-short-name }
navbar-settings = Панель навигации
show-nav-bar-bottom = 
    .label = Показать панель инструментов в нижней части { -brand-short-name } (экспериментально)
material-effect = 
    .label = Разрешить Mica for Everyone изменять дизайн браузера (устарело)
disable-extension-check-compatibility-option = 
    .label = Не проверять совместимость с дополнениями (устаревшее)
other-preference = Другие настройки
enable-userscript = 
    .label = Включить устаревшие компоненты (устаревшее)
about-userscript = Включение этой функции может привести к неожиданным ошибкам или фатальным сбоям.
search-positon-top = 
    .label = Отображение панели поиска в верхней части страницы
allow-auto-restart = 
    .label = Автоматический перезапуск при изменении настроек, требующих перезапуска
disable-fullscreen-notification = 
    .label = Не отображать уведомление при входе в полноэкранный режим

## Browser Theme

system-color-settings = Для этого дизайна доступна как светлая, так и темная тема.
preferences-theme-appearance-header = Настройки темы оформления
system-theme-dark = 
    .label = Тёмная тема
system-theme-light = 
    .label = Светлая тема
system-theme-auto = 
    .label = Автоматический выбор темы

## User interface preferences

ui-preference = Внешний вид браузера
preferences-browser-appearance-description = Вы можете выбрать один из замечательных дизайнов { -brand-short-name }, написанных сторонними разработчиками. Некоторые дизайны могут быть несовместимы с вашей конфигурацией.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (устаревший)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (устаревший)
floorp-gnomeUI = 
    .label = Тема GNOME (устаревшая)

## Download Manager

download-notification-preferences = Настройки уведомлений о загрузке
start-always-notify = 
    .label = Уведомлять только в начале загрузки
finish-always-notify = 
    .label = Уведомлять только при завершении загрузки
always-notify = 
    .label = Уведомлять при запуске и завершении загрузки
do-not-notify = 
    .label = Отключить уведомления о загрузках

## Sidebar

profiles-button-label = Управление профилями
floorp-help-button-label = Поддержка { -brand-short-name }
appmenuitem-reboot = 
    .label = Перезапустить

## UserAgent

userAgent-preference = Пользовательский агент (устаревшее)
default-useragent-mode = 
    .label = Использовать пользовательский агент Firefox (по умолчанию)
windows-chrome-useragent-mode = 
    .label = Изменить пользовательский агент на Chrome для Windows
macOS-chrome-useragent-mode = 
    .label = Изменить пользовательский агент на Chrome для macOS
linux-chrome-useragent-mode = 
    .label = Изменить пользовательский агент на Chrome для Linux
mobile-chrome-useragent-mode = 
    .label = Изменить пользовательский агент на Chrome для iOS
use-custom-useragent-mode = 
    .label = Использовать сторонний пользовательский агент

## DMR UI

download-mgr-UI = 
    .label = Включить менеджер загрузок SimpleUI
downloading-red-color = 
    .label = Выделять иконку менеджера загрузок красным цветом во время загрузки
sidebar-preferences = Боковая панель
bsb-preferences = Настройки боковой панели
view-sidebar2-right = 
    .label = Отображать боковую панель справа
enable-sidebar2 = 
    .label = Включить боковую панель
visible-bms = 
    .label = Включить боковую панель
hide-bms-to-unload-panel = 
    .label = Выгружать панель при её скрытии
enable-addons-in-sidebar2-with-experimental = 
    .label = Включить скрипты расширений в боковой панели менеджера браузера (экспериментально)
enable-addons-in-sidebar2 = 
    .label = Включить скрипты расширений в боковой панели менеджера браузера
sidebar2-enable-addons-desc = Если эта настройка включена, расширения, блокирующие рекламу, и другие расширения будут работать в боковой панели. Однако не все расширения будут работать.
custom-URL-option = Задать URL-адреса веб-панели
set-custom-URL-button = 
    .label = Задать URL...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Боковая панель
bsb-context = Использовать контейнер
bsb-userAgent-label = 
    .label = Изменить пользовательский агент на мобильную версию
bsb-width = Ширина (0 - глобальное значение)
bsb-page = Страница для открытия
bsb-add = Добавить веб-панель в боковую панель браузера
bsb-setting = Настройки веб-панели
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Веб-сайт
sidebar2-pref-delete = 
    .label = Удалить
sidebar2-pref-setting = 
    .label = Настройки
sidebar2-global-width = Глобальное значение ширины веб-панели
use-icon-provider-option = Используемый провайдер иконок
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Яндекс (доступно в Китае)
use-icon-provider-option-hatena = 
    .label = Яндекс (доступен в Китае)
memory-and-performance = Память и производительность
min-memory = 
    .label = Минимальное использование памяти (низкая производительность)
balance-memory = 
    .label = Баланс между использованием памяти и производительностью
max-memory = 
    .label = Наилучшая производительность (высокое потребление памяти)
delete-border-and-roundup-option = 
    .label = Округлить углы страниц

## DualTheme

dualtheme-enable = 
    .label = Включить двойную тему
newtab-background = Фоновое изображение на домашней странице { -brand-short-name }
newtab-background-random-image = 
    .label = Случайное изображение с Unsplash
newtab-background-gradation = 
    .label = Градиент
newtab-background-not-background = 
    .label = Отключить фоновое изображение
newtab-background-selected-image = 
    .label = Пользовательская папка...
newtab-background-selected-one-image = 
    .label = Пользовательское изображение...
newtab-background-folder = Использовать изображения из выбранной папки:
newtab-background-image = Использовать изображение:
newtab-choose-image = Выберите изображение...
newtab-background-folder-reload = 
    .label = Перезагрузить изображения
newtab-background-folder-default = 
    .label = Сбросить настройки
newtab-background-folder-open = 
    .label = Открыть папку
newtab-background-folder-choose = Выберите папку с изображениями...
newtab-background-image-choose = Выберите изображение...
newtab-background-extensions = Использовать изображения с этими расширениями (через ",")
disable-blur-on-newtab = 
    .label = Отключить эффект размытия на домашней странице { -brand-short-name }
disable-releasenote-on-newtab = 
    .label = Отключите заметки о выпуске и ссылки поддержки на домашней странице { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Отключить указание авторства изображений (Unsplash) на главной странице { -brand-short-name }

## Lepton Preferences

about-lepton = Настройка { -brand-short-name } с помощью Lepton
lepton-preference-button = 
    .label = Настройки Lepton...
    .accesskey = L
lepton-header = Настройки Lepton
lepton-preference = Настройки Lepton
photon-mode = 
    .label = Использовать дизайн Photon
lepton-mode = 
    .label = Использовать дизайн Lepton
protonfix-mode = 
    .label = Использовать настроенный дизайн Proton
autohide-preference = Автоматически скрывать элементы браузера
floorp-lepton-enable-tab-autohide = 
    .label = Автоматически скрывать вкладки
floorp-lepton-enable-navbar-autohide = 
    .label = Автоматически скрывать панель инструментов
floorp-lepton-enable-sidebar-autohide = 
    .label = Автоматически скрывать боковую панель
floorp-lepton-enable-urlbar-autohide = 
    .label = Автоматически скрывать адресную строку
floorp-lepton-enable-back-button-autohide = 
    .label = Автоматически скрывать кнопку "Назад"
floorp-lepton-enable-forward-button-autohide = 
    .label = Автоматически скрывать кнопку "Вперёд"
floorp-lepton-enable-page-action-button-autohide = 
    .label = Автоматически скрывать кнопки на адресной строке
floorp-lepton-enable-toolbar-overlap = 
    .label = Отображать панель инструментов поверх содержимого сайта
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Автоматически скрывать панель инструментов при отображении содержимого «ltr»
hide-preference = Управление элементами браузера
floorp-lepton-enable-tab_icon-hide = 
    .label = Скрыть значки вкладок
floorp-lepton-enable-tabbar-hide = 
    .label = Скрыть панель вкладок
floorp-lepton-enable-navbar-hide = 
    .label = Скрыть панель инструментов
floorp-lepton-enable-sidebar_header-hide = 
    .label = Скрыть заголовки боковой панели
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Скрыть значки адресной строки
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Скрыть значки панели закладок
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Скрыть надписи на панели закладок
floorp-lepton-enable-disabled_menu-hide = 
    .label = Скрыть отключенные пункты контекстного меню
floorp-lepton-disable-userChrome-icon = 
    .label = Отключить контекстное меню и значки меню панели Lepton
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Включить значки контекстного меню Lepton
positon-preferences = Настройки положения
floorp-lepton-enable-centered-tab = 
    .label = Центрировать метки на вкладках
floorp-lepton-enable-centered-urlbar = 
    .label = Центрировать текст в адресной строке
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Центрировать элементы панели закладок
urlbar-preferences = Адресная строка
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Переместить значки адресной строки в левую сторону
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = При наборе текста отображать кнопку «Перейти»
floorp-lepton-enable-always-show-page_action = 
    .label = Всегда показывать действия страницы в адресной строке
tabbar-preferences = Панель вкладок
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Панель вкладок в строке заголовка
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Объединить панель вкладок и панель инструментов
lepton-sidebar-preferences = Боковая панель
floorp-lepton-enable-overlap-sidebar = 
    .label = Отображать боковую панель поверх содержимого сайта
floorp-home-mode-choice-default = 
    .label = Домашняя страница { -brand-short-name } (по умолчанию)
floorp-home-prefs-content-header = Содержимое стартовой страницы { -brand-short-name }
floorp-home-prefs-content-description = Выберите содержимое, которое вы хотите видеть на главной странице { -brand-short-name }.

## Notes

floorp-notes = Заметки { -brand-short-name }
restore-from-backup = Восстановить заметки из резервной копии
enable-notes-sync = 
    .label = Включить синхронизацию заметок { -brand-short-name }
about-notes-backup-tips = { -brand-short-name } Notes использует Firefox Sync для синхронизации ваших заметок с другими устройствами. Если вы потеряете заметки, вы cможете восстановить их из резервной копии. При запуске { -brand-short-name } создается резервная копия.
notes-sync-description = Это может решить проблему потери содержимого из-за перезаписи заметок во время синхронизации.
backuped-time = Резервная копия создана в
notes-backup-option = Настройки резервного копирования
backup-option-button = Настройки резервного копирования...
restore-from-backup-prompt-title = Служба восстановления заметок { -brand-short-name }
restore-from-this-backup = Восстановить заметки до состояния, в котором они были в этой резервной копии?
restore-button = Восстановить

## user.js

header-userjs = user.js
userjs-customize = Настройка { -brand-short-name } с помощью user.js
about-userjs-customize = user.js - это файл конфигурации, позволяющий настраивать { -brand-short-name }. Файлы user.js загружаются из Интернета и заменяют текущий файл user.js. Перед продолжением работы создайте резервную копию текущего файла user.js. Конфигурация user.js будут автоматически применена после перезапуска { -brand-short-name }.
userjs-label = Список user.js
userjs-prompt = Применить этот user.js?
apply-userjs-attention = Применение нового user.js перезапишет ваш текущий файл user.js.
apply-userjs-attention2 = Пожалуйста, сделайте резервную копию текущего файла user.js, прежде чем продолжить.
userjs-button = Настройки user.js...
userjs-select-option = Выберите user.js для использования в { -brand-short-name }.
apply-userjs-button = Применить

## userjs Options

default-userjs-label = { -brand-short-name } Default
about-default-userjs = Телеметрия отключена. Хорошо сбалансированный { -brand-short-name } с различными включёнными надстройками.
Securefox-label = Yokoffing Peskyfox
about-Securefox = HTTPS-по умолчанию. Полная защита от кук с изоляцией сайтов. Расширенное сетевое разделение. Различные другие улучшения.
default-label = Yokoffing Default
about-default = Все необходимые настройки по умолчанию. Это ваш user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Значительно увеличивает скорость просмотра в Firefox. Поборитесь с Chrome на его территории!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Очищает новую вкладку, удаляет Pocket, восстанавливает компактный режим в качестве опции и останавливает уведомления веб-страниц, всплывающие окна и другие раздражающие элементы.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Получите плавную прокрутку, как в Edge, или выберите что-то более подходящее для вашего стиля.
select-workspace = Выберите рабочее пространство
workspace-select-icon = Выберите значок рабочего пространства
    .label = Выберите значок рабочего пространства
workspace-select-container = Выберите контейнер
    .label = Выберите контейнер
workspace-customize = 
    .title = Настроить рабочую область
floorp-no-workspace-container = 
    .label = Без контейнера
workspace-icon-article = 
    .label = Заметка
workspace-icon-book = 
    .label = Книга
workspace-icon-briefcase = 
    .label = Работа
workspace-icon-cart = 
    .label = Покупки
workspace-icon-chat = 
    .label = Чат
workspace-icon-chill = 
    .label = Личное
workspace-icon-circle = 
    .label = Круг
workspace-icon-compass = 
    .label = Компас
workspace-icon-code = 
    .label = Код
workspace-icon-dollar = 
    .label = Банк
workspace-icon-fence = 
    .label = Забор
workspace-icon-fingerprint = 
    .label = Личное
workspace-icon-food = 
    .label = Еда
workspace-icon-fruit = 
    .label = Фрукт
workspace-icon-game = 
    .label = Игра
workspace-icon-gear = 
    .label = Шестерёнка
workspace-icon-gift = 
    .label = Подарок
workspace-icon-key = 
    .label = Ключ
workspace-icon-lightning = 
    .label = Молния
workspace-icon-network = 
    .label = Интернет
workspace-icon-notes = 
    .label = Заметка
workspace-icon-paint = 
    .label = Краска
workspace-icon-photo = 
    .label = Фото
workspace-icon-pin = 
    .label = Булавка
workspace-icon-pet = 
    .label = Питомец
workspace-icon-question = 
    .label = Вопросительный знак
workspace-icon-smartphone = 
    .label = Смартфон
workspace-icon-star = 
    .label = Звезда
workspace-icon-tree = 
    .label = Дерево
workspace-icon-vacation = 
    .label = Отпуск
workspace-icon-love = 
    .label = Любовь
workspace-icon-moon = 
    .label = Луна
workspace-icon-music = 
    .label = Музыка
workspace-icon-user = 
    .label = Пользователь
# Custom Keyboard Shortcuts
floorp-CSK-title = Пользовательские сочетания клавиш
floorp-CSK-description = Настройте сочетания клавиш { -brand-short-name }. { -brand-short-name } предоставляет более 80 настраиваемых сочетаний клавиш! Дублированые сочетания клавиш не будут работать. Для применения этих настроек требуется перезапуск { -brand-short-name }.
disable-fx-actions = 
    .label = Отключить горячие клавиши Mozilla Firefox
customize-Action = 
    .label = Добавить горячую клавишу
remove-Action = 
    .label = Удалить горячую клавишу
CSK-reset-title = Сбросить горячие клавиши
CSK-reset-description = Сброс пользовательских горячих клавиш { -brand-short-name } по умолчанию.
CSK-reset-label = Сбросить горячие клавиши
CSK-reset-button = Сбросить настройки
CSK-manage-title = Управление сочетаниями клавиш
CSK-remove-shortcutkey = Сбросить горячую клавишу?
CSK-remove-shortcutkey-description = Вы уверены, что хотите удалить комбинацию клавиш?
CSK-restore-default = Сбросить настройки?
CSK-restore-default-description = Восстановить комбинации клавиш { -brand-short-name } по умолчанию? Текущие сочетания клавиш будут потеряны.
CSK-reboot-browser-label = Перезапустите { -brand-short-name } для применения этих настроек
CSK-reboot-browser-button = Перезапустить { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Сочетание клавиш: { $key } и { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Текущее сочетание клавиш: { $key }.
CSK-keyborad-shortcut-is-changed = (Не применено)
floorp-custom-actions-tab-action = Действия вкладок
floorp-custom-actions-page-action = Действия страницы
floorp-custom-actions-visible-action = Видимые действия
floorp-custom-actions-search-action = Поисковые действия
floorp-custom-actions-tools-action = Действия Инструментов
floorp-custom-actions-bookmark-action = Действия с закладками
floorp-custom-actions-open-page-action = Действия на открытой странице
floorp-custom-actions-history-action = Действия истории
floorp-custom-actions-pip-action = Действия с режимом «картинка в картинке»
floorp-custom-actions-downloads-action = Действия загрузок
floorp-custom-actions-sidebar-action = Действия боковой панели
floorp-custom-actions-bms-action = Действия боковой панели
floorp-custom-actions-split-view-action = Действия при раздельном просмотре
floorp-custom-actions-workspaces-action = Действия рабочих пространств
floorp-custom-actions-custom-action = Пользовательские действия (экспериментально)

## Mouse Gestures

mouse-gesture = Жесты мышью
mouse-gesture-description = Gesturify должен быть установлены для использования жестов мыши с { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy - это расширение, которое добавляет жесты мыши в ваш браузер. Если { -brand-short-name } обнаружит установку этого дополнения, он добавит жесты в Gesturefy, которые доступны только в { -brand-short-name }. Кроме того, это дополнение может работать с новыми вкладками!
# Translate
TWS = Translate Web Pages
about-TWS = Переводите свою страницу в режиме реального времени с помощью Google или Yandex. Вы также можете перевести выделенный текст или всю страницу.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Центр приватности
block-more-tracker = Блокируйте больше рекламы и трекеров
block-tracker = Этот раздел содержит набор расширений, предназначенных для блокировки рекламы и трекеров
view-at-AMO = Подробнее на addons.mozilla.org
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin блокирует рекламу, трекеры и опасные сайты.
Facebook-Container = Facebook Container
about-Facebook-Container = Запретите Facebook следить за вами в Интернете. Расширение Facebook Container поможет вам взять под контроль и изолировать вашу веб-активность от Facebook.

## Fingerprinting

fingerprint-header = Защита от фингерпринтинга и утечки IP-адреса
block-fingerprint = Фингерпринтинг – это механизм отслеживания, который опирается на уникальные особенности вашего браузера и операционной системы. Этот раздел содержит настройки для дальнейшего усиления защиты помимо блокировки по умолчанию.
enable-firefox-fingerprint-protections = Включить надёжную защиту от фингерпринтинга
about-firefox-fingerprint-protection = Включение защиты в Floorp активирует принудительную светлую тему, отключает некоторые API и т.д. Некоторые сайты могут отображаться некорректно.
fingerprint-Protection = 
    .label = Защита от фингерпринтинга
html5-canvas-prompt-settings = 
    .label = Автоматически отклонять запросы на подтверждение доступа к данным изображения HTML5
canvas-prompt = Запрещает веб-сайтам использовать запрос на чтение холста, если это не разрешено вручную.
disable-webgl = 
    .label = Отключить WebGL
about-webgl = WebGL — это Javascript API, используемый для рендеринга графики, который может использоваться для идентификации GPU.
Canvas-Blocker = Canvas Blocker
about-CB = Это дополнение подменяет данные, используемые техниками фингерпринтинга.
WebRTC-connection = WebRTC - стандарт, обеспечивающий звонки в реальном времени. Если вы отключите эту настройку, вы не сможете использовать Discord и т.д.
WebRTC = 
    .label = Включить WebRTC соединение
################################################################### browser ###############################################################

rest-mode = Берём перерыв...
rest-mode-description = { -brand-short-name } остановлен. Нажмите OK или ENTER для возобновления работы.
Sidebar2 = 
    .label = Боковая панель
    .tooltiptext = Изменить видимость боковой панели
sidebar2-mute-and-unmute = 
    .label = Выкл/Вкл звук на этой панели
sidebar2-unload-panel = 
    .label = Выгрузить панель
sidebar2-change-ua-panel = 
    .label = Мобильный Пользовательский Агент
sidebar2-delete-panel = 
    .label = Удалить эту панель
sidebar2-change-zoom-level = 
    .label = Изменить масштаб
sidebar2-zoom-in = 
    .label = Приблизить
sidebar2-zoom-out = 
    .label = Отдалить
sidebar2-reset-zoom = 
    .label = Сбросить масштабирование
sidebar2-close-button = 
    .tooltiptext = Закрыть боковую панель
sidebar-back-button = 
    .tooltiptext = Назад
sidebar-forward-button = 
    .tooltiptext = Вперёд
sidebar-reload-button = 
    .tooltiptext = Reload
sidebar-go-index-button = 
    .tooltiptext = Перейти на главную страницу
sidebar-muteAndUnmute-button = 
    .tooltiptext = Выключить/включить звук боковой панели
sidebar2-browser-manager-sidebar = Управление браузером
show-browser-manager-sidebar = 
    .tooltiptext = Отображать боковую панель { sidebar2-browser-manager-sidebar }
sidebar2-bookmark-sidebar = Закладок
show-bookmark-sidebar = 
    .tooltiptext = Отображать боковую панель { sidebar2-bookmark-sidebar }
sidebar2-history-sidebar = Истории
show-history-sidebar = 
    .tooltiptext = Отображать боковую панель { sidebar2-history-sidebar }
sidebar2-download-sidebar = Загрузок
show-download-sidebar = 
    .tooltiptext = Отображать боковую панель { sidebar2-download-sidebar }
sidebar2-notes-sidebar = Заметок
show-notes-sidebar = 
    .tooltiptext = Отображать боковую панель { sidebar2-notes-sidebar }
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Дополнения и темы
sidebar2-hide-sidebar-button = 
    .tooltiptext = Закрыть боковую панель
sidebar-passwords-button = 
    .tooltiptext = Пароли
sidebar-preferences-button = 
    .tooltiptext = Настройки
sidebar-keepWidth-button = 
    .tooltiptext = Использовать текущую ширину на этой панели
sidebar2-keep-width-for-global = 
    .label = Установить текущий размер для всех веб-панелей, которые не имеют уникального размера
bsb-context-add = 
    .label = Добавить страницу на веб-панель...
bsb-context-link-add = 
    .label = Добавить ссылку на веб-панель...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Открыть папку с текущим профилем
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = С
css-menubar = 
    .label = CSS
    .accesskey = С
rebuild-css = 
    .label = Пересобрать CSS-файлы браузера
    .accesskey = R
make-browsercss-file = 
    .label = Создать CSS файл браузера
    .accesskey = M
open-css-folder = 
    .label = Открыть папку с CSS файлами
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Редактировать файл userChrome.css
edit-userContentCss-editor = 
    .label = Редактировать файл userContent.css
not-found-editor-path = Путь к редактору не найден
set-pref-description = Введите расположение CSS-редактора, который вы хотите использовать:
rebuild-complete = Пересборка завершена.
please-enter-filename = Введите имя файла.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Повторно открыть закрытую вкладку
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Включить в качестве подтемы
dual-theme-disable-addon-button = Отключить подтему
dual-theme-enabled-heading = Включено в качестве подтемы
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Строка состояния
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Открыть панель вкладок в стиле дерева
gf-floorp-open-tree-style-tab-description = Открыть панель вкладок в стиле дерева на боковой панели
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name } Открыть панель закладок
gf-floorp-open-bookmarks-sidebar-description = Открыть панель закладок на боковой панели
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Открыть панель истории
gf-floorp-open-history-sidebar-description = Открыть панель истории на боковой панели
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Открыть панель синхронизированных вкладок
gf-floorp-open-synctabs-sidebar-description = Открыть панель синхронизированных вкладок на боковой панели
gf-floorp-close-sidebar-name = [{ -brand-short-name } Закрыть боковую панель
gf-floorp-close-sidebar-description = Закрыть боковую панель
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Открыть боковую панель
gf-floorp-open-browser-manager-sidebar-description = Открыть боковую панель, если была загружена её веб-панель
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Закрыть боковую панель
gf-floorp-close-browser-manager-sidebar-description = Закрыть боковую панель
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Вкл/выкл боковую панель
gf-floorp-show-browser-manager-sidebar-description = Вкл/выкл боковую панель
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Скрыть строку состояния
gf-floorp-hide-statusbar-description = Скрыть строку состояния
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Вкл/выкл строку состояния
gf-floorp-show-statusbar-description = Отобразить или скрыть строку состояния
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Открыть выбранное дополнение на боковой панели
gf-floorp-open-extension-sidebar-description = Открыть выбранное дополнение на боковой панели
gf-floorp-open-extension-sidebar-settings-addons-id = Дополнение боковой панели
gf-floorp-open-extension-sidebar-settings-addons-id-description = Расширение дополнения, открытого на боковой панели
gf-floorp-open-extension-sidebar-settings-list-default = Пожалуйста, выберите дополнение
gf-floorp-open-extension-sidebar-settings-list-unknwon = Неизвестное дополнение
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Найдены обновления!
update-portable-notification-found-message = Загружаем обновления...
update-portable-notification-ready-title = Обновления готовы к установке!
update-portable-notification-ready-message = { -brand-short-name } будет обновлен при следующем запуске.
update-portable-notification-success-title = Обновление прошло успешно!
update-portable-notification-success-message = Обновление прошло успешно! Надеемся, вам понравится новая версия { -brand-short-name }!
update-portable-notification-failed-title = Не удалось установить обновление.
update-portable-notification-failed-redirector-message = Не удалось остановить обновления. Перезагрузка браузера может решить эту проблему.
update-portable-notification-failed-prepare-message = Не удалось подготовить обновление.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = Обновления { -brand-short-name } Portable
floorp-update-application-auto-enabled-option = 
    .label = Автоматически проверять наличие обновлений для { -brand-short-name } Portable. (Рекомендуется)
##################################################################### Open link in external ###############################################################
openInExternal-title = Открыть во внешнем браузере
open-link-in-external-enabled-option = 
    .label = Включить функцию "Открыть во внешнем браузере"
open-link-in-external-select-browser-option = Выберите, какой браузер будет открыт
open-link-in-external-select-browser-option-default = 
    .label = Браузер по умолчанию
open-link-in-external-tab-context-menu = Открыть в другом браузере
open-link-in-external-tab-dialog-title-error = Произошла ошибка:
open-link-in-external-tab-dialog-message-default-browser-not-found = Браузер по умолчанию не найден или не настроен.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Выбранный браузер не найден.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Новая заметка
memo-title-input-placeholder = Задайте заголовок
memo-input-placeholder = Введите или вставьте текст
delete-memo = Удалить
save-memo = Сохранить
memo-welcome-title = Добро пожаловать!
memo-first-tip = Добро пожаловать в заметки { -brand-short-name }! Вот несколько инструкций по их использованию!
memo-second-tip = Заметки { -brand-short-name } - это блокнот, позволяющий хранить множество заметок, которые синхронизируются между устройствами. Чтобы включить синхронизацию, необходимо войти в { -brand-short-name } с помощью учетной записи Firefox.
memo-third-tip = Заметки { -brand-short-name } будут сохранены в настройках { -brand-short-name } и синхронизированы между устройствами с помощью Firefox Sync. Firefox Sync шифрует содержимое синхронизации с паролем учетной записи Firefox, поэтому никто, кроме вас, не сможет прочитать их содержимое.
memo-import-data-tip = Firefox Sync не является службой резервного копирования. Рекомендуется создавать резервные копии.
memo-new-title = Новая заметка
chage-view-mode = Режим просмотра/редактирования
readonly-mode = Оффлайн (только для чтения)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Поддержка Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Очистить загрузки
    .accesskey = D
    .tooltiptext = Очистить загрузки
floorp-show-all-downloads = 
    .label = Отобразить все загрузки
    .accesskey = S
    .tooltiptext = Отобразить все загрузки
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Создать новое рабочее пространство...
    .tooltiptext = Создать новое рабочее пространство
workspaces-manage-workspaces-button = 
    .label = Управление рабочими пространствами...
    .tooltiptext = Управляйте вашими рабочими пространствами
reorder-this-workspace-to-up = 
    .label = Переместить рабочее пространство вверх
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Переместить рабочее пространство вниз
    .accesskey = A
rename-this-workspace = 
    .label = Переименовать рабочее пространство
    .accesskey = R
delete-this-workspace = 
    .label = Удалить рабочее пространство
    .accesskey = D
manage-this-workspaces = 
    .label = Управление рабочими пространствами...
    .accesskey = M
workspace-new-default-name = Новое рабочее пространство
workspace-default-name = По умолчанию
move-tab-another-workspace = 
    .label = Переместить в другое рабочее пространство
rename-workspace-prompt-title = Переименовать рабочее пространство
rename-workspace-prompt-text = Введите имя рабочего пространства. Большинство символов и знаков могут быть использованы.
workspaces-toolbar-button = Рабочие пространства
    .label = Рабочие пространства
    .tooltiptext = Выберите рабочее пространство...

## Preferences

enable-workspaces = 
    .label = Включить рабочие пространства
    .tooltiptext = Включить рабочие пространства
workspace-notice = Рабочие пространства не будут работать при включенной настройке, если кнопка рабочих пространств не размещена на панели инструментов. Используйте эту настройку, если хотите полностью отключить рабочие пространства.
enable-workspaces-with-experimental = 
    .label = Включить рабочие пространства (экспериментально)
    .tooltiptext = Включить рабочие пространства (экспериментально)
workspace-warning = Рабочие пространства не могут быть использованы с дополнением Tab Group. Если вы хотите использовать дополнение Tab Group, пожалуйста, отключите рабочие пространства и перезапустите { -brand-short-name }.
category-workspaces = 
    .label = Рабочие пространства
    .tooltiptext = Рабочие пространства
pane-workspaces-title = Рабочие пространства
floorp-workspaces-title = Рабочие пространства { -brand-short-name }
floorp-workspace-settings-button = Настройки рабочего пространства...
floorp-preferences-label = Настройки
floorp-extensions-label = Расширения
floorp-private-label = Приватный
change-to-close-workspace-popup-option = 
    .label = Закрыть всплывающее окно рабочих пространств при выборе рабочего пространства
manage-workspace-on-bms-option = 
    .label = Управление рабочими пространствами на боковой панели
show-workspace-name-option = 
    .label = Отображать название рабочего пространства на кнопке рабочего пространства
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Режим общего доступа
    .accesskey = Ы
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Вход в учетную запись Firefox
welcome-to-floorp = Добро пожаловать в { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } - это гибкий, многофункциональный браузер, поддерживающий различные пользовательские окружения и основанный на Firefox.
welcome-start-setup = Готовы приступить?
welcome-skip-to-start-browsing = Пропустить и начать просмотр
welcome-select-preferences-template = Выберите преднастройку
welcome-minimum-template = Базовый функционал
welcome-enable-basic-features = Активировать базовые функции и настройки.
welcome-medium-template = По умолчанию
welcome-enable-some-features = Активировать дополнительные функции и настройки.
welcome-maximum-template = Расширенный функционал
welcome-enable-most-of-features = Активировать расширенные функции и настройки. Рекомендуется для опытных пользователей.
welcome-go-next-setup = Дальше
welcome-select-browser-design = Выберите дизайн браузера
welcome-describe-browser-design = Вы можете выбрать один из замечательных сторонних дизайнов { -brand-short-name }. Дизайны для конкретной операционной системы также доступны в разделе "Настройки".
welcome-design-lepton-name = Lepton Original Design
welcome-design-photon-name = Lepton Photon Design
welcome-design-ProtonFix-name = Lepton ProtonFix Design
welcome-design-floorp-fluerial-name = Fluerial Design { -brand-short-name }
welcome-design-firefox-proton-name = Firefox Proton Design
welcome-import-data = Импортировать ваши данные
welcome-import-data-description = Быстрая настройка! Импортируйте свои закладки, пароли и многое другое из вашего старого браузера. Пользователи Firefox могут импортировать данные из Firefox Sync.
welcome-import-data-button = Импортировать данные...
welcome-import-data-skip = Пропустить импорт
welcome-select-button = Выбрать
welcome-finish-setup = Настройка завершена!
welcome-finish-setup-description = Всё готово! Другие возможности, такие как вертикальные вкладки и рабочие пространства, могут быть найдены в настройках { -brand-short-name }. Приятного использования!
welcomet-finish-setup = Начать просмотр
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Горячие клавиши
    .tooltiptext = Горячие клавиши
category-CSK-title = Горячие клавиши
shortcutkey-customize = 
    .title = Горячие клавиши
select-shortcutkeyAction = Выберите действие для горячей клавиши
shortcutkey-customize-key-list-placeholder = Здесь появятся ваши сочетания клавиш
shortcut-key-label = Горячая клавиша
start-input-button-listen = Начать прослушивание
end-input-button-listen = Остановить прослушивание
shortcut-key-description = Нажмите "Начать прослушивание" и нажмите комбинацию клавиш, которую вы хотите использовать для данного действия. Несколько клавиш могут быть использованы.
floorp-custom-actions-open-new-tab = Открыть новую вкладку
    .label = Открыть новую вкладку
floorp-custom-actions-close-tab = Закрыть текущую вкладку
    .label = Закрыть текущую вкладку
floorp-custom-actions-open-new-window = Открыть новое окно
    .label = Открыть новое окно
floorp-custom-actions-open-new-private-window = Открыть новое приватное окно
    .label = Открыть новое приватное окно
floorp-custom-actions-close-window = Закрыть текущее окно
    .label = Закрыть текущее окно
floorp-custom-actions-restore-last-session = Восстановить последнюю сессию
    .label = Восстановить последнюю сессию
floorp-custom-actions-restore-last-window = Восстановить последнее окно
    .label = Восстановить последнее окно
floorp-custom-actions-show-next-tab = Отобразить следующую вкладку
    .label = Показать следующую вкладку
floorp-custom-actions-show-previous-tab = Отобразить предыдущую вкладку
    .label = Показать предыдущую вкладку
floorp-custom-actions-show-all-tabs-panel = Отобразить панель всех вкладок
    .label = Отображать список вкладок
floorp-custom-actions-send-with-mail = Отправить по электронной почте
    .label = Отправить по электронной почте
floorp-custom-actions-save-page = Сохранить страницу
    .label = Сохранить страницу
floorp-custom-actions-print-page = Распечатать страницу
    .label = Распечатать страницу
floorp-custom-actions-mute-current-tab = Вкл/выкл звук текущей вкладки
    .label = Вкл/выкл звук текущей вкладки
floorp-custom-actions-toggle-bookmark-toolbar = Вкл/выкл панель закладок
    .label = Панель закладок
floorp-custom-actions-show-source-of-page = Показать исходник страницы
    .label = Отобразить информацию о странице
floorp-custom-actions-show-page-info = Отобразить информацию о странице
    .label = Отобразить информацию о странице
floorp-custom-actions-zoom-in = Приблизить
    .label = Приблизить
floorp-custom-actions-zoom-out = Отдалить
    .label = Отдалить
floorp-custom-actions-reset-zoom = Сбросить масштабирование
    .label = Сбросить масштаб
floorp-custom-actions-back = Назад
    .label = Назад
floorp-custom-actions-forward = Вперёд
    .label = Вперёд
floorp-custom-actions-reload = Reload
    .label = Перезагрузить
floorp-custom-actions-stop = Остановить
    .label = Остановить
floorp-custom-actions-force-reload = Принудительная перезагрузка
    .label = Принудительная перезагрузка
floorp-custom-actions-search-in-this-page = Поиск на этой странице
    .label = Найти на странице
floorp-custom-actions-show-next-search-result = Показывать следующее поисковое слово в результатах этой страницы
    .label = Следующий результат поиска по странице
floorp-custom-actions-show-previous-search-result = Показывать предыдущее поисковое слово в результатах этой страницы
    .label = Предыдущий результат поиска по странице
floorp-custom-actions-search-the-web = Поиск в Интернете
    .label = Поиск в интернете
floorp-custom-actions-open-migration-wizard = Открыть мастер миграции
    .label = Открыть мастер миграции
floorp-custom-actions-quit-from-application = Выйти из приложения
    .label = Выйти из { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Настройка панели инструментов
    .label = Открыть настройки { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Войти в режим оффлайн
    .label = Войти в режим оффлайн
floorp-custom-actions-open-screen-capture = Открыть инструмент захвата экрана
    .label = Сделать скриншот
floorp-custom-actions-show-pip = Отображать картинку в картинке
    .label = Отображать картинку в картинке
floorp-custom-actions-bookmark-this-page = Добавить страницу в закладки
    .label = Добавить страницу в закладки
floorp-custom-actions-open-bookmarks-sidebar = Открыть боковую панель закладок
    .label = Открыть боковую панель закладок
floorp-custom-actions-open-bookmark-add-tool = Открыть инструмент добавления закладок
    .label = Добавить закладку
floorp-custom-actions-open-bookmark-add-toolbar = Открыть всплывающее окно "Добавить новую закладку"
    .label = Добавить в панель закладок
floorp-custom-actions-open-bookmarks-manager = Открыть менеджер закладок
    .label = Открыть Менеджер закладок
floorp-custom-actions-show-bookmark-toolbar = Вкл/выкл панель закладок
    .label = Вкл/выкл панель закладок
floorp-custom-actions-open-general-preferences = Открыть общие настройки
    .label = Открыть общие настройки
floorp-custom-actions-open-privacy-preferences = Открыть настройки конфиденциальности
    .label = Открыть настройки конфиденциальности
floorp-custom-actions-open-workspaces-preferences = Открыть настройки рабочих пространств
    .label = Открыть настройки рабочих пространств
floorp-custom-actions-open-containers-preferences = Открыть настройки контейнеров
    .label = Открыть настройки контейнеров
floorp-custom-actions-open-search-preferences = Открыть настройки поиска
    .label = Открыть настройки поиска
floorp-custom-actions-open-sync-preferences = Открыть настройки синхронизации
    .label = Открыть настройки синхронизации
floorp-custom-actions-open-task-manager = Открыть диспетчер задач
    .label = Открыть диспетчер задач { -brand-short-name }
floorp-custom-actions-open-home-page = Открыть домашнюю страницу { -brand-short-name }
    .label = Открыть домашнюю страницу { -brand-short-name }
floorp-custom-actions-open-addons-manager = Открыть дополнения и темы
    .label = Открыть дополнения и темы
floorp-custom-actions-forget-history = Очистить историю
    .label = Очистить историю
floorp-custom-actions-quick-forget-history = Быстро очистить историю
    .label = Быстро очистить историю
floorp-custom-actions-clear-recent-history = Очистить недавнюю историю
    .label = Очистить недавнюю историю
floorp-custom-actions-search-history = История поиска
    .label = История поиска
floorp-custom-actions-manage-history = Управление историей
    .label = Управление историей
floorp-custom-actions-open-downloads = Открыть загрузки
    .label = Открыть загрузки
floorp-custom-actions-show-bms = Включить или выключить боковую панель
    .label = Включить или выключить боковую панель
floorp-custom-actions-show-current-panel = Включить или выключить текущую панель
    .label = Включить или выключить текущую панель
floorp-custom-actions-show-bookmark-sidebar = Отобразить боковую панель закладок
    .label = Показать боковую панель закладок
floorp-custom-actions-show-history-sidebar = Отобразить боковую панель истории
    .label = Отобразить боковую панель истории
floorp-custom-actions-show-synced-tabs-sidebar = Отобразить боковую панель синхронизированных вкладок
    .label = Отобразить боковую панель синхронизированных вкладок
floorp-custom-actions-reverse-sidebar = Обратное положение боковой панели
    .label = Обратное положение боковой панели
floorp-custom-actions-hide-sidebar = Скрыть боковую панель
    .label = Скрыть боковую панель
floorp-custom-actions-show-sidebar = Отобразить/скрыть боковую панель
    .label = Отобразить/скрыть боковую панель
floorp-custom-actions-toggle-sidebar = Отобразить/скрыть боковую панель
    .label = Отобразить/скрыть боковую панель
floorp-custom-actions-open-previous-workspace = Открыть предыдущее рабочее область
    .label = Открыть предыдущее рабочее пространство
floorp-custom-actions-open-next-workspace = Открыть следующее рабочее пространство
    .label = Открыть следующее рабочее пространство
floorp-custom-actions-show-panel-1 = Отобразить/скрыть панель 1
    .label = Отобразить/скрыть панель 1
floorp-custom-actions-show-panel-2 = Отобразить/скрыть панель 2
    .label = Отобразить/скрыть панель 2
floorp-custom-actions-show-panel-3 = Отобразить/скрыть панель 3
    .label = Отобразить/скрыть панель 3
floorp-custom-actions-show-panel-4 = Отобразить/скрыть панель 4
    .label = Отобразить/скрыть панель 4
floorp-custom-actions-show-panel-5 = Отобразить/скрыть панель 5
    .label = Отобразить/скрыть панель 5
floorp-custom-actions-show-panel-6 = Отобразить/скрыть панель 6
    .label = Отобразить/скрыть панель 6
floorp-custom-actions-show-panel-7 = Отобразить/скрыть панель 7
    .label = Отобразить/скрыть панель 7
floorp-custom-actions-show-panel-8 = Отобразить/скрыть панель 8
    .label = Отобразить/скрыть панель 8
floorp-custom-actions-show-panel-9 = Отобразить/скрыть панель 9
    .label = Отобразить/скрыть панель 9
floorp-custom-actions-show-panel-10 = Отобразить/скрыть панель 10
    .label = Отобразить/скрыть панель 10
floorp-custom-actions-open-split-view-on-left = Открыть текущую вкладку слева в режиме раздельного просмотра
    .label = Открыть текущую вкладку слева в режиме раздельного просмотра
floorp-custom-actions-open-split-view-on-right = Открыть текущую вкладку справа в режиме раздельного просмотра
    .label = Открыть текущую вкладку справа в режиме раздельного просмотра
floorp-custom-actions-close-split-view = Закрыть разделённую вкладку
    .label = Закрыть разделённую вкладку
floorp-custom-actions-custom-action-1 = Действие 1
    .label = Действие 1
floorp-custom-actions-custom-action-2 = Действие 2
    .label = Действие 2
floorp-custom-actions-custom-action-3 = Действие 3
    .label = Действие 3
floorp-custom-actions-custom-action-4 = Действие 4
    .label = Действие 4
floorp-custom-actions-custom-action-5 = Действие 5
    .label = Действие 5
floorp-custom-actions-rest-mode = Включить режим отдыха
    .label = Включить режим отдыха
floorp-custom-actions-hide-user-interface = Вкл/выкл пользовательский интерфейс
    .label = Вкл/выкл пользовательский интерфейс
floorp-custom-actions-toggle-navigation-panel = Включить или выключить панель навигации
    .label = Включить или выключить панель навигации
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Запустить
    .tooltiptext = Запустить { -brand-short-name } с этим профилем
floorp-profiles-in-use = Этот профиль уже используется.
floorp-profiles-title = Профили
floorp-profile-manager = Менеджер профилей
floorp-profiles-create = Создать профиль
floorp-profile = Профиль
    .label = Менеджер профилей
    .tooltiptext = Открыть менеджер профилей
fxa-not-signed-in = Не авторизован
###################################################################### Private Container ##############################################################
floorp-private-container-name = Приватный
floorp-toggle-private-container = 
    .label = Переоткрыть в приватном/без контейнера
    .accesskey = P
open-in_private-container = 
    .label = Открыть в новой вкладке с приватным контейнером
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Открыть в режиме раздельного просмотра
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Remove Split View
split-view-title = Настройки раздельного просмотра
split-view-position = Расположение
split-view-flex-type = Тип разметки
split-view-position-top = Top Side
split-view-position-left = По умолчанию
split-view-position-right = Обратный
split-view-flex-column = Вертикальный
split-view-flex-row = Горизонтальный
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Сканировать QR-код с помощью телефона
qrcode-generate-page-action = 
    .tooltiptext = Поделиться страницей с телефоном
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Кнопка унифицированных расширений
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Установить приложение
    .tooltiptext = Установить этот сайт в качестве веб-приложения
ssb-page-action-title = Установите приложение
ssb-app-open-button = 
    .label = Открыть в приложении
ssb-app-install-button = 
    .label = Установить
ssb-app-cancel-button = 
    .label = Отменить
floorp-open-manage-ssb-page = 
    .label = Управление установленными веб-приложениями
appmenuitem-webapps = 
    .label = Веб-приложения
appmenu-open-installed-apps-subheader = Открыть установленные веб-приложения
appmenuitem-install-current-page = 
    .label = Установите этот сайт в качестве веб-приложения
appmenuitem-open-current-page = 
    .label = Откройте этот сайт в установленном приложении
appmenuitem-contextmenu-open-app = 
    .label = Открыть приложение
appmenuitem-contextmenu-uninstall-app = 
    .label = Удалить это приложение

## Preferences

category-ssb = 
    .label = Веб-приложения
    .tooltiptext = Веб-приложения
category-ssb-title = Веб-приложения
floorp-ssb-title = Веб-приложения
floorp-ssb-description = Веб-приложения - это веб-сайты, которые можно установить в качестве приложений. Их можно запускать с панели меню { -brand-short-name } или из меню "Пуск" Windows.
ssb-preferences = Настройки веб-приложений
floorp-enable-ssb = 
    .label = Включить веб-приложения
floorp-enable-ssb-with-experimental = 
    .label = Включить веб-приложения (экспериментально)
floorp-enable-ssb-description = Эта функция экспериментальна на Mac и Linux. Рекомендуется включить эту функцию в Windows.
floorp-disable-toolbars = 
    .label = Отключить панель инструментов в окне веб-приложений
floorp-disable-toolbars-description = Этот параметр скрывает все расширения и панели инструментов в окне веб приложений.
ssb-installed-list-title = Установленные веб-приложения
ssb-uninstall-title = Удалите веб-приложение
ssb-uninstall-message = Вы уверены, что хотите удалить это веб-приложение из { -brand-short-name }?
ssb-uninstall-button = 
    .label = Удалить
ssb-uninstall-cancel = Отменить
######################################################################### Download Notification ###############################################################
floorp-started-download = Загрузка начата
floorp-finished-download = Загрузка завершена
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = Ваш { -brand-short-name } актуален!
floorp-notificationContent-latest = Ваша версия { -brand-short-name } актуальна. Вы используете последнюю версию { -brand-short-name }.
floorp-notificationTitle = Доступна новая версия { -brand-short-name } !
floorp-notificationContent = Нажмите для загрузки последней версии.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Закрыть вкладки до начала
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Закрыть вкладки до конца
    .accesskey = E
