# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> ist ein in Japan entwickelter Browser. Er basiert auf Firefox und läuft weiterhin unter <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, um das Web zu verbessern. Willst du helfen? <label data-l10n-name="helpus-donateLink">Unterstütze uns mit einer Spende!</label>
icon-creator = Icon-Ersteller <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> und <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Eine Liste von <label data-l10n-name="about-contributor">Mitwirkenden und Entwicklern</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Design
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Ein Neustart ist erforderlich, um die Änderungen zu übernehmen
tab-width = Minimale Tab-Breite
tab-height = Minimale Tab-Höhe
preferences-tabs-newtab-position = Neue Tab-Position
open-new-tab-use-default = 
    .label = Neue Tabs an der Standardposition öffnen
open-new-tab-at-the-end = 
    .label = Neue Tabs am Ende der Tab-Leiste öffnen
open-new-tab-next-to-current = 
    .label = Neue Tabs nach dem aktuellen Tab öffnen
multirow-tabs-limit = 
    .label = Zeilenlimit für mehrere Tabs aktivieren
multirow-tabs-newtab = 
    .label = Schaltfläche "Neuen Tab öffnen" am Ende der untersten Tab-Reihe anzeigen
multirow-tabs-value = Anzahl der Zeilen, wenn mehrzeilige Tabs aktiviert sind
enable-tab-sleep = 
    .label = Ruhezustand für Tabs aktivieren
tab-sleep-timeout-minutes-value = Tabs gehen in den Ruhezustand, nachdem sie für (Minuten) inaktiv sind
tab-sleep-settings-button = Einstellungen...
tab-sleep-settings-dialog-title = 
    .title = Einstellungen für Tabs im Ruhezustand
tab-sleep-settings-dialog-excludehosts-label = Hosts ausschließen
tab-sleep-settings-dialog-excludehosts-label-2 = Geben Sie einen Host pro Zeile ein.
tab-sleep-tab-context-menu-excludetab = Tab wach halten
enable-tab-scroll-change = 
    .label = Tabs mithilfe des Mausrads wechseln
enable-tab-scroll-reverse = 
    .label = Richtung invertieren
enable-tab-scroll-wrap = 
    .label = Scroll-Tabs am Rand umbrechen
enable-double-click-block = 
    .label = Tabs mit Doppelklick schließen
enable-show-pinned-tabs-title = 
    .label = Titel von angepinnten Tabs anzeigen
tabbar-preference = Tab-Leiste
tab-normal-mode = 
    .label = Standard
hide-horizontality-tabs = 
    .label = Tabs in der horizontalen Tab-Leiste ausblenden
verticalTab-setting = 
    .label = Browser für vertikale Tab-Leiste optimieren
move-tabbar-position = 
    .label = Tab-Leiste unterhalb der Symbolleiste anzeigen
tabbar-on-bottom = 
    .label = Tableiste am unteren Rand des Fensters anzeigen
tabbar-favicon-color = 
    .label = Einfärben der Tab-Leiste mit der Favicon Farbe der aktuellen Website
tabbar-style-preference = Stil der Tab-Leiste
horizontal-tabbar = 
    .label = Horizontale Tab-Leiste
tabbar-style-description = Ein Neustart von { -brand-short-name } ist erforderlich, um diese Einstellung anzuwenden.
multirow-tabbar = 
    .label = Mehrzeilige Tab-Leiste
vertical-tabbar = 
    .label = Vertikale Tab-Leiste (experimentell)
native-vertical-tab-show-right = 
    .label = Vertikale Tabs auf der rechten Seite des Fensters anzeigen
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = Vertikale Tab-Leiste automatisch ausblenden
floorp-show-vertical-tab-newtab-button = 
    .label = Schaltfläche "Neue Registerkarte öffnen" in der vertikalen Tab-Leiste anzeigen
floorp-show-vertical-tab-scrollbar = 
    .label = Scrollleiste in vertikaler Tab Leiste anzeigen
TST = Tree Style Tab
about-TST = Tree Style Tab ist ein beliebtes Add-on, mit dem Sie Registerkarten in einer baumartigen Struktur anzeigen können. Dieses Add-on ist bereits in { -brand-short-name } vorintegriert. Bitte installieren Sie das Add-on, um { -brand-short-name }'s Tree Style Tab zu aktivieren.
treestyletab-Settings = 
    .label = Tree Style Tab einklappen
sidebar-reverse-position-toolbar = Seitenleiste auf der anderen Seite anzeigen
bookmarks-bar-settings = Lesezeichen-Symbolleiste (nur eine Option kann gleichzeitig angewendet werden)
bookmarks-focus-mode = 
    .label = Lesezeichen-Symbolleiste ausblenden, wenn nicht über der Navigationsleiste gefahren wird
bookmarks-bottom-mode = 
    .label = Lesezeichen-Symbolleiste am unteren Rand von { -brand-short-name } anzeigen
navbar-settings = Navigationsleiste
show-nav-bar-bottom = 
    .label = Symbolleiste am unteren Rand von { -brand-short-name } (experimentell) anzeigen
disable-extension-check-compatibility-option = 
    .label = Do not check for compatibility with add-ons (deprecated)
other-preference = Andere Einstellungen
search-positon-top = 
    .label = Anzeige der Suchleiste am oberen Rand der Seite
allow-auto-restart = 
    .label = Automatisch neu starten, wenn Einstellungen geändert werden
disable-fullscreen-notification = 
    .label = Keine Benachrichtigung anzeigen, wenn der Vollbildmodus aktiviert wird

## Browser Theme

system-color-settings = Einige Themes haben sowohl helle als auch dunkle Modi - wählen Sie den Modus, den diese Themes verwenden sollen.
preferences-theme-appearance-header = Theme-Modus
system-theme-dark = 
    .label = Dunkel
system-theme-light = 
    .label = Hell
system-theme-auto = 
    .label = Systemfarben übernehmen

## User interface preferences

ui-preference = Browser-Darstellung
preferences-browser-appearance-description = Wähle ein eingebautes Drittanbieter-Design für { -brand-short-name }. Einige Designs sind möglicherweise nicht mit Ihrer Konfiguration kompatibel.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (veraltet)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (New)

## Download Manager

download-notification-preferences = Download Benachrichtigungen
start-always-notify = 
    .label = Nur benachrichtigen, wenn Downloads gestartet werden
finish-always-notify = 
    .label = Nur benachrichtigen, wenn Downloads beendet werden
always-notify = 
    .label = Benachrichtigen, wenn Downloads gestartet und beendet werden
do-not-notify = 
    .label = Download Benachrichtigungen deaktivieren

## Sidebar

profiles-button-label = Profile verwalten
floorp-help-button-label = { -brand-short-name } Support
appmenuitem-reboot = 
    .label = Neustart

## DMR UI

download-mgr-UI = 
    .label = SimpleUI Download Manager aktivieren
downloading-red-color = 
    .label = Das rote Download-Symbol beim Download verwenden
sidebar-preferences = Seitenleiste
bsb-preferences = Browser-Manager-Seitenleiste Einstellungen
view-sidebar2-right = 
    .label = Browser-Manager-Seitenleiste auf der rechten Seite anzeigen
enable-sidebar2 = 
    .label = Browser Manager Seitenleiste aktivieren
visible-bms = 
    .label = Browser-Manager-Seitenleiste anzeigen
hide-bms-to-unload-panel = 
    .label = Panel beim Ausblenden des Panels entladen
enable-addons-in-sidebar2-with-experimental = 
    .label = Inhaltsskripte für Erweiterungen in der Browser-Manager-Seitenleiste aktivieren (experimentell)
enable-addons-in-sidebar2 = 
    .label = Inhaltsskripte für Erweiterungen in der Browser-Manager-Seitenleiste aktivieren (experimentell)
sidebar2-enable-addons-desc = Wenn diese Einstellung aktiviert ist, funktionieren Werbeblocker-Erweiterungen und andere Erweiterungen in der Seitenleiste. Es werden jedoch nicht alle Erweiterungen unterstützt.
custom-URL-option = Web Panel-URL festlegen
set-custom-URL-button = 
    .label = Benutzerdefinierte URL...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Browser-Manager-Seitenleiste
bsb-context = Folgenden Container verwenden
bsb-userAgent-label = 
    .label = Mobilen User Agent in diesem Web Panel verwenden
bsb-width = Breite (falls auf 0 gesetzt, wird der globale Wert verwendet)
bsb-page = Zu öffnende Seite
bsb-add = Web Panel auf der Browser-Manager-Seitenleiste hinzufügen
bsb-setting = Web Panel Einstellungen
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Webseite
sidebar2-pref-delete = 
    .label = Löschen
sidebar2-pref-setting = 
    .label = Einstellungen
sidebar2-global-width = Breite der globalen Web-Panels
use-icon-provider-option = Icon-Anbieter verwenden
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (in China verfügbar)
use-icon-provider-option-hatena = 
    .label = Hatena (in China verfügbar)
memory-and-performance = Speicher und Leistung
min-memory = 
    .label = Minimale Speicherauslastung (geringe Leistung)
balance-memory = 
    .label = Gleichgewicht zwischen Speichernutzung und Leistung
max-memory = 
    .label = Beste Leistung (hoher Speicherverbrauch)
delete-border-and-roundup-option = 
    .label = Abrunden der Seitenecken

## DualTheme

dualtheme-enable = 
    .label = Enable Dual Theme (Deprecated)
floorp-enable-dualtheme-description = Dual Theme feature may cause problems with extensions. Please use with caution.
newtab-background = { -brand-short-name }-Startseite Hintergrund
newtab-background-random-image = 
    .label = Zufällige Bilder von Unsplash
newtab-background-gradation = 
    .label = Farbverlauf
newtab-background-not-background = 
    .label = Hintergrund deaktivieren
newtab-background-selected-image = 
    .label = Benutzerdefinierter Ordner...
newtab-background-selected-one-image = 
    .label = Benutzerdefiniertes Bild...
newtab-background-folder = Bilder aus diesem Ordner verwenden:
newtab-background-image = Bild verwenden:
newtab-choose-image = Bild wählen...
newtab-background-folder-reload = 
    .label = Bilder neu laden
newtab-background-folder-default = 
    .label = Standardeinstellungen wiederherstellen
newtab-background-folder-open = 
    .label = Ordner öffnen
newtab-background-folder-choose = Bilderordner auswählen...
newtab-background-image-choose = Bild wählen...
newtab-background-extensions = Bilder mit folgenden Dateiendungen verwenden (getrennt durch ",")
disable-blur-on-newtab = 
    .label = Unschärfe-Effekt in { -brand-short-name }-Startseite deaktivieren
disable-releasenote-on-newtab = 
    .label = Änderungsnotizen und Support-Links in { -brand-short-name}-Startseite deaktivieren
disable-imagecredit-on-newtab = 
    .label = Bildnachweis-Link in { -brand-short-name }-Startseite deaktivieren

## Lepton Preferences

about-lepton = { -brand-short-name } mit Lepton anpassen
lepton-preference-button = 
    .label = Lepton-Einstellungen...
    .accesskey = L
lepton-header = Lepton-Einstellungen
lepton-preference = Lepton-Einstellungen
photon-mode = 
    .label = Photon Design verwenden
lepton-mode = 
    .label = Lepton Design verwenden
protonfix-mode = 
    .label = Optimiertes Proton Design verwenden
autohide-preference = Browser-Elemente automatisch ausblenden
floorp-lepton-enable-tab-autohide = 
    .label = Tabs automatisch ausblenden
floorp-lepton-enable-navbar-autohide = 
    .label = Symbolleiste automatisch ausblenden
floorp-lepton-enable-sidebar-autohide = 
    .label = Seitenleiste automatisch ausblenden
floorp-lepton-enable-urlbar-autohide = 
    .label = Adressleiste automatisch ausblenden
floorp-lepton-enable-back-button-autohide = 
    .label = Zurück-Button automatisch ausblenden
floorp-lepton-enable-forward-button-autohide = 
    .label = Vorwärts-Button automatisch ausblenden
floorp-lepton-enable-page-action-button-autohide = 
    .label = Buttons in der Adressleiste automatisch ausblenden
floorp-lepton-enable-toolbar-overlap = 
    .label = Symbolleiste über Webseiteninhalt anzeigen
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Symbolleiste automatisch ausblenden, wenn "ltr" Inhalt angezeigt wird
hide-preference = Browser-Elemente verwalten
floorp-lepton-enable-tab_icon-hide = 
    .label = Tab-Symbole ausblenden
floorp-lepton-enable-tabbar-hide = 
    .label = Tab Leiste ausblenden
floorp-lepton-enable-navbar-hide = 
    .label = Werkzeugleiste verstecken
floorp-lepton-enable-sidebar_header-hide = 
    .label = Sidebarüberschriften ausblenden
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Adressleistensymbole ausblenden
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Lesezeichen-Leiste Symbole ausblenden
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Lesezeichenleistenbezeichnungen ausblenden
floorp-lepton-enable-disabled_menu-hide = 
    .label = Deaktivierte Kontextmenüelemente ausblenden
floorp-lepton-disable-userChrome-icon = 
    .label = Leptons Kontextmenü und Panelmenü-Symbole deaktivieren
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Leptons Kontextmenü-Symbole aktivieren
positon-preferences = Positionsanpassungen
floorp-lepton-enable-centered-tab = 
    .label = Label in Tabs zentrieren
floorp-lepton-enable-centered-urlbar = 
    .label = Text in der Adressleiste zentrieren
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Lesezeichenleiste zentrieren
urlbar-preferences = Adressleiste
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Adressleisten-Symbole auf die linke Seite verschieben
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Beim Tippen eine "Go"-Taste anzeigen
floorp-lepton-enable-always-show-page_action = 
    .label = Seitenaktionen immer in der Adressleiste anzeigen
tabbar-preferences = Tableiste
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Tableiste in der Titelleiste
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Tableiste und Symbolleiste kombinieren
lepton-sidebar-preferences = Seitenleiste
floorp-lepton-enable-overlap-sidebar = 
    .label = Seitenleiste über Webseiteninhalt anzeigen
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Startseite (Standard)
floorp-home-prefs-content-header = { -brand-short-name }-Startseiteninhalt
floorp-home-prefs-content-description = Wählen Sie den Inhalt aus, den Sie auf der { -brand-short-name }-Startseite sehen möchten.

## Notes

floorp-notes = { -brand-short-name } Notizen
restore-from-backup = Notizen aus Backup wiederherstellen
enable-notes-sync = 
    .label = { -brand-short-name } Notizen Sync aktivieren
about-notes-backup-tips = { -brand-short-name } Notizen verwendet Firefox Sync, um Ihre Notizen mit anderen Geräten zu synchronisieren. Wenn Sie Ihre Notizen verlieren, können Sie diese von einer Sicherheitskopie wiederherstellen. Ein automatisches Backup wird erstellt, wenn sie { -brand-short-name } öffnen.
notes-sync-description = Dies kann das Problem des Verlustes von Inhalten lösen, da während der Synchronisation Notizen überschrieben werden.
backuped-time = Gesichert am
notes-backup-option = Sicherungseinstellungen
backup-option-button = Sicherungseinstellungen...
restore-from-backup-prompt-title = { -brand-short-name } Notizen Wiederherstellungsdienst
restore-from-this-backup = Notizen in den Zustand zurückversetzen, wie in dieser Sicherung vorhanden sind?
restore-button = Wiederherstellen

## user.js

header-userjs = user.js
userjs-customize = { -brand-short-name } mit user.js anpassen
about-userjs-customize = user.js ist eine Konfigurationsdatei, mit der Sie { -brand-short-name } anpassen können. user.js Dateien werden aus dem Internet heruntergeladen und überschreiben Ihre aktuelle user.js Datei. Bitte sichern Sie Ihre aktuelle user.js-Datei, bevor Sie fortfahren. user.js Konfigurationen werden automatisch nach einem Neustart von { -brand-short-name } angewendet.
userjs-label = user.js Liste
userjs-prompt = Diese user.js anwenden?
apply-userjs-attention = Die Anwendung einer neuen user.js überschreibt Ihre aktuelle user.js-Datei.
apply-userjs-attention2 = Bitte sichern Sie Ihre aktuelle user.js-Datei, bevor Sie fortfahren.
userjs-button = user.js Einstellungen...
userjs-select-option = Verwalten Sie die user.js, die derzeit in { -brand-short-name } verwendet werden, um Leistung und Privatsphäre zu verbessern.
apply-userjs-button = Anwenden

## userjs Options

default-userjs-label = { -brand-short-name } Standard
about-default-userjs = Telemetrie deaktiviert. Ausgewogenes { -brand-short-name } mit verschiedenen Anpassungen aktiviert.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS-by-Default. Gesamter Cookie-Schutz mit Website-Isolierung. Verbesserter Zustand und Netzwerk-Partitionierung. Verschiedene andere Verbesserungen.
default-label = Yokoffing Default
about-default = Alles Wesentliche. Keiner des Bruchs. Dies ist Ihre user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Beschleunigt die Browsergeschwindigkeit von Firefox. Gib Chrome einen Run für sein Geld!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Aktualisieren Sie die neue Tab-Seite. Entfernen Sie Pocket. Kompakter Modus als Option wiederherstellen. Webseiten-Benachrichtigungen, Pop-ups und andere Ärgernisse stoppen.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Holen Sie sich Edge-ähnliches Scrollen in Ihrem bevorzugten Browser — oder wählen Sie etwas mehr Ihren Stil.
select-workspace = Arbeitsbereich auswählen
workspace-select-icon = Symbol für Arbeitsbereich auswählen
    .label = Symbol für Arbeitsbereich auswählen
workspace-select-container = Container-Tab auswählen
    .label = Container-Tab auswählen
workspace-customize = 
    .title = Arbeitsbereich anpassen
floorp-no-workspace-container = 
    .label = No Container
workspace-icon-article = 
    .label = Artikel
workspace-icon-book = 
    .label = Buch
workspace-icon-briefcase = 
    .label = Job
workspace-icon-cart = 
    .label = Einkaufen
workspace-icon-chat = 
    .label = Chat
workspace-icon-chill = 
    .label = Privat
workspace-icon-circle = 
    .label = Kreis
workspace-icon-compass = 
    .label = Kompass
workspace-icon-code = 
    .label = Code
workspace-icon-dollar = 
    .label = Bank
workspace-icon-fence = 
    .label = Zaun
workspace-icon-fingerprint = 
    .label = Persönlich
workspace-icon-food = 
    .label = Nahrung
workspace-icon-fruit = 
    .label = Obst
workspace-icon-game = 
    .label = Spiel
workspace-icon-gear = 
    .label = Ausrüstung
workspace-icon-gift = 
    .label = Geschenk
workspace-icon-key = 
    .label = Schlüssel
workspace-icon-lightning = 
    .label = Blitz
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notizen
workspace-icon-paint = 
    .label = Malen
workspace-icon-photo = 
    .label = Foto
workspace-icon-pin = 
    .label = Pin
workspace-icon-pet = 
    .label = Haustier
workspace-icon-question = 
    .label = Frage
workspace-icon-smartphone = 
    .label = Smartphone
workspace-icon-star = 
    .label = Stern
workspace-icon-tree = 
    .label = Baum
workspace-icon-vacation = 
    .label = Urlaub
workspace-icon-love = 
    .label = Liebe
workspace-icon-moon = 
    .label = Mond
workspace-icon-music = 
    .label = Musik
workspace-icon-user = 
    .label = Benutzer
# Custom Keyboard Shortcuts
floorp-CSK-title = Benutzerdefinierte Tastaturkürzel
floorp-CSK-description = Passen Sie die Tastaturkürzel von { -brand-short-name } an. { -brand-short-name } bietet mehr als 80 anpassbare Tastaturkürzel! Doppelte Kurzbefehle werden nicht funktionieren. Starten Sie { -brand-short-name } neu, um diese Einstellungen zu übernehmen.
disable-fx-actions = 
    .label = Deaktiviere die Tastaturkürzel von Mozilla Firefox
customize-Action = 
    .label = Verknüpfung hinzufügen
remove-Action = 
    .label = Verknüpfung entfernen
CSK-reset-title = Benutzerdefinierte Tastaturkürzel zurücksetzen
CSK-reset-description = Benutzerdefinierte Tastenkürzel auf die Standardwerte von { -brand-short-name }zurücksetzen.
CSK-reset-label = Benutzerdefinierte Tastaturkürzel zurücksetzen
CSK-reset-button = Standard wiederherstellen
CSK-manage-title = Tastaturkürzel verwalten
CSK-remove-shortcutkey = Benutzerdefinierte Tastaturkürzel entfernen?
CSK-remove-shortcutkey-description = Sind Sie sicher, dass Sie dieses Tastaturkürzel entfernen möchten?
CSK-restore-default = Standard wiederherstellen?
CSK-restore-default-description = Die Standard-Tastaturkürzel von { -brand-short-name } wiederherstellen? Ihre aktuellen Tastenkombinationen gehen verloren.
CSK-reboot-browser-label = { -brand-short-name } neustarten, um diese Einstellungen zu übernehmen
CSK-reboot-browser-button = { -brand-short-name } neu starten
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Aktuelle Tastaturkürzel: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Aktuelle Tastaturkürzel: { $key }.
CSK-keyborad-shortcut-is-changed = (Nicht angewendet)
floorp-custom-actions-tab-action = Tab Aktionen
floorp-custom-actions-page-action = Seiten Aktionen
floorp-custom-actions-visible-action = Sichtbare Aktionen
floorp-custom-actions-search-action = Aktionen durchsuchen
floorp-custom-actions-tools-action = Werkzeug Aktionen
floorp-custom-actions-bookmark-action = Lesezeichen-Aktionen
floorp-custom-actions-open-page-action = Öffne Seitenaktionen
floorp-custom-actions-history-action = Chronik Aktionen
floorp-custom-actions-pip-action = Bild-in-Bild-Aktionen
floorp-custom-actions-downloads-action = Download-Aktionen
floorp-custom-actions-sidebar-action = Seitenleiste Aktionen
floorp-custom-actions-bms-action = Browser-Manager-Seitenleistenaktionen
floorp-custom-actions-split-view-action = Geteilte Ansicht
floorp-custom-actions-workspaces-action = Arbeitsbereich-Aktionen
floorp-custom-actions-custom-action = Eigene Aktionen (Experimentell)

## Mouse Gestures

mouse-gesture = Mausgesten
mouse-gesture-description = Gesturefy muss installiert sein, um Mausgesten mit { -brand-short-name } zu verwenden.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy ist eine Erweiterung, die Mausgesten hinzufügt. Wenn { -brand-short-name } die Installation dieses Add-ons entdeckt, werden Gesten Befehle hinzugefügt, die nur in { -brand-short-name } verfügbar sind. Dieses Add-on kann auch neue Tabs starten!
# Translate
TWS = Webseite übersetzen
about-TWS = Übersetzen Sie Ihre Seite in Echtzeit mit Google oder Yandex. Sie können auch den ausgewählten Text oder die gesamte Seite übersetzen.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Privatsphäre-Hub
block-more-tracker = Weitere Werbung und Tracker blockieren
block-tracker = Dieser Abschnitt enthält eine Reihe von Erweiterungen zum Blockieren von Werbung und Trackern
view-at-AMO = Dieses Addon in addons.mozilla.org ansehen
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin blockiert Werbung, umfangreiche Tracker und zusätzliche gefährliche Websites.
Facebook-Container = Facebook-Container
about-Facebook-Container = Verhindern Sie Facebook daran, Sie im Web zu verfolgen. Facebook-Container-Erweiterung hilft Ihnen, Ihre Web-Aktivitäten von Facebook zu steuern und zu isolieren.

## Fingerprinting

fingerprint-header = Widerstehen von Fingerprinting & IP-Adressenlecks
block-fingerprint = Fingerprinting ist ein Tracking-Mechanismus, der sich auf die einzigartigen Eigenschaften Ihres Browsers und Betriebssystems stützt. Dieser Abschnitt enthält Einstellungen, mit denen Sie diesen Schutz über die standardmäßige Blockierung hinaus weiter verbessern können.
enable-firefox-fingerprint-protections = Aktiviere starken Schutz gegen Fingerabdrücke
about-firefox-fingerprint-protection = Die Aktivierung des Schutzes durch Firefox umfasst den erzwungenen Light-Modus, die Deaktivierung einiger APIs usw. Einige Websites funktionieren unter Umständen nicht wie erwartet.
fingerprint-Protection = 
    .label = Anti-Fingerprinting-Schutz
html5-canvas-prompt-settings = 
    .label = Zugriffsbestätigung für HTML5-Bilddaten automatisch ausblenden
canvas-prompt = Verhindert die Verwendung der Leinwand als Prompt für Webseiten, sofern dies nicht manuell erlaubt ist.
disable-webgl = 
    .label = WebGL deaktivieren
about-webgl = WebGL ist eine Javascript-API, die zum Rendern von Grafiken verwendet wird, die verwendet werden kann, um GPU zu identifizieren.
Canvas-Blocker = Canvas-Blocker
about-CB = Dieses Add-on fälscht Daten, die von Fingerprinting-Techniken verwendet werden.
WebRTC-connection = WebRTC ist ein Standard, der Anrufe in Echtzeit ermöglicht. Wenn Sie diese Einstellung deaktivieren, können Sie Discord usw. nicht verwenden.
WebRTC = 
    .label = WebRTC-Verbindung aktivieren
################################################################### browser ###############################################################

rest-mode = Mach eine Pause...
rest-mode-description = { -brand-short-name } ist zurzeit pausiert. Drücken Sie ENTER oder OK um fortzufahren.
Sidebar2 = 
    .label = Browser-Manager-Seitenleiste
    .tooltiptext = Seitenleistensichtbarkeit ändern
sidebar2-mute-and-unmute = 
    .label = Dieses Panel stumm/entsperren
sidebar2-unload-panel = 
    .label = Dieses Panel entladen
sidebar2-change-ua-panel = 
    .label = Mobile User-Agent umschalten
sidebar2-delete-panel = 
    .label = Dieses Panel löschen
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom In
sidebar2-zoom-out = 
    .label = Zoom Out
sidebar2-reset-zoom = 
    .label = Reset Zoom
sidebar2-close-button = 
    .tooltiptext = Seitenleiste schließen
sidebar-back-button = 
    .tooltiptext = Zurück
sidebar-forward-button = 
    .tooltiptext = Vorwärts
sidebar-reload-button = 
    .tooltiptext = Neu laden
sidebar-go-index-button = 
    .tooltiptext = Zur Startseite
sidebar-muteAndUnmute-button = 
    .tooltiptext = Seitenleiste stummschalten/aufheben
sidebar2-browser-manager-sidebar = Browser-Manager
show-browser-manager-sidebar = 
    .tooltiptext = { sidebar2-browser-manager-sidebar } Seitenleiste anzeigen
sidebar2-bookmark-sidebar = Lesezeichen
show-bookmark-sidebar = 
    .tooltiptext = { sidebar2-bookmark-sidebar } Seitenleiste anzeigen
sidebar2-history-sidebar = Verlauf
show-history-sidebar = 
    .tooltiptext = { sidebar2-history-sidebar } Seitenleiste anzeigen
sidebar2-download-sidebar = Downloads
show-download-sidebar = 
    .tooltiptext = { sidebar2-download-sidebar } Seitenleiste anzeigen
sidebar2-notes-sidebar = Notizen
show-notes-sidebar = 
    .tooltiptext = { sidebar2-notes-sidebar } Seitenleiste anzeigen
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Add-ons und Themes
sidebar2-hide-sidebar-button = 
    .tooltiptext = Browser-Manager-Seitenleiste verstecken
sidebar-passwords-button = 
    .tooltiptext = Passwörter
sidebar-preferences-button = 
    .tooltiptext = Einstellungen
sidebar-keepWidth-button = 
    .tooltiptext = Die aktuelle Breite auf diesem Panel weiter verwenden
sidebar2-keep-width-for-global = 
    .label = Diese Breite auf alle Panels ohne eigene Breite anwenden
bsb-context-add = 
    .label = Seite zum Web-Panel hinzufügen...
bsb-context-link-add = 
    .label = Link zum Web-Panel hinzufügen...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Profilverzeichnis öffnen
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = CSS-Dateien des Browsers neu erstellen
    .accesskey = L
make-browsercss-file = 
    .label = CSS-Datei des Browsers erstellen
    .accesskey = M
open-css-folder = 
    .label = CSS-Ordner öffnen
    .accesskey = O
edit-userChromeCss-editor = 
    .label = userChrome.css Datei bearbeiten
edit-userContentCss-editor = 
    .label = userContent.css bearbeiten
not-found-editor-path = CSS-Datei-Editor konnte nicht gefunden werden
set-pref-description = Geben Sie den Speicherort des CSS-Dateieditors ein, den Sie verwenden möchten:
rebuild-complete = Wiederherstellung wurde abgeschlossen.
please-enter-filename = Bitte geben Sie einen Dateinamen ein.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Geschlossenen Tab erneut öffnen
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Als duales Theme aktivieren
dual-theme-disable-addon-button = Duales Theme deaktivieren
dual-theme-enabled-heading = Als duales Theme aktiviert
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Statusleiste
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Tree-Style Tab Panel öffnen
gf-floorp-open-tree-style-tab-description = Tree-Style Tab Panel in der Seitenleiste öffnen
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Lesezeichen-Panel öffnen
gf-floorp-open-bookmarks-sidebar-description = Lesezeichen-Panel in der Seitenleiste öffnen
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Chronik-Panel öffnen
gf-floorp-open-history-sidebar-description = Chronik-Panel in der Seitenleiste öffnen
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Synchronisierte Tabs-Panel öffnen
gf-floorp-open-synctabs-sidebar-description = Synchronisierte Tab-Panel in der Seitenleiste öffnen
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Seitenleiste schließen
gf-floorp-close-sidebar-description = Seitenleiste schließen
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Öffne BMS
gf-floorp-open-browser-manager-sidebar-description = Browser-Manager-Seitenleiste öffnen, wenn das Web Panel geladen ist
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] BMS schließen
gf-floorp-close-browser-manager-sidebar-description = Browser-Manager-Seitenleiste schließen
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] BMS umschalten
gf-floorp-show-browser-manager-sidebar-description = Browser-Manager-Seitenleiste umschalten
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Statusleiste ausblenden
gf-floorp-hide-statusbar-description = Statusleiste ausblenden
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Statusleiste umschalten
gf-floorp-show-statusbar-description = Statusleiste anzeigen oder ausblenden
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Add-on-Panel in der Seitenleiste öffnen
gf-floorp-open-extension-sidebar-description = Ausgewähltes Add-on in der Seitenleiste öffnen
gf-floorp-open-extension-sidebar-settings-addons-id = Add-on Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id-description = Die Erweiterung des Add-ons öffnen der Seitenleiste
gf-floorp-open-extension-sidebar-settings-list-default = Bitte wählen Sie ein Add-on
gf-floorp-open-extension-sidebar-settings-list-unknwon = Unbekanntes Add-on
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Updates gefunden!
update-portable-notification-found-message = Updates werden heruntergeladen...
update-portable-notification-ready-title = Bereit zum Aktualisieren!
update-portable-notification-ready-message = { -brand-short-name } wird beim nächsten Start aktualisiert.
update-portable-notification-success-title = Update erfolgreich!
update-portable-notification-success-message = Update erfolgreich! Wir wünschen Ihnen viel Spaß mit der neuen Version von { -brand-short-name }!
update-portable-notification-failed-title = Update fehlgeschlagen.
update-portable-notification-failed-redirector-message = Update fehlgeschlagen. Ein Neustart Ihres Browsers könnte dieses Problem beheben.
update-portable-notification-failed-prepare-message = Fehler bei der Vorbereitung der Aktualisierung.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Portable Update
floorp-update-application-auto-enabled-option = 
    .label = Automatisch nach Updates für { -brand-short-name } Portable suchen. (Empfohlen)
##################################################################### Open link in external ###############################################################
openInExternal-title = In externem Browser öffnen
open-link-in-external-enabled-option = 
    .label = Aktivieren Sie die Funktion "Im externen Browser öffnen"
open-link-in-external-select-browser-option = Wählen Sie aus, welcher Browser geöffnet werden soll
open-link-in-external-select-browser-option-default = 
    .label = Standardbrowser
open-link-in-external-tab-context-menu = In externem Browser öffnen
open-link-in-external-tab-dialog-title-error = Ein Fehler ist aufgetreten:
open-link-in-external-tab-dialog-message-default-browser-not-found = Standardbrowser wurde nicht gefunden oder ist nicht konfiguriert.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Der ausgewählte Browser existiert nicht.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Neu
memo-title-input-placeholder = Schreibe hier einen Titel
memo-input-placeholder = Schreibe oder füge eine Memo hier ein
delete-memo = Löschen
save-memo = Speichern
memo-welcome-title = Willkommen!
memo-first-tip = Willkommen bei { -brand-short-name } Notizen! Hier sind einige Tipps, wie man es verwenden kann!
memo-second-tip = { -brand-short-name } Notizen ist ein Notizblock, mit dem Sie mehrere Notizen speichern können, die geräteübergreifend synchronisiert werden. Um die Synchronisierung zu aktivieren, müssen Sie sich bei { -brand-short-name } mit Ihrem Firefox-Konto anmelden.
memo-third-tip = { -brand-short-name } Die Notizen werden in den Einstellungen von { -brand-short-name } gespeichert und mit Firefox Sync geräteübergreifend synchronisiert. Firefox Sync verschlüsselt den Inhalt der Synchronisierung mit Ihrem Firefox-Kontopasswort, sodass niemand außer Ihnen den Inhalt kennt.
memo-import-data-tip = Firefox Sync ist kein Sicherungsdienst. Wir empfehlen Ihnen, Sicherungen zu erstellen.
memo-new-title = Neue Notiz
chage-view-mode = Ansicht/Bearbeiten-Modus umschalten
readonly-mode = Offline (schreibgeschützt)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Hilfe zu Floorp
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Downloads löschen
    .accesskey = D
    .tooltiptext = Downloads löschen
floorp-show-all-downloads = 
    .label = Alle Downloads anzeigen
    .accesskey = S
    .tooltiptext = Alle Downloads anzeigen
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Neuen Arbeitsbereich erstellen...
    .tooltiptext = Einen neuen Arbeitsbereich erstellen
workspaces-manage-workspaces-button = 
    .label = Arbeitsbereiche verwalten...
    .tooltiptext = Deine Arbeitsbereiche verwalten
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Arbeitsbereich umbenennen
    .accesskey = R
delete-this-workspace = 
    .label = Arbeitsbereich löschen
    .accesskey = D
manage-this-workspaces = 
    .label = Arbeitsbereiche verwalten...
    .accesskey = M
workspace-new-default-name = Neuer Arbeitsbereich
workspace-default-name = Standard
move-tab-another-workspace = 
    .label = In einen anderen Arbeitsbereich verschieben
rename-workspace-prompt-title = Arbeitsbereich umbenennen
rename-workspace-prompt-text = Geben Sie den Namen des Arbeitsbereichs ein. Die meisten Zeichen und Symbole können verwendet werden.
workspaces-toolbar-button = Arbeitsbereiche
    .label = Arbeitsbereiche
    .tooltiptext = Arbeitsbereich auswählen...

## Preferences

enable-workspaces = 
    .label = Arbeitsbereiche aktivieren
    .tooltiptext = Arbeitsbereiche aktivieren
workspace-notice = Arbeitsbereiche funktionieren nur, wenn der entsprechende Knopf auf der Symbolleiste befindet. Aktivieren Sie diese Einstellung um Arbeitsbereiche vollständig zu deaktivieren.
enable-workspaces-with-experimental = 
    .label = Arbeitsbereiche aktivieren (experimentell)
    .tooltiptext = Arbeitsbereiche aktivieren (experimentell)
workspace-warning = Arbeitsbereiche können nicht zusammen mit Add-ons für Tab-Gruppen verwendet werden. Wenn du Add-ons für Tab-Gruppen verwenden möchtest, deaktiviere Arbeitsbereiche und starte { -brand-short-name } neu.
category-workspaces = 
    .label = Arbeitsbereiche
    .tooltiptext = Arbeitsbereiche
pane-workspaces-title = Arbeitsbereiche
floorp-workspaces-title = { -brand-short-name } Arbeitsbereiche
floorp-workspace-settings-button = Arbeitsbereichseinstellungen...
floorp-preferences-label = Preferences
floorp-extensions-label = Extensions
floorp-private-label = Private
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = Arbeitsbereich auf der Browser-Manager-Seitenleiste verwalten
show-workspace-name-option = 
    .label = Anzeigen des Arbeitsbereichsnamens auf der Schaltfläche Arbeitsbereich in der Registerkarte
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Freigabemodus
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Bei Ihrem Firefox-Konto anmelden
welcome-to-floorp = Willkommen bei { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Bereit einzutauchen?
welcome-skip-to-start-browsing = Setup überspringen
welcome-select-preferences-template = Wähle eine Vorlage
welcome-minimum-template = Einfach
welcome-enable-basic-features = Aktiviere grundlegende Funktionen und Einstellungen für ein einfaches Erlebnis.
welcome-medium-template = Standard
welcome-enable-some-features = Aktiviere zusätzliche Funktionen und Einstellungen für ein besseres Erlebnis.
welcome-maximum-template = Erweitert
welcome-enable-most-of-features = Aktiviere erweiterte Funktionen und Einstellungen. Empfohlen für erfahrene Benutzer.
welcome-go-next-setup = Weiter
welcome-select-browser-design = Wähle ein Browser-Design
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Lepton Original Design
welcome-design-photon-name = Lepton Photon Design
welcome-design-ProtonFix-name = Lepton ProtonFix Design
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Firefox Proton Design
welcome-import-data = Browserdaten importieren
welcome-import-data-description = Schnelle Einrichtung! Importiere Lesezeichen, Passwörter und mehr aus deinem alten Browser. Benutzer von Firefox können ihre Daten von Firefox Sync importieren.
welcome-import-data-button = Daten importieren...
welcome-import-data-skip = Import überspringen
welcome-select-button = Auswählen
welcome-finish-setup = Einrichtung abgeschlossen!
welcome-finish-setup-description = Sie sind fertig! Weitere Funktionen wie vertikale Tabs und Arbeitsbereiche finden Sie in den Einstellungen. Viel Spaß mit { -brand-short-name }!
welcomet-finish-setup = Beginne im Web zu surfen
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Tastenkürzel
    .tooltiptext = Tastenkürzel
category-CSK-title = Tastenkürzel
shortcutkey-customize = 
    .title = Tastenkürzel
select-shortcutkeyAction = Aktion zum Auslösen auswählen
shortcutkey-customize-key-list-placeholder = Ihr Tastaturkürzel wird hier angezeigt
shortcut-key-label = Tastenkürzel
start-input-button-listen = Aufnahme starten
end-input-button-listen = Aufnahme stoppen
shortcut-key-description = Klicke auf "Aufnahme starten" und gebe dein neues Tastenkürzel für diese Aktion ein. Es können mehrere Tasten verwendet werden, allerdings funktionieren die Tastenkombinationen nicht, wenn sie bereits anderen Aktionen zugewiesen sind.
floorp-custom-actions-open-new-tab = Neuen Tab öffnen
    .label = Neuen Tab öffnen
floorp-custom-actions-close-tab = Aktuellen Tab schließen
    .label = Aktuellen Tab schließen
floorp-custom-actions-open-new-window = Neues Fenster öffnen
    .label = Neues Fenster öffnen
floorp-custom-actions-open-new-private-window = Neues privates Fenster öffnen
    .label = Neues privates Fenster öffnen
floorp-custom-actions-close-window = Aktuelles Fenster schließen
    .label = Aktuelles Fenster schließen
floorp-custom-actions-restore-last-session = Letzte Sitzung wiederherstellen
    .label = Letzte Sitzung wiederherstellen
floorp-custom-actions-restore-last-window = Letztes Fenster wiederherstellen
    .label = Letztes Fenster wiederherstellen
floorp-custom-actions-show-next-tab = Nächsten Tab anzeigen
    .label = Nächsten Tab anzeigen
floorp-custom-actions-show-previous-tab = Vorherigen Tab anzeigen
    .label = Vorherigen Tab anzeigen
floorp-custom-actions-show-all-tabs-panel = Alle Tabs anzeigen
    .label = Registerkartenliste anzeigen
floorp-custom-actions-send-with-mail = Mit E-Mail senden
    .label = Per E-Mail senden
floorp-custom-actions-save-page = Seite speichern
    .label = Seite speichern
floorp-custom-actions-print-page = Print page
    .label = Print page
floorp-custom-actions-mute-current-tab = Stumm/Stummschalten des aktuellen Tab
    .label = Stumm/Stummschalten des aktuellen Tab
floorp-custom-actions-toggle-bookmark-toolbar = Lesezeichen-Symbolleiste anzeigen
    .label = Lesezeichen-Symbolleiste umschalten
floorp-custom-actions-show-source-of-page = Seitenquelle anzeigen
    .label = Seitenquelle öffnen
floorp-custom-actions-show-page-info = Seiteninfo anzeigen
    .label = Seiteninfo öffnen
floorp-custom-actions-zoom-in = Vergrößern
    .label = Vergrößern
floorp-custom-actions-zoom-out = Verkleinern
    .label = Verkleinern
floorp-custom-actions-reset-zoom = Reset zoom
    .label = Reset zoom
floorp-custom-actions-back = Zurück
    .label = Zurück
floorp-custom-actions-forward = Vorwärts
    .label = Vorwärts
floorp-custom-actions-reload = Reload
    .label = Reload
floorp-custom-actions-stop = Stoppen
    .label = Stoppen
floorp-custom-actions-force-reload = Neu laden erzwingen
    .label = Neu laden erzwingen
floorp-custom-actions-search-in-this-page = Auf dieser Seite suchen
    .label = In Seite suchen
floorp-custom-actions-show-next-search-result = Nächstes Suchwort in diesem Seitenergebnis anzeigen
    .label = Nächstes Ergebnis in Seite
floorp-custom-actions-show-previous-search-result = Vorheriges Suchwort in diesem Seitenergebnis anzeigen
    .label = Vorherige Suche in Seite" Ergebnis
floorp-custom-actions-search-the-web = Web durchsuchen
    .label = Web durchsuchen
floorp-custom-actions-open-migration-wizard = Öffne Migrationsassistent
    .label = Öffne Migrationsassistent
floorp-custom-actions-quit-from-application = Von der Anwendung beenden
    .label = { -brand-short-name } beenden
floorp-custom-actions-enter-into-customize-mode = Werkzeugleiste anpassen
    .label = Öffne { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Offline-Modus aktivieren
    .label = Offline-Modus aktivieren
floorp-custom-actions-open-screen-capture = Bildschirmaufnahme öffnen
    .label = Screenshot machen
floorp-custom-actions-show-pip = Bild in Bild anzeigen
    .label = Bild in Bild anzeigen
floorp-custom-actions-bookmark-this-page = Diese Seite markieren
    .label = Diese Seite markieren
floorp-custom-actions-open-bookmarks-sidebar = Lesezeichen Seitenleiste öffnen
    .label = Lesezeichen-Seitenleiste öffnen
floorp-custom-actions-open-bookmark-add-tool = Lesezeichen hinzufügen Werkzeug öffnen
    .label = Lesezeichen hinzufügen
floorp-custom-actions-open-bookmark-add-toolbar = Pop-up-Fenster "Neues Lesezeichen hinzufügen" öffnen
    .label = Zur Lesezeichen-Symbolleiste hinzufügen
floorp-custom-actions-open-bookmarks-manager = Lesezeichen-Manager öffnen
    .label = Lesezeichen-Manager öffnen
floorp-custom-actions-show-bookmark-toolbar = Lesezeichen-Symbolleiste umschalten
    .label = Lesezeichen-Symbolleiste umschalten
floorp-custom-actions-open-general-preferences = Allgemeine Einstellungen öffnen
    .label = Allgemeine Einstellungen öffnen
floorp-custom-actions-open-privacy-preferences = Privatsphäre-Einstellungen öffnen
    .label = Datenschutzeinstellungen öffnen
floorp-custom-actions-open-workspaces-preferences = Open Workspaces preferences
    .label = Einstellungen für offene Arbeitsbereiche
floorp-custom-actions-open-containers-preferences = Container-Einstellungen öffnen
    .label = Container-Einstellungen öffnen
floorp-custom-actions-open-search-preferences = Sucheinstellungen öffnen
    .label = Sucheinstellungen öffnen
floorp-custom-actions-open-sync-preferences = Sync-Einstellungen öffnen
    .label = Sync-Einstellungen öffnen
floorp-custom-actions-open-task-manager = Offener Task-Manager
    .label = Öffne { -brand-short-name }'s Task-Manager
floorp-custom-actions-open-home-page = Öffne { -brand-short-name }'s Startseite
    .label = Öffne { -brand-short-name }'s Homepage
floorp-custom-actions-open-addons-manager = Add-ons und Themes öffnen
    .label = Add-ons und Themes öffnen
floorp-custom-actions-forget-history = Verlauf löschen
    .label = Verlauf löschen
floorp-custom-actions-quick-forget-history = Schnell-vergessen-Verlauf
    .label = Schnell-vergessen-Verlauf
floorp-custom-actions-clear-recent-history = Aktuellen Verlauf löschen
    .label = Aktuellen Verlauf löschen
floorp-custom-actions-search-history = Suchverlauf
    .label = Suchverlauf
floorp-custom-actions-manage-history = Verlauf verwalten
    .label = Verlauf verwalten
floorp-custom-actions-open-downloads = Downloads öffnen
    .label = Öffne Downloads
floorp-custom-actions-show-bms = Toggle browser manager sidebar
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = Lesezeichen-Seitenleiste anzeigen
    .label = Lesezeichen Sidebar anzeigen
floorp-custom-actions-show-history-sidebar = Chronik-Seitenleiste anzeigen
    .label = Chronik-Seitenleiste anzeigen
floorp-custom-actions-show-synced-tabs-sidebar = Show synced tabs sidebar
    .label = Show Synced Tabs Sidebar
floorp-custom-actions-reverse-sidebar = Seitenleistenposition umkehren
    .label = Seitenleistenposition umkehren
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = Seitenleiste umschalten
    .label = Seitenleiste umschalten
floorp-custom-actions-toggle-sidebar = Seitenleiste Ein-/Ausblenden
    .label = Seitenleiste Ein-/Ausblenden
floorp-custom-actions-open-previous-workspace = Open previous Workspace
    .label = Open previous Workspace
floorp-custom-actions-open-next-workspace = Open next Workspace
    .label = Open next Workspace
floorp-custom-actions-show-panel-1 = Panel 1 umschalten
    .label = Panel 1 umschalten
floorp-custom-actions-show-panel-2 = Panel 2 umschalten
    .label = Panel 2 umschalten
floorp-custom-actions-show-panel-3 = Panel 3 umschalten
    .label = Panel 3 umschalten
floorp-custom-actions-show-panel-4 = Panel 4 umschalten
    .label = Panel 4 umschalten
floorp-custom-actions-show-panel-5 = Panel 5 umschalten
    .label = Panel 5 umschalten
floorp-custom-actions-show-panel-6 = Panel 6 umschalten
    .label = Panel 6 umschalten
floorp-custom-actions-show-panel-7 = Panel 7 umschalten
    .label = Panel 7 umschalten
floorp-custom-actions-show-panel-8 = Panel 8 umschalten
    .label = Panel 8 umschalten
floorp-custom-actions-show-panel-9 = Panel 9 umschalten
    .label = Panel 9 umschalten
floorp-custom-actions-show-panel-10 = Panel 10 umschalten
    .label = Panel 10 umschalten
floorp-custom-actions-open-split-view-on-left = Aktuelle Registerkarte auf der linken Seite in geteilter Ansicht öffnen
    .label = Aktuelle Registerkarte auf der linken Seite in geteilter Ansicht öffnen
floorp-custom-actions-open-split-view-on-right = Aktuelle Registerkarte auf der rechten Seite in geteilter Ansicht öffnen
    .label = Aktuelle Registerkarte auf der rechten Seite in geteilter Ansicht öffnen
floorp-custom-actions-close-split-view = Geteilte Ansicht schließen
    .label = Geteilte Ansicht schließen
floorp-custom-actions-custom-action-1 = Eigene Aktion 1
    .label = Eigene Aktion 1
floorp-custom-actions-custom-action-2 = Benutzerdefinierte Aktion 2
    .label = Benutzerdefinierte Aktion 2
floorp-custom-actions-custom-action-3 = Benutzerdefinierte Aktion 3
    .label = Benutzerdefinierte Aktion 3
floorp-custom-actions-custom-action-4 = Benutzerdefinierte Aktion 4
    .label = Benutzerdefinierte Aktion 4
floorp-custom-actions-custom-action-5 = Benutzerdefinierte Aktion 5
    .label = Benutzerdefinierte Aktion 5
floorp-custom-actions-rest-mode = Ruhemodus einschalten
    .label = Ruhemodus einschalten
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
floorp-custom-actions-toggle-navigation-panel = Toggle Navigation Panel
    .label = Toggle Navigation Panel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Starten
    .tooltiptext = { -brand-short-name } mit diesem Profil starten
floorp-profiles-in-use = Dieses Profil wird verwendet.
floorp-profiles-title = Profiles
floorp-profile-manager = Profil-Manager
floorp-profiles-create = Profil erstellen
floorp-profile = Profil
    .label = Profil-Manager
    .tooltiptext = Profil-Manager öffnen
fxa-not-signed-in = Nicht angemeldet
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privat
floorp-toggle-private-container = 
    .label = In Private/No Container wieder öffnen
    .accesskey = P
open-in_private-container = 
    .label = In neuem Tab mit privatem Container öffnen
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Open in Split View
floorp-split-view-fixed-menu = 
    .label = Split this Tab in a Tab without Split View
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Remove Split View
split-view-title = Split View Settings
split-view-position = Position
split-view-flex-type = Flex Type
split-view-position-top = Top Side
split-view-position-left = Default
split-view-position-right = Reverse
split-view-flex-column = Vertical
split-view-flex-row = Horizontal
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Scannen Sie den QR-Code mit Ihrem Handy
qrcode-generate-page-action = 
    .tooltiptext = Teilen Sie diese Seite mit Ihrem Handy
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Unified Extensions Button
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Als App installieren
    .tooltiptext = Diese Website als App installieren
ssb-page-action-title = Als App installieren
ssb-app-open-button = 
    .label = In App öffnen
ssb-app-install-button = 
    .label = Installieren
ssb-app-cancel-button = 
    .label = Abbrechen
floorp-open-manage-ssb-page = 
    .label = Installierte Web-Apps verwalten
appmenuitem-webapps = 
    .label = Web-Apps
appmenu-open-installed-apps-subheader = Installierte Web-Apps öffnen
appmenuitem-install-current-page = 
    .label = Diese Website als App installieren
appmenuitem-open-current-page = 
    .label = Diese Seite in der installierten App öffnen
appmenuitem-contextmenu-open-app = 
    .label = Diese App öffnen
appmenuitem-contextmenu-uninstall-app = 
    .label = Diese App deinstallieren

## Preferences

category-ssb = 
    .label = Web-Apps
    .tooltiptext = Web-Apps
category-ssb-title = Web-Apps
floorp-ssb-title = Web-Apps
floorp-ssb-description = Web-Apps sind Webseiten, die als Anwendungen installiert werden. Sie können diese von der Menüleiste in { -brand-short-name } oder von dem Windows-Startmenü öffnen.
ssb-preferences = Web-App-Einstellungen
floorp-enable-ssb = 
    .label = Web-Apps aktivieren
floorp-enable-ssb-with-experimental = 
    .label = Web-Apps aktivieren (experimentell)
floorp-enable-ssb-description = Diese Funktion ist auf Mac und Linux experimentell. Es wird empfohlen, diese Funktion unter Windows zu verwenden.
floorp-disable-toolbars = 
    .label = Symbolleisten in Web-Apps deaktivieren
floorp-disable-toolbars-description = Diese Einstellung wird alle Erweiterungen und Symbolleisten im Web-Apps Fenster ausblenden.
ssb-installed-list-title = Installierte Web-Apps
ssb-uninstall-title = Web-App deinstallieren
ssb-uninstall-message = Sind Sie sicher, dass Sie diese Web-App von { -brand-short-name } entfernen möchten?
ssb-uninstall-button = 
    .label = Deinstallieren
ssb-uninstall-cancel = Abbrechen
######################################################################### Download Notification ###############################################################
floorp-started-download = Download gestartet
floorp-finished-download = Download abgeschlossen
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } ist auf dem neuesten Stand!
floorp-notificationContent-latest = { -brand-short-name } ist auf dem neuesten Stand. Sie verwenden die neueste Version von { -brand-short-name }.
floorp-notificationTitle = Neue Version von { -brand-short-name } ist verfügbar!
floorp-notificationContent = Klicken Sie hier, um die neueste Version herunterzuladen.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
