# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> yra viena iš Japonijoje sukurtų vietinių naršyklių. Ji sukurta "Firefox" pagrindu ir toliau veikia pagal <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, siekiant tobulinti žiniatinklį. Norite padėti? <label data-l10n-name="helpus-donateLink">Paaukokite</label>
icon-creator = Ikonų kūrėjas <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> ir <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = <label data-l10n-name="about-contributor">autorių ir kūrėjų sąrašas</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Dizainas
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Norint pritaikyti pakeitimus, reikia iš naujo paleisti
tab-width = Mažiausias skirtukų plotis
preferences-tabs-newtab-position = Naujo skirtuko vieta
open-new-tab-use-default = 
    .label = Atidaryti naujus skirtukus numatytoje padėtyje
open-new-tab-at-the-end = 
    .label = Atidaryti naujus skirtukus skirtukų juostos pabaigoje
open-new-tab-next-to-current = 
    .label = Atidaryti naujus skirtukus šalia esamo skirtuko
multirow-tabs-limit = 
    .label = Įjungti eilučių apribojimą kelių eilučių skirtukuose
multirow-tabs-newtab = 
    .label = Padėti „Atidaryti naują skirtuką“ mygtuką skirtukų eilutės pabaigoje
multirow-tabs-value = Eilučių skaičius, kai įjungtą kelių eilučių skirtukai
enable-tab-sleep = 
    .label = Įjungti miegančius skirtukus
tab-sleep-timeout-minutes-value = Skirtukai bus užmigdyti, kai bus neaktyvūs per (minučių)
tab-sleep-settings-button = Nustatymai...
tab-sleep-settings-dialog-title = 
    .title = Miegančių skirtukų nustatymai
tab-sleep-settings-dialog-excludehosts-label = Neįtraukti šeimininkų
tab-sleep-settings-dialog-excludehosts-label-2 = Vienoje eilutėje įveskite po vieną kompiuterį.
tab-sleep-tab-context-menu-excludetab = Laikyti skirtuką atsibudęs
enable-tab-scroll-change = 
    .label = Perjungti skirtukus slinkdami pele
enable-tab-scroll-reverse = 
    .label = Atvirkštinė slinkties skirtukų kryptis
enable-tab-scroll-wrap = 
    .label = Apvynioti slenkančius skirtukus prie krašto
enable-double-click-block = 
    .label = Close tabs with a double click
enable-show-pinned-tabs-title = 
    .label = Rodyti prisegtų skirtukų pavadinimus
tabbar-preference = Skirtukų juosta
tab-normal-mode = 
    .label = Numatytas
hide-horizontality-tabs = 
    .label = Paslėpti skirtukus horizontalioje skirtukų juostoje
verticalTab-setting = 
    .label = Optimizuoti naršyklę vertikaliai skirtukų juostai
move-tabbar-position = 
    .label = Rodyti skirtukų juostą po įrankių juosta
tabbar-on-bottom = 
    .label = Rodyti skirtukų juostą lango apačioje
tabbar-favicon-color = 
    .label = Nuspalvinti skirtuko juostos spalva pagal svetainės favikonos spalvą
tabbar-style-preference = Skirtukų juostos stilius
horizontal-tabbar = 
    .label = Horizontali skirtukų juosta
tabbar-style-description = Kad šis nustatymas būtų pilnai pritaikytas, reikia iš naujo paleisti „{ -brand-short-name }“ .
multirow-tabbar = 
    .label = Kelių eilučių skirtukų juosta
vertical-tabbar = 
    .label = Vertikali skirtukų juosta (eksperimentinuojama)
native-vertical-tab-show-right = 
    .label = Rodyti vertikalią skirtukų juostą dešinėje lango pusėje
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = Paslėpti vertikalią skirtukų juostą
floorp-show-vertical-tab-newtab-button = 
    .label = Rodyti mygtuką „Atidaryti naują skirtuką“ vertikalioje skirtukų juostoje
floorp-show-vertical-tab-scrollbar = 
    .label = Show scrollbar on Vertical Tab Bar
TST = Medžio stiliaus skirtukas
about-TST = „Tree Style Tab“ yra populiarus papildinys, kuris rodo skirtukus medžio pavidalo struktūroje. Šis priedas jau iš anksto yra integruotas į „{ -brand-short-name }“. Norėdami aktyvuoti „{ -brand-short-name } Tree Style Tab“, įdiekite priedą.
treestyletab-Settings = 
    .label = Paslėpti medžio stiliaus skirtuką
sidebar-reverse-position-toolbar = Rodyti šonines juostas kitoje pusėje
bookmarks-bar-settings = Žymeklių įrankių juosta (galima pasirnkti tik vieną nustatymą)
bookmarks-focus-mode = 
    .label = Paslėpti žymeklių įrankių juostą, nebent užvedus pelės žymeklį virš naršymo juostos
bookmarks-bottom-mode = 
    .label = Rodyti žymeklių įrankių juostą „{ -brand-short-name }“ apačioje
navbar-settings = Naršymo juosta
show-nav-bar-bottom = 
    .label = Rodyti įrankių juostą „{ -brand-short-name }“ apačioje (eksperimentinuojama)
material-effect = 
    .label = Leisti "Mica For Everyone" keisti naršyklės dizainą
disable-extension-check-compatibility-option = 
    .label = Netikrinti suderinamumo su priedais
other-preference = Kiti pasirinkimai
enable-userscript = 
    .label = Įgalinti senesnius komponentus
about-userscript = Įjungus šią funkciją gali atsirasti netikėtos klaidos.
search-positon-top = 
    .label = Rodyti paieškos juostą puslapio viršunėje
allow-auto-restart = 
    .label = Automatiškai paleisti iš naujo, kai pakeičiami nustatymai, kuriuos reikia paleisti iš naujo
disable-fullscreen-notification = 
    .label = Nerodyti pranešimo įėjus į išplėtus ekraną

## Browser Theme

system-color-settings = Kai kurie dizainai turi šviesų ir tamsų rėžimą. Pasirinkite, kurį režimą norite naudoti.
preferences-theme-appearance-header = Dizaino režimas
system-theme-dark = 
    .label = Tamsiai
system-theme-light = 
    .label = Šviesiai
system-theme-auto = 
    .label = Sekite mano sistemos išvaizdą

## User interface preferences

ui-preference = Naršyklės išvaizda
preferences-browser-appearance-description = Pasirinkite dizainą, kurį norite naudoti „{ -brand-short-name }“ naršyklėje. Kai kurie dizainai gali nesusiderinti su jūsų konfigūracija.
firefox-proton = 
    .label = „Firefox Proton“ dizainas
firefox-photon-lepton = 
    .label = „Firefox Photon・Lepton“ dizainas
floorp-fluentUI = 
    .label = „Microsoft Fluent“ dizainas (nebenaudojamas)
floorp-fluerialUI = 
    .label = „{ -brand-short-name } Fluerial“ dizainas (nebenaudojamas)
floorp-gnomeUI = 
    .label = GNOME dizainas (nebenaudojamas)

## Download Manager

download-notification-preferences = Atsisiuntimo pranešimai
start-always-notify = 
    .label = Pranešti tik tada, kai pradedamas atsisiuntimas
finish-always-notify = 
    .label = Pranešti tik tada, kai atsisiuntimas baigiamas
always-notify = 
    .label = Pranešti, kai pradedamas atsisiuntimas ir kai atsisiuntimas baigiamas
do-not-notify = 
    .label = Išjungti atsisiuntimo pranešimus

## Sidebar

profiles-button-label = Tvarkyti profilius
floorp-help-button-label = „{ -brand-short-name }“ Parama
appmenuitem-reboot = 
    .label = Perkrauti

## UserAgent

userAgent-preference = Vartotojo agentas
default-useragent-mode = 
    .label = Naudoti „Firefox“ vartotojo agentą (numatytasis nustatymas)
windows-chrome-useragent-mode = 
    .label = Apsimesti kaip „Chrome“ „Windows“ sistemoje
macOS-chrome-useragent-mode = 
    .label = Apsimesti kaip „Chrome“ „macOS“ sistemoje
linux-chrome-useragent-mode = 
    .label = Apsimesti kaip „Chrome“ „Linux“ sistemoje
mobile-chrome-useragent-mode = 
    .label = Apsimesti kaip „Chrome“ „iOS“ sistemoje
use-custom-useragent-mode = 
    .label = Naudoti pasirinktinį vartotojo agentą

## DMR UI

download-mgr-UI = 
    .label = Įjungti „SimpleUI“ atsisiuntimo tvarkyklę
downloading-red-color = 
    .label = Atsisiųnčiant, naudoti raudoną atsisiuntimo piktogramą
sidebar-preferences = Šoninė juosta
bsb-preferences = Naršyklės tvarkyklės šoninės juostos nustatymai
view-sidebar2-right = 
    .label = Rodyti naršyklės tvarkyklės šoninę juostą dešinėje
enable-sidebar2 = 
    .label = Įjungti naršyklės tvarkyklės šoninės juostą
visible-bms = 
    .label = Rodyti naršyklės tvarkyklės šoninę juostą
hide-bms-to-unload-panel = 
    .label = Iškrauti skydelį, kai paslepiamas skydelis
enable-addons-in-sidebar2-with-experimental = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar (experimental)
enable-addons-in-sidebar2 = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar
sidebar2-enable-addons-desc = If this setting is enabled, ad blocking extensions and other extensions will work in the sidebar. However, not all extensions will work.
custom-URL-option = Nustatyti žiniatinklio skydelio URL adresus
set-custom-URL-button = 
    .label = Nustatyti pasirinktinius URL adresus...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Naršyklės tvarkyklės šoninė juosta
bsb-context = Naudokite ši konteinerį
bsb-userAgent-label = 
    .label = Naudoti mobilų vartotojo agentą, šiame žiniatinklio skydelyje
bsb-width = Plotis (jei nustatyta 0, bus naudojama visuotinė vertė)
bsb-page = Atidaryti puslapį
bsb-add = Pridėti žiniatinklio skydelį naršyklės tvarkytuvo šoninėje juostoje
bsb-setting = Web skydelio nustatymai
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Svetainė
sidebar2-pref-delete = 
    .label = Ištrinti
sidebar2-pref-setting = 
    .label = Nustatymai
sidebar2-global-width = Visuotinio žiniatinklio skydelio plotis
use-icon-provider-option = Naudoti piktogramos teikėją
use-icon-provider-option-google = 
    .label = „Google“
use-icon-provider-option-duckduckgo = 
    .label = „DuckDuckGo“
use-icon-provider-option-yandex = 
    .label = „Yandex“ (galima Kinijoje)
use-icon-provider-option-hatena = 
    .label = „Hatena“ (galima Kinijoje)
memory-and-performance = Atmintis ir greitis
min-memory = 
    .label = Minimalus atminties naudojimas (mažas greitis)
balance-memory = 
    .label = Atminties naudojimo ir greičio balansas
max-memory = 
    .label = Greičiausias greitis (didelis atminties naudojimas)
delete-border-and-roundup-option = 
    .label = Suapvalinti puslapių kampus
STG-smilar-workspaces-option = 
    .label = Make "Simple Tab Groups" add-on buttons look like Workspaces buttons

## DualTheme

dualtheme-enable = 
    .label = Įjungti dvigubini stilių
newtab-background = „{ -brand-short-name }“ pagrindinis fonas
newtab-background-random-image = 
    .label = Įvairius vaizdus iš „Unsplash“
newtab-background-gradation = 
    .label = Gradientas
newtab-background-not-background = 
    .label = Išjungti foną
newtab-background-selected-image = 
    .label = Pasirinktinis aplankas...
newtab-background-selected-one-image = 
    .label = Custom image...
newtab-background-folder = Naudokite vaizdus iš šio aplanko:
newtab-background-image = Use image :
newtab-choose-image = Choose Image...
newtab-background-folder-reload = 
    .label = Perkrauti vaizdus
newtab-background-folder-default = 
    .label = Atkurti numatytuosius nustatymus
newtab-background-folder-open = 
    .label = Atidaryti aplanką
newtab-background-folder-choose = Pasirinkite vaizdų aplanką...
newtab-background-image-choose = Choose image...
newtab-background-extensions = Naudokite vaizdus su šiais failų plėtiniais (atskiriami kableliais)
disable-blur-on-newtab = 
    .label = Disable blur effect in { -brand-short-name } Home
disable-releasenote-on-newtab = 
    .label = Disable Release Note and Support Links in { -brand-short-name } Home
disable-imagecredit-on-newtab = 
    .label = Disable image credit (Unsplash) in { -brand-short-name } Home

## Lepton Preferences

about-lepton = Pritaikyti „{ -brand-short-name }“ su „Lepton“
lepton-preference-button = 
    .label = „Lepton“ nustatymai...
    .accesskey = L
lepton-header = „Lepton“ nustatymai
lepton-preference = „Lepton“ nustatymai
photon-mode = 
    .label = Naudoti "Photon" dizainą
lepton-mode = 
    .label = Naudoti „Lepton“ dizainą
protonfix-mode = 
    .label = Naudokite patobulintą „Proton“ dizainą
autohide-preference = Automatiškai paslėpti naršyklės elementus
floorp-lepton-enable-tab-autohide = 
    .label = Automatiškai paslėpti skirtukus
floorp-lepton-enable-navbar-autohide = 
    .label = Automatiškai paslėpti įrankių juostą
floorp-lepton-enable-sidebar-autohide = 
    .label = Automatiškai paslėpti šoninę juostą
floorp-lepton-enable-urlbar-autohide = 
    .label = Automatiškai paslėpti adreso juostą
floorp-lepton-enable-back-button-autohide = 
    .label = Automatiškai paslėpti grįžimo mygtuką
floorp-lepton-enable-forward-button-autohide = 
    .label = Automatiškai paslėpti pirmyn mygtuką
floorp-lepton-enable-page-action-button-autohide = 
    .label = Automatiškai paslėpti adreso juostos mygtukus
floorp-lepton-enable-toolbar-overlap = 
    .label = Rodyti įrankių juostą virš svetainės turinio
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Automatiškai paslėpti įrankių juostą, kai rodomas „ltr“ turinys
hide-preference = Naršyklės elementų valdymas
floorp-lepton-enable-tab_icon-hide = 
    .label = Paslėpti skirtukų piktogramas
floorp-lepton-enable-tabbar-hide = 
    .label = Paslėpti skirtukų juostą
floorp-lepton-enable-navbar-hide = 
    .label = Paslėpti įrankių juostą
floorp-lepton-enable-sidebar_header-hide = 
    .label = Paslėpti šoninės juostos antraštes
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Paslėpti adreso juostos piktogramas
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Paslėpti žymeklių juostos piktogramas
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Paslėpti žymeklių juostos etiketes
floorp-lepton-enable-disabled_menu-hide = 
    .label = Paslėpti išjungtus kontekstinio meniu elementus
floorp-lepton-disable-userChrome-icon = 
    .label = Išjungti „Lepton“ kontekstinio meniu ir skydelio meniu piktogramas
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Įjungti „Lepton“ kontekstinio meniu piktogramas
positon-preferences = Padėties koregavimas
floorp-lepton-enable-centered-tab = 
    .label = Centruoti etikėtes skirtukuose
floorp-lepton-enable-centered-urlbar = 
    .label = Centruoti tekstą adresinėje juostoje
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Centruoti žymeklių juostos elementus
urlbar-preferences = Adresų juosta
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Perkelti adresinės juostos piktogramas į kairę pusė
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Rašydami tekstą, rodyti „Go“ mygtuką
floorp-lepton-enable-always-show-page_action = 
    .label = Visada rodyti puslapio veiksmus adreso juostoje
tabbar-preferences = Skirtukų juosta
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Skirtukų juosta antraštinėje juostoje
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Sujungti skirtukų juostą ir įrankių juostą
lepton-sidebar-preferences = Šoninė juosta
floorp-lepton-enable-overlap-sidebar = 
    .label = Rodyti šoninę juostą virš svetainės turinio
floorp-home-mode-choice-default = 
    .label = „{ -brand-short-name }“ Pagrindas (numatytasis)
floorp-home-prefs-content-header = „{ -brand-short-name }“ Pagrindinis turinys
floorp-home-prefs-content-description = Pasirinkite turinį, kurį norite matyti „{ -brand-short-name }“ pagrindiniame puslapyje.

## Notes

floorp-notes = „{ -brand-short-name }“ Užrašai
restore-from-backup = Atkurti užrašus iš atsarginės kopijos
enable-notes-sync = 
    .label = Įjungti „{ -brand-short-name }“ užrašu sinchronizavima
about-notes-backup-tips = „{ -brand-short-name }“ užrašai naudoja „Firefox“ sinchronizavima, kad galėtumete sinchronizuoti jūsų užrašus su kitais prietaisais. Jei prarasit užrašus, jūs galėsite atkurti užrašus iš atsarginės kopijos. Atsarginė kopija kuriama, kai paleidžiate „{ -brand-short-name }“.
notes-sync-description = Šis gali išspresti turinio praradimo problema, dėl sinchronizavimo metu perrašytų užrašu.
backuped-time = Atsarginė kopija sukurta
notes-backup-option = Atsarginės kopijos nustatymai
backup-option-button = Atsarginės kopijos nustatymai...
restore-from-backup-prompt-title = „{ -brand-short-name }“ užrašu atkurimo paslauga
restore-from-this-backup = Atkurti užrašus į tokią pačią būseną kaip atsarginėje kopijoje?
restore-button = Atkurti

## user.js

header-userjs = user.js
userjs-customize = Tinkinti „{ -brand-short-name }“ su user.js
about-userjs-customize = user.js - tai konfigūracijos failas, kuriuo gali pakeisti „{ -brand-short-name }“. user.js failai atsisiunčiami iš interneto ir pakeičia dabartinį user.js failą. Prieš tęsdami, sukurkite dabartinio user.js failo atsarginę kopiją. user.js konfigūracijos bus pritaikytos automatiškai iš naujo paleidus „{ -brand-short-name }“.
userjs-label = user.js sąrašas
userjs-prompt = Taikyti šį user.js?
apply-userjs-attention = Pritaikius naują user.js, bus perrašytas dabartinis user.js failas.
apply-userjs-attention2 = Prieš tęsdami sukurkite atsarginę dabartinio user.js failo kopiją.
userjs-button = user.js Nustatymai...
userjs-select-option = Tvarkykite šiuo metu „{ -brand-short-name }“ naudojamą user.js, kad pagerintumėte greitį ir privatumą.
apply-userjs-button = Pritaikyti

## userjs Options

default-userjs-label = „{ -brand-short-name }“ numatytosios nuostatos
about-default-userjs = Telemetrija išjungta. Gerai subalansuotas „{ -brand-short-name }“ su įvairiais pritaikymais.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS pagal nutylėjimą. Visiška slapukų apsauga su svetainių izoliavimu. Patobulintas būsenos ir tinklo skaidymas. Įvairūs kiti patobulinimai.
default-label = Yokoffing įsipareigojimų nevykdymas
about-default = Visi svarbiausi dalykai. Nė vieno lūžio. Tai jūsų user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Labai padidinkite „Firefox“ naršymo greitį. Užlenkit „Chrome“ naršymo greitį!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Sutvarkyti naują skirtuko puslapį. Pašalinti „Pocket“. Atkurti kompatiškąjį rėžimą kaip nustatymą. Stabdyti tinklalapio pranešimus, iššokančius langus ir kitus nemalonumus.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Gauti švelnu slinkima, kaip „Edge“, tavo mėgstamausiame naršyklėje, arba pasirinkite kažką kito kas tinka jūsų stilių.
select-workspace = Pasirinkti aplinką
workspace-select-icon = Pasirinkite aplinkos piktogramą
    .label = Pasirinkite aplinkos piktogramą
workspace-select-container = Pasirinkite konteinerio skirtuką
    .label = Pasirinkite konteinerio skirtuką
workspace-customize = 
    .title = Pritaikykite aplinką
floorp-no-workspace-container = 
    .label = No Container
workspace-icon-article = 
    .label = Article
workspace-icon-book = 
    .label = Book
workspace-icon-briefcase = 
    .label = Darbas
workspace-icon-cart = 
    .label = Apsipirkimas
workspace-icon-chat = 
    .label = Chat
workspace-icon-chill = 
    .label = Privatus
workspace-icon-circle = 
    .label = Apskritimas
workspace-icon-compass = 
    .label = Kompasas
workspace-icon-code = 
    .label = Code
workspace-icon-dollar = 
    .label = Bankas
workspace-icon-fence = 
    .label = Tvora
workspace-icon-fingerprint = 
    .label = Asmeninis
workspace-icon-food = 
    .label = Maistas
workspace-icon-fruit = 
    .label = Vaisiai
workspace-icon-game = 
    .label = Game
workspace-icon-gear = 
    .label = Pavarų dėžė
workspace-icon-gift = 
    .label = Dovana
workspace-icon-key = 
    .label = Key
workspace-icon-lightning = 
    .label = Lightning
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notes
workspace-icon-paint = 
    .label = Paint
workspace-icon-photo = 
    .label = Photo
workspace-icon-pin = 
    .label = Pin
workspace-icon-pet = 
    .label = Augintinis
workspace-icon-question = 
    .label = Klausimas
workspace-icon-smartphone = 
    .label = Smart Phone
workspace-icon-star = 
    .label = Žvaigždė
workspace-icon-tree = 
    .label = Medis
workspace-icon-vacation = 
    .label = Atostogos
workspace-icon-love = 
    .label = Love
workspace-icon-moon = 
    .label = Moon
workspace-icon-music = 
    .label = Music
workspace-icon-user = 
    .label = User
# Custom Keyboard Shortcuts
floorp-CSK-title = Pasirinktinieji klaviatūros spartieji klavišai
floorp-CSK-description = Pritaikykite „{ -brand-short-name }“ klaviatūros sparčiuosius klavišus. „{ -brand-short-name }“ turi daugiau nei 80 pritaikomų klaviatūros sparčiųjų klavišų! Duplikuoti klaviatūros spartieji klavišai neveiks. Iš naujo paleiskite „{ -brand-short-name }“, kad pritaikytumėte šiuos nustatymus.
disable-fx-actions = 
    .label = Išjungti „Mozilla Firefox“ klaviatūros sparčiuosius klavišus
customize-Action = 
    .label = Pridėti spartųjį klavišą
remove-Action = 
    .label = Pašalinti spartujį klavišą
CSK-reset-title = Iš naujo nustatyti pakeistus klaviatūros sparčiuosius klavišus
CSK-reset-description = Iš naujo nustayti pakeistus klaviatūros sparčiuosius klavišus į „{ -brand-short-name }“ numatytuosius nustatymus.
CSK-reset-label = Iš naujo nustatyti pakeistus klaviatūros sparčiuosius klavišus
CSK-reset-button = Atkurti numatytuosius nustatymus
CSK-manage-title = Tvarkykite sparčiuosius klavišus
CSK-remove-shortcutkey = Pašalinti pakeistą klaviatūros kombinaciją?
CSK-remove-shortcutkey-description = Ar tikrai norite pašalinti šią sparčiąją klaviatūros kombinaciją?
CSK-restore-default = Atkurti numatytąsias nuostatas?
CSK-restore-default-description = Atkurti „{ -brand-short-name }“ numatytuosius klaviatūros sparčiuosius klavišus? Tavo dabartiniai spartieji klavišai bus prarasti.
CSK-reboot-browser-label = Iš naujo paleiskite „{ -brand-short-name }“, kad pritaikytumėte šiuos nustatymus
CSK-reboot-browser-button = Iš naujo paleiskite „{ -brand-short-name }“
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Dabartinė sparčioji klaviatūros kombinacija: { $key } ir { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Dabartinė sparčioji klaviatūros kombinacija: { $key }.
CSK-keyborad-shortcut-is-changed = (nepritaikyta)
floorp-custom-actions-tab-action = Skirtuko veiksmai
floorp-custom-actions-page-action = Puslapio veiksmai
floorp-custom-actions-visible-action = Matomi veiksmai
floorp-custom-actions-search-action = Paieškos veiksmai
floorp-custom-actions-tools-action = Įrankių veiksmai
floorp-custom-actions-bookmark-action = Žymeklio veiksmai
floorp-custom-actions-open-page-action = Atidaryto puslapio veiksmai
floorp-custom-actions-history-action = Istorijos veiksmai
floorp-custom-actions-pip-action = Vaizdas paveikslelyjė veiksmai
floorp-custom-actions-downloads-action = Atsisiuntimo veiksmai
floorp-custom-actions-sidebar-action = Veiksmai šoninėje juostoje
floorp-custom-actions-bms-action = Naršyklės tvarkyklės šoninės juostos veiksmai
floorp-custom-actions-split-view-action = Split View Actions
floorp-custom-actions-workspaces-action = Workspaces Actions
floorp-custom-actions-custom-action = Pasirinktiniai veiksmai (eksperimentuojama)

## Mouse Gestures

mouse-gesture = Pelės gestai
mouse-gesture-description = Norint naudoti pelės gestus su „{ -brand-short-name }“, reikia įdiegti „Gesturefy“.
Gesturefy = „Gesturefy“
about-Gesturefy = „Gesturefy“ - plėtinys, kuris prideda pelės gestus į naršykle. Jei „{ -brand-short-name }“ suranda šio priedo įdiegimą, į „Gesturefy“ bus pridėtos gestų komandos, kurios yra prieinamos tik „{ -brand-short-name }“ naršyklėje. Be to, šis papildinys gali veikti su naujais skirtukais!
# Translate
TWS = Versti žiniatinklio puslapį
about-TWS = Išverskite puslapį realiuoju laiku naudodami „Google“ arba „Yandex“. Taip pat galite išversti pasirinktą tekstą arba visą puslapį.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Privatumo centras
block-more-tracker = Blokuoti daugiau skelbimų ir sekėjų
block-tracker = Šiame skyriuje pateikiami plėtiniai, skirti skelbimams ir sekėjams blokuoti.
view-at-AMO = Peržiūrėti šį papildinį addons.mozilla.org
uBlock-Origin = „uBlock Origin“
about-uboori = „uBlock Origin“ blokuoja skelbimus, plačias sekimo priemones ir kitas pavojingas svetaines.
Facebook-Container = „Facebook“ konteineris
about-Facebook-Container = Neleiskite „Facebook“ sekti jūsų internete. „Facebook Container“ plėtinys padeda kontroliuoti ir atskirti savo veiklą internete nuo „Facebook“.

## Fingerprinting

fingerprint-header = Atsispirti pirštų atspaudų paėmimui ir IP adresų nutekėjimui
block-fingerprint = Pirštų atspaudai - sekimo mechanizmas, pagrįstas unikaliomis jūsų naršyklės ir operacinės sistemos funkcijomis. Šiame skyriuje pateikiami nustatymai, kuriais galima dar labiau sustiprinti šią apsaugą, palyginus su numatytuoju blokavimu.
enable-firefox-fingerprint-protections = Įgalinti stiprią apsaugą nuo pirštų atspaudų
about-firefox-fingerprint-protection = Įjungus „Firefox“ apsauga, tai apima priverstinio šviesos rėžimas, išjungiama kai kurių API ir t. t.. Kai kurie puslapiai gali neveikti.
fingerprint-Protection = 
    .label = Apsauga nuo pirštų atspaudų
html5-canvas-prompt-settings = 
    .label = Automatiškai atmetami prieigos patvirtinimo raginimai, susiję su HTML5 vaizdo duomenimis
canvas-prompt = Neleidžia svetainėms naudoti drobės skaitymo raginimo, nebent tai leidžiama rankiniu būdu.
disable-webgl = 
    .label = Išjungti „WebGL“
about-webgl = „WebGL“ yra „Javascript“ API, kuriis naudojamas grafiniams vaizdams, pagal kurį galima nustatyti GPU.
Canvas-Blocker = „Canvas Blocker“
about-CB = Šis priedas suklastoja duomenis, naudojamus pirštų atspaudų nustatymo metodais.
WebRTC-connection = „WebRTC“ yra standartas, kuriuo užtikrinamas skambinimas realiuoju laiku. Jei išjungsite šį nustatymą, negalėsite naudotis „Discord“ ir kt.
WebRTC = 
    .label = Įjungti „WebRTC“ ryšį
################################################################### browser ###############################################################

rest-mode = Pertraukėlė...
rest-mode-description = „{ -brand-short-name }“ šiuo metu yra sustabdytas. Kad tęsti, paspauskite „ENTER“ arba „OK“.
Sidebar2 = 
    .label = Naršyklės tvarkyklės šoninė juosta
    .tooltiptext = Pakeisti šoninės juostos matomumą
sidebar2-mute-and-unmute = 
    .label = Išjungti / įjungti šio skydelio garsą
sidebar2-unload-panel = 
    .label = Iškrauti šį skydelį
sidebar2-change-ua-panel = 
    .label = Perjungti mobilų vartotojo agentą
sidebar2-delete-panel = 
    .label = Ištrinti šį skydelį
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom In
sidebar2-zoom-out = 
    .label = Zoom Out
sidebar2-reset-zoom = 
    .label = Reset Zoom
sidebar2-close-button = 
    .tooltiptext = Uždaryti šoninę juostą
sidebar-back-button = 
    .tooltiptext = Atgal
sidebar-forward-button = 
    .tooltiptext = Pirmyn
sidebar-reload-button = 
    .tooltiptext = Perkrauti
sidebar-go-index-button = 
    .tooltiptext = Eiti į pagrindą
sidebar-muteAndUnmute-button = 
    .tooltiptext = Perjungti šoninės juostos garsą
sidebar2-browser-manager-sidebar = Naršyklės tvarkyklė
show-browser-manager-sidebar = 
    .tooltiptext = Rodyti { sidebar2-browser-manager-sidebar } šoninę juostą
sidebar2-bookmark-sidebar = Žymės
show-bookmark-sidebar = 
    .tooltiptext = Rodyti { sidebar2-bookmark-sidebar } šoninę juostą
sidebar2-history-sidebar = Istorija
show-history-sidebar = 
    .tooltiptext = Rodyti { sidebar2-history-sidebar } šoninę juostą
sidebar2-download-sidebar = Atsisiuntimai
show-download-sidebar = 
    .tooltiptext = Rodyti { sidebar2-download-sidebar } šoninę juostą
sidebar2-notes-sidebar = Užrašai
show-notes-sidebar = 
    .tooltiptext = Rodyti { sidebar2-notes-sidebar } šoninę juostą
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Priedai ir stiliai
sidebar2-hide-sidebar-button = 
    .tooltiptext = Hide Browser Manager Sidebar
sidebar-passwords-button = 
    .tooltiptext = Slaptažodžiai
sidebar-preferences-button = 
    .tooltiptext = Nustatymai
sidebar-keepWidth-button = 
    .tooltiptext = Toliau naudokite dabartinį šio skydo plotį
sidebar2-keep-width-for-global = 
    .label = Taikykite šį plotį visiems skydeliams be pasirinktinio pločio
bsb-context-add = 
    .label = Pridėti puslapį į žiniatinklio skydelį...
bsb-context-link-add = 
    .label = Pridėti nuorodą į žiniatinklio skydelį...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Atviras profilių katalogas
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Atkurti naršyklės CSS failus
    .accesskey = R
make-browsercss-file = 
    .label = Sukurti naršyklės CSS failą
    .accesskey = M
open-css-folder = 
    .label = Atidarykite CSS aplanką
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Redaguoti userChrome.css failą
edit-userContentCss-editor = 
    .label = Redaguoti userContent.css failą
not-found-editor-path = Nepavyko rasti CSS failo redaktoriaus
set-pref-description = Įveskite norimo CSS failo redaktoriaus failo vietą:
rebuild-complete = Atkurimas baigtas.
please-enter-filename = Įveskite failo pavadinimą.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Vėl atidaryti uždarytą skirtuką
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Leisti, kaip papildomas stilius
dual-theme-disable-addon-button = Išjungti papildomą stilių
dual-theme-enabled-heading = Įjungta, kaip papildomas stilius
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Būsenos juosta
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = „[{ -brand-short-name }]“ Atidaryti medžio stiliaus skirtuko skydelį
gf-floorp-open-tree-style-tab-description = Atidaryti medžio stiliaus skirtuko skydelį šoninėje juostoje
gf-floorp-open-bookmarks-sidebar-name = „[{ -brand-short-name }]“ Atidaryti žymeklių skydelį
gf-floorp-open-bookmarks-sidebar-description = Atidaryti žymeklių skydelį šoninėje juostoje
gf-floorp-open-history-sidebar-name = „[{ -brand-short-name }]“ Atidaryti istorijos skydelį
gf-floorp-open-history-sidebar-description = Atidaryti istorijos skydelį šoninėje juostoje
gf-floorp-open-synctabs-sidebar-name = „[{ -brand-short-name }]“ Atidaryti sinchronizuotų skirtukų skydelį
gf-floorp-open-synctabs-sidebar-description = Atidaryti sinchronizuotų skirtukų skydelį šoninėje juostoje
gf-floorp-close-sidebar-name = „[{ -brand-short-name }]“ Uždaryti šoninę juostą
gf-floorp-close-sidebar-description = Uždaryti šoninę juostą
gf-floorp-open-browser-manager-sidebar-name = „[{ -brand-short-name }]“ atidaryti BMS
gf-floorp-open-browser-manager-sidebar-description = Atidaryti naršyklės tvarkyklės šoninę juostą, jei buvo pakrautas naršyklės tvarkyklės šoninės juostos žiniatinklio skydelis
gf-floorp-close-browser-manager-sidebar-name = „[{ -brand-short-name }]“ Uždaryti BMS
gf-floorp-close-browser-manager-sidebar-description = Uždaryti naršyklės tvarkyklės šoninę juostą
gf-floorp-show-browser-manager-sidebar-name = „[{ -brand-short-name }]“ Perjungti BMS
gf-floorp-show-browser-manager-sidebar-description = Perjungti naršyklės tvarkyklės šoninė juostą
gf-floorp-hide-statusbar-name = „[{ -brand-short-name }]“ paslėpti būsenos juostą
gf-floorp-hide-statusbar-description = Paslėpti būsenos juostą
gf-floorp-show-statusbar-name = „[{ -brand-short-name }]“ perjungti būsenos juostą
gf-floorp-show-statusbar-description = Rodyti arba slėpti būsenos juostą
gf-floorp-open-extension-sidebar-name = „[{ -brand-short-name }]“ Atidaryti pasirinktą šoninės juostos priedą
gf-floorp-open-extension-sidebar-description = Atidaryti pasirinktą priedą ant šoninės juostos
gf-floorp-open-extension-sidebar-settings-addons-id = Šoninės juostos priedas
gf-floorp-open-extension-sidebar-settings-addons-id-description = Šoninės juostos atidarymo priedo pratęsimas
gf-floorp-open-extension-sidebar-settings-list-default = Pasirinkite priedą
gf-floorp-open-extension-sidebar-settings-list-unknwon = Nežinomas priedas
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Rasti atnaujinimai!
update-portable-notification-found-message = Atsisiunčiami atnaujinimai...
update-portable-notification-ready-title = Paruoštas atsinaujinimui!
update-portable-notification-ready-message = „{ -brand-short-name }“ bus atnaujinta kitame paleidime.
update-portable-notification-success-title = Sėkmingai atsinaujino!
update-portable-notification-success-message = Sėkmingai atsinaujino! Tikimės, kad jums patiks nauja „{ -brand-short-name }“ versija !
update-portable-notification-failed-title = Atnaujinti nepavyko.
update-portable-notification-failed-redirector-message = Atnaujinti nepavyko. Iš naujo paleidus naršyklę ši problema gali būti išspręsta.
update-portable-notification-failed-prepare-message = Nepavyko parengti naujinimo.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = „{ -brand-short-name }“ Nešiojamasis atnaujinimas
floorp-update-application-auto-enabled-option = 
    .label = Automatiškai patikrinkite, ar yra „{ -brand-short-name }“ portatyvinės versijos atnaujinimų. (Rekomenduojama)
##################################################################### Open link in external ###############################################################
openInExternal-title = Atidaryti kitame naršyklėje
open-link-in-external-enabled-option = 
    .label = Įgalinti „Atidaryti kitame naršyklėje“ funkcija
open-link-in-external-select-browser-option = Pasirinkite, kokia naršyklė bus atidaryta
open-link-in-external-select-browser-option-default = 
    .label = Numatytoji naršyklė
open-link-in-external-tab-context-menu = Atidaryti kitame naršyklėje
open-link-in-external-tab-dialog-title-error = Įvyko klaida:
open-link-in-external-tab-dialog-message-default-browser-not-found = Numatytoji naršyklė nerasta arba nėra sukonfigūruota.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Pasirinkta naršyklė neegzistuoja.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Naujas
memo-title-input-placeholder = Čia įrašykite pavadinimą
memo-input-placeholder = Parašykite arba įklijuokite atmintinę čia
delete-memo = Ištrinti
save-memo = Išsaugoti
memo-welcome-title = Sveiki atvykę!
memo-first-tip = Sveiki atvykę į „{ -brand-short-name }“ užrašus! Štai keletas instrukcijų, kaip ja naudotis!
memo-second-tip = „{ -brand-short-name }“ užrašai yra užrašų knygelė, kurioje galite išsaugoti kelias užrašus, kurios sinchronizuojasi visuose įrenginiuose. Norėdami įjungti sinchronizavimą, turite prisijungti prie „{ -brand-short-name }“ su savo „Firefox“ paskyra.
memo-third-tip = „{ -brand-short-name }“ užrašai bus išsaugota jūsų „{ -brand-short-name }“ nustatymuose ir bus sinchronizuotos visuose įrenginiuose naudojant „Firefox“ sinchronizavimą. Sinchronizavimo turiniai užšifruojami „Firefox Sync“ naudojant jūsų „Firefox“ paskyros slaptažodį, todėl niekas, išskyrus jus, nežinos jų turinio.
memo-import-data-tip = „Firefox“ sinchronizavime nėra atsarginės kopijos kūrimo paslauga. Rekomenduojame pačiam kurti atsargines kopijas.
memo-new-title = Naujas užrašas
chage-view-mode = Perjungti peržiūros / redagavimo režimą
readonly-mode = Neprisijungęs (galima tik skaityti)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = „Ablaze“ susisiekimas
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Išvalyti atsisiuntimus
    .accesskey = D
    .tooltiptext = Išvalyti atsisiuntimus
floorp-show-all-downloads = 
    .label = Rodyti visus atsisiuntimus
    .accesskey = S
    .tooltiptext = Rodyti visus atsisiuntimus
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Create new Workspace...
    .tooltiptext = Create a new Workspace
workspaces-manage-workspaces-button = 
    .label = Manage Workspaces...
    .tooltiptext = Manage your Workspaces
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Rename Workspace
    .accesskey = R
delete-this-workspace = 
    .label = Delete Workspace
    .accesskey = D
manage-this-workspaces = 
    .label = Manage Workspaces...
    .accesskey = M
workspace-new-default-name = New Workspace
workspace-default-name = Default
move-tab-another-workspace = 
    .label = Perkelti į kitą aplinką
rename-workspace-prompt-title = Rename Workspace
rename-workspace-prompt-text = Enter Workspace Name. Most characters and symbols can be used.
workspaces-toolbar-button = Workspaces
    .label = Workspaces
    .tooltiptext = Select a Workspace...

## Preferences

enable-workspaces = 
    .label = Enable Workspaces
    .tooltiptext = Enable Workspaces
workspace-notice = Workspaces will not work with this settings enabled unless the workspaces's button is placed on the toolbar. Use this setting if you want to disable Workspaces completely.
enable-workspaces-with-experimental = 
    .label = Enable Workspaces (Experimental)
    .tooltiptext = Enable Workspaces (Experimental)
workspace-warning = Workspaces cannot be used with Tab Group add-ons. If you want to use Tab Group add-ons, please disable Workspaces and restart { -brand-short-name }.
category-workspaces = 
    .label = Workspaces
    .tooltiptext = Workspaces
pane-workspaces-title = Workspaces
floorp-workspaces-title = „{ -brand-short-name }“ Aplinkos
floorp-workspace-settings-button = Aplinkos nustatymai...
change-to-close-workspace-popup-option = 
    .label = Uždaryti aplinkos iššokantį langą pasirinkus aplinką
manage-workspace-on-bms-option = 
    .label = Aplinkų tvarkymai naršyklės tvarkytuvo šoninėje juostoje
show-workspace-name-option = 
    .label = Rodyti aplinkos pavadinimą skirtuko juostos aplinkos mygtuke
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Dalijimosi režimas
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Prisijunkite prie „Firefox“ paskyros
welcome-to-floorp = Sveiki atvykę į „{ -brand-short-name }“!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Ready to dive in?
welcome-skip-to-start-browsing = Pradėkite naršyti
welcome-select-preferences-template = Choose a template
welcome-minimum-template = Pagrindinis
welcome-enable-basic-features = Enable basic features and settings for a simple experience.
welcome-medium-template = Numatytoji
welcome-enable-some-features = Enable additional features and settings for a better experience.
welcome-maximum-template = Išplėstinė
welcome-enable-most-of-features = Enable advanced features and settings. Recommended for experienced users.
welcome-go-next-setup = Kitas
welcome-select-browser-design = Pasirinkite naršyklės dizainą
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = „Lepton“ originalus dizainas
welcome-design-photon-name = „Lepton Photon“ dizainas
welcome-design-ProtonFix-name = „Lepton ProtonFix“ dizainas
welcome-design-floorp-fluerial-name = „{ -brand-short-name }“ Fluoro dizainas
welcome-design-firefox-proton-name = „Firefox Proton“ dizainas
welcome-import-data = Importuokite naršyklės duomenis
welcome-import-data-description = Quick setup! Import your bookmarks, passwords, and more from your old browser. Firefox users can import data from Firefox Sync.
welcome-import-data-button = Importuoti duomenis...
welcome-import-data-skip = Praleisti importą
welcome-select-button = Pasirinkite
welcome-finish-setup = Sąranka baigta!
welcome-finish-setup-description = You're all set! Other features like Vertical Tabs & Workspaces can be found in { -brand-short-name }'s Settings. Enjoy { -brand-short-name }!
welcomet-finish-setup = Pradėkite naršyti internete
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Keyboard Shortcuts
    .tooltiptext = Keyboard Shortcuts
category-CSK-title = Keyboard Shortcuts
shortcutkey-customize = 
    .title = Keyboard Shortcuts
select-shortcutkeyAction = Pasirinkite veiksmą, kurį norite paleisti
shortcutkey-customize-key-list-placeholder = Jūsų klaviatūros sparčiosios klaviatūros bus rodomos čia
shortcut-key-label = Keyboard Shortcut
start-input-button-listen = Start Listening
end-input-button-listen = Stop Listening
shortcut-key-description = Click "Start Listening" and enter your new keyboard shortcut for this action. Multiple keys can be used; however, keyboard shortcuts will not work if already assigned to other actions.
floorp-custom-actions-open-new-tab = Atidaryti naują skirtuką
    .label = Atidaryti naują skirtuką
floorp-custom-actions-close-tab = Uždaryti dabartinį skirtuką
    .label = Uždaryti dabartinį skirtuką
floorp-custom-actions-open-new-window = Atidaryti naują langą
    .label = Atidaryti naują langą
floorp-custom-actions-open-new-private-window = Atidaryti naują privatų langą
    .label = Atidaryti naują privatų langą
floorp-custom-actions-close-window = Uždaryti esamą langą
    .label = Uždaryti esamą langą
floorp-custom-actions-restore-last-session = Atkurti paskutinė sesiją
    .label = Atkurti paskutinė sesiją
floorp-custom-actions-restore-last-window = Atkurti paskutinį langą
    .label = Atkurti paskutinį langą
floorp-custom-actions-show-next-tab = Rodyti kitą skirtuką
    .label = Rodyti kitą skirtuką
floorp-custom-actions-show-previous-tab = Rodyti ankstesnį skirtuką
    .label = Rodyti ankstesnį skirtuką
floorp-custom-actions-show-all-tabs-panel = Rodyti visus skirtukus
    .label = Rodyti skirtukų sąrašą
floorp-custom-actions-send-with-mail = Siųsti paštu
    .label = Siųsti el. paštu
floorp-custom-actions-save-page = Išsaugoti puslapį
    .label = Išsaugoti puslapį
floorp-custom-actions-print-page = Spausdinti puslapį
    .label = Spausdinti puslapį
floorp-custom-actions-mute-current-tab = Perjungti dabartinio skirtuko nutildymą
    .label = Perjungti dabartinio skirtuko nutildymą
floorp-custom-actions-toggle-bookmark-toolbar = Perjungti žymeklių įrankių juostą
    .label = Perjungti žymeklių įrankių juostą
floorp-custom-actions-show-source-of-page = Rodyti puslapio šaltinį
    .label = Atidaryti puslapio šaltinį
floorp-custom-actions-show-page-info = Rodyti puslapio informaciją
    .label = Atidaryto puslapio informacija
floorp-custom-actions-zoom-in = Priartinti vaizdą
    .label = Priartinti vaizdą
floorp-custom-actions-zoom-out = Tolinti vaizdą
    .label = Padidinti mastelį
floorp-custom-actions-reset-zoom = Iš naujo nustatyti vaizdo priartinimą
    .label = Iš naujo nustatyti vaizdo priartinimą
floorp-custom-actions-back = Atgal
    .label = Atgal
floorp-custom-actions-forward = Pirmyn
    .label = Pirmyn
floorp-custom-actions-reload = Perkrauti
    .label = Perkrauti
floorp-custom-actions-stop = Sustabdyti
    .label = Sustabdyti
floorp-custom-actions-force-reload = Priverstinis perkrovimas
    .label = Priverstinis perkrovimas
floorp-custom-actions-search-in-this-page = Paieška šiame puslapyje
    .label = Rasti puslapyje
floorp-custom-actions-show-next-search-result = Rodyti kitos paieškos žodį šiame puslapyje
    .label = Kitas „Rasti puslapyje“ rezultatas
floorp-custom-actions-show-previous-search-result = Rodyti ankstesnį paieškos žodį šiame puslapyje
    .label = Ankstesnis „Rasti puslapyje“ rezultatas
floorp-custom-actions-search-the-web = Paieška internete
    .label = Paieška internete
floorp-custom-actions-open-migration-wizard = Atidarykite migracijos vedlį
    .label = Atidarykite migracijos vedlį
floorp-custom-actions-quit-from-application = Išeiti iš programos
    .label = Baigti „{ -brand-short-name }“
floorp-custom-actions-enter-into-customize-mode = Keisti įrankių juostą
    .label = Atidarykite „{ -brand-short-name }“ taikymus
floorp-custom-actions-enter-into-offline-mode = Įeikite į neprisijungusį režimą
    .label = Įeikite į neprisijungusį režimą
floorp-custom-actions-open-screen-capture = Atidaryti ekrano fotografavimo įrankį
    .label = Padarykite ekrano nuotrauką
floorp-custom-actions-show-pip = Rodyti vaizdą paveikslėlyje
    .label = Rodyti vaizdą paveikslėlyje
floorp-custom-actions-bookmark-this-page = Pažymėkite šį puslapį
    .label = Pažymėkite šį puslapį
floorp-custom-actions-open-bookmarks-sidebar = Atidarykite skirtukų šoninę juostą
    .label = Atidaryti žymių šoninę juostą
floorp-custom-actions-open-bookmark-add-tool = Atidaryti žymių pridėjimo įrankį
    .label = Pridėti žyme
floorp-custom-actions-open-bookmark-add-toolbar = Atidaryti iškylantį langą „Pridėti naują žymę“
    .label = Įtraukti į žymeklių juostą
floorp-custom-actions-open-bookmarks-manager = Atidarykite žymeklių tvarkytuvę
    .label = Atidarykite žymeklių tvarkytuvę
floorp-custom-actions-show-bookmark-toolbar = Perjungti žymeklių įrankių juostą
    .label = Perjungti žymeklių įrankių juostą
floorp-custom-actions-open-general-preferences = Atidaryti bendrąsias nuostatas
    .label = Atidaryti bendrąsias nuostatas
floorp-custom-actions-open-privacy-preferences = Atidaryti privatumo nuostatos
    .label = Atidaryti privatumo nuostatos
floorp-custom-actions-open-workspaces-preferences = Atidaryti aplinkos nuostatas
    .label = Atidaryti aplinkos nuostatas
floorp-custom-actions-open-containers-preferences = Atidaryti konteinerių nuostatas
    .label = Atidaryti konteinerių nuostatas
floorp-custom-actions-open-search-preferences = Atidaryti paieškos nuostatas
    .label = Atidaryti paieškos nuostatas
floorp-custom-actions-open-sync-preferences = Atidaryti sinchronizavimo nuostatas
    .label = Atidaryti sinchronizavimo nuostatas
floorp-custom-actions-open-task-manager = Atidarykite užduočių tvarkytuvę
    .label = Atidaryti „{ -brand-short-name }“ užduočių tvarkyklę
floorp-custom-actions-open-home-page = Atidaryti „{ -brand-short-name }“ pagrindinį puslapį
    .label = Atidaryti „{ -brand-short-name }“ pagrindinį puslapį
floorp-custom-actions-open-addons-manager = Atidaryti priedus ir stilius
    .label = Atidaryti priedus ir temas
floorp-custom-actions-forget-history = Pamiršti istoriją
    .label = Pamiršti istoriją
floorp-custom-actions-quick-forget-history = Greitai pamiršti istoriją
    .label = Greitai pamiršti istoriją
floorp-custom-actions-clear-recent-history = Išvalyti naujausią istoriją
    .label = Išvalyti naujausią istoriją
floorp-custom-actions-search-history = Ieškoti istorijoje
    .label = Ieškoti istorijoje
floorp-custom-actions-manage-history = Tvarkyti istoriją
    .label = Tvarkyti istoriją
floorp-custom-actions-open-downloads = Atidaryti atsisiuntimus
    .label = Atidaryti atsisiuntimus
floorp-custom-actions-show-bsm = Rodyti naršyklės tvarkyklės šoninę juostą
    .label = Rodyti naršyklės tvarkyklės šoninę juostą
floorp-custom-actions-show-bookmark-sidebar = Rodyti žymeklių šoninę juostą
    .label = Rodyti žymeklių šoninę juostą
floorp-custom-actions-show-history-sidebar = Rodyti istorijos šoninę juostą
    .label = Rodyti istorijos šoninę juostą
floorp-custom-actions-show-synced-tabs-sidebar = Rodyti sinchronizuotų skirtukų šoninę juostą
    .label = Rodyti sinchronizuotų skirtukų šoninę juostą
floorp-custom-actions-reverse-sidebar = Atvirkštinė šoninės juostos padėtis
    .label = Atvirkštinė šoninės juostos padėtis
floorp-custom-actions-hide-sidebar = Paslėpti šoninę juostą
    .label = Paslėpti šoninę juostą
floorp-custom-actions-show-sidebar = Perjungti šoninę juostą
    .label = Perjungti šoninę juostą
floorp-custom-actions-toggle-sidebar = Toggle sidebar
    .label = Toggle sidebar
floorp-custom-actions-open-previous-workspace = Atidaryti ankstesnę aplinką
    .label = Atidaryti ankstesnę aplinką
floorp-custom-actions-open-next-workspace = Atidaryti kitą aplinką
    .label = Atidaryti kitą aplinką
floorp-custom-actions-show-panel-1 = Perjungti į 1 skydelį
    .label = Perjungti į 1 skydelį
floorp-custom-actions-show-panel-2 = Perjungti į 2 skydelį
    .label = Perjungti į 2 skydelį
floorp-custom-actions-show-panel-3 = Perjungti į 3 skydelį
    .label = Perjungti į 3 skydelį
floorp-custom-actions-show-panel-4 = Perjungti į 4 skydelį
    .label = Perjungti į 4 skydelį
floorp-custom-actions-show-panel-5 = Perjungti į 5 skydelį
    .label = Perjungti į 5 skydelį
floorp-custom-actions-show-panel-6 = Perjungti į 6 skydelį
    .label = Perjungti į 6 skydelį
floorp-custom-actions-show-panel-7 = Perjungti į 7 skydelį
    .label = Perjungti į 7 skydelį
floorp-custom-actions-show-panel-8 = Perjungti į 8 skydelį
    .label = Perjungti į 8 skydelį
floorp-custom-actions-show-panel-9 = Perjungti į 9 skydelį
    .label = Perjungti į 9 skydelį
floorp-custom-actions-show-panel-10 = Perjungti į 10 skydelį
    .label = Perjungti į 10 skydelį
floorp-custom-actions-open-split-view-on-left = Open current tab on left in split view
    .label = Open current tab on left in split view
floorp-custom-actions-open-split-view-on-right = Open current tab on right in split view
    .label = Open current tab on right in split view
floorp-custom-actions-close-split-view = Close split view
    .label = Close split view
floorp-custom-actions-custom-action-1 = Pasirinktinis veiksmas 1
    .label = Pasirinktinis veiksmas 1
floorp-custom-actions-custom-action-2 = Pasirinktinis veiksmas 2
    .label = Pasirinktinis veiksmas 2
floorp-custom-actions-custom-action-3 = Pasirinktinis veiksmas 3
    .label = Pasirinktinis veiksmas 3
floorp-custom-actions-custom-action-4 = Pasirinktinis veiksmas 4
    .label = Pasirinktinis veiksmas 4
floorp-custom-actions-custom-action-5 = Pasirinktinis veiksmas 5
    .label = Pasirinktinis veiksmas 5
floorp-custom-actions-rest-mode = Įjungti poilsio režimą
    .label = Įjungti poilsio režimą
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Paleisti
    .tooltiptext = Paleisti „{ -brand-short-name }“ su šiuo profiliu
floorp-profiles-in-use = Šis profilis yra naudojamas.
floorp-profiles-title = Profiliai
floorp-profile-manager = Profilio tvarkyklė
floorp-profiles-create = Sukurti profilį
floorp-profile = Profilis
    .label = Profilio tvarkyklė
    .tooltiptext = Atidaryti profilio tvarkyklę
fxa-not-signed-in = Neprisijungta
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privatus
floorp-toggle-private-container = 
    .label = Vėl atidaryti privačią / be konteinerio
    .accesskey = P
open-in_private-container = 
    .label = Atidaryti naujame skirtuke su privačiu konteineriu
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = Open in split view
splitview-show-on-right = 
    .label = Rodyti dešinėje
splitview-show-on-left = 
    .label = Rodyti kairėje
splitview-close-split-tab = 
    .label = Uždaryti padalytą skirtuką
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Nuskaitykite QR kodą su savo telefonu
qrcode-generate-page-action = 
    .tooltiptext = Bendrinkite šį puslapį su telefonu
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Suvienodintų plėtinių mygtukas
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Install app
    .tooltiptext = Install this site as an app
ssb-page-action-title = Įdiegti programą
ssb-app-open-button = 
    .label = Atidaryti programoje
ssb-app-install-button = 
    .label = Įdiegti
ssb-app-cancel-button = 
    .label = Atšaukti
floorp-open-manage-ssb-page = 
    .label = Tvarkyti įdiegtas žiniatinklio programas
appmenuitem-webapps = 
    .label = Žiniatinklio programos
appmenu-open-installed-apps-subheader = Atidaryti įdiegtas žiniatinklio programas
appmenuitem-install-current-page = 
    .label = Įdiekti šią svetainę kaip programa
appmenuitem-open-current-page = 
    .label = Atidaryti šią svetainę įdiegtoje programoje
appmenuitem-contextmenu-open-app = 
    .label = Atidaryti šią programą
appmenuitem-contextmenu-uninstall-app = 
    .label = Pašalinti šią programą

## Preferences

category-ssb = 
    .label = Web Apps
    .tooltiptext = Web Apps
category-ssb-title = Web Apps
floorp-ssb-title = Web Apps
floorp-ssb-description = Web Apps are websites that can be installed as apps. They can be launched from { -brand-short-name }'s menu panel or the Windows Start menu.
ssb-preferences = Web Apps Settings
floorp-enable-ssb = 
    .label = Enable Web Apps
floorp-enable-ssb-with-experimental = 
    .label = Enable Web Apps (Experimental)
floorp-enable-ssb-description = This feature is experimental on Mac and Linux. It is recommended to enable this feature on Windows.
floorp-disable-toolbars = 
    .label = Disable toolbars on Web Apps Window
floorp-disable-toolbars-description = This setting will hide all extensions and toolbars on Web Apps Window.
ssb-installed-list-title = Installed Web Apps
ssb-uninstall-title = Uninstall Web App
ssb-uninstall-message = Are you sure you want to uninstall this Web App from { -brand-short-name }?
ssb-uninstall-button = 
    .label = Uninstall
ssb-uninstall-cancel = Cancel
######################################################################### Download Notification ###############################################################
floorp-started-download = Download started
floorp-finished-download = Download finished
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } is up to date!
floorp-notificationContent-latest = { -brand-short-name } is up to date. You are using the latest version of { -brand-short-name }.
floorp-notificationTitle = New version of { -brand-short-name } is available!
floorp-notificationContent = Click to download the latest version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
