# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> é um dos navegadores domésticos desenvolvidos no Japão. Ele é baseado no Firefox e continua a operar sob <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, para melhorar a web. Quer ajudar? <label data-l10n-name="helpus-donateLink">Faça uma doação</label>
icon-creator = Criador de ícones <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> and <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Uma lista de colaboradores e desenvolvedores do <label data-l10n-name="about-contributor"></label>
#################################################################### about:preferences ####################################################################

pane-design-title = Projetar
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = É necessário reiniciar para aplicar as alterações
tab-width = Largura mínima das abas
preferences-tabs-newtab-position = Posição da nova aba
open-new-tab-use-default = 
    .label = Abrir novas abas na posição padrão
open-new-tab-at-the-end = 
    .label = Abrir novas abas no final da barra de guias
open-new-tab-next-to-current = 
    .label = Abrir novas abas ao lado da aba atual
multirow-tabs-limit = 
    .label = Ativar limite de linha para abas multi-linhas
multirow-tabs-newtab = 
    .label = Coloque o botão "Abrir uma nova aba" no final da linha inferior de abas
multirow-tabs-value = Número de linhas quando as abas multi-linhas estão ativadas
enable-tab-sleep = 
    .label = Habilitar abas de dormir
tab-sleep-timeout-minutes-value = As abas durarão após ficar inativo por (minutos)
tab-sleep-settings-button = Configurações...
tab-sleep-settings-dialog-title = 
    .title = Configurações de abas adormecidas
tab-sleep-settings-dialog-excludehosts-label = Excluir hosts
tab-sleep-settings-dialog-excludehosts-label-2 = Insira um host por linha.
tab-sleep-tab-context-menu-excludetab = Manter aba ativa
enable-tab-scroll-change = 
    .label = Alternar abas rolando com o mouse
enable-tab-scroll-reverse = 
    .label = Inverter a direção das abas de rolagem
enable-tab-scroll-wrap = 
    .label = Envolver as guias de rolagem na borda
enable-double-click-block = 
    .label = Fechar todas abas com clique duplo
enable-show-pinned-tabs-title = 
    .label = Exibir o título das abas fixadas
tabbar-preference = Barra de Abas
tab-normal-mode = 
    .label = Padrão
hide-horizontality-tabs = 
    .label = Ocultar abas na Barra de Abas Horizontal
verticalTab-setting = 
    .label = Otimizar navegador para a Barra de Abas Vertical
move-tabbar-position = 
    .label = Mostrar barra de guias abaixo da barra de ferramentas
tabbar-on-bottom = 
    .label = Exibir a Barra na parte inferior da janela
tabbar-favicon-color = 
    .label = Cor da barra de guias usando a cor do favicon do site atual
tabbar-style-preference = Tab Bar Style
horizontal-tabbar = 
    .label = Barra de Abas Horizontais
tabbar-style-description = É necessário reiniciar o { -brand-short-name } para aplicar totalmente esta configuração.
multirow-tabbar = 
    .label = Barra de Abas Multi-Linha
vertical-tabbar = 
    .label = Barra de Abas Verticais (experimental)
native-vertical-tab-show-right = 
    .label = Mostrar barra de guia vertical no lado direito da janela
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = Recolher Barra de Abas Verticais
floorp-show-vertical-tab-newtab-button = 
    .label = Mostrar o botão "Abrir uma nova aba" na Barra de Abas Verticais
floorp-show-vertical-tab-scrollbar = 
    .label = Mostrar a barra de rolagem na Barra de Abas Verticais
TST = Aba Estilo Árvore
about-TST = Tree Style Tab é uma extensão popular que permite exibir guias em uma estrutura similar a uma árvore. Esse complemento já está pré-integrado no { -brand-short-name }. Instale a extensão para ativar o Tree Style Tab do { -brand-short-name }.
treestyletab-Settings = 
    .label = Recolher aba do estilo de árvore
sidebar-reverse-position-toolbar = Mostrar barras laterais do outro lado
bookmarks-bar-settings = Barra de Favoritos (apenas uma opção pode ser usada por vez)
bookmarks-focus-mode = 
    .label = Ocultar barra de favoritos a menos que pairando sobre a barra de navegação
bookmarks-bottom-mode = 
    .label = Mostrar a barra de favoritos na parte inferior do { -brand-short-name }
navbar-settings = Barra de Ferramentas
show-nav-bar-bottom = 
    .label = Mostrar a barra de ferramentas na parte inferior do { -brand-short-name } (experimental)
material-effect = 
    .label = Permita que o Mica Para Todos modifique o design do navegador
disable-extension-check-compatibility-option = 
    .label = Não verifique compatibilidade com extensões (obsoleto)
other-preference = Outras Preferências
enable-userscript = 
    .label = Ativar componentes legados (obsoleto)
about-userscript = Habilitar este recurso pode causar bugs inesperados ou erros fatais.
search-positon-top = 
    .label = Exibir a Barra de Busca na parte superior da página
allow-auto-restart = 
    .label = Reiniciar automaticamente quando as configurações que requerem reinicialização forem alteradas
disable-fullscreen-notification = 
    .label = Não mostrar uma notificação ao entrar em tela cheia

## Browser Theme

system-color-settings = Alguns temas possuem modos claros e escuros - escolha qual modo você gostaria que esses temas usassem.
preferences-theme-appearance-header = Modo tema
system-theme-dark = 
    .label = Escuro
system-theme-light = 
    .label = Fino
system-theme-auto = 
    .label = Seguir a aparência do meu sistema

## User interface preferences

ui-preference = Aparência do navegador
preferences-browser-appearance-description = Escolha um design de terceiros embutido para usar no { -brand-short-name }. Alguns projetos podem não ser compatíveis com a sua configuração.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon➲ Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (descontinuado)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (descontinuado)
floorp-gnomeUI = 
    .label = Tema GNOME (descontinuado)

## Download Manager

download-notification-preferences = Baixar Notificações
start-always-notify = 
    .label = Notificar apenas ao iniciar downloads
finish-always-notify = 
    .label = Notificar apenas quando um download terminar
always-notify = 
    .label = Notificar quando iniciar downloads e quando um download terminar
do-not-notify = 
    .label = Desativar notificações de download

## Sidebar

profiles-button-label = Gerenciar perfis
floorp-help-button-label = Suporte { -brand-short-name }
appmenuitem-reboot = 
    .label = Reiniciar

## UserAgent

userAgent-preference = Agente de usuário (obsoleto)
default-useragent-mode = 
    .label = Usar o Navegador de Usuário do Firefox (Padrão)
windows-chrome-useragent-mode = 
    .label = Spoof Chrome no Windows
macOS-chrome-useragent-mode = 
    .label = Spoof Chrome no macOS
linux-chrome-useragent-mode = 
    .label = Spoof Chrome no Linux
mobile-chrome-useragent-mode = 
    .label = Spoof Chrome no iOS
use-custom-useragent-mode = 
    .label = Usar User Agent Personalizado

## DMR UI

download-mgr-UI = 
    .label = Habilitar o Gerenciador de Download SimpleUI
downloading-red-color = 
    .label = Usar o ícone de downloads vermelhos quando baixar
sidebar-preferences = Sidebar
bsb-preferences = Configurações da barra lateral do navegador
view-sidebar2-right = 
    .label = Exibir a barra lateral Gerenciador de Navegadores à direita
enable-sidebar2 = 
    .label = Ativar a barra lateral Gerenciador de Navegadores
visible-bms = 
    .label = Mostrar a barra lateral Gerenciador de Navegadores
hide-bms-to-unload-panel = 
    .label = Descarregar painel quando esconder painel
enable-addons-in-sidebar2-with-experimental = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar (experimental)
enable-addons-in-sidebar2 = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar
sidebar2-enable-addons-desc = Se esta opção estiver ativada, extensões de bloqueamento de anúncios e outras extensões funcionarão na barra lateral. Porém, nem todas as extensões funcionarão.
custom-URL-option = Definir URLs do Painel Web
set-custom-URL-button = 
    .label = Configurar URLs Personalizados...
    .accesskey = S.O.
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Barra lateral Gerenciador de Navegadores
bsb-context = Usar o seguinte Contêiner
bsb-userAgent-label = 
    .label = Use o Agente de Usuário Móvel neste Painel Web
bsb-width = Largura (se definida como 0, o valor global será usado)
bsb-page = Página a abrir
bsb-add = Adicionar Painel Web no Painel lateral Gerenciador de Navegadores
bsb-setting = Configurações do Web Panel
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = site
sidebar2-pref-delete = 
    .label = excluir
sidebar2-pref-setting = 
    .label = Confirgurações
sidebar2-global-width = Largura de painéis web globais
use-icon-provider-option = Usar Provedor de Ícones
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = Parafugo
use-icon-provider-option-yandex = 
    .label = Yandex (disponível na China)
use-icon-provider-option-hatena = 
    .label = Hatena (disponível na China)
memory-and-performance = Memória e Desempenho
min-memory = 
    .label = Uso mínimo de memória (baixo desempenho)
balance-memory = 
    .label = Uso e desempenho de memória de saldo
max-memory = 
    .label = Melhor Desempenho (alto uso de memória)
delete-border-and-roundup-option = 
    .label = Arredondar os cantos das páginas

## DualTheme

dualtheme-enable = 
    .label = Ativar Tema Duplo
newtab-background = { -brand-short-name } Fundo Home
newtab-background-random-image = 
    .label = Imagens aleatórias do Unsplash
newtab-background-gradation = 
    .label = Degradê
newtab-background-not-background = 
    .label = Desativar fundo
newtab-background-selected-image = 
    .label = Pasta personalizada...
newtab-background-selected-one-image = 
    .label = Imagem personalizada...
newtab-background-folder = Use imagens desta pasta:
newtab-background-image = Use imagem:
newtab-choose-image = Escolher imagem...
newtab-background-folder-reload = 
    .label = Reload images
newtab-background-folder-default = 
    .label = Restaurar Padrões
newtab-background-folder-open = 
    .label = Abrir pasta
newtab-background-folder-choose = Escolher pasta de imagens...
newtab-background-image-choose = Escolher imagem...
newtab-background-extensions = Usar imagens com essas extensões de arquivo (separadas por ",")
disable-blur-on-newtab = 
    .label = Desativar efeito de desfoque em { -brand-short-name } home
disable-releasenote-on-newtab = 
    .label = Desativar notas de versão e links de suporte em { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Desativar crédito de imagem (abertura) na página { -brand-short-name }

## Lepton Preferences

about-lepton = Personalize { -brand-short-name } com Lepton
lepton-preference-button = 
    .label = Configurações da Lepton...
    .accesskey = O
lepton-header = Configurações do Lepton
lepton-preference = Configurações do Lepton
photon-mode = 
    .label = Usar design de Photon
lepton-mode = 
    .label = Usar design Lepton
protonfix-mode = 
    .label = Usar projeto Proton ajustado
autohide-preference = Ocultar automaticamente elementos do navegador
floorp-lepton-enable-tab-autohide = 
    .label = Ocultar automaticamente as abas
floorp-lepton-enable-navbar-autohide = 
    .label = Ocultar barra de ferramentas automaticamente
floorp-lepton-enable-sidebar-autohide = 
    .label = Ocultar automaticamente a barra lateral
floorp-lepton-enable-urlbar-autohide = 
    .label = Ocultar automaticamente a Barra de Endereços
floorp-lepton-enable-back-button-autohide = 
    .label = Ocultar o botão voltar automaticamente
floorp-lepton-enable-forward-button-autohide = 
    .label = Ocultar automaticamente o botão para frente
floorp-lepton-enable-page-action-button-autohide = 
    .label = Ocultar os botões automaticamente na Barra de Endereços
floorp-lepton-enable-toolbar-overlap = 
    .label = Mostrar barra de ferramentas sobre o conteúdo do site
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Ocultar automaticamente a barra de ferramentas ao exibir conteúdo "ltr"
hide-preference = Gerenciar elementos de navegador
floorp-lepton-enable-tab_icon-hide = 
    .label = Ocultar ícones de abas
floorp-lepton-enable-tabbar-hide = 
    .label = Ocultar Barra de Abas
floorp-lepton-enable-navbar-hide = 
    .label = Ocultar barra
floorp-lepton-enable-sidebar_header-hide = 
    .label = Ocultar cabeçalhos do painel lateral
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Ocultar ícones da barra de endereço
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Ocultar ícones da barra de favoritos
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Ocultar rótulos da barra de favoritos
floorp-lepton-enable-disabled_menu-hide = 
    .label = Ocultar itens do menu de contexto desabilitados
floorp-lepton-disable-userChrome-icon = 
    .label = Desativar o menu de contexto do Lepton e os ícones de menu do painel
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Habilitar os ícones do menu de contexto do Lepton
positon-preferences = Ajustes de posição
floorp-lepton-enable-centered-tab = 
    .label = Centralizar etiquetas em abas
floorp-lepton-enable-centered-urlbar = 
    .label = Texto do centro na Barra de Endereços
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Centralizar barra de favoritos
urlbar-preferences = Barra de endereços
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Mover ícones da barra de endereço para o lado esquerdo
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Ao digitar, mostrar um botão "Ir"
floorp-lepton-enable-always-show-page_action = 
    .label = Sempre mostrar ações da página na barra de endereços
tabbar-preferences = Barra de Abas
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Barra de Abas na Barra de Título
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Combinar barra de guias e barra de ferramentas
lepton-sidebar-preferences = Sidebar
floorp-lepton-enable-overlap-sidebar = 
    .label = Mostrar barra lateral sobre o conteúdo do site
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Página Inicial (Padrão)
floorp-home-prefs-content-header = Conteúdo Inicial { -brand-short-name }
floorp-home-prefs-content-description = Escolha o conteúdo que deseja ver na Página Inicial { -brand-short-name }.

## Notes

floorp-notes = Notas { -brand-short-name }
restore-from-backup = Restaurar Notas do backup
enable-notes-sync = 
    .label = Habilitar sincronização de notas do { -brand-short-name }
about-notes-backup-tips = O Notas { -brand-short-name } usa o Firefox Sync para sincronizar suas notas com outros dispositivos. Se você perder suas notas, poderá restaurá-las a partir de um backup. O backup é criado ao iniciar o { -brand-short-name }.
notes-sync-description = Isso pode resolver o problema de perda de conteúdo devido a sobrescrever notas durante a sincronização.
backuped-time = Backup efetuado em
notes-backup-option = Configurações de backup
backup-option-button = Configurações de backup...
restore-from-backup-prompt-title = Serviço de Restauração do Notas { -brand-short-name }
restore-from-this-backup = Restaurar as Anotações de volta ao estado em que estão neste backup?
restore-button = RESTAURAR

## user.js

header-userjs = user.js
userjs-customize = Personalizar { -brand-short-name } com user.js
about-userjs-customize = user.js é um arquivo de configuração que lhe permite personalizar o { -brand-short-name }. Os arquivos user.js são baixados da Internet e sobrescrevem seu usuário atual. Arquivo s. Por favor, faça o backup do seu arquivo user.js atual antes de continuar. As configurações user.js serão aplicadas automaticamente depois de reiniciar o { -brand-short-name }.
userjs-label = lista user.js
userjs-prompt = Aplicar este user.js?
apply-userjs-attention = A aplicação de um novo user.js irá substituir o seu arquivo user.js atual.
apply-userjs-attention2 = Por favor, faça um backup do seu arquivo user.js atual antes de continuar.
userjs-button = configurações do user.js...
userjs-select-option = Gerencie os user.js atualmente usados no { -brand-short-name } para melhorar o desempenho e a privacidade.
apply-userjs-button = Aplicar

## userjs Options

default-userjs-label = Padrão { -brand-short-name }
about-default-userjs = Telemetria desativada. { -brand-short-name } bem equilibrado com várias personalizações ativadas.
Securefox-label = Fofox Seguro Assombrado
about-Securefox = HTTPS-by-Default. Proteção total de Cookie com isolamento do site. Estado melhorado e partição de rede. Várias outras melhorias.
default-label = Padrão Yokoffing
about-default = Tudo o que é essencial. Nenhuma das quebras. Este é seu user.js.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Aumenta imensamente a velocidade de navegação do Firefox. Faça o Chrome suar para conseguir dinheiro!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Liberar a página de novas abas. Remover o Pocket. Restaurar o modo compacto como opção. Parar notificações de página web, pop-ups e outros incômodos.
Smoothfox-label = Fumaça Atordoante
about-Smoothfox = Obtenha uma rolagem suave no seu navegador favorito — ou escolha algo mais seu estilo.
select-workspace = Selecionar Workspace
workspace-select-icon = Selecionar Ícone do Workspace
    .label = Ícone do Workspace
workspace-select-container = Selecionar Aba Contêiner
    .label = Selecionar aba contêiner
workspace-customize = 
    .title = Personalizar Área de Trabalho
floorp-no-workspace-container = 
    .label = Sem Contêiner
workspace-icon-article = 
    .label = Artigo
workspace-icon-book = 
    .label = Livro
workspace-icon-briefcase = 
    .label = Trabalho
workspace-icon-cart = 
    .label = Compras
workspace-icon-chat = 
    .label = Conversa
workspace-icon-chill = 
    .label = Privado
workspace-icon-circle = 
    .label = Círculo
workspace-icon-compass = 
    .label = Bússola
workspace-icon-code = 
    .label = Código
workspace-icon-dollar = 
    .label = Banco
workspace-icon-fence = 
    .label = Cerca
workspace-icon-fingerprint = 
    .label = pessoal
workspace-icon-food = 
    .label = Alimentação
workspace-icon-fruit = 
    .label = Frutas
workspace-icon-game = 
    .label = Jogo
workspace-icon-gear = 
    .label = Engrenagem
workspace-icon-gift = 
    .label = Presente
workspace-icon-key = 
    .label = Chave
workspace-icon-lightning = 
    .label = Raio
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notas
workspace-icon-paint = 
    .label = Pintar
workspace-icon-photo = 
    .label = Foto
workspace-icon-pin = 
    .label = Fixar
workspace-icon-pet = 
    .label = Animal
workspace-icon-question = 
    .label = Questão
workspace-icon-smartphone = 
    .label = Celular
workspace-icon-star = 
    .label = Estrela
workspace-icon-tree = 
    .label = Árvore
workspace-icon-vacation = 
    .label = Férias
workspace-icon-love = 
    .label = Amor
workspace-icon-moon = 
    .label = Lua
workspace-icon-music = 
    .label = Musica
workspace-icon-user = 
    .label = Usuário
# Custom Keyboard Shortcuts
floorp-CSK-title = Atalhos de teclado personalizados
floorp-CSK-description = Personalize os atalhos de teclado do { -brand-short-name }. O { -brand-short-name } oferece mais de 80 atalhos de teclado personalizáveis! Atalhos de teclado duplicados não funcionarão. Reinicie o { -brand-short-name } para aplicar essas configurações.
disable-fx-actions = 
    .label = Desativar atalhos de teclado do Mozilla Firefox
customize-Action = 
    .label = Adicionar atalho
remove-Action = 
    .label = Remover atalho
CSK-reset-title = Redefinir atalhos de teclado personalizados
CSK-reset-description = Redefinir atalhos de teclado personalizados para os padrões de { -brand-short-name }.
CSK-reset-label = Redefinir atalhos de teclado personalizados
CSK-reset-button = Restaurar Padrões
CSK-manage-title = Gerenciar atalhos de teclado
CSK-remove-shortcutkey = Remover atalho de teclado personalizado?
CSK-remove-shortcutkey-description = Tem certeza de que deseja remover este atalho de teclado?
CSK-restore-default = Restaurar padrões?
CSK-restore-default-description = Restaurar os atalhos de teclado padrão do { -brand-short-name }? Seus atalhos atuais serão perdidos.
CSK-reboot-browser-label = Reinicie o { -brand-short-name } para aplicar estas configurações
CSK-reboot-browser-button = Reiniciar o { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Atalho para teclado atual: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Atalho de teclado atual: { $key }.
CSK-keyborad-shortcut-is-changed = (Não aplicado)
floorp-custom-actions-tab-action = Ações da Aba
floorp-custom-actions-page-action = Ações de Página
floorp-custom-actions-visible-action = Ações visíveis
floorp-custom-actions-search-action = Procurar ações
floorp-custom-actions-tools-action = Ações de Ferramentas
floorp-custom-actions-bookmark-action = Ações para favoritos
floorp-custom-actions-open-page-action = Abrir Ações da Página
floorp-custom-actions-history-action = Ações do Histórico
floorp-custom-actions-pip-action = Ações Picture-in-Picture
floorp-custom-actions-downloads-action = Ações de Downloads
floorp-custom-actions-sidebar-action = Ações do painel lateral
floorp-custom-actions-bms-action = Ações da barra lateral do navegador
floorp-custom-actions-split-view-action = Ações de visualização dividida
floorp-custom-actions-workspaces-action = Ações de área de trabalho
floorp-custom-actions-custom-action = Ações personalizadas (Experimental)

## Mouse Gestures

mouse-gesture = Gestos do Mouse
mouse-gesture-description = Gesturefy deve ser instalado para usar gestos do mouse com { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy é uma extensão que adiciona gestos do mouse ao seu navegador. Se o { -brand-short-name } detectar a instalação deste complemento, ele adicionará comandos de gestos ao Gesturefy que só estão disponíveis no { -brand-short-name }. Essa extensão também cria novas abas!
# Translate
TWS = Translate Web Page
about-TWS = Traduza sua página em tempo real usando Google ou Yandex. Você também pode traduzir o texto selecionado ou a página inteira.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Centro de Privacidade
block-more-tracker = Bloquear mais anúncios e rastreadores
block-tracker = Esta seção contém um conjunto de extensões projetadas para bloquear anúncios e rastreadores
view-at-AMO = Veja este addon em addons.mozilla.org
uBlock-Origin = Origem do uBlock
about-uboori = O uBlock Origin bloqueia anúncios, rastreadores extensivos e sites perigosos adicionais.
Facebook-Container = Container do Facebook
about-Facebook-Container = Evite que o Facebook o rastreie através da web. A extensão do Container do Facebook ajuda você a assumir controle e isolar suas atividades da web do Facebook.

## Fingerprinting

fingerprint-header = Resistir a Impressões Digitais e vazamentos de endereços IP
block-fingerprint = A impressão digital é um mecanismo de rastreamento que depende das características únicas do seu navegador e do seu sistema operacional. Esta seção contém configurações para melhorar ainda mais esta proteção além do bloqueio padrão.
enable-firefox-fingerprint-protections = Ativar uma forte proteção contra impressão digital
about-firefox-fingerprint-protection = Habilitar a proteção pelo Firefox inclui o modo de luz forçada, desabilitando algumas APIs, etc. Alguns sites podem estar quebrados.
fingerprint-Protection = 
    .label = Proteção anti-impressão digital
html5-canvas-prompt-settings = 
    .label = Automaticamente dispensar solicitações de confirmação de acesso para dados de imagens HTML5
canvas-prompt = Impede que sites usem o aviso de leitura em tela, a menos que seja permitido manualmente.
disable-webgl = 
    .label = Desabilitar WebGL
about-webgl = WebGL é uma API Javascript usada para renderizar gráficos, que pode ser usada para identificar GPU.
Canvas-Blocker = Bloqueador de Tela
about-CB = Este complemento oculta dados usados por técnicas de impressão digital.
WebRTC-connection = WebRTC é um padrão que fornece chamadas em tempo real. Se você desativar essa configuração, você não poderá usar o Discord, etc.
WebRTC = 
    .label = Ativar Conexão WebRTC
################################################################### browser ###############################################################

rest-mode = Fazendo uma pausa...
rest-mode-description = { -brand-short-name } está suspenso no momento. Pressione ENTER ou OK para continuar.
Sidebar2 = 
    .label = Barra lateral Gerenciador de Navegadores
    .tooltiptext = Alterar visibilidade da barra lateral
sidebar2-mute-and-unmute = 
    .label = Silenciar/Reativar este Painel
sidebar2-unload-panel = 
    .label = Descarregar este painel
sidebar2-change-ua-panel = 
    .label = Alternar agente de usuário móvel
sidebar2-delete-panel = 
    .label = Excluir este painel
sidebar2-change-zoom-level = 
    .label = Mudar nível de ampliamento
sidebar2-zoom-in = 
    .label = Ampliar
sidebar2-zoom-out = 
    .label = Reduzir
sidebar2-reset-zoom = 
    .label = Redefinir Ampliamento
sidebar2-close-button = 
    .tooltiptext = Fechar barra lateral
sidebar-back-button = 
    .tooltiptext = Anterior
sidebar-forward-button = 
    .tooltiptext = Encaminhar
sidebar-reload-button = 
    .tooltiptext = Reload
sidebar-go-index-button = 
    .tooltiptext = Ir para casa
sidebar-muteAndUnmute-button = 
    .tooltiptext = Mute/Unmute sidebar
sidebar2-browser-manager-sidebar = Gerenciador de Navegadores
show-browser-manager-sidebar = 
    .tooltiptext = Show { sidebar2-browser-manager-sidebar } Sidebar
sidebar2-bookmark-sidebar = Favoritos
show-bookmark-sidebar = 
    .tooltiptext = Show { sidebar2-bookmark-sidebar } Sidebar
sidebar2-history-sidebar = Histórico
show-history-sidebar = 
    .tooltiptext = Show { sidebar2-history-sidebar } Sidebar
sidebar2-download-sidebar = Downloads
show-download-sidebar = 
    .tooltiptext = Show { sidebar2-download-sidebar } Sidebar
sidebar2-notes-sidebar = Observações
show-notes-sidebar = 
    .tooltiptext = Show { sidebar2-notes-sidebar } Sidebar
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Complementos e temas
sidebar2-hide-sidebar-button = 
    .tooltiptext = Ocultar a barra lateral do gerenciador de navegador
sidebar-passwords-button = 
    .tooltiptext = Senhas
sidebar-preferences-button = 
    .tooltiptext = Confirgurações
sidebar-keepWidth-button = 
    .tooltiptext = Continue usando a largura atual neste Painel
sidebar2-keep-width-for-global = 
    .label = Aplicar esta largura a todos os painéis sem largura personalizada
bsb-context-add = 
    .label = Adicionar página ao Painel Web...
bsb-context-link-add = 
    .label = Adicionar link ao Painel de Web...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Abrir diretório de perfil
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Reconstruir arquivos CSS do navegador
    .accesskey = R
make-browsercss-file = 
    .label = Criar arquivo CSS do navegador
    .accesskey = MM
open-css-folder = 
    .label = Abrir pasta CSS
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Editar arquivo userChrome.css
edit-userContentCss-editor = 
    .label = Editar arquivo userContent.css
not-found-editor-path = Não foi possível encontrar um editor de arquivo CSS
set-pref-description = Insira a localização do arquivo do editor de arquivo CSS que você deseja usar:
rebuild-complete = A reconstrução foi concluída.
please-enter-filename = Por favor, insira um nome de arquivo.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Reabrir aba fechada
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Habilitar como sub-tema
dual-theme-disable-addon-button = Desativar sub-tema
dual-theme-enabled-heading = Habilitado como sub-tema
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Barra de status
    .accesskey = S.O.
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Abrir Painel de Abas Estilo de Árvore
gf-floorp-open-tree-style-tab-description = Abrir Painel de Abas Estilo de Árvore na Barra Lateral
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Abrir o Painel de Favoritos
gf-floorp-open-bookmarks-sidebar-description = Abrir o Painel de Favoritos na Barra Lateral
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Abrir o Painel de Histórico
gf-floorp-open-history-sidebar-description = Abrir painel de histórico na barra lateral
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Abrir painel de abas sincronizadas
gf-floorp-open-synctabs-sidebar-description = Abrir painel de abas sincronizadas na barra lateral
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Fechar Barra Lateral
gf-floorp-close-sidebar-description = Fechar barra lateral
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Abrir BMS
gf-floorp-open-browser-manager-sidebar-description = Abrir a barra lateral Gerenciador de Navegadores caso o Painel de Controle do Navegador esteja carregado
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Fechar BMS
gf-floorp-close-browser-manager-sidebar-description = Fechar barra lateral Gerenciador de Navegadores
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Alternar BMS
gf-floorp-show-browser-manager-sidebar-description = Alternar barra lateral Gerenciador de Navegadores
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Esconder Barra Lateral
gf-floorp-hide-statusbar-description = Ocultar barra de status
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Alternar Barra Lateral
gf-floorp-show-statusbar-description = Exibir ou ocultar barra de status
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Open selected add-on Sidebar
gf-floorp-open-extension-sidebar-description = Open selected add-on on the Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id = Complemento da barra lateral
gf-floorp-open-extension-sidebar-settings-addons-id-description = A extensão do complemento aberto na barra lateral
gf-floorp-open-extension-sidebar-settings-list-default = Selecione o complemento
gf-floorp-open-extension-sidebar-settings-list-unknwon = Extensão desconhecida
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Atualizações encontradas!
update-portable-notification-found-message = Baixando atualizações...
update-portable-notification-ready-title = Pronto para atualizar!
update-portable-notification-ready-message = { -brand-short-name } will be updated on the next launch.
update-portable-notification-success-title = Atualização bem-sucedida!
update-portable-notification-success-message = Update succeeded! Hope you enjoy the new version of { -brand-short-name }!
update-portable-notification-failed-title = Falha na atualização.
update-portable-notification-failed-redirector-message = Falha na atualização. Reiniciar seu navegador pode resolver este problema.
update-portable-notification-failed-prepare-message = Falha ao preparar a atualização.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = Atualização Portátil { -brand-short-name }
floorp-update-application-auto-enabled-option = 
    .label = Verificar automaticamente atualizações para o portátil { -brand-short-name } . (Recomendado)
##################################################################### Open link in external ###############################################################
openInExternal-title = Abrir no navegador externo
open-link-in-external-enabled-option = 
    .label = Ativar o recurso "Abrir em navegador externo"
open-link-in-external-select-browser-option = Escolha qual navegador será aberto
open-link-in-external-select-browser-option-default = 
    .label = Navegador padrão
open-link-in-external-tab-context-menu = Abrir no navegador externo
open-link-in-external-tab-dialog-title-error = Ocorreu um erro:
open-link-in-external-tab-dialog-message-default-browser-not-found = O navegador padrão não foi encontrado ou não está configurado.
open-link-in-external-tab-dialog-message-selected-browser-not-found = O navegador selecionado não existe.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Novidades
memo-title-input-placeholder = Escreva um título aqui
memo-input-placeholder = Escreva ou cole um memorando aqui
delete-memo = excluir
save-memo = Guardar
memo-welcome-title = Bem-vindo!
memo-first-tip = Welcome to { -brand-short-name } Notes! Here are some instructions on how to use it!
memo-second-tip = { -brand-short-name } Notes is a notepad that lets you store multiple notes that sync across devices. To enable synchronization, you need to sign in to { -brand-short-name } with your Firefox account.
memo-third-tip = { -brand-short-name } Notes will be saved in your { -brand-short-name } settings and synchronized across devices using Firefox Sync. Firefox Sync encrypts the contents of the sync with your Firefox account password, so no one but you know its contents.
memo-import-data-tip = Firefox Sync não é um serviço de backup. Nós recomendamos que você crie backups.
memo-new-title = Nova anotação
chage-view-mode = Alternar Modo de Visualização/Edição
readonly-mode = Offline (Somente Leitura)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Suporte ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Limpar Downloads
    .accesskey = D
    .tooltiptext = Limpar Downloads
floorp-show-all-downloads = 
    .label = Mostrar todos os downloads
    .accesskey = S.O.
    .tooltiptext = Mostrar todos os downloads
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Create new Workspace...
    .tooltiptext = Criar área de trabalho
workspaces-manage-workspaces-button = 
    .label = Manage Workspaces...
    .tooltiptext = Gerenciar suas áreas de trabalho
reorder-this-workspace-to-up = 
    .label = Mover área de trabalho acima
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Mover área de trabalho abaixo
    .accesskey = A
rename-this-workspace = 
    .label = Renomear área de trabalho
    .accesskey = R
delete-this-workspace = 
    .label = Excluir área de trabalho
    .accesskey = D
manage-this-workspaces = 
    .label = Gerenciar áreas de trabalho...
    .accesskey = M
workspace-new-default-name = Nova Área de trabalho
workspace-default-name = Padrão
move-tab-another-workspace = 
    .label = Mover para outro Espaço
rename-workspace-prompt-title = Renomear Área de trabalho
rename-workspace-prompt-text = Enter Workspace Name. Most characters and symbols can be used.
workspaces-toolbar-button = Áreas de trabalho
    .label = Áreas de trabalho
    .tooltiptext = Selecionar área de trabalho...

## Preferences

enable-workspaces = 
    .label = Ativar área de trabalho
    .tooltiptext = Ativar área de trabalho
workspace-notice = Workspaces will not work with this settings enabled unless the workspaces's button is placed on the toolbar. Use this setting if you want to disable Workspaces completely.
enable-workspaces-with-experimental = 
    .label = Ativar áreas de trabalho (experimental)
    .tooltiptext = Ativar áreas de trabalho (experimental)
workspace-warning = Workspaces cannot be used with Tab Group add-ons. If you want to use Tab Group add-ons, please disable Workspaces and restart { -brand-short-name }.
category-workspaces = 
    .label = Áreas de trabalho
    .tooltiptext = Áreas de trabalho
pane-workspaces-title = Áreas de trabalho
floorp-workspaces-title = { -brand-short-name } Workspace
floorp-workspace-settings-button = Configurações do workspace...
floorp-preferences-label = Configurações
floorp-extensions-label = Extensões
floorp-private-label = Privado
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = Gerenciar Área de Trabalho na Barra lateral Gerenciador de Navegadores
show-workspace-name-option = 
    .label = Mostrar nome da Área de Trabalho no botão Tab da Barra de Trabalho
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Modo de Compartilhamento
    .accesskey = S.O.
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Entre em sua conta do Firefox
welcome-to-floorp = Bem-vindo a { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Ready to dive in?
welcome-skip-to-start-browsing = Pular para iniciar a navegação
welcome-select-preferences-template = Choose a template
welcome-minimum-template = Básico
welcome-enable-basic-features = Enable basic features and settings for a simple experience.
welcome-medium-template = Padrão
welcome-enable-some-features = Enable additional features and settings for a better experience.
welcome-maximum-template = Avançado
welcome-enable-most-of-features = Enable advanced features and settings. Recommended for experienced users.
welcome-go-next-setup = Próximo
welcome-select-browser-design = Selecione um Design de Navegador
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Design original Lepton
welcome-design-photon-name = Design Lepton Photon
welcome-design-ProtonFix-name = ProtonFix Design Lepton
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Projeto Proton do Firefox
welcome-import-data = Importar Dados do Seu Navegador
welcome-import-data-description = Configuração rápida! Importe seus favoritos, senhas e muito mais do seu navegador antigo. Os usuários do Firefox podem importar dados de Sincronização com o Firefox.
welcome-import-data-button = Importar dados...
welcome-import-data-skip = Pular importação
welcome-select-button = Selecionar
welcome-finish-setup = Configuração concluída!
welcome-finish-setup-description = Está tudo pronto! Outros recursos, como guias verticais e espaços de trabalho, podem ser encontrados nas configurações do { -brand-short-name }. Aproveite o { -brand-short-name }!
welcomet-finish-setup = Comece a navegar na web
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Atalhos de teclado
    .tooltiptext = Atalhos de teclado
category-CSK-title = Atalhos de teclado
shortcutkey-customize = 
    .title = Atalhos de teclado
select-shortcutkeyAction = Selecione uma ação para acionar
shortcutkey-customize-key-list-placeholder = Seu atalho de teclado aparecerá aqui
shortcut-key-label = Atalho de teclado
start-input-button-listen = Começar a ouvir
end-input-button-listen = Para de ouvir
shortcut-key-description = Aperte em "Começar a ouvir" e digite seu novo atalho de teclado para essa ação. Várias teclas podem ser usadas; porém, atalhos de teclado não vão funcionar se já atribuídos a outra ação.
floorp-custom-actions-open-new-tab = Abrir uma aba
    .label = Abrir uma aba
floorp-custom-actions-close-tab = Fechar a aba atual
    .label = Fechar a aba atual
floorp-custom-actions-open-new-window = Abrir uma nova janela
    .label = Abrir uma nova janela
floorp-custom-actions-open-new-private-window = Abrir uma nova janela privativa
    .label = Abrir uma nova janela privativa
floorp-custom-actions-close-window = Fechar a janela atual
    .label = Fechar a janela atual
floorp-custom-actions-restore-last-session = Restaurar a última sessão
    .label = Restaurar a última sessão
floorp-custom-actions-restore-last-window = Restaurar a última janela
    .label = Restaurar a última janela
floorp-custom-actions-show-next-tab = Mostrar a próxima aba
    .label = Mostrar a próxima aba
floorp-custom-actions-show-previous-tab = Mostrar aba anterior
    .label = Mostrar aba anterior
floorp-custom-actions-show-all-tabs-panel = Mostrar painel de todas as abas
    .label = Mostrar a lista de abas
floorp-custom-actions-send-with-mail = Enviar com e-mail
    .label = Enviar via e-mail
floorp-custom-actions-save-page = Salvar página
    .label = Salvar página
floorp-custom-actions-print-page = Print page
    .label = Print page
floorp-custom-actions-mute-current-tab = Ativar/desativar som da guia atual
    .label = Ativar/desativar som da guia atual
floorp-custom-actions-toggle-bookmark-toolbar = Alternar barra de favoritos
    .label = Alternar barra de favoritos
floorp-custom-actions-show-source-of-page = Mostrar fonte da página
    .label = Abrir código da página
floorp-custom-actions-show-page-info = Mostrar informações da página
    .label = Abrir Informações da Página
floorp-custom-actions-zoom-in = Aumentar zoom
    .label = Aumentar zoom
floorp-custom-actions-zoom-out = Diminuir zoom
    .label = Diminuir zoom
floorp-custom-actions-reset-zoom = Reset zoom
    .label = Reset zoom
floorp-custom-actions-back = Anterior
    .label = Anterior
floorp-custom-actions-forward = Encaminhar
    .label = Encaminhar
floorp-custom-actions-reload = Reload
    .label = Reload
floorp-custom-actions-stop = Interromper
    .label = Interromper
floorp-custom-actions-force-reload = Forçar recarregamento
    .label = Forçar recarregamento
floorp-custom-actions-search-in-this-page = Pesquisar nesta página
    .label = Localizar na página
floorp-custom-actions-show-next-search-result = Mostrar próxima palavra de busca no resultado desta página
    .label = Próximo resultado "Localizar na página"
floorp-custom-actions-show-previous-search-result = Mostrar palavra de busca anterior no resultado desta página
    .label = Resultado anterior "Localizar na página"
floorp-custom-actions-search-the-web = Pesquisar na web
    .label = Pesquisar na web
floorp-custom-actions-open-migration-wizard = Abrir assistente de migração
    .label = Abrir assistente de migração
floorp-custom-actions-quit-from-application = Sair do aplicativo
    .label = Sair de { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Personalizar barra de ferramentas
    .label = Abrir Personalizar { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Entrar modo offline
    .label = Entrar no modo offline
floorp-custom-actions-open-screen-capture = Abrir ferramenta de captura de tela
    .label = Capturar tela
floorp-custom-actions-show-pip = Mostrar imagem na imagem
    .label = Mostrar Picture-in-Picture
floorp-custom-actions-bookmark-this-page = Adicionar aos favoritos
    .label = Adicionar aos favoritos
floorp-custom-actions-open-bookmarks-sidebar = Abrir barra lateral de favoritos
    .label = Abrir barra lateral de favoritos
floorp-custom-actions-open-bookmark-add-tool = Adicionar aos favoritos ferramenta
    .label = Adicionar aos favoritos
floorp-custom-actions-open-bookmark-add-toolbar = Abrir janela pop-up "Adicionar um novo favorito"
    .label = Adicionar à Barra de Favoritos
floorp-custom-actions-open-bookmarks-manager = Abrir gerenciador de favoritos
    .label = Abrir Gerenciador de Favoritos
floorp-custom-actions-show-bookmark-toolbar = Alternar barra de favoritos
    .label = Alternar barra de favoritos
floorp-custom-actions-open-general-preferences = Abrir preferências gerais
    .label = Abrir preferências gerais
floorp-custom-actions-open-privacy-preferences = Abrir preferências de privacidade
    .label = Abrir Preferências De Privacidade
floorp-custom-actions-open-workspaces-preferences = Abrir opções de áreas de trabalho
    .label = Preferências do Open Workspace
floorp-custom-actions-open-containers-preferences = Abrir preferências de contêineres
    .label = Abrir Preferências de Contêineres
floorp-custom-actions-open-search-preferences = Abrir preferências de pesquisa
    .label = Abrir preferências de pesquisa
floorp-custom-actions-open-sync-preferences = Abrir preferências de sincronização
    .label = Abrir preferências Sync
floorp-custom-actions-open-task-manager = Abrir gerenciador de tarefas
    .label = Abrir { -brand-short-name }Gerenciador de Tarefas
floorp-custom-actions-open-home-page = Abrir página inicial do { -brand-short-name }
    .label = Abrir página do { -brand-short-name }
floorp-custom-actions-open-addons-manager = Abrir extensões e temas
    .label = Complementos e temas abertos
floorp-custom-actions-forget-history = Esquecer o histórico
    .label = Esquecer o histórico
floorp-custom-actions-quick-forget-history = Histórico de esquecimentos rápidos
    .label = Histórico de esquecimentos rápidos
floorp-custom-actions-clear-recent-history = Limpar histórico recente
    .label = Limpar histórico recente
floorp-custom-actions-search-history = Histórico de busca
    .label = Histórico de busca
floorp-custom-actions-manage-history = Gerenciar Histórico
    .label = Gerenciar Histórico
floorp-custom-actions-open-downloads = Abrir downloads
    .label = Abrir Downloads
floorp-custom-actions-show-bms = Alternar a barra lateral do gerenciador de navegador
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = Exibir barra lateral de favoritos
    .label = Exibir barra lateral de favoritos
floorp-custom-actions-show-history-sidebar = Show history sidebar
    .label = Show History Sidebar
floorp-custom-actions-show-synced-tabs-sidebar = Show synced tabs sidebar
    .label = Show Synced Tabs Sidebar
floorp-custom-actions-reverse-sidebar = Posição da barra lateral inversa
    .label = Posição da barra lateral inversa
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = Ativar/Desativar barra lateral
    .label = Ativar/Desativar barra lateral
floorp-custom-actions-toggle-sidebar = Alternar barra lateral
    .label = Alternar barra lateral
floorp-custom-actions-open-previous-workspace = Abrir o espaço de trabalho anterior
    .label = Abrir o espaço de trabalho anterior
floorp-custom-actions-open-next-workspace = Abrir o próximo espaço de trabalho
    .label = Open next Workspace
floorp-custom-actions-show-panel-1 = Alternar painel 1
    .label = Alternar painel 1
floorp-custom-actions-show-panel-2 = Alternar painel 2
    .label = Alternar painel 2
floorp-custom-actions-show-panel-3 = Alternar painel 3
    .label = Alternar painel 3
floorp-custom-actions-show-panel-4 = Alternar painel 4
    .label = Alternar painel 4
floorp-custom-actions-show-panel-5 = Alternar painel 5
    .label = Alternar painel 5
floorp-custom-actions-show-panel-6 = Alternar painel 6
    .label = Alternar painel 6
floorp-custom-actions-show-panel-7 = Alternar painel 7
    .label = Alternar painel 7
floorp-custom-actions-show-panel-8 = Alternar painel 8
    .label = Alternar painel 8
floorp-custom-actions-show-panel-9 = Alternar painel 9
    .label = Alternar painel 9
floorp-custom-actions-show-panel-10 = Alternar painel 10
    .label = Alternar painel 10
floorp-custom-actions-open-split-view-on-left = Open current tab on left in split view
    .label = Open current tab on left in split view
floorp-custom-actions-open-split-view-on-right = Open current tab on right in split view
    .label = Open current tab on right in split view
floorp-custom-actions-close-split-view = Close split view
    .label = Close split view
floorp-custom-actions-custom-action-1 = Ação personalizada 1
    .label = Ação personalizada 1
floorp-custom-actions-custom-action-2 = Ação personalizada 2
    .label = Ação personalizada 2
floorp-custom-actions-custom-action-3 = Ação personalizada 3
    .label = Ação personalizada 3
floorp-custom-actions-custom-action-4 = Ação personalizada 4
    .label = Ação personalizada 4
floorp-custom-actions-custom-action-5 = Ação personalizada 5
    .label = Ação personalizada 5
floorp-custom-actions-rest-mode = Enable rest mode
    .label = Enable rest mode
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
floorp-custom-actions-toggle-navigation-panel = Toggle Navigation Panel
    .label = Toggle Navigation Panel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Lançamento
    .tooltiptext = Inicie { -brand-short-name } com este perfil
floorp-profiles-in-use = Este perfil está em uso.
floorp-profiles-title = Profiles
floorp-profile-manager = Gerenciador de perfis
floorp-profiles-create = Criar Perfil
floorp-profile = Perfil
    .label = Gerenciador de perfis
    .tooltiptext = Abrir Gerenciador de Perfis
fxa-not-signed-in = Sem sessão iniciada
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privado
floorp-toggle-private-container = 
    .label = Reabrir em Privado/Nenhum Contêiner
    .accesskey = PT
open-in_private-container = 
    .label = Abrir em Nova Aba com Recipiente Privado
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = Open in split view
splitview-show-on-right = 
    .label = Show on right
splitview-show-on-left = 
    .label = Show on left
splitview-close-split-tab = 
    .label = Close split tab
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Escaneie o Código QR com seu Telefone
qrcode-generate-page-action = 
    .tooltiptext = Compartilhe esta página com seu telefone
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Botão de Extensões Unificadas
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Install app
    .tooltiptext = Install this site as an app
ssb-page-action-title = Install app
ssb-app-open-button = 
    .label = Open In App
ssb-app-install-button = 
    .label = Install
ssb-app-cancel-button = 
    .label = Cancel
floorp-open-manage-ssb-page = 
    .label = Manage installed Web Apps
appmenuitem-webapps = 
    .label = Web Apps
appmenu-open-installed-apps-subheader = Open installed web apps
appmenuitem-install-current-page = 
    .label = Install this site as an app
appmenuitem-open-current-page = 
    .label = Open this site on installed app
appmenuitem-contextmenu-open-app = 
    .label = Open this app
appmenuitem-contextmenu-uninstall-app = 
    .label = Uninstall this app

## Preferences

category-ssb = 
    .label = Web Apps
    .tooltiptext = Web Apps
category-ssb-title = Web Apps
floorp-ssb-title = Web Apps
floorp-ssb-description = Web Apps are websites that can be installed as apps. They can be launched from { -brand-short-name }'s menu panel or the Windows Start menu.
ssb-preferences = Web Apps Settings
floorp-enable-ssb = 
    .label = Enable Web Apps
floorp-enable-ssb-with-experimental = 
    .label = Enable Web Apps (Experimental)
floorp-enable-ssb-description = This feature is experimental on Mac and Linux. It is recommended to enable this feature on Windows.
floorp-disable-toolbars = 
    .label = Disable toolbars on Web Apps Window
floorp-disable-toolbars-description = This setting will hide all extensions and toolbars on Web Apps Window.
ssb-installed-list-title = Installed Web Apps
ssb-uninstall-title = Uninstall Web App
ssb-uninstall-message = Are you sure you want to uninstall this Web App from { -brand-short-name }?
ssb-uninstall-button = 
    .label = Uninstall
ssb-uninstall-cancel = Cancel
######################################################################### Download Notification ###############################################################
floorp-started-download = Download started
floorp-finished-download = Download finished
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } is up to date!
floorp-notificationContent-latest = { -brand-short-name } is up to date. You are using the latest version of { -brand-short-name }.
floorp-notificationTitle = New version of { -brand-short-name } is available!
floorp-notificationContent = Click to download the latest version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
