# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> 是一款日本開發的瀏覽器。 基於 Firefox 開發並由 <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label> 運行，旨在促進網絡發展。 想支持我們？ <label data-l10n-name="helpus-donateLink">點此捐款</label>
icon-creator = 圖示作者： <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> 和 <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = <label data-l10n-name="about-contributor">貢獻者和開發者名單</label>。
#################################################################### about:preferences ####################################################################

pane-design-title = 設計
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = 需要重啟以套用變更
tab-width = 分頁的最小寬度
tab-height = 分頁的最小高度
preferences-tabs-newtab-position = 新分頁位置
open-new-tab-use-default = 
    .label = 在預設位置開啟新分頁
open-new-tab-at-the-end = 
    .label = 在最右側開啟新分頁
open-new-tab-next-to-current = 
    .label = 在右側開啟新分頁
multirow-tabs-limit = 
    .label = 啟用分頁行數限制
multirow-tabs-newtab = 
    .label = 始終將 "開啟新分頁" 按鈕放在多行分頁內
multirow-tabs-value = 多行分頁列分頁最大行數
enable-tab-sleep = 
    .label = 啟用分頁休眠
tab-sleep-timeout-minutes-value = 多久後休眠閒置分頁 (單位：分鐘)
tab-sleep-settings-button = 設定...
tab-sleep-settings-dialog-title = 
    .title = 分頁休眠設定
tab-sleep-settings-dialog-excludehosts-label = 排除域名
tab-sleep-settings-dialog-excludehosts-label-2 = 每行輸入一個域名。
tab-sleep-tab-context-menu-excludetab = 保持分頁於喚醒狀態
enable-tab-scroll-change = 
    .label = 透過滾綸切換分頁
enable-tab-scroll-reverse = 
    .label = 反轉分頁滾動方向
enable-tab-scroll-wrap = 
    .label = 在邊緣處循環滾動分頁
enable-double-click-block = 
    .label = 雙擊關閉分頁
enable-show-pinned-tabs-title = 
    .label = 顯示固定分頁的標題
tabbar-preference = 分頁列
tab-normal-mode = 
    .label = 預設
hide-horizontality-tabs = 
    .label = 隱藏橫向分頁列
verticalTab-setting = 
    .label = 最佳化瀏覽器垂直分頁列
move-tabbar-position = 
    .label = 在工具列下方顯示分頁列
tabbar-on-bottom = 
    .label = 在視窗底部顯示分頁列
tabbar-favicon-color = 
    .label = 使用目前網站的圖示顏色為分頁列著色
tabbar-style-preference = 分頁列樣式
horizontal-tabbar = 
    .label = 水平分頁列
tabbar-style-description = 需要重新啟動 { -brand-short-name } 以完全套用此設定。
multirow-tabbar = 
    .label = 多層分頁排列
vertical-tabbar = 
    .label = 垂直分頁列 (實驗性質)
native-vertical-tab-show-right = 
    .label = 在窗口右側顯示垂直分頁列
native-vertical-tab-show-padding = 
    .label = 在分頁列上方啟用可拖拽空間
hover-vertical-tab = 
    .label = 摺疊垂直分頁列
floorp-show-vertical-tab-newtab-button = 
    .label = 在垂直分頁列內顯示"開啟新分頁"的選項
floorp-show-vertical-tab-scrollbar = 
    .label = 於垂直分頁列顯示捲動軸
TST = 樹狀分頁列
about-TST = Tree Style Tab是一款可以讓您使用樹狀結構展示分頁列的擴充套件。{ -brand-short-name } 內已經內建設定檔案。請安裝此擴充套件以啟用 { -brand-short-name } 的樹狀分頁列功能。
treestyletab-Settings = 
    .label = 摺疊樹狀分頁列
sidebar-reverse-position-toolbar = 在窗口另一邊顯示側邊欄
bookmarks-bar-settings = 書籤工具列 (一次只可使用一個選項)
bookmarks-focus-mode = 
    .label = 隱藏書籤工具列，只在滑鼠放置於瀏覽位址列時顯示
bookmarks-bottom-mode = 
    .label = 在 { -brand-short-name } 底部顯示書籤工具列
navbar-settings = 瀏覽位址列
show-nav-bar-bottom = 
    .label = 在 { -brand-short-name } 底部顯示瀏覽位址列 (實驗性質)
disable-extension-check-compatibility-option = 
    .label = 不檢查擴充套件兼容性 (已終止支援)
other-preference = 其他的偏好設定
search-positon-top = 
    .label = 在頁面頂端顯示搜索欄
allow-auto-restart = 
    .label = 當變更需要重啟的設定項時自動重啟
disable-fullscreen-notification = 
    .label = 全螢幕狀態時不顯示通知

## Browser Theme

system-color-settings = 部分主題同時擁有亮色和暗色模式，請選擇自己喜好的主題模式
preferences-theme-appearance-header = 主題模式
system-theme-dark = 
    .label = 暗色
system-theme-light = 
    .label = 亮色
system-theme-auto = 
    .label = 根據系統外觀改變

## User interface preferences

ui-preference = 瀏覽器外觀
preferences-browser-appearance-description = 選擇一款於 { -brand-short-name } 內建的第三方設計的外觀。部分設計外觀可能與您的設定不相容。
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (已終止支援)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (新版)

## Download Manager

download-notification-preferences = 下載通知
start-always-notify = 
    .label = 只在開始下載時通知
finish-always-notify = 
    .label = 只在下載完成後通知
always-notify = 
    .label = 在開始下載以及下載完成時通知
do-not-notify = 
    .label = 停用下載通知

## Sidebar

profiles-button-label = 管理個人設定檔
floorp-help-button-label = { -brand-short-name } 支援
appmenuitem-reboot = 
    .label = 重新啟動

## DMR UI

download-mgr-UI = 
    .label = 啟用 SimpleUI 下載管理工具
downloading-red-color = 
    .label = 在下載時使用紅色下載圖示
sidebar-preferences = 側邊欄
bsb-preferences = 瀏覽器管理工具側邊欄設定
view-sidebar2-right = 
    .label = 在窗口右邊顯示管理工具側邊欄
enable-sidebar2 = 
    .label = 啟用管理工具側邊欄
visible-bms = 
    .label = 顯示管理工具側邊欄
hide-bms-to-unload-panel = 
    .label = 隱藏側欄面板時卸下面板內容
enable-addons-in-sidebar2-with-experimental = 
    .label = 在管理工具側邊欄中啟用擴充套件功能 (實驗性質)
enable-addons-in-sidebar2 = 
    .label = 在管理工具側邊欄中啟用擴充套件功能
sidebar2-enable-addons-desc = 如果啟用此設定，抗廣告等功能的擴充套件將可在側邊欄中使用。但請注意，不是所有的擴充套件都能夠正常使用。
custom-URL-option = 設置Web面板網址
set-custom-URL-button = 
    .label = 設定自訂的網址...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = 管理工具側邊欄
bsb-context = 使用以下分頁容器
bsb-userAgent-label = 
    .label = 在此Web面板使用手機端User Agent
bsb-width = 寬度 (如果設為0，將會使用全局默認值)
bsb-page = 要打開的頁面
bsb-add = 將Web面板添加至管理工具側邊欄
bsb-setting = Web面板設定
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = 網址
sidebar2-pref-delete = 
    .label = 刪除
sidebar2-pref-setting = 
    .label = 設定
sidebar2-global-width = 全局Web面板寬度
use-icon-provider-option = 網站圖標提供者
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (可於中國境內直連)
use-icon-provider-option-hatena = 
    .label = Hatena (可於中國境內直連)
memory-and-performance = 記憶體及效能
min-memory = 
    .label = 最小化記憶體使用量 (低效能)
balance-memory = 
    .label = 均衡分配記憶體效能
max-memory = 
    .label = 最佳效能 (較高記憶體使用率)
delete-border-and-roundup-option = 
    .label = 圓化頁面邊緣

## DualTheme

dualtheme-enable = 
    .label = Enable Dual Theme (Deprecated)
floorp-enable-dualtheme-description = Dual Theme feature may cause problems with extensions. Please use with caution.
newtab-background = { -brand-short-name } 主頁背景
newtab-background-random-image = 
    .label = 來自Unsplash的隨機圖像
newtab-background-gradation = 
    .label = 漸層圖像
newtab-background-not-background = 
    .label = 停用背景圖像
newtab-background-selected-image = 
    .label = 自定義資料夾
newtab-background-selected-one-image = 
    .label = 自訂圖像...
newtab-background-folder = 從此資料夾使用圖像：
newtab-background-image = 使用圖像：
newtab-choose-image = 選擇圖像…
newtab-background-folder-reload = 
    .label = 重新加載圖像
newtab-background-folder-default = 
    .label = 重設為預設值
newtab-background-folder-open = 
    .label = 開啟資料夾
newtab-background-folder-choose = 選擇圖像資料夾...
newtab-background-image-choose = 選擇圖像…
newtab-background-extensions = 使用擁有以下副檔名的圖像 (以","分割)
disable-blur-on-newtab = 
    .label = 在 { -brand-short-name } 主頁上停用模糊效果
disable-releasenote-on-newtab = 
    .label = 在 { -brand-short-name } 首頁不顯示版本資訊及支援鏈接
disable-imagecredit-on-newtab = 
    .label = 在 { -brand-short-name } 首頁不顯示 (Unsplash) 圖像來源

## Lepton Preferences

about-lepton = 使用 Lepton 客製化 { -brand-short-name }
lepton-preference-button = 
    .label = Lepton 設定...
    .accesskey = L
lepton-header = Lepton 設定
lepton-preference = Lepton 設定
photon-mode = 
    .label = 採用 Photon 設計
lepton-mode = 
    .label = 採用 Lepton 設計
protonfix-mode = 
    .label = 採用改良版 Proton 設計
autohide-preference = 自動隱藏部分介面
floorp-lepton-enable-tab-autohide = 
    .label = 自動隱藏分頁列
floorp-lepton-enable-navbar-autohide = 
    .label = 自動隱藏工具列
floorp-lepton-enable-sidebar-autohide = 
    .label = 自動隱藏側邊欄
floorp-lepton-enable-urlbar-autohide = 
    .label = 自動隱藏位址欄
floorp-lepton-enable-back-button-autohide = 
    .label = 自動隱藏"返回"鈕
floorp-lepton-enable-forward-button-autohide = 
    .label = 自動隱藏"前進"鈕
floorp-lepton-enable-page-action-button-autohide = 
    .label = 自動隱藏位址欄上的按鈕
floorp-lepton-enable-toolbar-overlap = 
    .label = 在網站內容上顯示工具列
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = 自動隱藏工具列
hide-preference = 管理瀏覽器顯示物件
floorp-lepton-enable-tab_icon-hide = 
    .label = 隱藏分頁圖標
floorp-lepton-enable-tabbar-hide = 
    .label = 隱藏分頁列
floorp-lepton-enable-navbar-hide = 
    .label = 隱藏工具列
floorp-lepton-enable-sidebar_header-hide = 
    .label = 隱藏側邊欄標題
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = 隱藏位址欄圖標
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = 隱藏書籤列圖標
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = 隱藏書籤列文本
floorp-lepton-enable-disabled_menu-hide = 
    .label = 隱藏不可用的選單項目
floorp-lepton-disable-userChrome-icon = 
    .label = 停用 Lepton 的選單項目以及面板的圖標
floorp-lepton-disable-userChrome-menu-icon = 
    .label = 啟用 Lepton 的選單項目圖標
positon-preferences = 位置調整
floorp-lepton-enable-centered-tab = 
    .label = 居中顯示分頁標題
floorp-lepton-enable-centered-urlbar = 
    .label = 居中顯示位址欄文本
floorp-lepton-enable-centered-bookmarkbar = 
    .label = 居中顯示書籤列項目
urlbar-preferences = 位址欄
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = 將位址欄圖標移至左邊
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = 在鍵入時顯示"前進箭頭"按鈕
floorp-lepton-enable-always-show-page_action = 
    .label = 始終在位址欄顯示頁面操作
tabbar-preferences = 分頁列
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = 分頁列的位置作為單一頁面標題欄
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = 合併分頁列及工具列
lepton-sidebar-preferences = 側邊欄
floorp-lepton-enable-overlap-sidebar = 
    .label = 在網站內容上顯示側邊欄
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } 首頁 (默認)
floorp-home-prefs-content-header = { -brand-short-name } 首頁內容
floorp-home-prefs-content-description = 選擇要在您的 { -brand-short-name } 首頁畫面顯示哪些內容。

## Notes

floorp-notes = { -brand-short-name } 筆記
restore-from-backup = 從備份中復原筆記
enable-notes-sync = 
    .label = 啟用 { -brand-short-name } 筆記同步功能
about-notes-backup-tips = { -brand-short-name } 使用 Firefox Sync 來同步您的筆記至其他設備上。如果您失去了筆記內容，您可以從備份中復原。而備份會在每一次啟動 { -brand-short-name } 時自動進行。
notes-sync-description = 這可以解決同步筆記時內容被覆寫而丟失的問題。
backuped-time = 備份於
notes-backup-option = 備份設定
backup-option-button = 備份設定...
restore-from-backup-prompt-title = { -brand-short-name } 筆記復原服務
restore-from-this-backup = 要將筆記復原至備份時的狀態嗎？
restore-button = 復原

## user.js

header-userjs = user.js
userjs-customize = 使用 user.js 客製化 { -brand-short-name }
about-userjs-customize = user.js 是一種讓您可以客製化 { -brand-short-name } 的配置檔。user.js是從網路上下載的，並會覆寫您現使用的user.js配置檔。請在使用前備份好您現在的user.js。user.js配置檔會在 { -brand-short-name } 重啟後生效。
userjs-label = user.js 列表
userjs-prompt = 套用此 user.js？
apply-userjs-attention = 套用新的 user.js 會覆寫您現在的 user.js 配置檔。
apply-userjs-attention2 = 請在繼續之前先備份您現在使用的 user.js 配置檔。
userjs-button = user.js 設定...
userjs-select-option = 管理目前 { -brand-short-name } 使用的 user.js 以提升效能，增強隱私防護。
apply-userjs-button = 套用

## userjs Options

default-userjs-label = { -brand-short-name } 預設
about-default-userjs = 已禁用Telemetry。均衡豐富的可客製化版 { -brand-short-name } 。
Securefox-label = Yokoffing Securefox
about-Securefox = 默認連接 HTTPS。完全站點區隔的cookies防護。強化狀態與網路區隔。以及其他功能強化。
default-label = Yokoffing Default
about-default = 所有的必備功能。無任何故障。這個 user.js 由你作主。
Fastfox-label = Yokoffing Fastfox
about-Fastfox = 提升強化 Floorp 的瀏覽速度，與 Chrome 對比也毫不遜色！
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = 最佳化新分頁。移除 Pocket。復原 緊密(不支援) 密度選項。停止網站通知，彈窗以及其他煩瑣提示。
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = 在 Floorp 上實現類似 Edge 一般順滑的頁面滾動效果 —— 更舒適的瀏覽體驗。
select-workspace = 選擇工作空間
workspace-select-icon = 選擇工作空間圖示
    .label = 選擇工作空間圖示
workspace-select-container = 選擇分頁容器
    .label = 選擇分頁容器
workspace-customize = 
    .title = 自訂工作空間
floorp-no-workspace-container = 
    .label = 不使用容器
workspace-icon-article = 
    .label = 文章
workspace-icon-book = 
    .label = 書本
workspace-icon-briefcase = 
    .label = 辦公
workspace-icon-cart = 
    .label = 購物
workspace-icon-chat = 
    .label = 聊天
workspace-icon-chill = 
    .label = 私人
workspace-icon-circle = 
    .label = 圓圈
workspace-icon-compass = 
    .label = 指南
workspace-icon-code = 
    .label = 程式碼
workspace-icon-dollar = 
    .label = 銀行
workspace-icon-fence = 
    .label = 柵欄
workspace-icon-fingerprint = 
    .label = 個人
workspace-icon-food = 
    .label = 美食
workspace-icon-fruit = 
    .label = 水果
workspace-icon-game = 
    .label = 遊戲
workspace-icon-gear = 
    .label = 齒輪
workspace-icon-gift = 
    .label = 禮物
workspace-icon-key = 
    .label = 鎖匙
workspace-icon-lightning = 
    .label = 閃電
workspace-icon-network = 
    .label = 網路
workspace-icon-notes = 
    .label = 筆記
workspace-icon-paint = 
    .label = 繪畫
workspace-icon-photo = 
    .label = 相片
workspace-icon-pin = 
    .label = 釘選
workspace-icon-pet = 
    .label = 寵物
workspace-icon-question = 
    .label = 問題
workspace-icon-smartphone = 
    .label = 智慧型手機
workspace-icon-star = 
    .label = 星星
workspace-icon-tree = 
    .label = 樹木
workspace-icon-vacation = 
    .label = 假日
workspace-icon-love = 
    .label = 愛心
workspace-icon-moon = 
    .label = 月亮
workspace-icon-music = 
    .label = 音樂
workspace-icon-user = 
    .label = 用户
# Custom Keyboard Shortcuts
floorp-CSK-title = 自訂鍵盤快捷鍵
floorp-CSK-description = 客製化 { -brand-short-name } 的鍵盤快捷鍵。 { -brand-short-name } 提供超過80種可自訂的鍵盤快捷鍵位！重複的快捷鍵位將不會生效。請重啟 { -brand-short-name } 套用變更。
disable-fx-actions = 
    .label = 停用 Mozilla Firefox 原訂的鍵盤快捷鍵
customize-Action = 
    .label = 添加快捷鍵
remove-Action = 
    .label = 移除快捷鍵
CSK-reset-title = 重置自訂鍵盤快捷鍵
CSK-reset-description = 重置自訂鍵盤快捷鍵至 { -brand-short-name } 預設的狀態。
CSK-reset-label = 重置自訂鍵盤快捷鍵
CSK-reset-button = 重設為預設值
CSK-manage-title = 管理鍵盤快捷鍵
CSK-remove-shortcutkey = 移除自訂鍵盤快捷鍵？
CSK-remove-shortcutkey-description = 您確定要移除此鍵盤快捷鍵嗎？
CSK-restore-default = 重設為預設值？
CSK-restore-default-description = 要重設為 { -brand-short-name } 預設的鍵盤快捷鍵嗎？您現在的快捷鍵位將會丟失。
CSK-reboot-browser-label = 重啟 { -brand-short-name } 以套用設定
CSK-reboot-browser-button = 重啟 { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = 目前的鍵盤快捷鍵： { $key } & { $modifiers }。
CSK-keyborad-shortcut-info-with-keycode = 目前的鍵盤快捷鍵： { $key }。
CSK-keyborad-shortcut-is-changed = (未套用)
floorp-custom-actions-tab-action = 分頁操作
floorp-custom-actions-page-action = 頁面操作
floorp-custom-actions-visible-action = 可見操作
floorp-custom-actions-search-action = 搜尋操作
floorp-custom-actions-tools-action = 工具操作
floorp-custom-actions-bookmark-action = 書籤操作
floorp-custom-actions-open-page-action = 開啟頁面操作
floorp-custom-actions-history-action = 歷史操作
floorp-custom-actions-pip-action = 字母畫面操作
floorp-custom-actions-downloads-action = 下載操作
floorp-custom-actions-sidebar-action = 側邊欄操作
floorp-custom-actions-bms-action = 管理工具側邊欄操作
floorp-custom-actions-split-view-action = 分割視圖操作
floorp-custom-actions-workspaces-action = 工作空間操作
floorp-custom-actions-custom-action = 自訂操作 (實驗性質)

## Mouse Gestures

mouse-gesture = 滑鼠手勢
mouse-gesture-description = 欲使用 { -brand-short-name } 的滑鼠手勢功能請先安裝 Gesturefy。
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy 是一款添加滑鼠手勢功能的擴充套件。如果 { -brand-short-name } 檢測到此擴充套件已安裝即會在 Gesturefy 中添加 { -brand-short-name } 限定的手勢指令。此擴充套件也可在新分頁中使用！
# Translate
TWS = Translate Web Pages
about-TWS = 安裝此擴充套件後即可使用 Google 或 Yandex 的翻譯服務對頁面進行實時翻譯。您也可以選擇只翻譯部分字節或整個頁面。

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = 隱私中心
block-more-tracker = 屏蔽更多的廣告以及追蹤器
block-tracker = 此區域旨在推介一系列專為屏蔽廣告以及追蹤器設計的擴充套件
view-at-AMO = 在 addons.mozilla.org 查看此擴充套件
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin可屏蔽廣告，大量的追蹤器，以及危險的網站。
Facebook-Container = Facebook Container
about-Facebook-Container = 阻止臉書在網絡上追蹤你。Facebook Container擴充套件可幫助您掌握並從Facebook上的活動區隔開來。

## Fingerprinting

fingerprint-header = 制止數位指紋以及 IP 位址洩漏
block-fingerprint = 數位指紋是一種以採集您的瀏覽器及系統的獨特設定的跟蹤機制。此區域提供比預設防護更加強化隱私的防護選項。
enable-firefox-fingerprint-protections =
    .label = 開啟強力數位指紋防護
about-firefox-fingerprint-protection = 由 Firefox 提供的防護，將強制使用亮色模式，屏蔽部分 API 連結。部分網站頁面可能會出現錯誤。
fingerprint-Protection = 
    .label = 數位指紋防護
html5-canvas-prompt-settings = 
    .label = 自動拒絕 HTML5 圖像數據的讀取確認提示
canvas-prompt = 防止網頁在手動准許之前使用 Canvas 讀取提示。
disable-webgl = 
    .label = 禁止 WebGL
about-webgl = WebGL 是一款渲染圖形的 Javascript API，可用於識別顯示卡資訊。
Canvas-Blocker = CanvasBlocker
about-CB = 此擴充套件可以生成偽裝數據來擾亂網站對數位指紋的收集。
WebRTC-connection = WebRTC 是一款提供實時通訊的協議。如果禁用此設定，您將無法使用 Discord 等服務。
WebRTC = 
    .label = 啟用 WebRTC 連結
################################################################### browser ###############################################################

rest-mode = 正在休息中...
rest-mode-description = { -brand-short-name } 現正休息中。請按 ENTER 或是 確認鈕 繼續瀏覽。
Sidebar2 = 
    .label = 管理工具側邊欄
    .tooltiptext = 變更側欄的可視度
sidebar2-mute-and-unmute = 
    .label = 靜音/取消靜音此面板
sidebar2-unload-panel = 
    .label = 卸下此面板
sidebar2-change-ua-panel = 
    .label = 使用/取消使用移動端 User Agent
sidebar2-delete-panel = 
    .label = 刪除此面板
sidebar2-change-zoom-level = 
    .label = 縮放大小調整
sidebar2-zoom-in = 
    .label = 放大
sidebar2-zoom-out = 
    .label = 縮小
sidebar2-reset-zoom = 
    .label = 重設縮放大小
sidebar2-close-button = 
    .tooltiptext = 關閉側邊欄
sidebar-back-button = 
    .tooltiptext = 返回
sidebar-forward-button = 
    .tooltiptext = 前進
sidebar-reload-button = 
    .tooltiptext = 重新載入
sidebar-go-index-button = 
    .tooltiptext = 返回首頁
sidebar-muteAndUnmute-button = 
    .tooltiptext = 靜音/取消靜音側邊欄
sidebar2-browser-manager-sidebar = 管理工具
show-browser-manager-sidebar = 
    .tooltiptext = 顯示 { sidebar2-browser-manager-sidebar } 側邊欄
sidebar2-bookmark-sidebar = 書籤
show-bookmark-sidebar = 
    .tooltiptext = 顯示 { sidebar2-bookmark-sidebar } 側邊欄
sidebar2-history-sidebar = 歷史
show-history-sidebar = 
    .tooltiptext = 顯示 { sidebar2-history-sidebar } 側邊欄
sidebar2-download-sidebar = 下載
show-download-sidebar = 
    .tooltiptext = 顯示 { sidebar2-download-sidebar } 側邊欄
sidebar2-notes-sidebar = 筆記
show-notes-sidebar = 
    .tooltiptext = 顯示 { sidebar2-notes-sidebar } 側邊欄
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = 附加元件與佈景主題
sidebar2-hide-sidebar-button = 
    .tooltiptext = 關閉管理工具側邊欄
sidebar-passwords-button = 
    .tooltiptext = 密碼
sidebar-preferences-button = 
    .tooltiptext = 設定
sidebar-keepWidth-button = 
    .tooltiptext = 在此面板保持目前的寬度
sidebar2-keep-width-for-global = 
    .label = 將此寬度應用至沒有自訂過寬度的面板
bsb-context-add = 
    .label = 將此頁面添加為 Web 面板...
bsb-context-link-add = 
    .label = 將鏈接添加為 Web 面板...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = 開啟用戶設定檔目錄
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS樣式
    .accesskey = C
css-menubar = 
    .label = CSS樣式
    .accesskey = C
rebuild-css = 
    .label = 重建瀏覽器CSS樣式檔
    .accesskey = R
make-browsercss-file = 
    .label = 創建瀏覽器CSS樣式檔
    .accesskey = M
open-css-folder = 
    .label = 開啟CSS樣式資料夾
    .accesskey = O
edit-userChromeCss-editor = 
    .label = 編輯 userChrome.css 配置檔
edit-userContentCss-editor = 
    .label = 編輯 userContent.css 配置檔
not-found-editor-path = 找不到CSS樣式檔編輯器
set-pref-description = 鍵入您想使用的CSS樣式檔編輯器的程式所在資料夾：
rebuild-complete = 重建已經完成。
please-enter-filename = 請鍵入檔案名。
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = 恢復先前關閉的分頁
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = 作為子主題啟用
dual-theme-disable-addon-button = 停用子主題
dual-theme-enabled-heading = 已啟用的子主題：
##################################################################### toolbar ###############################################################

status-bar = 
    .label = 狀態列
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] 開啟樹狀分頁列
gf-floorp-open-tree-style-tab-description = 在側邊欄開啟樹狀側邊欄
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] 開啟書籤面板
gf-floorp-open-bookmarks-sidebar-description = 在側邊欄開啟書籤面板
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] 開啟歷史面板
gf-floorp-open-history-sidebar-description = 在側邊欄開啟歷史面板
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] 開啟已同步的分頁面板
gf-floorp-open-synctabs-sidebar-description = 在側邊欄開啟已同步的分頁面板
gf-floorp-close-sidebar-name = [{ -brand-short-name }] 關閉側邊欄
gf-floorp-close-sidebar-description = 關閉側邊欄
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] 開啟管理工具側邊欄
gf-floorp-open-browser-manager-sidebar-description = 如果管理工具側邊欄的Web面板已載入，就開啟管理工具側邊欄
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] 關閉管理工具側邊欄
gf-floorp-close-browser-manager-sidebar-description = 關閉管理工具側邊欄
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] 開啟管理工具側邊欄
gf-floorp-show-browser-manager-sidebar-description = 開啟管理工具側邊欄
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] 隱藏狀態列
gf-floorp-hide-statusbar-description = 隱藏狀態列
gf-floorp-show-statusbar-name = [{ -brand-short-name }] 顯示狀態列
gf-floorp-show-statusbar-description = 顯示或隱藏狀態列
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] 於側邊欄開啟選定的擴充套件
gf-floorp-open-extension-sidebar-description = 於側邊欄開啟選定的擴充套件
gf-floorp-open-extension-sidebar-settings-addons-id = 側邊欄擴充套件
gf-floorp-open-extension-sidebar-settings-addons-id-description = 在側邊欄開啟的擴充套件
gf-floorp-open-extension-sidebar-settings-list-default = 請選定擴充套件
gf-floorp-open-extension-sidebar-settings-list-unknwon = 未知的擴充套件
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = 有可用的更新！
update-portable-notification-found-message = 下載更新中...
update-portable-notification-ready-title = 更新準備就緒！
update-portable-notification-ready-message = { -brand-short-name } 會在下一次啟動時進行更新
update-portable-notification-success-title = 更新成功！
update-portable-notification-success-message = 希望新版本的 { -brand-short-name } 能繼續帶您暢享網路！
update-portable-notification-failed-title = 更新失敗。
update-portable-notification-failed-redirector-message = 重新啟動瀏覽器也許能夠解決此問題。
update-portable-notification-failed-prepare-message = 準備更新失敗。
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } 攜帶版更新
floorp-update-application-auto-enabled-option = 
    .label = 自動檢查 { -brand-short-name } 攜帶版更新。 (建議)
##################################################################### Open link in external ###############################################################
openInExternal-title = 於外部瀏覽器開啟
open-link-in-external-enabled-option = 
    .label = 啟用 "於外部瀏覽器開啟" 的功能
open-link-in-external-select-browser-option = 選擇要開啟的瀏覽器
open-link-in-external-select-browser-option-default = 
    .label = 預設瀏覽器
open-link-in-external-tab-context-menu = 於外部瀏覽器開啟
open-link-in-external-tab-dialog-title-error = 發生錯誤：
open-link-in-external-tab-dialog-message-default-browser-not-found = 沒有找到或未設定預設瀏覽器
open-link-in-external-tab-dialog-message-selected-browser-not-found = 選定的瀏覽器不存在。
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = 新增筆記
memo-title-input-placeholder = 在此處填寫標題
memo-input-placeholder = 在此處粘貼或寫下筆記
delete-memo = 刪除
save-memo = 儲存
memo-welcome-title = 歡迎！
memo-first-tip = 歡迎使用 { -brand-short-name } 筆記！此處將介紹您如何使用！
memo-second-tip = { -brand-short-name } 筆記是可以讓你在不同設備上同步共用的記事本。同步功能需要您先在 { -brand-short-name } 上登錄您的 Firefox 帳號才可啟用。
memo-third-tip = { -brand-short-name } 筆記保存在您的 { -brand-short-name } 設定中，並會使用 Firefox Sync 在其他設備上同步筆記內容。Firefox Sync 同步的內容會使用您的 Firefox 帳戶密碼保護，所以除了您之外沒有人可以查閱內容。
memo-import-data-tip = Firefox Sync 並不是備份服務。我們建議您自行建立備份。
memo-new-title = 新增筆記
chage-view-mode = 切換查看/編輯模式
readonly-mode = 離線 (唯讀)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Ablaze 支援
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = 清除下載記錄
    .accesskey = D
    .tooltiptext = 清除下載記錄
floorp-show-all-downloads = 
    .label = 顯示所有下載
    .accesskey = S
    .tooltiptext = 顯示所有下載
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = 建立新工作空間
    .tooltiptext = 建立新工作空間
workspaces-manage-workspaces-button = 
    .label = 管理工作空間...
    .tooltiptext = 管理工作空間
reorder-this-workspace-to-up = 
    .label = 向上移動此工作空間
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = 向下移動此工作空間
    .accesskey = A
rename-this-workspace = 
    .label = 重新命名工作空間
    .accesskey = R
delete-this-workspace = 
    .label = 刪除工作空間
    .accesskey = D
manage-this-workspaces = 
    .label = 管理工作空間...
    .accesskey = M
workspace-new-default-name = 新增工作空間
workspace-default-name = 預設
move-tab-another-workspace = 
    .label = 移至另一個工作空間
rename-workspace-prompt-title = 重新命名工作空間
rename-workspace-prompt-text = 輸入工作區名稱。 可使用大多數字元和符號。
workspaces-toolbar-button = 工作空間
    .label = 工作空間
    .tooltiptext = 選擇一個工作空間...

## Preferences

enable-workspaces = 
    .label = 啟用工作空間
    .tooltiptext = 啟用工作空間
workspace-notice =
    除非工作空間的按鈕已經放置在工具列上，工作空間不會在此設定啟用的情況下生效。
    欲完全停用工作空間，請啟用此設定。
enable-workspaces-with-experimental = 
    .label = 啟用工作空間 (實驗性質)
    .tooltiptext = 啟用工作空間 (實驗性質)
workspace-warning = 工作空間無法與分頁分組擴充套件一同使用。 如果您想要使用分頁分組擴充套件，請停用工作空間並重新啟動 { -brand-short-name}。
category-workspaces = 
    .label = 工作空間
    .tooltiptext = 工作空間
pane-workspaces-title = 工作空間
floorp-workspaces-title = { -brand-short-name } 工作空間
floorp-workspace-settings-button = 工作空間設定...
floorp-preferences-label = 設定
floorp-extensions-label = 附加元件
floorp-private-label = 私隱
change-to-close-workspace-popup-option = 
    .label = 選擇工作空間時，關閉工作空間的彈窗
manage-workspace-on-bms-option = 
    .label = 在管理工具側邊欄管理工作空間
show-workspace-name-option = 
    .label = 在分頁列上的工作空間按鈕上顯示工作空間的名稱
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = 共享模式
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = 登錄您的 Firefox 帳戶
welcome-to-floorp = 歡迎使用 { -brand-short-name }！
welcome-describe-floorp = { -brand-short-name } 是一款基於 Firefox 開發，提供豐富的客製化功能的瀏覽器，並支援多個平台。
welcome-start-setup = 準備好開始了嗎？
welcome-skip-to-start-browsing = 跳過初始設定
welcome-select-preferences-template = 選擇瀏覽器模板
welcome-minimum-template = 梅
welcome-enable-basic-features = 啟用基礎功能，提供簡便的使用體驗。
welcome-medium-template = 竹 (預設)
welcome-enable-some-features = 啟用更多追加功能，帶來更豐富的體驗。
welcome-maximum-template = 松
welcome-enable-most-of-features = 啟用更進階的功能。推薦更熟練的用戶使用。
welcome-go-next-setup = 下一步
welcome-select-browser-design = 選擇瀏覽器的介面設計
welcome-describe-browser-design = 您可以在 { -brand-short-name } 上選用第三方設計的精美介面。部分系統特有的介面設計也可在偏好設定中找到。
welcome-design-lepton-name = Lepton 原始設計
welcome-design-photon-name = Lepton Photon 設計
welcome-design-ProtonFix-name = Lepton 改良版Proton 設計
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial 設計
welcome-design-firefox-proton-name = Firefox Proton 設計
welcome-import-data = 匯入您的瀏覽器數據
welcome-import-data-description = 快速設定！匯入您的書籤，密碼，還有您之前的瀏覽器數據。 Firefox 用戶也可以從 Firefox Sync 匯入資料！
welcome-import-data-button = 匯入數據...
welcome-import-data-skip = 跳過匯入
welcome-select-button = 選擇
welcome-finish-setup = 設定完成！
welcome-finish-setup-description = 您已經設定完成！垂直分頁以及工作空間等功能可以在 "設定"中找到。開始暢享 { -brand-short-name } 吧！
welcomet-finish-setup = 開始瀏覽吧！
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = 鍵盤快捷鍵
    .tooltiptext = 鍵盤快捷鍵
category-CSK-title = 鍵盤快捷鍵
shortcutkey-customize = 
    .title = 鍵盤快捷鍵
select-shortcutkeyAction = 選擇一個要觸發的操作
shortcutkey-customize-key-list-placeholder = 您的鍵盤快捷鍵會在這裡顯示
shortcut-key-label = 鍵盤快速鍵
start-input-button-listen = 開始收錄
end-input-button-listen = 停止收錄
shortcut-key-description = 點擊 "開始收錄" 然後為此動作輸入您的鍵盤快捷鍵。可以設定多重組鍵，但是如果其他操作已經安排相同鍵位的話將無效。
floorp-custom-actions-open-new-tab = 開啟新分頁
    .label = 開啟新分頁
floorp-custom-actions-close-tab = 關閉目前的分頁
    .label = 關閉目前的分頁
floorp-custom-actions-open-new-window = 開啟新視窗
    .label = 開啟新視窗
floorp-custom-actions-open-new-private-window = 開啟新的私隱視窗
    .label = 開啟新的私隱視窗
floorp-custom-actions-close-window = 關閉目前的視窗
    .label = 關閉目前的視窗
floorp-custom-actions-restore-last-session = 恢復上次的瀏覽進程
    .label = 恢復上次的瀏覽進程
floorp-custom-actions-restore-last-window = 恢復上一個視窗
    .label = 恢復上一個視窗
floorp-custom-actions-show-next-tab = 顯示下一個分頁
    .label = 顯示下一個分頁
floorp-custom-actions-show-previous-tab = 顯示上一個分頁
    .label = 顯示上一個分頁
floorp-custom-actions-show-all-tabs-panel = 顯示所有分頁面板
    .label = 顯示分頁列表
floorp-custom-actions-send-with-mail = 通過電子郵件發送
    .label = 通過電子郵件發送
floorp-custom-actions-save-page = 儲存頁面
    .label = 儲存頁面
floorp-custom-actions-print-page = 列印頁面
    .label = 列印頁面
floorp-custom-actions-mute-current-tab = 切換靜音/取消靜音當前分頁
    .label = 切換靜音/取消靜音當前分頁
floorp-custom-actions-toggle-bookmark-toolbar = 切換顯示書籤列
    .label = 切換顯示書籤列
floorp-custom-actions-show-source-of-page = 檢視頁面原始碼
    .label = 打開頁面原始碼
floorp-custom-actions-show-page-info = 檢視頁面資訊
    .label = 打開頁面資訊
floorp-custom-actions-zoom-in = 放大
    .label = 放大
floorp-custom-actions-zoom-out = 縮小
    .label = 縮小
floorp-custom-actions-reset-zoom = 重設縮放
    .label = 重設縮放
floorp-custom-actions-back = 返回
    .label = 返回
floorp-custom-actions-forward = 前進
    .label = 前進
floorp-custom-actions-reload = 重新載入
    .label = 重新載入
floorp-custom-actions-stop = 停止
    .label = 停止
floorp-custom-actions-force-reload = 強制重新載入
    .label = 強制重新載入
floorp-custom-actions-search-in-this-page = 在此頁面搜尋
    .label = 在頁面中搜尋
floorp-custom-actions-show-next-search-result = 顯示頁面內搜尋文字下次出現的位置
    .label = 尋找文字下次出現的位置
floorp-custom-actions-show-previous-search-result = 顯示頁面內搜尋文字前次出現的位置
    .label = 尋找文字前次出現的位置
floorp-custom-actions-search-the-web = 在網路上搜尋
    .label = 在網路上搜尋
floorp-custom-actions-open-migration-wizard = 開啟遷移導引
    .label = 開啟遷移導引
floorp-custom-actions-quit-from-application = 結束程式
    .label = 結束運行 { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = 自訂工具列
    .label = 客製化 { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = 進入離線模式
    .label = 進入離線模式
floorp-custom-actions-open-screen-capture = 開啟畫面擷圖工具
    .label = 畫面擷圖
floorp-custom-actions-show-pip = 顯示子母畫面
    .label = 顯示子母畫面
floorp-custom-actions-bookmark-this-page = 將本頁加入書籤
    .label = 將本頁加入書籤
floorp-custom-actions-open-bookmarks-sidebar = 開啟書籤側邊欄
    .label = 開啟書籤側邊欄
floorp-custom-actions-open-bookmark-add-tool = 開啟新增書籤工具
    .label = 新增書籤
floorp-custom-actions-open-bookmark-add-toolbar = 開啟"新增書籤"彈窗
    .label = 新增至書籤列
floorp-custom-actions-open-bookmarks-manager = 開啟書籤管理
    .label = 開啟書籤管理
floorp-custom-actions-show-bookmark-toolbar = 切換顯示書籤列
    .label = 切換顯示書籤列
floorp-custom-actions-open-general-preferences = 開啟一般設定
    .label = 開啟一般設定
floorp-custom-actions-open-privacy-preferences = 開啟隱私安全設定
    .label = 開啟隱私安全設定
floorp-custom-actions-open-workspaces-preferences = 開啟工作空間設定
    .label = 開啟工作空間設定
floorp-custom-actions-open-containers-preferences = 開啟容器設定
    .label = 開啟容器設定
floorp-custom-actions-open-search-preferences = 開啟搜尋設定
    .label = 開啟搜尋設定
floorp-custom-actions-open-sync-preferences = 開啟同步設定
    .label = 開啟同步設定
floorp-custom-actions-open-task-manager = 開啟工作管理員
    .label = 開啟 { -brand-short-name } 的工作管理員
floorp-custom-actions-open-home-page = 開啟 { -brand-short-name } 首頁
    .label = 開啟 { -brand-short-name } 首頁
floorp-custom-actions-open-addons-manager = 開啟附加元件與佈景主題
    .label = 開啟附加元件與佈景主題
floorp-custom-actions-forget-history = 清除歷史記錄
    .label = 清除歷史記錄
floorp-custom-actions-quick-forget-history = 快速清除歷史記錄
    .label = 快速清除歷史記錄
floorp-custom-actions-clear-recent-history = 清除最近的歷史紀錄
    .label = 清除最近的歷史紀錄
floorp-custom-actions-search-history = 搜尋記錄
    .label = 搜尋記錄
floorp-custom-actions-manage-history = 管理歷史記錄
    .label = 管理歷史記錄
floorp-custom-actions-open-downloads = 開啟下載資料夾
    .label = 開啟下載資料夾
floorp-custom-actions-show-bms = 切換顯示管理工具側邊欄
    .label = 切換顯示管理工具側邊欄
floorp-custom-actions-show-current-panel = 切換顯示當前面板
    .label = 切換顯示當前面板
floorp-custom-actions-show-bookmark-sidebar = 顯示書籤側邊欄
    .label = 顯示書籤側邊欄
floorp-custom-actions-show-history-sidebar = 顯示歷史側邊欄
    .label = 顯示歷史側邊欄
floorp-custom-actions-show-synced-tabs-sidebar = 顯示已同步分頁側邊欄
    .label = 顯示已同步分頁側邊欄
floorp-custom-actions-reverse-sidebar = 反轉側邊欄位置
    .label = 反轉側邊欄位置
floorp-custom-actions-hide-sidebar = 隱藏側邊欄
    .label = 隱藏側邊欄
floorp-custom-actions-show-sidebar = 顯示側邊欄
    .label = 顯示側邊欄
floorp-custom-actions-toggle-sidebar = 切換側邊欄
    .label = 切換側邊欄
floorp-custom-actions-open-previous-workspace = 開啟之前的工作空間
    .label = 開啟之前的工作空間
floorp-custom-actions-open-next-workspace = 開啟下一個工作空間
    .label = 開啟下一個工作空間
floorp-custom-actions-show-panel-1 = 切換面板 1
    .label = 切換面板 1
floorp-custom-actions-show-panel-2 = 切換面板 2
    .label = 切換面板 2
floorp-custom-actions-show-panel-3 = 切換面板 3
    .label = 切換面板 3
floorp-custom-actions-show-panel-4 = 切換面板 4
    .label = 切換面板 4
floorp-custom-actions-show-panel-5 = 切換面板 5
    .label = 切換面板 5
floorp-custom-actions-show-panel-6 = 切換面板 6
    .label = 切換面板 6
floorp-custom-actions-show-panel-7 = 切換面板 7
    .label = 切換面板 7
floorp-custom-actions-show-panel-8 = 切換面板 8
    .label = 切換面板 8
floorp-custom-actions-show-panel-9 = 切換面板 9
    .label = 切換面板 9
floorp-custom-actions-show-panel-10 = 切換面板 10
    .label = 切換面板 10
floorp-custom-actions-open-split-view-on-left = 將此分頁置於分割視圖左側
    .label = 將此分頁置於分割視圖左側
floorp-custom-actions-open-split-view-on-right = 將此分頁置於分割視圖右側
    .label = 將此分頁置於分割視圖右側
floorp-custom-actions-close-split-view = 關閉分割視圖分頁
    .label = 關閉分割視圖分頁
floorp-custom-actions-custom-action-1 = 自訂操作 1
    .label = 自訂操作 1
floorp-custom-actions-custom-action-2 = 自訂操作 2
    .label = 自訂操作 2
floorp-custom-actions-custom-action-3 = 自訂操作 3
    .label = 自訂操作 3
floorp-custom-actions-custom-action-4 = 自訂操作 4
    .label = 自訂操作 4
floorp-custom-actions-custom-action-5 = 自訂操作 5
    .label = 自訂操作 5
floorp-custom-actions-rest-mode = 開啟休息模式
    .label = 開啟休息模式
floorp-custom-actions-hide-user-interface = 切換使用者介面
    .label = 切換使用者介面
floorp-custom-actions-toggle-navigation-panel = 切換顯示瀏覽版面
    .label = 切換顯示瀏覽版面
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = 啟動
    .tooltiptext = 使用此設定檔啟動 { -brand-short-name }
floorp-profiles-in-use = 已經在使用此設定檔。
floorp-profiles-title = 設定檔
floorp-profile-manager = 設定檔管理器
floorp-profiles-create = 建立設定檔
floorp-profile = 設定檔
    .label = 設定檔管理器
    .tooltiptext = 開啟設定檔管理器
fxa-not-signed-in = 尚未登入
###################################################################### Private Container ##############################################################
floorp-private-container-name = 私隱
floorp-toggle-private-container = 
    .label = 在私隱/無容器中重新開啟
    .accesskey = P
open-in_private-container = 
    .label = 用私隱容器在新分頁開啟
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = 在分割視圖中開啟
floorp-split-view-fixed-menu = 
    .label = Split this Tab in a Tab without Split View
floorp-split-view-open-menu-disabled = 
    .label = 需要有未分割及未選中的分頁以進行分割視圖
split-view-remove-button = 移除分割視圖
split-view-title = 分割視圖設定
split-view-position = 位置
split-view-flex-type = 排列型式
split-view-position-top = 頂端
split-view-position-left = 預設
split-view-position-right = 反向
split-view-flex-column = 垂直
split-view-flex-row = 水平
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = 使用手機掃描 QR Code
qrcode-generate-page-action = 
    .tooltiptext = 與手機分享此頁面
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = 統合擴充套件按鈕
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = 安裝應用程式
    .tooltiptext = 將此網站安裝為 PWA 應用程式
ssb-page-action-title = 安裝應用程式
ssb-app-open-button = 
    .label = 在應用程式中開啟
ssb-app-install-button = 
    .label = 安裝
ssb-app-cancel-button = 
    .label = 取消
floorp-open-manage-ssb-page = 
    .label = 管理已安裝的 PWA 應用程式
appmenuitem-webapps = 
    .label = PWA 應用程式
appmenu-open-installed-apps-subheader = 開啟已安裝的 PWA 應用程式
appmenuitem-install-current-page = 
    .label = 將此網站安裝為 PWA 應用程式
appmenuitem-open-current-page = 
    .label = 在已安裝的 PWA 應用上開啟此網站
appmenuitem-contextmenu-open-app = 
    .label = 開啟此 PWA 應用程式
appmenuitem-contextmenu-uninstall-app = 
    .label = 移除此 PWA 應用程式

## Preferences

category-ssb = 
    .label = PWA 應用程式
    .tooltiptext = PWA 應用程式
category-ssb-title = PWA 應用程式
floorp-ssb-title = PWA 應用程式
floorp-ssb-description = PWA 應用程式 是指可以安裝為應用程式的網站。安裝後可於 { -brand-short-name } 應用程式選單或 Windows 開始畫面 裡開啟。
ssb-preferences = PWA 應用程式設定
floorp-enable-ssb = 
    .label = 啟用 PWA 應用程式
floorp-enable-ssb-with-experimental = 
    .label = 啟用 PWA 應用程式 (實驗性質)
floorp-enable-ssb-description = 此功能在 Mac 以及 Linux 平台上仍屬於實驗性質。建議在 Windows 平台上啟用此功能。
floorp-disable-toolbars = 
    .label = 在 PWA 應用程式 停用工具列
floorp-disable-toolbars-description = 此設定將會把 PWA 應用程式 視窗內所有的擴充套件及工具列隱藏。
ssb-installed-list-title = 已安裝的 PWA 應用程式
ssb-uninstall-title = 移除此 PWA 應用程式
ssb-uninstall-message = 你是否要從 { -brand-short-name } 移除此 PWA 應用程式？
ssb-uninstall-button = 
    .label = 移除
ssb-uninstall-cancel = 取消
######################################################################### Download Notification ###############################################################
floorp-started-download = 下載開始
floorp-finished-download = 下載已完成
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } 已經是最新版本！
floorp-notificationContent-latest = 您現在使用的 { -brand-short-name } 已經是最新版本。
floorp-notificationTitle = { -brand-short-name } 已有新版本！
floorp-notificationContent = 點擊下載最新版本。
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = 關閉下方所有分頁
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = 關閉下方所有分頁
    .accesskey = E
