# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> adalah salah satu peramban domestik yang dikembangkan di Jepang. Peramban ini didasarkan pada Firefox dan terus beroperasi di bawah <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, untuk meningkatkan web. Ingin membantu? <label data-l10n-name="helpus-donateLink">Berikan donasi</label>
icon-creator = Pencipta ikon <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> dan <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Daftar kontributor dan pengembang <label data-l10n-name="about-contributor"></label>
#################################################################### about:preferences ####################################################################

pane-design-title = Desain
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Diperlukan pengaktifan ulang untuk menerapkan perubahan
tab-width = Lebar minimum tab
tab-height = Tinggi minimal tab
preferences-tabs-newtab-position = Posisi tab baru
open-new-tab-use-default = 
    .label = Membuka tab baru pada posisi bawaan
open-new-tab-at-the-end = 
    .label = Buka tab baru di ujung Tab Bar
open-new-tab-next-to-current = 
    .label = Membuka tab baru di samping tab yang sedang dibuka
multirow-tabs-limit = 
    .label = Aktifkan batas baris untuk tab multibaris
multirow-tabs-newtab = 
    .label = Tempatkan tombol "Buka tab baru" di akhir baris tab paling bawah
multirow-tabs-value = Jumlah baris saat tab multi-baris diaktifkan
enable-tab-sleep = 
    .label = Aktifkan Tab Tidur
tab-sleep-timeout-minutes-value = Tab akan tidur jika tidak aktif selama (menit)
tab-sleep-settings-button = Pengaturan...
tab-sleep-settings-dialog-title = 
    .title = Pengaturan Tab Tidur
tab-sleep-settings-dialog-excludehosts-label = Kecualikan host
tab-sleep-settings-dialog-excludehosts-label-2 = Masukkan satu host per baris.
tab-sleep-tab-context-menu-excludetab = Biarkan tab terjaga
enable-tab-scroll-change = 
    .label = Beralih tab dengan menggulir tetikus Anda
enable-tab-scroll-reverse = 
    .label = Membalikkan arah gulir tab
enable-tab-scroll-wrap = 
    .label = Membungkus tab gulir di bagian tepi
enable-double-click-block = 
    .label = Tutup tab dengan klik ganda
enable-show-pinned-tabs-title = 
    .label = Menampilkan judul tab yang disematkan
tabbar-preference = Bilah Tab
tab-normal-mode = 
    .label = Bawaan
hide-horizontality-tabs = 
    .label = Sembunyikan tab pada Bilah Tab Horizontal
verticalTab-setting = 
    .label = Optimalkan browser untuk Tab Bar Vertikal
move-tabbar-position = 
    .label = Menampilkan Tab Bar di bawah Toolbar
tabbar-on-bottom = 
    .label = Menampilkan Tab Bar di bagian bawah jendela
tabbar-favicon-color = 
    .label = Warnai Bilah Tab dengan warna favicon situs web saat ini
tabbar-style-preference = Gaya Bilah Tab
horizontal-tabbar = 
    .label = Bilah Tab Horizontal
tabbar-style-description = Diperlukan pengaktifan ulang { -brand-short-name } untuk menerapkan pengaturan ini sepenuhnya.
multirow-tabbar = 
    .label = Bilah Tab Multibaris
vertical-tabbar = 
    .label = Bilah Tab Vertikal (eksperimental)
native-vertical-tab-show-right = 
    .label = Tampilkan Bilah Tab Vertikal di sisi kanan jendela
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = Tutup Bilah Tab Vertikal
floorp-show-vertical-tab-newtab-button = 
    .label = Tampilkan tombol "Buka tab baru" dalam Bilah Tab Vertikal
floorp-show-vertical-tab-scrollbar = 
    .label = Tampilkan bilah gulir pada Bilah Tab Vertikal
TST = Tab Gaya Pohon
about-TST = Tree Style Tab adalah pengaya populer yang memungkinkan Anda menampilkan tab dalam struktur seperti pohon. Pengaya ini sudah terintegrasi sebelumnya di { -brand-short-name }. Silakan pasang pengaya untuk mengaktifkan Tab Gaya Pohon { -brand-short-name }.
treestyletab-Settings = 
    .label = Tab Gaya Pohon Runtuh
sidebar-reverse-position-toolbar = Tampilkan Bilah Samping di sisi lain
bookmarks-bar-settings = Bilah Alat Markah (hanya satu opsi yang dapat digunakan dalam satu waktu)
bookmarks-focus-mode = 
    .label = Sembunyikan Bilah Alat Markah kecuali jika Anda mengarahkan kursor ke bilah navigasi
bookmarks-bottom-mode = 
    .label = Tampilkan Bilah Alat Markah di bagian bawah { -brand-short-name }
navbar-settings = Bilah Navigasi
show-nav-bar-bottom = 
    .label = Tampilkan bilah alat di bagian bawah { -brand-short-name } (eksperimental)
disable-extension-check-compatibility-option = 
    .label = Do not check for compatibility with add-ons (deprecated)
other-preference = Preferensi Lainnya
search-positon-top = 
    .label = Tampilkan Bilah Pencarian di bagian atas halaman
allow-auto-restart = 
    .label = Mulai ulang secara otomatis ketika pengaturan yang memerlukan pengaktifan ulang diubah
disable-fullscreen-notification = 
    .label = Tidak menampilkan notifikasi saat memasuki layar penuh

## Browser Theme

system-color-settings = Sebagian tema memiliki mode terang dan gelap - pilih mode mana yang Anda inginkan untuk digunakan oleh tema-tema ini.
preferences-theme-appearance-header = Mode Tema
system-theme-dark = 
    .label = Gelap
system-theme-light = 
    .label = Terang
system-theme-auto = 
    .label = Ikuti tampilan sistem

## User interface preferences

ui-preference = Tampilan browser
preferences-browser-appearance-description = Pilih desain pihak ketiga bawaan untuk digunakan di { -brand-short-name }. Beberapa desain mungkin tidak kompatibel dengan konfigurasi Anda.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (lawas)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (New)

## Download Manager

download-notification-preferences = Pemberitahuan Unduhan
start-always-notify = 
    .label = Beri tahu hanya saat memulai unduhan
finish-always-notify = 
    .label = Beri tahu hanya ketika unduhan selesai
always-notify = 
    .label = Beri tahu saat memulai unduhan dan saat unduhan selesai
do-not-notify = 
    .label = Nonaktifkan notifikasi unduhan

## Sidebar

profiles-button-label = Kelola Profil
floorp-help-button-label = Dukungan { -brand-short-name }
appmenuitem-reboot = 
    .label = Mulai ulang

## DMR UI

download-mgr-UI = 
    .label = Aktifkan Pengelola Unduhan SimpleUI
downloading-red-color = 
    .label = Gunakan ikon unduhan berwarna merah saat mengunduh
sidebar-preferences = Bilah samping
bsb-preferences = Pengaturan Bilah Samping Pengelola Peramban
view-sidebar2-right = 
    .label = Menampilkan Bilah Samping Pengelola Peramban di sebelah kanan
enable-sidebar2 = 
    .label = Aktifkan Bilah Samping Pengelola Peramban
visible-bms = 
    .label = Menampilkan Bilah Samping Pengelola Peramban
hide-bms-to-unload-panel = 
    .label = Bongkar panel saat menyembunyikan panel
enable-addons-in-sidebar2-with-experimental = 
    .label = Aktifkan Skrip Konten Pengaya di Bilah Sisi Pengelola Peramban (eksperimental)
enable-addons-in-sidebar2 = 
    .label = Aktifkan Skrip Konten Pengaya di Bilah Sisi Pengelola Peramban
sidebar2-enable-addons-desc = Jika pengaturan ini diaktifkan, pengaya pemblokiran iklan dan pengaya lainnya akan berfungsi di bilah sisi. Namun, tidak semua pengaya akan berfungsi.
custom-URL-option = Atur URL Panel Web
set-custom-URL-button = 
    .label = Atur URL Khusus...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Bilah Samping Pengelola Peramban
bsb-context = Gunakan Kontainer berikut ini
bsb-userAgent-label = 
    .label = Gunakan Agen Pengguna Seluler di Panel Web ini
bsb-width = Lebar (jika diatur ke 0, nilai global akan digunakan)
bsb-page = Halaman untuk membuka
bsb-add = Menambahkan Panel Web pada Bilah Sisi Manajer Browser
bsb-setting = Pengaturan Panel Web
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Situs web
sidebar2-pref-delete = 
    .label = Hapus
sidebar2-pref-setting = 
    .label = Pengaturan
sidebar2-global-width = Lebar Panel Web Global
use-icon-provider-option = Gunakan Penyedia Ikon
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (tersedia di Tiongkok)
use-icon-provider-option-hatena = 
    .label = Hatena (tersedia di Tiongkok)
memory-and-performance = Memori dan Performa
min-memory = 
    .label = Penggunaan Memori Minimum (kinerja rendah)
balance-memory = 
    .label = Seimbangkan Penggunaan Memori dan Kinerja
max-memory = 
    .label = Performa Terbaik (penggunaan memori tinggi)
delete-border-and-roundup-option = 
    .label = Bulatkan sudut-sudut laman

## DualTheme

dualtheme-enable = 
    .label = Enable Dual Theme (Deprecated)
floorp-enable-dualtheme-description = Dual Theme feature may cause problems with extensions. Please use with caution.
newtab-background = { -brand-short-name } Latar Belakang Rumah
newtab-background-random-image = 
    .label = Gambar acak dari Unsplash
newtab-background-gradation = 
    .label = Gradien
newtab-background-not-background = 
    .label = Nonaktifkan latar belakang
newtab-background-selected-image = 
    .label = Folder khusus...
newtab-background-selected-one-image = 
    .label = Gambar khusus...
newtab-background-folder = Gunakan gambar dari folder ini:
newtab-background-image = Gunakan gambar:
newtab-choose-image = Pilih Gambar ...
newtab-background-folder-reload = 
    .label = Muat ulang gambar
newtab-background-folder-default = 
    .label = Kembalikan Default
newtab-background-folder-open = 
    .label = Buka folder
newtab-background-folder-choose = Pilih folder gambar...
newtab-background-image-choose = Pilih gambar ...
newtab-background-extensions = Gunakan gambar dengan pengaya berkas berikut ini (dipisahkan dengan ",")
disable-blur-on-newtab = 
    .label = Nonaktifkan efek buram di Beranda { -brand-short-name }
disable-releasenote-on-newtab = 
    .label = Nonaktifkan Catatan Rilis dan Tautan Dukungan di Beranda { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Nonaktifkan kredit gambar (Unsplash) di Beranda { -brand-short-name }

## Lepton Preferences

about-lepton = Sesuaikan { -brand-short-name } dengan Lepton
lepton-preference-button = 
    .label = Pengaturan Lepton...
    .accesskey = L
lepton-header = Pengaturan Lepton
lepton-preference = Pengaturan Lepton
photon-mode = 
    .label = Gunakan desain Photon
lepton-mode = 
    .label = Gunakan desain Lepton
protonfix-mode = 
    .label = Gunakan desain Proton yang telah diubah
autohide-preference = Sembunyikan elemen peramban secara otomatis
floorp-lepton-enable-tab-autohide = 
    .label = Sembunyikan tab secara otomatis
floorp-lepton-enable-navbar-autohide = 
    .label = Sembunyikan Bilah Alat secara otomatis
floorp-lepton-enable-sidebar-autohide = 
    .label = Sembunyikan Bilah Sisi secara otomatis
floorp-lepton-enable-urlbar-autohide = 
    .label = Sembunyikan Bilah Alamat secara otomatis
floorp-lepton-enable-back-button-autohide = 
    .label = Sembunyikan tombol kembali secara otomatis
floorp-lepton-enable-forward-button-autohide = 
    .label = Sembunyikan tombol maju secara otomatis
floorp-lepton-enable-page-action-button-autohide = 
    .label = Sembunyikan tombol secara otomatis pada Baris Alamat
floorp-lepton-enable-toolbar-overlap = 
    .label = Menampilkan Bilah Alat di atas konten situs web
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Sembunyikan Bilah Alat secara otomatis saat menampilkan konten "ltr"
hide-preference = Kelola elemen browser
floorp-lepton-enable-tab_icon-hide = 
    .label = Sembunyikan ikon tab
floorp-lepton-enable-tabbar-hide = 
    .label = Sembunyikan Bilah Tab
floorp-lepton-enable-navbar-hide = 
    .label = Sembunyikan Bilah Alat
floorp-lepton-enable-sidebar_header-hide = 
    .label = Sembunyikan Tajuk Bilah Samping
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Sembunyikan ikon Bilah Alamat
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Sembunyikan ikon Bilah Markah
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Sembunyikan label Bilah Markah
floorp-lepton-enable-disabled_menu-hide = 
    .label = Sembunyikan item menu konteks yang dinonaktifkan
floorp-lepton-disable-userChrome-icon = 
    .label = Menonaktifkan menu konteks dan ikon menu panel Lepton
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Aktifkan ikon menu konteks Lepton
positon-preferences = Penyesuaian posisi
floorp-lepton-enable-centered-tab = 
    .label = Memusatkan label di tab
floorp-lepton-enable-centered-urlbar = 
    .label = Memusatkan teks di Bilah Alamat
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Tengahkan item Bilah Markah
urlbar-preferences = Bilah Alamat
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Pindahkan ikon Bar Alamat ke sisi kiri
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Saat mengetik, tampilkan tombol "Kunjungi"
floorp-lepton-enable-always-show-page_action = 
    .label = Selalu tampilkan tindakan halaman di Bilah Alamat
tabbar-preferences = Bilah Tab
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Bilah Tab di Bilah Judul
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Gabungkan Bilah Tab dan Bilah Alat
lepton-sidebar-preferences = Bilah samping
floorp-lepton-enable-overlap-sidebar = 
    .label = Tampilkan Bilah Samping di atas konten situs web
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Beranda (Default)
floorp-home-prefs-content-header = { -brand-short-name } Beranda Konten
floorp-home-prefs-content-description = Pilih konten yang ingin Anda lihat di Halaman Beranda { -brand-short-name } .

## Notes

floorp-notes = { -brand-short-name } Catatan
restore-from-backup = Memulihkan Catatan dari cadangan
enable-notes-sync = 
    .label = Aktifkan { -brand-short-name } Sinkronisasi Catatan
about-notes-backup-tips = Catatan { -brand-short-name } menggunakan Firefox Sync untuk menyinkronkan catatan Anda dengan perangkat lain. Jika Anda kehilangan catatan, Anda dapat memulihkannya dari cadangan. Cadangan dibuat saat Anda membuka { -brand-short-name }.
notes-sync-description = Hal ini dapat mengatasi masalah kehilangan konten akibat menimpa catatan selama sinkronisasi.
backuped-time = Didukung di
notes-backup-option = Pengaturan Pencadangan
backup-option-button = Pengaturan Pencadangan...
restore-from-backup-prompt-title = { -brand-short-name } Layanan Pemulihan Catatan
restore-from-this-backup = Pulihkan Catatan kembali ke kondisi awal saat pencadangan ini?
restore-button = Pulihkan

## user.js

header-userjs = user.js
userjs-customize = Sesuaikan { -brand-short-name } dengan user.js
about-userjs-customize = user.js adalah file konfigurasi yang memungkinkan Anda untuk menyesuaikan { -brand-short-name }. Berkas user.js diunduh dari Internet dan menimpa berkas user.js Anda saat ini. Harap cadangkan berkas user.js Anda saat ini sebelum melanjutkan. Konfigurasi user.js akan diterapkan secara otomatis setelah memulai ulang { -brand-short-name }.
userjs-label = daftar user.js
userjs-prompt = Terapkan user.js ini?
apply-userjs-attention = Menerapkan user.js baru akan menimpa berkas user.js Anda saat ini.
apply-userjs-attention2 = Harap cadangkan file user.js Anda saat ini sebelum melanjutkan.
userjs-button = Pengaturan user.js...
userjs-select-option = Kelola user.js yang saat ini digunakan di { -brand-short-name } untuk meningkatkan kinerja dan privasi.
apply-userjs-button = Menerapkan

## userjs Options

default-userjs-label = Bawaan { -brand-short-name }
about-default-userjs = Telemetri dinonaktifkan. Seimbang { -brand-short-name } dengan berbagai penyesuaian yang diaktifkan.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS secara default. Perlindungan Cookie Total dengan isolasi situs. Pemisahan status dan jaringan yang disempurnakan. Berbagai peningkatan lainnya.
default-label = Yokoffing Default
about-default = Semua yang penting. Tidak ada yang rusak. Ini adalah user.js Anda.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Meningkatkan kecepatan penjelajahan Firefox secara signifikan. Buat Chrome bersaing ketat!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Rapikan laman tab baru. Hapus Pocket. Kembalikan mode ringkas sebagai opsi. Hentikan notifikasi laman web, pop-up, dan gangguan lainnya.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Dapatkan pengguliran yang mulus seperti Edge di browser favorit Anda - atau pilih sesuatu yang sesuai dengan gaya Anda.
select-workspace = Pilih Ruang Kerja
workspace-select-icon = Pilih Ikon Ruang Kerja
    .label = Pilih Ikon Ruang Kerja
workspace-select-container = Pilih Tab Kontainer
    .label = Pilih Tab Kontainer
workspace-customize = 
    .title = Sesuaikan Ruang Kerja
floorp-no-workspace-container = 
    .label = No Container
workspace-icon-article = 
    .label = Artikel
workspace-icon-book = 
    .label = Buku
workspace-icon-briefcase = 
    .label = Pekerjaan
workspace-icon-cart = 
    .label = Belanja
workspace-icon-chat = 
    .label = Obrolan
workspace-icon-chill = 
    .label = Pribadi
workspace-icon-circle = 
    .label = Lingkaran
workspace-icon-compass = 
    .label = Kompas
workspace-icon-code = 
    .label = Kode
workspace-icon-dollar = 
    .label = Bank
workspace-icon-fence = 
    .label = Pagar
workspace-icon-fingerprint = 
    .label = Pribadi
workspace-icon-food = 
    .label = Makanan
workspace-icon-fruit = 
    .label = Buah
workspace-icon-game = 
    .label = Gim
workspace-icon-gear = 
    .label = Perlengkapan
workspace-icon-gift = 
    .label = Hadiah
workspace-icon-key = 
    .label = Kunci
workspace-icon-lightning = 
    .label = Petir
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Catatan
workspace-icon-paint = 
    .label = Cat
workspace-icon-photo = 
    .label = Foto
workspace-icon-pin = 
    .label = Sematkan
workspace-icon-pet = 
    .label = Hewan peliharaan
workspace-icon-question = 
    .label = Pertanyaan
workspace-icon-smartphone = 
    .label = Ponsel
workspace-icon-star = 
    .label = Bintang
workspace-icon-tree = 
    .label = Pohon
workspace-icon-vacation = 
    .label = Liburan
workspace-icon-love = 
    .label = Cinta
workspace-icon-moon = 
    .label = Bulan
workspace-icon-music = 
    .label = Musik
workspace-icon-user = 
    .label = Pengguna
# Custom Keyboard Shortcuts
floorp-CSK-title = Pintasan papan ketik khusus
floorp-CSK-description = Sesuaikan pintasan papan ketik { -brand-short-name }. { -brand-short-name } menyediakan lebih dari 80 pintasan papan ketik yang dapat disesuaikan! Pintasan papan ketik duplikat tidak akan berfungsi. Mulai { -brand-short-name } ulang untuk menerapkan pengaturan ini.
disable-fx-actions = 
    .label = Nonaktifkan pintasan papan ketik Mozilla Firefox
customize-Action = 
    .label = Tambahkan pintasan
remove-Action = 
    .label = Hapus pintasan
CSK-reset-title = Atur ulang pintasan papan ketik khusus
CSK-reset-description = Atur ulang pintasan papan ketik khusus ke bawaan { -brand-short-name }.
CSK-reset-label = Atur ulang pintasan papan ketik khusus
CSK-reset-button = Kembalikan Default
CSK-manage-title = Kelola pintasan papan ketik
CSK-remove-shortcutkey = Hapus pintasan papan ketik khusus?
CSK-remove-shortcutkey-description = Apakah Anda yakin ingin menghapus pintasan papan ketik ini?
CSK-restore-default = Kembalikan Default?
CSK-restore-default-description = Pulihkan pintasan papan ketik { -brand-short-name } bawaan? Pintasan Anda saat ini akan hilang.
CSK-reboot-browser-label = Mulai ulang { -brand-short-name } untuk menerapkan pengaturan ini
CSK-reboot-browser-button = Mulai ulang { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Pintasan papan ketik saat ini: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Pintasan papan ketik saat ini: { $key }.
CSK-keyborad-shortcut-is-changed = (Tidak Diterapkan)
floorp-custom-actions-tab-action = Tab Tindakan
floorp-custom-actions-page-action = Tindakan Halaman
floorp-custom-actions-visible-action = Tindakan yang Terlihat
floorp-custom-actions-search-action = Tindakan Pencarian
floorp-custom-actions-tools-action = Tindakan Alat
floorp-custom-actions-bookmark-action = Tindakan Markah
floorp-custom-actions-open-page-action = Tindakan Halaman Terbuka
floorp-custom-actions-history-action = Tindakan Sejarah
floorp-custom-actions-pip-action = Tindakan Gambar dalam Gambar
floorp-custom-actions-downloads-action = Tindakan Unduhan
floorp-custom-actions-sidebar-action = Tindakan Bilah Samping
floorp-custom-actions-bms-action = Tindakan Bilah Samping Pengelola Peramban
floorp-custom-actions-split-view-action = Tindakan Tampilan Terpisah
floorp-custom-actions-workspaces-action = Tindakan Ruang Kerja
floorp-custom-actions-custom-action = Tindakan Khusus (Eksperimental)

## Mouse Gestures

mouse-gesture = Gestur Tetikus
mouse-gesture-description = Gesturefy harus diinstal untuk menggunakan gerakan mouse dengan { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy adalah pengaya yang menambahkan gerakan tetikus ke peramban Anda. Jika { -brand-short-name } mendeteksi pemasangan pengaya ini, ini akan menambahkan perintah gerakan ke Gesturefy yang hanya tersedia di { -brand-short-name }. Pengaya ini juga dapat membuat tab baru!
# Translate
TWS = Terjemahkan Halaman Web
about-TWS = Terjemahkan halaman Anda dalam waktu nyata menggunakan Google atau Yandex. Anda juga dapat menerjemahkan teks yang dipilih atau seluruh halaman.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Pusat Privasi
block-more-tracker = Blokir lebih banyak Iklan dan Pelacak
block-tracker = Bagian ini berisi seperangkat pengaya yang dirancang untuk memblokir iklan dan pelacak
view-at-AMO = Lihat addon ini di addons.mozilla.org
uBlock-Origin = Asal uBlock
about-uboori = uBlock Origin memblokir iklan, pelacak ekstensif, dan situs-situs berbahaya tambahan.
Facebook-Container = Wadah Facebook
about-Facebook-Container = Cegah Facebook melacak Anda di web. Pengaya Facebook Container membantu Anda mengendalikan dan mengisolasi aktivitas web Anda dari Facebook.

## Fingerprinting

fingerprint-header = Menahan Sidik Jari & kebocoran alamat IP
block-fingerprint = Sidik jari adalah mekanisme pelacakan yang bergantung pada fitur unik browser dan sistem operasi Anda. Bagian ini berisi pengaturan untuk lebih meningkatkan perlindungan ini di luar pemblokiran default.
enable-firefox-fingerprint-protections = 
    .label = Enable strong protection against fingerprinting
about-firefox-fingerprint-protection = Mengaktifkan perlindungan oleh Firefox termasuk mode cahaya paksa, menonaktifkan beberapa API, dll. Beberapa situs mungkin rusak.
fingerprint-Protection = 
    .label = Perlindungan anti-sidik jari
html5-canvas-prompt-settings = 
    .label = Secara otomatis mengabaikan permintaan konfirmasi akses untuk data gambar HTML5
canvas-prompt = Mencegah situs web menggunakan prompt pembacaan kanvas kecuali diizinkan secara manual.
disable-webgl = 
    .label = Menonaktifkan WebGL
about-webgl = WebGL adalah API Javascript yang digunakan untuk merender grafik, yang dapat digunakan untuk mengidentifikasi GPU.
Canvas-Blocker = Pemblokir Kanvas
about-CB = Add-on ini memalsukan data yang digunakan oleh teknik sidik jari.
WebRTC-connection = WebRTC adalah standar yang menyediakan panggilan waktu nyata. Jika Anda menonaktifkan pengaturan ini, Anda tidak akan dapat menggunakan Discord, dll.
WebRTC = 
    .label = Aktifkan Koneksi WebRTC
################################################################### browser ###############################################################

rest-mode = Beristirahat...
rest-mode-description = { -brand-short-name } saat ini ditangguhkan. Tekan ENTER atau OK untuk melanjutkan.
Sidebar2 = 
    .label = Bilah Samping Pengelola Peramban
    .tooltiptext = Ubah keterlihatan bilah sisi
sidebar2-mute-and-unmute = 
    .label = Bisukan/Suarakan Panel ini
sidebar2-unload-panel = 
    .label = Bongkar Panel ini
sidebar2-change-ua-panel = 
    .label = Alihkan Agen Pengguna Seluler
sidebar2-delete-panel = 
    .label = Hapus Panel ini
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom In
sidebar2-zoom-out = 
    .label = Zoom Out
sidebar2-reset-zoom = 
    .label = Reset Zoom
sidebar2-close-button = 
    .tooltiptext = Tutup Bilah Sisi
sidebar-back-button = 
    .tooltiptext = Kembali
sidebar-forward-button = 
    .tooltiptext = Teruskan
sidebar-reload-button = 
    .tooltiptext = Muat ulang
sidebar-go-index-button = 
    .tooltiptext = Pulanglah.
sidebar-muteAndUnmute-button = 
    .tooltiptext = Bilah samping Bisukan/Senyapkan
sidebar2-browser-manager-sidebar = Pengelola Peramban
show-browser-manager-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-browser-manager-sidebar } Bilah sisi
sidebar2-bookmark-sidebar = Markah
show-bookmark-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-bookmark-sidebar } Bilah sisi
sidebar2-history-sidebar = Sejarah
show-history-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-history-sidebar } Bilah sisi
sidebar2-download-sidebar = Unduhan
show-download-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-download-sidebar } Bilah sisi
sidebar2-notes-sidebar = Catatan
show-notes-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-notes-sidebar } Bilah sisi
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Pengaya dan tema
sidebar2-hide-sidebar-button = 
    .tooltiptext = Sembunyikan Bilah Samping Pengelola Peramban
sidebar-passwords-button = 
    .tooltiptext = Kata sandi
sidebar-preferences-button = 
    .tooltiptext = Pengaturan
sidebar-keepWidth-button = 
    .tooltiptext = Tetap gunakan lebar saat ini pada Panel ini
sidebar2-keep-width-for-global = 
    .label = Terapkan lebar ini ke semua panel tanpa lebar khusus
bsb-context-add = 
    .label = Menambahkan halaman ke Panel Web...
bsb-context-link-add = 
    .label = Menambahkan tautan ke Panel Web...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Buka Direktori Profil
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Membangun kembali file CSS browser
    .accesskey = R
make-browsercss-file = 
    .label = Membuat file CSS browser
    .accesskey = M
open-css-folder = 
    .label = Buka folder CSS
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Edit file userChrome.css
edit-userContentCss-editor = 
    .label = Edit file userContent.css
not-found-editor-path = Tidak dapat menemukan editor file CSS
set-pref-description = Masukkan lokasi file editor file CSS yang ingin Anda gunakan:
rebuild-complete = Pembangunan kembali telah selesai.
please-enter-filename = Masukkan nama file.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Buka kembali tab yang ditutup
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Aktifkan sebagai sub-tema
dual-theme-disable-addon-button = Nonaktifkan sub-tema
dual-theme-enabled-heading = Diaktifkan sebagai sub-tema
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Bilah Status
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Buka Panel Tab Gaya Pohon
gf-floorp-open-tree-style-tab-description = Buka Panel Tab Gaya Pohon di Bilah Samping
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Buka Panel Markah
gf-floorp-open-bookmarks-sidebar-description = Buka Panel Markah di Bilah Samping
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Buka Panel Riwayat
gf-floorp-open-history-sidebar-description = Buka Panel Riwayat di Bilah Samping
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Buka Panel Tab Tersinkron
gf-floorp-open-synctabs-sidebar-description = Buka Panel Tab Tersinkron di Bilah Samping
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Tutup Bilah Sisi
gf-floorp-close-sidebar-description = Tutup Bilah Sisi
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Buka BMS
gf-floorp-open-browser-manager-sidebar-description = Buka Bilah Sisi Pengelola Peramban jika Panel Web Bilah Sisi Pengelola Peramban dimuat
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Tutup BMS
gf-floorp-close-browser-manager-sidebar-description = Menutup Bilah Sisi Pengelola Peramban
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Saklar BMS
gf-floorp-show-browser-manager-sidebar-description = Beralih ke Bilah Sisi Pengelola Peramban
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Sembunyikan Bilah Status
gf-floorp-hide-statusbar-description = Sembunyikan Bilah Status
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Saklar Bilah Status
gf-floorp-show-statusbar-description = Tampilkan atau Sembunyikan Bilah Status
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Buka Bilah Sisi pengaya yang dipilih
gf-floorp-open-extension-sidebar-description = Buka pengaya yang dipilih di Bilah Samping
gf-floorp-open-extension-sidebar-settings-addons-id = Penambahan Bilah Samping
gf-floorp-open-extension-sidebar-settings-addons-id-description = Perpanjangan dari add-on yang terbuka pada bilah sisi
gf-floorp-open-extension-sidebar-settings-list-default = Silakan pilih add-on
gf-floorp-open-extension-sidebar-settings-list-unknwon = Pengaya yang tidak dikenal
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Pembaruan ditemukan!
update-portable-notification-found-message = Mengunduh pembaruan...
update-portable-notification-ready-title = Siap untuk memperbarui!
update-portable-notification-ready-message = { -brand-short-name } akan diperbarui pada peluncuran berikutnya.
update-portable-notification-success-title = Pembaruan berhasil!
update-portable-notification-success-message = Pembaruan berhasil! Semoga Anda menikmati versi { -brand-short-name } yang baru!
update-portable-notification-failed-title = Pembaruan gagal.
update-portable-notification-failed-redirector-message = Pembaruan gagal. Memulai ulang peramban Anda dapat mengatasi masalah ini.
update-portable-notification-failed-prepare-message = Gagal menyiapkan pembaruan.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Pembaruan Portabel
floorp-update-application-auto-enabled-option = 
    .label = Secara otomatis memeriksa pembaruan ke { -brand-short-name } portable. (Direkomendasikan)
##################################################################### Open link in external ###############################################################
openInExternal-title = Buka di browser eksternal
open-link-in-external-enabled-option = 
    .label = Aktifkan fitur "Buka di browser eksternal"
open-link-in-external-select-browser-option = Pilih browser yang akan dibuka
open-link-in-external-select-browser-option-default = 
    .label = Browser default
open-link-in-external-tab-context-menu = Buka di browser eksternal
open-link-in-external-tab-dialog-title-error = Terjadi kesalahan:
open-link-in-external-tab-dialog-message-default-browser-not-found = Browser default tidak ditemukan atau tidak dikonfigurasi.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Browser yang dipilih tidak ada.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Baru
memo-title-input-placeholder = Tulis judul di sini
memo-input-placeholder = Tulis atau tempel memo di sini
delete-memo = Hapus
save-memo = Simpan
memo-welcome-title = Selamat datang!
memo-first-tip = Selamat datang di Catatan { -brand-short-name }! Berikut ini beberapa petunjuk tentang cara menggunakannya!
memo-second-tip = Catatan { -brand-short-name } adalah buku catatan yang memungkinkan Anda menyimpan beberapa catatan yang disinkronkan di seluruh perangkat. Untuk mengaktifkan sinkronisasi, Anda harus masuk ke { -brand-short-name } dengan akun Firefox Anda.
memo-third-tip = Catatan { -brand-short-name } akan disimpan di pengaturan { -brand-short-name } Anda dan disinkronkan di seluruh perangkat menggunakan Firefox Sync. Firefox Sync mengenkripsi isi sinkronisasi dengan kata sandi akun Firefox Anda, sehingga tidak ada orang lain yang mengetahui isinya.
memo-import-data-tip = Firefox Sync bukan sebuah layanan pencadangan. Kami menyarankan Anda untuk membuat cadangan.
memo-new-title = Catatan Baru
chage-view-mode = Alihkan Mode Tampilan/Edit
readonly-mode = Offline (Hanya-baca)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Dukungan Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Hapus Unduhan
    .accesskey = D
    .tooltiptext = Hapus Unduhan
floorp-show-all-downloads = 
    .label = Tampilkan semua unduhan
    .accesskey = S
    .tooltiptext = Tampilkan semua unduhan
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Buat Ruang Kerja baru...
    .tooltiptext = Buat Ruang Kerja Baru
workspaces-manage-workspaces-button = 
    .label = Kelola Ruang Kerja...
    .tooltiptext = Kelola Ruang Kerja Anda
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Ubah Nama Ruang Kerja
    .accesskey = R
delete-this-workspace = 
    .label = Hapus Ruang Kerja
    .accesskey = D
manage-this-workspaces = 
    .label = Kelola Ruang Kerja...
    .accesskey = M
workspace-new-default-name = Ruang Kerja Baru
workspace-default-name = Bawaan
move-tab-another-workspace = 
    .label = Pindah ke Ruang Kerja lain
rename-workspace-prompt-title = Ubah Nama Ruang Kerja
rename-workspace-prompt-text = Masukkan Nama Ruang Kerja. Sebagian besar karakter dan simbol dapat digunakan.
workspaces-toolbar-button = Ruang Kerja
    .label = Ruang Kerja
    .tooltiptext = Pilih Ruang Kerja...

## Preferences

enable-workspaces = 
    .label = Aktifkan Ruang Kerja
    .tooltiptext = Aktifkan Ruang Kerja
workspace-notice = Ruang Kerja tidak akan berfungsi dengan pengaturan ini diaktifkan kecuali tombol Ruang Kerja ditempatkan pada bilah alat. Gunakan pengaturan ini jika Anda ingin menonaktifkan Ruang Kerja sepenuhnya.
enable-workspaces-with-experimental = 
    .label = Aktifkan Ruang Kerja (Eksperimental)
    .tooltiptext = Aktifkan Ruang Kerja (Eksperimental)
workspace-warning = Ruang Kerja tidak dapat digunakan dengan pengaya Tab Group. Jika Anda ingin menggunakan pengaya Tab Group, nonaktifkan Ruang Kerja dan buka { -brand-short-name } ulang.
category-workspaces = 
    .label = Ruang Kerja
    .tooltiptext = Ruang Kerja
pane-workspaces-title = Ruang Kerja
floorp-workspaces-title = { -brand-short-name } Ruang kerja
floorp-workspace-settings-button = Pengaturan Ruang Kerja...
floorp-preferences-label = Preferences
floorp-extensions-label = Ekstensi
floorp-private-label = Private
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = Mengelola Ruang Kerja di Bilah Sisi Manajer Browser
show-workspace-name-option = 
    .label = Tampilkan Nama Ruang Kerja pada Tombol Ruang Kerja Tab Bar
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Mode Berbagi
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Masuk ke Akun Firefox Anda
welcome-to-floorp = Selamat datang di { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Siap untuk memasuki?
welcome-skip-to-start-browsing = Lewati untuk Mulai Menjelajah
welcome-select-preferences-template = Pilih templat
welcome-minimum-template = Dasar
welcome-enable-basic-features = Aktifkan fitur dan pengaturan dasar untuk pengalaman yang sederhana.
welcome-medium-template = Default
welcome-enable-some-features = Aktifkan fitur dan pengaturan tambahan untuk pengalaman yang lebih baik.
welcome-maximum-template = Lanjutan
welcome-enable-most-of-features = Aktifkan fitur dan pengaturan lanjutan. Disarankan untuk pengguna berpengalaman.
welcome-go-next-setup = Berikutnya
welcome-select-browser-design = Memilih Desain Browser
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Desain Asli Lepton
welcome-design-photon-name = Desain Foton Lepton
welcome-design-ProtonFix-name = Desain Lepton ProtonFix
welcome-design-floorp-fluerial-name = { -brand-short-name } Desain Fluerial
welcome-design-firefox-proton-name = Desain Firefox Proton
welcome-import-data = Impor Data Browser Anda
welcome-import-data-description = Penyiapan cepat! Impor markah, kata sandi, dan lainnya dari peramban lama Anda. Pengguna Firefox dapat mengimpor data dari Firefox Sync.
welcome-import-data-button = Impor Data...
welcome-import-data-skip = Lewati Impor
welcome-select-button = Pilih
welcome-finish-setup = Setup selesai!
welcome-finish-setup-description = Anda sudah siap! Fitur lain seperti Tab Vertikal & Ruang Kerja dapat ditemukan di Pengaturan { -brand-short-name }. Selamat menikmati { -brand-short-name }!
welcomet-finish-setup = Mulai Menjelajahi Web
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Pintasan Papan Ketik
    .tooltiptext = Pintasan Papan Ketik
category-CSK-title = Pintasan Papan Ketik
shortcutkey-customize = 
    .title = Pintasan Papan Ketik
select-shortcutkeyAction = Memilih tindakan yang akan dipicu
shortcutkey-customize-key-list-placeholder = Pintasan papan ketik Anda akan muncul di sini
shortcut-key-label = Pintasan Papan Ketik
start-input-button-listen = Mulai Mendengarkan
end-input-button-listen = Berhenti Mendengarkan
shortcut-key-description = Klik "Mulai Mendengarkan" dan masukkan pintasan papan ketik baru untuk tindakan ini. Beberapa tombol dapat digunakan; namun, pintasan papan ketik tidak akan berfungsi jika sudah ditetapkan untuk tindakan lain.
floorp-custom-actions-open-new-tab = Buka tab baru
    .label = Buka tab baru
floorp-custom-actions-close-tab = Menutup tab saat ini
    .label = Menutup tab saat ini
floorp-custom-actions-open-new-window = Buka jendela baru
    .label = Buka jendela baru
floorp-custom-actions-open-new-private-window = Buka jendela pribadi baru
    .label = Buka jendela pribadi baru
floorp-custom-actions-close-window = Menutup jendela saat ini
    .label = Menutup jendela saat ini
floorp-custom-actions-restore-last-session = Pulihkan sesi terakhir
    .label = Pulihkan sesi terakhir
floorp-custom-actions-restore-last-window = Pulihkan jendela terakhir
    .label = Pulihkan jendela terakhir
floorp-custom-actions-show-next-tab = Menampilkan tab berikutnya
    .label = Menampilkan tab berikutnya
floorp-custom-actions-show-previous-tab = Menampilkan tab sebelumnya
    .label = Menampilkan tab sebelumnya
floorp-custom-actions-show-all-tabs-panel = Menampilkan panel semua tab
    .label = Menampilkan daftar tab
floorp-custom-actions-send-with-mail = Kirim dengan surat
    .label = Kirim melalui email
floorp-custom-actions-save-page = Simpan halaman
    .label = Simpan halaman
floorp-custom-actions-print-page = Halaman cetak
    .label = Halaman cetak
floorp-custom-actions-mute-current-tab = Beralih ke tab bisu/bukan bisu saat ini
    .label = Beralih ke tab bisu/bukan bisu saat ini
floorp-custom-actions-toggle-bookmark-toolbar = Saklar bilah alat markah
    .label = Saklar Bilah Alat Markah
floorp-custom-actions-show-source-of-page = Menampilkan sumber halaman
    .label = Buka Sumber Halaman
floorp-custom-actions-show-page-info = Tampilkan info halaman
    .label = Buka Info Halaman
floorp-custom-actions-zoom-in = Memperbesar
    .label = Memperbesar
floorp-custom-actions-zoom-out = Perkecil
    .label = Perkecil
floorp-custom-actions-reset-zoom = Atur ulang zoom
    .label = Atur ulang zoom
floorp-custom-actions-back = Kembali
    .label = Kembali
floorp-custom-actions-forward = Teruskan
    .label = Teruskan
floorp-custom-actions-reload = Muat ulang
    .label = Muat ulang
floorp-custom-actions-stop = Berhenti.
    .label = Berhenti.
floorp-custom-actions-force-reload = Paksa memuat ulang
    .label = Paksa memuat ulang
floorp-custom-actions-search-in-this-page = Cari di halaman ini
    .label = Temukan di halaman
floorp-custom-actions-show-next-search-result = Tampilkan kata pencarian berikutnya di hasil halaman ini
    .label = Berikutnya hasil "Temukan di halaman"
floorp-custom-actions-show-previous-search-result = Tampilkan kata pencarian sebelumnya di hasil halaman ini
    .label = Sebelumnya Hasil "Temukan di halaman"
floorp-custom-actions-search-the-web = Cari di web
    .label = Cari di web
floorp-custom-actions-open-migration-wizard = Buka panduan migrasi
    .label = Buka panduan migrasi
floorp-custom-actions-quit-from-application = Keluar dari aplikasi
    .label = Keluar { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Sesuaikan Bilah Alat
    .label = Buka Sesuaikan { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Beralih ke mode luring
    .label = Masuk ke mode offline
floorp-custom-actions-open-screen-capture = Buka alat penangkap layar
    .label = Ambil tangkapan layar
floorp-custom-actions-show-pip = Menampilkan gambar dalam gambar
    .label = Tampilkan Gambar dalam Gambar
floorp-custom-actions-bookmark-this-page = Tandai halaman ini
    .label = Tandai halaman ini
floorp-custom-actions-open-bookmarks-sidebar = Buka bilah sisi markah
    .label = Buka bilah samping Markah
floorp-custom-actions-open-bookmark-add-tool = Buka alat tambah markah
    .label = Tambahkan Markah
floorp-custom-actions-open-bookmark-add-toolbar = Buka jendela pop-up "Tambahkan markah baru"
    .label = Tambahkan ke Bilah Alat Markah
floorp-custom-actions-open-bookmarks-manager = Buka pengelola bookmark
    .label = Buka Pengelola Markah
floorp-custom-actions-show-bookmark-toolbar = Alihkan bilah alat markah
    .label = Alihkan Bilah Alat Markah
floorp-custom-actions-open-general-preferences = Buka preferensi umum
    .label = Buka Preferensi Umum
floorp-custom-actions-open-privacy-preferences = Buka preferensi privasi
    .label = Buka Preferensi Privasi
floorp-custom-actions-open-workspaces-preferences = Open Workspaces preferences
    .label = Preferensi Ruang Kerja Terbuka
floorp-custom-actions-open-containers-preferences = Preferensi wadah terbuka
    .label = Preferensi Wadah Terbuka
floorp-custom-actions-open-search-preferences = Buka preferensi pencarian
    .label = Buka Preferensi Pencarian
floorp-custom-actions-open-sync-preferences = Buka preferensi sinkronisasi
    .label = Buka Preferensi Sinkronisasi
floorp-custom-actions-open-task-manager = Buka pengelola tugas
    .label = Buka Pengelola Tugas { -brand-short-name }
floorp-custom-actions-open-home-page = Buka halaman beranda { -brand-short-name }
    .label = Buka beranda { -brand-short-name }
floorp-custom-actions-open-addons-manager = Buka pengaya dan tema
    .label = Buka Pengaya dan tema
floorp-custom-actions-forget-history = Lupakan sejarah
    .label = Lupakan sejarah
floorp-custom-actions-quick-forget-history = Lupakan sejarah dengan cepat
    .label = Lupakan sejarah dengan cepat
floorp-custom-actions-clear-recent-history = Hapus riwayat terbaru
    .label = Hapus riwayat terbaru
floorp-custom-actions-search-history = Riwayat pencarian
    .label = Riwayat pencarian
floorp-custom-actions-manage-history = Kelola riwayat
    .label = Kelola riwayat
floorp-custom-actions-open-downloads = Buka unduhan
    .label = Buka Unduhan
floorp-custom-actions-show-bms = Toggle browser manager sidebar
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = Menampilkan bilah sisi Markah
    .label = Tampilkan Bilah Sisi Markah
floorp-custom-actions-show-history-sidebar = Tampilkan bilah sisi riwayat
    .label = Tampilkan Bilah Sisi Riwayat
floorp-custom-actions-show-synced-tabs-sidebar = Menampilkan bilah sisi tab yang disinkronkan
    .label = Tampilkan Bilah Sisi Tab yang Disinkronkan
floorp-custom-actions-reverse-sidebar = Membalikkan posisi bilah sisi
    .label = Membalikkan posisi bilah sisi
floorp-custom-actions-hide-sidebar = Sembunyikan bilah sisi
    .label = Sembunyikan bilah sisi
floorp-custom-actions-show-sidebar = Alihkan bilah sisi
    .label = Alihkan bilah sisi
floorp-custom-actions-toggle-sidebar = Alihkan bilah sisi
    .label = Alihkan bilah sisi
floorp-custom-actions-open-previous-workspace = Open previous Workspace
    .label = Open previous Workspace
floorp-custom-actions-open-next-workspace = Open next Workspace
    .label = Open next Workspace
floorp-custom-actions-show-panel-1 = Alihkan panel 1
    .label = Alihkan panel 1
floorp-custom-actions-show-panel-2 = Alihkan panel 2
    .label = Alihkan panel 2
floorp-custom-actions-show-panel-3 = Alihkan panel 3
    .label = Alihkan panel 3
floorp-custom-actions-show-panel-4 = Alihkan panel 4
    .label = Alihkan panel 4
floorp-custom-actions-show-panel-5 = Alihkan panel 5
    .label = Alihkan panel 5
floorp-custom-actions-show-panel-6 = Alihkan panel 6
    .label = Alihkan panel 6
floorp-custom-actions-show-panel-7 = Alihkan panel 7
    .label = Alihkan panel 7
floorp-custom-actions-show-panel-8 = Alihkan panel 8
    .label = Alihkan panel 8
floorp-custom-actions-show-panel-9 = Alihkan panel 9
    .label = Alihkan panel 9
floorp-custom-actions-show-panel-10 = Alihkan panel 10
    .label = Alihkan panel 10
floorp-custom-actions-open-split-view-on-left = Buka tab saat ini di sebelah kiri dalam tampilan terpisah
    .label = Buka tab saat ini di sebelah kiri dalam tampilan terpisah
floorp-custom-actions-open-split-view-on-right = Buka tab saat ini di sebelah kanan dalam tampilan terpisah
    .label = Buka tab saat ini di sebelah kanan dalam tampilan terpisah
floorp-custom-actions-close-split-view = Tutup tampilan terpisah
    .label = Tutup tampilan terpisah
floorp-custom-actions-custom-action-1 = Tindakan khusus 1
    .label = Tindakan khusus 1
floorp-custom-actions-custom-action-2 = Tindakan khusus 2
    .label = Tindakan khusus 2
floorp-custom-actions-custom-action-3 = Tindakan khusus 3
    .label = Tindakan khusus 3
floorp-custom-actions-custom-action-4 = Tindakan khusus 4
    .label = Tindakan khusus 4
floorp-custom-actions-custom-action-5 = Tindakan khusus 5
    .label = Tindakan khusus 5
floorp-custom-actions-rest-mode = Aktifkan mode istirahat
    .label = Aktifkan mode istirahat
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
floorp-custom-actions-toggle-navigation-panel = Toggle Navigation Panel
    .label = Toggle Navigation Panel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Peluncuran
    .tooltiptext = Luncurkan { -brand-short-name } dengan profil ini
floorp-profiles-in-use = Profil ini sedang digunakan.
floorp-profiles-title = Profil
floorp-profile-manager = Manajer Profil
floorp-profiles-create = Buat Profil
floorp-profile = Profil
    .label = Manajer Profil
    .tooltiptext = Buka Manajer Profil
fxa-not-signed-in = Tidak masuk
###################################################################### Private Container ##############################################################
floorp-private-container-name = Pribadi
floorp-toggle-private-container = 
    .label = Buka Kembali secara Pribadi/Tanpa Kontainer
    .accesskey = P
open-in_private-container = 
    .label = Buka di Tab Baru dengan Wadah Pribadi
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Open in Split View
floorp-split-view-fixed-menu = 
    .label = Split this Tab in a Tab without Split View
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Remove Split View
split-view-title = Split View Settings
split-view-position = Posisi
split-view-flex-type = Flex Type
split-view-position-top = Sisi Atas
split-view-position-left = Bawaan
split-view-position-right = Reverse
split-view-flex-column = Vertikal
split-view-flex-row = Horizontal
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Pindai Kode QR dengan Ponsel Anda
qrcode-generate-page-action = 
    .tooltiptext = Bagikan halaman ini dengan ponsel Anda
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Tombol Pengaya Terpadu
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Pasang aplikasi
    .tooltiptext = Pasang situs ini sebagai aplikasi
ssb-page-action-title = Pasang aplikasi
ssb-app-open-button = 
    .label = Buka Di Aplikasi
ssb-app-install-button = 
    .label = Pasang
ssb-app-cancel-button = 
    .label = Batal
floorp-open-manage-ssb-page = 
    .label = Kelola Aplikasi Web terpasang
appmenuitem-webapps = 
    .label = Aplikasi Web
appmenu-open-installed-apps-subheader = Buka aplikasi web yang terpasang
appmenuitem-install-current-page = 
    .label = Pasang situs ini sebagai aplikasi
appmenuitem-open-current-page = 
    .label = Buka situs ini di aplikasi yang terpasang
appmenuitem-contextmenu-open-app = 
    .label = Buka aplikasi ini
appmenuitem-contextmenu-uninstall-app = 
    .label = Copot pemasangan aplikasi ini

## Preferences

category-ssb = 
    .label = Aplikasi Web
    .tooltiptext = Aplikasi Web
category-ssb-title = Aplikasi Web
floorp-ssb-title = Aplikasi Web
floorp-ssb-description = Aplikasi Web adalah situs web yang dapat dipasang sebagai aplikasi. Aplikasi ini dapat diluncurkan dari panel menu { -brand-short-name } atau menu Mulai Windows.
ssb-preferences = Pengaturan Aplikasi Web
floorp-enable-ssb = 
    .label = Aktifkan Aplikasi Web
floorp-enable-ssb-with-experimental = 
    .label = Aktifkan Aplikasi Web (Eksperimental)
floorp-enable-ssb-description = Fitur ini bersifat eksperimental pada Mac dan Linux. Disarankan untuk mengaktifkan fitur ini di Windows.
floorp-disable-toolbars = 
    .label = Nonaktifkan bilah alat di Jendela Aplikasi Web
floorp-disable-toolbars-description = Pengaturan ini akan menyembunyikan semua pengaya dan bilah alat pada Jendela Aplikasi Web.
ssb-installed-list-title = Aplikasi Web yang Terinstal
ssb-uninstall-title = Copot Pemasangan Aplikasi Web
ssb-uninstall-message = Apakah Anda yakin ingin mencopot pemasangan Aplikasi Web ini dari { -brand-short-name }?
ssb-uninstall-button = 
    .label = Copot pemasangan
ssb-uninstall-cancel = Batal
######################################################################### Download Notification ###############################################################
floorp-started-download = Pengunduhan dimulai
floorp-finished-download = Unduhan selesai
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } sudah diperbarui!
floorp-notificationContent-latest = { -brand-short-name } sudah diperbarui. Anda menggunakan versi { -brand-short-name } yang terkini.
floorp-notificationTitle = Versi baru { -brand-short-name } telah tersedia!
floorp-notificationContent = Klik untuk mengunduh versi terbaru.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
