# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> adalah salah satu peramban domestik yang dikembangkan di Jepang. Peramban ini didasarkan pada Firefox dan terus beroperasi di bawah <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, untuk meningkatkan web. Ingin membantu? <label data-l10n-name="helpus-donateLink">Berikan donasi</label>
icon-creator = Pencipta ikon <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> dan <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Daftar kontributor dan pengembang <label data-l10n-name="about-contributor"></label>
#################################################################### about:preferences ####################################################################

pane-design-title = Desain
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Diperlukan pengaktifan ulang untuk menerapkan perubahan
tab-width = Lebar minimum tab
preferences-tabs-newtab-position = Posisi tab baru
open-new-tab-use-default = 
    .label = Membuka tab baru pada posisi bawaan
open-new-tab-at-the-end = 
    .label = Buka tab baru di ujung Tab Bar
open-new-tab-next-to-current = 
    .label = Membuka tab baru di samping tab yang sedang dibuka
multirow-tabs-limit = 
    .label = Mengaktifkan batas baris untuk tab multibaris
multirow-tabs-newtab = 
    .label = Tempatkan tombol "Buka tab baru" di akhir baris tab paling bawah
multirow-tabs-value = Jumlah baris saat tab multi-baris diaktifkan
enable-tab-sleep = 
    .label = Mengaktifkan Tab Tidur
tab-sleep-timeout-minutes-value = Tab akan tidur jika tidak aktif selama (menit)
tab-sleep-settings-button = Pengaturan...
tab-sleep-settings-dialog-title = 
    .title = Pengaturan Tab Tidur
tab-sleep-settings-dialog-excludehosts-label = Mengecualikan host
tab-sleep-settings-dialog-excludehosts-label-2 = Masukkan satu host per baris.
tab-sleep-tab-context-menu-excludetab = Keep tab awake
enable-tab-scroll-change = 
    .label = Beralih tab dengan menggulir dengan mouse Anda
enable-tab-scroll-reverse = 
    .label = Membalikkan arah gulir tab
enable-tab-scroll-wrap = 
    .label = Membungkus tab gulir di bagian tepi
enable-double-click-block = 
    .label = Tutup tab dengan klik ganda
enable-show-pinned-tabs-title = 
    .label = Menampilkan judul tab yang disematkan
tabbar-preference = Bilah Tab
tab-normal-mode = 
    .label = Bawaan
hide-horizontality-tabs = 
    .label = Menyembunyikan tab pada Bilah Tab Horizontal
verticalTab-setting = 
    .label = Optimalkan browser untuk Tab Bar Vertikal
move-tabbar-position = 
    .label = Menampilkan Tab Bar di bawah Toolbar
tabbar-on-bottom = 
    .label = Menampilkan Tab Bar di bagian bawah jendela
tabbar-favicon-color = 
    .label = Warnai Bilah Tab dengan warna favicon situs web saat ini
tabbar-style-preference = Gaya Bilah Tab
horizontal-tabbar = 
    .label = Bilah Tab Horizontal
tabbar-style-description = Diperlukan pengaktifan ulang { -brand-short-name } untuk menerapkan pengaturan ini sepenuhnya.
multirow-tabbar = 
    .label = Bilah Tab Multibaris
vertical-tabbar = 
    .label = Bilah Tab Vertikal (eksperimental)
native-vertical-tab-show-right = 
    .label = Tampilkan Bilah Tab Vertikal di sisi kanan jendela
hover-vertical-tab = 
    .label = Collapse Vertical Tab Bar
floorp-show-vertical-tab-newtab-button = 
    .label = Tampilkan tombol "Buka tab baru" dalam Bilah Tab Vertikal
floorp-show-vertical-tab-scrollbar = 
    .label = Tampilkan bilah gulir pada Bilah Tab Vertikal
TST = Tab Gaya Pohon
about-TST = Tree Style Tab is a popular add-on that allows you to display tabs in a tree-like structure. This add-on is already pre-integrated in { -brand-short-name }. Please install the add-on to activate { -brand-short-name }'s Tree Style Tab.
treestyletab-Settings = 
    .label = Tab Gaya Pohon Runtuh
sidebar-reverse-position-toolbar = Tampilkan Bilah Samping di sisi lain
bookmarks-bar-settings = Bilah Alat Markah (hanya satu opsi yang dapat digunakan dalam satu waktu)
bookmarks-focus-mode = 
    .label = Menyembunyikan Bilah Alat Markah kecuali jika Anda mengarahkan kursor ke bilah navigasi
bookmarks-bottom-mode = 
    .label = Tampilkan Bilah Alat Markah di bagian bawah { -brand-short-name }
navbar-settings = Bilah Navigasi
show-nav-bar-bottom = 
    .label = Tampilkan bilah alat di bagian bawah { -brand-short-name } (eksperimental)
material-effect = 
    .label = Izinkan Mica For Everyone untuk memodifikasi desain browser
disable-extension-check-compatibility-option = 
    .label = Jangan memeriksa kompatibilitas dengan pengaya
other-preference = Preferensi Lainnya
enable-userscript = 
    .label = Enable legacy components
about-userscript = Enabling this feature may cause unexpected bugs or fatal errors.
search-positon-top = 
    .label = Display the Find Bar at the top of the page
allow-auto-restart = 
    .label = Mulai ulang secara otomatis ketika pengaturan yang memerlukan pengaktifan ulang diubah
disable-fullscreen-notification = 
    .label = Tidak menampilkan notifikasi saat memasuki layar penuh

## Browser Theme

system-color-settings = Sebagian tema memiliki mode terang dan gelap - pilih mode mana yang Anda inginkan untuk digunakan oleh tema-tema ini.
preferences-theme-appearance-header = Mode Tema
system-theme-dark = 
    .label = Gelap
system-theme-light = 
    .label = Terang
system-theme-auto = 
    .label = Ikuti tampilan sistem

## User interface preferences

ui-preference = Tampilan browser
preferences-browser-appearance-description = Pilih desain pihak ketiga bawaan untuk digunakan di { -brand-short-name }. Beberapa desain mungkin tidak kompatibel dengan konfigurasi Anda.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon・Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (deprecated)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (deprecated)
floorp-gnomeUI = 
    .label = GNOME Theme (deprecated)

## Download Manager

download-notification-preferences = Pemberitahuan Unduhan
start-always-notify = 
    .label = Beri tahu hanya saat memulai unduhan
finish-always-notify = 
    .label = Beri tahu hanya ketika unduhan selesai
always-notify = 
    .label = Beri tahu saat memulai unduhan dan saat unduhan selesai
do-not-notify = 
    .label = Nonaktifkan notifikasi unduhan

## Sidebar

profiles-button-label = Kelola Profil
floorp-help-button-label = Dukungan { -brand-short-name }
appmenuitem-reboot = 
    .label = Mulai ulang

## UserAgent

userAgent-preference = Agen Pengguna
default-useragent-mode = 
    .label = Gunakan Agen Pengguna Firefox (Bawaan)
windows-chrome-useragent-mode = 
    .label = Palsukan sebagai Chrome di Windows
macOS-chrome-useragent-mode = 
    .label = Palsukan sebagai Chrome di macOS
linux-chrome-useragent-mode = 
    .label = Palsukan sebagai Chrome di Linux
mobile-chrome-useragent-mode = 
    .label = Palsukan sebagai Chrome di iOS
use-custom-useragent-mode = 
    .label = Gunakan Agen Pengguna Lain

## DMR UI

download-mgr-UI = 
    .label = Aktifkan Pengelola Unduhan SimpleUI
downloading-red-color = 
    .label = Gunakan ikon unduhan berwarna merah saat mengunduh
sidebar-preferences = Bilah samping
bsb-preferences = Pengaturan Bilah Samping Pengelola Peramban
view-sidebar2-right = 
    .label = Menampilkan Bilah Samping Pengelola Peramban di sebelah kanan
enable-sidebar2 = 
    .label = Mengaktifkan Bilah Samping Pengelola Peramban
visible-bms = 
    .label = Menampilkan Bilah Samping Pengelola Peramban
hide-bms-to-unload-panel = 
    .label = Bongkar panel saat menyembunyikan panel
enable-addons-in-sidebar2-with-experimental = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar (experimental)
enable-addons-in-sidebar2 = 
    .label = Enable Extensions Content Scripts in Browser Manager Sidebar
sidebar2-enable-addons-desc = If this setting is enabled, ad blocking extensions and other extensions will work in the sidebar. However, not all extensions will work.
custom-URL-option = Mengatur URL Panel Web
set-custom-URL-button = 
    .label = Mengatur URL Khusus...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Bilah Samping Pengelola Peramban
bsb-context = Use the following Container
bsb-userAgent-label = 
    .label = Gunakan Agen Pengguna Seluler di Panel Web ini
bsb-width = Lebar (jika diatur ke 0, nilai global akan digunakan)
bsb-page = Halaman untuk membuka
bsb-add = Menambahkan Panel Web pada Bilah Sisi Manajer Browser
bsb-setting = Pengaturan Panel Web
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Situs web
sidebar2-pref-delete = 
    .label = Menghapus
sidebar2-pref-setting = 
    .label = Pengaturan
sidebar2-global-width = Lebar Panel Web Global
use-icon-provider-option = Use Icon Provider
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (tersedia di Tiongkok)
use-icon-provider-option-hatena = 
    .label = Hatena (tersedia di Tiongkok)
memory-and-performance = Memori dan Performa
min-memory = 
    .label = Penggunaan Memori Minimum (kinerja rendah)
balance-memory = 
    .label = Menyeimbangkan Penggunaan Memori dan Kinerja
max-memory = 
    .label = Best Performance (high memory usage)
delete-border-and-roundup-option = 
    .label = Mengitari sudut-sudut halaman
STG-smilar-workspaces-option = 
    .label = Make "Simple Tab Groups" add-on buttons look like Workspaces buttons

## DualTheme

dualtheme-enable = 
    .label = Mengaktifkan Tema Ganda
newtab-background = { -brand-short-name } Latar Belakang Rumah
newtab-background-random-image = 
    .label = Gambar acak dari Unsplash
newtab-background-gradation = 
    .label = Gradien
newtab-background-not-background = 
    .label = Nonaktifkan latar belakang
newtab-background-selected-image = 
    .label = Folder khusus...
newtab-background-selected-one-image = 
    .label = Custom image...
newtab-background-folder = Gunakan gambar dari folder ini:
newtab-background-image = Use image :
newtab-choose-image = Pilih Gambar ...
newtab-background-folder-reload = 
    .label = Muat ulang gambar
newtab-background-folder-default = 
    .label = Kembalikan Default
newtab-background-folder-open = 
    .label = Buka folder
newtab-background-folder-choose = Pilih folder gambar...
newtab-background-image-choose = Pilih gambar ...
newtab-background-extensions = Gunakan gambar dengan ekstensi file berikut ini (dipisahkan dengan ",")
disable-blur-on-newtab = 
    .label = Disable blur effect in { -brand-short-name } Home
disable-releasenote-on-newtab = 
    .label = Disable Release Note and Support Links in { -brand-short-name } Home
disable-imagecredit-on-newtab = 
    .label = Disable image credit (Unsplash) in { -brand-short-name } Home

## Lepton Preferences

about-lepton = Sesuaikan { -brand-short-name } dengan Lepton
lepton-preference-button = 
    .label = Pengaturan Lepton...
    .accesskey = L
lepton-header = Pengaturan Lepton
lepton-preference = Pengaturan Lepton
photon-mode = 
    .label = Gunakan desain Photon
lepton-mode = 
    .label = Gunakan desain Lepton
protonfix-mode = 
    .label = Gunakan desain Proton yang telah diubah
autohide-preference = Menyembunyikan elemen browser secara otomatis
floorp-lepton-enable-tab-autohide = 
    .label = Menyembunyikan tab secara otomatis
floorp-lepton-enable-navbar-autohide = 
    .label = Menyembunyikan Bilah Alat secara otomatis
floorp-lepton-enable-sidebar-autohide = 
    .label = Menyembunyikan Bilah Sisi secara otomatis
floorp-lepton-enable-urlbar-autohide = 
    .label = Menyembunyikan Bilah Alamat secara otomatis
floorp-lepton-enable-back-button-autohide = 
    .label = Secara otomatis menyembunyikan tombol kembali
floorp-lepton-enable-forward-button-autohide = 
    .label = Secara otomatis menyembunyikan tombol maju
floorp-lepton-enable-page-action-button-autohide = 
    .label = Menyembunyikan tombol secara otomatis pada Baris Alamat
floorp-lepton-enable-toolbar-overlap = 
    .label = Menampilkan Bilah Alat di atas konten situs web
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Secara otomatis menyembunyikan Bilah Alat saat menampilkan konten "ltr"
hide-preference = Mengelola elemen browser
floorp-lepton-enable-tab_icon-hide = 
    .label = Sembunyikan ikon tab
floorp-lepton-enable-tabbar-hide = 
    .label = Sembunyikan Bilah Tab
floorp-lepton-enable-navbar-hide = 
    .label = Sembunyikan Bilah Alat
floorp-lepton-enable-sidebar_header-hide = 
    .label = Menyembunyikan Header Bilah Samping
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Menyembunyikan ikon Bilah Alamat
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Menyembunyikan ikon Bilah Penanda
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Menyembunyikan label bar penanda
floorp-lepton-enable-disabled_menu-hide = 
    .label = Menyembunyikan item menu konteks yang dinonaktifkan
floorp-lepton-disable-userChrome-icon = 
    .label = Menonaktifkan menu konteks dan ikon menu panel Lepton
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Mengaktifkan ikon menu konteks Lepton
positon-preferences = Penyesuaian posisi
floorp-lepton-enable-centered-tab = 
    .label = Memusatkan label di tab
floorp-lepton-enable-centered-urlbar = 
    .label = Memusatkan teks di Bilah Alamat
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Item Bar Penanda Tengah
urlbar-preferences = Bilah Alamat
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Pindahkan ikon Bar Alamat ke sisi kiri
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = When typing, show a "Go" button
floorp-lepton-enable-always-show-page_action = 
    .label = Selalu tampilkan tindakan halaman di Bilah Alamat
tabbar-preferences = Bilah Tab
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Tab Bar in the Title Bar
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Menggabungkan Tab Bar dan Bilah Alat
lepton-sidebar-preferences = Bilah samping
floorp-lepton-enable-overlap-sidebar = 
    .label = Tampilkan Bilah Samping di atas konten situs web
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Beranda (Default)
floorp-home-prefs-content-header = { -brand-short-name } Beranda Konten
floorp-home-prefs-content-description = Pilih konten yang ingin Anda lihat di Halaman Beranda { -brand-short-name } .

## Notes

floorp-notes = { -brand-short-name } Catatan
restore-from-backup = Memulihkan Catatan dari cadangan
enable-notes-sync = 
    .label = Aktifkan { -brand-short-name } Sinkronisasi Catatan
about-notes-backup-tips = { -brand-short-name } Notes uses Firefox Sync to sync your notes with other devices. If you lose your notes, you can restore them from a backup. A backup is created when you launch { -brand-short-name }.
notes-sync-description = Hal ini dapat mengatasi masalah kehilangan konten akibat menimpa catatan selama sinkronisasi.
backuped-time = Didukung di
notes-backup-option = Pengaturan Pencadangan
backup-option-button = Pengaturan Pencadangan...
restore-from-backup-prompt-title = { -brand-short-name } Notes Restore Service
restore-from-this-backup = Mengembalikan Catatan kembali ke kondisi awal saat pencadangan ini?
restore-button = Mengembalikan

## user.js

header-userjs = user.js
userjs-customize = Sesuaikan { -brand-short-name } dengan user.js
about-userjs-customize = user.js adalah file konfigurasi yang memungkinkan Anda untuk menyesuaikan { -brand-short-name }. file user.js diunduh dari Internet dan menimpa file user.js Anda saat ini. Harap cadangkan file user.js Anda saat ini sebelum melanjutkan. konfigurasi user.js akan diterapkan secara otomatis setelah memulai ulang { -brand-short-name }.
userjs-label = daftar user.js
userjs-prompt = Terapkan user.js ini?
apply-userjs-attention = Menerapkan user.js baru akan menimpa berkas user.js Anda saat ini.
apply-userjs-attention2 = Harap cadangkan file user.js Anda saat ini sebelum melanjutkan.
userjs-button = Pengaturan user.js...
userjs-select-option = Kelola user.js yang saat ini digunakan di { -brand-short-name } untuk meningkatkan kinerja dan privasi.
apply-userjs-button = Menerapkan

## userjs Options

default-userjs-label = { -brand-short-name } Default
about-default-userjs = Telemetri dinonaktifkan. Seimbang { -brand-short-name } dengan berbagai penyesuaian yang diaktifkan.
Securefox-label = Yokoffing Securefox
about-Securefox = HTTPS secara default. Perlindungan Cookie Total dengan isolasi situs. Pemisahan status dan jaringan yang disempurnakan. Berbagai peningkatan lainnya.
default-label = Yokoffing Default
about-default = Semua yang penting. Tidak ada yang rusak. Ini adalah user.js Anda.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Meningkatkan kecepatan penjelajahan Firefox secara signifikan. Buat Chrome bersaing ketat!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Merapikan halaman tab baru. Hapus Pocket. Mengembalikan mode ringkas sebagai opsi. Menghentikan notifikasi halaman web, pop-up, dan gangguan lainnya.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Dapatkan pengguliran yang mulus seperti Edge di browser favorit Anda - atau pilih sesuatu yang sesuai dengan gaya Anda.
select-workspace = Pilih Ruang Kerja
workspace-select-icon = Pilih Ikon Ruang Kerja
    .label = Pilih Ikon Ruang Kerja
workspace-select-container = Pilih Tab Kontainer
    .label = Pilih Tab Kontainer
workspace-customize = 
    .title = Sesuaikan Ruang Kerja
floorp-no-workspace-conatiner = 
    .label = Tidak Ada Wadah
workspace-icon-article = 
    .label = Artikel
workspace-icon-book = 
    .label = Buku
workspace-icon-briefcase = 
    .label = Pekerjaan
workspace-icon-cart = 
    .label = Belanja
workspace-icon-chat = 
    .label = Obrolan
workspace-icon-chill = 
    .label = Pribadi
workspace-icon-circle = 
    .label = Lingkaran
workspace-icon-compass = 
    .label = Kompas
workspace-icon-code = 
    .label = Kode
workspace-icon-dollar = 
    .label = Bank
workspace-icon-fence = 
    .label = Pagar
workspace-icon-fingerprint = 
    .label = Pribadi
workspace-icon-food = 
    .label = Makanan
workspace-icon-fruit = 
    .label = Buah
workspace-icon-game = 
    .label = Gim
workspace-icon-gear = 
    .label = Perlengkapan
workspace-icon-gift = 
    .label = Hadiah
workspace-icon-key = 
    .label = Kunci
workspace-icon-lightning = 
    .label = Petir
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Catatan
workspace-icon-paint = 
    .label = Paint
workspace-icon-photo = 
    .label = Foto
workspace-icon-pin = 
    .label = Pin
workspace-icon-pet = 
    .label = Hewan peliharaan
workspace-icon-question = 
    .label = Pertanyaan
workspace-icon-smartphone = 
    .label = Ponsel
workspace-icon-star = 
    .label = Bintang
workspace-icon-tree = 
    .label = Pohon
workspace-icon-vacation = 
    .label = Liburan
workspace-icon-love = 
    .label = Cinta
workspace-icon-moon = 
    .label = Bulan
workspace-icon-music = 
    .label = Musik
workspace-icon-user = 
    .label = Pengguna
# Custom Keyboard Shortcuts
floorp-CSK-title = Pintasan keyboard khusus
floorp-CSK-description = Customize { -brand-short-name }'s keyboard shortcuts. { -brand-short-name } provides more than 80 customizable keyboard shortcuts! Duplicate keyboard shortcuts will not work. Restart { -brand-short-name } to apply these settings.
disable-fx-actions = 
    .label = Menonaktifkan pintasan keyboard Mozilla Firefox
customize-Action = 
    .label = Tambahkan pintasan
remove-Action = 
    .label = Hapus pintasan
CSK-reset-title = Mengatur ulang pintasan keyboard khusus
CSK-reset-description = Atur ulang pintasan keyboard khusus ke default { -brand-short-name }.
CSK-reset-label = Mengatur ulang pintasan keyboard khusus
CSK-reset-button = Kembalikan Default
CSK-manage-title = Mengelola pintasan keyboard
CSK-remove-shortcutkey = Menghapus pintasan keyboard khusus?
CSK-remove-shortcutkey-description = Apakah Anda yakin ingin menghapus pintasan keyboard ini?
CSK-restore-default = Kembalikan Default?
CSK-restore-default-description = Restore { -brand-short-name }'s default keyboard shortcuts? Your current shortcuts will be lost.
CSK-reboot-browser-label = Mulai ulang { -brand-short-name } untuk menerapkan pengaturan ini
CSK-reboot-browser-button = Mulai ulang { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Pintasan keyboard saat ini: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Pintasan keyboard saat ini: { $key }.
CSK-keyborad-shortcut-is-changed = (Tidak Diterapkan)
floorp-custom-actions-tab-action = Tab Tindakan
floorp-custom-actions-page-action = Tindakan Halaman
floorp-custom-actions-visible-action = Tindakan yang Terlihat
floorp-custom-actions-search-action = Tindakan Pencarian
floorp-custom-actions-tools-action = Tindakan Alat
floorp-custom-actions-bookmark-action = Tindakan Penanda
floorp-custom-actions-open-page-action = Tindakan Halaman Terbuka
floorp-custom-actions-history-action = Tindakan Sejarah
floorp-custom-actions-pip-action = Tindakan Gambar dalam Gambar
floorp-custom-actions-downloads-action = Tindakan Unduhan
floorp-custom-actions-sidebar-action = Tindakan Bilah Samping
floorp-custom-actions-bms-action = Tindakan Bilah Samping Pengelola Peramban
floorp-custom-actions-split-view-action = Split View Actions
floorp-custom-actions-workspaces-action = Workspaces Actions
floorp-custom-actions-custom-action = Tindakan Khusus (Eksperimental)

## Mouse Gestures

mouse-gesture = Gerakan Mouse
mouse-gesture-description = Gesturefy harus diinstal untuk menggunakan gerakan mouse dengan { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy is an extension that adds mouse gestures to your browser. If { -brand-short-name } detects the installation of this add-on, it will add gesture commands to Gesturefy that are only available in { -brand-short-name }. This add-on also create new tabs!
# Translate
TWS = Terjemahkan Halaman Web
about-TWS = Terjemahkan halaman Anda secara real time menggunakan Google atau Yandex. Anda juga dapat menerjemahkan teks yang dipilih atau seluruh halaman.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Pusat Privasi
block-more-tracker = Blokir lebih banyak Iklan dan Pelacak
block-tracker = Bagian ini berisi seperangkat ekstensi yang dirancang untuk memblokir iklan dan pelacak
view-at-AMO = Lihat addon ini di addons.mozilla.org
uBlock-Origin = Asal uBlock
about-uboori = uBlock Origin memblokir iklan, pelacak ekstensif, dan situs-situs berbahaya tambahan.
Facebook-Container = Wadah Facebook
about-Facebook-Container = Mencegah Facebook melacak Anda di web. Ekstensi Facebook Container membantu Anda mengendalikan dan mengisolasi aktivitas web Anda dari Facebook.

## Fingerprinting

fingerprint-header = Menahan Sidik Jari & kebocoran alamat IP
block-fingerprint = Sidik jari adalah mekanisme pelacakan yang bergantung pada fitur unik browser dan sistem operasi Anda. Bagian ini berisi pengaturan untuk lebih meningkatkan perlindungan ini di luar pemblokiran default.
enable-firefox-fingerprint-protections = Mengaktifkan perlindungan yang kuat terhadap sidik jari
about-firefox-fingerprint-protection = Mengaktifkan perlindungan oleh Firefox termasuk mode cahaya paksa, menonaktifkan beberapa API, dll. Beberapa situs mungkin rusak.
fingerprint-Protection = 
    .label = Perlindungan anti-sidik jari
html5-canvas-prompt-settings = 
    .label = Secara otomatis mengabaikan permintaan konfirmasi akses untuk data gambar HTML5
canvas-prompt = Mencegah situs web menggunakan prompt pembacaan kanvas kecuali diizinkan secara manual.
disable-webgl = 
    .label = Menonaktifkan WebGL
about-webgl = WebGL adalah API Javascript yang digunakan untuk merender grafik, yang dapat digunakan untuk mengidentifikasi GPU.
Canvas-Blocker = Pemblokir Kanvas
about-CB = Add-on ini memalsukan data yang digunakan oleh teknik sidik jari.
WebRTC-connection = WebRTC adalah standar yang menyediakan panggilan waktu nyata. Jika Anda menonaktifkan pengaturan ini, Anda tidak akan dapat menggunakan Discord, dll.
WebRTC = 
    .label = Mengaktifkan Koneksi WebRTC
################################################################### browser ###############################################################

rest-mode = Beristirahat...
rest-mode-description = { -brand-short-name } is currently suspended. Press ENTER or OK to continue.
Sidebar2 = 
    .label = Bilah Samping Pengelola Peramban
    .tooltiptext = Mengubah visibilitas bilah sisi
sidebar2-mute-and-unmute = 
    .label = Membisukan/Mengheningkan Panel ini
sidebar2-unload-panel = 
    .label = Bongkar Panel ini
sidebar2-change-ua-panel = 
    .label = Alihkan Agen Pengguna Seluler
sidebar2-delete-panel = 
    .label = Hapus Panel ini
sidebar2-close-button = 
    .tooltiptext = Tutup Bilah Sisi
sidebar-back-button = 
    .tooltiptext = Kembali
sidebar-forward-button = 
    .tooltiptext = Teruskan
sidebar-reload-button = 
    .tooltiptext = Muat ulang
sidebar-go-index-button = 
    .tooltiptext = Pulanglah.
sidebar-muteAndUnmute-button = 
    .tooltiptext = Bilah samping Bisukan/Senyapkan
sidebar2-browser-manager-sidebar = Pengelola Peramban
show-browser-manager-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-browser-manager-sidebar } Bilah sisi
sidebar2-bookmark-sidebar = Penanda
show-bookmark-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-bookmark-sidebar } Bilah sisi
sidebar2-history-sidebar = Sejarah
show-history-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-history-sidebar } Bilah sisi
sidebar2-download-sidebar = Unduhan
show-download-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-download-sidebar } Bilah sisi
sidebar2-notes-sidebar = Catatan
show-notes-sidebar = 
    .tooltiptext = Tampilkan { sidebar2-notes-sidebar } Bilah sisi
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Pengaya dan tema
sidebar2-hide-sidebar-button = 
    .tooltiptext = Hide Browser Manager Sidebar
sidebar-passwords-button = 
    .tooltiptext = Kata sandi
sidebar-preferences-button = 
    .tooltiptext = Pengaturan
sidebar-keepWidth-button = 
    .tooltiptext = Tetap gunakan lebar saat ini pada Panel ini
sidebar2-keep-width-for-global = 
    .label = Terapkan lebar ini ke semua panel tanpa lebar khusus
bsb-context-add = 
    .label = Menambahkan halaman ke Panel Web...
bsb-context-link-add = 
    .label = Menambahkan tautan ke Panel Web...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Buka Direktori Profil
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Membangun kembali file CSS browser
    .accesskey = R
make-browsercss-file = 
    .label = Membuat file CSS browser
    .accesskey = M
open-css-folder = 
    .label = Buka folder CSS
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Edit file userChrome.css
edit-userContentCss-editor = 
    .label = Edit file userContent.css
not-found-editor-path = Tidak dapat menemukan editor file CSS
set-pref-description = Masukkan lokasi file editor file CSS yang ingin Anda gunakan:
rebuild-complete = Pembangunan kembali telah selesai.
please-enter-filename = Masukkan nama file.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Buka kembali tab yang ditutup
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Aktifkan sebagai sub-tema
dual-theme-disable-addon-button = Nonaktifkan sub-tema
dual-theme-enabled-heading = Diaktifkan sebagai sub-tema
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Bilah Status
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Open Tree Style Tab Panel
gf-floorp-open-tree-style-tab-description = Open Tree Style Tab Panel on the Sidebar
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Open Bookmarks Panel
gf-floorp-open-bookmarks-sidebar-description = Open Bookmarks Panel on the Sidebar
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Open History Panel
gf-floorp-open-history-sidebar-description = Open History Panel on the Sidebar
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Open Synced Tabs Panel
gf-floorp-open-synctabs-sidebar-description = Open Synced Tabs Panel on the Sidebar
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Close Sidebar
gf-floorp-close-sidebar-description = Tutup Bilah Sisi
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Open BMS
gf-floorp-open-browser-manager-sidebar-description = Open Browser Manager Sidebar if the Web Panel of Browser Manager Sidebar is loaded
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Close BMS
gf-floorp-close-browser-manager-sidebar-description = Menutup Bilah Sisi Pengelola Peramban
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Toggle BMS
gf-floorp-show-browser-manager-sidebar-description = Beralih ke Bilah Sisi Pengelola Peramban
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Hide Status Bar
gf-floorp-hide-statusbar-description = Sembunyikan Bilah Status
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Toggle Status Bar
gf-floorp-show-statusbar-description = Menampilkan atau Menyembunyikan Bilah Status
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Open selected add-on Sidebar
gf-floorp-open-extension-sidebar-description = Open selected add-on on the Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id = Penambahan Bilah Samping
gf-floorp-open-extension-sidebar-settings-addons-id-description = Perpanjangan dari add-on yang terbuka pada bilah sisi
gf-floorp-open-extension-sidebar-settings-list-default = Silakan pilih add-on
gf-floorp-open-extension-sidebar-settings-list-unknwon = Pengaya yang tidak dikenal
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Pembaruan ditemukan!
update-portable-notification-found-message = Mengunduh pembaruan...
update-portable-notification-ready-title = Siap untuk memperbarui!
update-portable-notification-ready-message = { -brand-short-name } will be updated on the next launch.
update-portable-notification-success-title = Pembaruan berhasil!
update-portable-notification-success-message = Update succeeded! Hope you enjoy the new version of { -brand-short-name }!
update-portable-notification-failed-title = Pembaruan gagal.
update-portable-notification-failed-redirector-message = Pembaruan gagal. Memulai ulang browser Anda dapat mengatasi masalah ini.
update-portable-notification-failed-prepare-message = Gagal menyiapkan pembaruan.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } Pembaruan Portabel
floorp-update-application-auto-enabled-option = 
    .label = Secara otomatis memeriksa pembaruan ke { -brand-short-name } portable. (Direkomendasikan)
##################################################################### Open link in external ###############################################################
openInExternal-title = Buka di browser eksternal
open-link-in-external-enabled-option = 
    .label = Aktifkan fitur "Buka di browser eksternal"
open-link-in-external-select-browser-option = Pilih browser yang akan dibuka
open-link-in-external-select-browser-option-default = 
    .label = Browser default
open-link-in-external-tab-context-menu = Buka di browser eksternal
open-link-in-external-tab-dialog-title-error = Terjadi kesalahan:
open-link-in-external-tab-dialog-message-default-browser-not-found = Browser default tidak ditemukan atau tidak dikonfigurasi.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Browser yang dipilih tidak ada.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Baru
memo-title-input-placeholder = Tulis judul di sini
memo-input-placeholder = Tulis atau tempel memo di sini
delete-memo = Menghapus
save-memo = Simpan
memo-welcome-title = Selamat datang!
memo-first-tip = Welcome to { -brand-short-name } Notes! Here are some instructions on how to use it!
memo-second-tip = { -brand-short-name } Notes is a notepad that lets you store multiple notes that sync across devices. To enable synchronization, you need to sign in to { -brand-short-name } with your Firefox account.
memo-third-tip = { -brand-short-name } Notes will be saved in your { -brand-short-name } settings and synchronized across devices using Firefox Sync. Firefox Sync encrypts the contents of the sync with your Firefox account password, so no one but you know its contents.
memo-import-data-tip = Sinkronisasi Firefox bukan merupakan layanan pencadangan. Kami menyarankan anda untuk membuat cadangan.
memo-new-title = Catatan Baru
chage-view-mode = Alihkan Mode Tampilan/Edit
readonly-mode = Offline (Hanya-baca)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Dukungan Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Hapus Unduhan
    .accesskey = D
    .tooltiptext = Hapus Unduhan
floorp-show-all-downloads = 
    .label = Tampilkan semua unduhan
    .accesskey = S
    .tooltiptext = Tampilkan semua unduhan
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Create new Workspace...
    .tooltiptext = Create a new Workspace
workspaces-manage-workspaces-button = 
    .label = Manage Workspaces...
    .tooltiptext = Manage your Workspaces
rename-this-workspace = 
    .label = Rename Workspace
    .accesskey = R
delete-this-workspace = 
    .label = Delete Workspace
    .accesskey = D
manage-this-workspaces = 
    .label = Manage Workspaces...
    .accesskey = M
workspace-new-default-name = New Workspace
workspace-default-name = Default
move-tab-another-workspace = 
    .label = Pindah ke Ruang Kerja lain
rename-workspace-prompt-title = Rename Workspace
rename-workspace-prompt-text = Enter Workspace Name. Most characters and symbols can be used.
workspaces-toolbar-button = Workspaces
    .label = Workspaces
    .tooltiptext = Select a Workspace...

## Preferences

enable-workspaces = 
    .label = Enable Workspaces
    .tooltiptext = Enable Workspaces
workspace-notice = Workspaces will not work with this settings enabled unless the workspaces's button is placed on the toolbar. Use this setting if you want to disable Workspaces completely.
enable-workspaces-with-experimental = 
    .label = Enable Workspaces (Experimental)
    .tooltiptext = Enable Workspaces (Experimental)
workspace-warning = Workspaces cannot be used with Tab Group add-ons. If you want to use Tab Group add-ons, please disable Workspaces and restart { -brand-short-name }.
category-workspaces = 
    .label = Workspaces
    .tooltiptext = Workspaces
pane-workspaces-title = Workspaces
floorp-workspaces-title = { -brand-short-name } Ruang kerja
floorp-workspace-settings-button = Pengaturan Ruang Kerja...
change-to-close-workspace-popup-option = 
    .label = Popup tutup ruang kerja muncul saat memilih Ruang Kerja
manage-workspace-on-bms-option = 
    .label = Mengelola Ruang Kerja di Bilah Sisi Manajer Browser
show-workspace-name-option = 
    .label = Tampilkan Nama Ruang Kerja pada Tombol Ruang Kerja Tab Bar
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Mode Berbagi
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Masuk ke Akun Firefox Anda
welcome-to-floorp = Selamat datang di { -brand-short-name }!
welcome-discribe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Ready to dive in?
welcome-skip-to-start-browsing = Lewati untuk Mulai Menjelajah
welcome-select-preferences-template = Choose a template
welcome-minimum-template = Dasar
welcome-enable-basic-features = Enable basic features and settings for a simple experience.
welcome-medium-template = Default
welcome-enable-some-features = Enable additional features and settings for a better experience.
welcome-maximum-template = Lanjutan
welcome-enable-most-of-features = Enable advanced features and settings. Recommended for experienced users.
welcome-go-next-setup = Berikutnya
welcome-select-browser-design = Memilih Desain Browser
welcome-discribe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = Desain Asli Lepton
welcome-design-photon-name = Desain Foton Lepton
welcome-design-ProtonFix-name = Desain Lepton ProtonFix
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Desain Firefox Proton
welcome-import-data = Impor Data Browser Anda
welcome-import-data-description = Quick setup! Import your bookmarks, passwords, and more from your old browser. Firefox users can import data from Firefox Sync.
welcome-import-data-button = Mengimpor Data...
welcome-import-data-skip = Lewati Impor
welcome-select-button = Pilih
welcome-finish-setup = Setup selesai!
welcome-finish-setup-description = You're all set! Other features like Vertical Tabs & Workspaces can be found in { -brand-short-name }'s Settings. Enjoy { -brand-short-name }!
welcomet-finish-setup = Mulai Menjelajahi Web
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Keyboard Shortcuts
    .tooltiptext = Keyboard Shortcuts
category-CSK-title = Keyboard Shortcuts
shortcutkey-customize = 
    .title = Keyboard Shortcuts
select-shortcutkeyAction = Memilih tindakan yang akan dipicu
shortcutkey-customize-key-list-placeholder = Pintasan keyboard Anda akan muncul di sini
shortcut-key-label = Keyboard Shortcut
start-input-button-listen = Start Listening
end-input-button-listen = Stop Listening
shortcut-key-description = Click "Start Listening" and enter your new keyboard shortcut for this action. Multiple keys can be used; however, keyboard shortcuts will not work if already assigned to other actions.
floorp-custom-actions-open-new-tab = Buka tab baru
    .label = Buka tab baru
floorp-custom-actions-close-tab = Menutup tab saat ini
    .label = Menutup tab saat ini
floorp-custom-actions-open-new-window = Buka jendela baru
    .label = Buka jendela baru
floorp-custom-actions-open-new-private-window = Buka jendela pribadi baru
    .label = Buka jendela pribadi baru
floorp-custom-actions-close-window = Menutup jendela saat ini
    .label = Menutup jendela saat ini
floorp-custom-actions-restore-last-session = Mengembalikan sesi terakhir
    .label = Mengembalikan sesi terakhir
floorp-custom-actions-restore-last-window = Mengembalikan jendela terakhir
    .label = Mengembalikan jendela terakhir
floorp-custom-actions-show-next-tab = Menampilkan tab berikutnya
    .label = Menampilkan tab berikutnya
floorp-custom-actions-show-previous-tab = Menampilkan tab sebelumnya
    .label = Menampilkan tab sebelumnya
floorp-custom-actions-show-all-tabs-panel = Menampilkan panel semua tab
    .label = Menampilkan daftar tab
floorp-custom-actions-send-with-mail = Kirim dengan surat
    .label = Kirim melalui email
floorp-custom-actions-save-page = Simpan halaman
    .label = Simpan halaman
floorp-custom-actions-print-page = Halaman cetak
    .label = Halaman cetak
floorp-custom-actions-mute-current-tab = Beralih ke tab bisu/bukan bisu saat ini
    .label = Beralih ke tab bisu/bukan bisu saat ini
floorp-custom-actions-toggle-bookmark-toolbar = Toggle bookmark toolbar
    .label = Mengalihkan Bilah Alat Penanda
floorp-custom-actions-show-source-of-page = Menampilkan sumber halaman
    .label = Buka Sumber Halaman
floorp-custom-actions-show-page-info = Tampilkan info halaman
    .label = Buka Info Halaman
floorp-custom-actions-zoom-in = Memperbesar
    .label = Memperbesar
floorp-custom-actions-zoom-out = Perkecil
    .label = Perkecil
floorp-custom-actions-reset-zoom = Atur ulang zoom
    .label = Atur ulang zoom
floorp-custom-actions-back = Kembali
    .label = Kembali
floorp-custom-actions-forward = Teruskan
    .label = Teruskan
floorp-custom-actions-reload = Muat ulang
    .label = Muat ulang
floorp-custom-actions-stop = Berhenti.
    .label = Berhenti.
floorp-custom-actions-force-reload = Paksa memuat ulang
    .label = Paksa memuat ulang
floorp-custom-actions-search-in-this-page = Cari di halaman ini
    .label = Temukan di halaman
floorp-custom-actions-show-next-search-result = Tampilkan kata pencarian berikutnya di hasil halaman ini
    .label = Berikutnya hasil "Temukan di halaman"
floorp-custom-actions-show-previous-search-result = Tampilkan kata pencarian sebelumnya di hasil halaman ini
    .label = Sebelumnya Hasil "Temukan di halaman"
floorp-custom-actions-search-the-web = Cari di web
    .label = Cari di web
floorp-custom-actions-open-migration-wizard = Buka panduan migrasi
    .label = Buka panduan migrasi
floorp-custom-actions-quit-from-application = Keluar dari aplikasi
    .label = Keluar { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Customize Toolbar
    .label = Buka Sesuaikan { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Enter offline mode
    .label = Masuk ke mode offline
floorp-custom-actions-open-screen-capture = Buka alat penangkap layar
    .label = Mengambil tangkapan layar
floorp-custom-actions-show-pip = Menampilkan gambar dalam gambar
    .label = Tampilkan Gambar dalam Gambar
floorp-custom-actions-bookmark-this-page = Tandai halaman ini
    .label = Tandai halaman ini
floorp-custom-actions-open-bookmarks-sidebar = Buka bilah sisi penanda
    .label = Bilah samping Buka Penanda
floorp-custom-actions-open-bookmark-add-tool = Buka alat tambah penanda
    .label = Tambahkan Penanda
floorp-custom-actions-open-bookmark-add-toolbar = Open "Add a new bookmark" pop-up window
    .label = Tambahkan ke Bilah Alat Penanda
floorp-custom-actions-open-bookmarks-manager = Buka pengelola bookmark
    .label = Buka Pengelola Penanda
floorp-custom-actions-show-bookmark-toolbar = Alihkan bilah alat penanda
    .label = Alihkan Bilah Alat Penanda
floorp-custom-actions-open-general-preferences = Buka preferensi umum
    .label = Buka Preferensi Umum
floorp-custom-actions-open-privacy-preferences = Buka preferensi privasi
    .label = Buka Preferensi Privasi
floorp-custom-actions-open-workspaces-preferences = Membuka preferensi ruang kerja
    .label = Preferensi Ruang Kerja Terbuka
floorp-custom-actions-open-containers-preferences = Preferensi wadah terbuka
    .label = Preferensi Wadah Terbuka
floorp-custom-actions-open-search-preferences = Buka preferensi pencarian
    .label = Buka Preferensi Pencarian
floorp-custom-actions-open-sync-preferences = Buka preferensi sinkronisasi
    .label = Buka Preferensi Sinkronisasi
floorp-custom-actions-open-task-manager = Buka pengelola tugas
    .label = Buka Pengelola Tugas { -brand-short-name }
floorp-custom-actions-open-home-page = Buka halaman beranda { -brand-short-name }
    .label = Buka beranda { -brand-short-name }
floorp-custom-actions-open-addons-manager = Open add-ons and themes
    .label = Buka Pengaya dan tema
floorp-custom-actions-forget-history = Lupakan sejarah
    .label = Lupakan sejarah
floorp-custom-actions-quick-forget-history = Lupakan sejarah dengan cepat
    .label = Lupakan sejarah dengan cepat
floorp-custom-actions-clear-recent-history = Hapus riwayat terbaru
    .label = Hapus riwayat terbaru
floorp-custom-actions-search-history = Riwayat pencarian
    .label = Riwayat pencarian
floorp-custom-actions-manage-history = Mengelola riwayat
    .label = Mengelola riwayat
floorp-custom-actions-open-downloads = Buka unduhan
    .label = Buka Unduhan
floorp-custom-actions-show-bsm = Menampilkan bilah sisi manajer browser
    .label = Menampilkan Bilah Samping Pengelola Peramban
floorp-custom-actions-show-bookmark-sidebar = Menampilkan bilah sisi penanda
    .label = Tampilkan Bilah Sisi Penanda
floorp-custom-actions-show-history-sidebar = Tampilkan bilah sisi riwayat
    .label = Tampilkan Bilah Sisi Riwayat
floorp-custom-actions-show-synced-tabs-sidebar = Menampilkan bilah sisi tab yang disinkronkan
    .label = Tampilkan Bilah Sisi Tab yang Disinkronkan
floorp-custom-actions-reverse-sidebar = Membalikkan posisi bilah sisi
    .label = Membalikkan posisi bilah sisi
floorp-custom-actions-hide-sidebar = Sembunyikan bilah sisi
    .label = Sembunyikan bilah sisi
floorp-custom-actions-show-sidebar = Alihkan bilah sisi
    .label = Alihkan bilah sisi
floorp-custom-actions-toggle-sidebar = Toggle sidebar
    .label = Toggle sidebar
floorp-custom-actions-open-previous-workspace = Buka ruang kerja sebelumnya
    .label = Buka ruang kerja sebelumnya
floorp-custom-actions-open-next-workspace = Buka ruang kerja berikutnya
    .label = Buka ruang kerja berikutnya
floorp-custom-actions-show-panel-1 = Alihkan panel 1
    .label = Alihkan panel 1
floorp-custom-actions-show-panel-2 = Alihkan panel 2
    .label = Alihkan panel 2
floorp-custom-actions-show-panel-3 = Alihkan panel 3
    .label = Alihkan panel 3
floorp-custom-actions-show-panel-4 = Alihkan panel 4
    .label = Alihkan panel 4
floorp-custom-actions-show-panel-5 = Alihkan panel 5
    .label = Alihkan panel 5
floorp-custom-actions-show-panel-6 = Alihkan panel 6
    .label = Alihkan panel 6
floorp-custom-actions-show-panel-7 = Alihkan panel 7
    .label = Alihkan panel 7
floorp-custom-actions-show-panel-8 = Alihkan panel 8
    .label = Alihkan panel 8
floorp-custom-actions-show-panel-9 = Alihkan panel 9
    .label = Alihkan panel 9
floorp-custom-actions-show-panel-10 = Alihkan panel 10
    .label = Alihkan panel 10
floorp-custom-actions-open-split-view-on-left = Open current tab on left in split view
    .label = Open current tab on left in split view
floorp-custom-actions-open-split-view-on-right = Open current tab on right in split view
    .label = Open current tab on right in split view
floorp-custom-actions-custom-action-1 = Tindakan khusus 1
    .label = Tindakan khusus 1
floorp-custom-actions-custom-action-2 = Tindakan khusus 2
    .label = Tindakan khusus 2
floorp-custom-actions-custom-action-3 = Tindakan khusus 3
    .label = Tindakan khusus 3
floorp-custom-actions-custom-action-4 = Tindakan khusus 4
    .label = Tindakan khusus 4
floorp-custom-actions-custom-action-5 = Tindakan khusus 5
    .label = Tindakan khusus 5
floorp-custom-actions-rest-mode = Enable rest mode
    .label = Enable rest mode
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Peluncuran
    .tooltiptext = Luncurkan { -brand-short-name } dengan profil ini
floorp-profiles-in-use = Profil ini sedang digunakan.
floorp-profiles-title = Profil
floorp-profile-manager = Manajer Profil
floorp-profiles-create = Buat Profil
floorp-profile = Profil
    .label = Manajer Profil
    .tooltiptext = Buka Manajer Profil
fxa-not-signed-in = Tidak masuk
###################################################################### Private Container ##############################################################
floorp-private-container-name = Pribadi
floorp-toggle-private-container = 
    .label = Buka Kembali secara Pribadi/Tanpa Kontainer
    .accesskey = P
open-in_private-container = 
    .label = Buka di Tab Baru dengan Wadah Pribadi
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = Fixed in split view
splitview-show-on-right = 
    .label = Show on right
splitview-show-on-left = 
    .label = Show on left
splitview-close-split-tab = 
    .label = Close split tab
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Pindai Kode QR dengan Ponsel Anda
qrcode-generate-page-action = 
    .tooltiptext = Bagikan halaman ini dengan ponsel Anda
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Tombol Ekstensi Terpadu
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Install app
    .tooltiptext = Install this site as an app
ssb-page-action-title = Install app
ssb-app-open-button = 
    .label = Open In App
ssb-app-install-button = 
    .label = Install
ssb-app-cancel-button = 
    .label = Cancel
floorp-open-manage-ssb-page = 
    .label = Manage installed Web Apps
appmenuitem-webapps = 
    .label = Web Apps
appmenu-open-installed-apps-subheader = Open installed web apps
appmenuitem-install-current-page = 
    .label = Install this site as an app
appmenuitem-open-current-page = 
    .label = Open this site on installed app
appmenuitem-contextmenu-open-app = 
    .label = Open this app
appmenuitem-contextmenu-uninstall-app = 
    .label = Uninstall this app

## Preferences

category-ssb = 
    .label = Web Apps
    .tooltiptext = Web Apps
category-ssb-title = Web Apps
floorp-ssb-title = Web Apps
floorp-ssb-description = Web Apps are websites that can be installed as apps. They can be launched from { -brand-short-name }'s menu panel or the Windows Start menu.
ssb-preferences = Web Apps Settings
floorp-enable-ssb = 
    .label = Enable Web Apps
floorp-enable-ssb-with-experimental = 
    .label = Enable Web Apps (Experimental)
floorp-enable-ssb-description = This feature is experimental on Mac and Linux. It is recommended to enable this feature on Windows.
floorp-disable-toolbars = 
    .label = Disable toolbars on Web Apps Window
floorp-disable-toolbars-description = This setting will hide all extensions and toolbars on Web Apps Window.
ssb-installed-list-title = Installed Web Apps
ssb-uninstall-button = 
    .label = Uninstall
ssb-uninstall-title = Uninstall Web App
ssb-uninstall-message = Are you sure you want to uninstall this Web App from { -brand-short-name }?
ssb-uninstall-button = Uninstall
ssb-uninstall-cancel = Cancel
######################################################################### Download Notification ###############################################################
floorp-started-download = Download started
floorp-finished-download = Download finished
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } is up to date!
floorp-notificationContent-latest = { -brand-short-name } is up to date. You are using the latest version of { -brand-short-name }.
floorp-notificationTitle = New version of { -brand-short-name } is available!
floorp-notificationContent = Click to download the latest version.
