# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> é um dos navegadores domésticos desenvolvidos no Japão. Ele é baseado no Firefox e continua a operar sob <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, para melhorar a web. Quer ajudar? <label data-l10n-name="helpus-donateLink">Faça uma doação</label>
icon-creator = Criador de ícones <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> and <label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Uma lista de colaboradores e desenvolvedores do <label data-l10n-name="about-contributor"></label>
#################################################################### about:preferences ####################################################################

pane-design-title = Projetar
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = É necessário reiniciar para aplicar as alterações
tab-width = Largura mínima das abas
preferences-tabs-newtab-position = Posição do novo separador
open-new-tab-use-default = 
    .label = Abrir novas abas na posição padrão
open-new-tab-at-the-end = 
    .label = Abrir novas abas no final da barra de guias
open-new-tab-next-to-current = 
    .label = Abrir novas abas ao lado da aba atual
multirow-tabs-limit = 
    .label = Ativar limite de linha para abas multi-linhas
multirow-tabs-newtab = 
    .label = Coloque o botão "Abrir uma nova aba" no final da linha inferior de abas
multirow-tabs-value = Número de linhas quando as abas multi-linhas estão ativadas
enable-tab-sleep = 
    .label = Habilitar abas de dormir
tab-sleep-timeout-minutes-value = As abas durarão após ficar inativo por (minutos)
tab-sleep-settings-button = Configurações...
tab-sleep-settings-dialog-title = 
    .title = Configurações de abas adormecidas
tab-sleep-settings-dialog-excludehosts-label = Excluir hosts
tab-sleep-settings-dialog-excludehosts-label-2 = Insira um host por linha.
tab-sleep-tab-context-menu-excludetab = Manter o separador acordado
enable-tab-scroll-change = 
    .label = Alternar abas rolando com o mouse
enable-tab-scroll-reverse = 
    .label = Inverter a direção das abas de rolagem
enable-tab-scroll-wrap = 
    .label = Envolver as guias de rolagem na borda
enable-double-click-block = 
    .label = Fechar separadores com um duplo clique
enable-show-pinned-tabs-title = 
    .label = Exibir o título das abas fixadas
tabbar-preference = Barra de Abas
tab-normal-mode = 
    .label = Predefinição
hide-horizontality-tabs = 
    .label = Ocultar abas na barra de guia horizontal
verticalTab-setting = 
    .label = Otimizar navegador para a Barra de Abas Vertical
move-tabbar-position = 
    .label = Mostrar barra de guias abaixo da barra de ferramentas
tabbar-on-bottom = 
    .label = Exibir a Barra na parte inferior da janela
tabbar-favicon-color = 
    .label = Cor da barra de guias usando a cor do favicon do site atual
tabbar-style-preference = Tab Bar Style
horizontal-tabbar = 
    .label = Barra de Abas Horizontais
tabbar-style-description = É necessário reiniciar o { -brand-short-name } para aplicar totalmente esta configuração.
multirow-tabbar = 
    .label = Barra de Abas Multi-Linha
vertical-tabbar = 
    .label = Barra de Abas Verticais (experimental)
native-vertical-tab-show-right = 
    .label = Mostrar barra de guia vertical no lado direito da janela
native-vertical-tab-show-padding = 
    .label = Ativar o preenchimento no topo
hover-vertical-tab = 
    .label = Recolher a barra de separadores vertical
floorp-show-vertical-tab-newtab-button = 
    .label = Mostrar o botão "Abrir um novo separador" na barra de separadores vertical
floorp-show-vertical-tab-scrollbar = 
    .label = Mostrar deslocação na barra de separadores vertical
TST = Aba Estilo Árvore
about-TST = O Tree Style Tab é um complemento popular que lhe permite apresentar separadores numa estrutura semelhante a uma árvore. Este complemento já está pré-integrado em { -brand-short-name }. Instale o add-on para ativar o Tree Style Tab do { -brand-short-name }.
treestyletab-Settings = 
    .label = Recolher aba do estilo de árvore
sidebar-reverse-position-toolbar = Mostrar barras laterais do outro lado
bookmarks-bar-settings = Barra de Favoritos (apenas uma opção pode ser usada por vez)
bookmarks-focus-mode = 
    .label = Ocultar barra de favoritos a menos que pairando sobre a barra de navegação
bookmarks-bottom-mode = 
    .label = Mostrar a barra de favoritos na parte inferior do { -brand-short-name }
navbar-settings = Barra de navegação
show-nav-bar-bottom = 
    .label = Mostrar a barra de ferramentas na parte inferior do { -brand-short-name } (experimental)
disable-extension-check-compatibility-option = 
    .label = Não verificar a compatibilidade com add-ons (obsoleto)
other-preference = Outras Preferências
search-positon-top = 
    .label = Exibir a barra de pesquisa na parte superior da página
allow-auto-restart = 
    .label = Reiniciar automaticamente quando as configurações que requerem reinicialização forem alteradas
disable-fullscreen-notification = 
    .label = Não mostrar uma notificação ao entrar em tela cheia

## Browser Theme

system-color-settings = Alguns temas possuem modos claros e escuros - escolha qual modo você gostaria que esses temas usassem.
preferences-theme-appearance-header = Modo tema
system-theme-dark = 
    .label = Escuro
system-theme-light = 
    .label = Fino
system-theme-auto = 
    .label = Seguir a aparência do meu sistema

## User interface preferences

ui-preference = Aparência do navegador
preferences-browser-appearance-description = Escolha um design de terceiros embutido para usar no { -brand-short-name }. Alguns projetos podem não ser compatíveis com a sua configuração.
firefox-proton = 
    .label = Firefox Proton UI
firefox-photon-lepton = 
    .label = Firefox Photon➲ Lepton UI
floorp-fluentUI = 
    .label = Microsoft Fluent UI (obsoleto)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (Novo)

## Download Manager

download-notification-preferences = Baixar Notificações
start-always-notify = 
    .label = Notificar apenas ao iniciar downloads
finish-always-notify = 
    .label = Notificar apenas quando um download terminar
always-notify = 
    .label = Notificar quando iniciar downloads e quando um download terminar
do-not-notify = 
    .label = Desativar notificações de download

## Sidebar

profiles-button-label = Gerenciar perfis
floorp-help-button-label = Suporte { -brand-short-name }
appmenuitem-reboot = 
    .label = Reiniciar

## DMR UI

download-mgr-UI = 
    .label = Habilitar o Gerenciador de Download SimpleUI
downloading-red-color = 
    .label = Usar o ícone de downloads vermelhos quando baixar
sidebar-preferences = Sidebar
bsb-preferences = Configurações da barra lateral do navegador
view-sidebar2-right = 
    .label = Exibir a barra lateral Gerenciador de Navegadores à direita
enable-sidebar2 = 
    .label = Ativar a barra lateral Gerenciador de Navegadores
visible-bms = 
    .label = Mostrar a barra lateral Gerenciador de Navegadores
hide-bms-to-unload-panel = 
    .label = Descarregar painel quando esconder painel
enable-addons-in-sidebar2-with-experimental = 
    .label = Ativar Scripts de Conteúdo de Extensões na Barra Lateral do Browser Manager (experimental)
enable-addons-in-sidebar2 = 
    .label = Ativar Scripts de Conteúdo de Extensões na Barra Lateral do Browser Manager
sidebar2-enable-addons-desc = Se esta definição estiver ativada, as extensões de bloqueio de anúncios e outras extensões funcionarão na barra lateral. No entanto, nem todas as extensões funcionarão.
custom-URL-option = Definir URLs do Painel Web
set-custom-URL-button = 
    .label = Configurar URLs Personalizados...
    .accesskey = S.O.
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Barra lateral Gerenciador de Navegadores
bsb-context = Utilizar o seguinte contentor
bsb-userAgent-label = 
    .label = Use o Agente de Usuário Móvel neste Painel Web
bsb-width = Largura (se definida como 0, o valor global será usado)
bsb-page = Página a abrir
bsb-add = Adicionar Painel Web no Painel lateral Gerenciador de Navegadores
bsb-setting = Configurações do Web Panel
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = site
sidebar2-pref-delete = 
    .label = excluir
sidebar2-pref-setting = 
    .label = Confirgurações
sidebar2-global-width = Largura de painéis web globais
use-icon-provider-option = Utilizar o fornecedor de ícones
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = Parafugo
use-icon-provider-option-yandex = 
    .label = Yandex (disponível na China)
use-icon-provider-option-hatena = 
    .label = Hatena (disponível na China)
memory-and-performance = Memória e Desempenho
min-memory = 
    .label = Uso mínimo de memória (baixo desempenho)
balance-memory = 
    .label = Uso e desempenho de memória de saldo
max-memory = 
    .label = Melhor desempenho (utilização elevada de memória)
delete-border-and-roundup-option = 
    .label = Arredondar os cantos das páginas

## DualTheme

dualtheme-enable = 
    .label = Ativar Tema Duplo
newtab-background = { -brand-short-name } Fundo Home
newtab-background-random-image = 
    .label = Imagens aleatórias do Unsplash
newtab-background-gradation = 
    .label = Degradê
newtab-background-not-background = 
    .label = Desativar fundo
newtab-background-selected-image = 
    .label = Pasta personalizada...
newtab-background-selected-one-image = 
    .label = Imagem personalizada...
newtab-background-folder = Use imagens desta pasta:
newtab-background-image = Utilizar imagem :
newtab-choose-image = Selecionar imagem...
newtab-background-folder-reload = 
    .label = Reload images
newtab-background-folder-default = 
    .label = Restaurar Padrões
newtab-background-folder-open = 
    .label = Abrir pasta
newtab-background-folder-choose = Escolher pasta de imagens...
newtab-background-image-choose = Selecionar imagem...
newtab-background-extensions = Usar imagens com essas extensões de arquivo (separadas por ",")
disable-blur-on-newtab = 
    .label = Desativar o efeito de desfocagem em { -brand-short-name } Home
disable-releasenote-on-newtab = 
    .label = Desativar a nota de lançamento e as ligações de suporte na Casa { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Desativar o crédito de imagem (Unsplash) em { -brand-short-name } Página inicial

## Lepton Preferences

about-lepton = Personalize { -brand-short-name } com Lepton
lepton-preference-button = 
    .label = Configurações da Lepton...
    .accesskey = O
lepton-header = Configurações do Lepton
lepton-preference = Configurações do Lepton
photon-mode = 
    .label = Usar design de Photon
lepton-mode = 
    .label = Usar design Lepton
protonfix-mode = 
    .label = Usar projeto Proton ajustado
autohide-preference = Ocultar automaticamente elementos do navegador
floorp-lepton-enable-tab-autohide = 
    .label = Ocultar automaticamente as abas
floorp-lepton-enable-navbar-autohide = 
    .label = Ocultar barra de ferramentas automaticamente
floorp-lepton-enable-sidebar-autohide = 
    .label = Ocultar automaticamente a barra lateral
floorp-lepton-enable-urlbar-autohide = 
    .label = Ocultar automaticamente a Barra de Endereços
floorp-lepton-enable-back-button-autohide = 
    .label = Ocultar o botão voltar automaticamente
floorp-lepton-enable-forward-button-autohide = 
    .label = Ocultar automaticamente o botão para frente
floorp-lepton-enable-page-action-button-autohide = 
    .label = Ocultar os botões automaticamente na Barra de Endereços
floorp-lepton-enable-toolbar-overlap = 
    .label = Mostrar barra de ferramentas sobre o conteúdo do site
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Ocultar automaticamente a barra de ferramentas ao exibir conteúdo "ltr"
hide-preference = Gerenciar elementos de navegador
floorp-lepton-enable-tab_icon-hide = 
    .label = Ocultar ícones de separadores
floorp-lepton-enable-tabbar-hide = 
    .label = Barra de Abas Ocultar
floorp-lepton-enable-navbar-hide = 
    .label = Ocultar barra
floorp-lepton-enable-sidebar_header-hide = 
    .label = Ocultar cabeçalhos do painel lateral
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Ocultar ícones da barra de endereço
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Ocultar ícones da barra de favoritos
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Ocultar rótulos da barra de favoritos
floorp-lepton-enable-disabled_menu-hide = 
    .label = Ocultar itens do menu de contexto desabilitados
floorp-lepton-disable-userChrome-icon = 
    .label = Desativar o menu de contexto do Lepton e os ícones de menu do painel
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Habilitar os ícones do menu de contexto do Lepton
positon-preferences = Ajustes de posição
floorp-lepton-enable-centered-tab = 
    .label = Centralizar etiquetas em abas
floorp-lepton-enable-centered-urlbar = 
    .label = Texto do centro na Barra de Endereços
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Centralizar barra de favoritos
urlbar-preferences = Barra de endereços
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Mover ícones da barra de endereço para o lado esquerdo
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Ao escrever, mostrar um botão "Ir"
floorp-lepton-enable-always-show-page_action = 
    .label = Sempre mostrar ações da página na barra de endereços
tabbar-preferences = Barra de Abas
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Barra de separadores na barra de título
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Combinar barra de guias e barra de ferramentas
lepton-sidebar-preferences = Sidebar
floorp-lepton-enable-overlap-sidebar = 
    .label = Mostrar barra lateral sobre o conteúdo do site
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } Página Inicial (Padrão)
floorp-home-prefs-content-header = Conteúdo Inicial { -brand-short-name }
floorp-home-prefs-content-description = Escolha o conteúdo que deseja ver na Página Inicial { -brand-short-name }.

## Notes

floorp-notes = Notas { -brand-short-name }
restore-from-backup = Restaurar Notas do backup
enable-notes-sync = 
    .label = Habilitar sincronização de notas do { -brand-short-name }
about-notes-backup-tips = { -brand-short-name } O Notes utiliza o Firefox Sync para sincronizar as suas notas com outros dispositivos. Se perder as suas notas, pode restaurá-las a partir de uma cópia de segurança. É criada uma cópia de segurança quando inicia { -brand-short-name }.
notes-sync-description = Isso pode resolver o problema de perda de conteúdo devido a sobrescrever notas durante a sincronização.
backuped-time = Backup efetuado em
notes-backup-option = Configurações de backup
backup-option-button = Configurações de backup...
restore-from-backup-prompt-title = { -brand-short-name } Serviço de restauro de notas
restore-from-this-backup = Restaurar as Anotações de volta ao estado em que estão neste backup?
restore-button = RESTAURAR

## user.js

header-userjs = user.js
userjs-customize = Personalizar { -brand-short-name } com user.js
about-userjs-customize = user.js é um arquivo de configuração que lhe permite personalizar o { -brand-short-name }. Os arquivos user.js são baixados da Internet e sobrescrevem seu usuário atual. Arquivo s. Por favor, faça o backup do seu arquivo user.js atual antes de continuar. As configurações user.js serão aplicadas automaticamente depois de reiniciar o { -brand-short-name }.
userjs-label = lista user.js
userjs-prompt = Aplicar este user.js?
apply-userjs-attention = A aplicação de um novo user.js irá substituir o seu arquivo user.js atual.
apply-userjs-attention2 = Por favor, faça um backup do seu arquivo user.js atual antes de continuar.
userjs-button = configurações do user.js...
userjs-select-option = Gerencie os user.js atualmente usados no { -brand-short-name } para melhorar o desempenho e a privacidade.
apply-userjs-button = Aplicar

## userjs Options

default-userjs-label = { -brand-short-name } Predefinição
about-default-userjs = Telemetria desativada. { -brand-short-name } bem equilibrado com várias personalizações ativadas.
Securefox-label = Fofox Seguro Assombrado
about-Securefox = HTTPS-by-Default. Proteção total de Cookie com isolamento do site. Estado melhorado e partição de rede. Várias outras melhorias.
default-label = Yokoffing Default
about-default = Tudo o que é essencial. Nenhuma das quebras. Este é seu user.js.
Fastfox-label = Fastfox Ajoelhado
about-Fastfox = Aumenta imediatamente a velocidade de navegação do Firefox. Dê ao Chrome uma corrida para o dinheiro!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Liberar a página de novas abas. Remover o Pocket. Restaurar o modo compacto como opção. Parar notificações de página web, pop-ups e outros incômodos.
Smoothfox-label = Fumaça Atordoante
about-Smoothfox = Obtenha uma rolagem suave no seu navegador favorito — ou escolha algo mais seu estilo.
select-workspace = Selecionar Projeto
workspace-select-icon = Ícone do Área de Trabalho
    .label = Ícone do Área de Trabalho
workspace-select-container = Selecionar aba de contêiner
    .label = Selecionar aba de contêiner
workspace-customize = 
    .title = Personalizar Área de Trabalho
floorp-no-workspace-container = 
    .label = Nenhum contentor
workspace-icon-article = 
    .label = Artigo
workspace-icon-book = 
    .label = Livro
workspace-icon-briefcase = 
    .label = Trabalho
workspace-icon-cart = 
    .label = Compras
workspace-icon-chat = 
    .label = Conversa
workspace-icon-chill = 
    .label = Privado
workspace-icon-circle = 
    .label = Círculo
workspace-icon-compass = 
    .label = Bússola
workspace-icon-code = 
    .label = Código
workspace-icon-dollar = 
    .label = Banco
workspace-icon-fence = 
    .label = Cerca
workspace-icon-fingerprint = 
    .label = pessoal
workspace-icon-food = 
    .label = Alimentação
workspace-icon-fruit = 
    .label = Frutas
workspace-icon-game = 
    .label = Jogo
workspace-icon-gear = 
    .label = Engrenagem
workspace-icon-gift = 
    .label = Presente
workspace-icon-key = 
    .label = Chave
workspace-icon-lightning = 
    .label = Relâmpago
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notas
workspace-icon-paint = 
    .label = Pintar
workspace-icon-photo = 
    .label = Fotografia
workspace-icon-pin = 
    .label = Afixar
workspace-icon-pet = 
    .label = Animal
workspace-icon-question = 
    .label = Questão
workspace-icon-smartphone = 
    .label = Smartphone
workspace-icon-star = 
    .label = Estrela
workspace-icon-tree = 
    .label = Árvore
workspace-icon-vacation = 
    .label = Férias
workspace-icon-love = 
    .label = Amor
workspace-icon-moon = 
    .label = Lua
workspace-icon-music = 
    .label = Música
workspace-icon-user = 
    .label = Utilizador
# Custom Keyboard Shortcuts
floorp-CSK-title = Atalhos de teclado personalizados
floorp-CSK-description = Personalize os atalhos de teclado do { -brand-short-name }. O { -brand-short-name } fornece mais de 80 atalhos de teclado personalizáveis! Atalhos de teclado duplicados não funcionarão. Reinicie o { -brand-short-name } para aplicar essas configurações.
disable-fx-actions = 
    .label = Desativar atalhos de teclado do Mozilla Firefox
customize-Action = 
    .label = Adicionar atalho
remove-Action = 
    .label = Remover atalho
CSK-reset-title = Redefinir atalhos de teclado personalizados
CSK-reset-description = Redefinir atalhos de teclado personalizados para os padrões de { -brand-short-name }.
CSK-reset-label = Redefinir atalhos de teclado personalizados
CSK-reset-button = Restaurar Padrões
CSK-manage-title = Gerenciar atalhos de teclado
CSK-remove-shortcutkey = Remover atalho de teclado personalizado?
CSK-remove-shortcutkey-description = Tem certeza de que deseja remover este atalho de teclado?
CSK-restore-default = Restaurar padrões?
CSK-restore-default-description = Restaurar os atalhos de teclado predefinidos do { -brand-short-name }? Os seus atalhos atuais serão perdidos.
CSK-reboot-browser-label = Reinicie o { -brand-short-name } para aplicar estas configurações
CSK-reboot-browser-button = Reiniciar o { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Atalho para teclado atual: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Atalho de teclado atual: { $key }.
CSK-keyborad-shortcut-is-changed = (Não aplicado)
floorp-custom-actions-tab-action = Ações da Aba
floorp-custom-actions-page-action = Ações de Página
floorp-custom-actions-visible-action = Ações visíveis
floorp-custom-actions-search-action = Procurar ações
floorp-custom-actions-tools-action = Ações de Ferramentas
floorp-custom-actions-bookmark-action = Ações para favoritos
floorp-custom-actions-open-page-action = Abrir Ações da Página
floorp-custom-actions-history-action = Ações do Histórico
floorp-custom-actions-pip-action = Ações Picture-in-Picture
floorp-custom-actions-downloads-action = Ações de Downloads
floorp-custom-actions-sidebar-action = Ações do painel lateral
floorp-custom-actions-bms-action = Ações da barra lateral do navegador
floorp-custom-actions-split-view-action = Ações de vista dividida
floorp-custom-actions-workspaces-action = Ações do Espaços de Trabalho
floorp-custom-actions-custom-action = Ações personalizadas (Experimental)

## Mouse Gestures

mouse-gesture = Gestos do Mouse
mouse-gesture-description = Gesturefy deve ser instalado para usar gestos do mouse com { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = O Gesturefy é uma extensão que adiciona gestos do rato ao seu navegador. Se o { -brand-short-name } detetar a instalação deste add-on, irá adicionar comandos de gestos ao Gesturefy que só estão disponíveis em { -brand-short-name }. Este add-on também cria separadores!
# Translate
TWS = Translate Web Page
about-TWS = Traduza sua página em tempo real usando Google ou Yandex. Você também pode traduzir o texto selecionado ou a página inteira.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Centro de Privacidade
block-more-tracker = Bloquear mais anúncios e rastreadores
block-tracker = Esta seção contém um conjunto de extensões projetadas para bloquear anúncios e rastreadores
view-at-AMO = Veja este addon em addons.mozilla.org
uBlock-Origin = Origem do uBlock
about-uboori = O uBlock Origin bloqueia anúncios, rastreadores extensivos e sites perigosos adicionais.
Facebook-Container = Container do Facebook
about-Facebook-Container = Evite que o Facebook o rastreie através da web. A extensão do Container do Facebook ajuda você a assumir controle e isolar suas atividades da web do Facebook.

## Fingerprinting

fingerprint-header = Resistir Fingerprinting e endereços IP vazados
block-fingerprint = A impressão digital é um mecanismo de rastreamento que depende das características únicas do seu navegador e do seu sistema operacional. Esta seção contém configurações para melhorar ainda mais esta proteção além do bloqueio padrão.
enable-firefox-fingerprint-protections = Ativar uma forte proteção contra impressão digital
about-firefox-fingerprint-protection = Habilitar a proteção pelo Firefox inclui o modo de luz forçada, desabilitando algumas APIs, etc. Alguns sites podem estar quebrados.
fingerprint-Protection = 
    .label = Proteção anti-impressão digital
html5-canvas-prompt-settings = 
    .label = Automaticamente dispensar solicitações de confirmação de acesso para dados de imagens HTML5
canvas-prompt = Impede que sites usem o aviso de leitura em tela, a menos que seja permitido manualmente.
disable-webgl = 
    .label = Desabilitar WebGL
about-webgl = WebGL é uma API Javascript usada para renderizar gráficos, que pode ser usada para identificar GPU.
Canvas-Blocker = Bloqueador de Tela
about-CB = Este complemento oculta dados usados por técnicas de impressão digital.
WebRTC-connection = WebRTC é um padrão que fornece chamadas em tempo real. Se você desativar essa configuração, você não poderá usar o Discord, etc.
WebRTC = 
    .label = Ativar Conexão WebRTC
################################################################### browser ###############################################################

rest-mode = Fazendo uma pausa...
rest-mode-description = { -brand-short-name } está atualmente suspenso. Prima ENTER ou OK para continuar.
Sidebar2 = 
    .label = Barra lateral Gerenciador de Navegadores
    .tooltiptext = Alterar visibilidade da barra lateral
sidebar2-mute-and-unmute = 
    .label = Silenciar/Reativar este Painel
sidebar2-unload-panel = 
    .label = Descarregar este painel
sidebar2-change-ua-panel = 
    .label = Alternar agente de usuário móvel
sidebar2-delete-panel = 
    .label = Excluir este painel
sidebar2-change-zoom-level = 
    .label = Alterar o nível de zoom
sidebar2-zoom-in = 
    .label = Ampliar
sidebar2-zoom-out = 
    .label = Reduzir
sidebar2-reset-zoom = 
    .label = Redefinir Zoom
sidebar2-close-button = 
    .tooltiptext = Fechar barra lateral
sidebar-back-button = 
    .tooltiptext = Anterior
sidebar-forward-button = 
    .tooltiptext = Encaminhar
sidebar-reload-button = 
    .tooltiptext = Reload
sidebar-go-index-button = 
    .tooltiptext = Ir para casa
sidebar-muteAndUnmute-button = 
    .tooltiptext = Mute/Unmute sidebar
sidebar2-browser-manager-sidebar = Gerenciador de Navegadores
show-browser-manager-sidebar = 
    .tooltiptext = Show { sidebar2-browser-manager-sidebar } Sidebar
sidebar2-bookmark-sidebar = Favoritos
show-bookmark-sidebar = 
    .tooltiptext = Show { sidebar2-bookmark-sidebar } Sidebar
sidebar2-history-sidebar = Histórico
show-history-sidebar = 
    .tooltiptext = Show { sidebar2-history-sidebar } Sidebar
sidebar2-download-sidebar = Downloads
show-download-sidebar = 
    .tooltiptext = Show { sidebar2-download-sidebar } Sidebar
sidebar2-notes-sidebar = Observações
show-notes-sidebar = 
    .tooltiptext = Show { sidebar2-notes-sidebar } Sidebar
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Complementos e temas
sidebar2-hide-sidebar-button = 
    .tooltiptext = Ocultar a barra lateral do Browser Manager
sidebar-passwords-button = 
    .tooltiptext = Senhas
sidebar-preferences-button = 
    .tooltiptext = Confirgurações
sidebar-keepWidth-button = 
    .tooltiptext = Continue usando a largura atual neste Painel
sidebar2-keep-width-for-global = 
    .label = Aplicar esta largura a todos os painéis sem largura personalizada
bsb-context-add = 
    .label = Adicionar página ao Painel Web...
bsb-context-link-add = 
    .label = Adicionar link ao Painel de Web...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Abrir diretório de perfil
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Reconstruir arquivos CSS do navegador
    .accesskey = R
make-browsercss-file = 
    .label = Criar arquivo CSS do navegador
    .accesskey = MM
open-css-folder = 
    .label = Abrir pasta CSS
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Editar arquivo userChrome.css
edit-userContentCss-editor = 
    .label = Editar arquivo userContent.css
not-found-editor-path = Não foi possível encontrar um editor de arquivo CSS
set-pref-description = Insira a localização do arquivo do editor de arquivo CSS que você deseja usar:
rebuild-complete = A reconstrução foi concluída.
please-enter-filename = Por favor, insira um nome de arquivo.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Reabrir aba fechada
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Habilitar como sub-tema
dual-theme-disable-addon-button = Desativar sub-tema
dual-theme-enabled-heading = Habilitado como sub-tema
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Barra de status
    .accesskey = S.O.
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Abrir o painel do separador estilo de árvore
gf-floorp-open-tree-style-tab-description = Abrir o painel do separador Estilo de Árvore na barra lateral
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Abrir o painel de favoritos
gf-floorp-open-bookmarks-sidebar-description = Abrir o painel de favoritos na barra lateral
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Abrir o painel do historial
gf-floorp-open-history-sidebar-description = Abrir o painel Histórico na barra lateral
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Abrir o painel de separadores sincronizados
gf-floorp-open-synctabs-sidebar-description = Abrir o painel Separadores sincronizados na barra lateral
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Fechar barra lateral
gf-floorp-close-sidebar-description = Fechar barra lateral
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Abrir BMS
gf-floorp-open-browser-manager-sidebar-description = Abrir a barra lateral do Browser Manager se o painel Web da barra lateral do Browser Manager estiver carregado
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Fechar BMS
gf-floorp-close-browser-manager-sidebar-description = Fechar barra lateral Gerenciador de Navegadores
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Alternar BMS
gf-floorp-show-browser-manager-sidebar-description = Alternar barra lateral Gerenciador de Navegadores
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Ocultar a barra de estado
gf-floorp-hide-statusbar-description = Ocultar barra de status
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Alternar a barra de estado
gf-floorp-show-statusbar-description = Exibir ou ocultar barra de status
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Abrir barra lateral de extensões selecionada
gf-floorp-open-extension-sidebar-description = Abrir extensão selecionada na barra lateral
gf-floorp-open-extension-sidebar-settings-addons-id = Complemento da barra lateral
gf-floorp-open-extension-sidebar-settings-addons-id-description = A extensão do complemento aberto na barra lateral
gf-floorp-open-extension-sidebar-settings-list-default = Selecione o complemento
gf-floorp-open-extension-sidebar-settings-list-unknwon = Extensão desconhecida
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Atualizações encontradas!
update-portable-notification-found-message = Baixando atualizações...
update-portable-notification-ready-title = Pronto para atualizar!
update-portable-notification-ready-message = { -brand-short-name } será atualizado no próximo lançamento.
update-portable-notification-success-title = Atualização bem-sucedida!
update-portable-notification-success-message = A atualização foi bem sucedida! Espero que gostem da nova versão do { -brand-short-name }!
update-portable-notification-failed-title = Falha na atualização.
update-portable-notification-failed-redirector-message = Falha na atualização. Reiniciar seu navegador pode resolver este problema.
update-portable-notification-failed-prepare-message = Falha ao preparar a atualização.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = Atualização Portátil { -brand-short-name }
floorp-update-application-auto-enabled-option = 
    .label = Verificar automaticamente atualizações para o portátil { -brand-short-name } . (Recomendado)
##################################################################### Open link in external ###############################################################
openInExternal-title = Abrir no navegador externo
open-link-in-external-enabled-option = 
    .label = Ativar o recurso "Abrir em navegador externo"
open-link-in-external-select-browser-option = Escolha qual navegador será aberto
open-link-in-external-select-browser-option-default = 
    .label = Navegador padrão
open-link-in-external-tab-context-menu = Abrir no navegador externo
open-link-in-external-tab-dialog-title-error = Ocorreu um erro:
open-link-in-external-tab-dialog-message-default-browser-not-found = O navegador padrão não foi encontrado ou não está configurado.
open-link-in-external-tab-dialog-message-selected-browser-not-found = O navegador selecionado não existe.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Novidades
memo-title-input-placeholder = Escreva um título aqui
memo-input-placeholder = Escreva ou cole um memorando aqui
delete-memo = excluir
save-memo = Guardar
memo-welcome-title = Bem-vindo!
memo-first-tip = Bem-vindo ao { -brand-short-name } Notes! Aqui estão algumas instruções sobre como o utilizar!
memo-second-tip = { -brand-short-name } O Notes é um bloco de notas que lhe permite armazenar várias notas sincronizadas entre dispositivos. Para ativar a sincronização, é necessário iniciar sessão em { -brand-short-name } com a sua conta Firefox.
memo-third-tip = { -brand-short-name } As notas serão guardadas nas suas definições de { -brand-short-name } e sincronizadas entre dispositivos utilizando o Firefox Sync. O Firefox Sync encripta o conteúdo da sincronização com a palavra-passe da sua conta Firefox, para que ninguém além de si conheça o seu conteúdo.
memo-import-data-tip = Firefox Sync não é um serviço de backup. Nós recomendamos que você crie backups.
memo-new-title = Nova anotação
chage-view-mode = Alternar Modo de Visualização/Edição
readonly-mode = Offline (Somente Leitura)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Suporte ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Limpar Downloads
    .accesskey = D
    .tooltiptext = Limpar Downloads
floorp-show-all-downloads = 
    .label = Mostrar todos os downloads
    .accesskey = S.O.
    .tooltiptext = Mostrar todos os downloads
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Criar um novo espaço de trabalho...
    .tooltiptext = Criar um novo espaço de trabalho
workspaces-manage-workspaces-button = 
    .label = Gerir espaços de trabalho...
    .tooltiptext = Gerir os seus espaços de trabalho
reorder-this-workspace-to-up = 
    .label = Mover para cima este espaço de trabalho
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Mover para baixo este espaço de trabalho
    .accesskey = A
rename-this-workspace = 
    .label = Renomear espaço de trabalho
    .accesskey = R
delete-this-workspace = 
    .label = Eliminar espaço de trabalho
    .accesskey = D
manage-this-workspaces = 
    .label = Gerir espaços de trabalho...
    .accesskey = M
workspace-new-default-name = Novo espaço de trabalho
workspace-default-name = Predefinição
move-tab-another-workspace = 
    .label = Mover para outro Espaço
rename-workspace-prompt-title = Renomear espaço de trabalho
rename-workspace-prompt-text = Introduzir o nome do espaço de trabalho. Pode ser utilizada a maioria dos caracteres e símbolos.
workspaces-toolbar-button = Espaços de trabalho
    .label = Espaços de trabalho
    .tooltiptext = Selecionar um espaço de trabalho...

## Preferences

enable-workspaces = 
    .label = Ativar espaços de trabalho
    .tooltiptext = Ativar espaços de trabalho
workspace-notice = Os espaços de trabalho não funcionarão com estas definições ativadas, a menos que o botão dos espaços de trabalho seja colocado na barra de ferramentas. Utilize esta definição se pretender desativar completamente os Espaços de trabalho.
enable-workspaces-with-experimental = 
    .label = Ativar espaços de trabalho (Experimental)
    .tooltiptext = Ativar espaços de trabalho (Experimental)
workspace-warning = Os espaços de trabalho não podem ser utilizados com os suplementos do Grupo de separadores. Se pretender utilizar os suplementos do Grupo de separadores, desative os Espaços de trabalho e reinicie { -brand-short-name }.
category-workspaces = 
    .label = Espaços de trabalho
    .tooltiptext = Espaços de trabalho
pane-workspaces-title = Espaços de trabalho
floorp-workspaces-title = { -brand-short-name } Workspace
floorp-workspace-settings-button = Configurações do workspace...
floorp-preferences-label = Preferências
floorp-extensions-label = Extensões
floorp-private-label = Privado
change-to-close-workspace-popup-option = 
    .label = Fechar o pop-up Espaços de trabalho ao selecionar um espaço de trabalho
manage-workspace-on-bms-option = 
    .label = Gerenciar Área de Trabalho na Barra lateral Gerenciador de Navegadores
show-workspace-name-option = 
    .label = Mostrar nome da Área de Trabalho no botão Tab da Barra de Trabalho
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Modo de Compartilhamento
    .accesskey = S.O.
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Entre em sua conta do Firefox
welcome-to-floorp = Bem-vindo a { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } é um navegador flexível e rico em funcionalidades que suporta vários ambientes e baseado no Firefox.
welcome-start-setup = Pronto para mergulhar?
welcome-skip-to-start-browsing = Pular para iniciar a navegação
welcome-select-preferences-template = Selecionar um modelo
welcome-minimum-template = Básico
welcome-enable-basic-features = Ativar as funcionalidades e definições básicas para uma experiência simples.
welcome-medium-template = Padrão
welcome-enable-some-features = Ativar funcionalidades e definições adicionais para uma melhor experiência.
welcome-maximum-template = Avançado
welcome-enable-most-of-features = Ativar funcionalidades e definições avançadas. Recomendado para utilizadores experientes.
welcome-go-next-setup = Próximo
welcome-select-browser-design = Selecione um Design de Navegador
welcome-describe-browser-design = Pode escolher um dos maravilhosos designs de terceiros { -brand-short-name } . Os desenhos específicos do SO também estão disponíveis nas Preferências.
welcome-design-lepton-name = Design original Lepton
welcome-design-photon-name = Design Lepton Photon
welcome-design-ProtonFix-name = ProtonFix Design Lepton
welcome-design-floorp-fluerial-name = Design { -brand-short-name } de Fluerial
welcome-design-firefox-proton-name = Projeto Proton do Firefox
welcome-import-data = Importar Dados do Seu Navegador
welcome-import-data-description = Configuração rápida! Importe os seus favoritos, palavras-passe e muito mais do seu antigo navegador. Os utilizadores do Firefox podem importar dados do Firefox Sync.
welcome-import-data-button = Importar dados...
welcome-import-data-skip = Pular importação
welcome-select-button = Selecionar
welcome-finish-setup = Configuração concluída!
welcome-finish-setup-description = Está tudo pronto! Outras funcionalidades, como separadores verticais e espaços de trabalho, podem ser encontradas nas opções de { -brand-short-name }. Desfrute de { -brand-short-name }!
welcomet-finish-setup = Comece a navegar na web
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Atalhos de teclado
    .tooltiptext = Atalhos de teclado
category-CSK-title = Atalhos de teclado
shortcutkey-customize = 
    .title = Atalhos de teclado
select-shortcutkeyAction = Selecione uma ação para acionar
shortcutkey-customize-key-list-placeholder = Seu atalho de teclado aparecerá aqui
shortcut-key-label = Atalho de teclado
start-input-button-listen = Começar a ouvir
end-input-button-listen = Parar de ouvir
shortcut-key-description = Clique em "Começar a ouvir" e introduza o seu novo atalho de teclado para esta ação. Podem ser utilizadas várias teclas; no entanto, os atalhos de teclado não funcionarão se já estiverem atribuídos a outras ações.
floorp-custom-actions-open-new-tab = Abrir uma aba
    .label = Abrir uma aba
floorp-custom-actions-close-tab = Fechar a aba atual
    .label = Fechar a aba atual
floorp-custom-actions-open-new-window = Abrir uma nova janela
    .label = Abrir uma nova janela
floorp-custom-actions-open-new-private-window = Abrir uma nova janela privativa
    .label = Abrir uma nova janela privativa
floorp-custom-actions-close-window = Fechar a janela atual
    .label = Fechar a janela atual
floorp-custom-actions-restore-last-session = Restaurar a última sessão
    .label = Restaurar a última sessão
floorp-custom-actions-restore-last-window = Restaurar a última janela
    .label = Restaurar a última janela
floorp-custom-actions-show-next-tab = Mostrar a próxima aba
    .label = Mostrar a próxima aba
floorp-custom-actions-show-previous-tab = Mostrar aba anterior
    .label = Mostrar aba anterior
floorp-custom-actions-show-all-tabs-panel = Mostrar painel de todas as abas
    .label = Mostrar a lista de abas
floorp-custom-actions-send-with-mail = Enviar com e-mail
    .label = Enviar via e-mail
floorp-custom-actions-save-page = Salvar página
    .label = Salvar página
floorp-custom-actions-print-page = Print page
    .label = Print page
floorp-custom-actions-mute-current-tab = Ativar/desativar som da guia atual
    .label = Ativar/desativar som da guia atual
floorp-custom-actions-toggle-bookmark-toolbar = Alternar a barra de ferramentas dos marcadores
    .label = Alternar barra de favoritos
floorp-custom-actions-show-source-of-page = Mostrar fonte da página
    .label = Abrir código da página
floorp-custom-actions-show-page-info = Mostrar informações da página
    .label = Abrir Informações da Página
floorp-custom-actions-zoom-in = Aumentar zoom
    .label = Aumentar zoom
floorp-custom-actions-zoom-out = Diminuir zoom
    .label = Diminuir zoom
floorp-custom-actions-reset-zoom = Reset zoom
    .label = Reset zoom
floorp-custom-actions-back = Anterior
    .label = Anterior
floorp-custom-actions-forward = Encaminhar
    .label = Encaminhar
floorp-custom-actions-reload = Reload
    .label = Reload
floorp-custom-actions-stop = Interromper
    .label = Interromper
floorp-custom-actions-force-reload = Forçar recarregamento
    .label = Forçar recarregamento
floorp-custom-actions-search-in-this-page = Pesquisar nesta página
    .label = Localizar na página
floorp-custom-actions-show-next-search-result = Mostrar próxima palavra de busca no resultado desta página
    .label = Próximo resultado "Localizar na página"
floorp-custom-actions-show-previous-search-result = Mostrar palavra de busca anterior no resultado desta página
    .label = Resultado anterior "Localizar na página"
floorp-custom-actions-search-the-web = Pesquisar na web
    .label = Pesquisar na web
floorp-custom-actions-open-migration-wizard = Abrir assistente de migração
    .label = Abrir assistente de migração
floorp-custom-actions-quit-from-application = Sair do aplicativo
    .label = Sair de { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Personalizar a barra de ferramentas
    .label = Abrir Personalizar { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Entrar no modo sem rede
    .label = Entrar no modo offline
floorp-custom-actions-open-screen-capture = Abrir ferramenta de captura de tela
    .label = Capturar tela
floorp-custom-actions-show-pip = Mostrar imagem na imagem
    .label = Mostrar Picture-in-Picture
floorp-custom-actions-bookmark-this-page = Adicionar aos favoritos
    .label = Adicionar aos favoritos
floorp-custom-actions-open-bookmarks-sidebar = Abrir barra lateral de favoritos
    .label = Abrir barra lateral de favoritos
floorp-custom-actions-open-bookmark-add-tool = Adicionar aos favoritos ferramenta
    .label = Adicionar aos favoritos
floorp-custom-actions-open-bookmark-add-toolbar = Abrir a janela pop-up "Adicionar um novo marcador"
    .label = Adicionar à Barra de Favoritos
floorp-custom-actions-open-bookmarks-manager = Abrir gerenciador de favoritos
    .label = Abrir Gerenciador de Favoritos
floorp-custom-actions-show-bookmark-toolbar = Alternar barra de favoritos
    .label = Alternar barra de favoritos
floorp-custom-actions-open-general-preferences = Abrir preferências gerais
    .label = Abrir preferências gerais
floorp-custom-actions-open-privacy-preferences = Abrir preferências de privacidade
    .label = Abrir Preferências De Privacidade
floorp-custom-actions-open-workspaces-preferences = Preferências de espaços de trabalho abertos
    .label = Preferências do Open Workspace
floorp-custom-actions-open-containers-preferences = Abrir preferências de contêineres
    .label = Abrir Preferências de Contêineres
floorp-custom-actions-open-search-preferences = Abrir preferências de pesquisa
    .label = Abrir preferências de pesquisa
floorp-custom-actions-open-sync-preferences = Abrir preferências de sincronização
    .label = Abrir preferências Sync
floorp-custom-actions-open-task-manager = Abrir gerenciador de tarefas
    .label = Abrir { -brand-short-name }Gerenciador de Tarefas
floorp-custom-actions-open-home-page = Abrir página inicial do { -brand-short-name }
    .label = Abrir página do { -brand-short-name }
floorp-custom-actions-open-addons-manager = Abrir extensões e temas
    .label = Complementos e temas abertos
floorp-custom-actions-forget-history = Esquecer o histórico
    .label = Esquecer o histórico
floorp-custom-actions-quick-forget-history = Histórico de esquecimentos rápidos
    .label = Histórico de esquecimentos rápidos
floorp-custom-actions-clear-recent-history = Limpar histórico recente
    .label = Limpar histórico recente
floorp-custom-actions-search-history = Histórico de busca
    .label = Histórico de busca
floorp-custom-actions-manage-history = Gerenciar Histórico
    .label = Gerenciar Histórico
floorp-custom-actions-open-downloads = Abrir downloads
    .label = Abrir Downloads
floorp-custom-actions-show-bms = Alternar a barra lateral do gestor do navegador
    .label = Alternar a barra lateral do Browser Manager
floorp-custom-actions-show-current-panel = Alternar o painel atual
    .label = Alternar o painel atual
floorp-custom-actions-show-bookmark-sidebar = Exibir barra lateral de favoritos
    .label = Exibir barra lateral de favoritos
floorp-custom-actions-show-history-sidebar = Show history sidebar
    .label = Show History Sidebar
floorp-custom-actions-show-synced-tabs-sidebar = Show synced tabs sidebar
    .label = Show Synced Tabs Sidebar
floorp-custom-actions-reverse-sidebar = Posição da barra lateral inversa
    .label = Posição da barra lateral inversa
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = Ativar/Desativar barra lateral
    .label = Ativar/Desativar barra lateral
floorp-custom-actions-toggle-sidebar = Alternar a barra lateral
    .label = Alternar a barra lateral
floorp-custom-actions-open-previous-workspace = Abrir o espaço de trabalho anterior
    .label = Abrir o espaço de trabalho anterior
floorp-custom-actions-open-next-workspace = Abrir o próximo espaço de trabalho
    .label = Abrir o próximo espaço de trabalho
floorp-custom-actions-show-panel-1 = Alternar painel 1
    .label = Alternar painel 1
floorp-custom-actions-show-panel-2 = Alternar painel 2
    .label = Alternar painel 2
floorp-custom-actions-show-panel-3 = Alternar painel 3
    .label = Alternar painel 3
floorp-custom-actions-show-panel-4 = Alternar painel 4
    .label = Alternar painel 4
floorp-custom-actions-show-panel-5 = Alternar painel 5
    .label = Alternar painel 5
floorp-custom-actions-show-panel-6 = Alternar painel 6
    .label = Alternar painel 6
floorp-custom-actions-show-panel-7 = Alternar painel 7
    .label = Alternar painel 7
floorp-custom-actions-show-panel-8 = Alternar painel 8
    .label = Alternar painel 8
floorp-custom-actions-show-panel-9 = Alternar painel 9
    .label = Alternar painel 9
floorp-custom-actions-show-panel-10 = Alternar painel 10
    .label = Alternar painel 10
floorp-custom-actions-open-split-view-on-left = Abrir o separador atual à esquerda na vista dividida
    .label = Abrir o separador atual à esquerda na vista dividida
floorp-custom-actions-open-split-view-on-right = Abrir o separador atual à direita na vista dividida
    .label = Abrir o separador atual à direita na vista dividida
floorp-custom-actions-close-split-view = Fechar vista dividida
    .label = Fechar vista dividida
floorp-custom-actions-custom-action-1 = Ação personalizada 1
    .label = Ação personalizada 1
floorp-custom-actions-custom-action-2 = Ação personalizada 2
    .label = Ação personalizada 2
floorp-custom-actions-custom-action-3 = Ação personalizada 3
    .label = Ação personalizada 3
floorp-custom-actions-custom-action-4 = Ação personalizada 4
    .label = Ação personalizada 4
floorp-custom-actions-custom-action-5 = Ação personalizada 5
    .label = Ação personalizada 5
floorp-custom-actions-rest-mode = Ativar o modo de repouso
    .label = Ativar o modo de repouso
floorp-custom-actions-hide-user-interface = Alternar a “interface” do utilizador
    .label = Alternar a “interface” do utilizador
floorp-custom-actions-toggle-navigation-panel = Alternar painel de navegação
    .label = Alternar painel de navegação
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Lançamento
    .tooltiptext = Inicie { -brand-short-name } com este perfil
floorp-profiles-in-use = Este perfil está em uso.
floorp-profiles-title = Profiles
floorp-profile-manager = Gerenciador de perfis
floorp-profiles-create = Criar Perfil
floorp-profile = Perfil
    .label = Gerenciador de perfis
    .tooltiptext = Abrir Gerenciador de Perfis
fxa-not-signed-in = Sem sessão iniciada
###################################################################### Private Container ##############################################################
floorp-private-container-name = Privado
floorp-toggle-private-container = 
    .label = Reabrir em Privado/Nenhum Contêiner
    .accesskey = PT
open-in_private-container = 
    .label = Abrir em Nova Aba com Recipiente Privado
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Abrir na vista dividida
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Remove Split View
split-view-title = Split View Settings
split-view-position = Position
split-view-flex-type = Flex Type
split-view-position-top = Top Side
split-view-position-left = Default
split-view-position-right = Reverse
split-view-flex-column = Vertical
split-view-flex-row = Horizontal
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Escaneie o Código QR com seu Telefone
qrcode-generate-page-action = 
    .tooltiptext = Compartilhe esta página com seu telefone
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Botão de Extensões Unificadas
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Instalar aplicação
    .tooltiptext = Instalar este sítio como uma aplicação
ssb-page-action-title = Instalar a aplicação
ssb-app-open-button = 
    .label = Abrir na aplicação
ssb-app-install-button = 
    .label = Instalar
ssb-app-cancel-button = 
    .label = Cancelar
floorp-open-manage-ssb-page = 
    .label = Gerir as aplicações Web instaladas
appmenuitem-webapps = 
    .label = Aplicações Web
appmenu-open-installed-apps-subheader = Abrir aplicações web instaladas
appmenuitem-install-current-page = 
    .label = Instalar este sítio como uma aplicação
appmenuitem-open-current-page = 
    .label = Abrir este sítio na aplicação instalada
appmenuitem-contextmenu-open-app = 
    .label = Abrir esta aplicação
appmenuitem-contextmenu-uninstall-app = 
    .label = Desinstalar esta aplicação

## Preferences

category-ssb = 
    .label = Aplicações Web
    .tooltiptext = Aplicações Web
category-ssb-title = Aplicações Web
floorp-ssb-title = Aplicações Web
floorp-ssb-description = As aplicações Web são sítios Web que podem ser instalados como aplicações. Podem ser iniciadas a partir do painel de menus do { -brand-short-name } ou do menu Iniciar do Windows.
ssb-preferences = Definições das aplicações Web
floorp-enable-ssb = 
    .label = Ativar as aplicações Web
floorp-enable-ssb-with-experimental = 
    .label = Ativar as aplicações Web (Experimental)
floorp-enable-ssb-description = Esta funcionalidade é experimental no Mac e no Linux. Recomendamos que esta funcionalidade seja ativada no Windows.
floorp-disable-toolbars = 
    .label = Desativar barras de ferramentas na janela aplicações Web
floorp-disable-toolbars-description = Esta definição irá ocultar todas as extensões e barras de ferramentas na janela das aplicações Web.
ssb-installed-list-title = Aplicações Web instaladas
ssb-uninstall-title = Desinstalar a aplicação Web
ssb-uninstall-message = Tem a certeza de que pretende desinstalar esta aplicação Web de { -brand-short-name }?
ssb-uninstall-button = 
    .label = Desinstalar
ssb-uninstall-cancel = Cancelar
######################################################################### Download Notification ###############################################################
floorp-started-download = Transferência iniciada
floorp-finished-download = Transferência concluída
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } está atualizado!
floorp-notificationContent-latest = { -brand-short-name } está atualizado. Está a utilizar a versão mais recente de { -brand-short-name }.
floorp-notificationTitle = Nova versão do { -brand-short-name } está disponível!
floorp-notificationContent = Clique para transferir a versão mais recente.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Fechar separadores para iniciar
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Fechar separadores até ao fim
    .accesskey = E
