# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label> هو أحد مستكشفات الانترنت المحلية المطورة في اليابان. يعتمد على FireFox ويعمل بموجب <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>لتحسين شبكة الويب. هل ترغب في المساعدة؟ <label data-l10n-name="helpus-donateLink">تبرع من هنا</label>
icon-creator = تصميم الأيقونة من قبل <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label> و<label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = قائمة بـ<label data-l10n-name="about-contributor">المساهمين والمطورين</label>
#################################################################### about:preferences ####################################################################

pane-design-title = تصميم
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = يتطلب إعادة تشغيل البرنامج لتصبح التغييرات نافذة المفعول
tab-width = الحد الأدنى لقياس عرض علامات التبويب
tab-height = Minimum height of tabs
preferences-tabs-newtab-position = موضع جديد لعلامة التبويب
open-new-tab-use-default = 
    .label = فتح علامات التبويب الجديدة في الموضع الافتراضي
open-new-tab-at-the-end = 
    .label = فتح علامات التبويب الجديدة في نهاية شريط علامات التبويب
open-new-tab-next-to-current = 
    .label = فتح علامات تبويب جديدة بجانب علامة التبويب الحالية
multirow-tabs-limit = 
    .label = تمكين محدودية الصف لعلامات التبويب متعددة الصفوف
multirow-tabs-newtab = 
    .label = عرض زر "فتح علامة تبويب جديدة" في نهاية الصف الأسفل من علامات التبويب
multirow-tabs-value = عدد الصفوف المسموح به عند تمكين علامات التبويب متعددة الصفوف
enable-tab-sleep = 
    .label = تمكين وضع السكون لعلامات التبويب
tab-sleep-timeout-minutes-value = سيتم إدخال علامات التبويب في وضع السكون بعد مدة من عدم النشاط (دقائق)
tab-sleep-settings-button = الإعدادات...
tab-sleep-settings-dialog-title = 
    .title = إعدادات وضع السكون لعلامات التبويب
tab-sleep-settings-dialog-excludehosts-label = استثناء المضيفين
tab-sleep-settings-dialog-excludehosts-label-2 = إدخال مضيف واحد لكل سطر.
tab-sleep-tab-context-menu-excludetab = إبقاء علامة التبويب نشطة
enable-tab-scroll-change = 
    .label = تبديل علامات التبويب عن طريق التمرير باستخدام الفأرة
enable-tab-scroll-reverse = 
    .label = عكس اتجاه تمرير علامات التبويب
enable-tab-scroll-wrap = 
    .label = التفاف علامات التبويب التي يتم تمريرها عند الحافة
enable-double-click-block = 
    .label = إغلاق علامات التبويب بالنقر المزدوج
enable-show-pinned-tabs-title = 
    .label = إظهار عنوان علامات التبويب المثبتة
tabbar-preference = شريط علامة التبويب
tab-normal-mode = 
    .label = الافتراضي
hide-horizontality-tabs = 
    .label = إخفاء علامات التبويب على شريط علامات التبويب الأفقي
verticalTab-setting = 
    .label = تحسين المستكشف لشريط علامات التبويب العمودي
move-tabbar-position = 
    .label = عرض شريط علامات التبويب أسفل شريط الأدوات
tabbar-on-bottom = 
    .label = عرض شريط علامات التبويب في أسفل الإطار
tabbar-favicon-color = 
    .label = تلوين شريط علامات التبويب باستخدام لون أيقونة اختصار الموقع الحالي
tabbar-style-preference = نمط شريط علامة التبويب
horizontal-tabbar = 
    .label = شريط علامة التبويب الأفقي
tabbar-style-description = يتطلب إعادة تشغيل { -brand-short-name } لتطبيق هذا الإعداد بشكل كامل.
multirow-tabbar = 
    .label = شريط علامة تبويب متعدد الصفوف
vertical-tabbar = 
    .label = شريط علامة تبويب عمودي (تجريبي)
native-vertical-tab-show-right = 
    .label = إظهار شريط علامة التبويب العمودي على الجانب الأيمن من الإطار
native-vertical-tab-show-padding = 
    .label = Enable padding at the top
hover-vertical-tab = 
    .label = طي شريط علامة التبويب العمودي
floorp-show-vertical-tab-newtab-button = 
    .label = إظهار زر "فتح في علامة تبويب جديدة" داخل شريط علامة التبويب العمودي
floorp-show-vertical-tab-scrollbar = 
    .label = إظهار شريط التمرير في شريط علامة التبويب العمودي
TST = نمط علامة تبويب شجري
about-TST = إن نمط علامة التبويب الشجري هو إضافة شائعة تسمح لك بعرض علامات التبويب على شكل هيكل شجري. هذه الإضافة تم دمجها مسبقاً مسبقاً في { -brand-short-name }. الرجاء تثبيت هذه الإضافة لتفعيل نمط علامة التبويب الشجري الخاص بـ { -brand-short-name }.
treestyletab-Settings = 
    .label = طي علامة التبويب الشجرية
sidebar-reverse-position-toolbar = إظهار الشريط الجانبي على الجانب الآخر
bookmarks-bar-settings = شريط أدوات قوائم العناوين (يمكن استخدام خيار واحد فقط في كل مرة)
bookmarks-focus-mode = 
    .label = إخفاء شريط أدوات قوائم العناوين ما لم يتم التمرير فوق شريط التنقل
bookmarks-bottom-mode = 
    .label = إظهار شريط أدوات قوائم العناوين في أسفل { -brand-short-name }
navbar-settings = شريط التنقل
show-nav-bar-bottom = 
    .label = إظهار شريط الأدوات أسفل { -brand-short-name } (تجريبي)
disable-extension-check-compatibility-option = 
    .label = Do not check for compatibility with add-ons (deprecated)
other-preference = إعدادات أخرى
search-positon-top = 
    .label = إظهار شريط البحث أعلى الصفحة
allow-auto-restart = 
    .label = إعادة التشغيل تلقائياً عند تغيير الإعدادات التي تتطلب إعادة التشغيل
disable-fullscreen-notification = 
    .label = عدم إظهار إشعار عند دخول وضع ملء الشاشة

## Browser Theme

system-color-settings = بعض السمات تحتوي على أوضاع فاتحة وداكنة - حدد الوضع الذي تريد استخدامه هذه السمات.
preferences-theme-appearance-header = وضع السمة
system-theme-dark = 
    .label = داكن
system-theme-light = 
    .label = فاتح
system-theme-auto = 
    .label = حسب إعدادات النظام

## User interface preferences

ui-preference = مظهر المستكشف
preferences-browser-appearance-description = حدد تصميم طرف ثالث مدمج للاستخدام في { -brand-short-name }. بعض التصاميم قد لا تكون متوافقة مع الإعدادات الخاصة بك.
firefox-proton = 
    .label = واجهة مستخدم Firefox Proton
firefox-photon-lepton = 
    .label = واجهة مستخدم Firefox Photon・Lepton
floorp-fluentUI = 
    .label = واجهة مستخدم Microsoft Fluent (متوقفة)
floorp-fluerialUI = 
    .label = { -brand-short-name } واجهة مستخدم فلوريال (جديدة)

## Download Manager

download-notification-preferences = إشعارات التحميل
start-always-notify = 
    .label = الإعلام فقط عند بدء التحميل
finish-always-notify = 
    .label = الإعلام فقط عند انتهاء التحميل
always-notify = 
    .label = الإعلام عند بدء التحميل وانتهاءه
do-not-notify = 
    .label = تعطيل إشعارات التحميل

## Sidebar

profiles-button-label = إدارة الملفات الشخصية
floorp-help-button-label = الدعم الفني لـ { -brand-short-name }
appmenuitem-reboot = 
    .label = إعادة التشغيل

## DMR UI

download-mgr-UI = 
    .label = تمكين مدير تحميل SimpleUI
downloading-red-color = 
    .label = استخدم أيقونة التحميل الحمراء عند التحميل
sidebar-preferences = الشريط الجانبي
bsb-preferences = إعدادات الشريط الجانبي لمدير المستكشف
view-sidebar2-right = 
    .label = عرض الشريط الجانبي لمدير المستكشف على اليمين
enable-sidebar2 = 
    .label = تمكين الشريط الجانبي لمدير المستكشف
visible-bms = 
    .label = إظهار الشريط الجانبي لمدير المستكشف
hide-bms-to-unload-panel = 
    .label = إلغاء تحميل اللوحة عند إخفاء اللوحة
enable-addons-in-sidebar2-with-experimental = 
    .label = تمكين المستندات التشغيلية لمحتويات الملحقات في الشريط الجانبي لمدير المستكشف (تجريبي)
enable-addons-in-sidebar2 = 
    .label = تمكين البرامج النصية لمحتويات الملحقات في الشريط الجانبي لمدير المستكشف
sidebar2-enable-addons-desc = عند تمكين هذا الإعداد، سيتم تشغيل لواحق حظر الإعلانات واللواحق الأخرى في الشريط الجانبي. ومع ذلك لن يتم تشغيل كافة الملحقات.
custom-URL-option = تعيين روابط لوحة الويب
set-custom-URL-button = 
    .label = تعيين روابط مخصصة...
    .accesskey = س
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = الشريط الجانبي لمدير المستكشف
bsb-context = استخدام الحاوية التالية
bsb-userAgent-label = 
    .label = استخدام عامل مستخدم الموبايل في لوحة الويب هذه
bsb-width = العرض (إذا تم تعيينه 0، سيتم استخدام القيمة العامة)
bsb-page = صفحة للفتح
bsb-add = إضافة لوحة ويب على الشريط الجانبي لمدير المستكشف
bsb-setting = إعدادات لوحة الويب
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = الموقع الالكتروني
sidebar2-pref-delete = 
    .label = حذف
sidebar2-pref-setting = 
    .label = الإعدادات
sidebar2-global-width = عرض لوحات الويب العالمية
use-icon-provider-option = استخدام مزود الأيقونة
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (متوفر في الصين)
use-icon-provider-option-hatena = 
    .label = Hatena (متوفر في الصين)
memory-and-performance = الذاكرة والأداء
min-memory = 
    .label = الحد الأدنى لاستخدام الذاكرة (أداء منخفض)
balance-memory = 
    .label = أداء واستخدام ذاكرة متوازن
max-memory = 
    .label = أداء أفضل (استخدام عالي للذاكرة)
delete-border-and-roundup-option = 
    .label = تدوير زوايا الصفحات

## DualTheme

dualtheme-enable = 
    .label = Enable Dual Theme (Deprecated)
floorp-enable-dualtheme-description = Dual Theme feature may cause problems with extensions. Please use with caution.
newtab-background = خلفية الصفحة الرئيسية { -brand-short-name }
newtab-background-random-image = 
    .label = صور عشوائية من Unsplash
newtab-background-gradation = 
    .label = متدرج
newtab-background-not-background = 
    .label = تعطيل الخلفية
newtab-background-selected-image = 
    .label = مجلد مخصص...
newtab-background-selected-one-image = 
    .label = صورة مخصصة...
newtab-background-folder = استخدم الصور من هذا المجلد:
newtab-background-image = استخدام صورة:
newtab-choose-image = تحديد صورة...
newtab-background-folder-reload = 
    .label = إعادة تحميل الصور
newtab-background-folder-default = 
    .label = استعادة الافتراضيات
newtab-background-folder-open = 
    .label = فتح المجلد
newtab-background-folder-choose = تحديد مجلد الصور...
newtab-background-image-choose = تحديد صورة...
newtab-background-extensions = استخدم الصور ذات اللواحق (مفصولة بـ ",")
disable-blur-on-newtab = 
    .label = تعطيل تأثير التمويه في الصفحة الرئيسية لـ { -brand-short-name }
disable-releasenote-on-newtab = 
    .label = تعطيل ملاحة الإصدار وروابط الدعم الفني في الصفحة الرئيسية لـ { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = تعطيل اعتماد صورة (Unsplash) في الصفحة الرئيسية لـ { -brand-short-name }

## Lepton Preferences

about-lepton = تخصيص { -brand-short-name } مع Lepton
lepton-preference-button = 
    .label = إعدادات Lepton...
    .accesskey = ل
lepton-header = إعدادات Lepton
lepton-preference = إعدادات Lepton
photon-mode = 
    .label = استخدام تصميم Photon
lepton-mode = 
    .label = استخدام تصميم Lepton
protonfix-mode = 
    .label = استخدام تصميم Proton معدلة
autohide-preference = إخفاء عناصر المستكشف تلقائياً
floorp-lepton-enable-tab-autohide = 
    .label = إخفاء علامات التبويب تلقائياً
floorp-lepton-enable-navbar-autohide = 
    .label = إخفاء شريط الأدوات تلقائياً
floorp-lepton-enable-sidebar-autohide = 
    .label = إخفاء الشريط الجانبي تلقائياً
floorp-lepton-enable-urlbar-autohide = 
    .label = إخفاء شريط العنوان تلقائياً
floorp-lepton-enable-back-button-autohide = 
    .label = إخفاء زر العودة تلقائياً
floorp-lepton-enable-forward-button-autohide = 
    .label = إخفاء زر الأمام تلقائياً
floorp-lepton-enable-page-action-button-autohide = 
    .label = إخفاء الأزرار تلقائيا في شريط العنوان
floorp-lepton-enable-toolbar-overlap = 
    .label = إظهار شريط الأدوات فوق محتوى الموقع
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = إخفاء شريط الأدوات تلقائياً عند عرض محتوى "ltr"
hide-preference = إدارة عناصر المستكشف
floorp-lepton-enable-tab_icon-hide = 
    .label = إخفاء أيقونات علامة التبويب
floorp-lepton-enable-tabbar-hide = 
    .label = إخفاء شريط علامة التبويب
floorp-lepton-enable-navbar-hide = 
    .label = إخفاء شريط الأدوات
floorp-lepton-enable-sidebar_header-hide = 
    .label = إخفاء رموز الشريط الجانبي
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = إخفاء أيقونات شريط العناوين
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = إخفاء أيقونات شريط الإشارات
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = إخفاء علامات شريط العلامات
floorp-lepton-enable-disabled_menu-hide = 
    .label = إخفاء عناصر قائمة السياق المعطلة
floorp-lepton-disable-userChrome-icon = 
    .label = تعطيل أيقونات قائمة السياق ولوحات Lepton
floorp-lepton-disable-userChrome-menu-icon = 
    .label = تمكين أيقونات قائمة سياق ليبتون
positon-preferences = تعديلات الموقف
floorp-lepton-enable-centered-tab = 
    .label = وسط التسميات في علامات التبويب
floorp-lepton-enable-centered-urlbar = 
    .label = وسط النص في شريط العناوين
floorp-lepton-enable-centered-bookmarkbar = 
    .label = وسط عناصر شريط العلامات
urlbar-preferences = شريط العناوين
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = نقل أيقونات شريط العناوين إلى الجانب الأيسر
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = When typing, show a "Go" button
floorp-lepton-enable-always-show-page_action = 
    .label = إظهار دائما إجراءات الصفحة في شريط العناوين
tabbar-preferences = شريط التبويب
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Tab Bar in the Title Bar
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = دمج شريط التبويب وشريط الأدوات
lepton-sidebar-preferences = Sidebar
floorp-lepton-enable-overlap-sidebar = 
    .label = إظهار الشريط الجانبي فوق محتوى الموقع
floorp-home-mode-choice-default = 
    .label = { -brand-short-name } المنزل (الافتراضي)
floorp-home-prefs-content-header = محتوى الصفحة الرئيسية { -brand-short-name }
floorp-home-prefs-content-description = اختر المحتوى الذي تريد رؤيته على الصفحة الرئيسية { -brand-short-name }.

## Notes

floorp-notes = { -brand-short-name } Notes
restore-from-backup = استعادة الملاحظات من النسخ الاحتياطي
enable-notes-sync = 
    .label = تمكين مزامنة الملاحظات { -brand-short-name }
about-notes-backup-tips = { -brand-short-name } Notes uses Firefox Sync to sync your notes with other devices. If you lose your notes, you can restore them from a backup. A backup is created when you launch { -brand-short-name }.
notes-sync-description = هذا يمكن أن يحل مشكلة فقدان المحتوى بسبب الكتابة فوق الملاحظات أثناء المزامنة.
backuped-time = النسخ الاحتياطي في
notes-backup-option = إعدادات النسخ الاحتياطي
backup-option-button = إعدادات النسخ الاحتياطي...
restore-from-backup-prompt-title = { -brand-short-name } Notes Restore Service
restore-from-this-backup = استعادة الملاحظات إلى الحالة التي كانوا فيها في هذه النسخة الاحتياطية؟
restore-button = إستعادة

## user.js

header-userjs = user.js
userjs-customize = تخصيص { -brand-short-name } باستخدام user.js
about-userjs-customize = user.js هو ملف تكوين يسمح لك بتخصيص { -brand-short-name }. يتم تنزيل ملفات user.js من الإنترنت والكتابة فوق المستخدم الحالي. ملف s. الرجاء النسخ الاحتياطي لملف user.js الحالي قبل المتابعة. سيتم تطبيق إعدادات user.js تلقائيًا بعد إعادة تشغيل { -brand-short-name }.
userjs-label = قائمة user.js
userjs-prompt = تطبيق هذا user.j؟
apply-userjs-attention = تطبيق user.js جديد سوف يستبدل ملف user.js الحالي.
apply-userjs-attention2 = الرجاء النسخ الاحتياطي لملف user.js الحالي قبل المتابعة.
userjs-button = إعدادات user.js...
userjs-select-option = إدارة user.js المستخدمة حاليا في { -brand-short-name } لتحسين الأداء والخصوصية.
apply-userjs-button = تطبيق

## userjs Options

default-userjs-label = { -brand-short-name } Default
about-default-userjs = تم تعطيل Telemetry . حسناً توازن { -brand-short-name } مع تمكين مختلف التخصيصات.
Securefox-label = تأمين يوكيرفوكس
about-Securefox = HTTPS-بشكل افتراضي. حماية ملفات تعريف الارتباط الشاملة مع عزل الموقع. تعزيز تقسيم الحالة والشبكة. تحسينات أخرى مختلفة.
default-label = Yokoffing Default
about-default = كل الضروريات. لا أحد من الكسور. هذا هو user.js.
Fastfox-label = فاتحة Fastfox
about-Fastfox = زيادة كبيرة في سرعة تصفح فايرفوكس. أعطِ كروم جرعات للحصول على ماله!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = إنهاء صفحة التبويب الجديدة. إزالة الجيب. استعادة الوضع المدمج كخيار. إيقاف التنبيهات والنوافذ المنبثقة وغير ذلك من المزاج.
Smoothfox-label = تمزيق سموثفوكس
about-Smoothfox = احصل على تمرير سلس يشبه الشريط على المتصفح المفضل الخاص بك - أو اختر شيئا أكثر من أسلوبك.
select-workspace = حدد مساحة العمل
workspace-select-icon = حدد أيقونة مساحة العمل
    .label = حدد أيقونة مساحة العمل
workspace-select-container = حدد علامة تبويب الحاوية
    .label = حدد علامة تبويب الحاوية
workspace-customize = 
    .title = تخصيص مساحة العمل
floorp-no-workspace-container = 
    .label = No Container
workspace-icon-article = 
    .label = Article
workspace-icon-book = 
    .label = Book
workspace-icon-briefcase = 
    .label = وظيفة
workspace-icon-cart = 
    .label = التسوق
workspace-icon-chat = 
    .label = Chat
workspace-icon-chill = 
    .label = خاص
workspace-icon-circle = 
    .label = دائرة
workspace-icon-compass = 
    .label = البوصلة
workspace-icon-code = 
    .label = Code
workspace-icon-dollar = 
    .label = البنك
workspace-icon-fence = 
    .label = سياج
workspace-icon-fingerprint = 
    .label = شخصي
workspace-icon-food = 
    .label = الطعام
workspace-icon-fruit = 
    .label = فاكهة
workspace-icon-game = 
    .label = Game
workspace-icon-gear = 
    .label = عتاد
workspace-icon-gift = 
    .label = هدية
workspace-icon-key = 
    .label = Key
workspace-icon-lightning = 
    .label = Lightning
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Notes
workspace-icon-paint = 
    .label = Paint
workspace-icon-photo = 
    .label = Photo
workspace-icon-pin = 
    .label = Pin
workspace-icon-pet = 
    .label = حيوان أليف
workspace-icon-question = 
    .label = سؤال
workspace-icon-smartphone = 
    .label = Smart Phone
workspace-icon-star = 
    .label = نجوم
workspace-icon-tree = 
    .label = شجرة
workspace-icon-vacation = 
    .label = العطلة
workspace-icon-love = 
    .label = Love
workspace-icon-moon = 
    .label = Moon
workspace-icon-music = 
    .label = Music
workspace-icon-user = 
    .label = User
# Custom Keyboard Shortcuts
floorp-CSK-title = اختصارات لوحة المفاتيح المخصصة
floorp-CSK-description = Customize { -brand-short-name }'s keyboard shortcuts. { -brand-short-name } provides more than 80 customizable keyboard shortcuts! Duplicate keyboard shortcuts will not work. Restart { -brand-short-name } to apply these settings.
disable-fx-actions = 
    .label = تعطيل اختصارات لوحة مفاتيح موزيلا فايرفوكس
floorp-CSK-error = The keybind you entered is already in use. Please try another keybind.
customize-Action = 
    .label = إضافة اختصار
remove-Action = 
    .label = إزالة الاختصار
CSK-reset-title = إعادة تعيين اختصارات لوحة المفاتيح المخصصة
CSK-reset-description = إعادة تعيين اختصارات لوحة المفاتيح المخصصة إلى الإعدادات الافتراضية ل { -brand-short-name }.
CSK-reset-label = إعادة تعيين اختصارات لوحة المفاتيح المخصصة
CSK-reset-button = استعادة الافتراضي
CSK-manage-title = إدارة اختصارات لوحة المفاتيح
CSK-remove-shortcutkey = إزالة اختصار لوحة المفاتيح المخصصة؟
CSK-remove-shortcutkey-description = هل أنت متأكد من أنك تريد إزالة اختصار لوحة المفاتيح هذا؟
CSK-restore-default = استعادة الإعدادات الافتراضية؟
CSK-restore-default-description = Restore { -brand-short-name }'s default keyboard shortcuts? Your current shortcuts will be lost.
CSK-reboot-browser-label = أعد تشغيل { -brand-short-name } لتطبيق هذه الإعدادات
CSK-reboot-browser-button = إعادة تشغيل { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = اختصار لوحة المفاتيح الحالية: { $key } و { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = اختصار لوحة المفاتيح الحالية: { $key }.
CSK-keyborad-shortcut-is-changed = (غير متاح)
floorp-custom-actions-tab-action = إجراءات التبويب
floorp-custom-actions-page-action = إجراءات الصفحة
floorp-custom-actions-visible-action = الإجراءات المرئية
floorp-custom-actions-search-action = إجراءات البحث
floorp-custom-actions-tools-action = إجراءات الأدوات
floorp-custom-actions-bookmark-action = إجراءات الإشارة المرجعية
floorp-custom-actions-open-page-action = فتح إجراءات الصفحة
floorp-custom-actions-history-action = إجراءات السجل
floorp-custom-actions-pip-action = إجراءات الصورة في الصورة
floorp-custom-actions-downloads-action = إجراءات التنزيلات
floorp-custom-actions-sidebar-action = إجراءات الشريط الجانبي
floorp-custom-actions-bms-action = إجراءات الشريط الجانبي لمدير المتصفح
floorp-custom-actions-split-view-action = Split View Actions
floorp-custom-actions-workspaces-action = Workspaces Actions
floorp-custom-actions-custom-action = إجراءات مخصصة (تجريبية)

## Mouse Gestures

mouse-gesture = إيماءات الماوس
mouse-gesture-description = يجب تثبيت Gesturefy لاستخدام إيماءات الماوس باستخدام { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy is an extension that adds mouse gestures to your browser. If { -brand-short-name } detects the installation of this add-on, it will add gesture commands to Gesturefy that are only available in { -brand-short-name }. This add-on also create new tabs!
# Translate
TWS = Translate Web Page
about-TWS = ترجمة صفحتك في الوقت الحقيقي باستخدام Google أو Yandex. يمكنك أيضا ترجمة النص المحدد أو الصفحة بأكملها.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = مركز الخصوصية
block-more-tracker = حظر المزيد من الإعلانات والمتابعين
block-tracker = يحتوي هذا القسم على مجموعة من الإضافات المصممة لمنع الإعلانات و التتبع
view-at-AMO = عرض هذه الإضافة في addons.mozilla.org
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin كتل الإعلانات، التعقب المكثف، والمواقع الخطيرة الإضافية.
Facebook-Container = حاوية الفيسبوك
about-Facebook-Container = منع الفيسبوك من تعقبك حول الويب. اضافة حاوية الفيسبوك تساعدك على التحكم وعزل نشاطك على الويب من الفيسبوك.

## Fingerprinting

fingerprint-header = مقاومة تسرب بصمات الأصابع وعنوان IP
block-fingerprint = البصمة هي آلية تتبع تعتمد على الميزات الفريدة للمتصفح ونظام التشغيل الخاص بك. يحتوي هذا القسم على إعدادات لزيادة تعزيز هذه الحماية بما يتجاوز الحظر الافتراضي.
enable-firefox-fingerprint-protections = 
    .label = Enable strong protection against fingerprinting
about-firefox-fingerprint-protection = الحماية التمكينية من قبل فايرفوكس تشمل وضع الإضاءة القسرية، وتعطيل بعض API، إلخ. يمكن كسر بعض المواقع.
fingerprint-Protection = 
    .label = الحماية المضادة للبصمات
html5-canvas-prompt-settings = 
    .label = رفض تلقائي لمطالبات تأكيد الوصول لبيانات صور HTML5
canvas-prompt = يمنع المواقع من استخدام عرض قراءة الكانفاس ما لم يكن مسموحا به يدويا.
disable-webgl = 
    .label = تعطيل WebGL
about-webgl = WebGL هو واجهة برمجة تطبيقات جافا سكريبت تستخدم لتقديم الرسوم البيانية، والتي يمكن استخدامها لتحديد GPU.
Canvas-Blocker = مانع الكانفاس
about-CB = هذه الاضافات الاضافية من البيانات المستخدمة بواسطة تقنيات أخذ البصمات.
WebRTC-connection = WebRTC هو معيار يوفر الاتصال في الوقت الحقيقي. إذا قمت بتعطيل هذا الإعداد، فلن تتمكن من استخدام ديسكورد، إلخ.
WebRTC = 
    .label = تمكين اتصال WebRTC
################################################################### browser ###############################################################

rest-mode = أخذ راحة...
rest-mode-description = { -brand-short-name } is currently suspended. Press ENTER or OK to continue.
Sidebar2 = 
    .label = شريط جانبي لمدير المتصفح
    .tooltiptext = تغيير رؤية الشريط الجانبي
sidebar2-mute-and-unmute = 
    .label = كتم/إلغاء كتم هذا اللوحة
sidebar2-unload-panel = 
    .label = إلغاء تحميل هذا اللوحة
sidebar2-change-ua-panel = 
    .label = تبديل وكيل المستخدم المحمول
sidebar2-delete-panel = 
    .label = حذف هذا اللوحة
sidebar2-change-zoom-level = 
    .label = Change Zoom Level
sidebar2-zoom-in = 
    .label = Zoom In
sidebar2-zoom-out = 
    .label = Zoom Out
sidebar2-reset-zoom = 
    .label = Reset Zoom
sidebar2-close-button = 
    .tooltiptext = إغلاق الشريط الجانبي
sidebar-back-button = 
    .tooltiptext = الرجوع
sidebar-forward-button = 
    .tooltiptext = إعادة
sidebar-reload-button = 
    .tooltiptext = Reload
sidebar-go-index-button = 
    .tooltiptext = الذهاب إلى المنزل
sidebar-muteAndUnmute-button = 
    .tooltiptext = Mute/Unmute sidebar
sidebar2-browser-manager-sidebar = مدير المتصفح
show-browser-manager-sidebar = 
    .tooltiptext = Show { sidebar2-browser-manager-sidebar } Sidebar
sidebar2-bookmark-sidebar = المفضلة
show-bookmark-sidebar = 
    .tooltiptext = Show { sidebar2-bookmark-sidebar } Sidebar
sidebar2-history-sidebar = التاريخ
show-history-sidebar = 
    .tooltiptext = Show { sidebar2-history-sidebar } Sidebar
sidebar2-download-sidebar = التنزيلات
show-download-sidebar = 
    .tooltiptext = Show { sidebar2-download-sidebar } Sidebar
sidebar2-notes-sidebar = الحواشي
show-notes-sidebar = 
    .tooltiptext = Show { sidebar2-notes-sidebar } Sidebar
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = الإضافات والمواضيع
sidebar2-hide-sidebar-button = 
    .tooltiptext = Hide Browser Manager Sidebar
sidebar-passwords-button = 
    .tooltiptext = كلمات المرور
sidebar-preferences-button = 
    .tooltiptext = الإعدادات
sidebar-keepWidth-button = 
    .tooltiptext = استمر في استخدام العرض الحالي في هذا اللوحة
sidebar2-keep-width-for-global = 
    .label = تطبيق هذا العرض على جميع اللوحات بدون عرض مخصص
bsb-context-add = 
    .label = إضافة صفحة إلى لوحة الويب...
bsb-context-link-add = 
    .label = إضافة رابط إلى لوحة الويب...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = فتح دليل الملف الشخصي
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = ج
css-menubar = 
    .label = CSS
    .accesskey = ج
rebuild-css = 
    .label = إعادة إنشاء ملفات CSS للمتصفح
    .accesskey = ر
make-browsercss-file = 
    .label = إنشاء ملف CSS للمتصفح
    .accesskey = م
open-css-folder = 
    .label = فتح مجلد CSS
    .accesskey = ع
edit-userChromeCss-editor = 
    .label = تحرير ملف userChrome.css
edit-userContentCss-editor = 
    .label = تحرير ملف userContent.css
not-found-editor-path = تعذر العثور على محرر ملف CSS
set-pref-description = أدخل موقع ملف محرر ملف CSS الذي تريد استخدامه:
rebuild-complete = تم إكمال إعادة البناء.
please-enter-filename = الرجاء إدخال اسم ملف.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = إعادة فتح علامة التبويب المغلقة
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = تمكين كسمة فرعية
dual-theme-disable-addon-button = تعطيل السمة الفرعية
dual-theme-enabled-heading = تمكين كسمة فرعية
##################################################################### toolbar ###############################################################

status-bar = 
    .label = شريط الحالة
    .accesskey = س
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = [{ -brand-short-name }] Open Tree Style Tab Panel
gf-floorp-open-tree-style-tab-description = Open Tree Style Tab Panel on the Sidebar
gf-floorp-open-bookmarks-sidebar-name = [{ -brand-short-name }] Open Bookmarks Panel
gf-floorp-open-bookmarks-sidebar-description = Open Bookmarks Panel on the Sidebar
gf-floorp-open-history-sidebar-name = [{ -brand-short-name }] Open History Panel
gf-floorp-open-history-sidebar-description = Open History Panel on the Sidebar
gf-floorp-open-synctabs-sidebar-name = [{ -brand-short-name }] Open Synced Tabs Panel
gf-floorp-open-synctabs-sidebar-description = Open Synced Tabs Panel on the Sidebar
gf-floorp-close-sidebar-name = [{ -brand-short-name }] Close Sidebar
gf-floorp-close-sidebar-description = إغلاق الشريط الجانبي
gf-floorp-open-browser-manager-sidebar-name = [{ -brand-short-name }] Open BMS
gf-floorp-open-browser-manager-sidebar-description = Open Browser Manager Sidebar if the Web Panel of Browser Manager Sidebar is loaded
gf-floorp-close-browser-manager-sidebar-name = [{ -brand-short-name }] Close BMS
gf-floorp-close-browser-manager-sidebar-description = إغلاق الشريط الجانبي لمدير المتصفح
gf-floorp-show-browser-manager-sidebar-name = [{ -brand-short-name }] Toggle BMS
gf-floorp-show-browser-manager-sidebar-description = تبديل شريط جانبي لمدير المتصفح
gf-floorp-hide-statusbar-name = [{ -brand-short-name }] Hide Status Bar
gf-floorp-hide-statusbar-description = إخفاء شريط الحالة
gf-floorp-show-statusbar-name = [{ -brand-short-name }] Toggle Status Bar
gf-floorp-show-statusbar-description = إظهار أو إخفاء شريط الحالة
gf-floorp-open-extension-sidebar-name = [{ -brand-short-name }] Open selected add-on Sidebar
gf-floorp-open-extension-sidebar-description = Open selected add-on on the Sidebar
gf-floorp-open-extension-sidebar-settings-addons-id = إضافة الشريط الجانبي
gf-floorp-open-extension-sidebar-settings-addons-id-description = تمديد الإضافات المفتوحة للشريط الجانبي
gf-floorp-open-extension-sidebar-settings-list-default = الرجاء تحديد الإضافة
gf-floorp-open-extension-sidebar-settings-list-unknwon = إضافة غير معروفة
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = تم العثور على تحديثات!
update-portable-notification-found-message = جاري تحميل التحديثات...
update-portable-notification-ready-title = جاهز للتحديث!
update-portable-notification-ready-message = { -brand-short-name } will be updated on the next launch.
update-portable-notification-success-title = نجاح التحديث!
update-portable-notification-success-message = Update succeeded! Hope you enjoy the new version of { -brand-short-name }!
update-portable-notification-failed-title = فشل التحديث.
update-portable-notification-failed-redirector-message = فشل التحديث. إعادة تشغيل المتصفح الخاص بك قد تحل هذه المشكلة.
update-portable-notification-failed-prepare-message = فشل في إعداد التحديث.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = { -brand-short-name } تحديث محمول
floorp-update-application-auto-enabled-option = 
    .label = التحقق تلقائياً من وجود تحديثات إلى { -brand-short-name } محمولة. (مستحسن)
##################################################################### Open link in external ###############################################################
openInExternal-title = فتح في المتصفح الخارجي
open-link-in-external-enabled-option = 
    .label = تمكين ميزة "فتح في المتصفح الخارجي"
open-link-in-external-select-browser-option = اختر المستعرض الذي سيتم فتحه
open-link-in-external-select-browser-option-default = 
    .label = المتصفح الافتراضي
open-link-in-external-tab-context-menu = فتح في المتصفح الخارجي
open-link-in-external-tab-dialog-title-error = حدث خطأ:
open-link-in-external-tab-dialog-message-default-browser-not-found = لم يتم العثور على المتصفح الافتراضي أو لم يتم تكوينه.
open-link-in-external-tab-dialog-message-selected-browser-not-found = المتصفح المحدد غير موجود.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = جديد
memo-title-input-placeholder = اكتب عنوان هنا
memo-input-placeholder = كتابة أو لصق مذكرة هنا
delete-memo = حذف
save-memo = حفظ
memo-welcome-title = مرحباً!
memo-first-tip = Welcome to { -brand-short-name } Notes! Here are some instructions on how to use it!
memo-second-tip = { -brand-short-name } Notes is a notepad that lets you store multiple notes that sync across devices. To enable synchronization, you need to sign in to { -brand-short-name } with your Firefox account.
memo-third-tip = { -brand-short-name } Notes will be saved in your { -brand-short-name } settings and synchronized across devices using Firefox Sync. Firefox Sync encrypts the contents of the sync with your Firefox account password, so no one but you know its contents.
memo-import-data-tip = مزامنة فايرفوكس ليست خدمة احتياطية. ننصحك بإنشاء نسخ احتياطية.
memo-new-title = ملاحظة جديدة
chage-view-mode = تبديل وضع العرض/التعديل
readonly-mode = غير متصل (مقروء فقط)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = دعم Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = مسح التنزيلات
    .accesskey = د
    .tooltiptext = مسح التنزيلات
floorp-show-all-downloads = 
    .label = إظهار جميع التنزيلات
    .accesskey = س
    .tooltiptext = إظهار جميع التنزيلات
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Create new Workspace...
    .tooltiptext = Create a new Workspace
workspaces-manage-workspaces-button = 
    .label = Manage Workspaces...
    .tooltiptext = Manage your Workspaces
reorder-this-workspace-to-up = 
    .label = Move up this Workspace
    .accesskey = B
reorder-this-workspace-to-down = 
    .label = Move down this Workspace
    .accesskey = A
rename-this-workspace = 
    .label = Rename Workspace
    .accesskey = R
delete-this-workspace = 
    .label = Delete Workspace
    .accesskey = D
manage-this-workspaces = 
    .label = Manage Workspaces...
    .accesskey = M
workspace-new-default-name = New Workspace
workspace-default-name = Default
move-tab-another-workspace = 
    .label = الانتقال إلى فضاء عمل آخر
rename-workspace-prompt-title = Rename Workspace
rename-workspace-prompt-text = Enter Workspace Name. Most characters and symbols can be used.
workspaces-toolbar-button = Workspaces
    .label = Workspaces
    .tooltiptext = Select a Workspace...

## Preferences

enable-workspaces = 
    .label = Enable Workspaces
    .tooltiptext = Enable Workspaces
workspace-notice = Workspaces will not work with this settings enabled unless the workspaces's button is placed on the toolbar. Use this setting if you want to disable Workspaces completely.
enable-workspaces-with-experimental = 
    .label = Enable Workspaces (Experimental)
    .tooltiptext = Enable Workspaces (Experimental)
workspace-warning = Workspaces cannot be used with Tab Group add-ons. If you want to use Tab Group add-ons, please disable Workspaces and restart { -brand-short-name }.
category-workspaces = 
    .label = Workspaces
    .tooltiptext = Workspaces
pane-workspaces-title = Workspaces
floorp-workspaces-title = { -brand-short-name } مساحات عمل
floorp-workspace-settings-button = إعدادات مساحة العمل...
floorp-preferences-label = Preferences
floorp-extensions-label = Extensions
floorp-private-label = Private
change-to-close-workspace-popup-option = 
    .label = Close Workspaces popup when selecting a Workspace
manage-workspace-on-bms-option = 
    .label = إدارة مساحة العمل على مدير المتصفح الشريط الجانبي
show-workspace-name-option = 
    .label = إظهار اسم فضاء العمل على زر مساحة عمل شريط التبويب
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = وضع المشاركة
    .accesskey = س
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = تسجيل الدخول إلى حساب فايرفوكس الخاص بك
welcome-to-floorp = مرحبا بكم في { -brand-short-name }!
welcome-describe-floorp = { -brand-short-name } is a feature-rich, flexible browser that supports various environments and is based on Firefox.
welcome-start-setup = Ready to dive in?
welcome-skip-to-start-browsing = تخطي لبدء التصفح
welcome-select-preferences-template = Choose a template
welcome-minimum-template = اساسي
welcome-enable-basic-features = Enable basic features and settings for a simple experience.
welcome-medium-template = الافتراضي
welcome-enable-some-features = Enable additional features and settings for a better experience.
welcome-maximum-template = متقدم
welcome-enable-most-of-features = Enable advanced features and settings. Recommended for experienced users.
welcome-go-next-setup = التالي
welcome-select-browser-design = حدد تصميم المتصفح
welcome-describe-browser-design = You can choose one of the wonderful third-party { -brand-short-name } designs. OS-specific designs are also available in Preferences.
welcome-design-lepton-name = تصميم ليبتون الأصلي
welcome-design-photon-name = تصميم ليبتون فوتون
welcome-design-ProtonFix-name = تصميم ليبتون بروتونفيكس
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = تصميم فايرفوكس بروتون
welcome-import-data = استيراد بيانات المتصفح الخاصة بك
welcome-import-data-description = Quick setup! Import your bookmarks, passwords, and more from your old browser. Firefox users can import data from Firefox Sync.
welcome-import-data-button = استيراد البيانات...
welcome-import-data-skip = تخطي الاستيراد
welcome-select-button = حدد
welcome-finish-setup = اكتمل الإعداد!
welcome-finish-setup-description = You're all set! Other features like Vertical Tabs & Workspaces can be found in { -brand-short-name }'s Settings. Enjoy { -brand-short-name }!
welcomet-finish-setup = بدء تصفح الويب
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Keyboard Shortcuts
    .tooltiptext = Keyboard Shortcuts
category-CSK-title = Keyboard Shortcuts
shortcutkey-customize = 
    .title = Keyboard Shortcuts
select-shortcutkeyAction = حدد إجراء للتشغيل
shortcutkey-customize-key-list-placeholder = سوف يظهر اختصار لوحة المفاتيح هنا
shortcut-key-label = Keyboard Shortcut
start-input-button-listen = Start Listening
end-input-button-listen = Stop Listening
shortcut-key-description = Click "Start Listening" and enter your new keyboard shortcut for this action. Multiple keys can be used; however, keyboard shortcuts will not work if already assigned to other actions.
floorp-custom-actions-open-new-tab = فتح علامة تبويب جديدة
    .label = فتح علامة تبويب جديدة
floorp-custom-actions-close-tab = إغلاق علامة التبويب الحالية
    .label = إغلاق علامة التبويب الحالية
floorp-custom-actions-open-new-window = فتح نافذة جديدة
    .label = فتح نافذة جديدة
floorp-custom-actions-open-new-private-window = فتح نافذة خاصة جديدة
    .label = فتح نافذة خاصة جديدة
floorp-custom-actions-close-window = إغلاق النافذة الحالية
    .label = إغلاق النافذة الحالية
floorp-custom-actions-restore-last-session = استعادة الجلسة الأخيرة
    .label = استعادة الجلسة الأخيرة
floorp-custom-actions-restore-last-window = استعادة النافذة الأخيرة
    .label = استعادة النافذة الأخيرة
floorp-custom-actions-show-next-tab = إظهار التبويب التالي
    .label = إظهار التبويب التالي
floorp-custom-actions-show-previous-tab = إظهار علامة التبويب السابقة
    .label = إظهار علامة التبويب السابقة
floorp-custom-actions-show-all-tabs-panel = إظهار كل لوحات التبويب
    .label = إظهار قائمة علامات التبويب
floorp-custom-actions-send-with-mail = إرسال مع البريد
    .label = إرسال عبر البريد الإلكتروني
floorp-custom-actions-save-page = حفظ الصفحة
    .label = حفظ الصفحة
floorp-custom-actions-print-page = Print page
    .label = Print page
floorp-custom-actions-mute-current-tab = تبديل كتم/إلغاء كتم التبويب الحالي
    .label = تبديل كتم/إلغاء كتم التبويب الحالي
floorp-custom-actions-toggle-bookmark-toolbar = Toggle bookmark toolbar
    .label = تبديل شريط أدوات الإشارات
floorp-custom-actions-show-source-of-page = إظهار مصدر الصفحة
    .label = فتح مصدر الصفحة
floorp-custom-actions-show-page-info = إظهار معلومات الصفحة
    .label = فتح معلومات الصفحة
floorp-custom-actions-zoom-in = تكبير في
    .label = تكبير في
floorp-custom-actions-zoom-out = تكبير خارجي
    .label = تكبير خارجي
floorp-custom-actions-reset-zoom = Reset zoom
    .label = Reset zoom
floorp-custom-actions-back = الرجوع
    .label = الرجوع
floorp-custom-actions-forward = إعادة
    .label = إعادة
floorp-custom-actions-reload = Reload
    .label = Reload
floorp-custom-actions-stop = توقف
    .label = توقف
floorp-custom-actions-force-reload = إعادة التحميل الإجباري
    .label = إعادة التحميل الإجباري
floorp-custom-actions-search-in-this-page = البحث في هذه الصفحة
    .label = البحث في الصفحة
floorp-custom-actions-show-next-search-result = إظهار كلمة البحث التالية في نتيجة هذه الصفحة
    .label = النتيجة التالية "البحث في الصفحة"
floorp-custom-actions-show-previous-search-result = إظهار كلمة البحث السابقة في نتيجة هذه الصفحة
    .label = النتيجة السابقة "البحث في الصفحة"
floorp-custom-actions-search-the-web = البحث في الويب
    .label = البحث في الويب
floorp-custom-actions-open-migration-wizard = فتح معالج الهجرة
    .label = فتح معالج الهجرة
floorp-custom-actions-quit-from-application = الخروج من التطبيق
    .label = الخروج { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Customize Toolbar
    .label = فتح التخصيص { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Enter offline mode
    .label = أدخل الوضع دون اتصال
floorp-custom-actions-open-screen-capture = فتح أداة التقاط الشاشة
    .label = التقاط لقطة شاشة
floorp-custom-actions-show-pip = إظهار الصورة في الصورة
    .label = إظهار الصورة في الصورة
floorp-custom-actions-bookmark-this-page = إشارة مرجعية إلى هذه الصفحة
    .label = إشارة مرجعية إلى هذه الصفحة
floorp-custom-actions-open-bookmarks-sidebar = فتح الشريط الجانبي للعلامات المرجعية
    .label = فتح الشريط الجانبي للعلامات
floorp-custom-actions-open-bookmark-add-tool = فتح أداة إضافة الإشارة المرجعية
    .label = إضافة إشارة مرجعية
floorp-custom-actions-open-bookmark-add-toolbar = Open "Add a new bookmark" pop-up window
    .label = إضافة إلى شريط أدوات الإشارات المرجعية
floorp-custom-actions-open-bookmarks-manager = فتح مدير الإشارات المرجعية
    .label = فتح مدير الإشارات المرجعية
floorp-custom-actions-show-bookmark-toolbar = تبديل شريط أدوات الإشارة المرجعية
    .label = تبديل شريط أدوات الإشارات
floorp-custom-actions-open-general-preferences = فتح التفضيلات العامة
    .label = فتح التفضيلات العامة
floorp-custom-actions-open-privacy-preferences = فتح تفضيلات الخصوصية
    .label = فتح تفضيلات الخصوصية
floorp-custom-actions-open-workspaces-preferences = Open Workspaces preferences
    .label = فتح تفضيلات مساحات العمل
floorp-custom-actions-open-containers-preferences = فتح تفضيلات الحاويات
    .label = تفضيلات الحاويات المفتوحة
floorp-custom-actions-open-search-preferences = فتح تفضيلات البحث
    .label = فتح تفضيلات البحث
floorp-custom-actions-open-sync-preferences = فتح تفضيلات المزامنة
    .label = فتح تفضيلات المزامنة
floorp-custom-actions-open-task-manager = فتح مدير المهام
    .label = فتح مدير المهام { -brand-short-name }
floorp-custom-actions-open-home-page = فتح الصفحة الرئيسية { -brand-short-name }
    .label = فتح الصفحة الرئيسية ل { -brand-short-name }
floorp-custom-actions-open-addons-manager = Open add-ons and themes
    .label = فتح الإضافات والمواضيع
floorp-custom-actions-forget-history = نسيان التاريخ
    .label = نسيان التاريخ
floorp-custom-actions-quick-forget-history = نسيان سريع للتاريخ
    .label = نسيان سريع للتاريخ
floorp-custom-actions-clear-recent-history = مسح المحفوظات الحديثة
    .label = مسح المحفوظات الحديثة
floorp-custom-actions-search-history = سجل البحث
    .label = سجل البحث
floorp-custom-actions-manage-history = إدارة السجل
    .label = إدارة السجل
floorp-custom-actions-open-downloads = فتح التنزيلات
    .label = فتح التنزيلات
floorp-custom-actions-show-bms = Toggle browser manager sidebar
    .label = Toggle the Browser Manager Sidebar
floorp-custom-actions-show-current-panel = Toggle current panel
    .label = Toggle Current Panel
floorp-custom-actions-show-bookmark-sidebar = إظهار الشريط الجانبي للإشارة المرجعية
    .label = إظهار شريط الإشارات الجانبي
floorp-custom-actions-show-history-sidebar = Show history sidebar
    .label = Show History Sidebar
floorp-custom-actions-show-synced-tabs-sidebar = Show synced tabs sidebar
    .label = Show Synced Tabs Sidebar
floorp-custom-actions-reverse-sidebar = موقف الشريط الجانبي العكسي
    .label = موقف الشريط الجانبي العكسي
floorp-custom-actions-hide-sidebar = Hide sidebar
    .label = Hide sidebar
floorp-custom-actions-show-sidebar = تبديل الشريط الجانبي
    .label = تبديل الشريط الجانبي
floorp-custom-actions-toggle-sidebar = Toggle sidebar
    .label = Toggle sidebar
floorp-custom-actions-open-previous-workspace = Open previous Workspace
    .label = Open previous Workspace
floorp-custom-actions-open-next-workspace = Open next Workspace
    .label = Open next Workspace
floorp-custom-actions-show-panel-1 = تبديل لوحة 1
    .label = تبديل لوحة 1
floorp-custom-actions-show-panel-2 = تبديل لوحة 2
    .label = تبديل لوحة 2
floorp-custom-actions-show-panel-3 = تبديل اللوحة 3
    .label = تبديل اللوحة 3
floorp-custom-actions-show-panel-4 = تبديل لوحة 4
    .label = تبديل لوحة 4
floorp-custom-actions-show-panel-5 = تبديل اللوحة 5
    .label = تبديل اللوحة 5
floorp-custom-actions-show-panel-6 = تبديل اللوحة 6
    .label = تبديل اللوحة 6
floorp-custom-actions-show-panel-7 = تبديل اللوحة 7
    .label = تبديل اللوحة 7
floorp-custom-actions-show-panel-8 = تبديل اللوحة 8
    .label = تبديل اللوحة 8
floorp-custom-actions-show-panel-9 = تبديل اللوحة 9
    .label = تبديل اللوحة 9
floorp-custom-actions-show-panel-10 = تبديل اللوحة 10
    .label = تبديل اللوحة 10
floorp-custom-actions-open-split-view-on-left = Open current tab on left in split view
    .label = Open current tab on left in split view
floorp-custom-actions-open-split-view-on-right = Open current tab on right in split view
    .label = Open current tab on right in split view
floorp-custom-actions-close-split-view = Close split view
    .label = Close split view
floorp-custom-actions-custom-action-1 = إجراء مخصص 1
    .label = إجراء مخصص 1
floorp-custom-actions-custom-action-2 = الإجراء المخصص 2
    .label = الإجراء المخصص 2
floorp-custom-actions-custom-action-3 = الإجراء المخصص 3
    .label = الإجراء المخصص 3
floorp-custom-actions-custom-action-4 = الإجراء المخصص 4
    .label = الإجراء المخصص 4
floorp-custom-actions-custom-action-5 = الإجراء المخصص 5
    .label = الإجراء المخصص 5
floorp-custom-actions-rest-mode = Enable rest mode
    .label = Enable rest mode
floorp-custom-actions-hide-user-interface = Toggle User Interface
    .label = Toggle User Interface
floorp-custom-actions-toggle-navigation-panel = Toggle Navigation Panel
    .label = Toggle Navigation Panel
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = تشغيل
    .tooltiptext = تشغيل { -brand-short-name } مع هذا الملف الشخصي
floorp-profiles-in-use = هذا الملف الشخصي قيد الاستخدام.
floorp-profiles-title = Profiles
floorp-profile-manager = مدير الملف الشخصي
floorp-profiles-create = إنشاء ملف شخصي
floorp-profile = الملف الشخصي
    .label = مدير الملف الشخصي
    .tooltiptext = فتح مدير الملف الشخصي
fxa-not-signed-in = لم يتم تسجيل الدخول
###################################################################### Private Container ##############################################################
floorp-private-container-name = خاص
floorp-toggle-private-container = 
    .label = إعادة الفتح في حاوية خاصة/لا حاوية
    .accesskey = ب
open-in_private-container = 
    .label = فتح في علامة تبويب جديدة مع حاوية خاصة
######################################################################## Split View ###############################################################

floorp-split-view-open-menu = 
    .label = Open in Split View
floorp-split-view-fixed-menu = 
    .label = Split this Tab in a Tab without Split View
floorp-split-view-open-menu-disabled = 
    .label = Need Unspliting and Unselected tab
split-view-remove-button = Remove Split View
split-view-title = Split View Settings
split-view-position = Position
split-view-flex-type = Flex Type
split-view-position-top = Top Side
split-view-position-left = Default
split-view-position-right = Reverse
split-view-flex-column = Vertical
split-view-flex-row = Horizontal
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = مسح رمز QR باستخدام هاتفك
qrcode-generate-page-action = 
    .tooltiptext = شارك هذه الصفحة مع هاتفك
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = زر الإضافات الموحدة
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Install app
    .tooltiptext = Install this site as an app
ssb-page-action-title = Install app
ssb-app-open-button = 
    .label = Open In App
ssb-app-install-button = 
    .label = Install
ssb-app-cancel-button = 
    .label = Cancel
floorp-open-manage-ssb-page = 
    .label = Manage installed Web Apps
appmenuitem-webapps = 
    .label = Web Apps
appmenu-open-installed-apps-subheader = Open installed web apps
appmenuitem-install-current-page = 
    .label = Install this site as an app
appmenuitem-open-current-page = 
    .label = Open this site on installed app
appmenuitem-contextmenu-open-app = 
    .label = Open this app
appmenuitem-contextmenu-uninstall-app = 
    .label = Uninstall this app

## Preferences

category-ssb = 
    .label = Web Apps
    .tooltiptext = Web Apps
category-ssb-title = Web Apps
floorp-ssb-title = Web Apps
floorp-ssb-description = Web Apps are websites that can be installed as apps. They can be launched from { -brand-short-name }'s menu panel or the Windows Start menu.
ssb-preferences = Web Apps Settings
floorp-enable-ssb = 
    .label = Enable Web Apps
floorp-enable-ssb-with-experimental = 
    .label = Enable Web Apps (Experimental)
floorp-enable-ssb-description = This feature is experimental on Mac and Linux. It is recommended to enable this feature on Windows.
floorp-disable-toolbars = 
    .label = Disable toolbars on Web Apps Window
floorp-disable-toolbars-description = This setting will hide all extensions and toolbars on Web Apps Window.
ssb-installed-list-title = Installed Web Apps
ssb-uninstall-title = Uninstall Web App
ssb-uninstall-message = Are you sure you want to uninstall this Web App from { -brand-short-name }?
ssb-uninstall-button = 
    .label = Uninstall
ssb-uninstall-cancel = Cancel
######################################################################### Download Notification ###############################################################
floorp-started-download = Download started
floorp-finished-download = Download finished
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } is up to date!
floorp-notificationContent-latest = { -brand-short-name } is up to date. You are using the latest version of { -brand-short-name }.
floorp-notificationTitle = New version of { -brand-short-name } is available!
floorp-notificationContent = Click to download the latest version.
######################################################################### vertical tab bar ###############################################################

close-tabs-to-the-start-on-vertical-tab-bar = 
    .label = Close Tabs to Start
    .accesskey = S
close-tabs-to-the-end-on-vertical-tab-bar = 
    .label = Close Tabs to End
    .accesskey = E
