# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

###################################################################### about:Dialog #################################################################################

about-floorp = <label data-l10n-name="floorp-browser-link">{ -brand-product-name }</label>là một trong những trình duyệt được phát triển tại Nhật Bản. Trình duyệt được dưa trên firefox và tiếp tục vận hành dưới <label data-l10n-name="ablaze-Link">{ -vendor-short-name }</label>, đễ hỗ trợ sự phát triển của web. Bạn muốn giúp đỡ?<label data-l10n-name="helpus-donateLink">Đóng góp</label>
icon-creator = Biểu tượng được thiết kể bởi <label data-l10n-name="browser-logo-twitter">@CutterKnife_</label>và<label data-l10n-name="brand-logo-twitter">@mwxdxx.</label>
contributors = Danh sách<label data-l10n-name="about-contributor">nhà hảo tâm và lập trình viên</label>
#################################################################### about:preferences ####################################################################

pane-design-title = Thiết kế
category-design = 
    .tooltiptext = { pane-design-title }
design-header = { pane-design-title }
feature-requires-restart = Khởi động lại để áp dụng thay đổi
tab-width = Độ rộng tối thiểu của thẻ
preferences-tabs-newtab-position = Vị trí tab mới
open-new-tab-use-default = 
    .label = Mở thẻ mới tại vị trí mặc định
open-new-tab-at-the-end = 
    .label = Mở thẻ mới ở cuối
open-new-tab-next-to-current = 
    .label = Mở tab kế bên tab hiện tại
multirow-tabs-limit = 
    .label = Mở cài đặt số lượng dòng tối đa khi sử dụng multi-row tabs
multirow-tabs-newtab = 
    .label = Đặt nút "mở một tab mới" tại dòng thấp nhất của tabs
multirow-tabs-value = Số lượng của dòng khi multi-row tabs được bật
enable-tab-sleep = 
    .label = Kích hoạt tính năng Sleeping Tabs
tab-sleep-timeout-minutes-value = Tabs sẽ được đưa vào chế độ Sleeping sau khi ngưng tương tác trong (phút)
tab-sleep-settings-button = Cài đặt...
tab-sleep-settings-dialog-title = 
    .title = Cài đặt Sleeping Tabs
tab-sleep-settings-dialog-excludehosts-label = Ngoại trừ các hosts
tab-sleep-settings-dialog-excludehosts-label-2 = Thêm tên host trên từng dòng.
tab-sleep-tab-context-menu-excludetab = Giữ thẻ luôn hoạt động
enable-tab-scroll-change = 
    .label = Đổi tab khi scroll chuột
enable-tab-scroll-reverse = 
    .label = Đảo chiều khi scroll tabs
enable-tab-scroll-wrap = 
    .label = Cuộn vòng các tab tại mép
enable-double-click-block = 
    .label = Tắt tab bằng cách nhấp đúp chuột
enable-show-pinned-tabs-title = 
    .label = Hiển thị tiêu đề của thẻ được ghim
tabbar-preference = Thanh chứa thẻ
tab-normal-mode = 
    .label = Mặc định
hide-horizontality-tabs = 
    .label = Ẩn thẻ khi sử dụng thanh chứa thẻ nằm ngang
verticalTab-setting = 
    .label = Ẩn các thẻ khi thanh chứa thẻ nằm dọc
move-tabbar-position = 
    .label = Hiển thị Tab bar dưới thanh công cụ
tabbar-on-bottom = 
    .label = Hiển thị ngăn chứa thẻ ở cuối cửa sổ
tabbar-favicon-color = 
    .label = Màu của thanh chứa thẻ dựa vào biểu tượng trang web
tabbar-style-preference = Kiểu Tab Bar
horizontal-tabbar = 
    .label = Tab Bar ngang
tabbar-style-description = Cần khởi động lại { -brand-short-name } để áp dụng cài đặt.
multirow-tabbar = 
    .label = Tab Bar nhiều dòng
vertical-tabbar = 
    .label = Thanh chứa thẻ nằm dọc (Thử nghiệm)
native-vertical-tab-show-right = 
    .label = Hiển thị thanh chứa thẻ dạng dọc ở bên phải cửa sổ
hover-vertical-tab = 
    .label = Thu gọn thanh chứa thẻ nằm dọc
floorp-show-vertical-tab-newtab-button = 
    .label = Hiện nút "Mở thẻ mới" bên trong Thanh chứa thẻ dọc
floorp-show-vertical-tab-scrollbar = 
    .label = Hiển thị thanh cuộn trên thanh chứa thẻ nằm dọc
TST = Tree Style Tab
about-TST = Tree Style Tab là tiện ích phổ biến cho phép bạn hiện thị các tab dưới dạng cây thư mục. Nó đã được tích hợp sẵn trong { -brand-short-name }. Vui lòng cài đặt tiện ích để kích hoạt cho { -brand-short-name }'.
treestyletab-Settings = 
    .label = Thu gọn Tree Style Tab
sidebar-reverse-position-toolbar = Hiển thị thanh lề bên phía đối diện
bookmarks-bar-settings = Thanh công cụ Đánh dấu ( chỉ có một tuỳ chọn có thể sử dụng)
bookmarks-focus-mode = 
    .label = Ẩn thanh công cụ đánh dấu trừ khi được di chuột thanh điều hướng
bookmarks-bottom-mode = 
    .label = Hiển thị thanh công cụ đánh dấu ở cuối { -brand-short-name }
navbar-settings = Thanh điều hướng
show-nav-bar-bottom = 
    .label = Hiển thị thanh công cụ ở dưới { -brand-short-name } (thử nghiệm)
material-effect = 
    .label = Hỗ trợ Mica cho mọi người có thể chỉnh sửa thiết kế của trình duyệt
disable-extension-check-compatibility-option = 
    .label = Không kiểm tra tương thích với add-ons
other-preference = Các tuỳ chọn khác
enable-userscript = 
    .label = Kích hoạt các thành phần Legacy
about-userscript = Kích hoạt tính năng này có thể gây ra một số lỗi không mong muốn.
search-positon-top = 
    .label = Hiển thị thanh tiềm kiếm đầu trang
allow-auto-restart = 
    .label = Tự động khởi động lại trình duyệt khi có thay đổi ở các cài đặt yêu cầu
disable-fullscreen-notification = 
    .label = Không thông báo khi ở chế độ toàn màn hình

## Browser Theme

system-color-settings = Một số giao diện có hai chế độ tối và sáng - bạn có thể chọn chế độ tùy theo sở thích.
preferences-theme-appearance-header = Kiểu giao diện
system-theme-dark = 
    .label = Tối
system-theme-light = 
    .label = Sáng
system-theme-auto = 
    .label = Sử dụng giao diện của hệ thống

## User interface preferences

ui-preference = Giao diện trình duyệt
preferences-browser-appearance-description = Chọn lựa công cụ thiết kế bên thứ ba để sử dụng { -brand-short-name }. Một số thiết kế có thể không tương thích với cài đặt của bạn.
firefox-proton = 
    .label = Giao diện Firefox Proton
firefox-photon-lepton = 
    .label = Giao diện Firefox Photon - Lepton
floorp-fluentUI = 
    .label = Microsoft Fluent UI (không khuyến khích)
floorp-fluerialUI = 
    .label = { -brand-short-name } Fluerial UI (không khuyến khích)
floorp-gnomeUI = 
    .label = GNOME theme (không khuyến khích)

## Download Manager

download-notification-preferences = Thông báo khi tải về
start-always-notify = 
    .label = Chỉ thông báo khi bắt đầu tải xuống
finish-always-notify = 
    .label = Chỉ thông báo khi hoản thành tải xuống
always-notify = 
    .label = Thông báo khi bắt đầu và hoàn thành tải xuống
do-not-notify = 
    .label = Vô hiệu hóa những thông báo này

## Sidebar

profiles-button-label = Quản lý Hồ sơ
floorp-help-button-label = Hỗ trợ { -brand-short-name }
appmenuitem-reboot = 
    .label = Khởi động lại

## UserAgent

userAgent-preference = User Agent
default-useragent-mode = 
    .label = Sử dụng Firefox User Agent ( Mặc định)
windows-chrome-useragent-mode = 
    .label = Như Chrome trên Windows
macOS-chrome-useragent-mode = 
    .label = Như Chrome trên macOS
linux-chrome-useragent-mode = 
    .label = Như Chrome trên Linux
mobile-chrome-useragent-mode = 
    .label = Như Chrome trên iOS
use-custom-useragent-mode = 
    .label = Sử dụng User Agent tuỳ chỉnh

## DMR UI

download-mgr-UI = 
    .label = Kích hoạt giao diện quản lý tải SimpleUI
downloading-red-color = 
    .label = Sử dụng biểu tượng màu đỏ khi tải
sidebar-preferences = Thanh lề
bsb-preferences = Quản lý thanh lề
view-sidebar2-right = 
    .label = Hiển thị thanh lề bên phải
enable-sidebar2 = 
    .label = Kích hoạt thanh lề
visible-bms = 
    .label = Hiện thanh lề
hide-bms-to-unload-panel = 
    .label = Dừng hoạt động của thanh lề khi ẩn
enable-addons-in-sidebar2-with-experimental = 
    .label = Kích hoạt tiện ích mở rộng ở thanh lề (thí nghiệm)
enable-addons-in-sidebar2 = 
    .label = Kích hoạt tiện ích mở rộng ở thanh lề
sidebar2-enable-addons-desc = Nếu tuỳ chỉnh này được bật, một số tiện ích mở rộng như chặn quảng cáo sẽ hoạt động bên thanh lề. Tuy nhiên, không phải tất cả tiện ích sẽ hoạt động.
custom-URL-option = Đặt liên kết Web Panel
set-custom-URL-button = 
    .label = Thêm liên kết tùy chọn...
    .accesskey = S
pane-BSB-title = { bsb-header }
category-BSB = 
    .tooltiptext = { pane-BSB-title }
category-downloads = 
    .tooltiptext = { files-and-applications-title }
bsb-header = Cài đặt thanh lề
bsb-context = Sử dụng các ngăn chứa thẻ dưới đây
bsb-userAgent-label = 
    .label = Sử dụng Mobile User Agent trong Web Panel
bsb-width = Độ rộng (nếu được chỉnh về 0, giá trị của trình duyệt sẽ được sử dụng)
bsb-page = Mở trang
bsb-add = Thêm Web Panel vào thanh lề
bsb-setting = Tuỳ chỉnh Web Panel cho thanh lề
bsb-add-title = 
    .title = { bsb-add }
bsb-setting-title = 
    .title = { bsb-setting }
bsb-browser-manager-sidebar = 
    .label = { sidebar2-browser-manager-sidebar }
bsb-bookmark-sidebar = 
    .label = { sidebar2-bookmark-sidebar }
bsb-history-sidebar = 
    .label = { sidebar2-history-sidebar }
bsb-download-sidebar = 
    .label = { sidebar2-download-sidebar }
bsb-notes-sidebar = 
    .label = { sidebar2-notes-sidebar }
bsb-website = 
    .label = Trang web
sidebar2-pref-delete = 
    .label = Xóa
sidebar2-pref-setting = 
    .label = Cài đặt
sidebar2-global-width = Độ rộng mặc định cho trang web
use-icon-provider-option = Sử dụng biểu tưởng được cung cấp từ
use-icon-provider-option-google = 
    .label = Google
use-icon-provider-option-duckduckgo = 
    .label = DuckDuckGo
use-icon-provider-option-yandex = 
    .label = Yandex (Có ở Trung Quốc)
use-icon-provider-option-hatena = 
    .label = Hatena (Có ở Trung Quốc)
memory-and-performance = Bộ nhớ và hiệu năng
min-memory = 
    .label = Sử dụng bộ nhớ thấp (hiệu năng thấp)
balance-memory = 
    .label = Cân bằng hiệu năng và bộ nhớ
max-memory = 
    .label = Hiệu năng cao nhất ( sử dụng nhiều bộ nhớ)
delete-border-and-roundup-option = 
    .label = Bo tròn các góc của trang
STG-smilar-workspaces-option = 
    .label = Biến nút tiện ích mở rộng "Simple Tab Groups" giống nút không gian làm việc

## DualTheme

dualtheme-enable = 
    .label = Bật chủ đề đôi
newtab-background = Ảnh nền của { -brand-short-name }
newtab-background-random-image = 
    .label = Ảnh ngẫu nhiên từ Unsplash
newtab-background-gradation = 
    .label = Gradient
newtab-background-not-background = 
    .label = Tắt ảnh nền
newtab-background-selected-image = 
    .label = Tuỳ chỉnh thư mục...
newtab-background-selected-one-image = 
    .label = Tuỳ chọn ảnh...
newtab-background-folder = Sử dụng ảnh tại thư mục này:
newtab-background-image = Sử dụng ảnh :
newtab-choose-image = Chọn ảnh...
newtab-background-folder-reload = 
    .label = Tải lại ảnh
newtab-background-folder-default = 
    .label = Khôi phục mặc định
newtab-background-folder-open = 
    .label = Mở thư mục
newtab-background-folder-choose = Chọn thư mục ảnh...
newtab-background-image-choose = Chọn ảnh...
newtab-background-extensions = Dùng ảnh với những định dạng sau (được ngăn cách bởi dấu,)
disable-blur-on-newtab = 
    .label = Vô hiệu hoá hiệu ứng mờ trong trang chủ { -brand-short-name }
disable-releasenote-on-newtab = 
    .label = Vô hiệu hoá thông tin cập nhật và liên kết hỗ trợ trong trang chủ { -brand-short-name }
disable-imagecredit-on-newtab = 
    .label = Không hiện credit (Unsplash) trong trang chủ { -brand-short-name }

## Lepton Preferences

about-lepton = Tuỳ chỉnh { -brand-short-name } với giao diện Lepton
lepton-preference-button = 
    .label = Thiết lập giao diện Lepton...
    .accesskey = L
lepton-header = Thiết lập giao diện Lepton
lepton-preference = Thiết lập giao diện Lepton
photon-mode = 
    .label = Dùng giao diện Photon
lepton-mode = 
    .label = Dùng giao diện Lepton
protonfix-mode = 
    .label = Sử dụng giao diện Proton đã được chỉnh sửa
autohide-preference = Tự động ẩn các thành phần của trình duyệt
floorp-lepton-enable-tab-autohide = 
    .label = Tự động ẩn các thẻ
floorp-lepton-enable-navbar-autohide = 
    .label = Tự động ẩn thanh công cụ
floorp-lepton-enable-sidebar-autohide = 
    .label = Tự động ẩn thanh lề
floorp-lepton-enable-urlbar-autohide = 
    .label = Tự động ẩn thanh địa chỉ
floorp-lepton-enable-back-button-autohide = 
    .label = Tự động ẩn nút quay lại
floorp-lepton-enable-forward-button-autohide = 
    .label = Tự động ẩn nút chuyển tiếp
floorp-lepton-enable-page-action-button-autohide = 
    .label = Tự động ẩn các nút trên thanh địa chỉ
floorp-lepton-enable-toolbar-overlap = 
    .label = Hiển thị thanh công cụ trên nội dung trang web
floorp-lepton-enable-toolbar-overlap-allow-layout-shift-autohide = 
    .label = Tự động ẩn thanh công cụ khi hiện thị nội dung dưới dạng "Ltr"
hide-preference = Quản lý thành phần của trình duyệt
floorp-lepton-enable-tab_icon-hide = 
    .label = Ẩn biểu tượng thẻ
floorp-lepton-enable-tabbar-hide = 
    .label = Ẩn thanh chứa thẻ
floorp-lepton-enable-navbar-hide = 
    .label = Ẩn thanh công cụ
floorp-lepton-enable-sidebar_header-hide = 
    .label = Ẩn tiêu đề cạnh lề
floorp-lepton-enable-urlbar_iconbox-hide = 
    .label = Ẩn icon thanh địa chỉ
floorp-lepton-enable-bookmarkbar_icon-hide = 
    .label = Ẩn icon thanh dấu trang
floorp-lepton-enable-bookmarkbar_label-hide = 
    .label = Ẩn nhãn thanh dấu trang
floorp-lepton-enable-disabled_menu-hide = 
    .label = Ẩn các mục bị vô hiệu hoá khi nhấp chuột phải
floorp-lepton-disable-userChrome-icon = 
    .label = Vô hiệu hoá context menu của Lepton và biểu tượng thanh công cụ
floorp-lepton-disable-userChrome-menu-icon = 
    .label = Hiện biểu tượng context menu của Lepton
positon-preferences = Chỉnh sửa vị trí
floorp-lepton-enable-centered-tab = 
    .label = Canh giữa nhãn trong các thẻ
floorp-lepton-enable-centered-urlbar = 
    .label = Canh giữa chữ trong thanh địa chỉ
floorp-lepton-enable-centered-bookmarkbar = 
    .label = Canh giữa các thẻ trên thanh dấu trang
urlbar-preferences = Thanh địa chỉ
floorp-lepton-enable-urlbar-icon-move-to-left = 
    .label = Chuyển biểu tượng thanh địa chỉ sang bên trái
floorp-lepton-enable-urlname-go_button_when_typing = 
    .label = Khi gõ, hiện nút "Go"
floorp-lepton-enable-always-show-page_action = 
    .label = Luôn hiển thị các thao tác trong thanh địa chỉ
tabbar-preferences = Thanh chứa thẻ
floorp-lepton-enable-tabbar-positon-as-titlebar = 
    .label = Thanh chứa thẻ nằm ngay trên thanh tiêu đề
floorp-lepton-enable-tabbar-as-urlbar = 
    .label = Kết hợp thanh chứa thẻ và thanh công cụ
lepton-sidebar-preferences = Thanh lề
floorp-lepton-enable-overlap-sidebar = 
    .label = Hiện thanh lề đè lên nội dung trang web
floorp-home-mode-choice-default = 
    .label = Trang chủ của { -brand-short-name } (mặc định)
floorp-home-prefs-content-header = Nội dung trang chủ { -brand-short-name }
floorp-home-prefs-content-description = Chọn nội dung bạn muốn thấy tại trang chủ { -brand-short-name }.

## Notes

floorp-notes = Ghi chú { -brand-short-name }
restore-from-backup = Khôi phục Ghi chú từ bản sao lưu
enable-notes-sync = 
    .label = Bật Ghi chú được đồng bộ trong { -brand-short-name }
about-notes-backup-tips = Ghi chú của { -brand-short-name } sử dụng Firefox Sync để đồng bộ hóa ghi chú của bạn với các thiết bị khác. Nếu bạn mất ghi chú, bạn có thể khôi phục chúng từ bản sao lưu. Bản sao lưu được tạo ra mỗi khi bạn khởi động { -brand-short-name }.
notes-sync-description = Điều này có thể giải quyết vấn đề mất nội dung do việc ghi đè ghi chú trong quá trình đồng bộ.
backuped-time = Được sao lưu vào lúc
notes-backup-option = Cài đặt sao lưu
backup-option-button = Cài đặt sao lưu...
restore-from-backup-prompt-title = Khôi phục ghi chú của { -brand-short-name }
restore-from-this-backup = Khôi phục trạng thái ghi chú theo bản sao lưu này?
restore-button = Khôi phục

## user.js

header-userjs = user.js
userjs-customize = Tuỳ chỉnh { -brand-short-name } với user.js
about-userjs-customize = user.js là tập tin giúp bạn tùy chỉnh { -brand-short-name }. Tập tin user.js được tải xuống từ Internet và sẽ ghi đè lên tập tin user.js hiện tại của bạn. Hãy sao lưu tập tin user.js hiện tại của bạn trước khi tiếp tục. Các tuỳ chỉnh trong user.js sẽ được áp dụng tự động sau khi bạn khởi động lại { -brand-short-name }.
userjs-label = Danh sách các tập tin user.js
userjs-prompt = Áp dụng user.js này?
apply-userjs-attention = User.js mới này sẽ ghi đè vào tập tin user.js hiện tại của bạn.
apply-userjs-attention2 = Vui lòng lưu lại tập tin user.js hiện tại của bạn trước khi tiếp tục.
userjs-button = Tuỳ chỉnh user.js...
userjs-select-option = Quản lý tập tin user.js hiện đang được sử dụng trong { -brand-short-name } để cải thiện hiệu suất và bảo mật.
apply-userjs-button = Áp dụng

## userjs Options

default-userjs-label = { -brand-short-name } Mặc định
about-default-userjs = Tiến trình thu thập dữ liệu đã bị vô hiệu hoá. Cân đối { -brand-short-name } với nhiều tuỳ biến khác nhau.
Securefox-label = Yokoffing Securefox
about-Securefox = Sử dụng HTTPS theo mặc định. Bảo vệ cookie toàn diện với tính năng cách ly trang web. Cải thiện trạng thái và phân vùng mạng. Nhiều cải tiến khác.
default-label = Yokoffing Default
about-default = Những thứ cần thiết. Đây là tập tin user.js của bạn.
Fastfox-label = Yokoffing Fastfox
about-Fastfox = Tăng cường đáng kể tốc độ duyệt web của Floorp. Thách thức sức mạnh của Chrome!
Peskyfox-label = Yokoffing Peskyfox
about-Peskyfox = Sắp xếp gọn gàng giao diện trang thẻ mới. Gỡ bỏ Pocket. Khôi phục chế độ thu gọn như một tùy chọn. Ngừng thông báo trang web, pop-up và những phiền toái khác.
Smoothfox-label = Yokoffing Smoothfox
about-Smoothfox = Đem trải nghiệm cuộn mượt như trình duyệt Microsoft Edge vào trình duyệt yêu thích của bạn - hoặc chọn những thứ phù hợp với phong cách của bạn.
select-workspace = Lựa chọn không gian làm việc
workspace-select-icon = Lựa chọn biểu tượng không gian làm việc
    .label = Lựa chọn biểu tượng không gian làm việc
workspace-select-container = Lựa chọn ngăn chứa thẻ
    .label = Lựa chọn ngăn chứa thẻ
workspace-customize = 
    .title = Tuỳ chỉnh không gian làm việc
floorp-no-workspace-conatiner = 
    .label = Không có ngăn chứa thẻ
workspace-icon-article = 
    .label = Bài viết
workspace-icon-book = 
    .label = Sách
workspace-icon-briefcase = 
    .label = Công việc
workspace-icon-cart = 
    .label = Mua sắm
workspace-icon-chat = 
    .label = Trò chuyện
workspace-icon-chill = 
    .label = Riêng tư
workspace-icon-circle = 
    .label = Hình tròn
workspace-icon-compass = 
    .label = La bàn
workspace-icon-code = 
    .label = Code
workspace-icon-dollar = 
    .label = Ngân hàng
workspace-icon-fence = 
    .label = Hàng rào
workspace-icon-fingerprint = 
    .label = Cá nhân
workspace-icon-food = 
    .label = Thức ăn
workspace-icon-fruit = 
    .label = Hoa quả
workspace-icon-game = 
    .label = Trò chơi
workspace-icon-gear = 
    .label = Công cụ
workspace-icon-gift = 
    .label = Quà
workspace-icon-key = 
    .label = Chìa khoá
workspace-icon-lightning = 
    .label = Sét
workspace-icon-network = 
    .label = Internet
workspace-icon-notes = 
    .label = Ghi chú
workspace-icon-paint = 
    .label = Hội hoạ
workspace-icon-photo = 
    .label = Ảnh
workspace-icon-pin = 
    .label = Pin
workspace-icon-pet = 
    .label = Thú cưng
workspace-icon-question = 
    .label = Dấu hỏi
workspace-icon-smartphone = 
    .label = Điện thoại thông minh
workspace-icon-star = 
    .label = Ngôi sao
workspace-icon-tree = 
    .label = Cây
workspace-icon-vacation = 
    .label = Kì nghỉ
workspace-icon-love = 
    .label = Tình yêu
workspace-icon-moon = 
    .label = Mặt trăng
workspace-icon-music = 
    .label = Nhạc
workspace-icon-user = 
    .label = Người dùng
# Custom Keyboard Shortcuts
floorp-CSK-title = Tuỳ chỉnh phím tắt
floorp-CSK-description = Tuỳ chỉnh phím tắt của { -brand-short-name }. { -brand-short-name } cung cấp hơn 80 phím tắt có thể tuỳ chỉnh! Các phím tắt trùng lặp sẽ không hoạt động. Khởi động lại { -brand-short-name } để áp dụng các cài đặt này.
disable-fx-actions = 
    .label = Vô hiệu hoá các phím tắt của Mozilla Firefox
customize-Action = 
    .label = Thêm phím tắt
remove-Action = 
    .label = Gỡ bỏ phím tắt
CSK-reset-title = Đặt lại tuỳ chỉnh phím tắt
CSK-reset-description = Đặt lại các phím tắt về dạng mặc định của { -brand-short-name }.
CSK-reset-label = Đặt lại các phím tắt
CSK-reset-button = Khôi phục về mặc định
CSK-manage-title = Quản lý phím tắt
CSK-remove-shortcutkey = Xoá phím tắt bàn phím tùy chỉnh?
CSK-remove-shortcutkey-description = Bạn chắc chắn muốn bỏ phím tắt này?
CSK-restore-default = Khôi phục mặc định?
CSK-restore-default-description = Khôi phục phím tắt mặc định của { -brand-short-name }? Các phím tắt hiện tại của bạn sẽ bị mất.
CSK-reboot-browser-label = Khởi động lại { -brand-short-name } để áp dụng những tuỳ chỉnh này
CSK-reboot-browser-button = Khởi động lại { -brand-short-name }
# Exist shortcut key: "S", "shift"
CSK-keyborad-shortcut-info = Phím tắt hiện tại: { $key } & { $modifiers }.
CSK-keyborad-shortcut-info-with-keycode = Phím tắt tuỳ chỉnh hiện tại: { $key}.
CSK-keyborad-shortcut-is-changed = (Không được áp dụng)
floorp-custom-actions-tab-action = Thao tác thẻ
floorp-custom-actions-page-action = Thao tác trên trang
floorp-custom-actions-visible-action = Thao tác hiển thị
floorp-custom-actions-search-action = Thao tác tìm kiếm
floorp-custom-actions-tools-action = Thao tác ở thanh công cụ
floorp-custom-actions-bookmark-action = Thao tác dấu trang
floorp-custom-actions-open-page-action = Thao tác mở trang
floorp-custom-actions-history-action = Thao tác lịch sử
floorp-custom-actions-pip-action = Thao tác Ảnh - trong - ảnh (Pip)
floorp-custom-actions-downloads-action = Thao tác tải xuống
floorp-custom-actions-sidebar-action = Thao tác thanh lề
floorp-custom-actions-bms-action = Thao tác quản lý thanh lề
floorp-custom-actions-split-view-action = Thao tác chia đôi màn hình
floorp-custom-actions-workspaces-action = Thao tác không gian làm việc
floorp-custom-actions-custom-action = Thao tác tuỳ chỉnh (thử nghiệm)

## Mouse Gestures

mouse-gesture = Cử chỉ chuột
mouse-gesture-description = Gesturefy cần phải cài đặt để sử dụng cử chỉ chuột với { -brand-short-name }.
Gesturefy = Gesturefy
about-Gesturefy = Gesturefy là một tiện ích mở rộng thêm cử chỉ chuột vào trình duyệt của bạn. Nếu { -brand-short-name } phát hiện rằng tiện ích đã được cài đặt, nó sẽ thêm các lệnh cử chỉ vào Gesturefy chỉ có sẵn trong { -brand-short-name }. Tiện ích này cũng tạo ra các tab mới!
# Translate
TWS = Translate Web Pages
about-TWS = Dịch trang của bạn ngay lập tức bằng cách sử dụng Google hoặc Yandex. Bạn cũng có thể dịch đoạn văn bản được đánh dấu hoặc toàn bộ trang.

# Privacy Hub


## BlockMoreTrackers

privacy-hub-header = Privacy Hub
block-more-tracker = Chặn quảng cáo và trình theo dõi mạnh mẽ hơn
block-tracker = Khu vực này chứa những tiện ích mở rộng dùng để chặn quảng cáo và trình theo dõi
view-at-AMO = Xem tiện ích mở rộng này tại addons.mozilla.org
uBlock-Origin = uBlock Origin
about-uboori = uBlock Origin chặn quảng cáo, các trình theo dõi và các trang web nguy hiểm khác.
Facebook-Container = Facebook Container
about-Facebook-Container = Ngăn chặn Facebook theo dõi bạn khi đang ở trên trang web. Phần mở rộng Facebook Container giúp bạn giữ quyền kiểm soát và cô lập hoạt động web của bạn trước Facebook.

## Fingerprinting

fingerprint-header = Ngăn ngừa Fingerprinting và lộ địa chỉ IP
block-fingerprint = Fingerprinting là một cơ chế theo dõi dựa trên các đặc điểm duy nhất của trình duyệt và hệ điều hành của bạn. Phần này chứa các thiết lập để tăng cường bảo vệ hơn nữa so với trình chặn mặc định.
enable-firefox-fingerprint-protections = Bật trình bảo vệ mạnh hơn trước Fingerprinting
about-firefox-fingerprint-protection = Bật bảo vệ do Firefox bao gồm bắt buộc dùng chế độ sáng, vô hiệu hoá một số APIs, etc. Một vài trang có thể bị lỗi.
fingerprint-Protection = 
    .label = Bảo vệ chống Fingerprinting
html5-canvas-prompt-settings = 
    .label = Tự động bỏ qua các thông báo xác nhận truy cập cho dữ liệu hình ảnh HTML5
canvas-prompt = Ngăn chặn trang web sử dụng thông báo đọc canvas trừ khi được phép thủ công.
disable-webgl = 
    .label = Vô hiệu hoá WebGL
about-webgl = WebGL là API của Javascript để hiển thị đồ hoạ, có thể được dùng để xác định GPU.
Canvas-Blocker = Canvas Blocker
about-CB = Ngăn chặn trình theo dõi lưu lại dấu vân tay của bạn bằng cách sử dụng Api Canvas.
WebRTC-connection = WebRTC là một tiêu chuẩn cung cấp cuộc gọi thời gian thực. Nếu bạn tắt thiết lập này, bạn sẽ không thể sử dụng Discord, v. v.
WebRTC = 
    .label = Bật kết nối WebRTC
################################################################### browser ###############################################################

rest-mode = Nghỉ ngơi một lát...
rest-mode-description = { -brand-short-name } hiện đang trong trạng thái nghỉ. Nhấn Enter hay Ok để tiếp tục.
Sidebar2 = 
    .label = Quản lý thanh lề
    .tooltiptext = Thay đổi hiển thị thanh lề
sidebar2-mute-and-unmute = 
    .label = Tắt âm/bật âm thanh khung này
sidebar2-unload-panel = 
    .label = Không chạy khung này
sidebar2-change-ua-panel = 
    .label = Tắt/bật User Agent Mobile
sidebar2-delete-panel = 
    .label = Xoá khung này
sidebar2-close-button = 
    .tooltiptext = Đóng thanh lề
sidebar-back-button = 
    .tooltiptext = Trở lại
sidebar-forward-button = 
    .tooltiptext = Chuyển tiếp
sidebar-reload-button = 
    .tooltiptext = Tải lại
sidebar-go-index-button = 
    .tooltiptext = Về trang chủ
sidebar-muteAndUnmute-button = 
    .tooltiptext = Tắt âm/ bật âm tại thanh lề
sidebar2-browser-manager-sidebar = Quản lý trình duyệt
show-browser-manager-sidebar = 
    .tooltiptext = Hiện { sidebar2-browser-manager-sidebar }
sidebar2-bookmark-sidebar = Dấu trang
show-bookmark-sidebar = 
    .tooltiptext = Hiện { sidebar2-bookmark-sidebar }
sidebar2-history-sidebar = Lịch sử
show-history-sidebar = 
    .tooltiptext = Hiện { sidebar2-history-sidebar }
sidebar2-download-sidebar = Tải xuống
show-download-sidebar = 
    .tooltiptext = Xem { sidebar2-download-sidebar }
sidebar2-notes-sidebar = Notes
show-notes-sidebar = 
    .tooltiptext = Hiện { sidebar2-notes-sidebar }
sidebar-add-button = 
    .tooltiptext = { bsb-add }
sidebar-addons-button = 
    .tooltiptext = Tiện ích mở rộng và chủ đề
sidebar2-hide-sidebar-button = 
    .tooltiptext = Ẩn quản lý thanh lề
sidebar-passwords-button = 
    .tooltiptext = Mật khẩu
sidebar-preferences-button = 
    .tooltiptext = Cài đặt
sidebar-keepWidth-button = 
    .tooltiptext = Tiếp tục sử dụng độ rộng này của khung
sidebar2-keep-width-for-global = 
    .label = Áp dụng độ rộng này cho tất cả các khung không có độ rộng tùy chỉnh
bsb-context-add = 
    .label = Thêm trang này vào Web Panel...
bsb-context-link-add = 
    .label = Thêm liên kết này Web Panel...
#################################################################### menu panel ############################################################

open-profile-dir = 
    .label = Mở thư mục Profile
####################################################################### menu ###############################################################

css-menu = 
    .label = CSS
    .accesskey = C
css-menubar = 
    .label = CSS
    .accesskey = C
rebuild-css = 
    .label = Tạo lại tập tin CSS cho trình duyệt
    .accesskey = R
make-browsercss-file = 
    .label = Tạo tập tin CSS cho trình duyệt
    .accesskey = M
open-css-folder = 
    .label = Mở thư mục CSS
    .accesskey = O
edit-userChromeCss-editor = 
    .label = Tuỳ chỉnh userChrome.css
edit-userContentCss-editor = 
    .label = Tuỳ chỉnh userContent.css
not-found-editor-path = Không thể tìm thấy trình chỉnh sửa file CSS
set-pref-description = Nhập vào vị trí của trình chỉnh sửa file CSS bạn muốn sử dụng:
rebuild-complete = Quá trinh tạo lại đã hoàn tất.
please-enter-filename = Vui lòng nhập tên file.
################################################################### Undo-Closed-Tab ###############################################################

undo-closed-tab = Mở lại tab đã đóng
################################################################### about:addons ###############################################################

# Dual Theme
dual-theme-enable-addon-button = Kích hoạt dưới dạng chủ đề phụ
dual-theme-disable-addon-button = Vô hiệu hoá chủ đề phụ
dual-theme-enabled-heading = Kích hoạt dưới dạng chủ đề phụ
##################################################################### toolbar ###############################################################

status-bar = 
    .label = Thanh trạng thái
    .accesskey = S
##################################################################### Gesturefy ###############################################################

gf-floorp-open-tree-style-tab-name = Mở bảng điều khiển của Tree Style Tab của { -brand-short-name }
gf-floorp-open-tree-style-tab-description = Mở bảng điều khiển Tree Style Tab ở thanh lề
gf-floorp-open-bookmarks-sidebar-name = Mở bảng điểu khiển thanh dấu trang của { -brand-short-name }
gf-floorp-open-bookmarks-sidebar-description = Mở panel dấu trang ở Sidebar
gf-floorp-open-history-sidebar-name = Mở lịch sử { -brand-short-name } ở thanh lề
gf-floorp-open-history-sidebar-description = Mở bảng điểu khiển lịch sử ở thanh lề
gf-floorp-open-synctabs-sidebar-name = Mở phần đồng bộ ở thanh lề cho { -brand-short-name }
gf-floorp-open-synctabs-sidebar-description = Mở bảng điểu khiển đồng bộ Tab ở thanh lề
gf-floorp-close-sidebar-name = Tắt thanh lề { -brand-short-name }
gf-floorp-close-sidebar-description = Tắt thanh lề
gf-floorp-open-browser-manager-sidebar-name = Mở quản lý thanh lề { -brand-short-name }
gf-floorp-open-browser-manager-sidebar-description = Mở quản lý thanh lề nếu Web Panel của nó đã được tải
gf-floorp-close-browser-manager-sidebar-name = Đóng quản lý thanh lề { -brand-short-name }
gf-floorp-close-browser-manager-sidebar-description = Tắt quản lý thanh lề
gf-floorp-show-browser-manager-sidebar-name = Tắt/bật quản lý thanh lề { -brand-short-name }
gf-floorp-show-browser-manager-sidebar-description = Tắt/bật quản lý thanh lề
gf-floorp-hide-statusbar-name = Ẩn thanh trạng thái { -brand-short-name }
gf-floorp-hide-statusbar-description = Ẩn thanh trạng thái
gf-floorp-show-statusbar-name = Bật/tắt thanh trạng thái { -brand-short-name }
gf-floorp-show-statusbar-description = Hiện hoặc ẩn thanh trạng thái
gf-floorp-open-extension-sidebar-name = Mở tiện ích mở rộng { -brand-short-name } được chọn ở thanh lề
gf-floorp-open-extension-sidebar-description = Mở tiện ích mở rộng được chọn ở thanh lề
gf-floorp-open-extension-sidebar-settings-addons-id = Tiện ích mở rộng của thanh lề
gf-floorp-open-extension-sidebar-settings-addons-id-description = Tiện ích mở rộng của thanh lề
gf-floorp-open-extension-sidebar-settings-list-default = Vui lòng lựa chọn tiện ích
gf-floorp-open-extension-sidebar-settings-list-unknwon = Tiện ích không xác định
##################################################################### { -brand-short-name } System Update Portable Version ###############################################################

update-portable-notification-found-title = Tìm thấy cập nhật!
update-portable-notification-found-message = Đang tải cập nhật...
update-portable-notification-ready-title = Sẵn sàng để cập nhật!
update-portable-notification-ready-message = { -brand-short-name } sẽ được cập nhật ở lần khởi động sau.
update-portable-notification-success-title = Cập nhật thành công!
update-portable-notification-success-message = Cập nhật thành công! Hi vọng bạn thích phiên bản mới của { -brand-short-name }!
update-portable-notification-failed-title = Cập nhật thất bại.
update-portable-notification-failed-redirector-message = Cập nhật thất bại. Hãy khởi động lại trình duyệt để có thể giải quyết vấn đề.
update-portable-notification-failed-prepare-message = Chuẩn bị cập nhật không thành công.
##################################################################### { -brand-short-name } Portable Preferences ###############################################################

floorp-portable-update-application-allow = Cập nhật { -brand-short-name } phiên bản di động
floorp-update-application-auto-enabled-option = 
    .label = Tự động cập nhật phiên bản di động của { -brand-short-name }. (Khuyến khích)
##################################################################### Open link in external ###############################################################
openInExternal-title = Mở bằng trình duyệt ngoài
open-link-in-external-enabled-option = 
    .label = Bật tính năng "Mở bằng trình duyệt ngoài"
open-link-in-external-select-browser-option = Chọn trình duyệt sẽ được mở
open-link-in-external-select-browser-option-default = 
    .label = Trình duyệt mặc định
open-link-in-external-tab-context-menu = Mở bằng trình duyệt ngoài
open-link-in-external-tab-dialog-title-error = Đã xảy ra lỗi:
open-link-in-external-tab-dialog-message-default-browser-not-found = Trình duyệt mặc định không được tìm thấy hoặc tuỳ chỉnh.
open-link-in-external-tab-dialog-message-selected-browser-not-found = Trình duyệt được chọn không tồn tại.
######################################################################### { -brand-short-name } Notes ###############################################################

new-memo = Tạo
memo-title-input-placeholder = Viết tiêu đề ở đây
memo-input-placeholder = Nhập hoặc dán memo ở đây
delete-memo = Xoá
save-memo = Lưu
memo-welcome-title = Chào mừng!
memo-first-tip = Chào mừng đến với mục ghi chú của{ -brand-short-name } ! Dưới đây là cách sử dụng chúng!
memo-second-tip = Các ghi chú trong { -brand-short-name } có thể được đồng bộ trên nhiều thiết bị. Để kích hoạt tính năng đồng bộ, bạn chỉ cần đăng nhập vào { -brand-short-name } bằng tài khoản Firefox của mình.
memo-third-tip = Những ghi chú trong { -brand-short-name } sẽ được lưu trong cài đặt của bạn và đồng bộ qua các thiết bị sử dụng Firefox Sync. Firefox Sync mã hóa nội dung đồng bộ với mật khẩu của tài khoản Firefox của bạn, đảm bảo rằng chỉ có bạn mới biết nội dung của nó.
memo-import-data-tip = Firefox Sync không phải là dịch vụ dùng để sao lưu. Chúng tôi khuyến nghị bạn hãy tự tạo sao lưu dữ liệu của bạn.
memo-new-title = Ghi chú mới
chage-view-mode = Chế độ xem / chỉnh sửa
readonly-mode = Chế độ không kết nối mạng (chỉ đọc)
######################################################################### Default bookmarks ###############################################################
default-bookmark-ablaze-support = Hỗ trợ Ablaze
######################################################################### Like Chrome Download mgr ###############################################################

floorp-delete-all-downloads = 
    .label = Xoá các tải xuống
    .accesskey = D
    .tooltiptext = Xoá các tải xuống
floorp-show-all-downloads = 
    .label = Xem tất cả tải xuống
    .accesskey = S
    .tooltiptext = Xem tất cả tải xuống
######################################################################### workspace ###############################################################

workspaces-create-new-workspace-button = 
    .label = Tạo không gian làm việc mới...
    .tooltiptext = Tạo không gian làm việc mới
workspaces-manage-workspaces-button = 
    .label = Quản lý không gian làm việc...
    .tooltiptext = Quản lý không gian làm việc
rename-this-workspace = 
    .label = Đổi tên không gian làm việc
    .accesskey = R
delete-this-workspace = 
    .label = Xoá không gian làm việc
    .accesskey = D
manage-this-workspaces = 
    .label = Quản lý không gian làm việc...
    .accesskey = M
workspace-new-default-name = Không gian làm việc mới
workspace-default-name = Mặc định
move-tab-another-workspace = 
    .label = Chuyển tới không gian làm việc khác
rename-workspace-prompt-title = Đổi tên không gian làm việc
rename-workspace-prompt-text = Nhập tên không gian làm việc. Có thể sử dụng các kí tự và kí hiệu thông thường.
workspaces-toolbar-button = Không gian làm việc
    .label = Không gian làm việc
    .tooltiptext = Chọn không gian làm việc...

## Preferences

enable-workspaces = 
    .label = Kích hoạt không gian làm việc
    .tooltiptext = Kích hoạt không gian làm việc
workspace-notice = Không gian làm việc sẽ không hoạt động trừ khi nút của không gian làm việc được đặt trên thanh công cụ. Sử dụng tuỳ chọn này nếu bạn muốn hoàn toàn vô hiệu hoá chức năng Không gian làm việc.
enable-workspaces-with-experimental = 
    .label = Kích hoạt không gian làm việc (Thử nghiệm)
    .tooltiptext = Kích hoạt không gian làm việc (Thử nghiệm)
workspace-warning = Không gian làm việc không thể sử dụng với tiện ích mở rộng Tab Group. Nếu bạn muốn sử dụng tiện ích Tab Group, vui lòng tắt tính năng không gian làm việc và khởi động lại { -brand-short-name }.
category-workspaces = 
    .label = Không gian làm việc
    .tooltiptext = Không gian làm việc
pane-workspaces-title = Không gian làm việc
floorp-workspaces-title = Không gian làm việc { -brand-short-name }
floorp-workspace-settings-button = Cài đặt không gian làm việc...
change-to-close-workspace-popup-option = 
    .label = Đóng cửa sổ bật lên khi đang chọn một không gian làm việc
manage-workspace-on-bms-option = 
    .label = Quản lý không gian làm việc trong Quản lý thanh lề
show-workspace-name-option = 
    .label = Hiển thị tên của không gian làm việc trong thanh chứa thẻ
######################################################################### menubar item ###############################################################

sharemode-menuitem = 
    .label = Chế độ Chia sẻ
    .accesskey = S
############################################################################## Welcome page ###############################################################

welcome-login-to-firefox-account = Đăng nhập vào Tài khoản Firefox của bạn
welcome-to-floorp = Chào mừng { -brand-short-name }!
welcome-discribe-floorp = { -brand-short-name } là một trình duyệt dễ dàng mở rộng hỗ trợ nhiều môi trường và dựa trên Firefox.
welcome-start-setup = Sẵn sàng để đi sâu chưa?
welcome-skip-to-start-browsing = Bỏ qua để bắt đầu sử dụng trình duyệt
welcome-select-preferences-template = Chọn mẫu
welcome-minimum-template = Cơ bản
welcome-enable-basic-features = Kích hoạt tính năng và cài đặt cho trải nghiệm đơn giản.
welcome-medium-template = Mặc định
welcome-enable-some-features = Kích hoạt tính năng phụ và cài đặt cho một trải nghiệm tốt hơn.
welcome-maximum-template = Nâng cao
welcome-enable-most-of-features = Kích hoạt tính năng và cài đặt nâng cao hơn. Phù hợp cho người sử dụng đã có kinh nghiệm sử dụng.
welcome-go-next-setup = Tiếp tục
welcome-select-browser-design = Chọn giao diện của Trình duyệt
welcome-discribe-browser-design = Bạn có thể chọn một trong các giao diện từ bên thứ 3 cho { -brand-short-name }. Những giao diện dành riêng cho các hệ điều hành khác nhau cũng sẵn sàng trong Cài Đặt.
welcome-design-lepton-name = Giao diện Lepton nguyên mẫu
welcome-design-photon-name = Giao diện Lepton Photon
welcome-design-ProtonFix-name = Giao diện Lepton ProtonFix
welcome-design-floorp-fluerial-name = { -brand-short-name } Fluerial Design
welcome-design-firefox-proton-name = Giao diện Firefox Proton
welcome-import-data = Nhập dữ liệu trình duyệt của bạn
welcome-import-data-description = Cài đặt nhanh! Nhập dấu trang, mật khẩu và nhiều thứ khác từ trình duyệt cũ của bạn. Người dùng Firefox có thể dùng Firefox Sync để nhập.
welcome-import-data-button = Nhập dữ liệu...
welcome-import-data-skip = Bỏ qua việc nhập
welcome-select-button = Chọn
welcome-finish-setup = Cài đặt hoàn thành!
welcome-finish-setup-description = Tất cả đã hoàn tất! Các tính năng các như thanh chứa thẻ nằm dọc và không gian làm việc có thể tìm thấy tại cài đặt của { -brand-short-name }! Hãy tận hưởng { -brand-short-name }!
welcomet-finish-setup = Bắt đầu duyệt web
############################################################# Custom Shortcutkey ###############################################################

category-CSK = 
    .label = Phím tắt
    .tooltiptext = Phím tắt
category-CSK-title = Phím tắt
shortcutkey-customize = 
    .title = Phím tắt
select-shortcutkeyAction = Lựa chọn thao tác để kích hoạt
shortcutkey-customize-key-list-placeholder = Phím tắt của bạn sẽ xuất hiện ở đây
shortcut-key-label = Phím tắt
start-input-button-listen = Bắt đầu lắng nghe
end-input-button-listen = Dừng lắng nghe
shortcut-key-description = Chọn "Bắt đầu lắng nghe" và nhấn phím tắt mới cho thao tác này. Có thể nhấn nhiều phím cùng lúc; tuy nhiên, phím tắt sẽ không hoạt động nếu nó đã được đặt cho các thao tác khác.
floorp-custom-actions-open-new-tab = Mở thẻ mới
    .label = Mở thẻ mới
floorp-custom-actions-close-tab = Tắt thẻ hiện tại
    .label = Tắt thẻ hiện tại
floorp-custom-actions-open-new-window = Mở cửa sổ mới
    .label = Mở cửa sổ mới
floorp-custom-actions-open-new-private-window = Mở thẻ riêng tư mới
    .label = Mở trong cửa sổ riêng tư mới
floorp-custom-actions-close-window = Đóng cửa sổ hiện tại
    .label = Đóng cửa sổ hiện tại
floorp-custom-actions-restore-last-session = Khôi phục phiên làm việc trước
    .label = Khôi phục phiên làm việc trước
floorp-custom-actions-restore-last-window = Mở lại cửa số trước
    .label = Mở lại cửa số trước
floorp-custom-actions-show-next-tab = Hiện thẻ tiếp theo
    .label = Hiện thẻ tiếp theo
floorp-custom-actions-show-previous-tab = Hiện thẻ trước
    .label = Hiện thẻ trước
floorp-custom-actions-show-all-tabs-panel = Hiển thị tất cả các thẻ
    .label = Hiện danh sách thẻ
floorp-custom-actions-send-with-mail = Gửi kèm theo mail
    .label = Gửi bằng mail
floorp-custom-actions-save-page = Lưu lại trang
    .label = Lưu lại trang
floorp-custom-actions-print-page = In trang
    .label = In trang
floorp-custom-actions-mute-current-tab = Bật/tắt âm thanh thẻ hiện tại
    .label = Bật/tắt âm thanh thẻ hiện tại
floorp-custom-actions-toggle-bookmark-toolbar = Bật/tắt thanh dấu trang
    .label = Bật/tắt thanh công cụ dấu trang
floorp-custom-actions-show-source-of-page = Hiện nguồn của trang
    .label = Mở nguồn trang
floorp-custom-actions-show-page-info = Hiện thông tin của trang
    .label = Mở thông tin của trang
floorp-custom-actions-zoom-in = Phóng to
    .label = Thu nhỏ
floorp-custom-actions-zoom-out = Thu nhỏ
    .label = Thu nhỏ
floorp-custom-actions-reset-zoom = Đặt lại thu phóng
    .label = Đặt lại thu phóng
floorp-custom-actions-back = Quay lại
    .label = Quay lại
floorp-custom-actions-forward = Chuyển tiếp
    .label = Chuyển tiếp
floorp-custom-actions-reload = Tải lại
    .label = Tải lại
floorp-custom-actions-stop = Dừng
    .label = Dừng
floorp-custom-actions-force-reload = Buộc tải lại
    .label = Buộc tải lại
floorp-custom-actions-search-in-this-page = Tìm kiếm trong trang
    .label = Tìm trong trang
floorp-custom-actions-show-next-search-result = Hiện từ tiếp theo trong kết quả tìm kiếm
    .label = Kết quả "Tìm trong trang" tiếp theo
floorp-custom-actions-show-previous-search-result = Hiện từ trước đó trong kết quả tìm kiếm
    .label = Kết quả "Tìm trong trang" trước đó
floorp-custom-actions-search-the-web = Tìm kiếm trên Web
    .label = Tìm kiếm trên Web
floorp-custom-actions-open-migration-wizard = Mở trợ lý đồng bộ hoá
    .label = Mở trợ lý đồng bộ hoá
floorp-custom-actions-quit-from-application = Thoát khỏi ứng dụng
    .label = Thoát { -brand-short-name }
floorp-custom-actions-enter-into-customize-mode = Tuỳ chỉnh thanh công cụ
    .label = Mở tuỳ chỉnh { -brand-short-name }
floorp-custom-actions-enter-into-offline-mode = Kích hoạt chế độ Offline
    .label = Kích hoạt chế độ Offline
floorp-custom-actions-open-screen-capture = Mở công cụ chụp ảnh màn hình
    .label = Chụp ảnh
floorp-custom-actions-show-pip = Khởi động tính năng Pip
    .label = Hiện hình trong hình
floorp-custom-actions-bookmark-this-page = Đánh dấu trang này
    .label = Đánh dấu trang này
floorp-custom-actions-open-bookmarks-sidebar = Mở dấu trang tại thanh lề
    .label = Mở dấu trang tại thanh lề
floorp-custom-actions-open-bookmark-add-tool = Mở công cụ thêm dấu trang
    .label = Thêm dấu trang
floorp-custom-actions-open-bookmark-add-toolbar = Mở cửa sổ "Thêm dấu trang"
    .label = Thêm vào thanh công cụ dấu trang
floorp-custom-actions-open-bookmarks-manager = Mở quản lý dấu trang
    .label = Mở quản lý dấu trang
floorp-custom-actions-show-bookmark-toolbar = Bật tắt thanh công cụ dấu trang
    .label = Bật/tắt thanh công cụ dấu trang
floorp-custom-actions-open-general-preferences = Mở tùy chọn chung
    .label = Mở tùy chọn chung
floorp-custom-actions-open-privacy-preferences = Mở tuỳ chọn bảo mật
    .label = Mở tuỳ chọn bảo mật
floorp-custom-actions-open-workspaces-preferences = Mở tuỳ chọn không gian làm việc
    .label = Mở tuỳ chọn không gian làm việc
floorp-custom-actions-open-containers-preferences = Mở tuỳ chọn thanh chứa trang
    .label = Mở tuỳ chọn ngăn chứa thẻ
floorp-custom-actions-open-search-preferences = Mở tuỳ chọn tìm kiếm
    .label = Mở tuỳ chọn tìm kiếm
floorp-custom-actions-open-sync-preferences = Mở tuỳ chọn đồng bộ hoá
    .label = Mở tuỳ chọn đồng bộ hoá
floorp-custom-actions-open-task-manager = Mở quản lý tiến trình
    .label = Mở quản lý tiến trình của { -brand-short-name }
floorp-custom-actions-open-home-page = Mở trang chủ { -brand-short-name }
    .label = Mở trang chủ { -brand-short-name }
floorp-custom-actions-open-addons-manager = Mở tiện ích & chủ đề
    .label = Mở tiện ích & chủ đề
floorp-custom-actions-forget-history = Quên lịch sử
    .label = Quên lịch sử
floorp-custom-actions-quick-forget-history = Quên lịch sử nhanh
    .label = Quên lịch sử nhanh
floorp-custom-actions-clear-recent-history = Xoá sạch lịch sử gần đây
    .label = Xoá sạch lịch sử gần đây
floorp-custom-actions-search-history = Tìm kiếm lịch sử
    .label = Tìm kiếm lịch sử
floorp-custom-actions-manage-history = Quản lý lịch sử
    .label = Quản lý lịch sử
floorp-custom-actions-open-downloads = Mở tải xuống
    .label = Mở tải xuống
floorp-custom-actions-show-bsm = Hiện quản lý thanh lề
    .label = Hiện quản lý thanh lề
floorp-custom-actions-show-bookmark-sidebar = Hiện trang đánh dấu ở thanh lề
    .label = Hiện trang đánh dấu ở thanh lề
floorp-custom-actions-show-history-sidebar = Hiện lịch sử tại thanh lề
    .label = Hiện lịch sử tại thanh lề
floorp-custom-actions-show-synced-tabs-sidebar = Hiện thẻ được đồng bộ ở thanh lề
    .label = Hiện thẻ được đồng bộ ở thanh lề
floorp-custom-actions-reverse-sidebar = Đảo ngược vị trí thanh lề
    .label = Đảo ngược vị trí thanh lề
floorp-custom-actions-hide-sidebar = Ẩn thanh lề
    .label = Ẩn thanh lề
floorp-custom-actions-show-sidebar = Bật / tắt thanh lề
    .label = Bật / tắt thanh lề
floorp-custom-actions-toggle-sidebar = Bật / tắt thanh lề
    .label = Bật / tắt thanh lề
floorp-custom-actions-open-previous-workspace = Mở không gian làm việc trước đó
    .label = Mở không gian làm việc trước đó
floorp-custom-actions-open-next-workspace = Mở không gian làm việc kế tiếp
    .label = Mở không gian làm việc kế tiếp
floorp-custom-actions-show-panel-1 = Bật/tắt trang số 1
    .label = Bật/tắt trang số 1
floorp-custom-actions-show-panel-2 = Bật/tắt trang số 2
    .label = Bật/tắt trang số 2
floorp-custom-actions-show-panel-3 = Bật/tắt trang số 3
    .label = Bật/tắt trang số 3
floorp-custom-actions-show-panel-4 = Bật/tắt trang số 4
    .label = Bật/tắt trang số 4
floorp-custom-actions-show-panel-5 = Bật/tắt trang số 5
    .label = Bật/tắt trang số 5
floorp-custom-actions-show-panel-6 = Bật/tắt trang số 6
    .label = Bật/tắt trang số 6
floorp-custom-actions-show-panel-7 = Bật/tắt trang số 7
    .label = Bật/tắt trang số 7
floorp-custom-actions-show-panel-8 = Bật/tắt trang số 8
    .label = Bật/tắt trang số 8
floorp-custom-actions-show-panel-9 = Bật/tắt trang số 9
    .label = Bật/tắt trang số 9
floorp-custom-actions-show-panel-10 = Bật/tắt trang số 10
    .label = Bật/tắt trang số 10
floorp-custom-actions-open-split-view-on-left = Mở thẻ hiện tại ở màn hình bên trái
    .label = Mở thẻ hiện tại ở màn hình bên trái
floorp-custom-actions-open-split-view-on-right = Mở thẻ hiện tại ở màn hình bên phải
    .label = Mở thẻ hiện tại ở màn hình bên phải
floorp-custom-actions-close-split-view = Tắt chế độ chia đôi màn hình
    .label = Tắt chế độ chia đôi màn hình
floorp-custom-actions-custom-action-1 = Tuỳ chỉnh thao tác 1
    .label = Tuỳ chỉnh thao tác 1
floorp-custom-actions-custom-action-2 = Tuỳ chỉnh thao tác 2
    .label = Tuỳ chỉnh thao tác 2
floorp-custom-actions-custom-action-3 = Tuỳ chỉnh thao tác 3
    .label = Tuỳ chỉnh thao tác 3
floorp-custom-actions-custom-action-4 = Tuỳ chỉnh thao tác 4
    .label = Tuỳ chỉnh thao tác 4
floorp-custom-actions-custom-action-5 = Tuỳ chỉnh thao tác 5
    .label = Tuỳ chỉnh thao tác 5
floorp-custom-actions-rest-mode = Bật chế độ nghỉ
    .label = Bật chế độ nghỉ
##################################################################### Profile Switcher ###############################################################

floorp-open-profile-with-new-instance = Khởi động
    .tooltiptext = Khởi động { -brand-short-name } với hồ sơ này
floorp-profiles-in-use = Hồ sơ này đang được sử dụng.
floorp-profiles-title = Hồ sơ
floorp-profile-manager = Quản lý hồ sơ
floorp-profiles-create = Tạo hồ sơ
floorp-profile = Hồ sơ
    .label = Quản lý hồ sơ
    .tooltiptext = Mở Quản lý hồ sơ
fxa-not-signed-in = Chưa đăng nhập
###################################################################### Private Container ##############################################################
floorp-private-container-name = Riêng tư
floorp-toggle-private-container = 
    .label = Mở lại trong chế độ Riêng tư/ Không chạy ngăn chứa thẻ
    .accesskey = P
open-in_private-container = 
    .label = Mở trong thẻ mới với với ngăn chứa thẻ riêng tư
######################################################################## Split View ###############################################################

floorp-split-view-menu = 
    .label = Mở dưới dạng chia đôi màn hình
splitview-show-on-right = 
    .label = Hiện bên phải
splitview-show-on-left = 
    .label = Hiện bên trái
splitview-close-split-tab = 
    .label = Tắt chia thẻ
######################################################################### Page Actions ###############################################################
qrcode-generate-page-action-title = Quét mã QR bằng điện thoại của bạn
qrcode-generate-page-action = 
    .tooltiptext = Chia sẻ trang này với điện thoại của bạn
######################################################################### Customize Mode ###############################################################
floorp-customize-mode-unified-extensions-button = 
    .label = Nút công cụ hợp nhất
######################################################################### Progressive Web Apps (SSB) ###############################################################

ssb-page-action = 
    .label = Cài đặt ứng dụng
    .tooltiptext = Cài đặt trang này dưới dạng ứng dụng
ssb-page-action-title = Cài đặt ứng dụng
ssb-app-open-button = 
    .label = Mở trong ứng dụng
ssb-app-install-button = 
    .label = Cài đặt
ssb-app-cancel-button = 
    .label = Hủy
floorp-open-manage-ssb-page = 
    .label = Quản lý ứng dụng Web đã cài
appmenuitem-webapps = 
    .label = Ứng dụng Web
appmenu-open-installed-apps-subheader = Chạy ứng dụng Web đã cài
appmenuitem-install-current-page = 
    .label = Cài đặt trang này dưới dạng ứng dụng
appmenuitem-open-current-page = 
    .label = Mở trang này trong ứng dụng đã cài
appmenuitem-contextmenu-open-app = 
    .label = Mở ứng dụng này
appmenuitem-contextmenu-uninstall-app = 
    .label = Xoá ứng dụng này

## Preferences

category-ssb = 
    .label = Ứng dụng Web
    .tooltiptext = Ứng dụng Web
category-ssb-title = Ứng dụng Web
floorp-ssb-title = Ứng dụng Web
floorp-ssb-description = Ứng dụng Web là các trang web có thể cài đặt như một ứng dụng. Chúng có thể mở từ thanh menu của { -brand-short-name } hoặc nút Start của Windows.
ssb-preferences = Cài đặt ứng dụng Web
floorp-enable-ssb = 
    .label = Bật ứng dụng Web
floorp-enable-ssb-with-experimental = 
    .label = Bật ứng dụng Web (Thử nghiệm)
floorp-enable-ssb-description = Chức năng đang thử nghiệm trên Mac và Linux. Được khuyến nghị nên sử dụng tính năng này trên Windows.
floorp-disable-toolbars = 
    .label = Vô hiệu hoá thanh công cụ trong ứng dụng Web
floorp-disable-toolbars-description = Tuỳ chỉnh này sẽ ẩn toàn bộ tiện ích mở rộng và thanh công cụ trên cửa sổ ứng dụng Web.....
ssb-installed-list-title = Ứng dụng web đã cài đặt
ssb-uninstall-title = Gỡ cài đặt ứng dụng web
ssb-uninstall-message = Bạn có chắc chắn muốn xứng dụng Web này ra khỏi { -brand-short-name } không?
ssb-uninstall-button = 
    .label = Gỡ cài đặt
ssb-uninstall-cancel = Huỷ bỏ
######################################################################### Download Notification ###############################################################
floorp-started-download = Bắt đầu tải xuống
floorp-finished-download = Tải xuống hoàn tất
######################################################################### Update notify ###############################################################

floorp-notificationTitle-latest = { -brand-short-name } đã được cập nhật!
floorp-notificationContent-latest = Bạn đang sử dụng phiên bản mới nhất của { -brand-short-name }.
floorp-notificationTitle = Phiên bản mới của { -brand-short-name } đã có !
floorp-notificationContent = Nhấn để tải bản mới nhất.
